### PR TITLE
TGUI hardsync & stuff

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
MAJOR antag backend update
- you cannot bruteforce the pen anymore
- uplink now uses bitflag to lock purchases
- poplock is handled entirely by the buyable uplink items
- tgui antag intro (for selected ones)

## Why It's Good For The Game
tgui: good
faster tooltip code: good

## Changelog
:cl:
add: Antag info panel using tgui for selected antags
code: TGUI hardsync
code: TIMER_DELETE_ME flag for timers
code: wiremod backend (DO NOT ENABLE, FOLLOWUP PR WILL ADD WIREMOD)
tweak: Cryo DOES NOT store the items, instead only drops it as soon as the person "fully cryo"
tweak: Changes on how uplink works. Purchases are now only based on if said uplink has the right flag to purchase an item, rather than using a list to whitelist/blacklist specific gamemodes for it. Also, the purchase items handles poplocking by themselves now.
/:cl:

# item highlight is a pref-verb toggle

### CODE REVIEW

**Comment by keronshb** [comment]
Some stuff might have broken on main.  Examples:

Fix chat now has this weird space:

image

Highlighting is broken/highlighting preferences are broken (ghosts can highlight items again too):

image

Weird lighting behavior:

image

Now to show VS a local that is up to date without the testmerge:

Fix Chat:

image

Item highlighting working:

image

Correct lighting on a vendor:

image

**Comment by keronshb** [comment]
There's also this weird "item category" default thing on live:

image

Looks like it's supposed to be ammo but it's also bundling in other stuff like the minibomb, compact derringer, etc.  It's a mess.

**Comment by TripleShades** [comment]
New behavior for atmos alarms noticed: When the power is turned off, every atmos alarm in the area without power will flash a light on and off.
While not a terrible change, I'm worried that it's very laggy.

**Comment by LetterN** [comment]
> Fix chat now has this weird space:

Feature, tgalert

> Highlighting is broken/highlighting preferences are broken (ghosts can highlight items again too):

Pref tab verb, ghost highlighting **shoud** only appear on their side

> Weird lighting behavior:

Vending machine light masks

> There's also this weird "item category" default thing on live:

Probably items lost their category

**Comment by Putnam3145** [comment]
A lot of vendors simply do not work. They cannot be purchased from whatsoever.

The cryo changes are, to be frank, bad. The only reasonable way to cryo someone who went SSD is now to get an admin to hijack their body and move them in. Dropping all their stuff on the tile lowers the barrier for abuse a huge deal.

**Comment by keronshb** [comment]
Costume Vendors don't work.  You can't buy anything from them.

Apparently the same for Kitchen vendors.

There's also a strange bug where overlays in your inventory stay.

**Comment by DeltaFire15** [comment]
Merge conflicting, therefore untestmerging.

**Comment by LetterN** [comment]
> Costume Vendors don't work. You can't buy anything from them.

You can, id required

> Apparently the same for Kitchen vendors.

same as above

> There's also a strange bug where overlays in your inventory stay.

screenshot please

**Comment by TripleShades** [comment]
> > Costume Vendors don't work. You can't buy anything from them.
> 
> You can, id required
> 
> > Apparently the same for Kitchen vendors.
> 
> same as above

You misunderstand, even with an ID, you cant purchase from vendors unless you're in the right department/have department access now.
So people who aren't in service cant purchase from service vendors.

**Comment by LetterN** [comment]
>quote

yes, found the issue, it was the vending discount optimization that did it, fixed it now

**Pull request merged**
