### PR TITLE
Pretties Box Station Departures

### PR DESCRIPTION
**Pull request by jack-avery**
## About The Pull Request

Makes Box Station departures look nice.

## Why It's Good For The Game

Less eye hurty.

## Changelog
:cl:
tweak: boxstation departures
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Don't really like it. Box departures already tends to get very cramped and people still tend to build bars and stuff there and this only gets in the way.

I don't see how it's eye hurty? It's very plain, but so is the rest of Box. It's a very old map.

**Comment by jack-avery** [comment]
> Don't really like it. Box departures already tends to get very cramped and people still tend to build bars and stuff there and this only gets in the way.

i get this, though i don't see many people complaining about the middle bar on meta, but that's also more spacious. i could just make this more spacious if that's the main issue

> I don't see how it's eye hurty? It's very plain, but so is the rest of Box. It's a very old map.

eyehurty comment made in jest. i like detailed maps. i like kilo

**Comment by YakumoChen** [comment]
Meta departures isn't very well traveled, unlike Box where you see people pop near there pretty frequently. The science window is right outside of it, after all. Meta has better places to set up shop as well, on box it's one of the few relatively open public spaces that isn't somewhere like arrivals where nobody ever goes.

**Comment by keronshb** [comment]
You should post some pictures for preview in the PR.

**Comment by MrJWhit** [comment]
Oh desktop, scroll to the bottom to the checks. Find Map Diff Renders, it's the second option, click details on the right.

Tada:
image

**Comment by keronshb** [comment]
> 
> 
> Oh desktop, scroll to the bottom to the checks. Find Map Diff Renders, it's the second option, click details on the right.
> 
> Tada:
> image

It's a courtesy to put it in the PR.

Anyway I'm not really liking these changes.  There's an arcade machine that "blocks" the intercom, it makes an awkward 1x1 entrance in front of Sec and near maint, seems a tad bit cluttered and it's off center.

Also there's a scrubber and vent missing now too.

**Comment by MrJWhit** [comment]
Scrubber and vent are under the chairs, they're still there.

**Comment by YakumoChen** [comment]
The space extension feels lazy and the decals make using it discouraging for no real reason. 

The wall placements would make more natural sense parallel to room flow rather than perpendicular but I still dont like them either way.

Also the air alarm feels like it was moved to a weird spot blocking traffic flow.

**Comment by MrJWhit** [comment]
...How does an air alarm block traffic flow? It's on a wall.

**Comment by YakumoChen** [comment]
The people standing to look at it will

You'll notice that a lot of APCs and air alarms are nested or out of the way in the public halls because box is a well designed map.

**Comment by MrJWhit** [comment]
I'm so completely lost at the videogame you play where people stop and stare at air alarms because there's something on the wall.

**Comment by YakumoChen** [comment]
If I'm trying to adjust the settings on an APC or air alarm I want it placed somewhere where the flow of traffic isn't causing people to shove me around constantly. Its little touches like that which make the map very organic.

**Comment by keronshb** [comment]
> 
> 
> Scrubber and vent are under the chairs, they're still there.

Are scrubbers/vents typically under furniture?  I don't remember seeing any, but I don't actually know.

And yeah the air alarm placement is a bit weird now.

**Comment by MrJWhit** [comment]
Oh
image
you're
image
right
image
air
image
alarms
image
are
image
out
image
of
image
the
image
way

And yes, scrubbers/vents go under furniture, it's fine.

**Comment by MrJWhit** [comment]
Side note: boxstation is kinda shit when it comes to a lot of maping stuff, the base layout is fine, but the piping, wires, and wall placement stuff is really annoying, you can see in those pictures multiple things on the same wall. Which is bad because you currently can't place two things on the same wall, meaning that it can't be fixed to the way that it was.

**Comment by YakumoChen** [comment]
If that was you being facetious you're doing a poor job because almost all of those examples are good and nested air alarm placements. I can only see a couple which could use some minor movement at best (like placing the one across from the kitchen next to the counter across insteadl

**Comment by MrJWhit** [comment]
They're in the main hallways and next to entrances and exits, it's massively annoying to use them already. They're air alarms, it's always going to be shitty to use them, it's fine.

**Comment by MrJWhit** [comment]
As of a month ago, there were **two APCs** in the morgue.

**Comment by YakumoChen** [comment]
What so you're saying that in addition to being in a spot you can stand where some thug is unlikely to shove you out of the way you can also peek out of a door to stealthily manipulate them?

I feel like that's good game design.

**Comment by MrJWhit** [comment]
What the hell even are you saying.

**Comment by YakumoChen** [comment]
Clearly you're the one that doesn't get it

I'm not talking about the morgue, to be clear.

**Comment by MrJWhit** [comment]
Yeah I don't understand what you said, could you explain it in a different way?

This specifically "What so you're saying that in addition to being in a spot you can stand where some thug is unlikely to shove you out of the way you can also peek out of a door to stealthily manipulate them?"
I don't understand what this is saying.

**Comment by YakumoChen** [comment]
This is a fantastic example of good air alarm placement. You can stand in the yellow tile to use the alarm and be out of the way of the flow of traffic (people are more likely to move diagonally than bump into you)

If you're a traitor you can also stand on the door (marked red) and use the alarm to fuck with it and duck into the bathroom when you're done.

**Comment by MrJWhit** [comment]
Ah, of course, and then you can stand here and then get pushed around by a sec officer leaving their area.
image

Thanks boxstation air alarms. Thank goodness you were intentional masterclass in design, and not haphazard dart throwing that sometimes was nice,

**Comment by YakumoChen** [comment]
You're cherry picking bad examples, sure.

**Comment by MrJWhit** [comment]
There are 4 air alarms on the central hallway. 2 of which you can do what you said. 2 of which you can't.
It's not intentional.

**Comment by YakumoChen** [comment]
A lot of it is, I can find 4 good examples for every one bad you find

**Comment by YakumoChen** [comment]
I hope you know this is easily among the dumbest arguments I've ever been in on github just so you can take completely off topic snipes at the oldest map in rotation.

**Comment by jack-avery** [comment]
what the hell happened here

**Pull request closed without merging**
