### PR TITLE
Roger Roger

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

A new cyborg skin, modeled after the battle droids of a famous galaxy far far away.

## Why It's Good For The Game

Roger Roger

## Changelog
:cl:
add: Rogerborgs
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
In all honesty though, please tell me if I need to make the sprite bigger, or should revise it in general.

**Comment by ForrestWick** [comment]
This is really cool but the sprite should prolly be a bit wider and have a bit more shading (I love the idea though)

**Comment by ghost** [comment]
ur bad
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9815

**Comment by ghost** [comment]
I feel like some of this ain't gonna merge properly, with the drakeborg removal pr having been merged, so I'm gonna make a new pr for this.

**Pull request closed without merging**
