### PR TITLE
DO NOT MERGE THIS I ACCIDENTALLY REMOVED THE BLOOD FILE COMPLETELY

### PR DESCRIPTION
**Pull request by ghost**
whoops

### CODE REVIEW

**Comment by MrJWhit** [comment]
Say an insect loses some blood from whatever, how do you suggest they regain it? There isn't bug blood lying around on the station.

EDIT: Also, use the proper PR format in explaining why it's useful.

**Comment by ghost** [comment]
> Say an insect loses some blood from whatever, how do you suggest they regain it? There isn't bug blood lying around on the station.
>
> EDIT: Also, use the proper PR format in explaining why it's useful.

Synthblood exists and there ARE bug blood bags. (source: I saw some ingame)
If you're really worried, I guess I _could_ make bug blood compatible with regular blood.

EDIT: I changed it to the proper format.
EDIT: Bug blood is now compatible with O blood.

**Review by Linzolle — COMMENTED** [review]
making BUG blood compatible with O blood is wholly unnecessary considering that Lizards and Xeno hybrids exist...

**Comment by TheSpaghetti** [comment]
> making BUG blood compatible with O blood is wholly unnecessary considering that Lizards and Xeno hybrids exist...

just in case

**Comment by ghost** [comment]
FUCK

**Comment by ghost** [comment]
made a new pull request because of accidental blood file deletion

**Pull request closed without merging**
