### PR TITLE
Porting cloaks from Beestation

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Ports of the following PRs:
https://github.com/BeeStation/BeeStation-Hornet/pull/2964
https://github.com/BeeStation/BeeStation-Hornet/pull/2898
https://github.com/BeeStation/BeeStation-Hornet/pull/2769
https://github.com/BeeStation/BeeStation-Hornet/pull/2765
https://github.com/BeeStation/BeeStation-Hornet/pull/2470

## Why It's Good For The Game

I honestly think they look pretty good, fit the overall aesthetic that we're going for.
Note, the CE's sprite goes with the overall CE color scheme, not engineering, also it's animated.
As with most sprites, I have no problem just grabbing one or two things instead of everything, the hard part is making the sprites, not porting.

## Changelog
:cl:
add: New sprites for the CE, CMO, RD, Captain, QM, and HoS cloak.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I like the animated CE cloak, but I'm far more fond of the original color scheme.

**Comment by MrJWhit** [comment]
Remember also that the CEs color scheme isn't the same as engineerings color scheme, it is that mostly white color from the hardsuit and hat-stuff.

**Comment by YakumoChen** [comment]
Yeah but I still like the colors of the original cloak.

**Comment by R3dtail** [comment]
why not make them alt+toggles so that people have options?

**Comment by Friggs** [comment]
I like all the new icons for all cloaks, with the exception of the RD cloak. I like the color, but it looks plain compared to the others considering this is the cloak for the Research director.

**Comment by thakyZ** [comment]
They look very nice. I always thought the captains cloak looked kinda bad with the yellow outline, but now it seems to look very nice

**Comment by MrJWhit** [comment]
> why not make them alt+toggles so that people have options?

Because I don't know how to do that, this is a port.
If you happen to have the code on hand, or can give me the code, I can do that.

**Comment by MrJWhit** [comment]
Moving PR to: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14115

**Pull request closed without merging**
