### PR TITLE
Resprites Regular Lasers (and Practice Lasers)

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
imageadd: Added new sprites including inhands for regular lasers, as well as for the practice variant.
/:cl:

CitLaserPreview CitLaserPracticePreview

This PR will resprite the laser gun, as well as the practice variant. Inhands are included. The Practice laser has a shiny orange body.

CitLaserInhandsPreview
CitLaserPracticeInhandsPreview

Preview in-game:
dreamseeker_Fxhl4w8QSq

In addition, the laser override file in the modular folder has been drastically gutted in anticipation of the removal of the modular folder.

NOTE: There is currently a bug in-game where the regular laser gun WILL NOT display the out of ammo indicator since 4 electric charge will be left over in the power cell after emptying the gun for whatever reason.

All assets included in this PR are licensed under CC-BY-SA unless otherwise noted.

### CODE REVIEW

**Comment by ghost** [comment]
Looks damn nice.

**Comment by lolman360** [comment]
toriate please teach me how to sprite your sprites are better than keek's

**Comment by Thalpy** [comment]
Toricakes a cute

**Comment by Michiyamenotehifunana** [comment]
> toriate please teach me how to sprite your sprites are better than keek's 

Practice and try to follow whoever's style you really like. Keek makes good sprites too, I wouldn't say mine are better, especially since I sprite in a somewhat different style for a certain other codebase.

**Comment by Michiyamenotehifunana** [comment]
Conflicts resolved.

**Comment by silicons** [comment]
i don't like this compared to /tg/'s sprites in general, tbh. this eris?

**Comment by Michiyamenotehifunana** [comment]
This uses Eris' palette but is otherwise an original design of mine.

**Comment by silicons** [comment]
lack of interest from other maintainers + i'm against this

love you toriate but sorry i prefer tg sprites to this. perhaps this could be used for other guns in the future if you are alright with it.

**Pull request closed without merging**
