### PR TITLE
unfucks paramedics access + PDA

### LINKED ISSUE #11223: Paramedic medical locker access
## Round ID:
21647

## Reproduction:
attempt to open a medical locker in medical with a full crew shift paramedic id

### LINKED ISSUE #11224: Paramedic PDA starts unbound
## Round ID:
21646/7

## Reproduction:
spawn in as a paramedic attempt to put your id into the pda watch how you instead bind the pda to you.

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

I did a fucky wucky whilst setting the access.
the discowd team is twying vewy hawd to fix it!

## Why It's Good For The Game
bug man bad
Closes #11223 
Closes #11224 
## Changelog
:cl:
fix: my dumb stupid paramedics
/:cl:

### CODE REVIEW

**Comment by Feasel** [comment]
Not sure about virology being on the list. 

Feels hefty powergamey.

I can understand surgical though. That should be there baseline. 

We have apothecary so no point in chemistry access... It's CMO and Chemist job for that.

**Comment by Detective-Google** [comment]
> Not sure about virology being on the list.
> 
> Feels hefty powergamey.
> 
> I can understand surgical though. That should be there baseline.
> 
> We have apothecary so no point in chemistry access... It's CMO and Chemist job for that.

it's literally just the medical doctor access with maint added on the end; copied verbatim from the file since they didn't like the /tg/ version of paramedic access.

**Comment by necromanceranne** [comment]
Funnily enough tg paramedic don't have medlocker access.

Why? Something something 'only stabilized, no treatment'.

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
Actually scratch off the added access, the job shouldn't be too much of a doppelganger of the M.D. one.

**Pull request merged**
