### PR TITLE
Port'n SMES sprites from Oracle Station

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of:
https://github.com/OracleStation/OracleStation/pull/409

## Why It's Good For The Game

Sprite update for the SMESes

## Changelog
:cl:
tweak: Sprite update for the SMES from oracle
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Ehhhh.... this is just the bay sprite, and it isn't any better.

**Comment by keronshb** [comment]
I feel this loses soul.  The current ones we have feel a lot less square like and that's good.  This just looks like a square.

**Comment by MrJWhit** [comment]
It's also a battery, and believe it or not, large batteries are actually boxes. Plus this is more readable from a quick glance.

**Comment by keronshb** [comment]
> 
> 
> It's also a battery, and believe it or not, large batteries are actually boxes. Plus this is more readable from a quick glance.

It's fine having the SMES not be a box because it's standard for a large battery to be a box, it's a game.  It just doesn't look as good as the current sprite at all.

**Comment by DeltaFire15** [comment]
While in real life yes batteries usually look like boxes, this is indeed a game and the current ones just look better. Closing this.

**Pull request closed without merging**
