### PR TITLE
Rabbit parts

### PR DESCRIPTION
**Pull request by Poojawa**
A mirror of #2200 which is rabbit ears and tail added to the features list for both human and mammals

### CODE REVIEW

**Comment by sirelgate** [comment]
dankeshen

**Comment by Iamgoofball** [comment]
1fe

**Comment by Poojawa** [comment]
It's not heresy if it's canon.

**Comment by Iamgoofball** [comment]
>selfmerging

**Comment by Iamgoofball** [comment]
# >>>>>selfmerging

**Comment by Poojawa** [comment]
Goof pls. This isn't even TG's github fam. take your meds.

**Pull request merged**
