### PR TITLE
Nerfs russian cargo crates

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Removes Alien Tech Crate - No one would ever get/use it
Removes a commit about a crate that will likely never be added
Replaces all mosins and 7.62 with the 10mm surpluse rifle as that is weaker, slower and bulkery to use then a mosin
Added a Russian Sniper crate that DOES have a mosin and 1 spare clip, for 7.5k.
Changes the sprite of ammo box to say 10mm from 9mm
Replaces the 7 clips of 7.62 with 3 mags of 10mm for a rifle, in the ammo tool box

## Why It's Good For The Game

Russian gear has still been a major point of balance were you can get really powerfull guns and armor and more all in 1 crate. The major point is to replace the power gun with a weaker yet still fitting lesser one well keeping the armor for the time being as it is.

## Changelog
:cl:
add: New cargo Russian Sniper crate
tweak: Most Russian Crates now have 10mm Rifles rather then the powerful 7.62 and ammo
balance: Lower amout of mags in the Ammo Tool box as well as replace them with more fitting ammo/sprite
removed: Alien Tech Crate as well as a dead cargo crate that will not be added
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
not sure how i feel about this

**Comment by EmeraldSundisk** [comment]
I would be able to live with this ONLY because the Nagant is still available. I will ask though, these are both under "hacked" items as opposed to emagged, right?

**Comment by Trilbyspaceclone** [comment]
Hidden means you have to emag it
Contraband means you got to multy tool the board.
10mm is 50% less damage then 7.62.

**Comment by Ghommie** [comment]
Pretty sure the ruskie gear nerf is not needed. The alien tech pack removal is good, but I can web edit it in a separate PR.

**Pull request closed without merging**
