### PR TITLE
Removes duplicate definition of games and toys nodes and readds autoylathe

### PR DESCRIPTION
**Pull request by silicons**
Riot foam needs to be addressed but unintended changes that later get marked as "intended" without ANY MENTION IN THE PR THAT DID IT is not acceptable #8660

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I didnt legit know, my bad

Also #9110 fixes this

**Comment by Poojawa** [comment]
all this does is remove arcade games...

**Comment by silicons** [comment]
@Poojawa check the file, it's defined again later :^)

**Comment by Poojawa** [comment]
Right, but, you also say 'readds autoylathe' and that isn't here, nerd.

**Review by nik707 — APPROVED** [review]

**Pull request merged**
