### PR TITLE
TG sync 3/20

### PR DESCRIPTION
**Pull request by Poojawa**
Huge overhauls

VG Lighting is standard. You will want to be at 511.1377 for optimal running.

Most New calls have been changed to Initialize, should be a bit easier on the server.

Most subsystems overhauled again, Maps should load a bit more dynamically, and things should function a tad better.

I'll be cherry picking some open PRs for quick fixes later tonight, so this is just to let ya'll know it's coming. <3

### CODE REVIEW

**Comment by TalkingCactus** [comment]
triple check to make sure there's as few things overwritten as possible 👍

**Comment by Poojawa** [comment]
[23:01:19] Runtime in living/carbon/update_icons.dm, line 38: list index out of bounds
[23:01:19] Runtime in species.dm, line 693: list index out of bounds
[23:01:19] Runtime in living/carbon/human/update_icons.dm, line 257: list index out of bounds
[23:01:19] Runtime in genitals.dm, line 233: list index out of bounds

wew, and the invisibility bug is back again.

**Comment by Poojawa** [comment]
````
[11:06:22] Runtime in , line : bad arg name 'nude'
proc name: update preview icon (/datum/preferences/proc/update_preview_icon)
usr: Poojawa (poojawa) (/mob/dead/new_player)
usr.loc: The floor (35,20,1) (/turf/open/floor/plasteel)
src: /datum/preferences (/datum/preferences)
call stack:
/datum/preferences (/datum/preferences): update preview icon(null)
/datum/preferences (/datum/preferences): ShowChoices(Poojawa (/mob/dead/new_player))
Poojawa (/mob/dead/new_player): Topic("src=\[mob_18];show_preferences...", /list (/list))
Poojawa (/client): Topic("src=\[mob_18];show_preferences...", /list (/list), Poojawa (/mob/dead/new_player))

[11:06:22] Runtime in preferences.dm, line 205: bad resource file
proc name: ShowChoices (/datum/preferences/proc/ShowChoices)
usr: Poojawa (poojawa) (/mob/dead/new_player)
usr.loc: The floor (35,20,1) (/turf/open/floor/plasteel)
src: /datum/preferences (/datum/preferences)
call stack:
/datum/preferences (/datum/preferences): ShowChoices(Poojawa (/mob/dead/new_player))
Poojawa (/mob/dead/new_player): Topic("src=\[mob_18];show_preferences...", /list (/list))
Poojawa (/client): Topic("src=\[mob_18];show_preferences...", /list (/list), Poojawa (/mob/dead/new_player))

[11:10:53] Runtime in update_icons.dm, line 38: list index out of bounds
proc name: remove overlay (/mob/living/carbon/proc/remove_overlay)
usr: Nan Batten () (/mob/living/carbon/human)
usr.loc: The plating (32,22,1) (/turf/open/floor/plating)
src: Nan Batten (/mob/living/carbon/human)
src.loc: the plating (32,22,1) (/turf/open/floor/plating)
call stack:
Nan Batten (/mob/living/carbon/human): remove overlay(30)
Human (/datum/species/human): handle mutant bodyparts(Nan Batten (/mob/living/carbon/human), null)
Human (/datum/species/human): handle body(Nan Batten (/mob/living/carbon/human))
Nan Batten (/mob/living/carbon/human): update body()
randomize human(Nan Batten (/mob/living/carbon/human))
Nan Batten (/mob/living/carbon/human): Initialize(0)
Nan Batten (/mob/living/carbon/human): New(0)
Nan Batten (/mob/living/carbon/human): New(the plating (32,22,1) (/turf/open/floor/plating))
Alisa Hoopengarner (/mob/dead/observer): change mob type(/mob/living/carbon/human (/mob/living/carbon/human), null, null, 1)
/datum/admins (/datum/admins): Topic("_src_=holder;simplemake=human;...", /list (/list))
Poojawa (/client): Topic("_src_=holder;simplemake=human;...", /list (/list), /datum/admins (/datum/admins))
```

@TalkingCactus Active build is on bleeding-edgy, since you're better with UIs/layering systems than me.

**Comment by TalkingCactus** [comment]
I don't see it on bleeding-edgy

edit: git client is being a cunt, nevermind

**Comment by LetterJay** [comment]
Pooj deleted the branch then remade it, so things look out of order.

**Comment by TalkingCactus** [comment]
yeah my git client was still showing the old branch, which I ended up
forking from for a fix I just made for a bug that doesn't exist on that
branch

**Comment by LetterJay** [comment]
``[23:01:19] Runtime in living/carbon/update_icons.dm, line 38: list index out of bounds
[23:01:19] Runtime in species.dm, line 693: list index out of bounds
[23:01:19] Runtime in living/carbon/human/update_icons.dm, line 257: list index out of bounds
[23:01:19] Runtime in genitals.dm, line 233: list index out of bounds``

**Comment by TalkingCactus** [comment]
Yeah my Git client is still pulling from the old branch, it's confused as fuck since it has the same name...

**Comment by Poojawa** [comment]
CitadelStation map brought up to standards now, including the tweaks from Leon.

Armory adjusted, now with plasma/laser rifles, equipment is all pixel shifted for easier theft noticing

**Comment by LetterJay** [comment]
So what's left?

**Comment by Poojawa** [comment]
actually trying to get it to work is what's left. :V I dunno what settings I need to have for this maploader thing.

DD hardlocks after loading the station map.

**Comment by LetterJay** [comment]
Which map?

**Comment by Poojawa** [comment]
All of 'em

**Comment by LetterJay** [comment]
is this ready to be tested live?

**Pull request closed without merging**
