### PR TITLE
SUPER SERIOUS PR! Adds admin gear harness for not fetish purposes!!!

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
meme pr

## Why It's Good For The Game
I'm not a fetish coder
I'm not a fetish coder
I'm not a fetish coder
I'm not a fetish coder
I'm not a fetish coder
I'm not a fetish coder

## Changelog
:cl:
add: Added admin gear harness
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
@dzahlus why do you need this just varedit

**Comment by timothyteakettle** [comment]
what kev said, you can even save and load vv'd items by saving them as a 1x1 map template

**Comment by dzahlus** [comment]
> @dzahlus why do you need this just varedit

> what kev said, you can even save and load vv'd items by saving them as a 1x1 map template

I don't this is just me copy pasting code because someone said it would be funny, dont merge hrnnngh

**Comment by moltoretardo** [comment]
I’m disowning you

**Comment by DeltaFire15** [comment]
Not needed.

**Pull request closed without merging**
