### PR TITLE
Ascent Port Project: Ports the Kharmaan Alates from Bay! [DNM]

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Ports the kharmaan from baystation, a race of crystalline space bugs intended for ghost role purposes down the line. They rely on the assets of #13452 to exist.

In addition to that, their tools, language, hivemind (worldnet) and clothings have been ported and by ported I mean I just had to code it from scratch.

image

## Why It's Good For The Game

Citadel is pretty light on compelling ghost roles currently that don't rely on pure RNG rolls or act as tutorials/gimmicks. These bugs are a step in the direction of adding more compelling ghost roles and interactions with the station. It's also kind of silly that the 2d spess game lacks much in the way of proper aliens.

## Changelog
:cl: Tupinambis
add: A species of crystalline space bugs known as the Kharmaan. 
add: Ascent tools and clothing, and the alate's signature exosuit. 
add: Ascent voc language and the worldnet hivemind fueled by a controller organ.
imageadd: A ton of sprites for the ascent items and kharmaan mobs
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
but what do they do

**Comment by Tupinambis** [comment]
> but what do they do

They are space exploring colonizers essentially, though what exactly they do is fairly open ended. They'll spawn in deep space with a ship and ideally we will get an overmap which would be ideal for em.

**Comment by timothyteakettle** [comment]
cool

**Comment by Tupinambis** [comment]
Closing so I can really do this right.

**Pull request closed without merging**
