### PR TITLE
Epitaph Implant

### PR DESCRIPTION
**Pull request by MalricB**
## About The Pull Request
Epitaph implant:
-17 TC
-Toggleable power using cult's red glowing hand sprite:
    *Can parry once every 3 seconds
    *Can parry projectiles
    *Has a decent amount of wound bonus, but 5 force.
    *If no ghosts accept the epitaph personality, you can reoffer every 3 minutes.
    *Parrying successfully will teleport the user behind the attacker
    *Parrying successfully will play Diavolo's SFX from JoJo's Bizarre AdventureTM
    *Parrying successfully will make the user attack whoever they parried, inducing a critical-class, slashing wound into the target by a 30 damage punch
    *Parrying successfully will disarm the attacker.
    *Parrying successfully will qdel the item, cycling it into cooldown for 30 seconds before it has to be summoned again.
-Will force trait [ Diabolic personality ] into the user's mind

Diabolic personality:
-Variation of split personality trait 
-Both the 'real' and 'fake' personality get a button that allows them to take over every 3 (?) minutes, else they get automatically switched every 10 minutes. 
-Switching to the 'fake' or 'new' personality will lightly modify the user's appearance:
    *Pink-styled hair, if user has no hair, then they'll get one and have it pink
    *User's name will be modified to a randomly generated one to signify a voice change
    *Communication like the ones Guardians/Holoparasites have, but requires the current host of the body to be near an object

## Why It's Good For The Game

funni meme item about jojo

## Changelog
:cl: DeltaFire, CygnusB
add: icons/mob/actions/epitaph.dmi 
soundadd: sound/weapons/Epitaph.ogg
/:cl:

### CODE REVIEW

**Comment by DragonTrance** [comment]
FUCKING  Q U A L I T Y

**Comment by Arturlang** [comment]
Also, did you try literally changing the color var of the things, instead of making proper icons for them that are essentially just colour changes

**Comment by zeroisthebiggay** [comment]
this sounds so fucking dumb

**i love it**

**Comment by dzahlus** [comment]
holy fuck PLEASE merge this

**Comment by BlueWildrose** [comment]
Incompatible with slimepeople when turning your hair pink because slimepeople's hair are set to their primary "skin" color rather than hair color.

other than that, hilarious.

**Comment by MalricB** [comment]
-parry half-works (applies wound but doesn't counterattack)
-thought I made it unable to be picked from brain damage but I guess not

**Comment by Detective-Google** [comment]
would be far better (and more thematic) as a wizard item tbh

**Comment by MalricB** [comment]
> would be far better (and more thematic) as a wizard item tbh

maybe? i'm mostly waiting on the parry rework thing tbh. also can't figure out why the fuck it's not counterattacking at the moment, it only applies the wound + teleport + disarm, no damage dealt

**Comment by DeltaFire15** [comment]
Merge conflicting.
~~also probably needs saids stuff fixed ee~~

**Pull request closed without merging**
