### PR TITLE
Medical smartdarts.

### PR DESCRIPTION
**Pull request by Thalpy**
[Changelogs]: Added new smartdarts and smartdart accessories.

add: 
- Smartdart blowgun that only shoots darts.
- Smartdart, a dart/syringe that can only inject medicines, and smartly stops the injection 1u below OD level. Once filled, the chemicals cannot be removed until administered into someone.
- Bluespace smartdart, a smartdart with more room.
- Medolier - a belt that holds smartdarts.
The gun and belt have been added to the med vendor, and the darts can be printed with advanced biomed research/advanced bluespace research.

imageadd: All above have respective sprites.

[why]: Basically a weaker/limited syringe gun that can only administer medicines (datum/reagent/medicine) below OD level. It's more finicky and faffy to use, absorbing all reagents in a beaker, with no means of return. Once administer it is applied to a patient. In a direct comparison a syringe gun offers more features and easier use. However, this doesn't harm the patient when they're hit by a syringe, and allows them peace of mind that they're actually being treated and not surprised zombie powdered. Lets pacifists use it too!

### CODE REVIEW

**Comment by yourdoom9898** [comment]
Note: Morphine is a medicine reagent

**Comment by Thalpy** [comment]
> Note: Morphine is a medicine reagent

Hmm, Should I change the code to exclude this? I mean, _it is a medicine._

**Comment by Poojawa** [comment]
this feels really hugbox-y. 

I get that it's meant to be helpful, and it's a decent idea. but stuff that deliberately has no harmful applications just limits options. 

Perhaps allow some means of bypassing the safety checks?

**Comment by Thalpy** [comment]
> 
> 
> this feels really hugbox-y.
> 
> I get that it's meant to be helpful, and it's a decent idea. but stuff that deliberately has no harmful applications just limits options.
> 
> Perhaps allow some means of bypassing the safety checks?

Mm, I was requested to code it that way, but maybe I could make emps do something to them? Not sure how to code an emp clause though, I'll try to dig around when I get time.

**Comment by Thalpy** [comment]
But, if I do that, won't it just be a reskinned syringegun? I'm not sure why you'd use this over that honestly.

**Comment by Poojawa** [comment]
that's literally what it is already.

**Comment by Thalpy** [comment]
I got an idea of what to do when I get back home.

**Comment by Thalpy** [comment]
I can't get the on_emp() to work. I'll see what Kev has to say since he told me to make it unable to OD in response to your concerns Pooj.

**Review by silicons — APPROVED** [review]

**Pull request merged**
