### PR TITLE
Nerfs Ass Slapping, or how a meme PR made me butthurt, or how I'm now resorting to making degenerate PRs such as this since my permaban from Aurora

### PR DESCRIPTION
**Pull request by BurgerLUA**
[Changelogs]: #
:cl: BurgerBB
balance: Ass slapping only works if you're actually behind the target. Ass slapping now respects disarm blocking. You can no longer face/ass slap someone on an intent other than help, unless they are also face/ass slapping.
fix: Fixed ass and face slapping grammar.
add: Adds meh effects for ass and face slapping.
/:cl:

[why]: ass slapping is a mistake

### CODE REVIEW

**Comment by WhiteHusky** [comment]
image
👌

**Comment by Ghommie** [comment]
> 
> how I'm now resorting to making degenerate PRs such as this since my permaban from Aurora

Totally up to you, man. You could always do other kind of PRs, like bugfixing, ports, refactoring.
🤷‍♂

**Comment by BurgerLUA** [comment]
lmao who the fuck fixes bugs

**Comment by Poojawa** [comment]
👋

**Review by silicons — APPROVED** [review]

**Pull request merged**
