### PR TITLE
Adds a lfwb-inspired orbiting pixel + flashing outline animation to the sprint and combat buttons (toggleable via prefs)

### PR DESCRIPTION
**Pull request by deathride58**
## About The Pull Request
This PR does exactly as it says on the tin. Alternative to #11617 

## Why It's Good For The Game

GIF is self-explanatory

Bonus gif: I also added the ability to color this effect

## Changelog
:cl: Bhijn
add: Added a lfwb-inspired orbiting pixel + flashing outline animation to the sprint and combat mode buttons. This can be toggled via the preferences menu, and is completely independent from all HUD themes.
/:cl:

### CODE REVIEW

**Review by silicons — APPROVED** [review]

**Comment by Hatterhat** [comment]
so when do we get combat mode music

**Comment by deathride58** [comment]
wyci (when you compose it)

**Comment by Ludox235** [comment]
Just put hot plates as combat music so evreryone can murderbone thinking they're the dreamer :/

**Comment by Arturlang** [comment]
Could be a teeny bit more obvious, honestly, and doesnt need to bloat our preferences, no reason to.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
