### PR TITLE
Get in the damn robot, Skylar

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Adds "mechsuits", stylized robotics jumpsuits found only in the RoboDrobe. Perfect clothing to pilot mechs in to fight Godzil- er, Colossus.
Sprites were unused, taken from TG.
No digi sprites because I don't have any

## Why It's Good For The Game

Great for when you mustn't run away from the big xeno invasion

## Changelog
:cl: YakumoChen
imageadd: Mechsuits, robotics jumpsuits added to RoboDrobe
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
wait I fucked up one mo

**Comment by YakumoChen** [comment]
Segfault but it compiled on my end so shrug

**Comment by Tupinambis** [comment]
We have far too many clothing sprites that bug out or just disappear because people port stuff without actually adding stuff like digi sprites. Please add digi sprites.

**Comment by YakumoChen** [comment]
I can't sprite. Too bad!

**Comment by lolman360** [comment]
digi sprites are piss easy to make you just make it look like someone with rickets is wearing it

**Comment by YakumoChen** [comment]
This is just a port. If you'd like to prove how easy it is, go ahead and make some

**Pull request merged**
