### PR TITLE
No adrenals for borgs please

### PR DESCRIPTION
**Pull request by BlackMajor**
Simply disables borg sprinting while vtec is installed (and fixes a bug where vtec could be installed multiple times).

### CODE REVIEW

**Comment by Tename** [comment]
Ya, Vtec doesn't even really seem noticeable without sprint and I don't really want to be spamming the Vtec change speed button at the top left instead of just hitting shift.

**Comment by BlackMajor** [comment]
@Tename 
The alternative is I just make sprinting while vtec is installed cost 0 charge.

Which now that I think about it I might do.

**Comment by Tename** [comment]
> @Tename
> The alternative is I just make sprinting while vtec is installed cost 0 charge.
> 
> Which now that I think about it I might do.

that would probably be better, unless you add a easy hotkey for changing vtec speed :/

**Comment by ghost** [comment]
@BlackMajor daily reminder to fix your code

**Review by nik707 — APPROVED** [review]

**Pull request merged**
