### PR TITLE
Field of Vision component.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. Somewhat inspired by Interbay's (which was taken from lfwb), though the code is fairly different, making use of planes and 513 alpha filters.
Extensively tested, it does the job visually, but there is still stuff to do, such as:
- [x] Adding a config to enable/disable FoV.
- [x] Code to toggle the FoV off when dead, being a dullahan (for obvious reasons), or using a camera console, entering closets etc.
- [x] Move some of the code clustering (mostly plane related bug fixes from tg) this WIP in different PRs.
- [x] Make the shadow cone also mask open space (pretty easy but there is a port to do first, see above).
- [x] Make mobs face whicher thing they are pulling regardless of density when moving (unless they have combat mode on). I don't want to add another janky fov plane blocker image for pulled objects.
- [x] Using `visible_atoms`/`get_actual_viewers` instead of `view`/`viewers` where appropriate.
- [ ] Get someone to make a better 180° icon, the current one is basically "blind right eye" state rotated 45° clockwise.
- [x] Documentation.
- [ ] Doing byond forum bug reports for some byond issues I found while working on this that had me backtrack quite a bit.
- [x] Possibly other improvements and tweaks.
- [x] dim the environment (again) to fit the shadow cone visuals.

## Why It's Good For The Game
Mostly flexing on the lag older PRs such as tgstation/tgstation#24304 and tgstation/tgstation#24537 would cause, aided by 513 filters.
Otherwise it's a fairly interesting feature, though tgstation & co have pretty much developed around full 360° vision the whole time (except combat mode, which was ported from interbay), so expect some potential salty tf2 spy gameplay whenever this is enabled.

## Changelog
:cl:
add: FoV component, probably a component.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
This kicks ass and I am fully interested in porting this if it works out.
For visuals you could do something like make the fov shadow grey out the area it's over as well to make it clearer what it is

**Comment by Ghommie** [comment]
Yea, there is already a visual greying out the area the mask is on. EDIT: perhaps you meant making it grey the area akin to the monochromacy trait, if so, yea, not yet.
Also looking toward it, so I get to port any potential improvement this feature may go through on tg.
Though I'd recommend making a simplified combat mode component that let players keep facing a given direction while moving first (iirc tg removed mouse position tracking for efficiency, but it can still work fine with ctrl+WASD imo), this feature may be a bit janky gameplay-wise without it.

**Comment by Vizoplez** [comment]
as taken from OOC
image

**Comment by Ghommie** [comment]
Well, it dunks powergaming a little, so it's a win imo. It can always be tweaked later to be slightly less drastic but just because it can make the game harder it doesn't mean it's a bad feature, and can also be toggled on / off.

**Comment by Vizoplez** [comment]
Alright - so now my opinion

1) this encourages metabuilds like rapier and stealth implant (FUCK) - This is because due to the changes, any fast stealth melee weapon (rapier which sleeps in 3 hits, or sleepy pen, which can be loaded with anything, can be abused and combo'd with the stealth implant due to their low cost for essentially free oneshots.
2) this encourages better gameplay from traitors (good, but stimpack at mach 5 still works), with less murderbone oriented builds, and puts emphasis on things like guerilla gloves and mute toxin, along with custom sleepypen builds. It may also encourage CQC + stealthbox nukies (FUCK)

**Comment by Ghommie** [comment]
Sounds good to me, stealth gameplay was generally quite underwhelming from experience.

On a second note: As per feedback request, I added another shadow cone blocker image (removed the pulled_image one, render targets don't works well on atoms with overlays unless they have the KEEP_TOGETHER appearance flag enabled),
So you should now be able to see adjacent movables regardless of direction, cheers.

**Comment by ShadeAware** [comment]
I sincerely hope this is made into a config option rather than just a set in stone system; this isn't going to go well for anyone at all.

**Pull request merged**
