### PR TITLE
Makes Buzz Fuzz go on a diet

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Buzz Fuzz has been severely toned down in it's ability to make you cripplingly fat
Buzz Fuzz cans no longer contain pure honey. The reagent itself still breaks down into honey (with a minuscule chance)

## Why It's Good For The Game

Buzz Fuzz is a disgustingly ridiculous drink powerful enough to stave off hunger for an entire shift. Not only did it contain honey (which broke down into sugar) but the reagent itself *also* broke down into sugar every tick, and sometimes _even more fucking honey_
Honey itself is a very strong reagent meant to be locked behind beekeeping. Honey is the best chemical in the game for surgery, among other uses (like again, making you fat very quickly).

Buzz Fuzz itself is actually already coded to be  a viable surgery boosting reagent, meaning cans of it can still be used for ghetto surgery. It turns out this drink is already great without the honey.

Finally there's incentive to actually drink more than a sip of the damn shit at a time. Did you know Buzz Fuzz has an addiction threshold? It's too bad crew became a cripplefat long before they ever had a chance to reach it.

## Changelog
:cl:
balance: To lower production costs, Buzz Fuzz is now manufactured with Real™️ Synthetic honey.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I'd recommend actually toning down honey itself. It's fairly silly how much sugar it breaks down into. I'd recommend just having it break down into tiny amounts, and at a fairly low probability. Should help with this issue.

**Comment by YakumoChen** [comment]
a problem for another PR. I'm not touching honey except to put it back as a botany-only chem.

**Comment by necromanceranne** [comment]
Fair enough. If anything it cuts down on the drink being too good as an easy heal in the field, even despite the fat bloating.

**Comment by Trilbyspaceclone** [comment]
Good changes.

**Pull request merged**
