### PR TITLE
help intent is no longer bypassing versus stuff that blocks

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

like reactive teleport armor and riot shields

## Why It's Good For The Game

funny thing, probably testmerge though because I feel like this isn't the best idea but uh, something something RD getting spaced by teleport armor funny.

and the whole "OFFICER I WAS ONLY TRYING TO HUG YOU" if you try to hug someone with a riot shield.

## Changelog
:cl:
tweak: check_shields can block help intent again.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I do not see why this is necessary.

**Comment by Detective-Google** [comment]
this probably fixes ctrl click bypassing the block on grabs too yeah?

**Comment by silicons** [comment]
@Detective-Google it does??

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
No, it doesn't. This only concerns the `help_shake_act` proc.

**Pull request merged**
