### PR TITLE
Contractor kits are now poplocked to 30.

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

Main's security state is pitiful now, lowpop isn't ready for something designed to be powerful in 1v1 with potential for snowballing. 

## Changelog
:cl:
balance: Contractor kits are now poplocked to 30 players.
/:cl:

### CODE REVIEW

**Comment by Kraseo** [comment]
😔

**Review by Ghommie — APPROVED** [review]

**Comment by necromanceranne** [comment]
Is this a meme or what. The contractor has just a sec baton+ and that's it. Unless he's getting contracts and unless he rolled very well on his random items (something like krav or combat medkit). What the fuck is happening where these contractors are getting so out of control that they can become an unstoppable force before anyone can stop them when the station is literally being told 'hey a man with a funne stick is about to go supernova with 30tc+ worth of gear'.

Also it was originally locked to 25 on tg.

**Comment by Detective-Google** [comment]
> Is this a meme or what. The contractor has just a sec baton+ and that's it. Unless he's getting contracts and unless he rolled very well on his random items (something like krav or combat medkit). What the fuck is happening where these contractors are getting so out of control that they can become an unstoppable force before anyone can stop them when the station is literally being told 'hey a man with a funne stick is about to go supernova with 30tc+ worth of gear'.
> 
> Also it was originally locked to 25 on tg.

yeah in essence the problem isnt people buying contractor it's easy to 1v1 some nerd with a stun baton the issue is that citadel players are so apathetic they _don't even call out they're being kidnapped_ and security usually can't deal with them, meaning contractor either ends up getting dunked by a random validhunter or they get 30 free TC because nobody can be assed to stop them.

**Comment by Putnam3145** [comment]
we honestly should be bwoinking people more for being apathetic that way but that would require 1. observer gang ahelping 2. the traitor ahelping

**Comment by silicons** [comment]
@necromanceranne it's more that i've observed with citadel's usual population this tends to be a snowball

i can speak firsthand ~~as part of the problem~~ that on tg if someone tries to snowball on lowpop they're going to get their ass kicked or people will die trying atleast on the majority of the servers (not limited to contractor, i never played with that on tg but tg has people involving themselves because they want to dunk the antag on cit that isn't going to happen).

here if it's 15 pop with 1 sec they're going to get their ass kicked.

the fact that no one but the antag "mains" even has traitor on isn't helping.

i don't want to do this but at this point i see it to be a necessity.

**Pull request merged**
