### PR TITLE
port of wounds part 2

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
more wounds
more fixes
more fun
from tgstation/tgstation#51786

## Why It's Good For The Game
wounds is hip and cool right?

## Changelog
:cl:
add: due to further advancements in medical technology, you can now have holes poked into your body for fun and enjoyment
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
wounds is not hip and cool.

**Comment by Tupinambis** [comment]
Wounds need the RNG removed. The idea of negative effects resulting from taking sufficient damage is not bad, and hell it used to come in the form of slowdown before combat reworks happened.  
  
But with RNG, it becomes frustrating as all hell to play with and against. Will my attack dislocate their shoulder or will it not? Will their attack cause me to bleed profusely or will I be just fine? I can't possibly know because it's inconsistent. It makes it incredibly easy to just blame your losses and pin your wins on the roll of the dice. That can be fun in some games, but this is a game where you can be permanently removed from the round. It's just not fun.

I'd much rather have hard thresholds for effects to take place. That way you know that if you attack with the welding tool on that body part multiple times that hey, after x hits you will do more damage. And vice versa. It could make combat more interesting and tactical, but if you can't PLAN for things because they might just not happen at all, it removes any tactics that could be borne from the mechanic.

As for medical and recovery stuff. I don't LOVE the idea of making wounds hard to recover from without surgery, but honestly that might just be a value adjustment thing, and I'd need to play with it more first to know for sure.

**Comment by timothyteakettle** [comment]
personally against hard thresholds because it would remove the fluid feel of combat and reduce it to 'hit person X times with Y to inflict wound Z' whereas with soft thresholds it's not extremely rng reliant and still fun

**Comment by Ludox235** [comment]
> 
> 
> Wounds need the RNG removed. The idea of negative effects resulting from taking sufficient damage is not bad, and hell it used to come in the form of slowdown before combat reworks happened.
> 
> But with RNG, it becomes frustrating as all hell to play with and against. Will my attack dislocate their shoulder or will it not? Will their attack cause me to bleed profusely or will I be just fine? I can't possibly know because it's inconsistent. It makes it incredibly easy to just blame your losses and pin your wins on the roll of the dice. That can be fun in some games, but this is a game where you can be permanently removed from the round. It's just not fun.
> 
> I'd much rather have hard thresholds for effects to take place. That way you know that if you attack with the welding tool on that body part multiple times that hey, after x hits you will do more damage. And vice versa. It could make combat more interesting and tactical, but if you can't PLAN for things because they might just not happen at all, it removes any tactics that could be borne from the mechanic.
> 
> As for medical and recovery stuff. I don't LOVE the idea of making wounds hard to recover from without surgery, but honestly that might just be a value adjustment thing, and I'd need to play with it more first to know for sure.

I agree. Once I literally bashed someone in the head with a baseball bat like 10 times and they disarmed my bat, hit me once on the head and I got my fucking skull smashed and a concussion.

**Comment by timothyteakettle** [comment]
baseball bats have a negative wound bonus what you're complaining about isn't RNG it's just your lack of knowledge of how wounds functions, things like wound defense values and existing wounds also are factored in when deciding if you're going to receive a wound, one hit on your skull wouldn't break it unless it was a high force weapon or had a high wound bonus, or you had existing wounds, etc

also your head has a base wound defense of 10 meaning you'd have to take /at least/ 45 brute for a dislocation and 60 for a fracture, assuming you had no other things factoring into the equation

editedit: i did the math, got it wrong, did the math again, not surprised you didn't wound them, a wound bonus of -10 and a wound defense of 10 on an item with a low force isn't going to be great

also uh going from soft thresholds to hard thresholds would make it /far/ worse and it'd be easier to have the entire system removed which seems to be what the few people who hate on wounds want, this is because you'd essentially reduce it to things like 'yes a desword always applies a burn on hit and this rapier will always cause a severe cut'

**Comment by timothyteakettle** [comment]
oh also the concussion stuff should be removed because to my knowledge that's both pure rng with no thresholds and not really needed when we have wounds

**Comment by Tupinambis** [comment]
'yes a desword always applies a burn on hit and this rapier will always cause a severe cut'

Which makes the system tool and strategy based rather than haha I rolled the dice correctly. Bay combat is ass, don't give cit bay combat.

I don't know how it'd make the system "easier to remove"

**Comment by timothyteakettle** [comment]
i want to try reduce how rng reliant it is by changing how the injury roll works so it's more reliant on your damage, gonna test out some value changes

**Pull request merged**
