### PR TITLE
nerfs plasma cutters

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request
cuts all plasma cutter damage in half (I'd prefer to make them identical to the tg values but catboy's word goes shrug)

## Why It's Good For The Game
no more printing lasers 10 at a time in cargo

## Changelog
:cl:
balance: plasma cutters are no longer gay
/:cl:
webedit moment

### CODE REVIEW

**Review by silicons — APPROVED** [review]
i will be merging this

rationale: these are meant to be mining tools. this is already far, far more lenient than tg's nerf for it.

if people think these are needed because they want more improvised weapons they can talk with us and design/balance existing improvised weapons themselves, we shouldn't have a mining tool just be a better, short ranged laser gun in close range and in the mech case, a laser cannon that does bruising instead of burns and can dismember.

and for mining purposes, it was never designed for combat anyways. i'm sure you can still use it as such, but you'll be far better off using a KA or crusher.

**Comment by moltoretardo** [comment]
As long as it can still weld and mine the same amounts of minerals this is good.

**Comment by ghost** [comment]
i support this pr. i usually use pka/pcutter dual wielding since it's basically same damage and you have higher dps because no dualwielding penalty

**Comment by necromanceranne** [comment]
I forgot ripley cutters were 40 damage once on tg haha

**Pull request merged**
