### PR TITLE
[TESTMERGE ONLY] System Corruption for robotic species

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
Foreword:
This will **need** testmerging for quite a while before even considering a merge, or I am not liable for any balance issues, oversights, or similar problems.
Feel free to leave (constructive) feedback on this PR or mention me (DeltaFire#7869) on discord, I will need it, considering I can't test this locally in the environment of actual rounds and actual player interactions yadda yadda.
Ideas I'd love to hear things related to:
More ways to gain corruption.
Possibly more _fun_ effects y'all can think of.
Possibly more ways to heal it (maybe borg chargers, like silicons had in their synthetic species doc?)
Maaybe completely decoupling system corruption from health / crit, and having its own threshhold? (unlikely to happen as it'd require a rework / modification of a ton of mechanics / UIs / other stuff)

Anyways, now for the stuff this does:
This PR takes toxins damage, and reworks the way it works codewise somewhat, creating three 'toxins types' any proc that adjusts / modifies toxins damage uses:
TOX_DEFAULT: Normal toxin damage, affects only normal organics, this is the default of adjustToxLoss()
TOX_SYSCORRUPT: Corruption damage that only influences robots.
TOX_OMNI: Default for getToxLoss() and setToxLoss(), used for things that should affect organics and robots, e.g. admin toxdamage modification.

Additionally, adds a new trait (TRAIT_ROBOTIC_ORGANISM), which modifies which tox type someone is affected by, and if handle_corruption() matters for them. Androids, Synthlizards and IPCs have it by default.

Now, what the hell is system corruption?
Robotic organisms now have gained _full immunity_ to any normal toxins damage, be it from breathing toxic gasses, poison, or anything else that causes it. Instead, they have to deal with system corruption: A somewhat rare, hard (or well, slow) to get rid of type of damage, that causes adverse effects over time if allowed to get out of control.

Ways to remove it:
System cleaner, a new chemical made from iron, oil, calomel and acetone. Slooowly purges corruption, mildly toxic for nonrobots, causes corruption instead if ODd (30u)

System purge surgery, a highly complex starting surgery that removes any and all corruption if successful, but requires quite some time to perform and can cause traumas if failed. Knocks the patient out for some time on success, depending on how much corruption was purged.

Ways to gain it:
EMPs cause system corruption, related logarythmical to the severity of the EMP. Up to 11.5 corruption per EMP if hit by the full pulse. In exchange, robotic species take less damage in their limbs from EMPs (half), which reduces the maximum burn damage per EMP from 30 to 15, and also halves their stun duration. Effectively, this reduces the max damage robots take from EMPs from 30 to 26.5. Though, as the corruption gain is logarythmical, corruption gain also does have quite some effect at lower severities, while the burn damage is linear and will be far lower at low severities.

Robots are also highly susceptible to system corruption from radiation (starting at 250 instead of 500 for normal organics), though they are immune to the special effects of radiation like hairloss or vomiting, and can increase their rad resistance to 750 via a implant (ECC System Guard implant), which is available via the advanced cyberimplants tech

Hitting a robots head with a blunt object and rolling the chance to knock them senseless (prob(force)) also causes 5 corruption in them.

Nanite bane heavily interferes with robots and causes 1 corruption per reagent tick, though it is very rare to see used.

Now, what does corruption actually DO?
Well, corruption levels are grouped into 4 categories: none, minor, major, and critical.
At none (<10) nothing happens and you can just go do your normal things.
At minor (10 - 35), you'll experience minor annoyances
At major (35 - 65), corruption will start to cause severely hampering effects
At critical (>65), you will be able to roll the worst effects, such as, but not limited to, more corruption, temporary combined blindness, muteness and deafness, extreme temperature surges, and more _fun_ things.

When not at the 'none' corruption level, 
every 10 seconds, (9 at major corruption, 8 at critical), you effectively roll a d100. If it rolls higher than your current corruption, you got lucky and nothing happens at all. If not, it enters the second phase of the handler:
Depending on your corruption level, it picks one of many possible effects, (one of which in the low category is actually good, and slightly lowers corruption + has a high weight, though it is far less likely to roll once you enter higher corruption levels),
and performs it, leaving a log in log_attack for admins for now (might clutter them a bit, but for now definitively required so people can go 'hey why am I halluscinating to an admin' and the admin can just see 'oh hey it was corruption'). Most corruption events also tell you what is going on, though some have no tell.
Not going to list all the effects here, go look at handle_corruption(), or allow yourself to be surprised by all the _fun_ ways it can mess with you at the _best_ possible times.

Health analyzers / scanners aswell as operating computers have been updated to show system corruption instead of toxins damage if the one scanned uses it
The way it is done for operating computers is mildly ugly, but it works fine and the uglyness isn't visible for any user, plus it's less of a mess than reworking the entire UI.

~~Sleepers are still pending a UI change to show "Corruption" instead of "Toxin" if the one inside is a robot, but I'll do that somewhen soonish.~~
Sleeper UI done aswell, please do tell me if I missed any.

## Why It's Good For The Game
As of now robotic species have a negative (EMPs fuck you over hard) and a neutral speciality (Self-healing if they have a welder and wires, but no healing chems for you and need surgery if past a threshhold), plus a minor positive one (power for food), and some minor buffs while naked (they can still have a belt / pocket slots and don't get ouchies from glass shards on the floor).
This should increase their survivability to thing robots should be immune to anyways (toxins), while adding uniqueness to them dealing with corruption, which actually has effects on you besides 'oh, all damage combined is at 100, guess I'll die'

## Changelog
:cl:
add: Robots (anyone with the robotic_organism trait) have toxins damage replaced with system corruption. See the PR for details.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
The radiation threshold being drastically higher than that of baseline humans is extremely out-of-line, especially when combined on top of immunity to traditional toxloss. It's also fairly unrealistic, considering how poorly most circuitry reacts to ionizing radiation IRL. (To put it in a little perspective, ECC RAM was deliberately designed to counteract the effects of background radiation in the vast majority of cases, where a single ionizing radiation particle ends up flipping a random bit, and guess what kind of RAM most traditional dedicated servers usually have. Background radiation is also the reason why it's usually pretty hard to achieve long uptimes with consumer-grade computer hardware.)
It'd probably make for a far more interesting gameplay experience overall if you opted to take after reality in this case, as in the PR's current state, robotic species realistically don't have to care at all about radiation. In a lot of cases, humans don't really have to pay much attention to radiation warning signs to begin with, and geiger counters usually just act as background noise most of the time. Lowering the threshold for robotic species to instead be below that of humans, like say, 250 rads or so (half of the human radiation threshold), will put them in a state where they actively have to pay attention to radiation signs and geiger counter ticking (as geiger counters start ticking at 100 rads), as it'll only take a moderate dose for them to start suffering ill effects in the form of gradually-building corruption. This would make a far more interesting distinction between humans and robotic species than granting them near-immunity to rads.
If making them fairly weak to rads feels a bit cruel, making a robotic-species-only implant (name it "ECC RAM Module", perhaps?) that bumps the radiation threshold up somewhere above the human radiation threshold would probably be a good way to allow something similar to the PR's current state of robotic species radiation to exist, albeit locked behind sci upgrades.

**Comment by DeltaFire15** [comment]
Hm, a lower safe threshhold for rad damage does sounds like an okay (additional) tradeoff for tox immunity, considering how contamination now spreads realistically and doesn't just spiral to absurd levels as easily, aswell as there not being that many sources for rads in particular.

**Comment by Arturlang** [comment]
@DeltaFire15 Was this concept inspired by cogminds system corruption mechanic? It really reminds me of it

**Comment by DeltaFire15** [comment]
> @DeltaFire15 Was this concept inspired by cogminds system corruption mechanic? It really reminds me of it

@Arturlang Yes, mostly the part about "corruption isn't just a number but instead has actual effects that vary with how corrupted ones system is."

**Pull request merged**
