### PR TITLE
Removes Fetish Content

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removes Fetish Content

## Why It's Good For The Game

Fetish Content on a furry ERP server that is advertised as a furry ERP server where furries have sex disturbs me.

## Changelog
:cl: Tupinambis
del: Fetish Content
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
did the OOC pr bot come back up?
tha's the only reason why you'd do this

**Comment by silicons** [comment]
https://github.com/tgstation/tgstation

**Comment by Tupinambis** [comment]
this PR was closed due to fetish content.

**Comment by PersianXerxes** [comment]
> 
> 
> this PR was closed due to fetish content.

F in the chat.

**Comment by Ghommie** [comment]
Good first PR.

**Review by Ghommie — APPROVED** [review]

**Pull request closed without merging**
