### PR TITLE
The Great Trigonometric Sprite Replacement, Phase 1!

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Added a syndicate exclusive .357. Replaces the original one in the uplink. All other .357s are untouched.
imageadd: added new sprites for crowbars, wrenches, syndicate .357, and eguns
/:cl:

These new sprites will help differentiate our codebase from others while being groovy!

This PR currently changes the following sprites:
1. Crowbar
2. Wrench
3. Syndicate Revolver
4. Energy Gun

This PR mainly serves as an introduction to my art style on a somewhat larger scale. If the reception on  this is good, I shall proceed on to Phase 2 and beyond, which would encompass more replacements, and fun little things like greyscaled bits allowing for random variation.

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]

**Comment by CameronWoof** [comment]
I'm not sure about the bright, colorful stripes on the tools. The wirecutters in particular don't read well; they look spiky and uncomfortable to use. "Blaster" sounds cartoony, not sure why the energy guns needed changing. You say e-gun, everyone knows what you're talking about.

As a final note, the animated "out of power" sprite for the blasters looks extremely busy. It looks like it's "working", not warning that it's out of battery.

**Comment by Michiyamenotehifunana** [comment]
I'll rethink the placement and brightness of the stripes and probably make it so that only certain variants (like the medical wrench) have it. The wirecutters are currently axed from this PR.

Poojawa requested the egun changes, so I'll leave the explaining to them.

**Comment by cebutris** [comment]
I don't know how I feel about the new revolver sprite. It seems like a blob of metal rather than an actual gun.

Plus, I'll have to mirror Cameron's thoughts on the change to "blaster". It just sounds dumb, and everyone will probably keep calling them eguns. Also, changing the names of something is out of scope in a sprite PR, isn't it?

**Comment by ghost** [comment]
You really do pretty great sprites Toriate, and I really specifically like the crowbar. I think the stripes make it look like it could be some fancy space brand tool.

**Review by jakeramsay007 — APPROVED** [review]
These sprites are exactly what we were looking for, code looks good and is modularised.

**Comment by cebutris** [comment]
Alright, this is a lot better now! I still don't see why the syndicate revolver needs a new sprite, it's kind of a nerf (because cap guns and russian revolvers gave plausible deniability and a little bit of a meta break) but it's not a huge deal and I'm not really firmly opposed. 

The only feedback I have is make the medical wrench more obviously medical (the stripes are there but I feel like they might be hard to see- I may be wrong, though!) but that's not a huge thing by any means.

You have my 👍

**Comment by Michiyamenotehifunana** [comment]
The revolver was made this way because several people voiced their distaste for the existing .357 sprite, yet still wanted the classic sprite for gatfruit. I may find a better solution for this in the future, depending on how it pans out on the live server.

I'll try to figure something out for the medical wrench later.

**Comment by Michiyamenotehifunana** [comment]
Alright, everything should be ready now.

**Pull request merged**
