### PR TITLE
Standardizes Roundstart Slimepeople. Re-adds Xenobiological Slimeperson Splitting.

### PR DESCRIPTION
**Pull request by fludd12**
There was no reason to have a roundstart race with that many bonuses. This gives players the ability to still play as slimepeople visually, but if they actually want the coolio slime abilities, they'll have to ask Science.

Meanwhile, it puts our xenobiological slimepeople up to date with /tg/'s, so you horny nerds can finally have one-person orgies I guess.

If you want me to give roundstart slimes a few gameplay changes that won't make them better than humans, suggest away.

### CODE REVIEW

**Comment by fludd12** [comment]
Doesn't actually use new sprites, I'm just a lazy bastard and copied the sprite states from slimes.

**Review by deathride58 — APPROVED** [review]
Since this relies on config updates, this requires Jay to remove `ROUNDSTART_SPECIES slime` and `ROUNDSTART_SPECIES jelly` from the config, and add `ROUNDSTART_SPECIES slimeperson` for this to have its intended affect

**Comment by deathride58** [comment]
Also, careful about the kind of hornet's nest you're kicking here. People complained pretty loud when upstream removed virus immunity from slimes, imagine the kind of screaming that'll come flooding in when roundstart slimes become human reskins.

**Comment by fludd12** [comment]
Perfectly willing to change slimes to be something a bit more than just human reskins, but I want to put them on par with, say, plasmapeople or lizardpeople.

**Comment by jakeramsay007** [comment]
@fludd12 I was just about to begin a semi-large rework of slimepeople as it is. Could you possibly DM me on discord? ChayseRamsay#7729

**Comment by yourdoom9898** [comment]
Is there any way to tell the two slimes apart? Otherwise, you're going to run into slimepeople just being "Medical Malpactice Simulator 2558".

**Comment by fludd12** [comment]
Closing in favor of @jakeramsay007's work

**Pull request closed without merging**
