### PR TITLE
Makes cult sacrifice not permakill people anymore.

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Makes the offer rune sacrifice not permakill people, just gut their bodies, and makes the construct's on death send the client back to the original body.

## Why It's Good For The Game
Its kinda not nice being forever lost because you got caught and sacrificed for just doing your job, and having a mindshield. This gives the possibility of revival, however difficult, due to you loosing a lot of important organs.

## Changelog
:cl:
tweak: Being sacrificed by the cult no longer removes all hope of rescue.
/:cl:

Currently known issues are: If the corpse is decapicated, it sends the mind to the headless corpse, need to figure out how to deal with this, if you know how, kindly tell me.

### CODE REVIEW

**Comment by Arturlang** [comment]
Aware of travis errors gimme a jiffy.

**Comment by Arturlang** [comment]
Properly compiles now

**Comment by Arturlang** [comment]
Travis fails master because of @timothyteakettle probably

**Comment by moltoretardo** [comment]
Won't people just suicide as a construct to get a chance at revival.

**Pull request merged**
