### PR TITLE
Removes the hardcoded species blacklist from mushroompeople (lets us make mushroom people be roundstart)

### PR DESCRIPTION
**Pull request by deathride58**
TAKE OFF THE HARDCODED BLACKLIST. STOP HAVING THE SPECIES BE CLOSED

:cl: deathride58
add: mushroom people are now roundstart on live
/:cl:

### CODE REVIEW

**Comment by DravenPeace1** [comment]
From what i have tested, they are almost alike a golem, having mutant eye that work just like the toggle darkness from ghosts, they don't breath and from what i tried, they take brute damage on space

**Comment by Iamgoofball** [comment]
We make them closed to deter furries

**Comment by Iamgoofball** [comment]
Also because half these are OP

**Comment by GuppyLaxx** [comment]
6 to 14 punch damage, supposedly high stun punch chance, built in martial art, night vision, unique language

yeah that's fine for roundstart

**Comment by Iamgoofball** [comment]
lmao are you high

**Comment by deathride58** [comment]
They can't wear suits, gloves, uniforms, or boots, meaning armor, insulateds, magboots, and being spaceproof are all right out the window. Additionally, they take extra damage from burn sources and additional damage from heat sources. They also move pretty slow. I played a couple of rounds as one on live, and they're pretty terrible when it comes to combat. The only thing they excel at in terms of combat is taking out simplemobs and targets that've been incapacitated, since their harm intent is blocked by their natural martial art. Since they cannot punch human mobs normally unless shenanigans happen to remove their natural martial art, their knockdown chance is more or less irrelevant outside of xenobio or the alien infestation event.

When you take everything into consideration, they're basically a hardmode race just like plasmamen are.

Also, the only reason mushroompeople are hardcoded to be disabled is because TG stopped allowing new species.

**Comment by WallaceShark** [comment]
These guys are just overglorified roundstart golems. Just re-add them as a golem made from mushroom shavings and you'd be good to go.

**Review by silicons — APPROVED** [review]

**Pull request merged**
