### PR TITLE
Custodial clarity.

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

Adds a sign outside MetaStation's custodial closet so it can be found more easily.

custodialclarity

## Why It's Good For The Game

MetaStation isn't played as often as Box Station, meaning players don't get as many opportunities to become familiar with the map. It doesn't help that the /tg/ wiki is outdated:
https://tgstation13.org/wiki/File:MetaStation.png

Being more easily able to find their closet should mean Janitors can get to work more quickly.

## Changelog
:cl:
add: Adds a sign outside MetaStation's custodial closet
tweak: Slight polish
/:cl:

### CODE REVIEW

**Comment by EmeraldSundisk** [comment]
Sweet Jesus that is a LOT of deletions for what was supposed to be a minor addition...

**Comment by Ghommie** [comment]
Still haven't learned to use the mapmerger eh? (or at the least manually run the dmm2tgm script before commiting)

**Comment by EmeraldSundisk** [comment]
I'll try that, mapmerge hasn't worked for me as of late.

**Comment by EmeraldSundisk** [comment]
Is it supposed to give more than just "press any key to continue"?

**Comment by EmeraldSundisk** [comment]
I'm going back to the drawing board with this one, too much broke.

**Comment by EmeraldSundisk** [comment]
I may have gotten it to a better state...

**Comment by Ghommie** [comment]
Sorry, but I heavily suspect this may be reverting some previous map changes and even looked at the latest map diff run to confirm that.
In fact 204+ 242- is more than a bit too much for one sign.

Please reset your master branch to the upstream/master, then make a new branch with the sign change.

**Comment by EmeraldSundisk** [comment]
Seems weird to me too, will look into this.

**Pull request closed without merging**
