### PR TITLE
IC chat word filter

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Ports https://github.com/KeplerStation/KeplerStation/pull/156.

## Why It's Good For The Game
Able to blacklist words such as online speak, slurs, etc. from being said in IC.

## Changelog
:cl: AffectedArc07
add: You can now blacklist words from IC chat via config
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I hear LOL, OMG, and WTF out in the real world all the time. Also were a MRP serb. Thus this is not needed and only serves to limit the interactions between others

**Comment by deathride58** [comment]
Regex is a very expensive thing. Saycode is already incredibly expensive as-is. I really don't see the value in wasting so much performance on something that's very easy to bypass when enforced solely via code, humans will always be _far_ more efficient at enforcing word filters than code. Which we're already able to do just fine.
Placing regex operations in clientside goonchat is also very questionable, as goonchat is currently the biggest drain for clientside performance, and javascript is even worse with regex than byond is.
So yeah, this PR is basically a hard no unless you can turn this into a compile flag. Unless any other maintainers wish to override my decision here, this PR will be closed after the 24 hour mark.

**Comment by cebutris** [comment]
@Trilbyspaceclone those are just the examples, commented out. This doesn't actually filter anything, but allows you to do it in future

**Comment by silicons** [comment]
i don't dislike it because of performance as much as because this is shit admins should be bwoinking for rather than being an automated system a la roblox.
:-1: sorry!

**Comment by Linzolle** [comment]
Just figured I'd throw this up here honestly. It was zero effort and wanted to see what opinion would be.

**Comment by lolman360** [comment]
i see it more used to block slurs than anything tbh
it's just a config

**Comment by nero1024** [comment]
You'd better implement the filter for other inputs like AI laws, borg names, etc.

**Comment by nik707** [comment]
I'm gonna close this for now, I love the idea but it's just too costly. Perhaps if someone came up with a more safe system it could be considered. Thanks for the port, either way!

**Pull request closed without merging**
