### PR TITLE
Pubby xenobiology atmospherics update among other things

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Tcomms scrubbers actually vent to space now. The n2 layer adaptor is now under a window along with the mix to engine loop being located beneath the o2/n2/air tanks. Xenobiology air/scrubbers is now isolated from the rest of the station. The scrubber located in the tiny starboard room before the secure pen is linked to the xenobiology scrubber loop while the vent in there goes to the rest of the station, giving slimes/xenomorphs a chance to escape.

## Why It's Good For The Game
Makes the tcomms scrubber to space actually work (didnt have power before). Atmos no longer spawns with 1 pipe underneath the tiles (n2 tank output. Xenobiology is now logically (mostly) isolated from the rest of the station pipe wise.

## Changelog
:cl:
add: The pubby xenobiology air/scrubber network is now isolated from the rest of the station
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
Why are we isolating xenobio's pipes?

**Comment by bunny232** [comment]
> Why are we isolating xenobio's pipes?

Realism

**Comment by bunny232** [comment]
^ expands the incinerator area a bit to the right so the rwall/vent/rwall can be powered (such as placing a scrubber on the vent to collect tritium)

**Comment by MrJWhit** [comment]
I spy some goofs
image

Secondly, what are these pumps, why is there a pump in the wall, what is that second one going to?
image

Thirdly, why are there still lattices on the flooring with the injector?
image

Fourthly, what even is this pump doing.
image

Fifth goof
image

**Comment by MrJWhit** [comment]
This is just stuff that's visible, did you run any sort of pipechecks for this?

**Comment by bunny232** [comment]
technically everything but the lattice was intentional

**Comment by bunny232** [comment]
^ tcomms starts off with a connected but off pump, xenobiology air system cleaned up , rogue lattice removed.

**Comment by bunny232** [comment]
maybe i was being a bit _*too*_ creative

**Pull request merged**
