### PR TITLE
Abolishes Nanotrasen Dresscode

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Beepsky no longer gets triggered if you are wearing an antag hat

## Why It's Good For The Game

Beepsky was arresting more people wearing (costume vendor) wizard hats than actual wizards.
Beepsky would never arrest actual ops since they wear agent IDs which drop threat level anyhow.

## Changelog
:cl: Yakumo Chen
tweak: Nanotrasen has formally relaxed the... very sparse dresscode guidelines for working on its station. You may now legally wear pointy hats and red helmets once more.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
This PR will stop beepsky from automatically reacting to high-threat antagonists, which makes this a no from me, since the main reason for this PR seems to be to allow crew members to wear the clothes of those antags with no repercussions whatsoever.

**Comment by YakumoChen** [comment]
Is there any reason beepsky needs to be able to beeline wizards? 

This doesnt affect nukeops since beepsky ignores them anyway due to agent ID, so more often than not this will only affect regular crew wearing antag clothes, not actual antags.

 Crew wearing antag items should be a proper IC issue, not a hardcode enforced one.

 As well most wizard clothes are easily obtainable from the costume vendor and this needlessly disallows use.

**Comment by YakumoChen** [comment]
@deathride58

**Comment by Poojawa** [comment]
any wizard that gets caught by beepsky deserves it.

He's so painfully slow to react in the first place, and there are so many escape spells available to a wizard.

**Comment by YakumoChen** [comment]
ill figure something out later.

**Pull request closed without merging**
