### PR TITLE
[WIP]Tools of cooking

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Adds in more cooking tools so that we dont magicly cook everything with are hands!
Re-adds spoons
Adds pots, pans and trays

## Why It's Good For The Game
Adds a bit more items for the cook to use and get rather then any old smuck, the tools are use in a lot of the crafting, making the game still easy for the proper job but harder for people trying to do a 3rd rate cooking show in maints.
Complexity to the cooking job with flavor 

## Photo ref + proof of testing -

image

## Changelog
:cl:
add: Spoons, Pots, Pans, Trays, Muffen Tray, and other cooking tools to the dinner-vender
tweaks: Makes a lot of the cooking needing tools that are harder to come by if your not the cook!
/:cl

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
I mean... is there a point to have them, though? Have we had any issues with people making food outside of gimmicks? And how does this make the cook's life any easier beside effectively add tools to crafting ingredients?

**Comment by Trilbyspaceclone** [comment]
Well the idea of the tools andded in cooking is so that theirs more complexity into the crafting menus
Its not ment to make the cooks life easyer, just more special
helps with emotes
They sure are not going to better melee then a knife!
More crafting in tuned for the further

**Comment by silicons** [comment]
i don't like this tbh

**Comment by Trilbyspaceclone** [comment]
Alright adding them into prolathen/autolathens

**Comment by davidchan13** [comment]
Service tool implant when?

**Pull request closed without merging**
