### PR TITLE
Moves paperwork crafting

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Moves paperwork crafting to the top of the list

## Why It's Good For The Game

Paper work is now easyer to craft rather then scrolling down and clicking you can quickly look at the top and click it. QoL
## Changelog
:cl:
balance: Moves paperwork crafting to the top of the list
/:cl:

### CODE REVIEW

**Comment by Kraseo** [comment]
this doesn't help in the slightest given that you can still hold enter and keep crafting regardless of the ui overlay getting in the way or not

**Comment by Trilbyspaceclone** [comment]
@Kraseo It helps

**Comment by timothyteakettle** [comment]
this is not fixing the issue, balancing stuff around the fact people will abuse a bug is not the solution, fixing the bug is. (also moving the recipe to the top makes no difference)

**Comment by Trilbyspaceclone** [comment]
@timothyteakettle Stops auto clickers and the like, so it helps

**Comment by Arturlang** [comment]
Going to squish this bug since nobody else has bothered to..

**Comment by Arturlang** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11844 will fix the issue this PR is triyng to fix

**Comment by Linzolle** [comment]
bandaid fix, #11844 fixes the actual underlying issue

**Pull request closed without merging**
