### PR TITLE
Adds a peep emote.

### PR DESCRIPTION
**Pull request by BlackMajor**
Literally what it says on the tin.

### CODE REVIEW

**Review by silicons — APPROVED** [review]
git gud nik

**Review by nik707 — APPROVED** [review]
hah ayes

**Review by deathride58 — APPROVED** [review]
*peep

**Review by silicons — APPROVED** [review]
nik btfo tho <3

**Review by silicons — APPROVED** [review]
t

**Review by nik707 — APPROVED** [review]
kevinz has a small foot

**Review by silicons — APPROVED** [review]
*nya

**Pull request merged**
