### PR TITLE
Corrects vending tackler gloves

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Spaces be bad

## Why It's Good For The Game

Code standers say tabs over spaces 

## Changelog
:cl:
code: Fixed tackler gloves using spaces over tabs
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Wow I completely fucken drop the ball on what I was doing

**Comment by CoreFlare** [comment]
bruh vendor gloves are just fine
this is a code cleanup

**Comment by Trilbyspaceclone** [comment]
@CoreFlare YEP I fucken messed up what I was typing is all...
Just a failing brain is all

**Comment by Arturlang** [comment]
Interesting. I used git cherrypick to do this.

**Pull request merged**
