### PR TITLE
Makes Public Autolathe Non Secure

### PR DESCRIPTION
**Pull request by MacaroniCritter**
## About The Pull Request
I like a lot of things in the autolathe that aren't available in the secure lathe, and I don't like going to the public lathe just to realize I have to go to the autolathe inside of cargo to get what I want.

## Why It's Good For The Game
People don't have to break into cargo "AS" much.

## Changelog
:cl:
del: Removed secure from public lathes
:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
That's literally the point of it, to stop people from just making weapons and running away.

**Comment by Ludox235** [comment]
Mfw can't even make a welder or multi-tool

**Comment by MacaroniCritter** [comment]
> That's literally the point of it, to stop people from just making weapons and running away.

It doesn't do any of that, people will literally just break in and move the actual autolathe outside or build an actual autolathe somewhere else, I've seen it so many times.

**Comment by MrJWhit** [comment]
Talk to cargo for a welder or a multitool then.

**Comment by MacaroniCritter** [comment]
Cargos almost always understaffed or non staffed, or to busy making money to give you one.

**Comment by moltoretardo** [comment]
Also asking each round for a welder sounds repetitive and boring when you can do it faster by yourself. It’s not even funny for the cargo tech that has to give welders to all the people that wants one. It’s as bad as if you’d lock the RPD in auxi storage behind cargo’s door. The scienticists tears would be enough to fill the whole station. This is a good qol

**Comment by Arturlang** [comment]
Point is so people cant get welders or multitools as much to break into places, otherwise usually everyone has a full set of tools

**Comment by deathride58** [comment]
just git gud, lmao

**Comment by MacaroniCritter** [comment]
People are going to break into places no matter what you take away from them and by putting welding tools and multitools behind a door all your doing is encouraging more break ins.

**Comment by Arturlang** [comment]
At the least then theyll have to put in some effort and do it obviously by breaking windows, not just by hacking doors, and people might be unwillingly to do so anyways.

**Comment by silicons** [comment]
i see enough reasoning with why we did this in the first place to keep it as is at the moment, sorry.

**Pull request closed without merging**
