### PR TITLE
completely removes penis/breast enlargement effects due to it being completely unmaintained and to be frank awful

### PR DESCRIPTION
**Pull request by silicons**
yeah the funny's over 

- no one's maintaining it, it's deadweight on the codebase and doesn't add anything interesting to the game imo
- the effects are awful to deal with and i just had someone tell me they died of having a normal sized dick
- there's no reason at all to punish people for this outside of "funny" but honestly if someone runs around the halls with this that's an admin issue not a code issue

### CODE REVIEW

**Comment by YakumoChen** [comment]
Didn't we only just now merge a PR that _is_ maintaining it?

**Comment by BlueWildrose** [comment]
I mean, that was me but, honestly I don't really care if ERP-focused mechanics have their 'realism' part taken away because it's not really meant to be a central focus to the primary game to begin with.

This also means that someone can't just grief someone who had breast expansion enabled but received nonconsensual chemicals. Considering the direction Cit-code is going in, that sort of stuff probably is reserved for a different server who put emphasis on the erotic (and hyper) part of it.

**Comment by LordSaladin** [comment]
so no more clearly labled drinks that turn  you into a guy/girl

**Comment by BlueWildrose** [comment]
> 
> 
> so no more clearly labled drinks that turn you into a guy/girl

The code doesn't change the overdose response to succubus milk/incubus draft, so you can still turn into a girl or guy with the two chemicals it looks like.

All this does is remove the slowdown or blood loss associated with having overly huge dick/tits.

**Review by DeltaFire15 — APPROVED** [review]
This status effect is leaving. Goodbye.

**Pull request merged**
