### PR TITLE
energy bola nerf - reduced breakout time (6 sec -> 2.5), deletes on remove

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title:
- energy bola breakout time reduced to 2.5 seconds
- ebola "shatters" on break (do_sparks and qdel)
## Why It's Good For The Game
"i have fun when i am bola'd for 6 seconds" said nobody ever
## Changelog
:cl:
balance: Energy bolas now take 2.5 seconds to remove and dissipate on removal.
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
> 
> ## About The Pull Request
> 
> see title:
> 
>     * energy bola breakout time reduced back to 2 seconds, like it had before
> 
>     * ebola "shatters" on break, spawning "fragments" that delete themselves within a second or two
> 
> 
> ## Why It's Good For The Game
> 
> energy bolas used to have a 2 second breakout time but then they were changed to not be energy snares so they could be caught but this basically brings back that bit. if i bothered to test my code. i should do that.
> ## Changelog
> 
> 🆑
> balance: Energy bolas now "shatter" and become unusable once removed.
> /🆑

Hatter, they were 6 second breakout time before they were uncatchable.  So they were always at 6 seconds AND being uncatchable for the longest time.

The only line of code I removed was this:

/obj/item/restraints/legcuffs/bola/energy/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
	if(iscarbon(hit_atom))
		var/obj/item/restraints/legcuffs/beartrap/B = new /obj/item/restraints/legcuffs/beartrap/energy/cyborg(get_turf(hit_atom))
		B.Crossed(hit_atom)
		qdel(src)
	..()
	
Which is what prevented them from being catchable.  They've always been a 6 second breakout time, which was REALLY nutty.

Out of curiosity, are these still going to be uncatchable?  Even 2 seconds in a fight is really annoying to have a slowdown that's completely not counterable.

**Comment by Hatterhat** [comment]
> Out of curiosity, are these still going to be uncatchable? Even 2 seconds in a fight is really annoying to have a slowdown that's completely not counterable.

okay first of all if you ever fill the whole damn reply box with an entire PR body i'm gonna kick your ass
second of all, they'll still be catchable. or at least they should be.
**the only reason they were uncatchable was because they deleted themselves and applied the cyborg energy snare in lieu of the bola itself on throw impact**
the borg esnare had breakout time of 2 seconds so this brings it back more in line with what it was before afaik

**Comment by moltoretardo** [comment]
I knew I wasn’t crazy! God I’ve been arguing with people over the duration of the bola resist being 2-3 seconds before. Thank you Hatter for this quick sanity regain.

**Comment by keronshb** [comment]
> 
> 
> I knew I wasn’t crazy! God I’ve been arguing with people over the duration of the bola resist being 2-3 seconds before. Thank you Hatter for this quick sanity regain.

Believe it or not they were at 6 even when I touched them.

**Comment by Hatterhat** [comment]
well fuck it we're nerfing them anyway

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
normal bolas are 3.5 secs breakout, so lets say 2.5 or 3 seconds for the energy bola and this is good to merge imo.
Considering movement-inhibiting stuff is pretty strong with our current combat system

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
