### PR TITLE
Remove Explosive Lances

### PR DESCRIPTION
**Pull request by Psody-Mordheim**
## Why It's Good For The Game
Alright, lets not beat around the bush and just admit Explosive Lances are god's wrath made manifest in an easily craft-able 1 click win button, which kills/gibs you 90% of the time, and even if they miss the embed chance it blows up next to you which still kills whoever you tossed it at.

Literally just learn to use grenades instead of the "haha you can't run away from something that is embedded in you bombspear.".

Now before you say, "Wow Von Carstein nice salt PR."
I am only doing this because I explicitly dared after a discussion about bombspears with someone and I fully expect this to get closed with 'bruh just make an actual nerf instead of deleting them entirely'

"But why did you remove spear warcry if this only about bombspears?"
Because literally only bombspears use the warcry so I felt dumb if I left the warcry in if I didn't delete that too.

## Changelog
:cl:
del: Removed Bombspears
del: Removed Altclick Spear Warcry
imagedel: Removed Bombspear Icons
/:cl:

### CODE REVIEW

**Comment by Sishen1542** [comment]
move warcry to spears in general, removing it is dummy

**Comment by silicons** [comment]
can you guys stop making prs because people dared you to jesus christ

**Comment by Trilbyspaceclone** [comment]
Oh hey a good pr. Shame it will never get merged...

**Comment by Psody-Mordheim** [comment]
> move warcry to spears in general, removing it is dummy

Literally nothing else uses warcries and if you want to say stupid shit while hitting people you need to setup your leet gamer skills and just copy paste stuff into chat quickly :^

**Comment by deathride58** [comment]
"I made this PR because I was dared"
That ain't a reason to blindly remove shit, mate.

**Comment by Psody-Mordheim** [comment]
> That ain't a reason to blindly remove shit, mate.

Explosive lances are incredibly cheap imbed grenades what purpose is there to keeping them besides their 1 click 1 win ability, unless you think something that just qdels everything a skillful tool.

**Comment by necromanceranne** [comment]
I didn't dare him, I told him to to both stop abusing them while complaining about them being overpowered, and if he is only going to abuse them because they exist, he should take the effort to fix what he already knows to be a problem. Bomb spears are a nuclear answer to everything because they literally can qdel everything, or at least instantly kill it. We have megafauna using bomb damage caps for a reason. The upper limits on them are insane.

Being able to lob that into someone and detonate the bomb remotely with no way to pull it out isn't much better to them detonating on impact like they did before. 

They are the great equalizer. But does having an answer any problem be as easily acquired as a trip to chemistry and breaking a window really a good thing to have in the game?

It's not a kneejerk, it's sanity checking literally infinite damage.

**Comment by Detective-Google** [comment]
'sanity checking' = completely removing an item, I don't buy it. I've said over and over the correct way to bring bombspears into line without completely kneecapping them is to make them detonate on melee only, and completely ditching the pre-prime effects. You could also nerf the spear embed chance from the (90%!!!!) very high chance it currently has, and or increase the stamina costs required to throw them, nerf the throw speed, or the range, but you choose to do none of these things. you choose to try and outright remove them because you can't be bothered to implement or even try a fix. miss me with that.

**Comment by Linzolle** [comment]
do something more than just remove the item, fix the actual issue

**Pull request closed without merging**
