### PR TITLE
nuke explosion is 512 dev which is actually less laggy than heavy + light

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

title

## Why It's Good For The Game

round's over anyways why do we care about not erasing everything and making it realistic

## Changelog
:cl:
tweak: nuke explosion is now full dev radius for anti lag purposes
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
travis broke

**Comment by Owai-Seek** [comment]
How will this affect things if the nuke is dumped on lavaland?

**Comment by silicons** [comment]
lavaland gets erased because it's a nuke

**Comment by silicons** [comment]
oh hey i just checked
nukes don't end round if not on station and it's not nukeops i guess? maybe? shrug
the edge case of someone nuking lavaland is a whatever to be honest.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
