### PR TITLE
[wip] Nerfs Mining Health points, damage, armor penitration, armor, points and more by 25% - always rounding down

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
All Hp, damage, armor, AP, and other forms of damage/health have been nerfed by 25% always rounding down

## About The Pull Request

Every number that has to do with damage, health or any thing inbettewn has been nerfed by 25%
Paradox storge also has been hit by the 25% nerf
## Why It's Good For The Game

De-fags miners without anyone really able to feel it. This makes armor that gets is gotten by miners less powerfull, meaning that if they deside to hand out tons of gear or even just antag hunt they are less of a massive threat that cant be stopped.
Note that all their miner healing items untouched, as well as more support-related items such as belt, janitor, and cores. Theirs no way to fairly nerf those by 25% without ruining its gimmic.
Note that also the suit add on is not nerffed nor is miner loot from their crates, just drops from megafuna and funa alike. Plants are also not nerffed

Note - Add ons as is things you add onto your jumpsuit or explore suit such as bone neckless or golith plates, those have not been nerfed/touched

# I also Think this should be test merged for a bit to see how we feel about it rather then closing it in a hour.

## Changelog
:cl:
balance:Nerfs Mining Health points, damage, armor penitration, armor, points and more by 25% - always rounding down, excluding healing items 
nerf; Paradox bag holds less by 25%
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
People really need to stop telling me "wyci"

**Comment by Hatterhat** [comment]
you made so many things worse than standard equivalents that this shouldn't even be considered

**Comment by Trilbyspaceclone** [comment]
Can you name one?

**Comment by silicons** [comment]
the pr will be closed at 24 hours unless a maintainer disagrees because:
1. it's not atomic at all there is no possible reason you can have to convince me this all needs to be one pr
2. the definition of low effort right now is "just axe everything with 25% without individual reasoning". some things aren't even that powerful, what are you doing?
3. consider that not all the issues are solved by just numerically nerfing
4. here's also where i ask you how much you've played the game and what you are hoping to accomplish by this. many of their gear aren't even good against antags other than marginally. there is absolutely ways to nerf healing/etc. 
5. give actual individual reasoning for nerfs to individual things or tight collections of things. because the only reason i see here is "massive threat that can not be stopped" and this pr isn't going to address that in a sensical way.

just stop. if you really care about this go through some higher effort and don't make one single pr that just numerically cuts everything down by 25% because this is frankly somehow more disgusting than just removing every recipe from miners period.

oh yeah and obligatory "go play the game and collect observations from playing or at least watching the job play because i seriously want to see your playtime + observer stats these days as i doubt you have any clue what you are doing to the majority of the items in that you wouldn't know how much they're used/how powerful they are when used."

**Comment by Iroquois-Pliskin** [comment]
Man, this is the 2nd absurd nerf PR related to Mining in the last like 3 days. Why are you even nerfing some of these things?

**Comment by Detective-Google** [comment]
ok this is great and all but `w h y`

**Comment by Trilbyspaceclone** [comment]
Well mining, its unnoticeable.
Well on station it just closes the gab from miner gear to station gear.

**Comment by ghost** [comment]
sorry but
just because you can code it
doesn't mean you should

**Comment by Trilbyspaceclone** [comment]
This is before its time

**Pull request closed without merging**
