### PR TITLE
Ports a new janiborg sprite from TG.

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
TG has a janiborg sprite they have temporarily added.
https://github.com/tgstation/tgstation/pull/63619

It fits with what citadel has so why not add it here on a more permanent basis. May want to test merge this one in case there any  issues as its a tall instead of wide sprite.

## Why It's Good For The Game
Make borgos look good.

## Changelog
:cl:
add: A new sprite has been added for service modules.
/:cl:

### CODE REVIEW

**Comment by TJatPBnJ** [comment]
your changelog has an error, its not a service borg

**Comment by shellspeed1** [comment]
I'll double check that, however on the cit codebase service and janiborgs share the same set of modules meaning there shouldn't be a difference..

**Comment by shellspeed1** [comment]
> your changelog has an error, its not a service borg

I'll double check that, however on the cit codebase service and janiborgs share the same set of modules meaning there shouldn't be a difference..

**Comment by shellspeed1** [comment]
Confirmed its fine

**Comment by desertmote** [comment]
hello! im the spriter. id like to request this is halted until the borg is completely rolled out in Skyrat. this is a development version sent to TG for a gag. it does not include the readme or watermark icon_state.

im completely ok with it and the other modules being ported when i make the final release, thank you.

**Comment by zeroisthebiggay** [comment]
> it does not include the readme or watermark icon_state.

ah-shit-here-we-go-again-ah-shit

**Comment by desertmote** [comment]
im not adding troublesome licensing or anything alike. i just wish to include a way to have my alias and galleries traceable from the workfile. note how im not credited in this PR either, it would be very unfair to me the artist if repositories took work completely unsigned and uncredited. 🙂

**Comment by shellspeed1** [comment]
I'm sorry but I did not notice that you had made the sprites in the original PR. I didn't credit you and thats a failure on my part since I did not notice it in the original PR from TG. That being said considering the problems we have had with copyrights and sprites from skyrat this is clearly a huge problem just ready to explode. Considering my initial fuckup and everything else the only sensible thing is to close this PR.

**Pull request closed without merging**
