### PR TITLE
Two new candy and sprite tweaks

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
New candy - A new vender lollipop, looks surgery and spirally
Sugar bomb! - Blueberry flavoured 
Tweaks sushi sprites to be better
Tweaks villian sprite for cake to be better
## Why It's Good For The Game

Fancy vender only candy that are different are always nice
Better sprites form age old icons are cool

## Changelog
:cl:
add: New candy - A new vender lollipop, and candy drop
tweak: sushi sprites to be better, as well as vanilla cakes
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
We..... already have lollipops in the vendor... the only thing this adds is the candy drop and we already have a candy item too (which is also in the vendor)

The sprites are pretty bad (and the sprite changes are almost meaningless) so I'm giving this a 👎

**Comment by Trilbyspaceclone** [comment]
@YakumoChen we have 2 different lollipops in the vender already

**Comment by YakumoChen** [comment]
> @YakumoChen we have 2 different lollipops in the vender already

Yes thank you for stating a second time why we dont need more

**Comment by Linzolle** [comment]
This doesn't really seem very necessary, to be honest.

**Comment by Trilbyspaceclone** [comment]
> This doesn't really seem very necessary, to be honest.

Why does somthing have to be necessary?
Its just more candy in a snack/candy themed vender
When I added the coco bars, that wasnt necessary nor was the spider pops I added in.
Not everything should be 100% necessary to add into the game, some stuff can be just for fluff or fun

**Comment by DeltaFire15** [comment]
Mh I think we have enough lollipops in vendors. Considering noone else merged this, I think it's safe to close.

**Pull request closed without merging**
