### PR TITLE
Brings back the syringe gun from dart gun

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Brings back the syringe gun as a roundstart item on the map.

## Why It's Good For The Game

With the introduction of the economy, two dart guns can be obtained from every individual small NanoMed machine on the wall. The syringe gun can't actually be obtained in-game at all, only a rapid fire syringe gun can get researched, sometimes.

## Changelog
:cl:
balance: Replaces dart gun with the syringe gun as a map item.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
hydro can make dart guns

**Comment by MrJWhit** [comment]
I... am deeply and actively confused what happened with those filechanges.

**Comment by DeltaFire15** [comment]
Pretty sure the syringe gun removal from the maps wasn't just to make dartguns more available, but more about discouraging chemwarfare

**Comment by TheObserver-sys** [comment]
Blowdart Guns are the epitome of terrible though. A ranged weapon with a delay so long that everyone in a 5 Z-Level radius knows what you are doing if you try to use it. A return of the syringe gun wouldn't be a terrible idea.

**Comment by timothyteakettle** [comment]
lock them behind a tech node if not already, making them available roundstart on the map is an awful idea, also rapid fire syringe guns not being researched commonly is not a reason to re-add the syringe gun to the map

**Comment by TheObserver-sys** [comment]
I'll agree, if not round start, an earlier node for medical would be a good idea. Perhaps on Med E-Tools?

**Comment by MrJWhit** [comment]
I'm fine with having syringe guns available with a more basic technode and having them more delayed, it's just that there's physically no way to get a normal-ass syringe gun at all in the game. Just the upgraded version, the hugboxed version, and the ghetto version.

**Review by silicons — CHANGES_REQUESTED** [review]
advanced biotechnology

**Comment by MrJWhit** [comment]
I'm just going to close it because, not going to lie, I forgot about this PR and I can't think of a reasonable way to update all of the maps without just... redoing the PR.

**Pull request closed without merging**
