### PR TITLE
Removes the Reinforcement Chromosome from Genetics.

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

This removes the Reinforcement Chromosome from Genetics.

## Why It's Good For The Game

Mutadone is genetics only counter and thus it's also a counter to Hulk, Space Adaptation and Thermals.  By finding and adding the Mutadone Proof to any trait, it makes genetics a pretty unstoppable powerhouse.  You can also do some shitty things like "permanently" making people monkeys or "permanently" muting people.

## Changelog
:cl:
balance: Removes the Reinforcement Chromosome from Genetics.
/:cl:

### CODE REVIEW

**Comment by rossark** [comment]
y tho, hulk is really not that good and actually better if you can mutadone it yourself and making it mutadone proof wont make it unstoppable when the person loses it when they go in critical condition anyways.. thermal vision has no sprite tell and if someone suspects you have it they're better off using a flash(bang) instead, it's a really strong mutation but it already has a weakness and mutade proofing it doesnt really fix that or make you unstoppable . SA is a very good power as well and without any downsides too so making it mutadoneproof is prtty nice but cold and low pressure protection alone also doesnt turn you into a unstoppable powerhouse either. There's also a big time investment in the whole process too, the geneticist has to get the mutation and then find the right chromosome for it which is all rng of course and this is just to stop someone grabbing one of the many dartguns in medbay, some mutadone and shooting u with no effort when all they need is to hit 1 dart of many with a single unit of it...maybe more if the victim has spare needles.. as they should though. 
"permanent" negative mutations dont really bring anything new.. its not any more or less shittier than pacification..giving someone metal organs  or implants etc...the alternative is usually worse and this still gives the victim a chance to fix it if they're creative or have a buddy to help.

**Comment by keronshb** [comment]
> 
> 
> y tho, hulk is really not that good and actually better if you can mutadone it yourself and making it mutadone proof wont make it unstoppable when the person loses it when they go in critical condition anyways.. thermal vision has no sprite tell and if someone suspects you have it they're better off using a flash(bang) instead, it's a really strong mutation but it already has a weakness and mutade proofing it doesnt really fix that or make you unstoppable . SA is a very good power as well and without any downsides too so making it mutadoneproof is prtty nice but cold and low pressure protection alone also doesnt turn you into a unstoppable powerhouse either. There's also a big time investment in the whole process too, the geneticist has to get the mutation and then find the right chromosome for it which is all rng of course and this is just to stop someone grabbing one of the many dartguns in medbay, some mutadone and shooting u with no effort when all they need is to hit 1 dart of many with a single unit of it...maybe more if the victim has spare needles.. as they should though.
> "permanent" negative mutations dont really bring anything new.. its not any more or less shittier than pacification..giving someone metal organs or implants etc...the alternative is usually worse and this still gives the victim a chance to fix it if they're creative or have a buddy to help.

Thermal Vision from genetics does not have a flash weakness.  My PR did not get merged so it has no downsides.

This is more of a balance check so that genetics ONLY counter isn't gone.

**Comment by rossark** [comment]
o shid my bad then, wew kinda weird it doesnt have flash weakness and unless theyre being super obvious about it its also impossible to detect without a scanner so ppl wont even know to use mutadone b4 its too late

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Preferrably just remove the reinforcing chromosome, leaving in code-support for mutadoneproofing, just without a way to get it as geneticist (might be useful for some stuff; who knows)

**Comment by keronshb** [comment]
> 
> 
> Preferrably just remove the reinforcing chromosome, leaving in code-support for mutadoneproofing, just without a way to get it as geneticist (might be useful for some stuff; who knows)

Should be good to go now.

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
