### PR TITLE
Makes hivemind free.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Makes hivemind free.

## Why It's Good For The Game

No one likes having to readapt because nobody else took hive-mind. 

## Changelog
:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Hivelings were pretty cancerous, which is why hivemind got locked behind a dna point lock. It was impossible to actually balance lings at all, because every single ling round, most of the lings would start grouping up roundstart, and lings would immediately try to rat everyone out who spoke in hivemind. So every single changeling round ended up playing out extremely predictably, turning to chaos in mere minutes of the round starting because it immediately became a 5v40. Hivemind also caused quite a few issues with the ling vs ling objectives, as lings ended up completely ignoring their objectives in favor of just causing chaos due to the tendency for players to just immediately group up when handed an exclusive antag chat on a silver platter.
Lings still have access to tools to find other lings (and also have the ability to grant hivemind access to others!), which means they're still more than able to group up if they want to put the effort towards it, but the 1 dna point cost is more than enough to stop a *lot* of the cancerous behavior that previously occurred.

**Comment by MrJWhit** [comment]
Any actual reason why didn't you test your code or follow the PR guidelines for writing up the PR?

**Comment by TheSpaghetti** [comment]
I dunno how.

**Comment by ghost** [comment]
> Any actual reason why didn't you test your code or follow the PR guidelines for writing up the PR?

I dunno how to test code.

As for PR guidelines, this is really simple sooo....

edit: it follows PR guidelines now

**Comment by ghost** [comment]
> Hivelings were pretty cancerous, which is why hivemind got locked behind a dna point lock. It was impossible to actually balance lings at all, because every single ling round, most of the lings would start grouping up roundstart, and lings would immediately try to rat everyone out who spoke in hivemind. So every single changeling round ended up playing out extremely predictably, turning to chaos in mere minutes of the round starting because it immediately became a 5v40. Hivemind also caused quite a few issues with the ling vs ling objectives, as lings ended up completely ignoring their objectives in favor of just causing chaos due to the tendency for players to just immediately group up when handed an exclusive antag chat on a silver platter.
> Lings still have access to tools to find other lings (and also have the ability to grant hivemind access to others!), which means they're still more than able to group up if they want to put the effort towards it, but the 1 dna point cost is more than enough to stop a _lot_ of the cancerous behavior that previously occurred.

Regular /tg/ made hivemind free again, why can't we? (And that was before the era of Cobby, when /tg/station wasn't run by awful coders.)

**Comment by Poojawa** [comment]
Citadel != TG

However much certain elements wish to make it.

**Comment by ghost** [comment]
> Citadel != TG
> 
> However much certain elements wish to make it.

Yes, but /tg/ still has good ideas that should be ported.

**Comment by silicons** [comment]
i don't particularly see a need for this.
what should happen is buffs to changeling stealth tools and overhauls based on that.
hivemind is not too expensive.

**Pull request closed without merging**
