### PR TITLE
Miner Table shuffle mark II

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Moves god's eyes to fallen angel loot table thus killing the angel might be more worth wile to do...
Removes spell blade and fire wand from drake/bubble gum table
Replaces fire wand with meat hook
Replaces spell blade with holoparasight
Moves the holoparasight, meat hook and eye of god from spike loot table.
Makes each type of spike and boss have its own type of chest
Their 3 types, magic, armor/weapon, and misc!
These three new types pick almost all the old loot but into different pools making the ones that people like much more clear to get, such as getting lets state ship in a bottle, now you have more odds to get it if you kill the correct spike type! 

This helps combat just flat out mean Rng were you can fight tooth and nail for a golith spike chest and get... A worthless ship in a bottle you already can make with just some bones and now the countless hides you have from killing the spike...

Adds 2 more crates to Arena Shuttle as well as 4-4-4 of each new type of chest

## Why It's Good For The Game

Makes fighting lava land megafuna more worth wile and less of a Well if get lucky with spikes I can just never deal with that and more stable rounds without the issue of 4 holo parasights or other things of that sort just via spike drops that are kinda easy to cheese and such.
This also takes out the frankly overly good fire wand aka 1 hit killer
and the also grate spell blade that nuggets people has 50% block iirc and is amazing.

Spike/Miniboss changes - 
These changes to make each type of boss/spike have its own loot table makes you have a more informed, if you look into it, odds of what to get as well as helps people know/target what kinda mobs they want to fight againts well not really buffing anything other then what tendrils to kill first :P 

For bosses these are a more rng and ontop of Rng if you fight them, you flat out dont know the miniboss you get, sadly I have no plans to make each miniboss have a tell before you spawn it.

I do really really really think these are good change to make. As they are not that nerfing or buffing, just shifting around power to more informed things so that as a player you can strategist better! 

## Changelog

:cl:
del: Removed spell blade, diamond picaxe, and fire wand from lava land loot tables
tweak: Each mini boss now has its own type of crate.
tweak: Each spike has its own type of crate that it pulls its now smaller loot table from
balance: Moved god eye from spike loot table to hard spawn collosses fight
balance: Moved holoparasight from spike loot table to bubble gum
balance: Moved magic meat hook from spike loot table to drake
add: 2 more crates to Arena Shuttle as well as 4-4-4 of each new type of chest
/:cl:

### _**Check out pr #12353 to see commits that dislike this pr.**_

### CODE REVIEW

**Comment by ghost** [comment]
> putting the worst items in the tendril you want to kill the least

at least we're buffing miner powergame. when are we porting skyrat's lavaland changes?

**Comment by Trilbyspaceclone** [comment]
@kappa-sama What do you mean?
I havent seen skyrats do this
I legit stated about this weeks ago... I thought this was my idea

**Comment by YakumoChen** [comment]
He means that you're still just making this easier to powergame for mining, and that this doesn't really add anything good at all for all the same reasons I disliked the first PR

Why would you think that relegating all the most boring/bad items to one specific type of tendril would be a good idea? You're pretty much fucking up all the RNG at this point.

**Comment by silicons** [comment]
image

This is still shuffling paths around with some pixie dust sprinkled on, c'mon man.

> These three new types pick almost all the old loot but into different pools making the ones that people like much more clear to get, such as getting lets state ship in a bottle, now you have more odds to get it if you kill the correct spike type!

Such is the fate of being a gamer who just wants loot. Sometimes ye get lucky, sometimes ye get a gimmick. 

> Removes spell blade and fire wand from drake/bubble gum table

Unironically a good change but maybe do something unique there and also don't bundle it in a PR that was already closed before.

**Pull request closed without merging**
