### PR TITLE
Better stock part sprites maybe

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Maybe makes stock parts in game look less... 2010? Just maybe some better looking spites.
Credit - 
Eris for the colour pallets
MegaMiana for ideas/help/feedback
## Why It's Good For The Game
Something that some people see every shift should look nicer and not from the 19th centenary 
## Changelog
:cl:
sprites: Maybe makes stock parts in game look less... 2010? Just maybe some better looking spites.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Great sprites, thumbs up from me

**Comment by ForrestWick** [comment]
These look good, I like it

**Comment by Detective-Google** [comment]
From Azlan#0852 in the tg discord
image

just the parts 
https://media.discordapp.net/attachments/694611413582348288/743889487373008977/unknown.png

**Comment by Tupinambis** [comment]
these look really nice!

**Comment by MrJWhit** [comment]
These are all great!

**Comment by lolman360** [comment]
old sprites have soul

**Comment by Tupinambis** [comment]
Gonna leave my opinion here, I think the old phasic scanner sprites look better than these new ones. Like the rest though.

**Comment by triplezeta** [comment]
okay so a friend just made me aware of these

and I've gotta be honest

a lot of these could do with pretty heavy improvement and generally don't fit the artstyle of this flavor of ss13 at all
image


let's start with the capacitors
image

All of these capacitor sprites share a common issue of having poorly-done outlines. 
image

The first one looks great by itself; it has a sane perspective and uses its palette well. If this were some kind of stylized game which consistently used outlines like this, this would be fine. The same cannot be said of the other 3 capacitors. 

image

Notably, these capacitors have a, to say the least, strange perspective inconsistent with the first, which the rest are likely based off of, and do not use a high-contrast palette like the first, giving them an almost matte appearance. The saturation is kicked all the way to maximum with these, and there is a distinct lack of hueshifting.

Modified capacitors would look something like this. (Edit: consistency with the shape)
image



Moving on from the capacitors, let's go to the lasers.
image

These share the capacitor's stylized outlines, but are also generally more consistent in quality between the 4 laser variants. 

I would suggest shaving away the outlines like so, and also working on the animation for some of the lasers. The tier 2 and tier 4 laser's animations in particular are the most offputting, as the Tier 2 laser appears to emit light *behind* the actual laser and the tier 4's animation takes far too long.
image
image

On to the matter bins, while the sprite itself is pretty good, the palette is ill-fitting for something like ss13.
image

It's far too blue (and too dark imo) to be in anything outside of something highly stylized like CEV Eris. Additionally, there's next to nothing distinguishing the parts apart other than the lights at the base of the matter bin with the exception of the bluespace matter bin, which has had the energetic animation of the inside of the bin replaced with a slow and boring one and the curve of the inside of the bin removed entirely for a seemingly flat plane.

As for the micro-manipulator and all variants, 
image

I believe these need a redesign. They look very static overall and just don't look like something that would move. Adding a better defined junction for the claw of the manipulator would help with this.



tdlr; hard outlines bad, color choice needs to be looked at again, animations need work, make bluespace parts more energetic in their animations

**Comment by Trilbyspaceclone** [comment]
@triplezeta 
Are we going to use Azlan sprites? Little bit confused on what were doing here if we want to keep those or use the Azlan sprites from BeeStation

**Comment by triplezeta** [comment]
I only made my comment because i took a look at what the current sprites in the PR looked like and thought that they weren't that good

h

**Comment by Trilbyspaceclone** [comment]
Ah ok. Thats for the feedback tho

**Comment by silicons** [comment]
they look alright but we prefer to stick with tg's artstyle
thank you, though.

**Pull request closed without merging**
