### PR TITLE
SPEEN (Audio added to spin emote)

### PR DESCRIPTION
**Pull request by Raptorizer**
## About The Pull Request
Adds audio to the spin emote
## Why It's Good For The Game
memes are good
## Changelog
:cl:
soundadd: added audio to spin emote
/:cl:

### CODE REVIEW

**Comment by Linzolle** [comment]
GOD PLEASE YES

**Comment by Linzolle** [comment]
actually this should be on the *flip emote

**Comment by Raptorizer** [comment]
but it is SPEEN not FLEEP

**Comment by nik707** [comment]
god i hate sound emotes im gonna pass o nthis and let the others decide

**Comment by nero1024** [comment]
Are there any anti-spam measures? Emotes that play sounds can get annoying real quick, esp. when spammed.

**Comment by YakumoChen** [comment]
I hate it, I don't want a sound to play when I spin

**Comment by Raptorizer** [comment]
The sound is now no longer on *spin.
It will play on a new emote: *speen

**Comment by silicons** [comment]
sorry, bit too memey

**Pull request closed without merging**
