### PR TITLE
Tracer's a human, not a changeling.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
warp implant stamheal 150->20 per use

## Why It's Good For The Game
adrenals implant has 3 uses and this has 15
3*150 = 450 stamheal per implant
15*20 = 300 stamheal per implant if you spam it all in one go

## Changelog
:cl:
tweak: tracer no longer gives you full stamheals per use
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
WHAT THE FUCK

**Comment by silicons** [comment]
Why is this using a CHEMICAL AGAIN

**Comment by ghost** [comment]
In hindsight I should've looked at what code I was piggy-backing off rather than just ignoring it.

**Comment by ghost** [comment]
> In hindsight I should've looked at what code I was piggy-backing off rather than just ignoring it.

f

> Why is this using a CHEMICAL AGAIN

if you're gonna make it use time reverse component close this

**Pull request merged**
