### PR TITLE
Adds Holo-rooms

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

converts some of the dorms on each map that had space in their dorms block to holo-dorms, which is basically a miniature holodeck for different bedrooms.
## Why It's Good For The Game

allows people to turn their bedrooms into a variety of different settings to match whatever they want to do. 
the idea of this was totally stolen from the RP server.
pretty simple for people to add new holo-dorm templates in the future if they want other stuff too.

## Changelog
:cl:
add:holo-dorms
/:cl:

god bless the person who wrote holodeck code for not hard-coding it.
https://cdn.discordapp.com/attachments/688542193324916738/706047692299567114/2020-05-02_02-40-26.mp4

### CODE REVIEW

**Comment by Detective-Google** [comment]
why did I decide to do two map prs at once the world will never know and I still hate myself for it.

**Comment by MrJWhit** [comment]
But why

**Comment by Detective-Google** [comment]
forgot to mention I added some more coins to the table by the holodeck to compensate for the coins that got axed from the dorm lockers going bye-bye.

**Comment by deathride58** [comment]
Why are the holodorms a part of the centcom z-level? The method of storing holodeck layouts as locations on the centcom z-level is legacy behavior, you should be using templates instead if possible.

EDIT: the fuck happened here?
image

Honestly, it'd probably be better to replace the holodeck on maps that're lacking in dorms like box instead of forcefully cramming holodorms in where they,,, *really* do not fit. Especially when you aren't even using templates and consequently can't even rotate those holodorms to fit those kinds of layouts

**Comment by Detective-Google** [comment]
if holodeck layouts aren't meant to be stored on the centcom z-level then _why the fuck are they all there_ one must realize in absence of any actual fuckin documentation of how these things work you have to take some measure of just imitating what the existing things do, and the holodeck says to add holodecks you do this: 	
`You can use this to add holodecks with minimal code:
	1) Define new areas for the holodeck programs
	2) Map them
	3) Create a new control console that uses those areas`
Personally, I don't think the box thing looks that bad, but I can always re-do it if other people think otherwise.

**Comment by deathride58** [comment]
The reason why holodeck layouts are the way they are, is because the code behind holodeck loading has not received any major updates in the past half-decade. It's the only remnant of the original shuttle code in the game, and with that comes numerous different quirks, such as the complete lack of rotation, for instance. There have been numerous backend improvements to maploading since the last time holodeck code had any major changes, the most notable of which being the template system, which provides *much* greater flexibility for this kinda stuff.

**Comment by Detective-Google** [comment]
> The reason why holodeck layouts are the way they are, is because the code behind holodeck loading has not received any major updates in the past half-decade. It's the only remnant of the original shuttle code in the game, and with that comes numerous different quirks, such as the complete lack of rotation, for instance. There have been numerous backend improvements to maploading since the last time holodeck code had any major changes, the most notable of which being the template system, which provides _much_ greater flexibility for this kinda stuff.

to be more specific, **if you expect me to rewrite all of holodeck code over a flair feature just close this PR**, I'm not interested in putting in the hours upon hours it would take me to figure it out over something that user-side would make no difference. This works, it works fine, if it's not fine enough then oh well I did what I could.

**Comment by Detective-Google** [comment]
haha fun something broke in this pr I'm just gonna close it and worry about it later

**Pull request closed without merging**
