### PR TITLE
New Bottle Sprites

### PR DESCRIPTION
**Pull request by HeroWithYay**
## About The Pull Request

Replaces the fat potion-looking sprites with more medicinal looking ones
Doesn't affect lavaland ones due to them making sense to be potions and not bottles + they have snowflake sprites anyway.

## Why It's Good For The Game

Only will ever be subjectively good. Personally I think they're a bit more in line with the art style of pill bottles and hypovials.
I needed an excuse to figure out github because I forget how this site works every month or so. My local repo barely works and this might not even compile despite being a tiny sprite replacement, please god help me.

image
image

## Changelog
:cl:
imageadd: replaced some icons
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
Somehow this managed to delete beakerbluespace80 and hypovial80, pls fix.

**Comment by HeroWithYay** [comment]
> Somehow this managed to delete beakerbluespace80 and hypovial80, pls fix.

How the fuck did i do that? Ill fix when back at pc

**Comment by SandPoot** [comment]
> > Somehow this managed to delete beakerbluespace80 and hypovial80, pls fix.
> 
> How the fuck did i do that? Ill fix when back at pc

image
it simply did

**Comment by HeroWithYay** [comment]
> > > Somehow this managed to delete beakerbluespace80 and hypovial80, pls fix.
> > 
> > 
> > How the fuck did i do that? Ill fix when back at pc
> 
> image
> it simply did

Wh-

**Comment by The-Sun-In-Splendour** [comment]
These look more like juice/milk bottles than anything else to me.

**Comment by HeroWithYay** [comment]
> These look more like juice/milk bottles than anything else to me.

image

Based off bottles like this. Can't really do the classic dark brown/orange colouring though without ruining the ability to tell reagent contents by colour.

image

**Comment by HeroWithYay** [comment]
> These look more like juice/milk bottles than anything else to me.

And I mean it's ss13... you can actually fill them with milk and juice. So I figured a more generic look halfway between medicine bottles and other products would be fitting. Just not fat little potions.

**Comment by HeroWithYay** [comment]
Those should be back now. Also added example images.

**Review by BlueWildrose — APPROVED** [review]
Good job on your first PR.

**Pull request merged**
