### PR TITLE
Adds new icon to hydroponics/harvest/peach.dmi

### PR DESCRIPTION
**Pull request by Ragolution**
Adds a new icon to peaches. One that actually looks like a peach and less like a weird purple apple.

Now people will be able to tell they're peaches and not weird purple apples.

Sorry, I'm not the best spriter but I did what I could.

https://imgur.com/a/u1fUtTA

### CODE REVIEW

**Comment by Ragolution** [comment]
how the fuck is there a merge conflict

**Comment by TripleShades** [comment]
bro you removed garlic and peas by accident, put them back

**Comment by Ragolution** [comment]
> bro you removed garlic and peas by accident, put them back

lmao what bruhhhhh

https://imgur.com/a/YEYW0x0

**Comment by Ragolution** [comment]
Gunna re-open this. I just realized my repo of Citmain is fucking super out of date.

**Pull request closed without merging**
