### PR TITLE
Allows circuit gripper to hold analyzers 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Robotic Circuit grippers can now hold and use analyzers

## Why It's Good For The Game

Its rather dumb that you cant hold analyzer and use them. Allows borgs to upgrade their own cams.

## Changelog
:cl:
balance: Allows robotic circuit grippers to hold analyzers
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
no

why would we let engiborgs xray ai cameras unaided.

**Comment by Trilbyspaceclone** [comment]
They already can build endless cams to do the same.

**Comment by silicons** [comment]
Then they can go build cameras.

**Comment by Trilbyspaceclone** [comment]
They can also emp proof them but thats not a problem?

**Comment by keronshb** [comment]
I don't think letting borgs upgrade cams for the AI is a good idea.  Maybe if they were emagged?

**Comment by silicons** [comment]
sorry no i'd rather not engiborgs be able to go xray cameras if they want to spend time building cameras in maint that's their choice

**Pull request closed without merging**
