### PR TITLE
Your meant to DRINK tea...

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Teas that are newly made no longer endlessly loop well out of system - my bad
To get the affects of tea, you must drink the tea. Not vape it, not splash it on your coder socks, not inject it into you vines or drip them into your eyes. Come one people, were MRP...

## Changelog
:cl:
tweak: Tea will now only work when drank rather then any other non-proper way!
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
you'd be better off purging any tea that comes from other sources or just outright not accepting said tea if it comes from another source
also it's a chem, so it _should_ work from any source, just like all other drinks

if there's an issue with people foaming/syringing it, then it should just be nerfed to be more appropriate

**Comment by Trilbyspaceclone** [comment]
I might make all drinks to get their affect need to be eaten/drank tbh. It feels like an undersight that you can vape legit blood and get that into your system as if it was IV'dropped

**Comment by timothyteakettle** [comment]
at the end of the day they're still chemicals and should work on people regardless of the method
if it's too powerful, nerf it

**Comment by davidchan13** [comment]
New item: Teapot IV, for when you urgently need to be british.

**Comment by Arturlang** [comment]
Many chemicals require different application methods to do their thing @timothyteakettle

**Comment by timothyteakettle** [comment]
this does not apply to food and drink reagents @Arturlang

**Comment by Ludox235** [comment]
> 
> ## About The Pull Request
> 
> Teas that are newly made no longer endlessly loop well out of system - my bad
> To get the affects of tea, you must drink the tea. Not vape it, not splash it on your coder socks, not inject it into you vines or drip them into your eyes. Come one people, were MRP...
> ## Changelog
> 
> 🆑
> tweak: Tea will now only work when drank rather then any other non-proper way!
> /🆑

You're* Effects* veins* Come on* We're*

**Comment by Trilbyspaceclone** [comment]
@timothyteakettle No other gun turns you into a other things/objects, didnt stop you form adding it in tho.
`But polymorph wand!`
No other /gun/.
Same argument here

**Comment by Trilbyspaceclone** [comment]
#13229 - does this +

**Pull request closed without merging**
