### PR TITLE
slimes can now have digitigrade/avian legs

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
title

sprites by Lizard#5266 (Delams-The-Sm)

digi:
image

avian:
image

## Why It's Good For The Game
some people want to be lizard slimes apparently and i see absolutely 0 reasons to stop them

## Changelog
:cl:
add: avian/digitigrade legs have been added for slimes
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
Testmerge when.

**Comment by SandPoot** [comment]
12 days.

**Comment by timothyteakettle** [comment]
this conflicts with an ongoing pr that I have testmerged
once it's fully merged i'll fix any merge conflicts with this, however it's not a higher priority than what is currently testmerged

**Comment by DeltaFire15** [comment]
Marking this as stale due to current nonmergable state aswell as long period of no commits.

**Comment by DeltaFire15** [comment]
Closing this PR due to staleness. Feel free to reopen once work on this PR is resumed.

**Pull request closed without merging**
