### PR TITLE
Ports Kilo Station from Skyrat

### PR DESCRIPTION
**Pull request by PersianXerxes**
## About The Pull Request

Ports Kilo Station from pre-rebase Skyrat, removing its maintenance shotgun and adding perma VR/cryo sleepers as well as a kinkmate and a public mining shuttle in the process!

## Why It's Good For The Game

The low pop server currently only has access to two maps: Box and Pubby (Meta's config is currently set to require 25 players, meaning it will never be available on the low pop server until this is changed), which is a shame.
Justin and I both felt the creation of the low pop server makes the perfect excuse to port Kilo Station to Citadel. On top of this, Kilo Station has been a popularly requested port, with Dan Neposh even attempting a port himself in the past, although he pulled /tg/'s version instead which I feel is not as good as this version due to design decisions such as the removal of its maint bar and perma wing.

## Changelog
:cl:
add: Added Kilo Station
tweak: Adjusts Kilo Station to be more in line with Citadel standards
imageadd: Added area icons required to make Kilo Station editable on Citadel code
code: Fixed a reagent container on Kilo pointing to a nonexistent reagent
config: Adds Kilo Station to the maps config file, does not fix Meta Station's population requirement
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
do you know how different it is from tg kilo btw?

**Comment by deathride58** [comment]
Shadowstation was the one who originally ported this to citcode. Do not let this be forgotten.

**Review by deathride58 — APPROVED** [review]

**Comment by PersianXerxes** [comment]
> 
> 
> do you know how different it is from tg kilo btw?

From a cursory glance over /tg/'s version (as linked to me by Justin), this version has less maint mobs, a common area in Perma, and a maint bar. Other than that, I'd have to take a more in-depth look over /tg/'s version.

Also, according to Necromancer, /tg/'s version of Kilo also experiences a somewhat consistent server crash around the hour mark of rounds it's run in, which this version does not have (Shadow Station regularly ran this version for over an hour without server crashes).

**Comment by Linzolle** [comment]
i'd rather all the maint mobs be removed tbfh. i played on shadow when they had kilo and it was a headache.

**Comment by Iroquois-Pliskin** [comment]
Yeah my big concern with Kilo is the maint mobs tbh. Having one or two spots with a piss weak hostile mob to spook the unprepared is fun. Making every other room a mob closet is asking for trouble.

**Comment by PersianXerxes** [comment]
> 
> 
> Yeah my big concern with Kilo is the maint mobs tbh. Having one or two spots with a piss weak hostile mob to spook the unprepared is fun. Making every other room a mob closet is asking for trouble.

This version, thankfully, doesn't feature "every other room" having mobs, for what that's worth. The only hostile mobs I found in maint were three Russians in a room immediately accessible by Medical for healing/revival and the cat surgeon by himself in a room between chapel and Science. All of these rooms are blocked off by barricades, the mobs are melee only, and they will de-aggro if you leave their vision.
I don't really think these will be a big deal compared to, for example, /tg/'s giant spiders in the AI upload. (In fact, for what it's worth, it looks as though Shadow Station removed all giant spider mobs from the map, which I appreciate it)

Now there **are** goliaths located in the asteroid surrounding the station, but you have to break down walls spacing the station or mine the asteroid to encounter those, which seems completely fair to me. Don't mine the asteroid without a PKA.

**Comment by Detective-Google** [comment]
As someone who played kilo a lot as it was new the maint mobs are really not a threat, definitely nothing that couldn't be solved with a welder.

**Comment by PersianXerxes** [comment]
Oh nice, someone made changes to areas.dmi
I'll see if I can fix that on my end ASAP.

**Comment by PersianXerxes** [comment]
And it's fixed!

**Comment by Ghommie** [comment]
Look at all these weak people unwilling to fight unrobust mindless ai simple mobs, how not !!fun!!.

Also the sofas in the bar need their dirs fixed to match the past months changes.

**Comment by PersianXerxes** [comment]
> 
> 
> Look at all these weak people unwilling to fight unrobust mindless ai simple mobs, how not !!fun!!.
> 
> Also the sofas in the bar need their dirs fixed to match the past months changes.

Fixed, whoops!

**Pull request merged**
