### PR TITLE
Reverts carbon based hat throwning - Aka hat throwing only works on borgs

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Makes Hats no longer be even able to be thrown atop of peoples heads. Sillicons untouched

## Why It's Good For The Game

*Yawn. Its rather meme and trolly for people. As well as rather powerfull to blind/armor remove for people. As well as stealing gear.

 
## Changelog
:cl:
del: removes hat throwing onto carbons
/:cl:

### CODE REVIEW

**Comment by PersianXerxes** [comment]
God yes, thank you!
Hat throwing was a bad meme.

**Comment by Trilbyspaceclone** [comment]
When I have to much fun
``Hey teens, you have to kill any head of staff?``
``Worry not with a amazing synda item, the Paper Hat(!) you can remove the armor on all heads off staff well their not in their hardsuits, So basicly always other then the CE!``
``With are fullproof 60 harm per shot,  .357 you can down anyone within 2 trigger pull!``

**Comment by ghost** [comment]
> When I have to much fun
> `Hey teens, you have to kill any head of staff?`
> `Worry not with a amazing synda item, the Paper Hat(!) you can remove the armor on all heads off staff well their not in their hardsuits, So basicly always other then the CE!`
> `With are fullproof 60 harm per shot, .357 you can down anyone within 2 trigger pull!`

you're joking but you should :)
make it so hats have a variable that lets them hatthrow that is disabled for all hats except a special syndicate item, h o n k

**Review by Ghommie — COMMENTED** [review]
This is the laziest way to revert a feature I have witnessed this month.
First off, the real issue is some hats lacking `clothing_flags` lack the `SNUG_FIT` flag when they should have it instead.
Second, the above flag could be converted in a typecache global list if you wish to avoid these sort of issues in the future.
Third, if you think some headwear shouldn't work for hat throwing, give them the `ANTI_TINFOIL_MANEUVER` (And probably as well change its snowflake name) flag, or better typecache it too.
Fourth, if you don't honestly give a heck about all of this, just remove the SNUG_FIT flag and the commented out code.

**Comment by Trilbyspaceclone** [comment]
Reason for not doing a full dquel of everything is do to it being good groudwork for this system to be done better.

**Comment by ForrestWick** [comment]
No
Fun
Allowed

**Comment by Poojawa** [comment]
Why would this have been ported to replace hats, instead of just making it so you put a hat on someone's head only if they aren't already wearing one

**Comment by Trilbyspaceclone** [comment]
@Poojawa Thats a good question, thank you Poojawa
image

**Comment by lolman360** [comment]
literally just pick up your hat when it falls off? lmao

**Comment by Poojawa** [comment]
"lol, it's funny" has always been, and will always be the worst fucking reasoning to adding something like this.

"lol it's funny" was the reason for the vomiting goose attempt, for the femur breaker, for a bunch of otherwise horrid suggestions.

 :v

**Comment by Linzolle** [comment]
at least make it not knock things off instead of this half assed removal

**Comment by Trilbyspaceclone** [comment]
Eeeeeh I like it how it is

**Pull request closed without merging**
