### PR TITLE
Wizard Den Repair

### PR DESCRIPTION
**Pull request by ghost**
Replaces the Wizard Den with a less fucked up version. Has cargo, tabletop room with a couple dead russians, a place for Chompy (the monster), and a mouse named Stuart.  The shuttle console is a fluff version that breaks as soon as it spawns.

http://i.imgur.com/W1thH3Z.png

I know TG already did this but I made my own version.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
edits 1
edits 2
there are two `2`s on the second image

**Comment by ghost** [comment]
http://i.imgur.com/BlbceZO.png

**Comment by ghost** [comment]
o shit forgot to add 2 walls to front

**Comment by ghost** [comment]
http://i.imgur.com/W1thH3Z.png

**Comment by TalkingCactus** [comment]
is this ready?

**Comment by ghost** [comment]
It's good to go

**Pull request merged**
