### PR TITLE
loadout items will no longer drop on the title screen most of the time as they will now insert into backpacks forcefully

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by deathride58** [comment]
Good puppy!

**Comment by deathride58** [comment]
This doesn't compile, you're fired

**Comment by deathride58** [comment]
Still doesn't compile, you double-fired

**Comment by silicons** [comment]
how

**Comment by Poojawa** [comment]
`modular_citadel/code/controllers/subsystem/job.dm:31:error: inconsistent indentation`

**Comment by LetterJay** [comment]
@kevinz000 FIX THIS

**Comment by Poojawa** [comment]
s t a l e

**Comment by nik707** [comment]
I'm closing all of Kevinz000 old, travis failed PRs and no one can stop me. One PR page here we come.

**Pull request closed without merging**
