### PR TITLE
Adds physics to the game.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Basically jiggle physics trope/meme. 

## Why It's Good For The Game
Aprils fool-ish contribution.

## Changelog
Nope.

### CODE REVIEW

**Comment by Linzolle** [comment]
ghom i cannot BELIEVE you

**Comment by necromanceranne** [comment]
:3c

**Comment by Arturlang** [comment]
I never knew you were this dirty, ghommie

**Comment by Ludox235** [comment]
coomer pr

**Comment by Ghommie** [comment]
This was a bad joke I forgot to close days ago.

**Pull request closed without merging**
