### PR TITLE
Where is your vibe?

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
Adds the vibe check emoji to the emoji list.

## About The Pull Request
It adds the vibe check emoji or for those who don't know, this guy:
vibe

## Why It's Good For The Game
More emoji's to express your salt oocly

## Changelog
:cl:
add: Adds the vibe check emoji to emoji.dmi
/:cl:

### CODE REVIEW

**Comment by bunny232** [comment]
creepy

**Comment by KeRSedChaplain** [comment]
why is it conflicting

**Comment by KeRSedChaplain** [comment]
WHY IS AN IMAGE ADD CONFLICTING

**Comment by DeltaFire15** [comment]
Nice merge conflicts.. vibe check failed.

**Comment by YakumoChen** [comment]
bad meme. The emoji doesn't even make real sense.

**Pull request closed without merging**
