### PR TITLE
exiting a bluespace jar through any means, hardstuns you for 5 seconds

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
be it thrown, resisted out, or let out, the occupant will be hardstunned for 5 seconds
this only applies to carbons

the hardstun-on-exit was suggested by reagen, it's a pretty good idea and i did say if people abuse it, i'll nerf it

## Why It's Good For The Game
people are abusing the jar that wasn't meant to be abused

## Changelog
:cl:
balance: exiting a bluespace jar through any means, hardstuns you for 5 seconds
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
i guess this is a balance change more than a tweak

**Comment by Hatterhat** [comment]
rip buddybagging 2

**Comment by zeroisthebiggay** [comment]
is stun a knockdown or am i thinking of paralyze
either way it should knockdown for better visual user feedback

**Comment by ghost** [comment]
> is stun a knockdown or am i thinking of paralyze
> either way it should knockdown for better visual user feedback

maybe the only issue is that knockdown takes off a quarter of your hp

**Comment by timothyteakettle** [comment]
stun isnt a knockdown you just cant do anything, could change it to a knockdown i guess

**Comment by keronshb** [comment]
Thank god no more funny cumjar guerrilla warfare.

**Review by DeltaFire15 — APPROVED** [review]

**Comment by IUrmYeah** [comment]
1/10 can't wait to be perma-locked to a jar.

**Pull request merged**
