### PR TITLE
Resprites Photocopiers

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
imageadd: Photocopiers now look different
/:cl:

lXqd8Rvs7b

Sprites are made by me. They are also used on Eris, and technically also Bay.

Arbitrary comparison pic in Box cargo bay:
3jAjBltDi0

Screenshot in library:
dreamseeker_Jrn8y7fTwA

### CODE REVIEW

**Comment by Ghommie** [comment]
I don't know, I'm kinda fond of the former one, it's fairly simple and doesn't have the jarring outlines that make the latter look a little out of place. It's quite good overall.
Try PRing this on tgstation too if you want, perhaps other people will have more to say about it.

**Comment by Linzolle** [comment]
yeah something about it is a little... _too_ detailed?

**Comment by ShadeAware** [comment]
The sprite is just really jarring with its colors. I think maybe making it a tiny bit more dull, and really scaling back that outline would help it tremendously.

**Comment by silicons** [comment]
:-1:

y'know guys there's a point where i have to say that looking video-gamey with simplistic elegance and vibrant colors is far better than something like baystation's sprite styles.

there's a reason i'm on tg and not bay.

**Comment by Linzolle** [comment]
seems unanimously unwanted

**Pull request closed without merging**
