### PR TITLE
Sprite Improvements! Jetpacks, TEG, Antimatter.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

The TEG and Antimatter Computer should have LESS codersprite syndrome, and look a bit better overall, the Antimatter especially. Jetpacks were ported from eris or modified from current and should now look less flat, emergency swipers have been ported from Eris. Check icon diffs to see everything.

## Why It's Good For The Game

Less ugly game good.

## Changelog
:cl: Tupinambis
imageadd: Updates TEG, Antimatter, Jetpack sprites (CO2 and Oxy from Eris).
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I kinda like the current TEG better.

**Comment by Arturlang** [comment]
Port eri's TEGs, how about?

**Comment by MrJWhit** [comment]
I like them all but the monitors, they don't seem significantly better, just bad in different ways.

**Comment by Tupinambis** [comment]
> Port eri's TEGs, how about?

They clash too much with the main artstyle, it's the same reason we don't port eris guns and such for the most part.

I am however going to revert the sprites for the TEG fans since those seem to be the most controversial and I'm not particularly happy with em.

**Comment by MrJWhit** [comment]
Oh, I should probably specify why I don't like the emergency swiper change. They're too dark and too similar of a color to a wall, and much smaller meaning you have a harder time clicking on it if/when you need to.

**Pull request merged**
