### PR TITLE
[wip] Adds Herbalist

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
wip
## About The Pull Request

Adds a new medical role -  Herbalist!
their goal is to make plants for chem use like omnizer, or lung healing chems ect ect.
Adds new area for them called the Herbalist Growery!

## Why It's Good For The Game

Allows medical to be apart of the service group a bit more and grow food or chems to heal people and i.g just do their own thing just as hydro does but for medical reasons like getting some of the more medical based plants like thisals and bee-palm

## Changelog
:cl:
add: New Job! The Herbalist, Med-Botney job
mapping: Removed in most maps the Viro erp room and added a mini-hydro station for medical use.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
didn't i make it quite clear that we are not going to be adding a medical botany job to take more work away from the actual  botanists?

**Comment by Trilbyspaceclone** [comment]
Check dates, this was made before you stated you didnt like it

**Comment by silicons** [comment]
regardless this is not going through for that reason.
give botany new features before trying to cut features from them.

**Comment by Ghommie** [comment]
We don't need a role blurring the line between medical/chemistry and botany. Yes, I know this is a WIP, but it's very barebone even in that state, with no function to support it past that threshold where I won't consider it a filler.

**Pull request closed without merging**
