### PR TITLE
removes two unused sprites

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
maintainers asked for one of these sprites to be removed and they were met with 'no' and for some reason maintainers went ahead and merged the pr anyway

this also removes a related sprite that was made to make fun of the first one, it's also unused and probably should also go to have clean sprite files thanks

id go ahead and delete dildo circuit sprites as they're also now gone however I don't plan on waiting for maintainers to host a vote on if a set of unused sprites of mechanical dildos should be removed from the codebase

this pr also shows that I have absolute power because the sprite says 'do not delete' but I have managed to delete it with just a single button press, showing that I am above the gods themselves

## Why It's Good For The Game
keep your snowflake credit shit outside of sprite files, thank you

## Changelog
:cl:
imagedel: the drake credit and pickle credit sprites have been removed
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Wait they actually put a fucking sprite as credit? Bruuhuhu

**Comment by lolman360** [comment]
>drake credit was 2.5kb

what the fuck

**Comment by timothyteakettle** [comment]
they outright refused maintainers requests for it to be removed and maintainers gave in

**Comment by moltoretardo** [comment]
When are we merging our github with skyrat's since their players are the one that decide what's merged here.

**Comment by moltoretardo** [comment]
image

I'm not kidding

**Comment by Ludox235** [comment]
> 
> 
> image
> 
> I'm not kidding

They probably talked to their metabuddies on the skyrat discord or something, I liked bcause I like the sprites but i didn't know the fucking sprite credit was still fucking in goddamnit why can't text be enough

**Comment by Ragolution** [comment]
I think the problem here is that this'll mirror to their codebase and because they rarely look at our PRs, it'll get automerged and everyone will get pissbaby bitchy

**Comment by silicons** [comment]
round two!

**Comment by timothyteakettle** [comment]
> round two!

you thought it was over? you fool, you absolute fool, it's never over!

**Comment by DeltaFire15** [comment]
> I think the problem here is that this'll mirror to their codebase and because they rarely look at our PRs, it'll get automerged and everyone will get pissbaby bitchy

@Ragolution They disabled their mirror bot so that specific issue will not exist. They'd have to selectively port the PR.

**Comment by Ludox235** [comment]
> 
> 
> > I think the problem here is that this'll mirror to their codebase and because they rarely look at our PRs, it'll get automerged and everyone will get pissbaby bitchy
> 
> @Ragolution They disabled their mirror bot so that specific issue will not exist. They'd have to selectively port the PR.

Thank fucking god holy shit I was feeling 🥴

**Comment by CameronWoof** [comment]
But Timothy!! It's specifically marked "Do-not-delete"!! Who knows what will happen?

**Comment by timothyteakettle** [comment]
also for anyone who wishes to cry about the license, i read through the entire license, you cannot remove copyright statements, but the image is not specifically a copyright statement, it's a separate asset to give credit, and so there's no reason we can't remove it while keeping the other (awful) images

**Comment by Ragolution** [comment]
As the artist of one of the sprites I give my full consent to remove my watermark.

**Pull request merged**
