### PR TITLE
Certain Chemsplosions no longer trigger while inside a mob.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Most reagent explosions no longer react inside mobs. Potassium/Water is nerfed in explosion strength.

## Why It's Good For The Game

Honestly, getting exploded after getting shot with multiple syringes and going into crit/getting gibbed from the explosions is kinda wack. Potassium/Water still works, but it's weaker.

## Changelog
:cl:
del: Explosive chems no longer react inside people.
/:cl:

### CODE REVIEW

**Comment by Sishen1542** [comment]
keep water/pot reacting in mob tbh

**Comment by ghost** [comment]
> keep water/pot reacting in mob tbh

I suppose I could, but I'll have to nerf the resulting explosion.

**Comment by ghost** [comment]
Pot/water now can still react in mobs, it's just that even with the best syringe, bluespace, the explosion will be very weak, and won't even delimb. As a result of that, its explosions generally have less of an oomph, but are still able to destroy structures and knock people down.

**Comment by shellspeed1** [comment]
I mean, I wanted to propose a different solution but people don't seem to like it. Might as well anyway. What if instead of people getting gibbed by bombs and as such round removed, we made it flings their organs and limbs everywhere so a bored doctor could take all the bits and pieces and rebuild the patient?

**Comment by ghost** [comment]
> I mean, I wanted to propose a different solution but people don't seem to like it. Might as well anyway. What if instead of people getting gibbed by bombs and as such round removed, we made it flings their organs and limbs everywhere so a bored doctor could take all the bits and pieces and rebuild the patient?

Honestly that works by itself as a solution to many things. The main thing I wanted to get rid of with this pr is getting exploded via a syringe. There's not really a counter to that, plus its not really fun to get hit by, as an antag, or as a non-antag.

**Comment by Kraseo** [comment]
cringe

**Comment by silicons** [comment]
not a fan of how this is handled, especially the pota/water nerf.

if it comes down to it it wouldn't be impossible to make explosions have an ignore/dampen explosive damage object-cache of sorts to make the syringes unable to instagib, but as is i don't think this is necessary.

**Comment by ghost** [comment]
I think I see a way to do this differently, with several ideas. I'm just gonna close this and make a new pr for it.

**Pull request closed without merging**
