### PR TITLE
Makes stasis beds *slightly* less hated

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title and check changelogs.

## Why It's Good For The Game
It is good

## Changelog
:cl:
add: The stasis beds can now be researched alongside being built.
balance: Maps are now half stasis beds and half sleepers... only in medbay.
fix: The stasis bed's examine now works.
refactor: Generally updates stasis bed's code and adds cooldown defines (i learnt how to use them)
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
Hot take, its pretty easy to get a sleeper if someone really wants one in medbay and we have chemistry right there where its pretty easy to make most chems. I'm fine with leaving them researchable but we probably don't need them roundstart.

**Comment by SandPoot** [comment]
The intent on re-adding them to maps is that it was said to be a port and work alongside the existing sleepers, not OUTRIGHT REMOVE THEM (FROM THE MAPS).

**Comment by Arturlang** [comment]
Honestly just good stuff, I only ported the original PR, replaced main station sleepers with the stasis beds, and handled stasis for our whack code. But on re-adding sleepers roundstart you'd best ask r0-adic as they were the one to ask me to replace the sleepers

**Comment by deathride58** [comment]
Why the fuck did stasis beds replace sleepers to begin with

Literally the entire reason they weren't ported initially is because they shouldn't have replaced sleepers.

**Comment by Arturlang** [comment]
Sleepers were not entierly removed @deathride58, and the problem with sleepers is that they make most medicines unnecesary as it produces unlimited amounts of chemicals for essentially free

**Pull request merged**
