### PR TITLE
The Unrolling Pin! (Ready)

### PR DESCRIPTION
**Pull request by WanderingFox95**
## About The Pull Request

We all had this happen to us before, right?
We're just trying to cook and realize - oh our flour just ran out, hydroponics isn't ready to prepare more but we don't need more buns, we want to make bread. But the dough is already flattened.
So here is the solution: The new and innovative **unrolling pin**!

Use it on flattened dough and pie dough to unflatten the dough and make cake batter, respectively!

It even shows up in your hand! No random assaults with mysteriously invisible weapons!
(Beyond the functionality for unflattering dough, the item is identical to the rolling pin)

## Why It's Good For The Game

It allows you to correct dough-based mistakes! (Also, come on, it's an unrolling pin)

## Changelog
:cl:
add: added the unrolling pin, an innovative solution to dough-based mishaps.
imageadd: added visuals for the unrolling pin
/:cl:

### CODE REVIEW

**Comment by Acer202** [comment]
As much as I love the idea of an unrolling pin, maybe you could alternatively make it so using flattened dough in-hand rolls it back up? Unless there's some crazy coding problem with that or something.

**Comment by WanderingFox95** [comment]
> 
> 
> As much as I love the idea of an unrolling pin, maybe you could alternatively make it so using flattened dough in-hand rolls it back up? Unless there's some crazy coding problem with that or something.

Of course, it's possible.
I just wanted do it in a funnier way.

**Comment by necromanceranne** [comment]
I only support this if is able to unflatten food that is already flat. Like pizza.

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> > As much as I love the idea of an unrolling pin, maybe you could alternatively make it so using flattened dough in-hand rolls it back up? Unless there's some crazy coding problem with that or something.
> 
> Of course, it's possible.
> I just wanted do it in a funnier way.

This is why I love this PR. You made something meant to be used in hand into a stupid fucking item (literally just a anti-rolling pin)

**Comment by brokenOculus** [comment]
Just need an un-knife to mend cut food items together.

**Comment by WanderingFox95** [comment]
> 
> 
> Just need an un-knife to mend cut food items together.

Good idea! Maybe for a later PR. I'll call it the E-fink.

**Comment by WanderingFox95** [comment]
If this change doesn't work, I will need to redo the fork thing and open a new PR.

**Pull request merged**
