### PR TITLE
Replace CE's RCD by an IRCD

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request

This replace the CE's RCD that is in his locker by an IRCD and make the IRCD start upgraded.

The IRCD is an RCD that can build and destroy things faster and is more efficient, it has a capacity of 500 Matter-Unit, or 340 MU more than a normal RCD. It is also upgraded, which allow it to do the same stuff as the rest.

## Why It's Good For The Game

Why would the CE start with the same RCD as his engineers ?
And why would the new RCD not be upgraded like the rest ?

## Changelog
:cl:
add: Replaced the CE's RCD with an IRCD
add: Made the IRCD upgraded
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
iirc kevin is completely against ranged rcds in any way, shape or form so good luck

**Comment by Putnam3145** [comment]
it should be noted that this would be the only way to have an ARCD that isn't admin stuff. tbh if you're gonna do this add a steal objective for it or something, but i'm iffy on it regardless, cause yeah, ranged RCD is scary

**Comment by lolman360** [comment]
i mean i dont think so, i even wanted to add it at once point but kevin shot it down so

**Comment by Sishen1542** [comment]
Hard downvote, just upgrade the one currently in locker

**Comment by Linzolle** [comment]
Absolutely not, this is meant to be an admin item. If you changed it to the _industrial_ RCD I will consider it.

**Comment by GrayRachnid** [comment]
ARCD is more powerful than the mech RCD. This thing can even be used through cameras.

**Comment by r4d6** [comment]
I was told that Ashwalkers start with an ARCD. Or something along those line.
Why ? "_Raided Technologie_" or some similar thing.

**Comment by Sishen1542** [comment]
They start with an upgraded rcd

**Comment by r4d6** [comment]
Also, the CE already started with an upgraded RCD before Sishen

**Comment by Sishen1542** [comment]
Ok so why buff it

**Comment by r4d6** [comment]
All the others the engies have are, so why not this one ?

**Comment by Sishen1542** [comment]
Because rcds are already incredibly powerful, you don't need stronger versions roundstart for no reason

**Comment by r4d6** [comment]
Fine, I'll change it to an IRCD

**Comment by Sishen1542** [comment]
Still a fat no from me

**Comment by r4d6** [comment]
Done, I changed it to an IRCD

**Comment by r4d6** [comment]
Can I get your opinions again now that I changed it from an ARCD to an IRCD.
also be aware of [Ghommie's PR](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10050) that add view checks to the RLD and the ARCD.

**Comment by Sishen1542** [comment]
Still a no from me chief, CE already starts with the best tools on station they don't need yet another buff. 

Also you seemed to have pushed your map to this pr

**Comment by r4d6** [comment]
fuck. it was just to have a git backup of it.

**Comment by r4d6** [comment]
Gah. Why can't I merge just a few commits ?

**Comment by r4d6** [comment]
Right, this is not going anywhere. So I am going to close it and just make a PR for the N2O tank.

**Pull request closed without merging**
