### PR TITLE
Ports the TG window buff, but not so bad

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Ports the TG's window buff, but not so high that it takes several minutes to break, as is you need to take one break to fully recharge your stamina if you are breaking it with a toolbox.

## Why It's Good For The Game
Currently windows are really stupidly weak right now, I don't like how stupidly strong TG made it, but I did agree they did need to be a bit stronger

## Changelog
:cl:
tweak: Windows in general are way tougher now, requiring some effort to break through
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Does this include the incredibly dumb deconstruction method they did?

**Comment by R3dtail** [comment]
Since this includes adding the extra-steps making reinforced windows much harder to deconstruct, I'm uh, not really too fond about that.  I mentioned in OOC about moving those steps to just the higher end tiers of glass like titanium, to make them a worthwhile upgrade.  But, of course, I'd have to see the changes in live to make much of an opinion on it since I do get where this is coming from.  But, making normal reinforced windows much harder to remove seems a /bit/ silly when you can just, encourage upgrading the station with the better glass to make things more secure.

**Comment by Arturlang** [comment]
Reinforced do actually need extra steps to be removed, or else there's no point to making them more durable, but if there's a compromise we can come to, I'm willing to do it

**Comment by MrJWhit** [comment]
Yeah but the method makes no god damn sense, why are you heating up screws to unscrew them.

**Comment by BlueWildrose** [comment]
Sounds like a desperate attempt to force a welder step in, which it doesn't really need. Honestly, take the welder step out and it'd probably be improved by that alone.

**Comment by MrJWhit** [comment]
Metal when it's heated **expands**, it would dig **further** into outer material, making it **harder** to unscrew. You heat up the outside of a stuck jar because the metal expands, giving you more space, you cool screws to give yourself more space to help you take it out. You can heat up a screw to help soften it because of the expansion (lower density), and then tear the absolute shit out of it.

This is a hill I will die on.

**Comment by keronshb** [comment]
Not liking this too much.

If anything the steps should be moved to Reinforced Plasma glass and Titanium/Plastitanium windows.

If people want stronger windows they should put up R Plasma

**Comment by Arturlang** [comment]
The point of this is to buff reinforced windows, so getting into rooms isnt as stupidly easy, but yes fine I'll remove the screw heating step

**Comment by Arturlang** [comment]
Itll take me a moment to do though, window code is fucking hell

**Comment by YakumoChen** [comment]
Don't really like it, windows are supposed to be a weak point into entering rooms. I'm not sure what logic TG ever had for changing things but getting through windows shouldn't be much more difficult then it is. Otherwise you have gay baby jail scenarios because you're stuck in a room with an obnoxiously tanky window.

**Comment by Arturlang** [comment]
The point here is not to have obnoxiously tanky windows, while also them not being completely stupidly weak, reinforced windows are not very reinforced, not really, and the normal windows are just laughable

**Comment by Arturlang** [comment]
Normal windows take the old reinforced window steps, and reinforced windows have lost the welding step, should be good to go now

**Comment by Tupinambis** [comment]
Windows were intended to be weak entry points to begin with. This just nerfs... well it nerfs some improv crafting recipes since it's harder to break windows for them, it nerfs fire axes? it nerfs antags. This is just a poorly thought out change. I'd only be okay with it if literally every map was entirely re-windowed to balance around this change.

**Comment by Arturlang** [comment]
@Tupinambis This does not nerf fire axes, nor does it nerf improvised recipies, you can simply get some weak glass and break that, this does NOT make the windows as strong as TG has them, it only makes them not something you can just stupidly easily broken, but still weaker than walls, i'd argue this would be worth a testmerge to at the least let people feel how hard it's to break, now that it doesnt take several minutes to break, or dismantle nor does it need welder like TG does, but now i feel like i'm repeating myself

**Comment by HeroWithYay** [comment]
Windows are in a good place right now, definitely not something we need except to make a lot more situations stupidly obnoxious. If it takes a full stamina bar to break with a toolbox how much will it take with an emergency oxygen tank? Do you expect players to be there for hours just because they got teleported by some antag or event?

Bear in mind virtually every window on the station is reinforced.

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
I'm gonna say ehh the integrity buff ain't really needed. If anything, make the more difficult decon steps required for reinforced plasma / plastanium windows, and those only.

**Comment by Arturlang** [comment]
The extra difficult steps are for the plastitanium windows and plasma reinforced ones alone yes, im going to test how hard its with a emergency tank though, and i am going to remark again that windows that are supposed to protect against even breaches and super secure rooms are often only protected by windows which takes only a few spear hits or literally two tools to remove

**Comment by Arturlang** [comment]
And even currently if windows break, people will just replace them with walls because thwyre just that useless

**Comment by YakumoChen** [comment]
People replace them with walls because you can do so without tools and only need metal.

Windows aren't supposed to protect against breaches. They're a weak point for breaches. Insecure breaching points are a vital part of game balance, it's the reason we dont allow the warden to replace every window with plasma glass round start.

**Comment by Arturlang** [comment]
Just going to close this, it looks like people really dont want this, eveb if it makes sense

**Pull request closed without merging**
