### PR TITLE
Revert "Citadel's folder's end"

### PR DESCRIPTION
**Pull request by yourdoom9898**
Reverts Citadel-Station-13/Citadel-Station-13#5828

Putting this revert here since this PR was a self-merge with a heavily debated nerf thrown in that was out of scope of the PR. This will also allow for a more coherent discussion about it than being on the Discord.

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
Revert *only* the map changes and RnD changes.

The vast majority of this PR consists of code improvements

**Comment by fludd12** [comment]
Regardless of how much of a PR consists of code improvements, there is a reason pull requests are atomic. You do not make that many changes to that many unrelated things at once, it's both horrible coding standard and isn't fair to the changes that are actually good, to try and make them a horse pill to swallow with your own opinions.

**Comment by cebutris** [comment]
This absolutely has reason to be reverted. The PR was:
-Self-merged
-Speed merged (at only 3 hours old!)
-Non-atomized, containing changes to xenobio and saycode as WELL as the code improvements, the only things declared in the title
-Had an undescriptive changelog that didn't explain to players what was changed

**Comment by deathride58** [comment]
@cebutris engineering changes were a completely separate PR. That PR only had two non-atomic changes that should've been made in separate PRs, one of which was actually a pretty commonly requested feature.

**Comment by cebutris** [comment]
My bad. The other points still stand

**Comment by Poojawa** [comment]
I'll properly revert this after I finish a sync

**Pull request closed without merging**
