### PR TITLE
[READY][PORT] Port of TG's ExperiSci PR Part 1

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Port of TG's ExperiSci PR(https://github.com/tgstation/tgstation/pull/54093). Currently there's not a lot of experiments but they will be added in the second part

## Why It's Good For The Game

See original PR

## Changelog
:cl:
add: Reworked science so now you need to perform "scientific" experiments
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
uuuuh currently material checks are shitty af so we need to rework em

**Comment by DeltaFire15** [comment]
Referenced PR is not merged yet. DNM.

**Comment by SmArtKar** [comment]
> Referenced PR is not merged yet. DNM.

now it is

**Comment by DeltaFire15** [comment]
Failing CI, a bunch of merge conflicts and no commits since a prelonged period of time. Marking PR as stale.

**Comment by DeltaFire15** [comment]
Closing this PR due to staleness.

**Pull request closed without merging**
