### PR TITLE
Updates DMAPI to v5

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

https://github.com/tgstation/tgstation/pull/50611
@LetterJay 

## Changelog
:cl:
server: DMAPI updated to v5
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
There were several PRs, use this one on hippie for refrence: https://github.com/HippieStation/HippieStation/pull/12756

**Review by Cyberboss — APPROVED** [review]
Assuming everything in `tgs.dm`/`modules/tgs` is up to date, looks good.

**Comment by silicons** [comment]
:heart:

**Comment by Cyberboss** [comment]
DMAPI was updated to 5.1.1 with fixes. You should add that https://github.com/tgstation/tgstation-server/releases/tag/dmapi-v5.1.1

**Comment by silicons** [comment]
kk

**Comment by Cyberboss** [comment]
@kevinz000 you're gonna hate me :) 
https://github.com/tgstation/tgstation-server/releases/tag/dmapi-v5.2.0

**Comment by BlackMajor** [comment]
pain

**Pull request merged**
