### PR TITLE
removes magicarp from gold cores

### PR DESCRIPTION
**Pull request by silicons**
unironically more annoying than headslugs every round

### CODE REVIEW

**Comment by Wilchenx** [comment]
needs i ded tag

**Comment by jakeramsay007** [comment]
but how else will I as a traitor become a changeling too reeee

**Comment by RogueSteampunker** [comment]
Didn't we have this conversation a long time ago?

**Review by deathride58 — CHANGES_REQUESTED** [review]
DME

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
