### PR TITLE
Minor sprite accessory update:

### PR DESCRIPTION
**Pull request by Verkister**
-Fixed snout layering.
-Added snouts for wolf and husky.
-Added body markings: hands/feet, belly/hands/feet, slim belly, and husky.
-Swapped base and extra color layers on husky tail to match the added parts.
-Removed unnecessary clutter.

[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

:cl: Minor sprite accessory update:
add: -Added snouts for wolf and husky.
del: -Removed unnecessary clutter.
tweak: Swapped base and extra color layers on husky tail to match the added parts.
fix: -Fixed snout layering.
/:cl:

### CODE REVIEW

**Review by LetterJay — COMMENTED** [review]
Tested by anyone?

**Comment by Verkister** [comment]
Tested by me but mostly on lobby char editor. Just sprite and customization list changes tho so any game breaking stuff is unlikely.

**Comment by LetterJay** [comment]
Alright. After I do a bit of testing for the test branch and have that ready I'll merge this to save a lot of time.

**Comment by Verkister** [comment]
I'm detecting additional ladles in this soup over the coderbus channel. Hopefully we can get over with this before shit gets tangled.

**Comment by LetterJay** [comment]
I'll make sure everything is working as it needs to be before any decisions are made. Don't worry.

**Pull request merged**
