### PR TITLE
Changeling Buffs

### PR DESCRIPTION
**Pull request by Raptorizer**
## About The Pull Request
Makes the spider ability able to be gained on round start and not after three absorbs.
Lowered the loudness of spiderlings and mute sting.
Lowered the DNA cost of cryo sting.
Increased the chemical cost of Hallucination sting while doubling the Mindbreaker toxin and regenerative materia.

## Why It's Good For The Game
A small step in adding a bit more interest to the changeling gamemode. More to come soon, hopefully.

## Editlog
09/15/2019 18:00pm CST
Adjusted spider requirement to require absorbs but still lowered by 1. 3 -> 2 required.
Reverted Cryo and mute sting changes

## Changelog
:cl:
tweak: tweaked a few things
balance: rebalanced something
/:cl:

### CODE REVIEW

**Comment by chefferz** [comment]
I disagree with this. Being able to produce spiders and incite even more chaos as a ling is suppose to be a reward for actually giving three people the real succ, not just a sting.

**Comment by YakumoChen** [comment]
Cyro is a combat sting, shouldn't be 1 DNA point. It's pretty deadly if you can't get to a coffee machine in time, pairs well with mute sting.

Mute sting is really powerful and a huge augment to any assasination or combat, it doesn't need nerfed.

Changeling is a pretty powerful antagonist as it is, the only problem is that its not got a lot of interesting powers, most of them are either useful exclusively for combat or stealth, not much good for general sabotage. It's a very boring antagonist to play in comparison to traitor where you have a huge selection of tools and a lot more versatility.

**Comment by deathride58** [comment]
>roundstart spiders

Hell no.


>decreased loudness of abilities used primarily for loud builds

That's a nerf, not a buff, as it pushes ling blood explosions further into you-have-to-build-specifically-for-it territory.

>hallucination sting changes

Now that's good.

**Comment by Raptorizer** [comment]
> I disagree with this. Being able to produce spiders and incite even more chaos as a ling is suppose to be a reward for actually giving three people the real succ, not just a sting.

Alrighty, but how about lowering it from 3 people to 2?

**Comment by Raptorizer** [comment]
> Cyro is a combat sting, shouldn't be 1 DNA point. It's pretty deadly if you can't get to a coffee machine in time, pairs well with mute sting.
> 
> Mute sting is really powerful and a huge augment to any assasination or combat, it doesn't need nerfed.
> 
> Changeling is a pretty powerful antagonist as it is, the only problem is that its not got a lot of interesting powers, most of them are either useful exclusively for combat or stealth, not much good for general sabotage. It's a very boring antagonist to play in comparison to traitor where you have a huge selection of tools and a lot more versatility.

Cyro and mute have been reverted back. I missunderstood what the "loudness" meant.

**Comment by Raptorizer** [comment]
Would people be interested in MORE different stings?

**Comment by Arturlang** [comment]
Yes, make then something you might actually need, as suprisingly many just dont use them

**Review by silicons — CHANGES_REQUESTED** [review]
the only acceptable part of this pr is hallusting imo sorry i don't want more changelings doing the stealthy pussy way of spamming spiders ad infinitum because me too scared to do anything but create spiders unga dunga ""stealth"" ""antagonism"" (seriously that's bad gameplay don't enable it more.)

**Pull request closed without merging**
