### PR TITLE
[Test-mergable, but not finished.] Nerf Moddernation

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
## About The Pull Request

Alriiiiiiiiiighty, so, Riot darts are whack, this is going to help fix that in 4 ways.
1. Nerf the AM4 series of rifles to 3rnd bursts, slightly longer firing delay.
2. Make all foam guns fire a slightly different projectile, so you can't immediately load riot darts at the first sign of trouble.
3. Make foam guns modifiable, using a screwdriver to open them, wirecutters to remove the air restrictor, pipe to reinforce the barrel, and screwdriver to put it all back together again. You'll also have to modify the magazines using a screwdriver and wirecutters.
4. Reduce the riot dart damage from 25 to 20. 

## Why It's Good For The Game

Reduces the ammount of riot dart spam, I should know, I'm probably the worst about it.

## Changelog
:cl:
add: Adds in a new way to modify foam shooting guns, required to make them shoot riot darts.
remove: Riot darts are no longer printable from the autolathe.
tweak: Changes the amount of nerf darts in a regular box to 60, from 40.
tweak: Reduces the amount of riot darts in a box to 30, from 40.
balance: Changed AM4 series rifles (B, C) automatic burst to 3, from 4.
balance: Changed Riot Darts stamina damage to 20, from 25.
refactor: Changes how foam darts are handled behind the scenes, the common toy darts you now see are a subtype of the original, preventing loading riot darts without modifying the guns.
/:cl:

### CODE REVIEW

**Comment by ZeroNetAlpha** [comment]
This can be testmerged for now, but it's lacking the ability to modify nerf guns, donk-soft weapons should be able to still fire their nerf darts.

**Comment by Poojawa** [comment]
making riot darts mass-producible was a mistake.

**Comment by lolman360** [comment]
no, making the fucking nukeop-tier guns that fired them was.

riot darts are fine in toy shotguns (4 shots, pump-action), toy crossbows(1 round) and toy foam force pistols(8 rounds, semiauto) - the only ones available on most rounds, and really only available from cargo (shotguns, pistols).

**Comment by DeltaFire15** [comment]
The reduction of riot dart damage will make the uplink riot-foam guns even less viable for their cost, is that intentional?

**Comment by ghost** [comment]
this is ok

**Comment by ZeroNetAlpha** [comment]
Honestly there were several mistakes involving riot darts. The uplink foam guns taking a nerf are an unfortunate, but needed side effect for the moment. After I'm done trying this out, I'll look into giving those particular guns their own buff.

**Comment by Ghommie** [comment]
PR hasn't been active for a LOT of time now. Will close in about one day if merge conflicts and the nuke-op nerf side-effect are not resolved.

**Pull request closed without merging**
