### PR TITLE
makes the passive generation rate reasonable post toxins nerf

### PR DESCRIPTION
**Pull request by silicons**
buffs by a little below 50%
25*60*60*2 = 180000 at current, max is around 320000
this will make it able to max research without tesla coils in a single round if toxins is done

### CODE REVIEW

**Comment by Poojawa** [comment]
you can also research with tritium cans in the SME, 

the ability to max research by passive gen alone shouldn't be viable.

**Comment by Trilbyspaceclone** [comment]
This feels hug-boxy. There is better ways to make points and better point gen thats more player interactive. Perhaps make the EXPERIMENTER give Rnd notes as you place in objects. Decon the Rnd notes to get points. Better item/parts better notes

**Comment by Trilbyspaceclone** [comment]
> you can also research with tritium cans in the SME,
> 
> the ability to max research by passive gen alone shouldn't be viable.

Poojawa has a point with Passive gen, Rnd should be more player interactive.
SME can be upgraded and used to get *massive point gen buffs*. And if sci is a cleave fox they can do fusen in there burner with a SMES in the space shutters to get 3 SMES makeing 10k points per tick~ *In theory*

**Comment by deathride58** [comment]
You can actually 100% rnd without leaving engineering if you know what you're doing, but the methods to do so are so tight under lock and key and are so harmful to the rest of the station to the point where nobody really tries it.

**Review by deathride58 — APPROVED** [review]
I'm probably gonna end up rolling this value back once I give research point production options to bartenders and miners/curators

**Pull request merged**
