### PR TITLE
the geese have been unleased

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
port of https://github.com/tgstation/tgstation/pull/43137
adds a maintenance pet for assistants and a purchaseable goose crates for cargo
geese will randomly attack nearby mobs, since they are violent and evil creatures

## Why It's Good For The Game
honk bird funny man

## Changelog
:cl: original by: WJohnston, Antur, Arcane, plapatin, sprites by cogwerks and edited by mrdoombringer. port by sishen1542
add: THE GOOSE IS LOOSE
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
👎 keep vomi/tg/oose on tg please. It's a tg meme.

**Comment by Sishen1542** [comment]
>  keep vomi/tg/oose on tg please. It's a tg meme.

good thing we're a tg downstream
too good of a feature to leave untouched

**Comment by YakumoChen** [comment]
It's not even that funny, unless you're into toilet humor, which I suppose is fitting for TG.

**Comment by Weblure** [comment]
Seems like something that's funny to look at once but annoying to put up with every single round. Maybe if this were much more rare and harder to get, it'd be alright.

**Comment by YakumoChen** [comment]
Just port the regular goose if you insist on having the goose meme, leave the vomit goose in the cesspit where it belongs. It's practically TG's logo now anyway, no need for us to steal it.

**Comment by Sishen1542** [comment]
yeah but it has vore so it fits on citadel

**Comment by Ghommie** [comment]
You'll have better chances to get this PR merged if you leave the pukish goose on code backend, I heard kevinz saying on discord weeks ago he's quite against it, or so I remember. honk.

**Comment by Sishen1542** [comment]
if maintainers want me to remove the vomit boys im fine with it, ill just slap a regular goose in the bars & keep the crate

**Comment by lolman360** [comment]
honestly i want it in maint bar just for the 90%ers to drag it out so they can erp

and having it vomit everywhere when they try

and if they leave it alone they'll probably get attacked by it

**Comment by Poojawa** [comment]
This is fucking disgusting. Not even remotely funny or useful.

**Comment by Ghommie** [comment]
> 
> 
> This is fucking disgusting. Not even remotely funny or useful. 

Just like some certain features already present on the codebase. :man_shrugging:

**Comment by Tupinambis** [comment]
To be honest, toning down the vomit to just make it a brief thing would be reasonable, especially if the goose spawns round start.

**Comment by silicons** [comment]
i love tg but not the vomi/tg/oose.

**Comment by Sishen1542** [comment]
removed vomit goose, kept regular goose

**Comment by silicons** [comment]
@Sishen1542 your pr isn't udpated

**Review by silicons — APPROVED** [review]

**Pull request merged**
