### PR TITLE
Revert "Zeolites tweaks"

### PR DESCRIPTION
**Pull request by LetterN**
Reverts Citadel-Station-13/Citadel-Station-13#13773

todo: refactor fermichems itself

### CODE REVIEW

**Comment by MrJWhit** [comment]
butwhy

**Comment by LetterN** [comment]
you "cannot" make the chem anymore, and instead you can emp the entire station with it (due to it's high failure rate)

**Comment by DeltaFire15** [comment]
@LetterN Just made a bunch of them (120u, purity 0.85 because I messed up a bit) on local with T1 machinery, can you elaborate what exactly makes them 'impossible' to make?
If you have some buffer and don't set the heater temp to absurd temperatures without it being upgraded, it's really not that difficult (besides that particular change actually made them easier to make, allowing beakers that can't stand very acidic / basic chems to handle them)

**Comment by DeltaFire15** [comment]
So yeah, as said, this wouldn't even change anything really. Closing this PR.

**Pull request closed without merging**
