### PR TITLE
Porting to the /tg/ sprite changes, and functionality, of large reagent containers

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of the following PRs:
https://github.com/tgstation/tgstation/pull/52808
https://github.com/tgstation/tgstation/pull/53874

I'm not bringing the mapping changes over, because I'll deal with that once any and all mapping PRs are handled, because I'll get my greasy hands in everything.
This _does_ include the cargo buylist as well.

## Why It's Good For The Game

Small sprite update, and also allows cargo to buy the large fuel tank.

## Changelog
:cl:
add: 
tweak: Added the ability for cargo to buy a large welding tank
imageadd: Tweaked large tank reagent sprites to /tg/'s
/:cl:

### CODE REVIEW

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Looks fine to me in general, though please remove the devastation range from its boom proc, I'd rather not want mass-orderable gibbing explosives added to cargo.

**Comment by MrJWhit** [comment]
As in, remove its uniqueness entirely? I'm fine with reducing it and removing the gib functionality, but these things still having the same explosion  as something with a 5th the reagent size seems a bit weird to me. Even just having a giant fireball is fine with me, maybe a (0,2,5,12) explosion would work?

**Comment by DeltaFire15** [comment]
Just the gibbing range that is an immediate issue in my opinion, the other values are probably fine as they are. If it gets abused or proves to be a problem, we can tweak those at that time.

**Comment by MrJWhit** [comment]
Done

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
