### PR TITLE
Replaces carbon xeno drone with a simplemob sentinal in the beno cube

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Replaces carbon xeno drone with a simplemob sentinal in the beno cube

## Why It's Good For The Game

It's clearly not the intended design of the cube, spawning in a brainless carbon mob, based on the "run!" part of the description. Plus, a drone can easily turn into a queen, which isn't ideal for something that's only accessible through silver slimes.

## Changelog
:cl:
tweak: Xeno cube now makes an aggressive sentinal instead of a brainless drone
/:cl:

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
Considering there's only been one reported person who's used it for brain stuff, and the fact that making it a simplemob completely destroys what purpose the cube would have as a means of getting xeno organs for cargo and surgery points for rnd, I'm gonna have to disagree.

Turning it into a simplemob only accomplishes in adding another mindless hostile mob in a role where hostile mobs far better than it already exist. All this does is punish the majority over one or two players the adminbase had failed to properly reprimand until recently.

**Comment by Solaris-Shade** [comment]
LINE 435 name = "alien drone cube"

If it spawns an alien sentinel, wouldn't the name need to be: name = "alien sentinel cube"    ?

**Comment by silicons** [comment]
```
	///list of things spawned at mob's loc when it dies.
	var/list/loot = list()
	///causes mob to be deleted on death, useful for mobs that spawn lootable corpses.
	var/del_on_death = FALSE
```
my recommendation is making it spawn a varedited (see: subtype) sentinel with slightly higher stats, and dropping a carbon sentinel body on death. this preserves old functionality without just giving people a free catatonic DRONE (see: evolving into queen, structures, etc), while keeping the item true to its name and frankly, intended function.

**Comment by MrJWhit** [comment]
Fair enough, that's updated. 

A drone causes eggsack balance concerns, and, I honestly couldn't find the alien drone simplemob.

**Comment by MrJWhit** [comment]
Looks good to me.

**Pull request closed without merging**
