### PR TITLE
Adds RGB knights and more!

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Added Lavaknights, a new ghost role of cat people in knight armor.
add: Added Hypereutactic blades, NEBs on steroids.
tweak: Made NEBs alt click to recolor
wip: Added lavaknight spawners. Someone else needs to add it in to a map or ruin properly.
imageadd: added sprites for hypereutactic blades
/:cl:

dreamseeker_2017-12-01_23-56-34

Lavaknights will add a unique lavaland experience for us. They have explicit instructions to not murderbone in their flavourtext and will hopefully produce awesome experiences, barring any shitty players being shit, of course.

dreamseeker_2017-12-01_23-28-14

Lavaknights will spawn as cat people.

dreamseeker_2017-12-01_18-41-59

The hypereutactic blade is a unique weapon which only lavaland captains spawn with. Ideally, only one should exist at any time due to their strength. They combine aspects of the dual-eswords and bastard sword, needing two hands to wield and having a slowdown.

A toy variant exists for the sake of toy memes.

The lavaknights are not implemented in any maps or ruins, meaning to test this, one would have to spawn the spawners. If this PR gets merged without implementation, admins should be encouraged to plop down a few spawners for the sake of testing.

dreamseeker_2017-12-02_00-01-06

The stats of the various items introduced in this PR should be thoroughly looked through before merging. Many numbers could do with some tweaking. All of this has been in the making for over a month, with barely an hour total of cumulative testing.

### CODE REVIEW

**Review by deathride58 — APPROVED** [review]
remind me to make a space ruin for this, featuring the catknights' ship crashed in a large asteroid filled with hostile life.

**Comment by cebutris** [comment]
I like the idea of catpeople ghost roles. It's so wonderfully Citadel.

**Comment by Michiyamenotehifunana** [comment]
Inb4 I make them sparkledog cat furries

**Comment by deathride58** [comment]
I'll handle turning these into an actual, non-bus-exclusive ghost role some time soon-ish 👍

**Pull request merged**
