### PR TITLE
xenobio regen core nerf (replaces aheal with legion core effect, 5s apply)

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
5s apply time for regen cores because lol you can literally shit them out
reduction of heal from literal full heal to basically just legion core

## Why It's Good For The Game
i hate xenobio players and i have no stake in whatever round this happened in again

## Changelog
:cl:
balance: Xenobiology regen cores now have a 5s apply time and don't full heal.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
kor died for this

**Comment by Hatterhat** [comment]
> 
> 
> kor died for this

let him rot

**Comment by BlueWildrose** [comment]
this is a fucking salt PR and a half right here.

currently creating a better alternative for regens than nerfing something literally even harder than how legion cores got nerfed.

**Comment by DeltaFire15** [comment]
Yeeah no this is going quite overboard.
If anything, preferring #15167 over this when adjusted, considering xenobio cores are, whilst still semi-massproducible, quite a big chunk more time-consuming to acquire than legion cores.

Closing this PR.

**Comment by Hatterhat** [comment]
making bad faith prs is my gift to this codebase

**Pull request closed without merging**
