### PR TITLE
reduces table cooldown to 0.4

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

title

## Why It's Good For The Game

tableslam funny, can't be that spammy now can it

## Changelog
:cl:
tweak: tableslamming has 0.4 second cooldown instead of 0.8
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Does it even stun at all anymore?

**Comment by silicons** [comment]
this is right click harm intent combat mode table slamming

**Comment by Arturlang** [comment]
Oh, alright.

**Review by Linzolle — APPROVED** [review]

**Comment by Linzolle** [comment]
bonk

**Pull request merged**
