### PR TITLE
Add cyborg upgrade: Automatic Scrubber

### PR DESCRIPTION
**Pull request by LeDrascol**
## About The Pull Request
Removes the service cyborg's innate ability to automatically clean floors, and makes it into an upgrade module.

## Why It's Good For The Game
Prevents service cyborgs from rendering mops obsolete, and requires them to interact with robotics to become ~~overpowered~~ advanced janitor replacements.

## Changelog
:cl:
add: Added cyborg module: Automatic Scrubber
tweak: Service cyborgs no longer automatically clean floors
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
it does not feel like service borgs are an issue with the ability to clean what they walk over, nor has it ever came to my attention that this has been problematic, so overall this PR confuses me a bit

**Comment by LeDrascol** [comment]
Giving every service borg the ability to auto-clean should, in practice, render all janitors, cleaning spray, and mop upgrades obsolete. Clean on move performs the task better than anything else, but is available immediately.

The real issue that isn't being properly addressed by this PR is that players graffiti can also be removed, often unintentionally, by borgs walking by. While messes like blood and dirt exist only to be cleaned, the presence of graffiti is intentional, and deserves different treatment.

A separate PR to directly address the sub-issue could be made.

**Comment by Poojawa** [comment]
wandering in to remind people that borgs, unless helped by crew, are supposed to be able to do their chosen task better than their human counterparts for the drawback of no hands and few non-job specific alternatives.

make the cleaning function a toggle. 

or if you absolutely need to nerf it, make it cost energy per step whilst also making it toggle-able.

**Comment by silicons** [comment]
make it a toggle
janiborgs/service borgs have almost **nothing** going for them
why nerf them?

**Comment by DeltaFire15** [comment]
There is no reason for this nerf.

**Pull request closed without merging**
