### PR TITLE
Changes the space adaptation sprite to something more subtle.

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Changes the space adaptation from a big ol' blob to a more subtle and less intrusive outline. A PR done on behalf of akada, who did the sprites.

spacemut
spacemut2

## Why It's Good For The Game

The big ass sprite is really an eyesore on everyone who has it.

## Changelog
:cl: akada
imageadd: Changes the space adaptation sprite to something less intrusive and more subtle.
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
I dunno, I think them having a bigger clickbox is good for balance though right?

**Comment by necromanceranne** [comment]
I literally don't give a shit about if it's a balance consideration because that's fucking stupid. Afros make you easier to click too, are you telling me playing with an afro is hardmode? Or the actual size of a piece of clothings sprite is a balancing point as well?

**Comment by BlueWildrose** [comment]
> I dunno, I think them having a bigger clickbox is good for balance though right?

what is heck is with you.

This is literally the most mundane, insignificant change to something here, something that has to do with fuckin' sprites of all things. All this does is change how many clickable pixels you have when you decide to melee something. It might have an impact if some bastard decides to go prone in order to force people to actually aim as well but that's pretty much it. Two of these things barely even have an impact in space-based combat, because people tend to shoot eachother in space instead more often than not. I don't know if you're being funny or not but it's not worth piping up over. If you're fighting in-doors, well, space adaptation matters even less. Maybe we can achieve true balance by just drawing an ugly green box layered under every spaceman whenever you enter combat mode if you're so concerned about pixels.

It's understandable that genetics is imbalanced and that thermals had probably ruined about 50+% of your traitor and heretic runs and that you can't use atmospheric area denial because all of sec has space adaptation but you know what, that's just what it is. Genetics powers as they are aside from thermals and sure, space adaptation has problems and maybe when Kev introduces a new method of information gathering via genetics we can have something less garbage than thermals but until then, quit protesting over every single insignificant thing that ends up benefiting the crew more than antags by even an inch. You've been crusading so hard about every damn thing that happens to be even the smallest detriment to the antags in even any slightest way, like piping up over a change to suit sensors I've made because you're worried that powergaming warden number 32 is gonna notice that someone's suit sensors dropped to vitals or something. It's not like people are gonna take a mile when they're given inches. I'm pretty sure people still care all about antags and properly balancing them versus crew because after all, it hasn't been you complaining about these things but you in particular tend to push them to great extremes things like "security shouldn't have this at all" or just simply: "I lost, nerf this".

I will argue that maybe space adaptation can be split into "void adaptation" and "cold adaptation" to make the syringes be handed out like popcorn less frequently and maybe genetics can do with a change to have more genetics on the table but otherwise, if you try to stop a method of powergaming that people have been seeming to abuse a lot, people are going to just find another way to powergame until the game just stops being fun. Part of the reason why people still play SS13 is because they're trying to find the many different ways to game the system, to become the most efficient there ever was and everything. They'll try to speedrun genetics, chemistry, virology, xenobiology, mining, or whatever the fuck. That's why people stick around - they got records to beat. There's no way around it aside from finding the most broken things and putting a complete stop to it, like the whole cargo lumbermill meme, or the monkey miasma farming, but otherwise you just have to put up with the fact that someone's going to abuse the hell out of a specific thing. If the crew can't even have the slightest bit of power (and not just raw skill) over an antag otherwise the gameplay is gonna get stale quickly. And just remember, whatever the crew can use, an antag can usually also use anyways.

Going off on a tangent aside, quit complaining over inches. They're not miles.

**Comment by necromanceranne** [comment]
Listen, I respect the hustle, and I'm not gonna say you're wrong, but let's talk about space adapt balance in a different pr or format and not muddy the discussion further. Because this is a sprite pr.

**Comment by BlueWildrose** [comment]
this is mostly me just blowing up because I've been seeing a repeat behavior from Keron that's starting to get annoying, apologies.

**Comment by rossark** [comment]
would it be possible to make it cover the head too, muh immersion is hurting. like how it looks though especially compared to the ugly glowing orb we currently have

**Comment by keronshb** [comment]
> 
> 
> I literally don't give a shit about if it's a balance consideration because that's fucking stupid. Afros make you easier to click too, are you telling me playing with an afro is hardmode? Or the actual size of a piece of clothings sprite is a balancing point as well?

You're right, in the grand scheme of things it doesn't really mater much in the end.  Apologies on my end.

I do wish the sprite covered the head, seems kind of odd just to stop by the neck.



> snip

This isn't the best place to talk about this.  I've read it.  Some of it is right, other parts not exactly.  Feel free to talk to me in DMs or drop a ping if you feel there's an issue.

**Comment by necromanceranne** [comment]
> would it be possible to make it cover the head too, muh immersion is hurting. like how it looks though especially compared to the ugly glowing orb we currently have

It covers the head it's just close to the head and blocked by your hair + clothes

**Comment by rossark** [comment]
> > would it be possible to make it cover the head too, muh immersion is hurting. like how it looks though especially compared to the ugly glowing orb we currently have
> 
> It covers the head it's just close to the head and blocked by your hair + clothes

ooo sneakyyy, very nice :D

**Comment by The-Sun-In-Splendour** [comment]
The sprite is actually worse than before and I despise kevinz for merging this pr.

**Comment by ghost** [comment]
> 
> 
> The sprite is actually worse than before and I despise kevinz for merging this pr.

Honestly I have to agree. The sprite is too discrete for what benefits it gives and is usually nearly impossible to see if someone wears bulky clothing like a coat. You have to really be looking to see it on most people

**Comment by JogBoba** [comment]
After playing with this new sprite for a while, while it’s nice in a way I do agree that it’s entirely too discreet to the point of being nearly impossible to spot if you’re not specifically looking for it. If it had something just a little more noticeable to it, it would be a nice change.

**Pull request merged**
