### PR TITLE
Ports IV bags from TG

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
This pull request ports IV bags from tg, a handy tool for more intensive treatments within tg. The specific pr they come from is https://github.com/tgstation/tgstation/pull/44531/files. IV bags can hold 100 units of reagents and are made with plastic. They will fit in both chem  bags and fridges and can be labeled using a pen. IV bags can be sealed by alt clicking on them, however if sealed they can still have their contents modified using a syringe. 

## Why It's Good For The Game
IV bags provide an additional tool for medical to use at least within the chem game and can be helpful for treating things such as blood loss or administering medications over time such as when performing surgery. Beyond this, I would like to look at chems that need to be diluted to be used safely as an option for chemistry and porting the rest of this PR bit by bit so we can decide what we do and don't want from it.

## Changelog
:cl:
add: Adds IV bags.
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
No idea why the changelog file has edits or map diff bot threw a merge conflict, please help.

**Comment by shellspeed1** [comment]
I'm hoping that didn't actually fuck anything since I know you guys were having issues with changelogs earlier and I honestly know only a tiny bit about coding, but it made the bot happy.

**Comment by YakumoChen** [comment]
I dont get it. Don't IV drips already do this?

**Comment by Trilbyspaceclone** [comment]
you can add a glass beaker that holds 120u, or a plastic bottle for the same amount and holds more...  To the IV stands already

**Comment by Trilbyspaceclone** [comment]
Just dont forget to add them to the organ box/medical belt

**Comment by shellspeed1** [comment]
Sure you can use a beaker or a bottle, the thing is those are easy to fuck with while IV bags take some effort. IV bags are meant to be somewhat disposable. As for adding them to the organ box and medical belt, you can put a chem bag on your belt so I see no reason to have them on your belt directly. I might look at having them on the organ box though.

**Comment by shellspeed1** [comment]
Decided to say fuck it and made it so you could put them in organ boxes and medbelts instead of just boxes.

**Comment by triplezeta** [comment]
"dont beakers already do this"
well yes
but we gotta get that

***b e l i e v a b i l i t y***

IV bags are an excellent flavor addition for medbay, and can be used by mappers and medbay personnel alike for general use. They also have separate function from beakers, in that they're able to be sealed, allowing a chemist to hand out idiot-proofed bags of medicine to medbay for use

**Comment by YakumoChen** [comment]
Chemist has idiot proof medicine. It's called a pill.

**Comment by Krysonism** [comment]
> you can add a glass beaker that holds 120u, or a plastic bottle for the same amount and holds more... To the IV stands already

My reasoning is that your coworkers won't use a random mystery beaker standing in a table in medbay, but an IV medicine bag is instantly recognisable and easily labeled. It is intended to insert the idea to use the drip into the mind of the doctor.

It is a little bit of social engineering. In addition using a beaker makes little sense RP wise.

**Pull request merged**
