### PR TITLE
Without this, everyone is broken

### PR DESCRIPTION
**Pull request by Poojawa**
Fucking byond stop drinking paint thinner.

### CODE REVIEW

**Comment by Zeldazackman** [comment]
Here's byond basically https://i.imgur.com/mIvWZta.png

**Review by deathride58 — APPROVED** [review]
@kevinz000 this could and probably should be speedmerged

**Comment by Poojawa** [comment]
Did you lose your merge powers, Bhjin

**Review by silicons — APPROVED** [review]

**Comment by silicons** [comment]
done

**Pull request merged**
