### PR TITLE
Refactors ventcrawling

### PR DESCRIPTION
**Pull request by jack-avery**
## About The Pull Request

Refactors ventcrawling. Specifically, how whether mobs can (or can't) is handled.

## Why It's Good For The Game

Ventcrawling is implemented poorly and this should alleviate that a bit.
Also apparently will free up some memory now that not every single mob has a ventcrawling variable.

Testing vectors (since I'm not testing all ~45 of them):
- Xenomorph ventcrawling works as intended.
- Mouse (and assumably by extension all simplemob) ventcrawling works as intended.
- Alien Gland ventcrawling works as intended
- Slime ventcrawling works as intended.

## Changelog
:cl:
refactor: ventcrawling
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
hey can you make it so you have to click on a vent when inside it to leave the ventcrawl because as it is right now you move really fast in vents and also instantly come out as soon as you walk into a vent which is really annoying w/ lagspikes or high ping

**Comment by jack-avery** [comment]
> hey can you make it so you have to click on a vent when inside it to leave the ventcrawl because as it is right now you move really fast in vents and also instantly come out as soon as you walk into a vent which is really annoying w/ lagspikes or high ping

i can try this as another pr, i'm leaving this as is purely as a refactor

**Comment by raspy-on-osu** [comment]
what the fuck is wrong

**Comment by jack-avery** [comment]
Builds fine locally. Time to keep re-rolling Travis

edit: bless

**Comment by raspy-on-osu** [comment]
bless

**Comment by Arturlang** [comment]
misnt there already the  jumpsuit that lets you ventcrawl

**Comment by jack-avery** [comment]
i checked every instance that modifies your ventcrawler value while making this. there is no jumpsuit

**Comment by DeltaFire15** [comment]
Uhhh I'm going to leave this one to @silicons

**Comment by silicons** [comment]
on it soon

**Comment by HeroWithYay** [comment]
> misnt there already the jumpsuit that lets you ventcrawl

late reply but jumpsuit is yogstation

**Pull request merged**
