### PR TITLE
Makes it so robots can heal normally from cores.

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

Robots suck at mining.
This makes them suck less at mining.

## Why It's Good For The Game

Fast heals for robots is probably a good thing

## Changelog
:cl:
tweak: robots heal normally from legion cores now
/:cl:

### CODE REVIEW

**Comment by TheEaterOfBeans** [comment]
it probably doesn't work but whatever
edit: nevermind it actually works fine

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
As you may not be aware, the reason for legion cores to have reduced effects on Synthetics is that it can also repair thresholded limbs, effectively making it lavaland nanogel (except better considering instant and nodamageslowdown for a time in addition to its minor heal). I'd rather not have miner cores be simillarely prevalent in that aspect like miners handing out their highly powerful survival pens like candy.

If you want to change this still, either consider merely increasing their multiplier to 0.4 instead of 0.2 which should still be in line, or alternatively remove its ability to heal thresholds if you want them to heal like for organics.

**Comment by TheEaterOfBeans** [comment]
> As you may not be aware, the reason for legion cores to have reduced effects on Synthetics is that it can also repair thresholded limbs, effectively making it lavaland nanogel (except better considering instant and nodamageslowdown for a time in addition to its minor heal). I'd rather not have miner cores be simillarely prevalent in that aspect like miners handing out their highly powerful survival pens like candy.
> 
> If you want to change this still, either consider merely increasing their multiplier to 0.4 instead of 0.2 which should still be in line, or alternatively remove its ability to heal thresholds if you want them to heal like for organics.

I want miner robots to get heals that DON'T need them to stand still so they can fight megafauna.
That's literally it.
I am not competent enough to code it better.

Thresholds shouldn't be a problem on Lavaland.

**Comment by TheEaterOfBeans** [comment]
I would make legion cores decay if you take them off Lavaland or something like that, but I can't because again, I have zero actual coding skill.

edit: okay fuck it I will actually try to make cores unusable off Lavaland

**Comment by TheEaterOfBeans** [comment]
yeah uh I was going to try stealing from nuke disk code after trying to use the suspiciously simple code someone posted in the Discord
but it's coNTROLLED BY "STATIONLOVING" INSTEAD OF ACTUALLY BEING IN THE NUKE DISK'S CODE, AND WHEN I FOUND _THAT_, IT WAS JUST
A WALL
OF CODE
THAT I HAVE NO HOPE OF UNDERSTANDING AND THEREFORE CAN'T STEAL FROM
**PAIN**

**Pull request closed without merging**
