### PR TITLE
Lets the Cargo Shuttle use Disposal Pipes again

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

Lets the Cargo Shuttle use Disposal Pipes again

## Why It's Good For The Game

This change was silly, let them load via disposals if they want to.

## Changelog
:cl:

balance: Lets the Cargo Shuttle use Disposal Pipes again
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
Cargo buff

**Comment by lolman360** [comment]
there was an issue with them re: teleporting to centcomm, that's why they aren't allowed on the shuttle

**Comment by keronshb** [comment]
> 
> 
> there was an issue with them re: teleporting to centcomm, that's why they aren't allowed on the shuttle

Can you explain how this works more?

**Comment by zeroisthebiggay** [comment]
> > there was an issue with them re: teleporting to centcomm, that's why they aren't allowed on the shuttle
> 
> Can you explain how this works more?

probably something like:
person in pipes isn't counted as 'being in the shuttle' so shuttle launches; qdels all contents which includes the pipes but only ejects the person inside of the pipes which lets them remain in centcom
or something

**Comment by silicons** [comment]
getallcontents should catch this

**Pull request merged**
