### PR TITLE
Removes the Statistical Benefits and Penalties for Combat Mode

### PR DESCRIPTION
**Pull request by CameronWoof**
## About The Pull Request

This PR does the following:
- Combat Mode no longer halts stamina regeneration
- Combat Mode no longer has any bearing on melee damage dealt or received
- Combat Mode no longer has any bearing on gun accuracy (but changing direction still does)

## Why It's Good For The Game

Toggling combat mode on and off is tedious and does not provide the player with any interesting choices or strategy. If you are running away, there is no reason to have it on. If you are fighting, there is no reason to have it off. Given that no conscious choice is being made on the player's part, toggling it on and off is just a chore and serves to confuse new players to the community who don't understand what it is, what it does, and who have no access to resources to learn.

The only thing the statistical benefits of Combat Mode do is artificially increase the difficulty of playing on the server, to no tactical or strategical benefit. It is not depth or meaningful complexity, it is just complication for its own sake.

Any special features of combat mode's control scheme are still active, as they are or can be legitimately useful.

## Changelog
:cl:
balance: There are no longer any numerical benefits associated with combat mode. It is now simply an optional control scheme that unlocks some special interactions.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Fun fact with combat mode, non-carbons have it on all the time. Meaning if you are fighting a mob/silicon it deals flat more harm to you, takes less harm more untill you turn on combat mode

**Comment by timothyteakettle** [comment]
if this doesn't get merged, then the statistical benefits of combat mode seriously need reducing as they're so large / such a big impact honestly

**Comment by Tupinambis** [comment]
Yes please.

**Comment by necromanceranne** [comment]
Lemme break it down pretty cleanly to explain why this isn't a smart decision and frankly the limitations imposed being in and out of the mode is in large part what justifies why many other mechanics work the way they do. I'll be really honest, you'd be better off stripping out stamina and combat mode entirely before largely making the careful use of the mode redundant.

**1.** Stamina regeneration being gated by combat mode prevents constant use of stamina draining abilities like sprinting, which at the moment is immensely fast. Free meth speed is not a good mechanic in of itself and I absolutely detest sprinting, but not being punished at all for sprinting while in combat mode is maybe the biggest reason why this change shouldn't be added. You would need to remove sprinting entirely for this to be a smart choice.

**2.** Combat damage mods do actually give some functionality to a variety of high power melee weapons being used in a sneak attack. While it definitely makes any weapons that put you on the floor significantly more powerful (like batons), it also makes attacking someone while they have their guard down fairly strong, which emphasizes mostly antagonists over nonantagonists. Stun batons will largely function regardless of whether you are or aren't in combat mode, so the only people mostly harmed by this is non-sec. Any problems surrounding being taken out of combat mode too easily (cough _tasers_ cough) should be evaluated there.

**3.** The limitations of being in and out of combat mode is mostly the point of a stamina based combat system to begin with. It means anyone who isn't going to want to be in combat and chooses to flee will be in something of a disadvantage. Not that they ARE right now due to sprint but that's, again, an entirely different topic all together. If people are simply constantly regenerating their stamina even during the middle of a prolonged skirmish, there isn't enough downtime between regeneration to make the point of that stamina be anything worth keeping around, as well as no intelligent thought behind when and where they should be dipping out of combat mode to regenerate stamina.

Hugboxing combat mode doesn't do anything other than put holes in an otherwise still fairly nascent system, and my stronger recommendation would be to simply can it and stamina outright and return to the tg combat system. Which is a damn shame given the potential the system holds, but it's better than a less than half-baked one.

There are also worse offenders within the system that need to be addressed before combat mode itself. Primarily the immense power of stamina based attacks and the monopoly security has on this kind of damage.

**Comment by silicons** [comment]
"Combat Mode no longer has any bearing on gun accuracy (but changing direction still does)"
why would we remove the good part about gun accuracy but not the bad part and actually keep it intentionally 
also everything necrodancer said

**Comment by Owai-Seek** [comment]
I mean, it could have been discussed further instead of just outright closing it, you gave no chance for changes after your comment.

Sneak attacks with melee weapons are irrelevant when so many people A. Go for a revolver and B. Already have the jump on someone in -most- cases. You already get 1-2 free hits, which means they'll have trouble escaping, why exactly do you need to do -even more- damage?

The only thing I dislike about combat mode is actually the damage multiplier if I'm going to be honest, and when I forget to turn it off and end up never regenerating stamina.

**Pull request closed without merging**
