### PR TITLE
[Ready] Improvised Weapons Update: Part 2

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Well here's what we have!
• Fix for missing saw icons. Not sure how that happened.
• 32 ACP ammo type. Will be used for another gun in the future.
• New weapon crafting parts.
• Improvised Pistol.
• Improvised Laser. Can be upgraded to be slightly more powerful with glassworking lenses and T4 parts.
• Loot tables for weapon parts and ammo boxes. To be placed by mappers.
• Clean-up of the weapon crafting menu. _Check the media section!_
• Shotgun from part 1 is now two-handed with a less severe damage modifier.
• Sprites from part 1 reworked again.

## Changes from Part 1
Improvised shotgun now needs two hands to fire but has a 0.9* damage modifier instead of 0.8*.
This fixes the issue of it being able to just run up to people and buckshot them point-blank twice to soft-crit before they can react. It also helps keep the rifle relevant, since it still does a little more damage and is easier to get.
Rifle has a new sprite. Now the bolt is actually all kinda in one spot, it's not incredibly weird.
Shotgun has a new sprite to make it more break-action-y.
image
Fixed clothing sprites for the guns, so once slung, it looks like the new sprites.

## Balancing
**Improvised Pistol:**
_Deals 13 brute damage with a magazine capacity of 8 and a 0.75 firing delay; this means it takes six seconds to actually empty an entire magazine. You're probably going to miss one of the bullets which would get you into softcrit. Once you craft it, you then have to craft a magazine, then you have to get access to bullets. You have to load bullets into the magazine. The benefit to it being so relatively weak compared to the shotgun and rifle is its small size. It takes a while to get one. Since high magazine capacity is somewhat powerful, you need plastic to craft the gun in the first place. You can get this by cutting shower curtains._

**Improvised Laser:**
_It can fire five shots before it needs recharging. It does 10 burn damage per shot, maximum 50 burn. It's really bad. It can be upgraded with a six-part crafting process with glassworking tools from cargo to make a lens. If you have tier 4 parts as well, you can upgrade it to doing 15 burn damage and firing ten shots, the same capacity as an egun. (Laser gun has slightly higher capacity, both egun and laser gun do 20 burn). To upgrade it, you need cargo to cooperate. Cargo staff can get easy access to the glassworking crate, however, they would have an easier time buying an egun or laser crate and breaking it open to get something better than they would making a lens and then getting parts from science/engineering. It's rechargeable, though. You also need a multitool to craft._

## Why It's Good For The Game
Adds more variety of improvised weapons to fit different niches that the other ones don't.
Extra loot tables! You can now find ammo in maint. Mappers can decide how much they want.
Completely original sprites, not taken from anywhere, not a video game or movie rip-off.
Works great for admin events small and large. Remember when we had that wave defence? This would work perfect for that. Enemies could have these relatively underpowered weapons and the crew could craft them too.
This is intended to not powercreep improvised weapons. The shotgun and rifle should still be the better choice. If anyone has balance concerns I'm happy to nerf things.

## Changelog
:cl: Floof Ball / Kathrin Morrison / Floof Ball#0798
add: Improvised Pistol + 32 ACP ammo.
add: Improvised Energy Gun. Fires 5 shots of 10 burn damage each. Can be upgraded with a lens made from glassworking and T4 parts for a minor buff.
add: Ammo + gun part loot spawners for mappers.
add: New sprites for Improvised Rifle, the ability to sling the rifle and a sprite for that.
add: New sprites for the Improvised Shotgun and its sling sprite.
balance: Improvised shotguns are now two-handed only.
balance: Improvised shotguns now only have a much less harsh 0.9* modifier, keeping them two hits to crit with slugs and buckshot. It can no longer be dual-wielded but can still be sawn off for w_class medium (can fit in backpacks).
fix: Missing handsaw icons added in.
tweak: Crafting table cleaned up into sections.
/:cl:

## Media
image
_Some of the new parts for crafting the weapons._
image
_The two new weapons._
image
_The recipe requirements._
image
_The improvised rifle and shotgun (and sawn-off... and also sling-shotgun) sprite changes._
__

### CODE REVIEW

**Comment by Ghommie** [comment]
Merge conflicts.

**Comment by KathrinBailey** [comment]
@Ghommie conflicts fixed, sorry for being so slow with it.

**Comment by YakumoChen** [comment]
I don't really see the point of the energy gun upgrade, or how it makes sense (one generally assumes typical laser guns don't use or need bleeding edge tech parts in the first place). Given the amount of cooperation it takes to upgrade one, as you said, and how obvious it is to be what you're getting the parts for, aren't you literally just better off buying laser guns from a crate anyway?

craftable laser guns also suffer from the problem of why they would be heinously overpowered in the first place: you only need a recharger to reload them and the lack of damage/ammo capacity can be made up for with bag space, and you don't need to fiddle with or make bullets to reload it. 50 damage puts you at a pretty strong advantage by itself, given that's past the slowdown threshold.

I also agree with the assessment that high magazine capacity is what would make a craftable pistol extraordinarily powerful. That said, plastic is very common (you can decon plastic flaps which are everywhere) and materials to craft are not generally considered a deterrent to crafting things unless you need to print them from a protolathe or some other very obtuse method (like durathread in general)

**Comment by KathrinBailey** [comment]
Impro pistol now needs:
1 pipe
3 plasteel << from 2 plasteel
15 plastic << from 1 plastic
8 metal
1 igniter
5 wooden planks
That's for all the recipes involved in making it.

**Comment by YakumoChen** [comment]
Maybe I wasn't clear enough when I said "material cost isn't a great detriment to crafting unless the materials are exotic" but consider exactly the absurd amount of volume of plastic you're requiring now for a single hand sized gun 

Given the gun is improvised, have you considered making it be pneumatic to trigger the firing mechanism instead? Requiring a certain amount of air pressure would add a second layer of ammo maintenance like magrifles currently do.

Baggable, craftsble, magazine loaded guns are certainly still powercreep as well, the craftable rifles are bulky and hold very little ammo.

**Comment by KathrinBailey** [comment]
**Please read before merging if you decide to merge:**
Shotguns have been made two-handed and the damage modifier raised from 0.8* to 0.9*
It addresses the issue left behind that you can just still walk up to people and buckshot them twice to crit them, that's what the original PR was trying to address.
This modifier still keeps the rifles relevant; the rifles are still easier to craft and do slightly more damage still.

**Edit:**
I went back and made new sprites.
People seem to like them better, I wasn't satisfied with the sprites I made in part 1. I think they were still an improvement but I think this is much more of an improvement.

**Pull request merged**
