### PR TITLE
Ports "nerfs cakehat for realsies" & co as an alternative to Pooj's PR

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Ports /tg/station PRs #45001 and #44006, also #44419 (ergo caramel), used for the birthday cake recipe.

## Why It's Good For The Game
Debating over a mere 15 points burn damage hardhat to people willing to make it worse than a match just because they don't enjoy its hilarity is simply not worth it.

What this PR does is stop the early round assistant from gaining free access to a ghetto weapon, adds caramel, make candied apples use caramel, uppercases "secret sauce" reagent initials, changes the recipe of birthday cakes, makes cakehats require birthday cakes, not the other way around, as well as two line changes on it.
That's enough to make its popularity wane a little and reduce the "salt".

Open to suggestions and tweaks for the birthday cake recipe and etcetera.

## Changelog
:cl: Ghommie (original PRs by nemvar and imsxz from /tg/station)
add: You can now make caramel by heating sugar. Be careful not to overcook it.
add: Adjusted the candied apple recipe
balance: cakehat has been nerfed
tweak: cakehat sounds cooler
add: You now get the cakehat by cooking a whole birthday cake.
del: The cakehat has been removed from all maps.
tweak: Birthday cake recipe no longer requires a cakehat. It now needs a candle, sugar and caramel.
add: Metastation bar now has a new plant. Her name is Potty.
/:cl:

### CODE REVIEW

**Comment by Thalpy** [comment]
The caramel reaction might break eigenstasium reactions, I'll have to check.

**Comment by Poojawa** [comment]
This literally just enables them to be mass-produced

**Comment by Ghommie** [comment]
> 
> 
> This literally just enables them to be mass-produced

As I told you over and over again, there is no real balance problem with the possibility of multiple cake hats existing in a given round.
Anyhow I'll be probably applying a tweak to the hypothetical cake hat mass production disaster that may be upsetting you and an adamant minority of players in a way or another if viable.

**Comment by chefferz** [comment]
Mass production of an infinite fuel cake hat is ridiculous.

Also, it's a birthday candle. Literally.. a candle. You're telling me a candle can do more damage than a kitchen knife? Cmon now. It's not a "mere 15 points", the issue is that it's infinitely fueled.

**Comment by Ghommie** [comment]
Listen, I know somes dislike tropes such as these joke weapons, somes would enjoy an higher degree of common sense or a different gameplay than what it's been offered. Ultimately we don't always stand by the same opinions and that's why different codebases exist, just take it with a grain of salt.

Anyhow, here is an initial tweak to cope with your peeves.
The power of each cakehat drops by 1 point every 5 existing cake hats added in the world, and the opposite is true too.

**Comment by Poojawa** [comment]
so it takes 5 cakes to become a force 14 instead of a force 15

Great balance change. yes, this is totally how to nerf things.

**Comment by Ghommie** [comment]
> 
> 
> so it takes 5 cakes to become a force 14 instead of a force 15
> 
> Great balance change. yes, this is totally how to nerf things.

Suggest a new divisor/modulo value then.

**Comment by Poojawa** [comment]
1 force and 1 throwforce.

handled.

**Comment by Ghommie** [comment]
I guess that's what I deserve for suggesting an idea you were hostile to in the first place.

**Comment by silicons** [comment]
let's not make this worse with more cakehats.

**Pull request closed without merging**
