### PR TITLE
[Testmerge] The Skeld

### PR DESCRIPTION
**Pull request by Xantholne**
## About The Pull Request

Adds a new map, the Skeld. Yes, that map, you know the one.

## Why It's Good For The Game

It's really not but it's an interesting map that the people I have been sharing the development for the last 5 weeks with have been getting more excited about. It's a bit smaller station size wise than box and meta and seems to be well received aside from (What was to be the april fools day) meme map, after the meme testing is over and enough issue reporting is found it'll be made into a standard rotation map.

I'm not sharing a map overview right now as we are testing because there are many secrets I want you all to find for yourselves first, but you'll get to see the spawn anyways.

## Changelog
:cl:
add: Added The Skeld
add: Kinda sus crewmembers.
/:cl:

dreamseeker_xjuJefHS6Q
dreamseeker_cQdXHRC4AD
dreamseeker_bNni0BDm4u
dreamseeker_m2cWyDsLdO

### CODE REVIEW

**Comment by moltoretardo** [comment]
Based, speedmerge please

**Comment by Linzolle** [comment]
but why

**Comment by Hartmann-von-Berlichingen** [comment]
yay julio :hug:

**Comment by JogBoba** [comment]
Flashes in robotics cannot be placed in cyborg heads, even after being screwdrivered.

**Comment by BlueWildrose** [comment]
Xenobiology:

- Should start with a box of syringes
- The freezer is rotated in the wrong position, the pipe is facing the opposite direction.
- One of the scrubbers is missing in the top left pen.
- needs more firelocks and the fire alarm
- this is just my opinion but it spawning with a xeno egg is going to just invite so many problems that could go very wrong lol

**Comment by LordSaladin** [comment]
a smaller non pubby map would be great for lowpop even if it still has amongus stuff, but can we call a emergency meeting on it?

**Comment by zeroisthebiggay** [comment]
this map is huge and consists of nothing but pure empty space with pointless meaningless rooms

>It's a bit smaller station size wise than box and meta

the size is more comparable to delta infact
68747470733a2f2f692e696d6775722e636f6d2f63734432516f622e6a7067
this is fucking **lambda** as a size comparison
and it holds up pretty well in comparison to actually playable space which lambda lacks in with the excess of asteroids comprising half of its actually playable space
why's it so big

- edit: here's some actual criticism

>- everything is too big in general, too empty, lots of floorspace that goes unused
>- the departments are comparatively tiny to the sheer floorspace the massive hallways take up especially medbay
>- science is needlessly huge compared to its tiny brothers, departments should never be built as rings, because rings take up so much space
>- the station exterior is boring and lacks any solars or meteor protection, not only making this extremely unappealing looking but making this station completely and utterly vulnerable to **generic space dust**
>- ai sat was copypasted from lambda
>- eva was copypasted from box, come on
>- maintenance is barren and uninteresting detailwise with way too many rooms sanctioned off by walls as excuse for easter eggs when all this does is make the playable space smaller
>- way too few spawn markers, i get the point of heho amogus, but only one atmos tech and engi marker? really? you're forcing jobs to share spawn markers at this point
>- why does tech storage have five pairs of insuls
>- this entire map is just powercreeped actually
>- xenobio doesn't need six slimes can we stop making xenobio faster to powergame
>- the engine by default is a chonkmatter. this is among many issues; such as the lack of reinforced flooring which will cause the entire engine room to burn down from one pyroclastic anomaly
>- botany has a chemistry dispenser. why??
>- virology is pointlessly tiny and has no monkies
>- every head office is gigantic and then cmo and qm get shafted. at least be consistently gigantic

**Comment by zeroisthebiggay** [comment]
6iUm1SA
self explanatory
XjQeP7O
stacking walls looks bad and stacking windows looks worse
the fridge is accessible from maintenance here
nPdU3ma
you stacked windows ontop of one another here
also there is such a thing as too many lights
at least be symmetrical
also that camera lmao
DQhjNOt
try and wire this in game
go on

**Comment by BlueWildrose** [comment]
Oh right, that screenshot of xenobio reminds me.

Take a look at the xeno pen in any other map, like Box.
dreamseeker_2021-04-03_19-12-40

The way you have your shield generators set up right now is like **a door with its hinges on the outside**. Anyone turns on would have to be stuck on the inside until it gets turned off, and the fact that the shield generators are even placed like that to begin with essentially means that any threat inside of them can easily just destroy those structures to break free.

Not sure if that was a meme or not, but probably should follow the example presented in box instead.

Also, something commonplace with all xenobio maps is that **all the grilles are shocked** as well. Shield generators also require cable beneath them, so be sure to lay the cable under all that.

**Comment by Xantholne** [comment]
> Oh right, that screenshot of xenobio reminds me.
> 
> Take a look at the xeno pen in any other map, like Box.
> dreamseeker_2021-04-03_19-12-40
> 
> The way you have your shield generators set up right now is like **a door with its hinges on the outside**. Anyone turns on would have to be stuck on the inside until it gets turned off, and the fact that the shield generators are even placed like that to begin with essentially means that any threat inside of them can easily just destroy those structures to break free.
> 
> Not sure if that was a meme or not, but probably should follow the example presented in box instead.
> 
> Also, something commonplace with all xenobio maps is that **all the grilles are shocked** as well. Shield generators also require cable beneath them, so be sure to lay the cable under all that.

they arent anchored, need to be manually set up

**Comment by BlueWildrose** [comment]
> they arent anchored, need to be manually set up

At the very least, the layer of glass should be backed with two r-walls behind it, and otherwise a space to the right and left of the glass. If for instance you genuinely do trap a xeno in there, if there is any opportunity where they can destroy the shield generators, they will, and not everyone is going to want to take the time to put those r-walls up that were obviously overlooked.

**Comment by Xantholne** [comment]
> > they arent anchored, need to be manually set up
> 
> At the very least, the layer of glass should be backed with two r-walls behind it, and otherwise a space to the right and left of the glass. If for instance you genuinely do trap a xeno in there, if there is any opportunity where they can destroy the shield generators, they will, and not everyone is going to want to take the time to put those r-walls up that were obviously overlooked.

Was already changed to include

**Comment by Pontenerd** [comment]
Chemisty has no beakers or a grinder roundstart

**Pull request closed without merging**
