### PR TITLE
War Ops now informs the crew where the Nuclear Device is located when activated.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

War Ops now informs the crew where the Nuclear Device is located when activated. Note that this only applies when war is declared, and not during regular Nuke Ops. A message from Central Command will state the area it is in, and the exact GPS coordinates.

## Why It's Good For The Game

Most servers with Nuke Ops has this feature and it honestly increases the amount of fun for the crew by allowing them to have one final last stand instead of going "unga bunga where is nuke" until everything explodes because the Captain decided not to be a good Captain and not inform anyone of their death or where they lost the disk.

Again, this does not occur during regular stealth nuke ops. Only when the Nuke Ops declare war and go loud.

## Changelog
:cl: BurgerBB
balance: Activating the nuclear device during war-ops informs the crew of the nuke's position.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
'cops can just trigger nuke in area, unachor and hide.

**Comment by optimumtact** [comment]
you should make this PR on /tg/ when kevin denies it here

**Comment by Poojawa** [comment]
> 'cops can just trigger nuke in area, unachor and hide.

unless it was changed recently, anchoring the nuke leaves it solidly in place.

**Comment by lolman360** [comment]
you can trigger w/o unanchor

**Comment by deathride58** [comment]
War Ops almost always leave a blood trail, so the info this PR gives is almost always known by the crew unless they're legitimately incompetent or the nukies went for a stealth warops approach

**Review by deathride58 — DISMISSED** [review]

**Comment by Ludox235** [comment]
This doesn't really change anything considering the nukies can just trigger the nuke at like, the solar SMES so they can take the disk and just run the fuck out before anybody can retaliate, which happens already 80% of the time nukies win

**Review by silicons — APPROVED** [review]
ehhhhhh fine

**Pull request merged**
