### PR TITLE
Adds an event that speeds up/slows down atmos

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

As title.

## Why It's Good For The Game

Uhhhhhhh I dunno I think it's neat that I can do this without destabilizing the whole system. More events is nice, I guess, though this one's a bit of a nothing.

## Changelog
:cl:
add: Atmospheric Flux event
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
you scare me sometimes

**Comment by Linzolle** [comment]
hey putnam what the fuck

**Comment by BlueWildrose** [comment]
oh no.

**Comment by bunny232** [comment]
image

**Pull request merged**
