### PR TITLE
Für das Vaterland

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Änderungsprotokoll]
Bringt die Feuerkraft des Fuhrers zurück

[Warum]
Um zu helfen, die Entarteten zu reinigen

### CODE REVIEW

**Comment by lolman360** [comment]
good pr. a thumbsup is not enough so I leave comment.

**Comment by Trilbyspaceclone** [comment]
Why do I have a negative score?

**Comment by yourdoom9898** [comment]
@Trilbyspaceclone That means you've made more PRs tagged as a "Feature" than tagged as a bug fix. It's a holdover from TG good boy points

**Comment by deathride58** [comment]
y tho

**Comment by Poojawa** [comment]
None of these sprites are maintained. you'll have to ensure it works rather than just trying to meme stupid shit.

**Pull request closed without merging**
