### PR TITLE
[TESTMERGE READY] Ported a bunch of tg hydroponics content.

### PR DESCRIPTION
**Pull request by Useroth**
## About The Pull Request

https://github.com/tgstation/tgstation/pull/44322
https://github.com/tgstation/tgstation/pull/45840
https://github.com/tgstation/tgstation/pull/43896
https://github.com/tgstation/tgstation/pull/46986

It's not a 100% exact port, because we lack some stuff that tg has, like Ethereals or minor atmos features.

Let's see how it works out as a test and then see if anything needs to be modified for Citadel's needs.

## Changelog
:cl:
add: A bunch of newer tg plants
add: A bunch of newer tg plant traits
add: A couple of newer tg plant reagents
/:cl:

### CODE REVIEW

**Comment by Thalpy** [comment]
Could I also bug you to run debug > generate wiki chems then open the generated log for the new reagents in admin tools > logs and either send me it or append it to the wiki?

**Comment by Owai-Seek** [comment]
As someone who plays a lot of service, it's really nice to see additional stuff being brought over from TG. The only real concern I have Is that the Poppy mutation line might be getting a bit overpopulated. You need to make Poppy's into Lily or Geraniums, and then from there you need to make Bee Balm/Spaceman Trumpet. I think in (at least Bee Balm's case), you can end up mutating backwards.

**Comment by Trilbyspaceclone** [comment]
I dont mind to many options ill likely at a later date move bee palm into its own flower grouping if its a worry

**Comment by Xantholne** [comment]
Mmm blue glow fairy grass.
Definitely going to be making a lot of that now.

**Comment by ghost** [comment]
time to port ethereals honk

**Review by BlackMajor — APPROVED** [review]

**Pull request merged**
