### PR TITLE
Makes gear harness cover nothing

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

I did a PR for this earlier not realizing that the default is actually MORE covering than what it had. This is what I meant. I don't expect people to misbehave too badly when it comes to this.

## Why It's Good For The Game

My immersion!

## Changelog
:cl:
tweak: Gear harness now covers nothing.
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
Besides exposing genitals, what does this change?

I think it would be interesting to make the gear harness adjustable and have the alt-clicked variant be exposing genitals, and the non-altclicked variant as it was before.

**Comment by R3dtail** [comment]
+1 to Bluewildrose's idea.  all the other equipment is alt+toggleable to expose, this shouldn't be much different

**Comment by Hatterhat** [comment]
this might also affect wound protection (or a lack thereof) but if you're wearing a gear harness you're probably not expecting to get into fights

**Comment by Putnam3145** [comment]
Done.

**Pull request merged**
