### PR TITLE
Cream Pies now transfer a portion of their reagents on hitting someone

### PR DESCRIPTION
**Pull request by BlackMajor**
One line code change. Because it's funny.

This means one of three things are going to happen.
A) The clown roundstart pours his can of laughter into his cream pies to force people to laugh when pied.
B) An antag botanist cooks cream pies using death bananas to throw at people.
C) The CMO puts his healmix into pies.

All are funny.

### CODE REVIEW

**Comment by Thalpy** [comment]
Let me know when this is merged so I can proceed to turn chemistry into a pie factory.

**Comment by Thalpy** [comment]
Also maybe make the method = TOUCH

**Comment by BlackMajor** [comment]
Wait a minute this is an easily accessible 80u reagent container that is inconspicuous unlike a syringe gun, relatively easy to access roundstart (three cream pies roundstart on most maps) and applies its reagents through clothing.

**Comment by BlackMajor** [comment]
That's better.

**Comment by Ghommie** [comment]
Indent the reagent transfer under a is_mouth_covered check, currently it bypasses any sort of protection.

**Comment by BlackMajor** [comment]
> Indent the reagent transfer under a is_mouth_covered check, currently it bypasses any sort of protection.

Fair point mate but im indecisive on if it should ignore protection because it's funny despite realism, or cave to mouth being covered but bump the reagent transfer up.

I'm leaning towards letting it ignore protections, unless that's really big dumb, because that's funnier.

**Review by deathride58 — APPROVED** [review]
YOLOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
