### PR TITLE
Fixes and updates to auxmos, nukes SSadjacent_air

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

moved adjacency deferred updates to auxmos
fixes some deadlocks that cause DEFCONS
map templates use sleeping turfs instead of adjacency cuts that doesn't even work in the first place
shuttlemove air updates done correctly and done after the entire shuttle has been moved

## Why It's Good For The Game

please TM this for a bit

## Changelog
:cl:
del: Removed SSadjacent_air
tweak: moved adjacencies deferring to auxmos
fix: fixed a few DEFCONS caused by auxmos deadlocks
fix: shuttlemove and map template placing code should update correctly now
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
@Putnam3145 yours

**Comment by Putnam3145** [comment]
Auxmos.dll compiled for znver2, yeah?

**Comment by Putnam3145** [comment]
Not unlikely katmos is crashing.

**Comment by Putnam3145** [comment]
...Also may have messed up shuttles, *again*. Shuttles and atmos, lord.

**Comment by Putnam3145** [comment]
Okay, this is *definitely* crashing. I'll untestmerge it for now.

**Comment by Putnam3145** [comment]
note: this is not crashing

**Pull request closed without merging**
