### PR TITLE
Reverts improv small arms, makes guncrafting easier and faster

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Removes the added features from  #12386 
-Removes the improvised pistol
-Removes the improvised laser
-Removes all associated parts, ammo, etc

Cleans up a few guncrafting things
Makes the crafting names not obtuse
Keeps the changes to sprites, loot tables, crafting menu, etc

Additions by @kappa-sama 
Removes barrel recipes, replaces them with regular pipes
Reduces a lot of the time needed to craft guns
Removes the hand saw as it is no longer relevant
Shotgun balance
Other minor tweaks

## Why It's Good For The Game

Guncrafting has been made much less time consuming and less obtuse, craft times were chopped down and guns can be made from pipes again instead of crafting barrels and adding another pointless layer of craft time to guns.

It is in my opinion the craftable pistol and laser are absurdly badly done in almost every respect, and are weapons that are so obscenely annoying to craft and use that they are not worth anyone's time to find the parts for and spend the effort to make. 

The pistol itself is complete rubbish. It takes a frankly absurd amount of material to craft (15 plastic and 3 plasteel for a handgun) and it fires so slow and does so little damage that even dual wielded you would be wasting your time. 
For the same amount of effort and time you could make a spear, a bolas, and have killed 3 people before you have one handgun.

The laser is nonsensical for different reasons. The fact you can cobble together a *lethal laser weapon* from scrap is complete bunk. The upgrade racks it up a notch by being so utterly byzantine that you would be better off just going to cargo and ordering a box of actual laser guns. When the autolathe exists, you shouldn't have to require a glassblowing kit to make a decent lens. Tier 4 stock parts are something more bleeding edge than the actual guns you're emulating, why does a shitty scrap beam gun require it?

I don't think it's worth the time to improve the code. The sprites are still there, if you want to bother to make improv handguns that don't suck ass.

## Changelog
:cl: Yakumo Chen, kappa-sama
del: Removes improvised handguns
del: removed handsaws, improvised gun barrels (you can use atmos pipes again)
balance: Guncrafting is less time and resource intensive
tweak: Item names in guncrafting are user-friendly.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Ah finally, now I can try my hand to make these not shite as weapons 👀

**Comment by silicons** [comment]
doesn't compile

**Comment by YakumoChen** [comment]
issue was removed file wasn't edited out in tgstation.dme

**Comment by ghost** [comment]
> issue was removed file wasn't edited out in tgstation.dme

oops

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
