### PR TITLE
Ports a bunch of VG's AI sprites

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Adds many new AI core displays and holograms from /vg/ station, including from https://github.com/vgstation-coders/vgstation13/pull/1599 this PR and probably several others I can't find. Didn't include all of them (like the 4chan ones), but kept the ones I did like.

## Why It's Good For The Game
image
image

The holograms from "male" and after (ninja isn't selectable since it only had one face, sorry) and all the AI cores after "Techdemon" are the added ones.

## Changelog
:cl:
imageadd: New AI Holograms and Displays! Ported from /vg/station.
/:cl:

### CODE REVIEW

**Comment by dapnee** [comment]
AI malf boy sprite is broken from what I can tell from just looking (top left pixels of the sprite) and I personally dislike the idea of child like holograms being an option on a 18+ server. Rest of it is fine and stuff I would like to see in game.

**Comment by Ghommie** [comment]
> 
> AI malf boy sprite is broken from what I can tell from just looking (top left pixels of the sprite)

Nah, that's the icondiffbot occasionally having some issues parsing animated icon states into .gif . Checked and it's fine.

**Comment by dapnee** [comment]
Based Ghommie as normal. I’ll keep that in mind.

**Comment by lolman360** [comment]
why not the 4chan ones

**Comment by ghost** [comment]
does cit code even use the dead sprites?

**Comment by YakumoChen** [comment]
@lolman360 we aren't 4chan

pretty sure we do use the dead sprites, I'm leaving them in regardless for reference sake.

I can remove the hologram sprites with a one line change without editing the dmi. I was thinking that too but it seemed to much like an edge case, I'll go ahead and do that.

The sprites all work, I tested them in game.

**Review by silicons — APPROVED** [review]

**Pull request merged**
