### PR TITLE
Ports Colorist Quirk and Hair Gradients Preferences

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

Ports these two PRs:

https://github.com/tgstation/tgstation/pull/59435

https://github.com/tgstation/tgstation/pull/59545

These give you the option to color your hair with gradients through the Colorist quirk.  It's a neutral quirk that spawns a dye item in your bag that lets you color your hair.  You can also order more from cargo and there's some in vendors.

Thanks to everyone on the original PRs.

Also big thanks to @SandPoot for making this a customization pref option!

## Why It's Good For The Game

More customization options are good.

## Changelog
:cl:
add: Added the ability to dye your hair with gradients by using a hair dye spray.
add: The new Colorist quirk, allowing you to spawn with a hair dye spray.
add: Adds Hair gradients to preferences
imageadd: Three new hair gradients, a pair of shorter fades and a spiky wave.
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
This feels like this could just straight up be a character customization, but it's fine being a dye for now - especially given the amount of shenanigans that'd have to be coded.

**Comment by keronshb** [comment]
> 
> 
> This feels like this could just straight up be a character customization, but it's fine being a dye for now - especially given the amount of shenanigans that'd have to be coded.

Probably yeah.  The better bet right now is to introduce it this way, and then try to figure out the customization option later.  then this way you can also change colors while in game too.

**Comment by BlueWildrose** [comment]
> > This feels like this could just straight up be a character customization, but it's fine being a dye for now - especially given the amount of shenanigans that'd have to be coded.
> 
> Probably yeah. The better bet right now is to introduce it this way, and then try to figure out the customization option later. then this way you can also change colors while in game too.

Imagine the possibilities with how this could be used for customization.

You could have an actual rainbow slimeperson.

**Comment by SandPoot** [comment]
And so, it now has pref options.

**Pull request merged**
