### PR TITLE
bulky belts

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
belts are bulky now

## Why It's Good For The Game
allows less storage in storage in storage
step one of many on the painful road of storage tweaks *sigh

## Changelog
:cl:
balance: belts are bulky now
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
deadass just nerf the heirloom briefcase????? boxes are till normal and can hold the same shit as belts

**Comment by Sishen1542** [comment]
> deadass just nerf the heirloom briefcase????? boxes are till normal and can hold the same shit as belts

belts have whitelisted items that are larger than what can be allowed in boxes.

**Comment by lolman360** [comment]
like what

**Comment by Linzolle** [comment]
> 
> 
> > deadass just nerf the heirloom briefcase????? boxes are till normal and can hold the same shit as belts
> 
> belts have whitelisted items that are larger than what can be allowed in boxes.

Then only nerf the sec belt? As far as I can tell, only the sec belt can hold any items that are normal-sized.

Update: Okay I'm wrong the circular saw is normal sized as well, but I still don't think this is a good change.

**Comment by IronEleven** [comment]
Off the top of my head this hurts:
CMO's using the belt defibrilator
Clock cultists concealing their toolbelt to blend in better

**Comment by silicons** [comment]
I don't like this.

**Comment by deathride58** [comment]
I also don't like this.

**Comment by Sishen1542** [comment]
storage rework when, KEBIN

**Comment by silicons** [comment]
soon

**Pull request closed without merging**
