### PR TITLE
Thermite reskin

### PR DESCRIPTION
**Pull request by katnep**
I reskined the thermite becuase crow challenged me to do a better job will include a link in a sec

### CODE REVIEW

**Comment by katnep** [comment]
image

**Comment by TalkingCactus** [comment]
What if you sprited it completely different from a normal spray can and made it auto-light the thermite on the wall after spraying. Or made it just a normal spray bottle so it can be used as a stealth item.

**Comment by katnep** [comment]
i mean i could i was literally just doing this because crow challenged me to and it turned out alright

**Comment by TalkingCactus** [comment]
2 missing pixels, though

**Comment by katnep** [comment]
those dots were remenents of the line across the bottle one sec

**Comment by katnep** [comment]
image

**Comment by katnep** [comment]
i think the point of it is to go loud with a hole in the wall though so making it pretty much undetectable would make it a bit overpowered

**Comment by ghost** [comment]
the bottle itself is supposed to be a knockoff of the space cleaner bottle as sort of a joke which this still achieves

**Comment by katnep** [comment]
syndicatebrand- TOTALLY SPACE CLEANER

**Comment by Axolotl123** [comment]
The spritzer of it should atleast be a different color, like the color of an actual space cleaner bottle.

**Pull request merged**
