### PR TITLE
New space ruin! Space Carp Hunters

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

A armed based full of armed men, booze and carp...
Things of note! 
- 2 Magnetic harpoons 
- 6 Harpoon shots
- 2 Synda sleepers!
- 1 Adv scaple
- Some mats like silver/plasma 
- 2 Old space suits
- 1 E-Cutless
- 3 Laser guns
Tons of carp meat and light beer
## Why It's Good For The Game

A new space ruin that can be hard to get into as well as get more loot from.
Even has a sorta mini boss! - The Grate White Carp

## Changelog
:cl:
add: New space ruin has been sighted in the local space, seems some of the people are their hunt down carp and sell of the meat. Perhaps give it a look!
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
putting an esword in space is a bad idea?

**Comment by Trilbyspaceclone** [comment]
@timothyteakettle Esword is a drop from one of the mobs
You get one from cave ambush as well.
Its fine loot wise

**Comment by silicons** [comment]
ok but why

**Comment by Trilbyspaceclone** [comment]
@kevinz000 New space ruin thats harder then most to get at, no gps so you cant just know were it is and with fair and balance loot

**Comment by Ghommie** [comment]
This gives me some ideas. But this is fairly bad, with pirates simple mobs that will probably be maimed by their own carps because factions and generic gamer loot.

**Pull request closed without merging**
