### PR TITLE
Modern modern

### PR DESCRIPTION
**Pull request by Poojawa**
For realsy this time.

It completely up to date with TG as of 1/23 0500 Texas Time

Includes mentor system, all the mob code is preserved as well. Digilegs were enabled for furry races as well, they only respect primary mut color for the moment. 

Furry races have been migrated to furrypeople.dm in species_types due to tg refractor. Gee golly. sure am glad non-proc editing code was allowed to infest main files again.

Furry greyscale stuff is in a .dmi in the icon/mob/special folder for reference. No point in having our sprites go missing on the off chance of a mistaaake. 

Cryo sprites are back to paradise ones, I confirmed they work just fine. Also nabbed a neat cryo alarm that isn't the fucking microwave ding.

### CODE REVIEW

**Comment by Poojawa** [comment]
Also purges unused maps that are depreciated by now.

**Comment by Poojawa** [comment]
Good to merge I'll do bleeding edgy PR for any testing you wanna do Jay

**Review by LetterJay — APPROVED** [review]
I can't see anything wrong. I tested it and it worked, nothing stood out as being broken.

**Comment by Poojawa** [comment]
Good to merge whenever then. fweee

**Comment by LetterJay** [comment]
If something fucks up I can always revert it.

**Review by TalkingCactus — COMMENTED** [review]
currently inactive, sorry

**Pull request merged**
