### PR TITLE
My balls are raw. Meatballs, that is.

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

Putting slabs of meat in a processor will now produce a raw meatball, instead of an already fully-cooked meatball.

## Why It's Good For The Game

Slightly more immersive cooking.

image

## Changelog
:cl:
tweak: Meatballs now spawn raw from food processors.
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
Meh seems pointless to me and you could argue the processor does heat things up.

**Comment by MrJWhit** [comment]
Tup, grinding meatballs does not add enough heat to **cook the meat**. If your blades have friction, your blades have fucked up.

**Comment by timothyteakettle** [comment]
good change always wondered why meatballs didn't need cooking but sausages did when placed in the food processor

**Comment by Ludox235** [comment]
fetish pr

**Comment by Ragolution** [comment]
Honestly tedious

**Review by Ghommie — APPROVED** [review]
ss13 microwave cooking is still several magnitudes easier than real life cuisine.

**Pull request merged**
