### PR TITLE
Removes syndicate uplink items from the autolathe

### PR DESCRIPTION
**Pull request by CameronWoof**
Did you know that a box of 40 riot foam darts would run a traitor two telecrystals, if they couldn't print them out en masse from an autolathe for free? 

Because they do.

:cl: CameronWoof
del: Riot foam darts from autolathe
/:cl:

### CODE REVIEW

**Comment by cebutris** [comment]
Misleading title. Also, other ammos for other guns that can be purchased in the uplink are available to print from the autolathe.

However this is totally justified since foam guns are a lot more common now

**Comment by CameronWoof** [comment]
All of my PR titles are accurate.

**Comment by cebutris** [comment]
It's accurate but a little misleading is all. Not a huge deal

**Review by deathride58 — CHANGES_REQUESTED** [review]
Modularize this.

You can remove a design from the autolathes by changing build_type to null or changing category to list().

**Comment by GuppyLaxx** [comment]
`>>>>>riot darts are such an amazing problem even worth it for a pr`
C'mon man, there's seriously worse shit everywhere, you can make stunbatons in this game, you can make chainsaws, you can make yourself a shotgun, but riot darts are too op so lets nerf them am i rite, punish traitors for having a bit more than nothing in their skull and thinking "maybe i can go to an autolathe and get some ammo for my `toy` gun that does virtually nothing in a legit fight"

**Comment by Poojawa** [comment]
GuppyLaxx confirmed person who thinks mobbing people with free disablers is Fun and Exciting.

**Comment by cebutris** [comment]
Disablers that can be reused indefinitley, no less!

**Comment by GuppyLaxx** [comment]
oh man i couldnt `already do that before and even better since they're unlimited range`

**Comment by Ragolution** [comment]
with the new combat changes I can definitely see this as necessary

**Review by Poojawa — APPROVED** [review]

**Comment by ZeroNetAlpha** [comment]
I don't like this change to be honest. There could be something else done like making riot darts have a limited use. I'll be making an alternate PR soon.

**Comment by Dankseed** [comment]
If we're removing the ability to make ammo (.357, 9/10mm, ect) from the autolathe, we need a replacement. I can't imagine only being able to get it by spending TC. I was thinking maybe make autolathes under a bit more security than right now, so it is harder to hack for ammo.

**Comment by lightcat** [comment]
**opinion alert**
What type of server are we going for?
A server whose only game play is locked behind being an antagonist?  A highly focused RP with literally only thing to do is rp? Because thats were we are headed and I dont like it.

**Lets first talk about the Riot darts.**

- People use them to have fun and play a mini game of war, sometimes harassing other people. Thats the main purpose.
- To mess around with security and heads in a green shift.
- Antagonists use them rarely but it can happen
- Self Antagonists can use them (Much better methods though and is not justification alone to remove a feature like this.)
- Can be used for rape ERP
- Can be cleaned with something as simple as space cleaner

Easy to pick up and is just a little fun thing in the game thats now going to be ruined for most of these purposes because someone didn't like them. Literally, no reason given other than some kind of obscure smart comment.

We are heading into a direction where people can't even goof around with things anymore for fun. I wouldn't be surprised if the security Protolathe soon required an ID with permissions or if most events just got outright removed for having the possibility to cause chaos.

**In case someone wants to bring it up no I don't have it out for anyone here or criticize everything the development team does. There are quiet a lot of PR's that I just dont commit on or even see but like their changes.**

p.s (I think democracy has ya in the votes.)

**Comment by cebutris** [comment]
If you want to goof around with darts, use actual darts. Riot darts are basically a free ranged stun that can be reused indefinitley (disablers require charging, shotguns require additional ammo. Darts can be picked up). The guns were added for people to goof around, but NOT with riot darts.

**Comment by deathride58** [comment]
The thing about riot darts?

With combat moving from stun-based combat to stamina-based combat, riot darts are a legitimate weapon now. They can shred your stamina with only a couple of shots.

There are only three alternatives to this PR to alleviate the brand new ggnore meta of using riot darts in combat: make riot darts deal less staminaloss, move riot darts to the sec autofab, or make it so you have to hack a dart gun using hard-to-get items to fire riot darts.

**Comment by Michiyamenotehifunana** [comment]
Giving toy guns horrible accuracy seemed to work for a while until I decided to rebuff the foam magrifle's accuracy. 

Perhaps reducing the maximum burst size of all toy guns can help alleviate this issue. The insane rapid fire capabilities of the toy guns seems to be one of the biggest causes of this issue, as even gimping their accuracy doesn't help much, since it ends up being a spray-and-pray kind of deal and at point-blank range it doesn't even make a difference.

**Comment by ZeroNetAlpha** [comment]
Totally be fine with making all foam guns semiauto

**Comment by improvedname** [comment]
You can make a literal shotgun which can do better then a foam gun xd

**Pull request closed without merging**
