### PR TITLE
Bleeding Changes, Armor protects blood loss

### PR DESCRIPTION
**Pull request by Poojawa**
Reopening #9402 as an alternative to #9682 because this has more effort than just completely absolving bloodloss at range.

Blood ratios made a lot more forgiving, armor protects additional bleeding.

More drugs heal blood loss rate as well, though Gauze is still superior

### CODE REVIEW

**Review by silicons — DISMISSED** [review]
why are we throwing in so many probs() and rands() we really don't need so much randomness in core combat code.

**Comment by Poojawa** [comment]
because TG's code has it and it's better than 100% assured blood deletion

**Comment by silicons** [comment]
ehh ill read it again in a day

**Comment by silicons** [comment]
actually yeah i don't like this.
armor shouldn't be a thresholded thing in general but even if it is there's no reason for the prob(40).
old tg code was just for effects, not damage.

**Pull request closed without merging**
