### PR TITLE
Attempts to ReAdd Sing/Tesla to Pubby

### PR DESCRIPTION
**Pull request by lightcat**
This is my first Pull Request so I have no idea if this is actually the file wanted. Trying to push out some changes to pubby. but something saying 100,000+ deletions tells me this is probably flawed...

* Added The Singularity/Tesla Setup back onto Pubby Station
* Removed pipe leading from Atmospherics into SME (SME no longer exists.)

Re Added engines to add map variety and to please the group that likes them.

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
USE THE MAPMERGER

**Comment by Ragolution** [comment]
But why?

**Comment by nik707** [comment]
mapmerge

**Comment by lightcat** [comment]
Working on the map merger.

**Comment by Tupinambis** [comment]
I'm gonna leave a fat thumbs down here. The Tesla was replaced for good reason. It's a simple engine with limited customizability, hugboxed to shit, you can  just leave it alone forever. But the moment a wire is cut by an antag, the thing will loose and there is nothing to stop it. Not only does this cause widespread destruction for little effort, but it also lags the server a ton. Keep that in consideration before you add something purely for variety.

**Comment by nik707** [comment]
> I'm gonna leave a fat thumbs down here. The Tesla was replaced for good reason. It's a simple engine with limited customizability, hugboxed to shit, you can just leave it alone forever. But the moment a wire is cut by an antag, the thing will loose and there is nothing to stop it. Not only does this cause widespread destruction for little effort, but it also lags the server a ton. Keep that in consideration before you add something purely for variety.

>easy as shit to loose and end a round
>hugboxed to shit
?????
these are two extremely different ideas

**Comment by Tupinambis** [comment]
It's hugboxed because, there is literally no risk in anything unless you just neglect to set it up properly in the first place. The only risk is antags looking to kill their targets without any effort besides deconning a wall and snipping a wire

**Comment by lightcat** [comment]
It's going to be a few days before this is updated.

**Comment by silicons** [comment]
stale PR and I don't think we should have tesla back on pubby, maybe give them the parts to make one if they want or anything.
SM is the future, sorry.

**Pull request closed without merging**
