### PR TITLE
Prevents SMES from outputting power if in a loop

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title.

## Why It's Good For The Game
Maybe? putnam thinks this could affect performance positively

## Changelog
:cl:
tweak: SMES will no longer output any power if in a loop.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.

**Comment by shellspeed1** [comment]
> This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.

This is really easy to do and hard to catch too

**Comment by Putnam3145** [comment]
> This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.



> > This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.
> 
> This is really easy to do and hard to catch too

It is now trivial to catch because the SMES tells you if this is happening. Also, it wouldn't cut off power? I'm pretty sure the actual engine's power output would still be applying.

**Comment by keronshb** [comment]
> > This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.
> 
> > > This is way to get a 0 TC power sink that's hidden with 4 cables and some gloves. Just connect the power output of the engine to the powernet of the station to instantly cut power.
> > 
> > 
> > This is really easy to do and hard to catch too
> 
> It is now trivial to catch because the SMES tells you if this is happening. Also, it wouldn't cut off power? I'm pretty sure the actual engine's power output would still be applying.

Step 1 do the loop
Step 2 put tile back on
Step 3 laugh as no one can figure this out because no one looks at prs/git/code (seriously, people still don't know the tesla has a counter among other things).

The rest of the station won't be getting power unless the SMES are outputting it or if the engine is wired directly to the grid, which this promotes doing that more now because of this weird SMES nerf.

**Comment by DeltaFire15** [comment]
I do not think this is needed, as using SMES as budget inline batteries, sometimes even manually toggling output / input for better effectiveness, doesn't seem like a bad thing.

**Comment by silicons** [comment]
Not feeling it but only because of what @DeltaFire15 said
We really do want to get power priorities at some point for powernets.

**Pull request closed without merging**
