### PR TITLE
removes mood buffs from vore/orgasms.

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Removes mood buffs from vore/orgasms

## Why It's Good For The Game
having erp mechanics that can be used to enhance your mood (which impacts move and action speed) is bad and abusable. This change keeps erp and gaming separated as it should be.

## Changelog
:cl:
del: Orgasms and vore no longer enhance your mood.
/:cl:

### CODE REVIEW

**Comment by LeadOnTaste** [comment]
Since speed and actionbar buffs and debuffs are barely detectable, this PR is useless. Either just nerf the buffs and debuffs, or just don't think about removing it, fool. It is not an issue as much as you think, Zara. For the fuck sake, stop turning Citadel into some wacky Furry Lifeweb. We want our old mechanics back, same with condoms, suits, machinery and toys from Skyrat and organs from there (they have anus). And masturbation emote/sub-verb for climax.

**Comment by TripleShades** [comment]
> 

Sir, I don't think you realize where you are.

**Comment by Putnam3145** [comment]
i kinda agree with just nerfing the mood changes, i.e. just setting them to 0, mostly because that's just a simpler way of doing it

**Comment by silicons** [comment]
at this point i'm going to say
god
i hate both sides

i'm not going to decide this pr myself but how about we

1. don't fill the game with 200 sex toys and organs, if you want to ERP emote it and don't fill the hall with cumstains
2. don't hunt down every ERP related feature because it gives some minute buff to gameplay until it's actually a problem. who tf is going to cum for that +whatever mood boost to validhunt with lmfao.

these two things sound contradictory but it's getting to the point where we're doing this every goddamn month.

**Comment by Putnam3145** [comment]
i used to powergame with it but i stopped because it's tedious and of minimal benefit

**Comment by ktoma36** [comment]
Ah yes, the powergame vore situation where you get vored in order to move faster with the mood buff. That goes away when you are unvored. Good logic there. Also if someone is using Vore for any kind of combat (where a buff like this would be applicable) is already a violation of rules.

**Comment by ktoma36** [comment]
I will say though the image of someone jacking off in order to try and outrun security is hilarious since there's much easier ways to boost mood (food, showers, optimist trait <if that's not been axed already>, drugs, being an antag)

**Comment by silicons** [comment]
i lied

i'm closing this with this reasoning, since yes, i hate powergaming erp as much as the next person but i'm also not a fan of witch hunting erp.

image

if anyone is actually upset, come talk to me on discord

**Pull request closed without merging**
