### PR TITLE
the travelling trader midround event

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
this adds a weight 10 midround event to the game that spawns a travelling trader mob who despawns after 15 minutes
they ask for one specific item out of a pool of possible items, based off the type of trader they are
upon giving them the requested item, they hand you a reward, also based off the type of trader they are

also fixes a small pet carrier bug (relevant because the rewards from the animal hunter all come inside a pet_carrier/bluespace (jar))

it also adds an embeddable fork, some kegs, and an infinite sticky tape roll into the game, as they're used for some of the reward pools

the subtypes so far:
cook - asks for a crafted food item
bartender - asks for a drink not found in the base dispenser reagents
animal hunter - asks for a station pet (if none happen to exist, asks for a monkey or a corgi, randomly)
surgeon - asks for a random body part/organ
botanist - asks for a random plant
artifact hunter - asks for something more unique or rare

also the animal hunter is special because their rewards consist of a (usually) hostile mob picked from a list, contained within a jar, and it's friendly specifically to the person who handed the item into the trader by adding their mob faction to its factions

## Why It's Good For The Game
we need more nice midrounds and this should be a pretty nice one for giving people something to do

## Changelog
:cl:
add: travelling traders from another dimension can now visit the station in search of something specific, and reward you for giving it to them
fix: small error with pet carrier logic fixed and also making sure simple mobs are catered for properly inside bluespace jars
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
still going through this and removing bugs but it should be in a fully working state extremely soon (like within the next hour i hope)

**Comment by timothyteakettle** [comment]
i've tested it and everything works without bugs now, so hopefully travis stops screaming

**Comment by Echopsychotic** [comment]
This seems like a interesting addition to midround and hopefully crew don't just ignore them or they don't do any trading.

**Comment by IUrmYeah** [comment]
Would like to see this in game. Just a suggestion, but how about a _**super rare**_ item unique to each trader?

**Comment by Echopsychotic** [comment]
Like what? A die of fate? or have them be associated with the ruins on lavaland?

**Pull request merged**
