### PR TITLE
shotgun pointblanking people actually throws them

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
manual port of tgstation/tgstation#47443
## Why It's Good For The Game
shotguns
## Changelog
:cl: Ryll/Shaps, ported by Hatterhat
add: Point-blanking people with shotguns actually throws them backwards!
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Why do we want to make shotguns hard stun tho

**Comment by silicons** [comment]
delta lookin' 4head

**Comment by nik707** [comment]
Also gonna leave this one because as Tril said >more stuns

**Review by nik707 — APPROVED** [review]
ok nvm its fine

**Pull request merged**
