### PR TITLE
Makes plasma men not rad nor hunger proof

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Plasmamen suits are 95% rad proof anyways, why would they not eat?
Anithugboxing

[why]
Hugboxing at its finest here...
Lilly-Trilby-Cat-Fail-CoderToday at 12:00 AM
If I remove the no hunger and the rad proofing form plasma men. Your not going to yell at me correct?
Just to make this clear
PoojawaToday at 12:02 AM
that's fine.
@Bhijn (deathride58) Can I remove plasma men rad proofing and no hunger loss without being yelled at?
Bhijn (deathride58)Today at 12:05 AM
yeah

### CODE REVIEW

**Comment by Ragolution** [comment]
it's not really hugboxing it's trying to make them not shit

i don't care about the merge but it aint hugbox

**Comment by silicons** [comment]
Plasmamen dont' need nerfing.

**Comment by Trilbyspaceclone** [comment]
Please refer to the time stamp discussion on discord for reason why nerfing is 100% valid and necessary 
@Ragolution @kevinz000

**Comment by granodd** [comment]
The time stamp discussion provides no information as to how this is either "100%" valid nor necessary. Please elaborate.

**Comment by silicons** [comment]
put it actually in the PR I'm not hunting down a discord conversation when plasmamemes are pretty weak combat wise already.

**Pull request closed without merging**
