### PR TITLE
Fixes ever case I can fine of WT-550 Auto Rifle being called Auto Rifle and not Semi-Auto - SMG

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Its a SEMI auto gun...

[why]
Fixes the inconsistent naming of the WT-550 and it mixes people up

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Truns out my master is a bit messy

**Comment by deathride58** [comment]
"Semi-auto SMG" is extremely contradictory. Also I'm 90% sure it has burst-fire capabilities

Speaking of, remind me some time later tonight and I'll add the ability to fire most burst-capable firearms full-auto

**Comment by Catwyn** [comment]
> Also I'm 90% sure it has burst-fire capabilities

It has no burst-firing capability.

**Comment by Catwyn** [comment]
> > Also I'm 90% sure it has burst-fire capabilities
It has no burst-firing capability.

**Review by silicons — APPROVED** [review]

**Pull request merged**
