### PR TITLE
Commenting out pAI circuitry

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

circuitry is pretty op. removes the pAI part of it so you have to still manually activate your circuits.

## Why It's Good For The Game

prevents people from being able to have someone else think for their door bolting/flameshooting/item grabbing bullshit.

## Changelog
:cl:
del: commented out pAI circuitry, probably.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
An unfortunate hit to a lot of roleplaying circuit devices, but I suppose it is a far better solution than removing cloning or the system entirely

**Comment by ShadeAware** [comment]
On that note, prehaps a different circuit that simply allows you to put a pAI IN the device without giving it any control would be a good addition as a backup

EDIT: Now that I think about it more, would it be possible to simply comment out the activators of the circuit? That way, you preserve currently printable circuits (mostly) allowing a pAI to be put in while still neutering non-roleplay oriented circuits. Since, you know, they can't _activate_ things anymore.

**Comment by silicons** [comment]
i'm sure glad i'm ""on break"" and not touching this one lmfao

**Comment by Ghommie** [comment]
I'd rather hinder pAI circuits salt potentials (I already halved down the locomotion circuit speed) than let these PRs stay open forevermore.

**Pull request closed without merging**
