### PR TITLE
*arf

### PR DESCRIPTION
**Pull request by NopemanMcHalt**
## About The Pull Request
Adds arf emote.

## Why It's Good For The Game
memes

## Changelog
:cl: Anonymous
soundadd: *arf.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Honestly I'm pretty sure we have enough dog emotes now with bark and awoo
Edit: Actually from listening to the sound it's just a shitty meme PR or really shoddily done. 👎

**Comment by NopemanMcHalt** [comment]
>Actually from listening to the sound it's just a shitty meme PR or really shoddily done

Shit they found me.

**Comment by NopemanMcHalt** [comment]
Ah shit I'm sorry.

**Comment by YakumoChen** [comment]
closing and opening it spams the PR in-game, please don't do that.

**Comment by JTGSZ** [comment]
I like dogs, so there should be more dog noises. this pr is great for me

**Comment by Linzolle** [comment]
the concept of a little arf emote is cute but the sound is just.. not

**Comment by NopemanMcHalt** [comment]
Welp, I can't find proper sound effect and it was meme-pr anyway. Closing for real.

**Pull request closed without merging**
