### PR TITLE
Adds a couple new bioware surgeries

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Adds two bioware surgeries:

1. Meningeal fortification, which halves all brain damage
2. Brain oxygenation optimization, which prevents soft crit

Also consolidates the bioware files a bit, since for some reason they were one file per surgery.

## Why It's Good For The Game

Bioware surgeries are cool. Nobody does them anyway, might as well add some stuff for the occasional Funny Business.

## Changelog
:cl:
add: Meningeal fortification surgery, which halves brain damage
add: Brain oxygenation optimization surgery, which prevents soft crit
code: Consolidated the 8 bioware files into 4 (not counting brain additions)
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
Brain oxygenation optimization, which prevents soft crit

gonna be the most used surgery you'll ever see

**Comment by timothyteakettle** [comment]
yeah uh, preventing softcrit is hilariously overpowered because you essentially have double health

**Comment by necromanceranne** [comment]
It's not quite double health, more like 30 extra. But it is pretty good.

**Comment by ghost** [comment]
Preventing softcrit seems excessively strong, considering the other way to do that currently is be an antag, or a tot with northstars

**Comment by DeltaFire15** [comment]
Yeeah uh hard no on the softcrit removal one.

**Comment by silicons** [comment]
kiiinda agreeing with @DeltaFire15 here on softcrit removal

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
> Yeeah uh hard no on the softcrit removal one.

^
PR seems okay other than that.

**Comment by DeltaFire15** [comment]
Closing due to staleness.

**Pull request closed without merging**
