### PR TITLE
Sound rework: Malf AI doomsday device alert

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
Changes the weird ass alert for malf AI nuke to something more...scary.

## Why It's Good For The Game
y͜͟҉́͢o͏̛̀͡ų̸̨ ̵͝a̶̷̕͟͟r̡̨é̶̛ ̷̷͡͡ņ̛͜͝ǫ̸̸́t̵͘ ̴̀͡͝͠g̵̡̀̀͢e̵̛t҉͟͞t̵̶̨̛i̸̕͝͝n̨̢͝g͢͡ ̵̵̢̀̀ơ͢ư͜t̛́͜

## Changelog
:cl:

soundadd: added a new malf ai nuke alert
sounddel: removed an old malf ai nuke alert
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
What about the second activist in 1990?

**Comment by YakumoChen** [comment]
Honestly you should just change the malf announcer to a dialup tone and it would be perfect.

**Review by Ghommie — CHANGES_REQUESTED** [review]
There are other aspects of the game where sounds should be improvemd, but the AI malf announcement honestly isn't one of them, at least not when the proposed one sounds more of a deepfried demon rambling. I had a laugh.

**Comment by dzahlus** [comment]
> There are other aspects of the game where sounds should be improvemd, but the AI malf announcement honestly isn't one of them, at least not when the proposed one sounds more of a deepfried demon rambling. I had a laugh.

It isn't the ai malf announcement, it's the AI malf nuke alert, have you heard the original? it has absolutely nothing to do with anything, no reference nothing.

would like a second opinion on this before going back to the drawing board.

**Comment by Ghommie** [comment]
My bad, I definitely wanted to say "AI nuke alert" but said "malf announcement" instead, not aknowledging malf AIs get their own traitor introduction sound.

And I still say that this is perhaps a bit too much of an earrape. Even though I still welcome you to make the doomsday device alert more threatening.

**Comment by dzahlus** [comment]
back to the drawing board

**Pull request closed without merging**
