### PR TITLE
Adds Anti Tank pistols

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate 
add: Adds the Anti Tank Pistol
fix: Anti Tank Pistol now chambers bullets properly.
tweak: sprites are slightly adjusted and the magazine in the sprites is actually the sniper's magazine.
add: Anti Tank pistol is now available to Nuke Ops
tweak: Anti Tank Pistol now has 3 times the recoil of the Sniper Rifle, 10 more firing delay, and has bullet spread.
/:cl:

Essentially a sawn-off sniper rifle. It has a handful of downsides that makes it plainly inferior to the sniper rifle. May need rebalances sometime in the future, but it isn't blatantly a superior choice to even the .357 due to its lower DPS, but has overall higher damage per magazine.

ATP
dreammaker_2017-09-17_21-17-31

### CODE REVIEW

**Comment by Poojawa** [comment]
Basically a bolter pistol.

I suppose, I don't know how often/if it'll be used though.

**Comment by jughu** [comment]
Stop adding stuff to admin only guns we already have alot of admin only add it if they auctally get a purpose to be used like a space ruin etc antags etc

**Comment by Michiyamenotehifunana** [comment]
🆑 Toriate
fix: Anti Tank Pistol now chambers bullets properly.
tweak: sprites are slightly adjusted and the magazine in the sprites is actually the sniper's magazine.
add: Anti Tank pistol is now available to Nuke Ops
tweak: Anti Tank Pistol now has 3 times the recoil of the Sniper Rifle, 10 more firing delay, and has bullet spread.
/🆑

With the ATP's issues ironed out, it would only seem fitting that it would actually be implemented in some form. Thus, an attempt at balancing it has been made, and nukeops can now purchase it for 14TC from their uplinks.

dreammaker_2017-09-18_21-01-16
dreammaker_2017-09-18_21-01-22

Note: The magazine is now an overlay, and the pistol can have a shot chambered in it with no magazine, however bullets cannot be directly loaded into it.

**Comment by LetterJay** [comment]
Is this ready? Also @Michiyamenotehifunana edit the OP with the CL info.

**Comment by Michiyamenotehifunana** [comment]
It's very much ready, however I wasn't able to test if it works absolutely flawlessly with nukeops. Not much to go wrong with the uplink code, though. Neither would there be issues with the pindicated variant.

**Pull request merged**
