### PR TITLE
Replaces real basalt for asthetic basalt in Anomalous Crystal

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

This replaces the real basalt tiles for fake ones in the Anomalous crystal.

## Why It's Good For The Game

These crystals are becoming exceedingly banbait because anyone can leave them around and/or drain atmos of an entire area in SECONDS because of it.  This way it fixes an issue while still keeping the general aesthetic of it.

## Changelog
:cl:
tweak: Replaced real basalt with fake basalt for the Anomalous Crystal
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
not a really fan of hugboxing this

**Comment by keronshb** [comment]
> 
> 
> not a really fan of hugboxing this

I don't want to hugbox it either but it just feels like banbait, like the Clown one.

**Comment by DeltaFire15** [comment]
Like Silicons, I don't exactly see this being a possibility as enough of an issue to remove it. Additionally, while unbreathable, transformed areas should still be perfectly livable with internals, ~~aswell as able to be refilled comperatively fast.~~
Therefore, closing this PR.

Edit: Apparently planetary atmos even in nonplanetary areas will be funny and slowly work it back towards the initial gasmix, still, not exaclty completely hazardous considering pressure levels do not require suit.

**Comment by Putnam3145** [comment]
> aswell as able to be refilled comperatively fast.

can you make the turfs not planetary atmos somehow cause that's the only possible way to refill

**Pull request closed without merging**
