### PR TITLE
Adds in stim pillls to Medical department vendors! [Coin only to get stim pills]

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]: 
Adds in 1-3 stim pills into each medical vendor that is used for item/clothing for departments 

[why]:
Long hard work days now are slightly less horrible, NT has teamed up once more with Med-Co to add in marked up stim pills to get there workers to pay even more to there own employer!
There coin only and can give people the little bit of speed they need to be able to do what needs to be done before [ EVERYONE DIES AND WERE ALL SAD EVENT]!
Now medics can get to dieing/dead people faster

### CODE REVIEW

**Comment by deathride58** [comment]
Maybe as a premium item for medical vendors, but this is just straight powercreep due to the mass availability of departmental clothing vendors all around every map

**Comment by Trilbyspaceclone** [comment]
Sure thing
I mean Med ↓

**Comment by CameronWoof** [comment]
This is an extremely strange PR. Why are these being put in clothing vendors? Why is it only available to Medical staff, _except_ for Atmospherics, which also gets one? 

The only place this would make sense is as a premium item in the NanoMed machines in Medbay.

**Comment by silicons** [comment]
No. Too much powercreep.

**Pull request closed without merging**
