### PR TITLE
Helter-Skelter.

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

The final frontier can be dangerous. Hostile alien species, apocalyptic death cults, _people not being who they claim to be_ - these aren't problems that impact Nanotrasen alone. People don't always make it from point A to point B, as can be seen by the shipwrecks that litter the stars. _Among them_ is one that looks oddly familiar, but you can't quite put your finger on why...

(It's not ready yet, but I'm getting it online at least. A preview for those who don't care much about spoilers: https://cdn.discordapp.com/attachments/336748540690825216/760608937741123585/hs.PNG)

## Why It's Good For The Game

More space ruins never hurt, and if there's a time to add this, it's now.

## Changelog
:cl:
add: Adds the "Skelter" space ruin
code: Creates a few new area designations for the Skelter
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
That didn't take long

I like the reference but I would prefer you didn't just litter a random empty ruin with a bunch of bloody 45s

**Comment by EmeraldSundisk** [comment]
I wouldn't really consider two "a bunch", but you did remind me to provide an image for anyone interested.

**Comment by YakumoChen** [comment]
It is a bunch,  for free at that. M1911 is also a revolver strength weapon. There's enough free guns in space and a knife instead still suits the reference fine.

**Comment by EmeraldSundisk** [comment]
Good point on the knife...still wanna see about a weaker ballistic pistol though.

**Comment by YakumoChen** [comment]
Consider something like a no mag sketchin? The gun is fine if it can't hold ammo I suppose, there just needs to be less free guns in space, not more

**Pull request merged**
