### PR TITLE
unmodularize hulk but this time it works

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
stealing @Ghommie  job

## Why It's Good For The Game
code

## Changelog
:cl:
code: modular is gone
/:cl:

### CODE REVIEW

**Review by Putnam3145 — APPROVED** [review]
toughest review yet

**Review by Putnam3145 — CHANGES_REQUESTED** [review]
wait actually hold up chief gotta update the .dme

**Comment by ghost** [comment]
pranked idiot this was all a plan to test your skills (/s)

**Review by Putnam3145 — APPROVED** [review]

**Comment by Putnam3145** [comment]
now where could my travis be

**Comment by Ghommie** [comment]
"but this time it works"... Wait, what? I mean, I recall playing against a tk-xray-hulk-midget-probably-not-fly-man before but that was days ago.

**Comment by ghost** [comment]
"this time it works" is because i forgot to unload the modular file from the dme

**Pull request merged**
