### PR TITLE
Syndicate borer added

### PR DESCRIPTION
**Pull request by ktccd**
:cl: ktccd
add: Syndicate agents, ~both the nuclear variant and~ **only** traitors, can now purchase our Syndi(tm) brand cortical borers! Nigh-guaranteed to be loyal to you and aid you in your mission, these borers sport all the latest and greatest of borer technology. _Reproductive capabilities may be void in certain states. Seller not responsible for providing souls to be housed in the borer body, please contact your local Syndi(tm) retail outlet for further customer service, refunds are available_
/:cl:

[why]: # 
Because borers are fun and provide some interesting ways to use them as a traitor. The icon for the item itself is a place-holder, as I lack spriting abilities and it looks ok as it is at least.
The borers of this variant are incapable of reproducing and will greentext together with their owner, which is not necessarily the same person as their host. An owner COULD for example buy a borer for their teammates, or send them to take control of a high-value host.
This kind of borer is a subtype of the regular kind, so it allows the possibility for further modifications if that's something we want, such as adding other chemicals to their production, though I want this PR to work as a basic set before I try anything weird.

### CODE REVIEW

**Comment by ktccd** [comment]
I would like some feedback on costs. I put it at 5TC, because I honestly don't know how much things are worth in the syndicate toolset. It kind of looks like things with high-killing power costs more than utility and support items...

**Comment by katnep** [comment]
At least 10tc and probably disable it on nuke ops

**Comment by ktccd** [comment]
Don't nuke ops explode when they die anyway? How would a nukie abuse this? O.o

**Comment by katnep** [comment]
Well nuke ops has a lot of options as is, and being able to get free adrenals/healing is pretty ridiculous

**Comment by katnep** [comment]
Either make a nuke ops grade one that costs more or disable it on them and around d 10/12 on Traitor

**Comment by ktccd** [comment]
There, added in and done. Also configured it for surplus shenanigans.
Notes for the future:
If it turns out that this item doesn't get ghosts to join up often enough, then it might be a good idea to disable surplus crate probability from it, as I don't think you can refund those items.

**Comment by ktccd** [comment]
Changed the changelog to show this.

**Comment by ktccd** [comment]
So is this fine for merging now?

**Pull request merged**
