### PR TITLE
12/21 modernizations from TG live

### PR DESCRIPTION
**Pull request by Poojawa**
rough porting of various major background code.  Doesn't touch game, datums, or modules yet

Not to be merged until lighting subsystem is figured out to a good degree.

Non-essential code specifically for Citadel should be in the Citadel folder, or a seperate file directly.

Code hooks really need to be ported/set up. Notta damn clue how to swing that though.

### CODE REVIEW

**Comment by Poojawa** [comment]
Species DNA reverted and properly counted again.

taur bodies are on hold, since they're pretty much just tails right now

**Comment by Poojawa** [comment]
almost 1300 files changed, lmao

Oh also, it doesn't actually compile yet. that's a wip.

**Comment by Poojawa** [comment]
almost 2,000 changes. jfc.

so many refractors.

**Comment by Poojawa** [comment]
code compile errors defeated. It's all good to start hardcore testing and fresh updating.

Latest TG map as well, to use the water vapor and Freon gases

**Comment by Poojawa** [comment]
Test complete, smoother than pancake batter.

**Comment by TalkingCactus** [comment]
RIP

**Pull request merged**
