### PR TITLE
Makes Stabilizing Serum cost just a bit more

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Stabilizing Serum from 400 miner points to 650, 250 or 60~% incress 
## Why It's Good For The Game

Miner Stabilizing Serums are basiclly mass gotton to help keep a large stockpile of cores that heal a bit of damage, you can after just one run likely buy adv scanner few pens and then a box of Stabilizing Serums making mining rather a joke when you can spam heal cores well also chem stacking, this should help make hunters want/need to mine just a it more.

## Changelog
:cl:
balance: Stabilizing Serum now cost 650 miner points, as before it was only 400
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
We just nerfed cores, why?

**Comment by Trilbyspaceclone** [comment]
@YakumoChen 

> Why It's Good For The Game
> 
> Miner Stabilizing Serums are basiclly mass gotton to help keep a large stockpile of cores that heal a bit of damage, you can after just one run likely buy adv scanner few pens and then a box of Stabilizing Serums making mining rather a joke when you can spam heal cores well also chem stacking, this should help make hunters want/need to mine just a it more.

**Comment by YakumoChen** [comment]
If youre getting more than 2 or 3 thousand points after your first mining run you've probably been out there for a fairly long time, I guarantee normal miners cant afford more than 4 serum at most and an advanced scanner on their first trip back.
 Thats enough for a single full heal from one damage type. Its not a lot.

This is an arbitrary and bad nerf for a nonproblem, cores can't be farmed until you find a tendril (assuming you do, and unlikely until you have a cutter)

**Comment by YakumoChen** [comment]
For reference the brute heal kit is like 800 and that heals twice as much as the same price in serum cores

**Comment by Trilbyspaceclone** [comment]
cores fully heal stam and remove for a bit damage based slowdowns. 
That should be higher valued then 400

**Comment by YakumoChen** [comment]
Stamina isn't an issue on lavaland. The slowdown removal isn't a valid reason  to up the price. This PR doesn't take into consideration the prices of anything else at all. It's a really needless nerf for an item that has already recently been heavily nerfed.

**Comment by silicons** [comment]
unnecessary post core-nerf 
focus on more problematic things.

**Pull request closed without merging**
