### PR TITLE
Reworking boxstation bar and bits of the kitchen

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

With the help of HiJanxy, we worked on redoing boxstation bar and kitchen.
HiJanxy is the brains of the operation, if there are any broad details questions and complaints (like medbay being pushed up a bit), feel free to complain to them. If there are any mechanical problems (like APCs not pixel shifting properly), feel free to complain to me.

THIS SHOULD BE TESTMERGED FIRST.

Since everyone loves a good picture:
image

## Why It's Good For The Game

It redirect traffic so it's not as hard to get through the bar, there's a few antag areas (the arcarde and the sad room), and the bar is a bit of a different shape.

## Changelog
:cl:
balance: Reworked boxstation bar and kitchen
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
I really don't like this area:

image

I like that it's a lounge, but it just being tiles is very offputting.

I also feel like there should be an entrance to the tables outside.

**Comment by MrJWhit** [comment]
Tiles I have no problem fixing/adjusting, what do you recommend I put there?

The entrance isn't there intentionally, it helps break up the boxstation flow from someone torquing through north-south of the bar area. Makes chasing someone through it harder, gives more of a reason to get out of the same hallways over and over again, and so on.

**Comment by keronshb** [comment]
> 
> 
> Tiles I have no problem fixing/adjusting, what do you recommend I put there?
> 
> The entrance isn't there intentionally, it helps break up the boxstation flow from someone torquing through north-south of the bar area. Makes chasing someone through it harder, gives more of a reason to get out of the same hallways over and over again, and so on.

I'd say maybe a carpet of some sort.  Also I think most of the tables should be replaced with wooden tables for more of a bar/restaurant feel.

**Comment by deathride58** [comment]
I really don't like how this looks visually, this design is basically a direct downgrade of what Boxstation's bar currently is, and this honestly feels like an attempt at change for the sake of change. Aside from that, here's a list of more constructive criticism that immediately comes to mind:

- Bar's exterior windows are on top of floortiles instead of plating as windows are normally supposed to be
- Kitchen island has an unnecessary indent, making movement extremely awkward considering the location of the indent. Would be better to instead have it be a 3x2 rectangle. Additionally, the separation of the deep fryers from the island without expanding the room to compensate leaves the kitchen feeling extra cramped, since it makes 1-tile-wide sections be the majority of the kitchen.
- Bartender's side of the bar counter is extremely cramped, and again, movement is awkward, especially with the indent (you can't move horizontally at all while serving customers on the west side of the counter).
- Placement of the jukebox prevents bartender from interacting with the jukebox while staying behind the counter.
- Disposal bin in the bar isn't even hooked up to disposals at all.
- A kitchen counter being present in bar is a decent change for the sake of consistency with other maps, but like other changes, the space is particularly cramped (you only have one tile to get into it if someone's sitting at the south side of the bar counter, and it being smashed against the south seating alcove means that there's little horizontal movement in that spot as well)

There's probably more I could point out, but this is mainly what I've noticed from a quick glanceover

**Comment by zeroisthebiggay** [comment]
angry quasi maptainer here to whine and moan in bulletin points about why this looks dumb

- why is the starboard hall now randomly intersected by a portion of the medbay lobby?
- the odd use of regular tables and metal tiles in a prominently wooden room is a sin and it makes them stick out unnecessarily.
- why would you kill half of the vr sleepers and make the dorms weirdly lopsided with the vr 'nook' in trade for a vacant commissary that barely has enough room to put anything inside of it ontop of compromising the clean dormitory aesthetic with a window into a fucking untiled room?
- why is the bartender's room weirdly tiled? this goes back to the previous point of the odd use of metal tiling in a civilian area; go all wood and carpet or go home.
- the room and its furnishings is weirdly shaped overall, it feels like there are hallways INSIDE of the room rather than it being a literal room; it's all very jagged for what box is supposed to be - a **box**. look at every other room surrounding this new wing and count how many non-square or non-rectangular rooms there are.
- the weird maintenance section on the bottom left corner of the bar is neat in theory but in reality, it's just taken up space for a room with no purpose and adding more to the lopsided aesthetic.
- the kitchen feels really cramped now - there's almost no space to move around anymore.
- i like the idea of having the kitchen be more prominently connected to the bar but removing the hallway access entirely is a huge blow to convenience since people from medbay now have to loop AROUND the bar and go IN through a western entrance just to get something to eat
- the bartender's curved counter looks dumb and is needlessly constricting on space for the bartender behind their counter; not to mention it gives them a spot on the counter that nobody can access but the bartender themselves, which mind you, defeats the purpose of a bar counter.
- why the fuck is there a potted plant behind windows. the old bar had a grass tile and plants beneath a glass tile and that looked infinitely better than a cordoned off potted fucking plant.
- the way that the bar and kitchen cuts slices out of the hallway is neat and all but you're forgetting that almost nowhere else on box does this, so you've cut into space for the room for an aesthetic that is shared nowhere else on the station, a nitpick for sure but it just looks dumb to have these outcoves with no use besides having chairs in them.
- you did all this but you didn't fix the misaligned decal tiles in front of the morgue.

why was this even done to be honest, what's wrong with box's bar enough so that it warrants this drastic of a change?

**Comment by zeroisthebiggay** [comment]
firstly
VTqfO26
bruh

secondly
H6cXhlJ
bruh

**Comment by kiwilover8** [comment]
I feel like this edit overall takes away from some of the baseline that boxstation's bar presents, and feels much more like something a bartender could be encouraged to remodel into mid-round, as opposed to what should be presented roundstart. It adds additional maintenance and eats away at the surrounding framework of the station just to add some extra bells and whistles which overall feel very out of place in boxstation's design.

**Comment by MrJWhit** [comment]
> secondly
> H6cXhlJ
> bruh

Yeah that I was going to fix when/if HiJanxy came along and made an argument on why the broad decisions on the barchange were good, and gave me direction in how to improve based on the feedback given.

StrongDMM just decided that the default sliding function just... doesn't work on APCs. Copying and pasting them to slide them over doesn't work for some reason. I tried to change the variable of the APC itself, didn't seem to fix the issue. I likely need to completely remove and remake the APC, which is annoying.

**Pull request closed without merging**
