### PR TITLE
Revert 3 master

### PR DESCRIPTION
**Pull request by Casuistic**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Care to explain what you are trying to accomplish here at least?

**Review by Ghommie — CHANGES_REQUESTED** [review]
Care to explain what are you trying to accomplish here at least?

**Comment by MrJWhit** [comment]
Was the entire point to just remove all of the space heaters? Why?

**Comment by silicons** [comment]
right.. make a new pr when you feel like explaining

**Pull request closed without merging**
