### PR TITLE
Finally, Peashooters

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
200 years ago, I promised I'd actually make another line to the peas. I finally return to make it a reality.

Introducing the first of two mutations in the peashooter line: The Peashooter.

What the hell is it, Kathrine?
It's a gun that shoots high velocity peas. That.. that's it.
It does no physical damage, and deals 15 stamina damage per bullet hit, at a -50 armor penetration.

This also adds functionality to peas, being able to cut into them to create a clip for the peashooter.

TODO: Get the fucking spronts, jacket!

## Why It's Good For The Game
Well, it certainly isn't +bad+ for the game, now is it? Okay, bad reasoning aside, it's a goofy little thing that's worse than a foam pistol with riot darts. Not particularly harmful, more of an annoyance to anyone with even an inkling of preparedness. Spacemen deserve to goof off with something pretty harmless from time to time, don't you think?

## Changelog
:cl:
add: Grant's Greenery is proud to announce a brand new genetic offspring of peas: The Peashooter!
add: You can now chop the top off of peas, and squash them into your peashooter.
/:cl:

### CODE REVIEW

**Comment by Solaris-Shade** [comment]
Would it be possible if you shoot someone in the mouth with a pea, instead of doing "damage" it force feeds them to eat a pea like a pneumatic cannon?

**Comment by R3dtail** [comment]
"Goof off" and stam damage don't really line up IMO.  i assume from the arm pen that it will do very little but uh.  Even then  why not just make it a purely innocent thing that someone can actually goof off with?  Idk, this seems wack just from cursory glance.

**Comment by Hatterhat** [comment]
this is really funny

**Comment by necromanceranne** [comment]
> "Goof off" and stam damage don't really line up IMO. i assume from the arm pen that it will do very little but uh. Even then why not just make it a purely innocent thing that someone can actually goof off with? Idk, this seems wack just from cursory glance.

They're actually weaker than riot donksoft guns by a significant margain, and things being decidedly subtle as an attack or just someone doing dumb fun is part of the suspense.

And also makes anyone who kills people for being shot with a peashooter a few times look like a dumbass.

**Comment by DeltaFire15** [comment]
Marking this as stale since it has been like this since April.

**Comment by DeltaFire15** [comment]
Closing since it's been stale since August.

**Pull request closed without merging**
