### PR TITLE
Removes mass message from lawyer PDAs

### PR DESCRIPTION
**Pull request by CameronWoof**
## About The Pull Request

Tin. 

## Why It's Good For The Game

Lawyers can no longer make the fact that their job is mind-numbingly boring everyone else's problem by shitting up their PDAs with spam about who they're having sex with or want to have sex with or whatever inane garbage they feel like everyone should be subjected to every five minutes for two straight hours.

Captain retains the ability.

For now.

## Changelog
:cl:
del: Lawyers can no longer mass-message with their PDAs.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
:mega: One day while andy was mas...

**Comment by GrayRachnid** [comment]
:-1: Don't remove the only thing that makes lawyer relevant

**Comment by CameronWoof** [comment]
This is not a fun or enjoyable way to be relevant.

**Comment by GrayRachnid** [comment]
Either
1) Lynch the lawyer
2) Turn off the ringer of your PDA

Maybe limit them to 5 messages total with ways to gain more(similar to how clown starts with 5 viruses but he earns more by slipping people) or find another way to nerf it.

Removal is not the way.

**Comment by CameronWoof** [comment]
I don't want to spend time every round throttling the Lawyer and their fuck of the day and dodging security for the rest of the shift as a result, and I shouldn't have to give up the use of my PDA to counter something that only exists to be annoying. The Captain retains his, in the case that he has something important to tell everyone (fat fucking chance, but whatever).

**Comment by GrayRachnid** [comment]
Then add a 5 message limit with ways to gain more.

**Comment by CameronWoof** [comment]
Five is too many. One is instantly irritating. If you want to tell each and every person on the station something inane, take the time to do it manually. If that sounds irritating, welcome to the club.

**Comment by GrayRachnid** [comment]
Gee you sure are making a point about it being irritating when you're nothing but irritating to everyone around you.

Lawyers' whole point is being annoying until heard, they have no power behind their voice and the only power they get is the power of the people that hear them. PDA messaging is a very good and easy way to spread their voice and they should definitely retain. 

Is it over-used? Yes. I agree with you. Should it be removed? No, they need it. Does it need to be limited? Yes. 5 is a good number but i'm sure 2-3 isn't bad either. Should they have ways to recharge it? Probably, maybe something like a head of staff stamp used on the PDA retains 3 charges and each stamp only applies once? So with QM, CE, HoP, HoS, CMO, RD, and Captain stamps you only get the Base 3 + 21 for a total of 24 only if you get all stamps.

**Comment by CameronWoof** [comment]
Sounds like a great project for you to work on.

**Comment by GrayRachnid** [comment]
You're the one who's annoyed by them, not me.

**Comment by CameronWoof** [comment]
Well if you're still this enthusiastic about them remaining when/if this PR is merged, you've already got a good plan for executing it.

**Comment by GrayRachnid** [comment]
Removal prs don't get merged that easily, especially considering it is a defining feature of the job :joy:

**Comment by GrayRachnid** [comment]
If mass PDA messages annoy you that much then fix them rather than remove them.

**Comment by CameronWoof** [comment]
Well, let's all hope it doesn't become fashionable to block PRs because a much more complicated and time-consuming alternative gets suggested in the comments.

**Comment by GrayRachnid** [comment]
Except it has happened plenty of times! 

Maintainers would pop in to your PR and tell you to make up a whole new system or port a new complicated from /tg/ rather than agree with a removal PR!

See: My genetics removal PR.

**Comment by silicons** [comment]
This is a fine system
PDA blocking is an option
Hell selective telecomms muting would be interesting even if with the potential to be overpowered
No.

**Comment by nik707** [comment]
I agree with this personally. Fuck mass messaging.

**Comment by CozmoB** [comment]
Actually make lawyer relevant rather than doing this

**Comment by CameronWoof** [comment]
We could give lawyers fax machines. Then if they want to annoy people by sending inane messages, they can risk getting jobbanned for it.

**Comment by KathrinBailey** [comment]
It might be worth delaying this and instead let the admins and headmins discuss the possibility of making Lawyer PDA @all use punishable IC by lynchings. If you release "spammy" and trash PDA messages (fuck of the day) instead of quality roleplay messages (Hi crew, I'm your lawyer, call me if you get arrested) three times, it is valid IC to destroy remove the lawyer's cartridge by any means necessary as long as it is non-lethal (you can buckshot them into crit if you heal them after).

Consistently spamming trash messages with the PDA should also be grounds for a job-ban. The key word is consistent. Admins must provide adequate logs proving they're spamming their fuck of the day or whatever every time they play lawyer or whatever and not just they did one shift and another shift a week later.

Regardless, if you do remove it, please add a cartridge with this feature in that mappers can place and admins can spawn.

**Comment by GrayRachnid** [comment]
IMO That shouldn't be an admin issue and it shouldn't be removed either. There are other alternatives.

**Comment by ghost** [comment]
lawyer having it makes no sense, heads of staff having it makes more sense

**Comment by Ghommie** [comment]
Since Nicc made an emojicracy referendum on the discord last week that gathered so far about sixty votes, more than half in favor of preserving the feature, and that no overriding maintainer approval has been given so far, lest this not become another clutter kept open for no reason, I declare this PR closed.

A feature to block individual messagers would be nice, toh.

**Pull request closed without merging**
