### PR TITLE
[Testmerge Ready] Europalights port (Only boxstation is adjusted currently)

### PR DESCRIPTION
**Pull request by deathride58**
This is basically a straight-forward port of Europalights from VGstation. The original PR porting Europalights to VGstation can be found at vgstation-coders/vgstation13#15738
Europalights originate from Europastation. Europastation's github can be found at https://github.com/Yonaguni/EuropaStation/ , but the current codebase no longer uses europalights.
The main reason I'm porting europalights here is due to the massive server-side performance impact that the current lighting system (goonlights) has. The primary reason a lot of developers were turned away from Europalights is due to the massive clientside performance impact it typically has. However, thanks to improvements in Byond 512, europalights now has a _very_ reduced impact on clientside performance, though it's still significant enough to be notable on lower-end machines.
One of the goals for this PR is to make this lighting system support light sizes that have ranges larger than 5 tiles, whether it be by allowing arbitrary light sizes (preferable) or by painstakingly recreating the lighting icons from scratch and pulling it off that way.
Thank you for coming to my TED talk.

Current state:
image
image
It works. It bloody works, everything works! To my knowledge, at least. As of right now, Boxstation is the only map that's properly adjusted for the new lighting. Once I finish up adjusting all the other maps, this will be considered ready for merge.

:cl: Old Europastation's Dev team. Ported to VG by Unusual Crow. Ported to Citadel by Bhijn
add: The server now uses the Europalights light system. The system originated from Europastation, and had an unsuccessful attempt to be ported over to VGstation. This PR ports over the unsuccessful VGstation PR. This has the benefit of vastly improved lighting performance on the server's end, but comes at the cost of a higher clientside performance impact.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Since there isn't a majority in support of this lighting system now that it's been testmerged, this PR will be closed soon. I will be creating a standalone repo that contains all of the relevant files along with instructions on how to port it to a TG-based codebase once this PR is closed. This PR will be closed as soon as the testmerge is lifted.

**Comment by Arturlang** [comment]
Darn, it looked quite good, sad to see it go into coding hell.

**Comment by Poojawa** [comment]
be sure to update your commenting with how high end machines can't handle the rendering and low machines experienced superior performance.

**Comment by silicons** [comment]
dead

**Pull request closed without merging**
