### PR TITLE
[WIP] the funny headless people pr thats taken over a year because im bad at organisation

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
no

this pr is here so i can just document what i have left to do so i dont forget

remaining bug/missing-feature list represented as the missing of some wanted feature:
- [x] eyes don't show up
- [ ] head doesn't fall off when knocked down
- [ ] listening is coming from the body
- [ ] can't talk through headsets
- [ ] changing head-items wont update the head overlay unless you take the head off and put it back on
- [x] 8 months worth of merge conflicts

## Why It's Good For The Game
it's not

## Changelog
:cl:
add: pain
add: suffering
/:cl:

### CODE REVIEW

**Comment by EmeraldSundisk** [comment]
> ## Why It's Good For The Game
> it's not

Well, at least you're honest.

**Comment by timothyteakettle** [comment]
this is still going it's just taking ages

**Comment by DeltaFire15** [comment]
WIP PR with no commits since July. Marking as stale.

**Comment by Linzolle** [comment]
Nothing since being marked stale.

**Pull request closed without merging**
