### PR TITLE
Adds rtgs and moves around the pacman family 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Adds in adv and normal RTGs 
Moves around the pacmans

[why]
RTGs are never used and are nothing power wise to make anything of note

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Local cat forgets to do half the coding

**Review by deathride58 — CHANGES_REQUESTED** [review]
RTGs are a hard no, *especially* with how low the costs in this PR are.

RTGs are free infinite energy produced with no downsides, danger, or setup required. There's good reason RTGs are restricted to debug purposes and specific ruins.

**Review by silicons — CHANGES_REQUESTED** [review]
Okay there's "alien tech is overpowered" and "literally adding admin stuff to R&D"
Stop.

**Comment by Trilbyspaceclone** [comment]
@deathride58 
Give me a middle ground ill do it.

**Comment by deathride58** [comment]
There's really no middleground between having RTGs and not having RTGs

**Pull request closed without merging**
