### PR TITLE
Foxy away mission

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
New away area thats combat focused. Contains 50 hp foxes that do 25-30 damage and 4 named boss foxes, 200 hp foxes that keep their distance and cast fireball/magic missile backed up by 4 of the 'normal' foxes. Hope you bring a group and stay on a diagonal.
total loot: 
hidden1,behind a boss:
**pride mirror**
a rainbow knife
4 hearts
hidden2, behind a boss:
asclepius rod
Behind a boss but not hidden1:
hilbert hotel
book of babel
cookie synth
circled hand
1000 credit chip
Behind a boss but not hidden2:
lots of dead human corpses

not behind a boss:
a ton of kitchen fridges/carnivore ingredient boxes
2 butcher knives
at the gateway entrance:
dead cargo tech

## Why It's Good For The Game
idk man kev said do it and we need a actually dangerous away mission in rotation. Although silly it should be a decent challenge.

## Changelog
:cl:
add: New away mission, Watch out for the foxes.
config: added new blacklisted away mission to awaymissionconfig
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Honestly, this just feels way too big and way too empy, with too much repeating of items. I'm also not sure if there's enough lighting for this place. It's a good start, I just don't think this is ready for the server just yet.

**Comment by silicons** [comment]
when you said dangerous i didn't think it'd be a mob arena of ... foxes.

**Comment by lolman360** [comment]
>hilbert hotel
>exclusive cool space ruin item in an away mission

**Comment by bunny232** [comment]
Will work on improving this later/making it smaller

**Pull request closed without merging**
