### PR TITLE
Better ORM and Mining Vendor sprites

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of: https://github.com/OracleStation/OracleStation/pull/293

## Why It's Good For The Game

Makes the ORM look more like the rest of the mining equipment, plus a minor improvement on the mining vendor

## Changelog
:cl:
tweak: Changes ORM sprites to Oracle's
tweak: Minor adjustment to mining vendor sprite
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
the new vendor looks significantly worse than the one we have atm
the orm is typically mapped in facing north which means it accepts ore from that dir and the new sideways sprite is a little confusing regarding that

**Comment by MacaroniCritter** [comment]
i HATE this sprite from Oracle.

**Comment by YakumoChen** [comment]
Both of these look vastly inferior to current sprites.

**Comment by keronshb** [comment]
Sorry it seems like I'm on a negative comment streak for all of these, but this one aint cutting it either.  The vendor looks way too boxy and fat and the ORM doesn't really look that great.

**Comment by MrJWhit** [comment]
The vendors look exactly the same, and the ORM has a similar look to the unloading machine and the furnace. AKA one of the more original machines.
Plus you have the fact that it's visibly directional, unlike the current ORM.

**Comment by YakumoChen** [comment]
At least with one direction you're not being misled you just have to guess. Two directions dont give you any clues if it's up or across.

The vendor has strictly worse animation and the stock seems to go away with the lights off

**Comment by DeltaFire15** [comment]
I think consensus is clear here.

**Pull request closed without merging**
