### PR TITLE
Adds more to the Autodrobe coin slot!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Adds in more clothing for gimmicks or to look fancy! None of those outfits have any armor or usefulness other then to look good or cover your face if its a mask similar to the chicken hat. All items need a coin to get to keep it balanced! 

[Changelogs]: # Adds in more clothing for gimmicks or to look fancy! None of those outfits have any armor or usefulness other then to look good or cover your face if its a mask similar to the chicken 
adds in
dracula coat
doctor freeze's labcoat
gothic coat
draculass coat
doctor freeze's jumpsuit
doctor freeze's wig
foam lobster suit

[why]: # These outfits look nice and have no real in-game affect for Power-gamers, Whats the point in having them if there going to be unused!

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Hope I didn't ruin everything ever by touching the code!

**Comment by silicons** [comment]
why..?

**Comment by Poojawa** [comment]
o.o

wait what

**Comment by silicons** [comment]
oh i see

**Comment by silicons** [comment]
fuck why'd i leave that branch lying around

**Comment by silicons** [comment]
@Trilbyspaceclone disregard that, you tried to merge into a master branch that I made for a meme but unfortunately I forgot to delete it

**Comment by Poojawa** [comment]
tsk tsk, messy messy Kevin.

**Comment by Hatterhat** [comment]
coders r fags

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
