### PR TITLE
Signed language (Requested changes complete)

### PR DESCRIPTION
**Pull request by TyrianTyrell**
## About The Pull Request

This adds sign language to the game, adds "Multilingual" as a trait, and allows you to select both a character's phobia and bonus language when they have the appropriate traits.

## Why It's Good For The Game

I think having signed language for mute characters would add some interesting roleplay situations- in addition it makes sense for a signed language to exist.

## Changelog
:cl:
add: added a signed language, that can't be used over the radio but can be used if you're mute. also added the multilingual trait.
imageadd: hopefully added an icon for the signed language.
code: changed how some traits function slightly.
/:cl:

### CODE REVIEW

**Comment by TyrianTyrell** [comment]
Why is Github so obnoxious to use...?

**Comment by zeroisthebiggay** [comment]
should probably not let people choose the:
-blahsucker
-codespeak
-nar'sie
-ratvar
languages simply because they're antag languages and letting people snoop on what antags are saying especially codespeak is really really bad
disregarding the fact lizards spout draconic to communicate exclusively to one another on the radio and letting EVERYONE do this is going to encourage cliques one way or the other but it's citadel and nobody cares about the negative implications of giving a select group of people essentially private comms by having them choose arachnid which nobody but like one player uses

on a side note; I hate to say it but letting people communicate while they're mute is already pretty powerful and not particularly something I'd just let people get roundstart to use since it effectively makes the point of being mute moot other than the fact you can't use the radio; though I wouldn't mind it so much if you made it so people can't sign while handcuffed so you don't have people gesturing wildly after being mutestung and dragged away

thanks

**Comment by TyrianTyrell** [comment]
> should probably not let people choose the:
> -blahsucker
> -codespeak
> -nar'sie
> -ratvar
> languages simply because they're antag languages and letting people snoop on what antags are saying especially codespeak is really really bad
> disregarding the fact lizards spout draconic to communicate exclusively to one another on the radio and letting EVERYONE do this is going to encourage cliques one way or the other but it's citadel and nobody cares about the negative implications of giving a select group of people essentially private comms by having them choose arachnid which nobody but like one player uses
> 
> on a side note; I hate to say it but letting people communicate while they're mute is already pretty powerful and not particularly something I'd just let people get roundstart to use since it effectively makes the point of being mute moot other than the fact you can't use the radio; though I wouldn't mind it so much if you made it so people can't sign while handcuffed so you don't have people gesturing wildly after being mutestung and dragged away
> 
> thanks

Ah, did I forget to add that? Thank you for reminding me. I'll tweak it so if your hands are occupied (either because you're cuffed or because you've got items in both hands,) then you can't use it. Also I'll remove the antag languages.

**Comment by zeroisthebiggay** [comment]
> > should probably not let people choose the:
> > -blahsucker
> > -codespeak
> > -nar'sie
> > -ratvar
> > languages simply because they're antag languages and letting people snoop on what antags are saying especially codespeak is really really bad
> > disregarding the fact lizards spout draconic to communicate exclusively to one another on the radio and letting EVERYONE do this is going to encourage cliques one way or the other but it's citadel and nobody cares about the negative implications of giving a select group of people essentially private comms by having them choose arachnid which nobody but like one player uses
> > on a side note; I hate to say it but letting people communicate while they're mute is already pretty powerful and not particularly something I'd just let people get roundstart to use since it effectively makes the point of being mute moot other than the fact you can't use the radio; though I wouldn't mind it so much if you made it so people can't sign while handcuffed so you don't have people gesturing wildly after being mutestung and dragged away
> > thanks
> 
> Ah, did I forget to add that? Thank you for reminding me. I'll tweak it so if your hands are occupied (either because you're cuffed or because you've got items in both hands,) then you can't use it. Also I'll remove the antag languages.

cool based and gooder

**Comment by TyrianTyrell** [comment]
Also, you don't automatically get the language if you're muted by, say, a ling or by being a mime or something.

**Comment by Linzolle** [comment]
Adding the ability to choose your phobia as well as the multilingual perk should be their own separate PRs seeing as they are separate from "adding sign language".

**Comment by TyrianTyrell** [comment]
I don't know- I think at least the multilinguality should be packaged with the sign language- because otherwise, there's nothing that would grant the language to anyone.

**Review by silicons — CHANGES_REQUESTED** [review]
move the phobia to its own pr, please, there's a certain issue regarding that (phobias unlike multilingual tend to be more of a gameplay impact)
i'll merge this pr when that is done

**Comment by TyrianTyrell** [comment]
Okay, I think I got rid of the phobia stuff.

**Pull request merged**
