### PR TITLE
Prettying up the TEG

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Hopefully this is the last time.
1. Shuffled a few things around (RPD rack, fuel tanks, some gas flow meters, and some wall stuff)
2. Removed a few things (a pump that I learned to not like, and that 2x2 block of wall)
3. Adding a few things (rng spawner in the crate, and a monkey+hat in the burn chamber)

## Why It's Good For The Game

A few things that have bugged me since this was merged, and a funny monkey in the burnchamber, who doesn't like that.

## Changelog
:cl:
tweak: Minor adjustments to the TEG engine.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
The monkey is needed, and I will not get rid of them. They are the Good Burn Luck Charm.

**Comment by MrJWhit** [comment]
LORE UPDATE:
The monkeys name is Captain Plasma.

I will accept other monkey names in the meantime, probably making a poll on them if people care.

**Comment by moltoretardo** [comment]
Burning mankey

**Comment by MrJWhit** [comment]
Before I forget, other name suggestion is Gassy the Monkey, or Witty Gas Monkey.

**Pull request merged**
