### PR TITLE
Porting the first half of travis improvements.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Porting in tgstation PR #44845 by SpaceManiac.
Also the removal of an unnedeed import, by Spookydonut (#44594).

Hopefully nothing is amiss, one step at a time.

## Why It's Good For The Game
Trying to keep this travis up to date with the once-was-upstream's improvements.

## Changelog
None but all credits to the original authors.

### CODE REVIEW

**Comment by Ghommie** [comment]
Oh well, missing permissions. Shouldn't be surprised.
The ship's wheel is yours, maintainers.

**Comment by Poojawa** [comment]
why only a half port, and not a whole port

**Comment by Ghommie** [comment]
Tried that in one go and I seemengly killed travis.

**Comment by nik707** [comment]
@kevinz000 help

**Comment by Ghommie** [comment]
Ah screw it.

**Pull request closed without merging**
