### PR TITLE
3 New guns for sec to use, Late-game [Clickbate?]

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Misstakes
Adds in 3 new guns! - YAY GUNBLOAT
One is a HEAVY LASER CANNON WEW - deals 35 harm per shot and has 5 shots before needing reloading 
DISABLER CARBINE - has normal dislaber shoots but has 25 shots before needing dat reload
DISABLER  HEAVY LASER CANNON - Has 10 shots do to being non-lethal and rather easy to counter but if hit deals 48 stams!
New node to hold the new guns costs 2500 and is unlocked just at the same time as snipers

Removes all the export prices for tech nodes - it was bloat and unused 

## Why It's Good For The Game

Helps give sec more options that isnt just the standerd AEG or Taser to deal with legit every threat ever! Should also give then a fighting odds against nanite meta to out heal taser/disabler harm

## Changelog
:cl:
add: New guns*
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
Laser cannons were unbalanced when dual-wielding wasn't a thing. Probably reduce laser force to 30.

**Comment by Trilbyspaceclone** [comment]
Hm sure

**Comment by YakumoChen** [comment]
Don't agree with making research that is straight upgrades, you can probably tell every other gun in research is a side grade. variety means adding guns with different strengths and weaknesses, not just guns that are flat out better.

**Comment by Trilbyspaceclone** [comment]
Well, aegs are better then HOS gun
Carbines are better then lasers
Shotgun taser darts are better then tasers
You can argue that "Mag guns are better then blaster rifles" do to having more ammo and better stats.
Ect ect, these are to help brake out the AEG meta with different guns that are slower charging but deal/have more power
No one really uses disablers sadly so im hoping that this will make it better.
And the cannon versions are mostly just low-ammo high stopping rate, thats not just a mark gun or bomb disk...

**Comment by YakumoChen** [comment]
Are you kidding? The AEG has a huge drawback. Emp makes it light up like plutonium, assuming doesn't literally fucking explode.

Shotguns have limited ammo you have to print and manually reload, taking up inventory space or forcing you to rely on the lathe.
Mag guns have a weird ammo system, I'm not familiar enough with them to know what their drawback is if any, aside from also being reliant on the lathe for ammo.

Any gun you an research that is a direct upgrade is strictly bad design and should be made different or removed. if you make guns with better stats and no drawback the meta will just be to use them.

**Comment by YakumoChen** [comment]
Disablers need a hard buff since it takes forever to down anyone with them, taser has massive stopping power in comparison. They're much better on tg since three or four will slow or down someone, you don't feel the slowdown at all on citadel until you've taken that many hits. 

AEGs main buff isn't even that good, the recharge is very slow and you'll need to disengage a fight once you run out anyway, which is no better than any other energy gun. Unless you carry a bunch of them, in which case enjoy your fatal dose of rads if you get hit by an emp.

**Comment by Trilbyspaceclone** [comment]
Well the EMP's rad "nuke" isnt that good unless you get hit with 4 of them in you, do to how rads work it likely not even do toxin harm, if anything you just loos you hair.
Disablers as per statbus are legit never buy'ed. So throwing in a version that DOSNT need a full charge mag to drop someone is really needed, as per the "fully upgraded" versions its drawback will be lack of ammo, and costs of them as well as charge time. Rnd is already making flat upgraded things like tools and such so its more or less fits the theme Id think
Though I should make the cannon a back item and larger you do have me their. Thanks

**Comment by YakumoChen** [comment]
Tools are different from guns, tools aren't a combat item. There doesn't need to be much variety in tools because they only do one thing. 

Guns have a lot of varied use in combat and each different gun you can research reflects that purpose. Xray guns are weaker and ignore obstacles, shotguns have a wide variety of ammo but you need to store it and reload it one shot at a time, beam rifles require you stand still but are very powerful and long ranged, AEGs recharge, but very slowly, and EMPs cripple their use (it also gets worse over time after it's EMPed regardless of if you're being EMP'd more or not, and you get hit with rads every time it processes). Straight upgrades completely ruin the point of having a variety, people are just going to choose the ""best gun"". Whoever added carbines is dumb, they need something to make them not just Better Laser Gun because that's idiotic. 

Instead of adding direct upgrades to the existing disablers, why not just buff disabler shots? Lord knows it needs one.

**Comment by Trilbyspaceclone** [comment]
Rayguns only go through walls and maybe doors last I checked, and deal rads. AEG still recharge well, unlike in TG. All in all the guns added I feel are good for the game, as they have their own quirks, low ammo high harm. Or with carbines it takes better tech to get but are limited to only 1 ammo type

**Comment by Tupinambis** [comment]
In order to completely remove the strength of duel wielding the heavy weapons from the equation, I highly recommend making the heavy energy cannons require two hands to fire (like the L6 not the desword)

**Comment by lolman360** [comment]
why not make them like the sniper rifle? Bulky weapon, can be held in one hand but needs both to fire.

**Comment by silicons** [comment]
I'm very against adding more straight upgrades.

**Comment by silicons** [comment]
security really doesn't need even more buffs.

**Comment by lolman360** [comment]
why not just  edit your comment kevin

**Comment by Trilbyspaceclone** [comment]
This PR is at the state at which I like it.
Back in the day we never needed 2 hands to use the damn things, and its nerf'ed from that with size as well as damage reduction.
Unless I get code improvements regarding these, im not willing to edit them

**Comment by silicons** [comment]
security really does not need more straight upgrades rather than sidegrades sorry calling it now.

**Pull request closed without merging**
