### PR TITLE
Revert "Framework for (hopefully) reducing memory usage by replacing thousands of decals with turfs that look visually identical"

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title.

## Why It's Good For The Game
A bunch of static turf icons can't possibly be a good alternative to the infinite amount of combinations that can be done with decals, not even for the simplier things such as colored squares etcetera.  #12388 is probably as far as we can go without regressing.

## Changelog
Nope.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
They ARE decals in combinations that are seen in most other maps. 
They WOULD lower performance strain on the server if used
They are NOT limiting the amount of " infinite amount of combinations that can be done with decals"
reverting this framework pr on the other hand is DOING what you state is the goal of reverting this in that its limiting people. This IS limiting options people have when mapping.
This IS a good alternative to people that make the same tile with the same decals 200 times - Look at old Kilo, this pr would have saved rounds of MMO'ing.

What this does is limit mappers, and make it impossible to reduce the amount of decal performance sinks we have.

The pr your reverting adds options, but you clam it dosnt cuz ??? but your removing options by reverting it

**Comment by Ghommie** [comment]
Trilby, I strongly believe there is some sort of misunderstanding behind your reply, but nevertheless I'll give you a more detailed list of other reasons to help you understand better why I'm actually removing it:
1) We are not sure anybody will be enforcing or using those tiles anyway, that's a lot of work.
2) That "framework" will lead to unneeded double standard situations, considering /tg/station, as well as downstreams (including us), still extensively use decals. In short, a pain in the ass.
3) This goes against what Wjohn did in on `https://github.com/tgstation/tgstation/pull/40065` almost two years ago.
4) I am providing an alternative to ease the memory usage in #12388 without the aforementioned problems.

**Comment by silicons** [comment]
Yeah the decals should help enough to not make the new subtypes particularly .. needed.
I do have my doubts about the whole overlay situation but, the route of making a ton of turf subtypes isn't particularly good, I probably should have thought it through a bit more.
Sorry @KathrinBailey

**Comment by KathrinBailey** [comment]
I was told that the turf subtypes would be better for performance hence why I did this in the first place.
This definitely didn't "limit" turf decals since they're not being removed.
In terms of applying it manually, it'd have been me applying it to all the in-rotation maps on Citadel and downstream. I don't really trust anyone else to do it anyway because I haven't seen a mapper who will thoroughly do this without creating a ton of bugs on the side. There's probably one or two people who could do a good job of it but I haven't met them.
Regardless, it's nice you found a better solution.

**Pull request merged**
