### PR TITLE
the hamfisted bulldog buffs nobody asked for

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
- bulldog drums hold 10 shells
- bulldogs now have a 2rnd burst
- bulldog firerate is maybe kinda sorta doubled
- ammo generally cheaper
## Why It's Good For The Game
c20r: ol reliable, plinking dudes with .45 at range
l6: kills god himself.
bulldog: quirky little fella. a little goofy. a little zany.
bulldog in this pr: i am going to run at you and blast you to kingdom come with buckshot
## Changelog
:cl:
balance: The Bulldog shotgun given to nuclear operatives now holds 2 more shells (now 10) and fires faster, along with better ammunition deals being provided to Syndicate-affiliated operatives.
/:cl:

### CODE REVIEW

**Comment by Feasel** [comment]
No.

Why the literal fuck do you think this is a good idea, hatter?

The bulldog is the strongest nukie weapon in the hands of a competent one. SPECIALLY IF THEY GO CHEESE!!!

Put on syndicate mask, activate mask. ??? Holy shit I just qdel'd a gygax in like .2 seconds 😄 

Now you just made it so I could just 

Start burst, switch hands, start other burst.

Oh boi. I hope you like dying from goonchat and not having counterplay. 😄

**Comment by Detective-Google** [comment]
> No.
> 
> Why the literal fuck do you think this is a good idea, hatter?
> 
> The bulldog is the strongest nukie weapon in the hands of a competent one. SPECIALLY IF THEY GO CHEESE!!!
> 
> Put on syndicate mask, activate mask. ??? Holy shit I just qdel'd a gygax in like .2 seconds 😄
> 
> Now you just made it so I could just
> 
> Start burst, switch hands, start other burst.
> 
> Oh boi. I hope you like dying from goonchat and not having counterplay. 😄

**Comment by Hatterhat** [comment]
> No.

k
> Why the literal fuck do you think this is a good idea, hatter?

well really i thought "hey what if the bulldog had a burst" and then decided to give it more
> The bulldog is the strongest nukie weapon in the hands of a competent one. SPECIALLY IF THEY GO CHEESE!!!

then hey man all the power to the dude who decided "i'm gonna specialize in the short range buckshot spectacular"
> Put on syndicate mask, activate mask. ??? Holy shit I just qdel'd a gygax in like .2 seconds 😄

it's more "turned a gygax to a wreckage" but hey man if they didn't watch their back or come with backup then is that not a pilot's issue
> Now you just made it so I could just
> Start burst, switch hands, start other burst.

hey man if that's how you wanna jive that's how you wanna jive
> Oh boi. I hope you like dying from goonchat and not having counterplay. 😄

isn't the chat subsystem supposed to handle that, but also if you're a diskholder and you get jumped by a dude with a shotgun then maybe you'll think more "ah, shit" instead of "hold shift and go the other way"

**Comment by Feasel** [comment]
> > Why the literal fuck do you think this is a good idea, hatter?
> 
> well really i thought "hey what if the bulldog had a burst" and then decided to give it more
> 
  Because you like killing the fuck outta anyone? This makes it stupid easy and abusable.




> then hey man all the power to the dude who decided "i'm gonna specialize in the short range buckshot spectacular"

Can just use fuckin scatter shot or slugs 😄 
> > Put on syndicate mask, activate mask. ??? Holy shit I just qdel'd a gygax in like .2 seconds 😄
> 
> it's more "turned a gygax to a wreckage" but hey man if they didn't watch their back or come with backup then is that not a pilot's issue

Scatter laser = hallway is full of lethals. What back up breh? What back up? They're probably almost all in crit or near crit and your mech is almost dead :haha:

> > Now you just made it so I could just
> > Start burst, switch hands, start other burst.
> 
> hey man if that's how you wanna jive that's how you wanna jive
I don't like steam roll ops. It's boring. There's no struggle when you can delete hallways with this gun. 
> > Oh boi. I hope you like dying from goonchat and not having counterplay. 😄
> 
> isn't the chat subsystem supposed to handle that, but also if you're a diskholder and you get jumped by a dude with a shotgun then maybe you'll think more "ah, shit" instead of "hold shift and go the other way"

Can't handle it... Never got fixed. 
It's still an issue

**Comment by silicons** [comment]
stop

**Pull request closed without merging**
