### PR TITLE
New Bar Signs

### PR DESCRIPTION
**Pull request by ghost**
Changes up the second part of the coderbus sign and adds 3 new signs, The Snowflake, The Half-Life, and The Number One

The Snowflake:
https://my.mixtape.moe/nzhkoq.gif

The Half-Life:
~https://my.mixtape.moe/xapndm.gif~ 2muchcopyrightedlogo
https://my.mixtape.moe/pgdmua.gif

The Number One:
https://my.mixtape.moe/yksdbo.gif

The Coderbus:
https://my.mixtape.moe/oxgyck.gif

Top Men:
https://my.mixtape.moe/bilbar.gif

The Sun:
https://my.mixtape.moe/isfgyr.gif

Last two are from Europa. I created the rest of them myself.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
Half-Life needs to be a bit more subtle than that.

**Comment by ghost** [comment]
https://my.mixtape.moe/qhbfoh.gif
better?

**Comment by TalkingCactus** [comment]
Like less obviously a copyrighted logo

**Comment by ghost** [comment]
oh ok i'll do it when i'm home

**Comment by ghost** [comment]
https://my.mixtape.moe/pgdmua.gif
better.
valve won't sue open source nonprofit spessmans for the title don't worry

**Comment by TalkingCactus** [comment]
subtle references are better anyway
_not like that's subtle, but still_

**Comment by TalkingCactus** [comment]
is this ready?

**Comment by TalkingCactus** [comment]
Make sure to include sources as well

**Comment by ghost** [comment]
Should be but i haven't tested it yet, so if you can just wait until I'm home and I'll do that

**Comment by ghost** [comment]
Ready to commit

**Pull request merged**
