### PR TITLE
Make people nut with VOG

### PR DESCRIPTION
**Pull request by GuppyLaxx**
something something funny

### CODE REVIEW

**Comment by yourdoom9898** [comment]
How does this interact with arousal off players?

**Comment by GuppyLaxx** [comment]
Doesn't do anything to them, it checks if the person can be aroused at all first then makes them nut

**Comment by izzyinbox** [comment]
Lame, you stole it before I PR'd reeee
Anyway, this is missing type casting to `living/carbon/human`
How the heck did this even compile?

**Comment by Poojawa** [comment]
forcing your fetish material on people, smh.

**Comment by silicons** [comment]
closed in preference of the other pr

**Pull request closed without merging**
