### PR TITLE
meteors now only give 60-90 seconds warning

### PR DESCRIPTION
**Pull request by Sishen1542**
title

### CODE REVIEW

**Comment by IronEleven** [comment]
Persi's nerf already barely gives time to print and place sats.  We've been seeing a lot more rounds ended early by meteors lately.

**Comment by ghost** [comment]
we either have printable shields or warning timer, take your pick. if we're gonna have both, just remove meteors from the event pool so we can get actual events honk

**Comment by IronEleven** [comment]
I'd honestly be down for taking out meteors.  They either do nothing or end the round.

**Comment by Sishen1542** [comment]
without me to carry the engi department, everything falls apart

**Comment by Iroquois-Pliskin** [comment]
Meteors can currently fuck up everyone's day and getting printable meteor shields rely on Science, Engineering, and Mining all doing their jobs to get this stuff and then set it up. Making Meteors so short notice is a bad idea. If you do, then at least give the announcement an indication as to the direction they're approaching so Engineers can scramble to shield that section, rather than go for a buckshot approach of trying to shield everything.

**Comment by Poojawa** [comment]
Doesn't cargo still possess the ability to buy meteor sats

**Comment by ForrestWick** [comment]
Just remove meteors. They add nothing to make a round more fun or interesting and just cause nothing but grief or everyone. And the fact people want to make meteor storms harder to counter is just completely baffling. Disable them and let better events and midround spawns have a better chance

**Comment by Sishen1542** [comment]
> Meteors can currently fuck up everyone's day and getting printable meteor shields rely on Science, Engineering, and Mining..

so people doing their jobs?

> Doesn't cargo still possess the ability to buy meteor sats

yes, they're also printable

> ...**_They add nothing to make a round more fun or interesting_** ...

1. gives me something to do as an engineer
2. mass chaos gives antags easy cover to do their dirty work

:gorilla:

**Comment by ghost** [comment]
if we remove meteors i'm gonna make a pr that makes the rod chances equal to the current meteor

**Comment by silicons** [comment]
i like this

**Review by silicons — APPROVED** [review]

**Pull request merged**
