### PR TITLE
Removes OOC braindamage lines, adds a needed braindamage line

### PR DESCRIPTION
**Pull request by improvedname**

### CODE REVIEW

**Comment by deathride58** [comment]
Why remove the brain damage lines? Did they break your immersions?

**Comment by improvedname** [comment]
Yes

**Review by silicons — CHANGES_REQUESTED** [review]
>remove one ooc line
>leave the rest in
yeah uh I'd rather we kept the normal ones. It's not that much of an immersion break tbh.

**Comment by silicons** [comment]
fix it

**Comment by improvedname** [comment]
No

**Pull request closed without merging**
