### PR TITLE
Adds adv cams, ai upgrades and reblances illegal tech in Rnd

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Adds 6.67 to bullets normal
Moves Laser Carbine to adv weapons and makes it cost more
Adds 2 more nodes
Moves Illegal borg mod to new new
Changes a few costs to be less 
Adv illegal bullets 25k -> 8k
Illegal basic 10k - > 8k
Bullets 2750 - > 3k
move decloner to alien basic
Adds adv cams

## Why It's Good For The Game

Illegal tech is hard* to get and should limit by rareity rather then points
Decloner is alien rather then synda
Adv cams should be buildable

## Changelog
:cl:
add: nodes
balance: placement and point costs
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
>decloner changes

Hol up. Decloner's existed  waaaay before abductors were even a thing.

**Comment by Trilbyspaceclone** [comment]
@lolman360 Decloners are really powerfull and seem more ayyylom then illegal

**Comment by nik707** [comment]
@kevinz000 @deathride58 aaa balance changes

**Comment by silicons** [comment]
sorry not a fan of this, it's honestly just going to powercreep security above anything else.

**Pull request closed without merging**
