### PR TITLE
adds a cute new plushie

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

adds a cute new plushie

## Why It's Good For The Game

adds a cute new plushie
image

## Changelog
:cl:
add: adds a cute new plushie
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
ඞ

**Comment by LordSaladin** [comment]
that plushie is sus!, i saw them expose their melons and vent!

**Comment by Detective-Google** [comment]
bad post

**Comment by redta1l** [comment]
💪ඞ👍

**Comment by kiwedespars** [comment]
i made it cuter
image

**Comment by kiwedespars** [comment]
added aww maan
image

**Comment by moltoretardo** [comment]
someone stop him he's on a roll.

**Comment by kiwedespars** [comment]
he's got a backpack
image

**Comment by kiwedespars** [comment]
added tiny cute plushie
image

**Comment by Tupinambis** [comment]
ඞ

**Pull request merged**
