### PR TITLE
loyal benos

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Xenos, upon hatching, are now given a message telling them to obey whoever laid their egg.

## Why It's Good For The Game

Xenos will hopefully consider egg laying humanoids a queen. I probably could've done this in a better way but I suck at coding.

## Changelog
:cl:
tweak: NanoTrasen has made a breakthrough in psionic control technology. Hive-minded aliens can now be made to listen to individuals implanted with certain organs.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
> You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Fuck off bot.

**Comment by ghost** [comment]
>trying to give random people an army of extremely powerful antags at their beck and call

**Comment by ghost** [comment]
> > trying to give random people an army of extremely powerful antags at their beck and call

The only real difference from an actual queen is that a person is weaker and can use items, while a queen is a gigantic, slow monster that CANNOT use items.

**Comment by lolman360** [comment]
that makes them so much better

items are a good 60% of this game at least, and speed trumps brute force in combat any day

this pr allows you to turn humans into xeno queens but better in basically every way

**Comment by Ludox235** [comment]
It would be hilarious for _some_ things but let's be honest everyone will use them for pwr game so this won't get merged.

**Comment by timothyteakettle** [comment]
the fact people with the organ can lay eggs is bad enough giving them the full authority of a queen is an awful idea

this is the kind of change you'd expect on servers where rp is a priority over gameplay and so balance doesn't matter

 balance actually matters here because we prioritise gameplay first and i really don't want to have to fight someone with xenos on their side

**Comment by Sishen1542** [comment]
no thanks

**Comment by MalricB** [comment]
why

**Comment by silicons** [comment]
no thank you

**Pull request closed without merging**
