### PR TITLE
Mining inquisitor/berserker hardsuit nerf, slight drake armor buff.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. We nerfed the drake armor yet we forgot about the inquisitor/berserker hardsuits and how they are just better than the former now.

So here's the nerf: Minus 10 points from each armor category, and 10 more on bio, rad, fire, acid, an added immutable slowdown and limited anti magic. They shouldn't be way better than a captain hardsuit now.

Restored the drake armor original melee armor and some of its laser armor to help defend against both simple mobs and the station itself, that's a boss loot after all.

## Why It's Good For The Game
Normal paranormal ERT hardsuits are too robust for tendril RNG loot with their 50% damage reduction all round, no slowdown and unlimited anti magic protection.

## Changelog
:cl:
balance: Nerfed Mining inquisitor/berserker hardsuits.
balance: Restored the drake armor' original melee stats and some of the laser stats too.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
this seems to be an alt verson of #12270
If(when) this verson gets merged ill likely close the old pr and make a new one with the SEVA buffs. - Edit
Seva buffs and mask/bone add on nerfs

**Comment by Ghommie** [comment]
I didn't notice, thanks for telling. Feel free to scrap your changes on the topic or implement mine so we won't end up with merge conflicts.

**Comment by Trilbyspaceclone** [comment]
No prob your armor looks *much* better then the hack job I did - Edit
I never did forget about the ERT suits, I just didnt want to muddie the pr about drag amour about it. ^_^

**Comment by YakumoChen** [comment]
I really disagree with the slowdown. Any kind of slowdown makes the armor obstinately unusable on lavaland itself, where it's meant to be found and used, making it kind of junk regardless of how good the armor values are. I've never seen anyone use the NarNar hardsuit which can also be found in the chests, for exactly this reason.

**Comment by Trilbyspaceclone** [comment]
@YakumoChen Red slimes still give slowdown = 0. Team work and the like, just as hardsuits on lava land were back before the amazing Exo suits took over

**Comment by YakumoChen** [comment]
It's coded as an immutable slowdown, so no.

**Comment by necromanceranne** [comment]
The inquisitor hardsuit is an ert suit being used by an actual ert spawn. Just remove that from the loot pool rather than nerf the ert compared to their standard ert analogs.

Yes, someone genuinely put an admin spawn hardsuit in as lavaland loot. Yes it's dumb.

**Review by silicons — CHANGES_REQUESTED** [review]
please do something that is hitting only the tendril loot whether it's removing it or nerfing it don't care which at this point, not the base hardsuit itself
it's an adminspawn thing yes and we actually sometimes use it (it's actually part of paranormal ert)

**Comment by Ghommie** [comment]
I already made subtypes for that scope, kevinz.

**Comment by Trilbyspaceclone** [comment]
@YakumoChen Eather im blind or ERT  hardsuit to Paranormal hardsuit to the lava land one all can be used with red slimes.
If you could show me were the code blocking that is ill prob remove it, cuz in all cases it would be atm a colour swap and thats funny.
And when this is merged will be usefull for miners

**Review by silicons — APPROVED** [review]
ah, my bad, i misread

**Pull request merged**
