### PR TITLE
Removes the human check from cap/chap mind on cult conversion.

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
* Stops blood cult conversion runes from working on monkey'd chaplain/captain.
* Stops clock cult conversion runes from working on monkey'd chaplain/captain.

## Why It's Good For The Game
-Old code oversights are bad.

## Changelog
:cl:
fix: Removed the human check for cult conversion of captain/chaplain minds.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/d593d32ed4725ee5f50e2135f45eb26748975bf8/code/game/gamemodes/cult/cult.dm#L19

Just remove the `ishuman(M)` from this line, I doubt it will break things.

**Comment by RogueSteampunker** [comment]
As said plenty of times before, this is a kneejerk change that could just as easily do a mind check on them as monkies as it does when they're human, Barring everything from being converted is dumb.

**Comment by Sishen1542** [comment]
> As said plenty of times before, this is a kneejerk change that could just as easily do a mind check on them as monkies as it does when they're human, Barring everything from being converted is dumb.

**Comment by Ghommie** [comment]
Remember to change the Changelog entry, even if it's not fully functional as of now.
Once that get fixes (as if that will ever happen, but still), all the lot of stored .yml CL files will flood in.

**Comment by silicons** [comment]
emergent gameplay
@deathride58 @BlackMajor do any of you want this merged because i'm pretty negative on this.

**Comment by BlackMajor** [comment]
> emergent gameplay
> @deathride58 @BlackMajor do any of you want this merged because i'm pretty negative on this.

I've always been fine with the idea of cult being able to convert non-human mobs.

What I'm not ok with is that being used as a mean to circumvent the Chap/Cap cult convert immune status.
So I'm in favour of this change ensuring they can't be converted even if turned into a non-human mob.

**Review by silicons — APPROVED** [review]

**Pull request merged**
