### PR TITLE
Blob cats plushies!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Four new blob cat plushies
image
image

## Why It's Good For The Game

Cute plushies that are on discord but not in game yet!

## Changelog
:cl:
add: Four popular blob cat plushies
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Oh no they're adorable.

**Comment by Xantholne** [comment]
needs blobcatheart

**Comment by Ghommie** [comment]
The shape is a little odd, the whiskers should be light grey, not white, the expression doesn't match the emojis well enough and the sprites lacks that very slight hint of shading needed to not look like stickers.
Overall, eh, passable.
Could also use some darker borders to better distinguish them from other yellow atoms.

**Comment by Trilbyspaceclone** [comment]
@Ghommie Fun fact, those are the legit same colours as are emote on discord. I used SM Paint to use the dropper tool, then edit selected colour. And then added those two colours needed into DreamCrusher,

**Comment by Ghommie** [comment]
I know you used the same yellow RGB hue. But the whiskers are white when they should be light gray though. And the shading was souggested so the sprite won't look that flat. This is not Discord.

**Comment by silicons** [comment]
im adding this to #10277

**Pull request closed without merging**
