### PR TITLE
Adds traitor shotgun for 10TC

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
Adds a 10TC shotgun to the traitor uplink, poplocked to 15, normal size combat shotty with 3+1 ammo cap

## Why It's Good For The Game
New stuff good, I don't see why tots can't have a shotgun they can buy, it has 3+1 ammo capacity, autoracks but fires as slow as a normal shotty. Poplocked to 15 like revolver. Fits on belt, back or in your bag.

## Changelog
:cl:
add: Added new traitor shotgun to uplink for 10 TC 15 poplock
add: Added Precision Dynamics Short Shotgun-12 normal size combat shotgun with 3+1 ammo cap
imageadd: added PD SSG-12 sprite under state "traitorshotgun"
/:cl:

### CODE REVIEW

**Comment by kiwedespars** [comment]
sounds boring
combat shotgun for 10 tc
it's like adding spears/bolas/beartraps to the uplink for tc. it's not interesting, it's not fun. make it part of a bundle or something if you really want to, even though we have one of those.

**Comment by GrayRachnid** [comment]
why use this instead of .357

**Comment by dzahlus** [comment]
> why use this instead of .357

Modularity of shells, ammo freely available, stripper clip fills the mag

**Comment by dzahlus** [comment]
> sounds boring
> combat shotgun for 10 tc
> it's like adding spears/bolas/beartraps to the uplink for tc. it's not interesting, it's not fun. make it part of a bundle or something if you really want to, even though we have one of those.

bundle with stripper clips sounds good, but we don't have a shotgun bundle for traitors btw or any kind of shotgun. Also simplicity doesn't mean its boring. Yeah it's just a shotgun, that's why it's brilliant, I'll let interesting things be done by people better at coding than me, but a simple shotgun that just works feels like a good addition because of it's simplicity and it just works means people will actually use it

**Comment by GrayRachnid** [comment]
The 357 is a small gun, has 6 shots and does more damage. The ammo isn't hard to get either unless it was removed from the unlocked autolathe.
A 4 shot shotgun(even if it pumps itself) doesn't sound that appealing. yeah you can use custom ammo on it but at that point why not make 4 improvised shotguns and master the art of quick swapping?
Seems like a noob trap when the 357 can do its job better. If it's part of a bundle or made smaller(without the stamina downside) then I can see it being viable for that price.

**Comment by keronshb** [comment]
> 
> 
> The 357 is a small gun, has 6 shots and does more damage. The ammo isn't hard to get either unless it was removed from the unlocked autolathe.
> A 4 shot shotgun(even if it pumps itself) doesn't sound that appealing. yeah you can use custom ammo on it but at that point why not make 4 improvised shotguns and master the art of quick swapping?
> Seems like a noob trap when the 357 can do its job better. If it's part of a bundle or made smaller(without the stamina downside) then I can see it being viable for that price.

357 ammo, or speedloaders at least, were removed from the autolathe.

**Comment by kiwedespars** [comment]
>bundle with stripper clips sounds good, but we don't have a shotgun bundle for traitors btw or any kind of shotgun.

>		if("metaops") // 30 tc
			new /obj/item/clothing/suit/space/hardsuit/syndi(src) // 8 tc
			new /obj/item/gun/ballistic/automatic/shotgun/bulldog/unrestricted(src) // 8 tc
			new /obj/item/implanter/explosive(src) // 2 tc
			new /obj/item/ammo_box/magazine/m12g(src) // 2 tc
			new /obj/item/ammo_box/magazine/m12g(src) // 2 tc
			new /obj/item/grenade/plastic/c4 (src) // 1 tc
			new /obj/item/grenade/plastic/c4 (src) // 1 tc
			new /obj/item/card/emag(src) // 6 tc



we do

**Comment by silicons** [comment]
`New stuff good, I don't see why tots can't have a shotgun they can buy, it has 3+1 ammo capacity, autoracks but fires as slow as a normal shotty. Poplocked to 15 like revolver. Fits on belt, back or in your bag.`
please update with why this is good for the game. stating what it is, is not reasoning.

**Comment by dzahlus** [comment]
damn yall have no chill

**Pull request closed without merging**
