### PR TITLE
No ID insertion for everything except the hop console

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
Port of https://github.com/tgstation/tgstation/pull/45693

machines and consoles that previously required an inserted ID now check access on worn and inhand ids. They otherwise function identically.
Affected things:
ORM: click claim to claim cash to connected ID (also fixes it)
Mining vendor: uses ID on person or in hand.
medical console: checks worn ID
security records console: checks worn ID
gulag consoles: claim points to worn ID, checks access and point requirements from worn ID

_**Also some backend refactoring to prisoner management and gulag teleporter consoles**_

hop console will be next to strip out the shitcode entirely but this at least gets things functional in the mean time, but fully tested this time. It's very late here and I need to sleep. Due to the nature of it it's more elaborate of a rework.

## Why It's Good For The Game
QOL

## Changelog
:cl: original by actioninja, port by sishen1542
tweak: Medical and Security consoles now check access on worn or inhand ID instead of requiring an inserted ID
tweak: mining vendor now reads from ID in hand or on person instead of requiring an inserted ID
fix: ORM is functional again (for real this time)
tweak: ORM claim points button transfers points to worn/inhand ID instead of to an inserted ID, no longer accepts insertions
tweak: Same for gulag consoles
/:cl:

### CODE REVIEW

**Comment by Poojawa** [comment]
also can you see if you can't make lockers re-lockable by smacking PDAs on them? I swear it's broken at some point

**Comment by R3dtail** [comment]
Will you still have the option to insert your ID?  If naything the HOP console should be left alone, since it actually makes the HOP have to at least /somewhat/ think.  Plus, in times of emergency it's sometimes good to just leave your ID in the console and let folks get their own access.    
Addendum:  Sishen cleared it up that my concerns were misplaced, because he just copy and pasted the PR.     My concerns were mostly based on the idea of messing with the HOP console, which this doesn't do.  So, this thing's a pretty good QOL improvement and makes things more consistent across the board considering some machines accept IDs in ID slot, some need in hand and inserted, .  More consistency is good IMO.

**Comment by Sishen1542** [comment]
this is for everything except the hop console (save for simple circuits stuff such as APCs, air alarms etc)

Affected things:
ORM: click claim to claim cash to connected ID (also fixes it)
Mining vendor: uses ID on person or in hand.
medical console: checks worn ID
security records console: checks worn ID
gulag consoles: claim points to worn ID, checks access and point requirements from worn ID

**Comment by Thalpy** [comment]
This doesn't nerf clown's ability to announce things on the capt's console does it?

**Comment by Sishen1542** [comment]
nope

**Comment by nik707** [comment]
god yes

**Review by nik707 — CHANGES_REQUESTED** [review]
what's with the random map and sec changes?

**Comment by Sishen1542** [comment]
> what's with the random map and sec changes?

some backend refactoring to prisoner management and gulag teleporter consoles

**Review by nik707 — APPROVED** [review]

**Review by silicons — APPROVED** [review]

**Pull request merged**
