### PR TITLE
let's talk about pixel movement

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

i decided to revive another years old dead-ish project i guess

## Why It's Good For The Game

would solve some edge cases with movement and movement delays

introduces edge cases in everything else and changes the entire concept of how movement works

so nah it isn't but let's try this anyways if i don't burn out this time

also massive shoutout to ninjanomnom from /tg/ this is a port-redo-abomination of his work thank you you are a saint

## Changelog
:cl:
experimental: pixel movement wip
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
You know ninjanomnom's work on pixel movement is still ongoing right?

**Comment by deathride58** [comment]
is this the part where i try to push for vector movement for extra dev-related !!fun!! ?

**Comment by actioninja** [comment]
iirc vector movement is planned for ninjanomnom's version eventually because it's needed for a lot of functionality, but it's not considered critical. If someone was interested in implementing it I'm sure he would accept a pr.

**Comment by Iamgoofball** [comment]
just wait for ninjas version

**Pull request closed without merging**
