### PR TITLE
Allow Humans, Felinids, Slimepersons and Lizardpeoples to have Decorative Wings just like Mammals

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request

This give the Decorative Wings body parts to Humans, Felinids, Slimepersons and Lizardpeoples

## Why It's Good For The Game

It was the plan to give to those races wings when it worked, since it work, it is time to give them the wings.
## Changelog
:cl:
add: Added Decorative Wings for Humans, Felinids, Slimepersons and Lizardpeoples.

/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Can you try to get it to not 'break' chars with them getting wings if they had none? Would be good.
Since it happened with the mammal PR.

**Comment by r4d6** [comment]
If I set the "deco_wings" to "None", shouldn't they have no starting wings?

**Review by silicons — APPROVED** [review]

**Comment by Linzolle** [comment]
This actually will "break" it by giving characters random wings if they didn't have it. https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9524 fixes that.

**Comment by Linzolle** [comment]
> 
> 
> If I set the "deco_wings" to "None", shouldn't they have no starting wings?

No, because sanitize_inlist is called. Since old characters have their wings set as "null" by default, it'll pick random wings. #9524 makes it so it defaults to "None" if it's null.

**Pull request merged**
