### PR TITLE
Re-removes Fun

### PR DESCRIPTION
**Pull request by Poojawa**
## Changelog
:cl: Poojawa
fix: Cake Hat returned to normal Citadel values
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Just do what tgstation/tgstation#45001 did if you must, instead of hugboxing balance around a fancy equivalent of a circular saw with burn damage.

**Comment by Poojawa** [comment]
That... just makes them able to be mass produced?

How is that a better change.

**Comment by Ghommie** [comment]
The real peeve is how easy it's to grab one to delimb some folk with very early in the round, but that's something many other easily achievable or not weapons can do already, yet people use this as scapegoat for their "ided".

On the other hand, it always felt sad having to sacrifice a cake hat for the birthday cake recipe and not the other way around.

And I don't even really care if this is a fix to some mediocre nerf that got lost on the 5th rebase or something, the cakehat is neat and the instant K.O. non-crit/dead disembowelment removal has been ported already.

**Comment by Poojawa** [comment]
That's a whole lot of nonsense that doesn't explain why your suggestion that allows for mass-production of infinite welder hats is a good idea

**Comment by Ghommie** [comment]
> 
> 
> That's a whole lot of nonsense that doesn't explain why your suggestion that allows for mass-production of infinite welder hats is a good idea

Mass producing these as you say would take at least twice the effort than using an autolathe for welders or circular saws, and perhaps some botany, cargo and/or extra candles as the kitchen supplies runs short of the required ingredients for this recipe. 
And that PR I linked also allows birthday cakes to be mass produced too, instead of one per shift by default.
So why not? I told you before there is no need to nerf stats like this.

**Comment by Poojawa** [comment]
I do believe there isn't that much of effort.

Someone upgrading the microwaves allows them to make 2-4 in a single run.

So no, that isn't at all a better alternative.

**Comment by Ghommie** [comment]
I think you are mixing up the microwave with the food processor here. The former doesn't play loaves and fishes multiplication unlike the latter.

**Comment by Poojawa** [comment]
```
/obj/item/reagent_containers/food/snacks/store/cake/birthday/microwave_act(obj/machinery/microwave/M) //super sekrit club
	new /obj/item/clothing/head/hardhat/cakehat(get_turf(src))
	qdel(src)
```

Please stop trying to assume I'm retarded. thanks.

**Comment by lolman360** [comment]
> Please stop trying to assume I'm retarded. thanks.

pooj you are tho

to clarify i meant that both of you are confused
upgraded microwave doesn't dupe food just cooks it a bit faster
upgraded processor does duplicate food and work faster 
cake into cakehat is a microwave act and so isn't mutiplied
so yes, upgraded microwaves do allow for cakehats to be made faster but not for cheaper

**Review by silicons — CHANGES_REQUESTED** [review]
10 force, no dismemberment, 5 throwforce, 500 heat, 300 hotspot expose (i'm alright with turning heat/hotspot expose down a bit more if it's more powerful than i thought)
i think that's fair for all involved.

**Comment by Poojawa** [comment]
5 force, it's still just a tiny candle. and puts it in line with other tools like the crowbar

**Comment by nik707** [comment]
@kevinz000

**Pull request closed without merging**
