### PR TITLE
Adds Maintenance Bar+

### PR DESCRIPTION
**Pull request by TalkingCactus**
Adds an expended maintenance bar with a games room, simple cooking area, two dorms, vendors, and a shower. The games room includes dice, coins, a paper bin with a pen, and a custom manual for Dare Dice. You can find it west of telecommunications in engineering maintenance.

- Adds all access clothing vendors to the normal dorms area as well as a costume vendor to the locker room.
- Adds Renault to the Captain's office.
- Fixes access requirements on the HoP's shutter buttons. 

bar

### CODE REVIEW

**Comment by TalkingCactus** [comment]
wew lad it didn't reset my repo

**Comment by LetterJay** [comment]
More community areas are always welcome.

**Comment by Poojawa** [comment]
Could you ensure that the HOP's lane shutters are set to HOP access? Someone on TG realized they were set to cook level access because copy/paste memes.

Also add Renault to Captain's office!

**Comment by TalkingCactus** [comment]
Alright, fixed the buttons and added Renault. Also caught some missing wires to the maintenance APC, merging soon.

**Pull request merged**
