### PR TITLE
you can choose your blood colour on customization

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
we went through the cbt of detaching blood colour from blood type so we might as well use it for more than slime blood
[insert white blood = cum joke here]

this is pretty uninvasive as far as customization changes go because it starts as "None" which means it acts like your blood colour is your species default blood colour

which means absolutely no change is made to anyones savefiles, including no required migrations

here's an example where i made my blood orange as a human
image

as an extra note: this option is not enabled for slimes because a slimes blood colour is already their body colour
and once again yes i spelt it as 'color' in the code instead of 'colour' you damn americans ruining words

## Why It's Good For The Game
all heil customization

## Changelog
:cl:
add: blood colour is now an option on the customization menu
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
based now i can be a greasy homestuck

**Comment by ghost** [comment]
Cool, now I can play an insect with yellow blood instead of diarrhea blood.

**Comment by tiramisuapimancer** [comment]
when

**Comment by timothyteakettle** [comment]
this has a really awful issue in it that I need to fix, i'll fix it once my current testmerged pr is finished (it'll likely end up conflicting so there's no point until then)

**Comment by tiramisuapimancer** [comment]
teak ss413 came back before this pr was ever fixed how do you feel

**Comment by ghost** [comment]
...this is going to be the next #12439, isn't it?

**Comment by DeltaFire15** [comment]
Marking this as stale due to current unmergable state aswell as long period of no commits.

**Comment by DeltaFire15** [comment]
Closing this PR due to staleness. Feel free to reopen once work on this PR is resumed.

**Pull request closed without merging**
