### PR TITLE
Revert "Buffs defib users by making them stop pulling automatically"

### PR DESCRIPTION
**Pull request by GrayRachnid**
Reverts hugbox. There's an upgrade for this.

#8235

### CODE REVIEW

**Comment by GrayRachnid** [comment]
image
no fucking clue how these runtimes have anything to do with this pr

**Comment by Poojawa** [comment]
First, it ain't hugbox so much as QOL, only affects user who has their hands full of paddles. Makes sense they wouldn't be pulling.

Secondly, it also prevents racing off into the sunset to defib at the same time.

Thirdly, update your branch.

**Comment by GrayRachnid** [comment]
> 
> 
> First, it ain't hugbox so much as QOL, only affects user who has their hands full of paddles. Makes sense they wouldn't be pulling.
> 
> Secondly, it also prevents racing off into the sunset to defib at the same time.
> 
> Thirdly, update your branch.

There has always been a defib upgrade specifically to stop people from being shocked.

Besides, only one person can be pulling on them at any point in time, that person is usually the person defibbing them.

"It makes sense" in the real world but this is a video game and some things need to be balanced around what happens more often(In this case, the person pulling being the one defibbing).

And thanks for the tip

**Comment by Poojawa** [comment]
There wasn't always an upgrade disk, Trilby added them

punishing someone who has UI lag is not fun at all, it's a minor QoL tweak for heat-of-the-moment situations. Just nice to have, really.

**Comment by The-Sun-In-Splendour** [comment]
First, based pr
second, merge this

**Pull request merged**
