### PR TITLE
Roleplay Ash Drake variant - "oh no not again" the sequel

### PR DESCRIPTION
**Pull request by IgiariValkyr**
So. Basically someone said "haha roleplay dragon", so I said fuck it. I did this once before for another server, I can do it again. And hopefully be less possessive this time since it's not just a gimmick for myself to feel better.

_*clicks tongue*_ Yeah, I didn't expect to sit here for three fucking hours coding it all over again when I could have been sleeping.

Dragon can't swoop, which means no slams, fire rain, or lava arena.
Dragon fire only goes in a straight line for 8 tiles.
Dragon can penetrate armor much better, but deals less overall damage.
Dragon fast as fuck boi, but if you get 11 tiles away, loses interest. _*Good luck.*_
Dragon can see in the dark with a meson/thermal combo. Can't see items outside its "technical" vision cone, as no x-ray.
Dragon has a unique GPS marker to be found on the map if it exists through admin or random spawn.
I have no fucking clue if it can random spawn.

Pending issues:
Dragon moves way too damn fast. I can't find out how to slow it down.
No visual way to check health.
Fire comes out on any left-click, so it can be accidental on turn. I want to impliment a form of combat mode for this, or change it to a spell button since the dragon _*should*_ be used more for RP.

PaintDotNet_2021-05-02_05-05-05

### CODE REVIEW

**Comment by HeroWithYay** [comment]
The meme is cool and all but what actually is it and why is it good for the game?

Because what I'm gathering from your current description is that it's a weaker but extremely fast variant of ash drake that MIGHT randomspawn and is intended to be controlled by a player yet still has an aggro range?

It really isn't very clear.

EDIT: Is this for vore?

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> The meme is cool and all but what actually is it and why is it good for the game?
> 
> Because what I'm gathering from your current description is that it's a weaker but extremely fast variant of ash drake that MIGHT randomspawn and is intended to be controlled by a player yet still has an aggro range?
> 
> It really isn't very clear.
> 
> EDIT: Is this for vore?

Some admin spawned a player controlled "tomb dragon" earlier today on lavaland for RP or something. I guess they wanted a more RP focused dragon for .... reasons???

**Comment by HeroWithYay** [comment]
> Some admin spawned a player controlled "tomb dragon" earlier today on lavaland for RP or something. I guess they wanted a more RP focused dragon for .... reasons???

But this is for main??? Or am I on the wrong github here?

If my understanding is correct and this is just a poorly balanced version of ash drake that's player controllable (even though regular ash drake is already player controllable).

I don't think this is a very good idea to add.

**Comment by IgiariValkyr** [comment]
> The meme is cool and all but what actually is it and why is it good for the game?

It literally adds nothing to the game but a "slightly more consistent" way of people being able to roleplay as the big dragon.

> Because what I'm gathering from your current description is that it's a weaker but extremely fast variant of ash drake that MIGHT randomspawn and is intended to be controlled by a player yet still has an aggro range?

The bad thing is, I have no clue if it can randomspawn or not. I can't find anything about how megafauna spawn, so it may replace a normal drake, it may not. If it does randomspawn, it should still behave like a drake because it still has loot. So miners don't get all pissed that there's a new-ish mob that drops nothing. As for the speed, I literally can not find a way to lower it. I've tried the speed variable, move_to_delay, and neither of those work. So I off-balanced that with less damage and less health.

> It really isn't very clear.

Yeah, I should have typed better.

> EDIT: Is this for vore?

No fuck you. No vore. Vore bad. How do regular drakes even vore you without killing you first?

>But this is for main??? Or am I on the wrong github here?

No, this is Main. I'm not coding ash drakes for RP, that'd be fucking awful. TG code is bad enough.

>I don't think this is a very good idea to add.

Same, but... you know. Dragon RP. And something new for admins to spawn in centcomm to try and burn everyone off the shuttle with.

**Comment by zeroisthebiggay** [comment]
literal fetish content
**stop**

**Comment by IgiariValkyr** [comment]
> 
> 
> literal fetish content
> **stop**

mate i don't give a fuck about simplemob vore it doesn't work half the time. quite literally the mob will kill you before it vores you if the vore trigger of the _Original Ash Drake_ even procs at all. If i could remove the vore function from this one, I would.

**Comment by zeroisthebiggay** [comment]
> mate i don't give a fuck about simplemob vore it doesn't work half the time. quite literally the mob will kill you before it vores you if the vore trigger of the _Original Ash Drake_ even procs at all. If i could remove the vore function from this one, I would.

vore or not this is an ash drake for the sole purpose of (and in your words) """"""""""rp""""""""""
I can't say offensive words on github but damn you have to be a scumsucking troglodyte if you think anyone on citadel main is going to play as an ash drake for any reason but one of these two things

A: ERP; this is fetish content
B: murderbone; this is addition solely exists for someone to gank miners and find a way to get on station and rampage on there

look me in the **eyes** and say this content is *'good for the game'* regardless of what people use it for
just because you or some admin want to/want people to play as an ash drake and rp being a **uwu dwagon** and showing people your epic pile of watcher bones you substitute as your hoard doesn't mean that this entire playerbase is going to use this opportunity for anything but degenerate/malicious play

even if this isn't going to spawn and it's just for admins to fuck around with it's just worthless bloat weighing down the file size; any admin who wants to use a drake in their event is going to

A: spawn the lesser drake; it's literally what you're trying to implement in core concept but better in every single regard
B: not do that; because giving players megafauna control outside of anything but EORG is a fucking psychopathic maneuver that would get you demoted on any other server but our ratchet-ass system where admins can do whatever they so-desire so long as it's an *'event'*

> > I don't think this is a very good idea to add.
> 
> Same, but... you know. Dragon RP. And something new for admins to spawn in centcomm to try and burn everyone off the shuttle with.

>Same, but...

you said it yourself
it isn't

p.s.

> I have no fucking clue if it can random spawn.

**test your fucking code** holy shit

**Comment by silicons** [comment]
if the admin in question doesn't know how to do everything your pr does with vv and proccall, they aren't well trained enough to be trusted to erp as an ash drake

**Pull request closed without merging**
