### PR TITLE
magnetic rifles are now properly flagged as "nodamage"

### PR DESCRIPTION
**Pull request by silicons**
image
:blobcat: :gun:

### CODE REVIEW

**Comment by Poojawa** [comment]
uh. what

**Review by Trilbyspaceclone — APPROVED** [review]
Makes peacefull characters use mag guns!  <3

**Comment by silicons** [comment]
@deathride58 hi are we making them less than lethal and not completely nonlethal?

**Comment by Ragolution** [comment]
Emergent gameplay.

**Review by Ragolution — CHANGES_REQUESTED** [review]
Emergent Gameplay

**Pull request closed without merging**
