### PR TITLE
PROPERLY removes roboticists from engineering channel 

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

why is this a thing

## Why It's Good For The Game

robotics has nothign to do with engi and hasn't for the last decade

## Changelog
:cl:
del: robotics can't get on engi comms anymore
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
@kevinz000 make it so robotics spawns with them then and make it so you don't have to use money on the vendor to get them smh my head

**Comment by MrJWhit** [comment]
> @kevinz000 make it so robotics spawns with them then and make it so you don't have to use money on the vendor to get them smh my head

Give CE access to robotics if they're going to be a weird lovechild of science and engineering.

**Comment by Linzolle** [comment]
ok but then why do they need to exist if they're gonna be reskinned science encryption keys? Just remove em.

**Comment by YakumoChen** [comment]
Since when did robotics have engineering comms

**Comment by Trilbyspaceclone** [comment]
They always has had engineering comms,

**Comment by YakumoChen** [comment]
Is that a cit change? All my time on TG and I never heard the engineering channel while in robotics.

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
Wait, actually... Do what Linzolle suggested and remove them altogether, lazybun.

**Comment by IronEleven** [comment]
There's a coin-only Science/Engineering headset in the Robotics vendor.  It's a nod to the days when Robotics was considered part of both departments and located right next to engineering (where t-comms is now on box), Yakumo.

**Comment by Ghommie** [comment]
Oh yea, right, this is a sacred relic of the old days, and only used as a premium item in the roboticist vendor. No touchie.

**Pull request closed without merging**
