### PR TITLE
Universal blood quirk

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Adds a new 2 cost quirk which sets your blood type to U (universal) Randomizes your blood type on loss of the quirk or sets it to your species specific blood type on loss.

## Why It's Good For The Game
I wanna be a 'vampire' that can take pretty much any blood type, costs 2 points and is arguably not that powerful due to the ease of making SY (synthetic blood) that all blood types can accept.

## Changelog
:cl:
add: New quirk that gives you the universal blood type (U), which allows you to receive all blood types aside from HF, X*, GEL. 

/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
Synthblood requires a chem dispenser or a blood  bank (which requires blood inside of a blood bag to function). That isn't a one to one.

**Comment by deathride58** [comment]
Yeah, I'm really not feeling this. This is fairly out of line for what's expected out of positive quirks, that being that they're optional traits that largely affect edge case scenarios (such as night vision or light step), or have some sort of noteworthy drawback associated with them (such as drunken resilience or polycythemia vera, the former's drawback being that you have to get drunk to use it, the latter's drawback being that medbay has to burn through more blood to revive you if you've died violently)

For the trait proposed in this PR, there's genuinely no drawbacks. There's a pretty huge benefit: you no longer have to care about blood that goes into you. Blood transfusions exist largely as a soft equipment check; you either need a source of the _right_ blood type (plus a med scanner for those without exotic blood), or a chem dispenser to make synthblood, in order to restore blood safely. As blood is a fairly major resource for healing, the trait in this PR takes out every bit of risk involved in healing and being revived without the proper equipment.

**Comment by Poojawa** [comment]
wait, why did chemistry get to mass produce synthblood. reee!

**Comment by bunny232** [comment]
Idk, i just see synthblood being stupid easy to obtain, so a decently expensive quirk to bypass it doesn't seem unreasonable.

**Comment by deathride58** [comment]
Closing due to above-mentioned balance concerns. The idea admittedly would be fairly neat if paired up with some sort of quirky caveat (like only being able to restore blood from direct ingestion, and hunger only from drinking blood, maybe?). But as it stands right now, this PR with its current scope is simply problematic for game health.

**Pull request closed without merging**
