### PR TITLE
removes zoomba/roomba borg sprites

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
removal of small and uninteresting sprites for borgs

## Why It's Good For The Game
borgs are already powerful in combat, they don't need a module that allows them to avoid center mass clicks

## Changelog
:cl:
del: removed zoomba
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
salt pr 2

**Comment by Ludox235** [comment]
Salt pr 2

**Comment by TheObserver-sys** [comment]
This ain't it chief

**Review by silicons — DISMISSED** [review]
transform = new /matrix
transform.Scale(1, 2)

there's your nerf

alternatively change the sprite but that's effort

**Comment by ghost** [comment]
Good first PR

**Comment by MrJWhit** [comment]
I think it's good to just remove them.
They're just too small and even if you increase the size, they're going to *still* be in the bottom half of the square rather than the middle like everything else.

**Comment by Tupinambis** [comment]
Not only do they prevent center of mass clicks, but they also just look ugly, and they look more like circuit bots than cyborgs.

**Comment by Ragolution** [comment]
Booo

**Comment by Sishen1542** [comment]
img
@BlackMajor

**Comment by timothyteakettle** [comment]
suggestion: let this be a pAI sprite or a new cleanbot sprite

**Comment by jack-avery** [comment]
The sprite even with an upsize still takes up a very small portion of the tile it's on since a majority if it is just the lower area being the main body and the antenna being a whopping 1 pixel (3 at max if we're gonna be stingy). The sprite generally looks ugly, clashes horribly with the art design, and is often picked because "haha roomba funny". Most of the argument for keeping it would be just that as well, haha funny. Remove it.

**Comment by moltoretardo** [comment]
If normal carbons can’t have smaller size because of powergame I don’t understand why borgs should have it.

**Comment by lolman360** [comment]
i like them but probably because i haven't had to fight a 1/3rd sized borg with a stunarm yet

**Comment by BlackMajor** [comment]
Honestly I've bullied keb since he added these for being the dumb catboi he is for adding a sprite that would be used for powergae.

Personally I'd prefer upscaling them but like, with how sprite scaling works that'd end up looking awful unless you just redrew the whole thing, and to get that looking like a roomba while maintaining the same proportions wouldn't quite look right.

So, press F for Roombas.

**Pull request merged**
