### PR TITLE
Adds more Polychrome gear to the Loadout system

### PR DESCRIPTION
**Pull request by Ragolution**
Requested by a Moff

Enables Polychrome
- That one tanktop
- jumpsuit
- Skirt
- swimsuits
- A few others.

### CODE REVIEW

**Comment by Michiyamenotehifunana** [comment]
Wait I thought the hoodie and the shimapantsu were supposed to be donator tier items

**Comment by Ragolution** [comment]
> Wait I thought the hoodie and the shimapantsu were supposed to be donator tier items

Shit, are they? I'll take them out if they are.

**Comment by Michiyamenotehifunana** [comment]
> 
> 
> 
> 
> Shit, are they? I'll take them out if they are.

I mean, #7589 is pretty stale at this point. If anything, we could just get Jay's word on all the stuff added in #6465 and #6331.

**Comment by Michiyamenotehifunana** [comment]
Oh hey, #7621 seems to have attempted to do the same thing as this. Still worth a shot at asking @LetterJay about it again tho.

**Pull request closed without merging**
