### PR TITLE
🅱️oneless

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
remove bones from slimes

## Why It's Good For The Game
its logical and it was in the wounds comments anyways
e

## Changelog
:cl:
tweak: 🅱️oneless
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
dangerously based

**Comment by timothyteakettle** [comment]
didn't include it in the wound port because i didn't want to do lots of balance choices when porting something, pretty based imo though

**Comment by TheObserver-sys** [comment]
At last, no more crunchy slimes.

**Comment by moltoretardo** [comment]
Making slimes.,,,more op.,,,. Fetish content,,..???

Joking aside they should probably have something to compensate for that buff.

**Comment by Linzolle** [comment]
This basically makes slimes superior to other races completely mechanically which is kinda, no. If they have no bones there _needs_ to be some kind of offset that doesn't make them immediately better gameplay-wise.

**Comment by ghost** [comment]
Do citadel slimepeople not die to cold? Getting wrecked by 2 shots from a fire extinguisher is a pretty reasonable tradeoff imo.

**Comment by Sishen1542** [comment]
> This basically makes slimes superior to other races completely mechanically which is kinda, no. If they have no bones there _needs_ to be some kind of offset that doesn't make them immediately better gameplay-wise.

they already die from 5u of charcoal/tricord and we have races with the no_flesh tag and i don't think anybody whined when that was brought about which stops them from dying from *stacking bleeds when we already have hyperlethal poojblood* (in the wounds port)

> Do citadel slimepeople not die to cold? Getting wrecked by 2 shots from a fire extinguisher is a pretty reasonable tradeoff imo.

yes, but extinguishers dont do that. has to be atmos cold, frost oil, etc

**Comment by Ragolution** [comment]
howmst the fuck do i :b: onless smite them now?

**Comment by Sishen1542** [comment]
> howmst the fuck do i 🅱️ onless smite them now?

bloodless smite them once i fix the poojblood changes so they can go into negatives without dying again (will just knock unconscious and remove limbs over time)

also lin and pals, suru helped me realize something earlier.
removing bones from a carbon mob makes them easier to delimb, since you have to only cut through flesh instead of flesh and bone.
also people are crying about them being immune to a wound type while plasmamen/skeltals are immune to __***three wound types***__ (cut, pierce, burn)

**Pull request merged**
