### PR TITLE
Fix the megafauna problem

### PR DESCRIPTION
**Pull request by r4d6**
##  About The Pull Request
This expand the area around the mining base with a zone that is hopefully safe of 15 tiles around the base

## Why It's Good For The Game
Megafauna spawning 3 tiles from the base is bad

## Changelog
:cl:
fix: Megafauna shouldn't appear right next to the mining base anymore.
/:cl:

### CODE REVIEW

**Review by silicons — CHANGES_REQUESTED** [review]
I'm going to need an actual re-justification at some point of why randomized mining base is even needed.
What problem is it solving, what improvement is it making because here is the thing:
15 tiles is barely two non-wide-screens. Two screens is not acceptable distances for tendrils, megafauna, ruins, or ANYTHING to be spawning procedurally generated from the mining base.
If it's any bigger, via MAP PADDING, like I specifically said should not be done, you have the issue of mining base not fitting on the map edges, which is exactly where it should be. There's no damn reason for it to be centered. At all.

The fix once again is to make a post_load() proc if it doesn't exist already and use it to artificially pad the area around the spawn area with an /area to blacklist ruins and mobs and anything like that from spawning.
And even then I'm still at a loss to why randomization is needed at all.

**Comment by Ghommie** [comment]
Sadly, conflicts.

**Comment by Trilbyspaceclone** [comment]
@kevinz000 I personly dont like Rng miner base as well but its main alure is 3 fold
Meta braking,
Anti-Gulag brake out,
Harder Navigation for miners,
Meta brakes the meme of just all ghost roles like vet, bumbs and other from magicly knowing just head south west.
Makes Gulag less of a joke as now you likely can not survive the 3-4 tile jump + dealing with possible wild lands.
Makes GPS's for miners more usefull to get back to the base rather then again magicly knowing just head south west.
Game wise its a really really good idea, as well as in practice.
The few downsides it has are like right now and a other pr being addressed
Unsightly zone bottom left.
Closer to some ruins/ashies.
Closer to mega funa.
This pr seems to fix the to close to mega funa and we just mered the unsightly  zone in the bottom.

**Comment by YakumoChen** [comment]
I actually didn't do shit about the lavaland area where the old base was, all I did was clean up the zone around the mining base so it looks like a less ugly lava tumor in the middle of lavaland.

That said I'm with kevin. None of the actual justification for random mining base is any good, aside from fucking with gulag'd players (something that can be done easier by just expanding the moat a tile or two in a certain spot). 
Mining navigation does not need to be made harder (why?)
ghost roles are fine / very inconsequential to the game regardless, ash liggers are actually the bigger problem and the random mining base makes it generally easier for them to access it.
There isn't really a stated reason to "meta break" the lavaland base and the downsides of it far outweigh the upsides
Tendrils / Megas should not be spawning close to the base
The southwest area is already a mapped out safe zone for miners, makes sense from a realism perspective (a small surveyed area that is partially mined out to start from), and hasn't been cleaned up at all after the mining base was moved away from it (due to incredibly lazy mapping)

**Comment by silicons** [comment]
we're reverting random mining base

**Pull request closed without merging**
