### PR TITLE
Removes a plush representing the character of an underage player.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removed a plush representing the character of a player that was banned for being under-aged

## Why It's Good For The Game

As this item was made to represent the character of an underage player, It should not be in the game.

## Changelog
:cl:
imagedel: Removes a moth plush from the game.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
-Removes one of the plush for no reason other then player salt
-Keeps the other banned player(Legit for the same reason) plush
Hmm, you not even going to remove the donor items that are also from banned underaged players?
Legit no reason to remove a plush

**Comment by Tupinambis** [comment]
> > Removes one of the plush for no reason other then player salt
> > Keeps the other banned player(Legit for the same reason) plush
> > Hmm, you not even going to remove the donor items that are also from banned underaged players?

Not sure what's with the tone, but I don't know what other players you are referring to, and thus don't know that they should be removed.

**Comment by Trilbyspaceclone** [comment]
@Tupinambis jecca was banned for the same reason, in fact her donor item is still a thing that is linked to her Ckey.

**Comment by Ghommie** [comment]
@Trilbyspaceclone In my honest yet amateurish opinion, donator exclusive contents should be only ever contained within the server's game folders, a git submodule and/or similar, only leaving the framework required for said donator loadout to work, since such user-tailored fluff shouldn't concern the average gameplay.
That's some hot garbage owners/members, not contributors, will hopefully handle someday, so don't mind it on Tupinambis.

**Comment by Trilbyspaceclone** [comment]
@Ghommie Do to how a few things pull items you can get donor only gear.
X-miss tree is one as we as the Gift Box.
But ye I just thought it was unfair that you remove ***One*** of them, and not the known other.
Is also distasteful to call them "cursedplush"

**Review by silicons — APPROVED** [review]

**Pull request merged**
