### PR TITLE
*jerks

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Now wanking gives you mood boosts, I had to go on a self hosted server and give myself a dick to test this so it better be merged.

also arousal code is shit

### CODE REVIEW

**Comment by ghost** [comment]
guppy hitting a new low

**Comment by ghost** [comment]
also unrealistic, there should be good and bad orgasms

**Review by deathride58 — APPROVED** [review]
<span class='warning'>My mood gets worse.</span>

**Comment by mattmatterson111** [comment]
InterBay ripoff!

**Pull request merged**
