### PR TITLE
Making this PR to potentially lessen the ridiculous resource download time takes less time than downloading resources.

### PR DESCRIPTION
**Pull request by silicons**
Might make it not take four fucking minutes to get into the game.

### CODE REVIEW

**Comment by Poojawa** [comment]
inconsistant because it doesn't take me 4 minutes, lol

**Comment by nero1024** [comment]
Will this remove the preload screen? I like the preloader b/c I know the game won't a laggy unplayable mess while everything is streaming in for the next 10 mins.

**Comment by silicons** [comment]
@nero1024 Thsi will definiteiyl, definitely need a testmerge but in theory, it'll make you download everything *required* and then download the rest slowly
@deathride58 do you know how this stuff works because all I know is "0 is the baystation slow load while in game, 2 is tgstation load everything at once)

**Comment by nero1024** [comment]
TG doesn't load everything at once though, there's no preloader the last time I played on Bagil a couple of months ago.

**Comment by silicons** [comment]
@nero1024 it definitely does.

**Comment by silicons** [comment]
eh

**Pull request closed without merging**
