### PR TITLE
Ports long range atmos analyzer from skyrat

### PR DESCRIPTION
**Pull request by SiliconMain**
Point and click, should work on anything that a normal one can scan
tested, compiled, works
thanks putnam for holding my hand through spooky c++ atmos
also adds it to science protolathe because toxins is a thing

:cl:
add: Ported the long range atmos analyzer from sk*rat, credit to NotRanged
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
This is great and I'm happy to have it, but are we positive that a red analyzer is the best color? It screams syndicate too much for me.

**Comment by SiliconMain** [comment]
also has a bugfix for jaws of life regarding labels on them, forgot about that

**Comment by SiliconMain** [comment]
compiles on my machine not sure whats up with travis

**Comment by silicons** [comment]
request of author

**Pull request merged**
