### PR TITLE
Officially ends the non-stop thrill ride of coating the station in your gender fluids for "fun"

### PR DESCRIPTION
**Pull request by CameronWoof**
## About The Pull Request

Genitals that produce fluids (testicles, wombs, breasts) are now capped at a capacity of 15, rather than 50. They also produce at a rate of 0.035 units per life tick, down from 5.

## Why It's Good For The Game

The sex fluid decal spam has outstayed its welcome. It now takes approximately four-to-five minutes to "regenerate" enough fluid to create floor decals, instead of the two seconds it used to. You can climax as much as you want in the meantime, but if you want to make a mess anyone can see, you'll need to save up.

## Changelog
:cl:
tweak: Fluid-producing sexual organs no longer start full
tweak: Sexual organ fluid capacity decreased from 50 to 15
tweak: Sexual organ production rate decreased from 5u to 0.035u per two seconds.
tweak: Sexual fluid decals no longer contain reagents
tweak: Sexual fluids cannot by synthesized (e.g., by the Odysseus)
/:cl:

### CODE REVIEW

**Comment by chefferz** [comment]
Nerfing fluid production this much just because of a single round where a clown threw cum grenades is borderline grudge coding. 

Being cut down 333333% is unnecessary.

**Comment by chefferz** [comment]
Nerfing fluid production this much just because of a single round where a clown threw cum grenades is borderline grudge coding.

Being cut down 33333% is unnecessary. Although I will agree it's a bit excessive, there's a reason there's traits like nymphomania and masochism, and seeing as you've made it very clear you dislike the sex based/ERP based functions of the server, this is a huge stab to it.

Cut the fluid production down a bit, but that much is way unnecessary.

**Comment by CameronWoof** [comment]
The purpose of the arousal system and the traits you linked is to facilitate roleplay. Having unfettered access to massive amounts of decal-spreading reagent that people then walk around and passively leave snail trails of or go out of their way to put into grenades does not.

This isn't about you, specifically. The idea of putting cum in grenades and lobbing them all over the station was not your idea. It's an old one, and a tired one, and one that time and again does nothing but reduce round quality and destroy any believable atmosphere for roleplaying.

**Comment by chefferz** [comment]
I'll agree that it's a bit ridiculous, and needs to be cut a bit, but that high of a percentage is extreme.

**Comment by CameronWoof** [comment]
You can mess up the floor once every ten minutes or so. If you can give me any kind of reasonable, roleplay-inspired explanation for why you'd need to be able to do it more than a few times per round, I'm all ears.

**Comment by BurgerLUA** [comment]
Honestly I'm going to say it but we really need to stop with the "muh grudge coding" response to every pr. It's honestly a fucking meme at this point and almost a miracle that anything ever gets merged with this shitty attitude.

Cum grenades have plagued Citadel since the beginning of time. They're no longer consider funny because the ones making and detonating them are creeps. Like you can say "just a prank" all you want but if you examine the people doing this, not just clowns, they're some of the most snowflake, fetish obsessed creatures on citadel. It is not a prank, it's god damn fetish content.

**Review by BurgerLUA — APPROVED** [review]

**Review by silicons — CHANGES_REQUESTED** [review]
make it something reasonable like 1 or maybe 0.5 first please.

**Comment by silicons** [comment]
also keep the start full thing.

**Comment by CameronWoof** [comment]
The last commit doesn't do what the commit says. It actually reduces the 5u timer to 5 minutes.

**Comment by CameronWoof** [comment]
@kevinz000 I've halved the time it takes to generate 5u (the amount needed to create decals) to 5 minutes. With that in mind, do you hold to your review that it needs to be faster and accessible roundstart (and, as a result, able to be abused by slimepersons to circumvent the entire PR), or can this be merged?

**Comment by Bran34** [comment]
Just play janitor, fam.  Cum grenades sound hilarious and this is an 18+ server.

They're just decals.  who even actually cares?  If you can't stand the sight of pixelated sexual fluids maybe don't play on an 18+ furry server where everyone has genitals?

**Comment by nik707** [comment]
> Just play janitor, fam. Cum grenades sound hilarious and this is an 18+ server.
> 
> They're just decals. who even actually cares? If you can't stand the sight of pixelated sexual fluids maybe don't play on an 18+ furry server where everyone has genitals?

t.Man who wants citadel to be an LRP shitfest

**Review by silicons — APPROVED** [review]

**Pull request merged**
