### PR TITLE
TGUI alerts, lists, inputs

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title, includes all the cbt.
image
image

## Why It's Good For The Game
Does it?

## Changelog
:cl:
tweak: Replaced alerts, input lists, inputs and so on.
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
Actually i just don't know, but `sync` didn't want to go away.

**Comment by Solaris-Shade** [comment]
@SandPoot You magnificent person!

Speaking of CBT.....

image

Might want to look at the line endings in these two map files, I think they are borked. I know @silicons recently did a PR to correct a mapping issue along the same lines when the files looked like this.

**Comment by SandPoot** [comment]
<h2>I am serious this time, do not merge this without testmerging first and giving reviews!!</h2>

**Comment by SandPoot** [comment]
Conflicts solved.

**Comment by SandPoot** [comment]
Conflicts gone

**Comment by SandPoot** [comment]
I'd like to remind everyone that this is not a 1:1 copy of what tgstation did, this simply brute forces the simple menus to become tgui.

**Comment by LetterN** [comment]
tg abruptly axed this as i do not see `tgui_input_text.dm` on their code, also this is from virgo.

**Pull request merged**
