### PR TITLE
wizard timestop parrying katana

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
what the fuck do you think this is
## Why It's Good For The Game
pressing G for a timestop can't have repercussions if it's an adminbus-only object
(you also have to get hit by something while parrying)
## Changelog
:cl:
add: New item: Temporal Katana. 2 points for wizards, timestops upon successful parry, bokken quickparry stats (100 force on melee counter!).
add: Also you can *smirk. This has no mechanical effect, other than being smug.
/:cl:

### CODE REVIEW

**Comment by TheObserver-sys** [comment]
I fear few things. But Hatterhat? They scare me.

**Comment by Kraseo** [comment]
Minotaurs smirks... moment

**Comment by moltoretardo** [comment]
New wizard weapon when

**Comment by Linzolle** [comment]
play a real shin megoomy tensay image

**Comment by Hatterhat** [comment]
i forgot the title but thank you

**Pull request merged**
