### PR TITLE
Revoices awoo.ogg

### PR DESCRIPTION
**Pull request by monster860**
## About The Pull Request

I have revoiced awoo.ogg

## Why It's Good For The Game

The audio quality of the old awoo.ogg is, according to certain Yogstation members, "is really bad, I bet you could record your own that would be twice as good." I will leave it up to you to decide if this is actually "twice as good".

Old: https://cdn.discordapp.com/attachments/411919031260545024/754917271758962718/awoo.ogg

New: https://cdn.discordapp.com/attachments/411919031260545024/754916822939205662/better_awoo.ogg

## Changelog
:cl: monster860
soundadd: Revoices *awoo
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
11/10 pr love it!

**Comment by TheObserver-sys** [comment]
Why does it sound like a cat throwing up a hairball while attempting to meow?

**Comment by MrJWhit** [comment]
It sounds bad.

**Comment by ReddicusDragon** [comment]
11/10 sounds better than old

**Comment by KeRSedChaplain** [comment]
both are bad remove awoos from the code 😎

**Comment by davidchan13** [comment]
Even as a meme this is pretty shit.

**Comment by lolman360** [comment]
once again, monster's voice disappoints.

**Comment by ghost** [comment]
quirky

**Comment by rossark** [comment]
Honk

**Comment by silicons** [comment]
.. sorry but nah

**Pull request closed without merging**
