### PR TITLE
Botany max yield is now 4, max potency 250

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Same total ingredients. Might actually be a buff????

## Why It's Good For The Game

image

## Changelog
:cl:
tweak: Botany yield has been reduced and potency increased accordingly
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
Honestly, I don't think this will solve the problem of hundreds of items on a tile causing crashes, especially when botany can be scaled up infinitely. There is also a whole issue of plants being capped at how much they can hold reagent wise which makes this a hard nerf too. I think it would be overall better to go  with a rotting mechanism to force plants on the floor to clear up.
Edit: bees are not accounted for here, meaning you are possibly looking at 2 yield without them.

**Comment by silicons** [comment]
we do realize what 250 potency does right

just make items not harvest if the tile is stacked tbh

**Comment by silicons** [comment]
also at a certain point it's an administrative thing of like

"hey please don't intentionally [crash] the server, the funny gets unfunny when no one gets to play"

**Comment by Putnam3145** [comment]
yeah i've got a better thing in mind lol

**Pull request closed without merging**
