### PR TITLE
Reducing prefilled hypospray kits availability.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. Moved prefilled hypospray kits to the premium category of the med vendor, added DIY empty versions in their place. Replaced chemists trico hypo kits with the DIY variants.

## Why It's Good For The Game
Aiming to encourage players to use the healing mixes they made throughout the round instead of relying premade stuff.

## Changelog
:cl:
balance: Moved prefilled hypospray kits (save the organomaly one) to the premium category, replaced them with an DIY kit.
balance: The chemist job now starts with a DIY hypospray kit instead of a prefilled version.
balance: Reduced the capacity of chem-master printed hypovials from 60 to 30.
/:cl:

### CODE REVIEW

**Comment by Poojawa** [comment]
What was overpowered about them that requires this level of nerf?

**Comment by lolman360** [comment]
i always thought there were too many hypokits. good pr.

**Comment by silicons** [comment]
in that case is there a reason to be axing how available the actual hypokits/hyposprays are, versus just completely replacing them with a few empty hypokits? 
i don't think the hyposprays are the issue, versus the ~120 units each of free reagents roundstart that doesn't require any mixing.

**Comment by Ghommie** [comment]
If that's so, I'll probably move hypokits (save the macro-fixing one) to the premium category and add a few empty hypokits in their place. Good thought.

**Comment by Trilbyspaceclone** [comment]
Oh hey restock units might be gotton by medical now for more hypo kits or something, neet

**Comment by silicons** [comment]
@Trilbyspaceclone restock units won't matter if you can't reconstruct the vendor

**Comment by Trilbyspaceclone** [comment]
@kevinz000 All medical ones can be deconed and remade tho?
Unless its bugged*

**Comment by silicons** [comment]
@Trilbyspaceclone if that is a thing now I'm not aware of it, but I'll take your word for it.

**Comment by ghost** [comment]
lowering the liquid capacity to hypovials sounds like the exact opposite of what you want to do to get people to make their own mixes
20u is BARELY anything if you want people to make mixes at the chem master
i get moving the filled ones to premium, okay that's a good nerf
but nerfing capacities does nothing except clutter people's inventories with more vials and makes healing more tedious
also making people rely on chemists for the most used chemicals is a bad idea considering citadel is hitting a stage of constant low pop

**Comment by Ghommie** [comment]
You can print normal and large hypovials at the autolathe. Half the station maps have an apotechary chem dispenser, Two other chem dispensers exist, another chem dispenser board can be found in the tech storage.

Learn to use the resources you were given.

**Comment by ghost** [comment]
2 require chemistry access
1 requires an AI or engineer + materials
even if we can print normal vials it's completely inconvenient to have to go all the way to cargo just to use the lathe
AND manually put them in your chem master each time you want to make a mix

**Comment by Ghommie** [comment]
Issues totally intended, you have to work for it one way or another, that's the point.

**Comment by lolman360** [comment]
5u bicard/kelo/antitox heals 12 of their respective damage over 12 ticks.

**Comment by ghost** [comment]
>issues totally intended

doesn't mean they're good issues lol

**Comment by Trilbyspaceclone** [comment]
@Commandersand if we are hit with always low pop then you as a medical doc always have chemist access...

**Comment by silicons** [comment]
@Trilbyspaceclone not an argument
@Ghommie why are the max capacities being nerfed again? this makes them marginally more useful over pills/patches which is a big yikes, not everyone's going to carry beakers to beaker juggle (and it shouldn't be the end all anyways)
large hypovials only fit in cmo ones, printing more isn't going to solve the issue here. hypovials are already relatively unviable for use in mixing, so where's the problem here?
that said
@commandersand : 
add hypovials to medilathe if you care so much
and i don't know on what world people insert hypovials into chemmasters to make their mixes, because i've personally always used beakers so that's not a problem with this pr either.
there's nothing wrong with making people mix their chems, there's other healing chems more than available in the vendors and kits, so yes, i agree with the sentiment of learn to deal with it/use the station resources (not to encourage greytiding :^) but if there's no engineers and no ai i'm sure you can find another way to grab a chem dispenser board when necessary, and until you can there's plenty of more ways to get healing/chems.)
however i do not see the reagent capacity nerf as necessary at all. they already have a pitiful injection time, what's the deal?

**Comment by Ghommie** [comment]
The max volume is being nerfed because long time someone compared them to patches/pills and not syringes, then decided to double their capacity... while leaving them half-empty (keep in mind pre-filled vials start full now),
This was pointed out in a PR improvedname did a while ago that was thankfully turned down because he wanted to double the reagents volumes too to solve this irritating peeve.

**Comment by Trilbyspaceclone** [comment]
@kevinz000  - Yes it is an argument do, if we have normal pop we likely have a chemist/hop/cmo/cap or somone that is able to take the spare ID and give out upgraded access/help fill files
Second, as a medical doc your likely using the hypo's at first as theirs limited viles, large hpyos are beakers + do to being none melt-y unlike beakers iirc - Could be wrong but double checking the code they should never melt.
Third - They should likely kinda need restock units to get more hypo's, Poojawa always intented for you to not just be able to print them or get more flat out hypo packs form cargo. This is likely tho I know not of its true intent was for the restock units to be used rather then cargo being able to get the rather powerfull tool of a hypo, that is flat out the best for most cases as you can both spray and inject at any time leading to a skilled player cutting down on un-needed wasted space with patches or pills.
Hell, it feels the same speed and if you get a better hypo - CMO - Its flat out faster. The only cases were your better have having 30 patches/pills is when you have a belt full of pill bottles with different chems for touch based things, or chem mixes that heal mega fast like back in the old days when Runtime was around.

All in all these are good changes, that should help increase skill of players that franky these grate tools. I still see people that dont know you can swap the injection to patch, and I still see people that dont understand how good these tools are. Medical players i.g not all but i.g have gotton worst and worst being unable to handle basic under any kind of stress. In part I would have the theory that they have so much QoL and amazing tools on top of backups of things that they lost their skill and now "need" these things in order to do their job. 

The state of skill here is a joke, and we should try at lest to raise it a little with some micro management of chems, we already removed micro management of patches vs injection with that damn tool.  

- Thank you for coming to my TED Talk

**Comment by silicons** [comment]
- we do not code solely to fit lowpop and do not care to make things only compatible wtih lowpop
- large hypos are cmo exclusive right now
- yes, the cmo's is supposed to be faster, that's kind of obvious and is not really a factor.

**Comment by silicons** [comment]
still not sure about this tbh should have made the vendor separation/removing the premixed chemicals and nerfing capacities separately

**Comment by ghost** [comment]
yeah i don't mind the vendor nerfs
but the capacities really butcher hypovials

**Comment by Trilbyspaceclone** [comment]
@kevinz000 Kev, you use the large hypo's as better beakers. Your fully missing the point

**Comment by Chiirno** [comment]
@Trilbyspaceclone Large hypovials are certainly not just better beakers. The only advantage you gave was that they don't melt under high pH levels. Without Fermichem this is hardly a thing anymore, you'd need to be more precise as to not overstate how little an advantage this is, especially in the presence of xtra large beakers. Besides that, large hypovials both cost a more valuable material (in my estimation), that being iron instead of glass AND you cannot drink out of a hypovial which i consider a pretty large nerf. I'd say large beakers are better.

I don't think adding minutiae and tedium to the role will give us a more robust medical staff.

**Comment by lolman360** [comment]
steel and glass are on par costwise, there's a shitload more steel spawns on station and in maint and w/e (oranges was right about materialcreep) and sand for glass is piss easy to get with a shovel

**Comment by Chiirno** [comment]
True, I've been playing ghost roles so the difference is more relevant to me.

**Comment by Poojawa** [comment]
Okay so, being the author of the mk iis. 

They were intended to be the go between of patches and pills, being able to reduce clutter and being able to swap between inject and spray modes more as QoL than being overpowered.

The delayed application was purely to combat the old meta of the CMO's hypo being able to stealth instant click death with literally no ability to avoid it other than wearing a hardsuit. It was introduced at the height of chem warfare being the ultimate weapon to spam. 

When it was doubled capacity and reduced times, I objected to it, because it was a lazy change of convenience. That's why for ages they came half filled. they just quickly web edited capacities and PR'd.

Vials are not supposed to be able to be splashed, because being able to mass print splash potions was overpowered as fuck. You can syringe them but not splash. 

Small Vials were intended to be printed from chem master and at some point they got added to medical protolathe and it's like w/e. Useless without the actual injector _as intended_. the CMO's larger capacity for both application and vial size is more a nod to how Heads of Staff should always have superior equipment that makes them viable and valuable to steal. Even still the CMO's hypo had a slight delay so you could at least fight against it though.

Availability in the vendors was more to provide antagonists with the ability to acquire potentially helpful healing that would support inject or spray heal-mixes. It also is hella useful in general for snagging a 'oh shit we need a burn kit' and sprinting out to help people out. 

They're only supposed to have tier 1 chems at the start, and that's been on the nerf list for years at this point to be less effective besides just a shitty OD mechanic. It honestly isn't any different from the specific pills/patches with far more powerful versions of their respective chems pre-loaded in each medkit.

hypo medkits comes with 120u of respective chems, which unless the chems've been buffed would only result in ~120 omni heal of the body. the tricord being less effective obviously. 

White medikits come with 24 charges of limb-specific 20 brute heal and of burn heal each (480/480), as well as a pack of gauze (60 Brute + bleed suppress) and medipen. 

Why did you buff regular medikits, then want to nerf the hypos?

**Comment by Ghommie** [comment]
@silicons Reverted the "reduced vial capacity" portion of this PR as requested.

**Comment by Ghommie** [comment]
Stale.

**Pull request closed without merging**
