### PR TITLE
Makes a Mehki Top hat 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]:(Buffs the Mehki with a top hat that is shrouded in mystery)

[why]: (The Mehki Anderson allways wares a top hat when they can, its has gained many rumors and mystery of how it came to be. It was more then likely form a store or form there home. But who knows, other then The Mehki!)

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
This is beautiful and I love it

**Comment by Useroth** [comment]
Add a "steal" objective to go with it.

**Comment by yourdoom9898** [comment]
Wouldn't in be "worn by Mekhi," instead of "warn by Mekhi,"

**Comment by Wilchenx** [comment]
make the wearer valid

**Comment by deathride58** [comment]
It's Jay's decision of whether or not this should be allowed

**Review by LetterJay — APPROVED** [review]

**Comment by LetterJay** [comment]
@Trilbyspaceclone Conflicts

**Pull request closed without merging**
