### PR TITLE
change null to 0 in lighting/lighting_source.dm

### PR DESCRIPTION
**Pull request by LetterJay**
Changes null values to 0. Seems to have fixed the runtime flooding, but I can't confirm without a large playerbase to test with.

### CODE REVIEW

**Comment by PJB3005** [comment]
The zeroes won't accomplish anything.
The nullcheck is in the wrong spot and won't do anything either.

So after actual months of this runtime throwing on /vg/ (and being surpressed by the error handler) I think I finally figured out why it could happen.

I didn't want to fix it like this, because I thought the problem lied somewhere else, but I was wrong so here goes:

nullcheck `S.source_turf` here: https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/code/modules/lighting/lighting_turf.dm#L49

**Comment by LetterJay** [comment]
Sorry, I'm gonna sound dumb asking this. But, you want me to place ```if(!S.source_turf)``` on line 49? I can't remember how to do a nullcheck and no one that's online can either.

**Comment by PJB3005** [comment]
Yes, exactly.

**Comment by LetterJay** [comment]
Alright, running it. I'm still unsure of what triggers this. The runtimes comes randomly.

**Comment by LetterJay** [comment]
Should I run this live with a ```return``` or ```continue```?

**Comment by PJB3005** [comment]
Continue.

**Comment by PJB3005** [comment]
Well then

**Comment by LetterJay** [comment]
Didn't mean to close that; I need sleep.

**Comment by LetterJay** [comment]
So I don't screw something up due to lack of sleep, I'm gonna let you look over if you want and make sure I didn't do something I wasn't supposed to in this PR.

**Comment by PJB3005** [comment]
Only change that should actually do anything is the nullcheck for `if (!S.source_turf)`, rest can't make a difference.

**Comment by LetterJay** [comment]
Yea, a few of these I don't actually remember doing. Anyway, merging. Updating, we'll see what happens from here.

**Comment by PJB3005** [comment]
Just chiming in, I found the source of the runtime proper, finally.

I'll have a fix up soon:tm:

**Comment by LetterJay** [comment]
The crash loop?

**Comment by PJB3005** [comment]
the `null.x` runtime

**Comment by LetterJay** [comment]
That's usually what floods right before the bad list runtime flood. It only locks up players. Observers and ghosts are unaffected

**Comment by PJB3005** [comment]
uh.

Weird.

**Comment by PJB3005** [comment]
https://github.com/d3athrow/vgstation13/pull/13291

**Pull request merged**
