### PR TITLE
chaplain nullrod nerf

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

nerfs the chaplain's variant of hypereut because it inherited the parry data of deswords.
also removes the 50% block.

## Why It's Good For The Game

maybe hypereut having the parry data of a weapon that costs somewhere about 12-16 tc isn't a good idea, especially if it's a roundstart nullrod. removes the innate blockchance that it had as well, because rng block is bad.

## Changelog
:cl:
balance: nerfed hypereut chaplain weapon.
balance: 50% rng blockchance -> 0%
balance: parry made much worse because it's an actual weapon and a roundstart one at that.
/:cl:

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
lmao did kevin not remove the 50% block chance

**Comment by Sishen1542** [comment]
still going through other nullrods but this seems fine™️ since hypereut gets extra damage compared to the rest of them

**Comment by Tupinambis** [comment]
I am once again asking you to please have more specific PR names so I don't just assume "Blanket nerf all null rod" from the title.

**Comment by Detective-Google** [comment]
I thought this was an actual balance change at first but then I realized it was just killing more OP citadel trash 👍

**Pull request merged**
