### PR TITLE
Medihound Tweaks and Sound Preference improvements

### PR DESCRIPTION
**Pull request by Poojawa**
:cl: Poojawa
refactor: improved vore sound responsiveness to preference choices.
balance: removed morphine from Medihound sleeper chemical list
fix: fixed preference setting being broken
refactor: Medihound sleepers are Initialized properly, and icons update correctly now on eject
/:cl:

replaces #7622

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
I still think there's a better way to handle fixing the vore audio pref than adding a debounce for pref checking, but eh, if it works, it works

**Comment by Poojawa** [comment]
This is the same way instrument prefs are handled, so

**Comment by deathride58** [comment]
Fix compiling

**Comment by Poojawa** [comment]
what even the fuck

**Review by deathride58 — DISMISSED** [review]
Remind me later and I'll optimize this with the info I gave you in the coderbus channel a while back

**Comment by Poojawa** [comment]
I don't think there's any way to optimize this in a way that works better.

like I said, it's instrument filter code, and works really well.

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
