### PR TITLE
arachnids officially goes on the list of code features that were made by fetish coders who don't do the basic check of "don't let them cocoon LITERALLY ANY ATOM"

### PR DESCRIPTION
**Pull request by silicons**
Really?

### CODE REVIEW

**Comment by MacaroniCritter** [comment]
salt pr!!!

**Comment by Tupinambis** [comment]
So I was told by the person who originally made the PR on Waspstation that they made fixes that I should port, but I stopped devving.

This among other things was probably fixed over there, would probably save you a headache.

**Comment by triplezeta** [comment]
based title

@Maldaris you are now officially a fetish coder

**Comment by Maldaris** [comment]
On one hand this is an entirely reasonable change that I probably should have thought of in the first place.

On the other hand I'm not going to port it out of spite, because, fun fact, originally coded Arachnids as my response to all the (horny) mothposting on Boomer. You might even consider them to be anti-Horny

**Comment by triplezeta** [comment]
lmaooo

**Comment by silicons** [comment]
ehh tbf atleast the species is fun

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
While you are at it, please also blacklist any effects from it aswell as giving a message visible to others when they begin wrapping something

**Comment by DeltaFire15** [comment]
This also has NO distance checks at all what the hell

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
