### PR TITLE
[READY] Energy Sabers - an elegant esword skin for a more civilized age

### LINKED ISSUE #13520: alt click more broke
related to #13440
alt click function with item alt skins (shotgun, revolvers, HoS armor, etc) doesn't work

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
- adds the Energy Sabre reskin for the energy sword (altclick the sabre)
- energy swords can be recolored via multitool on disarm intent, overrides rainbow mode, rainbow mode activated by every other intent
- reshuffles the items and weapons .dmi and adds a defib .dmi
- **fixes altclick reskins!!!**
- closes #13520
image
https://streamable.com/7k9oyt
CURRENT ISSUES:
- i should probably add the functionality to toy swords
## Why It's Good For The Game
i thought it'd look cool
## Changelog
:cl:
add: Energy sabre reskin for the energy sword - access via alt-click.
fix: Alt-click reskins are fixed.
tweak: Defibrillators and their many, many overlays were moved to another .dmi.
tweak: You can now change the color of an energy sword via multitool. Not deswords. Yet.
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
tagged wip because i dont know if i fucked up the reskin radial or if it was just a bug i can't reproduce

**Comment by YakumoChen** [comment]
@Hatterhat alt click reskins are broken as shit right now for everything

**Comment by YakumoChen** [comment]
#13520

**Comment by Hatterhat** [comment]
you hate to see it

**Pull request merged**
