### PR TITLE
Updating ID Icons

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Nothing to see, just better ID icons from /tg/. Also, BS emag now has it's own blue sprite!

## Why It's Good For The Game

This sprites are much better than those old ones. 

## Changelog
:cl:
add: New ID icons
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
sad

**Comment by Detective-Google** [comment]
God bless I've been putting off porting these because lazy

**Comment by ShadeAware** [comment]
Oh God, these are ugly as sin.

**Comment by MrJWhit** [comment]
The PR has been up for 3 days, these are standard /tg/ sprites, if you had a problem previously, you should have said something before.

**Pull request merged**
