### PR TITLE
alternate buff to stimpak buff pr #11737

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
reverts #11737 in favor of making stimpaks cost 3tc instead of 5tc. this is already a mistake but it wouldn't get merged if it was a pure revert PR so we get an alternate buff instead.

if maintainers are uncomfortable with scarp users buying stimpack reliably i can up the cost to 4

## Why It's Good For The Game
5tc->3tc means stimpak can be bought on traitor with the 2 melee rampage tools without discounts, making it a bit better as a support item. since scarp is now weak to stamina as well as burns this will alleviate half of scarp's issues for a time, and desword... probably won't be seen with this anyways because if you're running desword you're gonna grab glue because any stamdamage you take is gonna come from knockdowns, but maybe if you get a discount you'll pick stimpak too.

players that like to think outside the box may find, with some more prep time, methods to split up the dosage for a bit of prolonged use.

also we didn't need to make the adrenals implant even more irrelevant by making a 5-use version of it that cost 5tc 

## Changelog
:cl:
balance: stimpaks are once again pre-fight buffs, only having one use for 5 minutes of rampaging that doesn't pierce hardsuits. as a tradeoff, they now cost less and can be bought by traitors running scarp/desword as a support consumable.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
What an odd way to balance a healing item

**Comment by ghost** [comment]
that statement means literally nothing

**Comment by Trilbyspaceclone** [comment]
I cant think of any other healing cocktail that injects all at once, epi pends are 13u of nice stuff but its once time use and barely heals anything really. Well the implant injects around 10~u regent healing + stim that also heal.
Stimpacks are a healing item, making them all or nothing is kinda bad

**Comment by necromanceranne** [comment]
Survival medipen.

**Comment by kappa-sama** [comment]
if maintainers have concerns with the balance of scarp users buying stimpack i can raise the price to 4

**Comment by ghost** [comment]
for anyone interested but not interested enough to codedive, here are the stats on stimulants:

`/datum/reagent/medicine/stimulants/on_mob_life(mob/living/carbon/M)
	if(M.health < 50 && M.health > 0)
		M.adjustOxyLoss(-1*REM, FALSE)
		M.adjustToxLoss(-1*REM, FALSE)
		M.adjustBruteLoss(-1*REM, FALSE)
		M.adjustFireLoss(-1*REM, FALSE)
	M.AdjustAllImmobility(-60, FALSE)
	M.AdjustUnconscious(-60, FALSE)
	M.adjustStaminaLoss(-20*REM, FALSE)`

`/datum/reagent/medicine/stimulants/on_mob_metabolize(mob/living/L)
	..()
	L.add_movespeed_modifier(type, update=TRUE, priority=100, multiplicative_slowdown=-0.5, blacklisted_movetypes=(FLYING|FLOATING))
	ADD_TRAIT(L, TRAIT_TASED_RESISTANCE, type)`

minor heal while in crit, 20 stam regen per tick, basically immune to stuns and ko's.
while in your system you're immune to the part of tasers that matters (noone uses them though) and you gain superspeed.


overdoses at 60u so you can only use one stimpak, but the overdose is pretty minor all things considered

**Comment by Trilbyspaceclone** [comment]
```
/datum/reagent/medicine/stimulants/on_mob_life(mob/living/carbon/M)
	if(M.health < 50 && M.health > 0)
		M.adjustOxyLoss(-1*REM, FALSE)
		M.adjustToxLoss(-1*REM, FALSE)
		M.adjustBruteLoss(-1*REM, FALSE)
		M.adjustFireLoss(-1*REM, FALSE)
	M.AdjustAllImmobility(-60, FALSE)
	M.AdjustUnconscious(-60, FALSE)
	M.adjustStaminaLoss(-20*REM, FALSE)
	..()
. = 1
```
it heals from (rounding here) 49.99 - > 00.01 hp.
It does NOT heal in crit

**Comment by ghost** [comment]
> it heals from (rounding here) 49.99 - > 00.01 hp.
> It does NOT heal in crit

you crit if you have less than 100 hp left

**Comment by necromanceranne** [comment]
I think Lilly is right it quite literally won't heal at 0 or less given the ranges. If it would heal in crit it would be checking for the crit threshold.

**Comment by silicons** [comment]
i don't even know what to say here

**Comment by silicons** [comment]
i mean in theory it's 5 minutes but why do i feel like this is going to be one of those "wipe the server in 5 minutes" things?

**Comment by ghost** [comment]
maybe. Feel free to change it to 4 if you want to, since that means you can only buy it with desword without discounts

**Comment by Ghommie** [comment]
Whops, I didn't mean to. It's too cheap.

**Comment by ghost** [comment]
> Whops, I didn't mean to. It's too cheap.

f
just pull a kevinz and merge directly to master like a psychopath

**Pull request merged**
