### PR TITLE
[s] killer tomato logging

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
Can be speedmerged

**Comment by nik707** [comment]
Lmao kevinz pls.

**Comment by MimicFaux** [comment]
Greentide stationwide

**Comment by deathride58** [comment]
fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it
reeeeeeeeeeee

**Review by nik707 — APPROVED** [review]

**Pull request merged**
