### PR TITLE
Revert "[MIRROR] Cell blueprints now use the /empty variants"

### PR DESCRIPTION
**Pull request by jakeramsay007**
Reverts Citadel-Station-13/Citadel-Station-13#5390

Literally the dumbest change to RnD they've made in a long time. Here to be voted on.

### CODE REVIEW

**Comment by ZeroNetAlpha** [comment]
Honestly, from my limited understanding, batteries are manufactured in a charged state irl. Even rechargeable batteries are. They however say to recharge before first use because some of the energy will fade while they are stored and waiting to be sold. I vote a tweak to give batteries random charges on creation.

**Review by deathride58 — DISMISSED** [review]
If you're gonna make a kneejerk revert, at least modularize it.

**Comment by ZeroNetAlpha** [comment]
That's basically putting the "pre tg touch" code in modular_citadel, right?

**Review by deathride58 — COMMENTED** [review]
Code is good, but let's give it some time to see if the complaints are still there before this gets merged.

I'm recommending leaving this PR up for at least a week to see if it should be closed or merged.

**Comment by AmatsuDF** [comment]
While a bit kneejerkish, it is needed until a better solution is either developed upstream or here.

**Comment by improvedname** [comment]
auctally this is the solution, this is mainly a salt PR from science as they can print batteries by a instant put them in inducers and keep their department powered while engine never got set up

**Comment by jakeramsay007** [comment]
This is not the solution, whatsoever. A better solution would have been making it so the protolathes draw power directly from the powernet with a cable beneath them to print charged cells, or change the cell chargers to be upgradable and at least three times faster. Taking ten to fifteen minutes to charge a single bluespace cell is ridiculous.

**Comment by improvedname** [comment]
this is a fine solution

**Comment by deathride58** [comment]
Can be closed when tgstation/tgstation#35517 gets mirrored and merged, as it takes care of the most common complaint about the PR that this PR is trying to revert.

**Comment by DaxDupont** [comment]
Oh god I have been pinged from the den of degeneracy

**Review by lightcat — APPROVED** [review]

**Comment by Poojawa** [comment]
resolved with #5442

**Pull request closed without merging**
