### PR TITLE
Fixes the lack of immersion

### PR DESCRIPTION
**Pull request by GuppyLaxx**
I've taken a small amount of my time to fix the lack of immersion regarding movement, hope you great roleplayers enjoy!

### CODE REVIEW

**Comment by deathride58** [comment]
Cease

**Comment by Brokenchair69** [comment]
I like it, actually adds to the immersion. I'm tired of being a dumb chess piece.

**Comment by deathride58** [comment]
The fuckin server box died when I tried to testmerge this

10/10

**Comment by RogueSteampunker** [comment]
I am... surprIsingly okay with this

**Comment by GuppyLaxx** [comment]
dont leave things in the back of ur prs

**Pull request closed without merging**
