### PR TITLE
Adds electro-stimulation integrated circuit part

### PR DESCRIPTION
**Pull request by izzyinbox**
:cl:
add: Added an integrated circuit part that interacts with the arousal system
/:cl:

because we totally need more lewd mechanics for citadel
:zap: :zap: :zap: :zap: :zap:

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆 🍆

**Comment by Hatterhat** [comment]
this PR is illegal

**Comment by Wilchenx** [comment]
this should be a nanite instead

**Comment by Wilchenx** [comment]
this should be a electric chair equivalent instead

**Review by deathride58 — APPROVED** [review]

**Comment by LetterN** [comment]
circuits were a mistake
>spam these thing around with bots that follows a person

**Comment by GuyonBroadway** [comment]
Hello from hippiestation.

image

That is all.

**Pull request merged**
