### PR TITLE
Add sign language.

### PR DESCRIPTION
**Pull request by TyrianTyrell**
## About The Pull Request

This is a minor change so I can get a feel for how these work. Right now it just adds sign language- which you can talk in even if you're mute, but can't talk over the radio with. I plan on making it so that if your hands are full, you can't use it, too.

## Why It's Good For The Game

Right now, mute characters don't have much in the way of communication. You have to use paper to do so or the PDA. I think adding sign language will add some interesting roleplay scenarios.

## Changelog
:cl:
add: added a default signed language to the game
imageadd: added temporary sign language icon
code: altered talking and radios to make them accommodate signed languages.
/:cl:

### CODE REVIEW

**Comment by TyrianTyrell** [comment]
Wait, hold on, is it supposed to do that? I swear I modified the "languages" icon.

**Comment by TyrianTyrell** [comment]
Okay, I missed something, hold on.

**Comment by SandPoot** [comment]
Remember to check the file on the dme

**Comment by SandPoot** [comment]
Also i feel like you can do the checks using:
`if(M.can_speak_vocal())`

**Comment by TyrianTyrell** [comment]
The checks for the radios?

**Comment by SandPoot** [comment]
Yes! if the person can't speak, the proc will return false!

**Comment by TyrianTyrell** [comment]
I don't think that'll work- It'll allow people who CAN speak to talk in the signed language over the radio.

**Comment by SandPoot** [comment]
It relies on the check you added, you just gotta make it work properly

**Comment by TyrianTyrell** [comment]
Yeah, the dme wasn't properly edited, I think I fixed it?

**Pull request closed without merging**
