### PR TITLE
Nukes the ability to cuff shoes from orbit.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removes the ability to cuff orange shoes from the game. (You can no longer apply cuffs to orange shoes to force slowdown on prisoners)

## Why It's Good For The Game

It effectively hard counters all implants and secret items that a traitor purchases rendering them useless. It is also just a bad faith option for security in general, as a permabrig prisoner without the right gear can't escape anyway, and all bucklecuffing their shoes does it make them miserable through the incredibly harsh movement speed penalty. They can't be removed by the wearer under any circumstance as well.

Shoecuffing is honestly just used to be a dick towards antags. It needs to go.

## Changelog
:cl: Tupinambis
del: You can no longer use handcuffs on orange shoes or create buckled shoes.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
or just make it so you can remove the shoecuffs but ok

**Review by deathride58 — CHANGES_REQUESTED** [review]
A much better way to handle this would be to make it possible to remove prison shoes.

**Comment by Tupinambis** [comment]
I have not a clue how to go about doing that. The code for cuffing is pretty obtuse.

**Comment by Trilbyspaceclone** [comment]
Anything that gives "No slowdown" will make you run at normal speeds.
Also, dont you have to like... Get arrested, placed in these shoes? So at that point your likely in perma or something.

**Comment by keronshb** [comment]
> 
> 
> Anything that gives "No slowdown" will make you run at normal speeds.
> Also, dont you have to like... Get arrested, placed in these shoes? So at that point your likely in perma or something.

I think the issue is that you can't even remove them unless someone else does it for you.  I was shoecuffed once before when I wasn't even an antag (it was a misunderstanding) and it's a total dick move since you move slower than a snails pace.

Back on SS13 circa 2005 we shoecuffed souly because we could and looking back at it, it's kind of a dick move when you have all these other means of restraining/stunning/etc.

**Comment by chefferz** [comment]
Shoe cuffs are there to prevent permabrig prisoners who have proven themselves wanting to escape, to prevent escape.

**Review by silicons — CHANGES_REQUESTED** [review]
bhijn's suggestion

**Comment by silicons** [comment]
oh and make implants remove them if you want

**Comment by chefferz** [comment]
> 
> 
> oh and make implants remove them if you want

Better idea.

**Comment by Detective-Google** [comment]
improve don't remove 🤡

**Comment by Ghommie** [comment]
Deathride would dunk me if I merged this.

**Pull request closed without merging**
