### PR TITLE
Fixes the "gear" harness.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Fixing some bad issues due digitigrades and alt-click to wear casually stuff.

## Why It's Good For The Game
Fixing issues.

## Changelog
:cl:
fix: fixing some related onmob sprites issues with the above accessory.
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
I mean, the entire point of the gear harness is so you can look nude, without actually exposing yourself/fucking with options. It was renamed to gear harness to avoid stupid controversy with it's name, as exposing yourself was still arrestable.

**Comment by silicons** [comment]
what owai said

**Comment by Ghommie** [comment]
Yes, I'll be pondering wheter I should turn the "nudity" pass into a slighty less senseless pseudo-invisible bodystocking under or just ditch it altogether because it's only a geam, s don't hastily close it yet.

**Comment by Linzolle** [comment]
I just want it to not have the stupid JSUIT thing floating next to you

**Comment by Ghommie** [comment]
Ah, screw it, this is the sort of bad feature I'd be happy didn't exist altogether.

**Review by silicons — APPROVED** [review]

**Pull request merged**
