### PR TITLE
Nukes away bad NSFW autosurgeons.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
I thought about the these autosurgeons for a while after removing them from cargo and came to the conclusion that, in the current state, these are just plain bad maintenance loot filler trash and don't offer any interesting degree of customization, unlike the character setup menu. (still, I don't think that'd suffice to keep them around)

## Why It's Good For The Game
Removing some bad maintanance loot trash.

## Changelog
:cl:
del: Removed some bad privates autosurgeons.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Why tho. These are mainly for flavor and adminbus, and allows a spaceman to regain their genitals after losing them somehow, or experiment with genitals they haven't chosen in the character customization menu. It's alright to have maintenance loot that serves no purpose outside of RP.

**Comment by ShadeAware** [comment]
Easy compromise:
-Loadable autosurgeons
-Growing genitals in limb growing vats

**Comment by Trilbyspaceclone** [comment]
They sell for 150 cr each. By the by

**Comment by IronEleven** [comment]
Testicle autosurgeons are useful since the dick pills don't give you balls unless you OD but the penis ones are just broken trash.

**Comment by Owai-Seek** [comment]
I'll have you know that these are a legitimate way for lizards to scrounge for food if they have a screwdriver.  /s

**Comment by Ghommie** [comment]
I... already know that, Owai... but... :nauseated_face: 

Also both relieved and disappointed that you goons act up like you actually make use of this trash.

**Pull request closed without merging**
