### PR TITLE
Blue air alarms

### PR DESCRIPTION
**Pull request by Poojawa**
:cl: Poojawa
tweak: Air alarm All clear color changed from green to blue
/:cl:

Green is not a creative color, and admittedly looks like shit for most things.

so we blue now

### CODE REVIEW

**Comment by Poojawa** [comment]
also the stray pixel is fixed, don't worry.

**Comment by Poojawa** [comment]
...why the fuck did those files get put in this..

**Comment by CameronWoof** [comment]
My beef with this is that green is the "all clear" alert color and blue is the "something is wrong" alert color for the station. This seems inconsistent because of it.

**Comment by Poojawa** [comment]
No it isn't? 

Blue is usually a neutral color. Being normal mood is a blue icon. Blue is also easier to see in light and dark situations

**Comment by CameronWoof** [comment]
I meant more for "Green Alert" and "Blue Alert", where green is "all clear" and Blue is "something is wrong."

Green APCS are fully charged and operating, while blue ones are hacked/charging. And... green is the "good mood" and blue is the "something is wrong/could be better" mood. This is inconsistent.

**Comment by Poojawa** [comment]
You're looking into this a bit much, tbh

**Comment by CameronWoof** [comment]
Ok.

**Comment by deathride58** [comment]
I still think the text's glow is way too bright, but blue honestly looks a lot nicer

Also this gives me the weird idea of letting atmos techs set completely custom colors for the air alarms for each individual state, but that's out of this PR's scope

**Comment by nik707** [comment]
> I still think the text's glow is way too bright, but blue honestly looks a lot nicer
> 
> Also this gives me the weird idea of letting atmos techs set completely custom colors for the air alarms for each individual state, but that's out of this PR's scope

pls

**Comment by Poojawa** [comment]
the text glow is bright in the light, but as you can see is quite clear in the dark. S'the trade off. Lights always look awful when washed out with a ton of ambiance

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
