### PR TITLE
fixes pacifist zombies

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Fixes Infectious Zombies not being able to attack living beings if the character has the "Pacifist" quirk. Relevant Issue #13650
Also adds a way to handle blacklisted quirks for each species, saving the ones that got removed to be restored when you transform from one species to the other. In case a similar bug ever occurs again.
Any optimization and feedback is appreciated this is my first time doing this.

## Why It's Good For The Game
Mean zombies NEED to hurt to be fun

## Changelog
:cl:
fix: fixed infectious zombies not being able to attack if host was pacifist
add: adds a way for species to have blacklisted quirks, the removal, and restoration of said quirks upon species changes
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
i hope this is not "hacky code"
Object Oriented is one thing. Trying to understand DM is a whole another can of worms

**Comment by timothyteakettle** [comment]
the ideal way to solve this would be to not check on every attack if they're not a zombie, but instead, just remove their pacifism when they become a zombie

**Comment by ghost** [comment]
hm... that also means having to restore that when they are cured, if they get cured... time to tackle that

**Comment by ghost** [comment]
got a small question though, "ROUNDSTART_TRAIT" source has comment saying "cannot be removed without admin intervention"
what does that mean

**Pull request merged**
