### PR TITLE
Makes the titlescreen properly positioned for widescreen again

### PR DESCRIPTION
**Pull request by deathride58**
:cl: deathride58
fix: The title screen is now properly positioned to display widescreen titlescreens again.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
:thinking:

**Comment by LetterJay** [comment]
Spooky

**Comment by Poojawa** [comment]
This should be made into a cit_maps backup

**Review by Poojawa — CHANGES_REQUESTED** [review]
This overall should be backed up, for easy re-applying if need be.

Mapping on our end should always be a 1:1 update with the citadel backups to keep things easily portable if massive changes ensue.

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
Whew, it's editing it's own comment again. You can delete the rest

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Poojawa** [comment]
so report mapdiffbot for multiple counts of spam kk.

♥

**Review by Poojawa — APPROVED** [review]

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Pull request merged**
