### PR TITLE
Adds ring jewelry

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Adds three rings to the game. Gold, Silver, and Diamond rings. They're hand slot items.
Rings can be equipped from Loadout, either directly on your hand or in a fancy box. Diamond will cost you extra.
Two new crates were added to cargo, one for a set of jewelry (comes with the gold and silver rings and the gold necklace), one expensive crate for a diamond ring. 

## Why It's Good For The Game

Small decoration. This PR is kind of a token effort to what could be done with rings (they're just glove reskins as it is), but I'm sure someone who can code better can refactor it more if they want.
More importantly the diamond ring is useful for marriage proposals, which occasionally happen. Valentines Day is coming up, you know...

## Changelog
:cl: Yakumo Chen
add: Rings for your fingers!
add: New cargo crates and loadout options to bling your rings!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Betting 2 antag tokens they'll propose to fermis on valentines day using this PR lol

**Comment by Linzolle** [comment]
make sure to add ring.dm to tgstation.dme, not compiling becaues you didn't.

**Comment by YakumoChen** [comment]
thanks Linzolle. never would have figured it out

**Comment by YakumoChen** [comment]
travis is still having a shitfit over line endings and I can't figure it out

**Comment by Ghommie** [comment]
Those sprites are a bit too tiny.

**Comment by YakumoChen** [comment]
spriting isn't exactly my forte
neither is coding but I don't claim to be good at it either

**Comment by ShadeAware** [comment]
Maybe some on-mob sprites would be nice (even if its just a pixel of color because rings are _tiny_).

**Comment by ghost** [comment]
on-mob is good idea, i suggest making it twinkle so it's noticeable

**Comment by YakumoChen** [comment]
I barely cobbled together what I have, inhands is probably a lot more complicated to do for a single, barely visible pixel on a spaceman.

**Review by silicons — APPROVED** [review]

**Pull request merged**
