### PR TITLE
table SLAM

### PR DESCRIPTION
**Pull request by LetterJay**
make a very loud point.

still not ready. need to add a sleep on it so it's not spammed to shit and double check damage works when slamming glass tables.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
don't use sleep()

**Comment by LetterJay** [comment]
which is used, then?

**Comment by TalkingCactus** [comment]
use a timer with `addtimer()` or something

(pretty sure that's the proc, might be a little different)

**Comment by ghost** [comment]
ye, just look up add_timer or whatever it is in the code to see how it's used, make a proc with everything that needs to be run after the delay and set that as the proc for the timer to run after

**Comment by LetterJay** [comment]
Fucked up something, closing.

**Pull request closed without merging**
