### PR TITLE
[READY] More Slime core deconstruction, now with Cross bread slime cores! (Best Grammar! 100% ready for merging PDM!!)

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
**Work in progress, want some feed back on balance on this!**

[Changelogs]
Adds in Red/Senpie cores to be deconned after thinking "Meh why not?"
Adds in Gray, Organ, Metal, Purple, Yellow, Blue, Dark Purple, Silver, Pyrite and Cerulean Crossbreaded slime cores, for deconstructed into raww sci points. Blorp!

[why]
To help sci get points!
_**Need feed back on points that should be given to slime cores and alternatives!**_
This is also to help with any first looks and such people mite have!

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Proof im not webedit only 
https://cdn.discordapp.com/attachments/455477249299185704/499049159555284992/unknown.png
https://cdn.discordapp.com/attachments/455477249299185704/499050792154824704/unknown.png
Only test grey burning core*

**Comment by Trilbyspaceclone** [comment]
Proof that im not wededits only
https://cdn.discordapp.com/attachments/499347891161137172/499348348222832640/unknown.png
https://cdn.discordapp.com/attachments/499347891161137172/499348637667688448/unknown.png
https://cdn.discordapp.com/attachments/499347891161137172/499348752570515466/unknown.png
https://cdn.discordapp.com/attachments/499347891161137172/499349073212735499/unknown.png
https://cdn.discordapp.com/attachments/499347891161137172/499349138790416385/unknown.png
https://cdn.discordapp.com/attachments/499347891161137172/499349277114368020/unknown.png
Only tested these cores*

**Comment by Trilbyspaceclone** [comment]
Just realized that slime crossbreeding cores are still in WIP...

**Comment by nik707** [comment]
What's the status on this?

**Comment by Trilbyspaceclone** [comment]
Waiting on if Deep Blues will be merg'ed to add them in

**Review by nik707 — APPROVED** [review]
yeah ok

**Pull request merged**
