### PR TITLE
Ports #52320, Stun baton sprites by Sirich96, and new stunsword sprites

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Ports over https://github.com/tgstation/tgstation/pull/52320 - sprites by Sirich96

And also some new sprites for the Stunsword based on the same palette.

Screenshot 2020-07-28 01 45 06

## Why It's Good For The Game

Stun batonnies.

## Changelog
:cl: NecromancerAnne, Sirich96
add: Stunbaton sprites by Sirich96.
add: New sprites for the stunsword.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Nooooooooo =(

**Comment by necromanceranne** [comment]
Is there anything specifically wrong, or...

**Comment by rossark** [comment]
I sense strong dominant energy coming from those sprites.

**Comment by lolman360** [comment]
the old sprites have soul but the new ones are just... slightly improved old ones so i think it's okay

not like toolboxes or lockers or the arguably worst offender, cit medkits

**Comment by necromanceranne** [comment]
Fuck soul

**Pull request merged**
