### PR TITLE
Makes internal tanks printable at the engineering lathe

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
This PR makes empty variants of several internal tanks printable. They are researched with a node just after engineering. Printable tanks include the large oxygen tank, the large plasma tank, emergency oxygen tanks, the engineering emergency oxygen tank, and the plasmaman belt tank. 

## Why It's Good For The Game
With the introduction of the economy I've been wanting to toy around with selling extra internal tanks to the crew. Being able to print more tanks would enable gimmicks with this. It would also make it far easier to make plasma tanks for the purpose of building additional radiation collectors for the SM.

## Changelog
:cl:
add: Internal tanks are now printable at the engineering lathe.
/:cl:

### CODE REVIEW

**Comment by IronEleven** [comment]
This feels like it should be either basic tools or an autolathe design, not another 2500 points for R&D to spend.

**Comment by silicons** [comment]
what the scientist said

**Comment by shellspeed1** [comment]
Tanks moved to industrial tech node. They should be researched pretty early unless science is horribly incompetent.

**Review by Ghommie — APPROVED** [review]
Fine I guess.

**Pull request merged**
