### PR TITLE
Drake borgs

### PR DESCRIPTION
**Pull request by BlackMajor**
This PR does what it says on the tin.
Ported from skyrat, https://github.com/Skyrat-SS13/Skyrat13/pull/2863

Adds an aux skin for borgs that are in the shape of drakes.
Also adds two plushies of the med drake and sec drake.
Original sprites comissioned from deviantart.com/mizartz.
Skyrat's PR didn't have vore sprites, so I recruited @ThighHighs to draw the vore sprites for them.

### CODE REVIEW

**Comment by Strazyplus** [comment]
You scrubbed all the credit out of the PR DMI and DM files.


plus not even TM'd or merged on skyrat yet Reee.. :(

**Comment by BlackMajor** [comment]
Yeah. Who bloats their code with credit everywhere when you can just credit it in the PR adding it.
That's just unecessary.

**Comment by Strazyplus** [comment]
> Yeah. Who bloats their code with credit everywhere when you can just credit it in the PR adding it.
> That's just unecessary.

image

not everywhere and honestly removing the skyrat part is absolutely fine, they wanted //skyrat change.

Plus you took away my only bonus I gave myself which was a plushie in my loadout, I thought it would be fine to have that since I provided the community such great new borg to play with, damn. did I hurt you?
but it is up to the server to accept me having plushies or not since its donator code.


Regardless I hope everyone enjoys the drakeborgs I had fun working with the artist to bring them to reality. after a short break, I might give them few more additions when my wallet recovers.

**Comment by ShadeAware** [comment]
Yeah atleast let this get merged on Skyrat before you try and steal the fucking PR and scrub away all credit like it was your own idea.

**Comment by BlackMajor** [comment]
> Yeah atleast let this get merged on Skyrat before you try and steal the fucking PR and scrub away all credit like it was your own idea.

Nah, think I'll pass on that one fam.

**Comment by LetterJay** [comment]
> Yeah atleast let this get merged on Skyrat before you try and steal the fucking PR and scrub away all credit like it was your own idea.

Using that argument is fairly poor when you have 100+ mirror PRs.

**Comment by Strazyplus** [comment]
If I had known credit was going to be scrubbed within the files, I would of PR'd it myself here sooner to prevent that.

**Comment by MrJWhit** [comment]
We don't credit stuff in-code already, and you were free to PR it here, but it looks like there were adjustments to the dmi's themselves for vore bellies.

**Comment by Strazyplus** [comment]
Would like the Drakeborg.dmi to be used instead of combined with widerobot, With the credit intact within the dmi.

**Comment by nik707** [comment]
open source is open source, i can't actually imagine being this upset about a single comment in code

**Comment by Strazyplus** [comment]
I don't mind not getting plushies in loadout (by via donator code) in fact if this was properly my PR I would ask/consider if making plushies a loadout option for all be okay, I have not done that previously because I thought there would be resistance but come to think of it, who would really say no to that?

I am not very upset about comments in code being removed, would be nice to have but honestly, I do agree it is a little unecessary. 

The drakeborg sprites were all combined in one under Drakeborg.dmi , it separates from the widerobots which often get fucked with for some reason. if you compare citadel & skyrat widerobot.dmi you will notice that citadels sprites are damaged, animations missing for almost all of the valeborg death animations. and you will find the valeengineer looking really sexy with a subtle recolor that I did.

in addition to preventing sprites from getting damaged by edits, the drakeborg.dmi comes with a unused sprite which provides a small card of credit.

image
ca2rd

I am not asking for this PR to be removed, the PR provides credit but the code and the sprite files been scrubbed of credit and it is disrespectful. I would like the sprites separated from widerobot as intended with the credit sprite within the DMI for these reasons above, the code comments can remain out.

**Comment by frontline03** [comment]
Imagine being so scummy that you have to remove credit from the code.

**Comment by ThighHighs** [comment]
I have nothing important to add here other then the fact that I made the vore sprites.

**Comment by Strazyplus** [comment]
> I have nothing important to add here other then the fact that I made the vore sprites.

Good job on them, personally I think it's too chunky but much better to have something than nothing. thumbs up you did good!

**Comment by deathride58** [comment]
After reading the artist's TOS, there is a very real possibility that this might not be AGPL 3 compatible. DNM until license situation is confirmed.

**Comment by Ludox235** [comment]
Who cares if deathride put on DNM when people test merge it anyways 🥴

**Comment by ThighHighs** [comment]
Sorry about posting this here (I don't know your discord) But Strazyplus why did you make the sprited 62x32 for your drakeborg? It really threw me off as I was working on the sleeper sprites >w>

**Comment by Detective-Google** [comment]
> Who cares if deathride put on DNM when people test merge it anyways 🥴

**Comment by jjpark-kb** [comment]
I dont see what issue there is with adding back the credits to the dmi? I bet I can find tons of "credits" in code as well.
EDIT:
image
Yep, first page of searching for credit. Granted, its sound and stuff.
image
Oops, here is some credit for an image and other stuff.
> We don't credit stuff in-code already, and you were free to PR it here, but it looks like there were adjustments to the dmi's themselves for vore bellies.

enough said.

**Comment by jjpark-kb** [comment]
> > Yeah atleast let this get merged on Skyrat before you try and steal the fucking PR and scrub away all credit like it was your own idea.
> 
> Using that argument is fairly poor when you have 100+ mirror PRs.

that isnt relevant at all. skyrats mirror bot links to the original pr. Blackmajor linked to the original pr, which is good.
He removed the credits though to the artist, which is the issue.

**Comment by Ludox235** [comment]
Honestly just leave the fucking credit holy shit it's litterally 1 line blackmajor who the fuck cares.
If someone had put a fucking ASCII block like those people who do cracks of games ok but here it's 1 fucking line.
Great sprites by the way.

**Comment by BobJoga** [comment]
> Yeah. Who bloats their code with credit everywhere when you can just credit it in the PR adding it.
> That's just unecessary.

You didn't credit anyone in any manner. You did not credit in the code, nor in the changelogs.

**Comment by ShadeAware** [comment]
This is pure scum. You should be ashamed of yourself @BlackMajor

**Comment by ShadeAware** [comment]
Also @deathride58 , to the average player with the way Blackmajor did this PR, it seems to really suggest me **made** this and all of the content in it, barring the sprites. This is, of course, not true. And its very blatantly him attempting to steal a PR from downstream and pass it off as his own.

**Comment by Draganfrukts** [comment]
Circus music 10 hour loop for this comment section.
Open source or not, you shouldn't delete credits.

**Comment by BlackMajor** [comment]
Hey kids what's going on in-    bloody hell y'all get up to some shenanigans while I'm asleep.

I aint gonna argue matters in a github PR though that's kinda a small brained move, I leave my discord open at all times for a reason if like, you wanted to actually talk over yer concerns instead of peanut posting.

Anywho, Bhijn said some shebang about what the artists terms are on their use so hey whatev', I'll wait for them to get back to me on their findings there and adjust accordingly.
Unless the artist doesn't care, then I won't, of course.

**Comment by BobJoga** [comment]
> Hey kids what's going on in- bloody hell y'all get up to some shenanigans while I'm asleep.
> 
> I aint gonna argue matters in a github PR though that's kinda a small brained move, I leave my discord open at all times for a reason if like, you wanted to actually talk over yer concerns instead of peanut posting.
> 
> Anywho, Bhijn said some shebang about what the artists terms are on their use so hey whatev', I'll wait for them to get back to me on their findings there and adjust accordingly.
> Unless the artist doesn't care, then I won't, of course.

Yeah fuck off. Credit your shit proper, put it at the very least in the fucking changelog.

**Comment by Detective-Google** [comment]
you're meant to put the author of the sprites after the first CL block, that's how it applies credit to the changelog.

i.e.
🆑 Navier
add: drakeborgs
/🆑

**Comment by Detective-Google** [comment]
also this is a nitpick but why is the branch called spaceruins lol

**Comment by Tupinambis** [comment]
So, I don't give a shit about the drama. I just wanted to say I think the drakeborg sprites do not fit in with the theme of ss13 at all, do not look in any way mechanical, and I don't love the way the sprites are shaped in general. I didn't like valeborgs and these are just worse. The animated idle sprite is also out of place.

**Comment by MalricB** [comment]
wack

**Comment by KeRSedChaplain** [comment]
Hot take I agree with tup, the sprites look incredibly cartoonish to me because of the _immensely noticable_ motion blur of the legs lmao

**Comment by Akrilla** [comment]
I'm a maintainer over at Skyrat, also the person that started the current feature freeze we have going on over there. When it was announced Navier approached me to say they were making this PR, and wasn't the happiest about needing to wait for a merge after spending all the effort they did.

Before that PR was even merged, this PR pops up, removing credit from the developer that spent the time doing the port. Regardless of intent, please understand that this comes across as at best disrepectful, and perhaps even petty. Unsure why this is a hill that has been decided to die on, and why 

> I aint gonna argue matters in a github PR though that's kinda a small brained move

PRs are quite literally here for PR discussion. I can't obviously do anything to force your hand, but it feels much better to allow https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12739 through instead, with full credit being given to the developer.

**Comment by MrJWhit** [comment]
I'll give you a hint: anything that remotely belongs to skyrat, brought up to citadel from skyrat, immediately causes issues on every level, even if it follows through the same exact process that skyrat uses with their mirror bot.

Credit isn't something that has been a major focus for... really anything that we've done so far, and neither has skyrat. When I reworked all of the atmos maps, I didn't put a comment saying I did it and look at me. I copied it from another codebase, and skyrat copied it from me, great I hope everyone enjoys it, it's really nice. We didn't have 5+ people flying in **demanding** that my name be plastered everything.

**Comment by CameronWoof** [comment]
The lack of credit given to contributors here is atrocious. I see no accreditation to your parents, without whom I feel fairly certain you would _not_ have been able to make this PR, and that's saying nothing for your grandparents and so on back to time immemorial, who should all have been credited in code comments throughout the PR.

I think the most blatant lack here is any credit given to The Lord Our God, who I daresay makes _all_ things possible, not least of which is PRs to this very github. Shame on you, for attempting to insinuate that so few deserve credit in a PR literally billions of years in the making (thank-you, Big Bang). Just atrocious.

**Comment by Akrilla** [comment]
And yet this doesn't change the fact that a removal of credit feels incredibly off, and unneeded 😂 People defending that the guy can't have his name in the changelog/comment is odd. This isn't even fully about lack of credit even, it's about quite literally *removing* what credit was there before.

**Comment by MrJWhit** [comment]
This isn't a copy and paste job, it's reworking what was there in just the dmi file into something for citadel.

**Comment by Strazyplus** [comment]
the code in these PRs for drakeborgs just links the sprites so the game engine can use them properly. Comments are for the artist whom did all the real work.

Why is the thing I helped (by paying) make to bring something myself and others wanted in spacestation13 causing people to be absolutely disrespectful just because I wanted the artist's credit to be left intact?

**Comment by Detective-Google** [comment]
firstly, @ShadeAware @BobJoga being salty and throwing insults is not going to get anything done and is being silly.

secondly, the fact it was brought here, and a feature freeze at skyrat is irrelevant to citadel

ditching the numbering scheme; but I'd really prefer if skyrat players didn't come out of the woodwork on any PR remotely _similar_ to a skyrat PR and call it theft when that server literally has a mirrorbot that 'steals' every PR made here. At the end of the day open source is open source and complaining about ports is childish.

that out of the way, I don't think these sprites look good in game, I find them incredibly unsettling. I don't think they encourage a desired behavior, and I don't think that all this drama was necessary when you could have just added the comment back into the code and nobody would care.

another thing I find particularly bad about this PR is that it adds to modular cit which we are trying to _reduce_ and eventually eliminate.

unfortunately nothing sensible will be done regarding this PR because both everyone decided to chimp out instead of actually discussing things.



> I aint gonna argue matters in a github PR though that's kinda a small brained move, I leave my discord open at all times for a reason if like, you wanted to actually talk over yer concerns instead of peanut posting.

🤡  the PRs have comments exactly for issues like this that way issues and developments are tracked.

**Comment by silicons** [comment]
cameron's pretty funny

anyways we're moving over to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12739 since i see no reason to not let navier make the final pull request.

**Comment by BlackMajor** [comment]
Closing this in favour of https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12739 , obviously.
No sense not letting the original auth make the port.

**Pull request closed without merging**
