### PR TITLE
PDA Uplinks Can Now Siphon Pens

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title
image

## Why It's Good For The Game
if i beat the shit out of a guy for his uplink and i steal it i want to be able to steal his funny antagbucks god damn it
## Changelog
:cl:
fix: PDA uplinks can now steal from pens. Properly. Just make sure to have a pen in your PDA, first.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
waéit what you can steal antagbucks without the code??? Since when is that in???

**Comment by Hatterhat** [comment]
:) @Ludox235

**Review by Ghommie — APPROVED** [review]

**Comment by Kraseo** [comment]
both uplinks have to be active otherwise you're just tapping two PDAs against eachother like a monkey so just don't leave your uplink up fourhead

**Comment by Hatterhat** [comment]
@Kraseo correction: only the siphoning uplink has to be active for funny uplink stealies

**Pull request merged**
