### PR TITLE
Pricehikes the Syndicate Mask, makes it one per customer.

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
This silly little mask, while _underrated_ by the powers that be on station, is severely underpriced, due to it's value potential. A two telecrystal click delay **halver** that has no limit on the amount sold and the amount of items it can be used on is frankly one of the most overpowered things in existence, due to people being able to juggle a "mask" that fits on the eye slot to have many charges of super speed.

In the interest of not completely removing the fun, though, I've elected to merely make it one per customer, and make it take up 5 telecrystals instead, so buying it is a slightly more impactful thing than not.

## Why It's Good For The Game
This really should be called "How did this mask ever make it into the game".  Extremely cheap, jugglable, infinitely recharging click delay halvers usable on all weapons are terrible. This makes it **less** terrible, and slightly less valuable.

## Changelog
:cl:
balance: The Tiger Collective has not been able to keep up production quotas on the Phantom Combat Enhancer Mask, forcing Syndicate Command to increase the price and limit the amount purchasable at one given time.
balance: Syndicate Mask price increased from 2 -> 5 TC, and is restricted to one per customer.
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
Wouldn't the better change be just to prevent it from juggling?

There is no reason to get more than one other than doing some weird juggling stuff, didn't even know that was possible.  Or if you don't spend all your TC then buy another one later if you got arrested.

**Comment by ghost** [comment]
Making it single buy, sure why not. But why would you make the price of something you get use out of with a 5 minute downtime worth 1/4 of your budget? No one buys it because even at 2TC it's not worth getting due to the lengthy cooldown that doesn't even tell you when it's ready. The only time I ever see the syndie mask is when it's from a loot crate.

**Comment by KrabSpider** [comment]
> lengthy cooldown that doesn't even tell you when it's ready. 

Examine the mask and you'll see if it's ready or not. 
Also counterpoint; you don't see people get a plastitanium toolbox even though it's a poor man's emag. You're expecting the very few antag players to actually pay attention and use the tools offered to their best use on a server that ain't even know what it wants to be?

**Comment by TheObserver-sys** [comment]
Let's not get it twisted here. People don't buy the mask because they're often combat averse, and rarely bother to experiment with the tools of their uplink and mechanics of the game. People didn't think about juggling masks from face to inventory because they didn't consider that it might be possible, unfortunately, I did, and realized just how potentially busted it is, at it's pricepoint.

Why am I moving the price up **and** limiting it to one per customer?  Simple. The ability to halve the click delay of __any item__, infinitely (after a cooldown) should be fucking **expensive** and _limited._  Fists of the Northstar, one of the only items that grants you reduced click delay is both expensive, and has a major caveat, that you only get it on fist strikes exclusively, no other items. This shitty, dollar store mask, for some reason against god and nature, gives it to you, no strings attached, on ANY ITEM IN THE GAME. Wanna turn your stechkin into a pocket machine gun? Breathe in, pull the trigger, watch as people are effortlessly slaughtered (or knocked out with use of sophorics). Wanna turn a WT550 into a Saw, damn near? Make an angry face, pull the trigger as fast as you can. Wanna magdump people with the HoS laser gun at lightspeed? Wanna turn into a mini hulk with a plastit toolbox? Wanna make fist of the northstar, but don't want to have to make the commitment of always wearing it **and get better armor to go along with it?**

If all of these reasons that it's kinda a mega**FUCK** idea to keep it at a 2 TC price point can't get through to you, then nothing I could bring up would satisfy you anyway.

IN closing, though, I'll leave you with an [experiment](https://cdn.discordapp.com/attachments/820393145757990964/904995220431720448/2021-11-02_03-23-50.mp4) I did while considering even making this PR.

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Definitely on board with limiting them to one each, price hike sure though neutral on whether 4 or 5. This is one of the most lethal and underrated items in the uplink, allowing for brutal levels of lethality in short bursts and with a 5 min cooldown, as can be seen when people *do* use it.
In general kinda weird to have this be "you can burst and be a beast for a short time but then have a pretty long cooldown" as opposed to *most* other things that do simillar and have limited uses instead, but thats way out of scope here.
Please do remove the accidental bits touching other files though.

**Comment by TheObserver-sys** [comment]
I didn't actually touch the additional files listed as being modified, looking over my commits. I think it **might** be something messy with my branch updating, but it shouldn't have an adverse effect on the game.

**Comment by ghost** [comment]
> 
> 
> Let's not get it twisted here. People don't buy the mask because they're often combat averse, and rarely bother to experiment with the tools of their uplink and mechanics of the game. People didn't think about juggling masks from face to inventory because they didn't consider that it might be possible, unfortunately, I did, and realized just how potentially busted it is, at it's pricepoint.
> 
> Why am I moving the price up **and** limiting it to one per customer? Simple. The ability to halve the click delay of **any item**, infinitely (after a cooldown) should be fucking **expensive** and _limited._ Fists of the Northstar, one of the only items that grants you reduced click delay is both expensive, and has a major caveat, that you only get it on fist strikes exclusively, no other items. This shitty, dollar store mask, for some reason against god and nature, gives it to you, no strings attached, on ANY ITEM IN THE GAME. Wanna turn your stechkin into a pocket machine gun? Breathe in, pull the trigger, watch as people are effortlessly slaughtered (or knocked out with use of sophorics). Wanna turn a WT550 into a Saw, damn near? Make an angry face, pull the trigger as fast as you can. Wanna magdump people with the HoS laser gun at lightspeed? Wanna turn into a mini hulk with a plastit toolbox? Wanna make fist of the northstar, but don't want to have to make the commitment of always wearing it **and get better armor to go along with it?**
> 
> If all of these reasons that it's kinda a mega**FUCK** idea to keep it at a 2 TC price point can't get through to you, then nothing I could bring up would satisfy you anyway.
> 
> IN closing, though, I'll leave you with an [experiment](https://cdn.discordapp.com/attachments/820393145757990964/904995220431720448/2021-11-02_03-23-50.mp4) I did while considering even making this PR.

The mask also lasts for a short while and _only_ has the benefit of decreased delay. You can magdump your limited-capacity weapons if you want, but unless you're bumrushing (which in that case, you're going to win mask or not) you're going to end up wasting the vast majority of your arsenal in seconds.

Running at someone with an esword or desword and the mask? Well, have fun running **the same speed as them** meaning you're going to spend most, if not all of the mask's duration just trying to click them once.

As for the northstars, you're also forgetting that it not only just works for fists, but it also gives you a lot of other benefits, including **ignoring softcrit**, increased wound damage AND a bonus to your fist damage to boot, on top of you dealing the usual stamina damage that punching and kicking does. The only downside that is active alongside all of these benefits is you can't use guns which, if you're going pugilist... doesn't even matter in the first place.

The limited to 1 person is fine, but a price change is absolutely asinine and will make an already niche item even more obscure outside of loot crates

**Comment by keronshb** [comment]
I feel it should be one or the other - pricehike OR limit per one.

At both, it's overkill to have the delay at 5 minutes.

**Comment by DeltaFire15** [comment]
Unadressed changes with nontargetted files still changed. Please either resolve them on this branch or transfer your changes to a fresh branch without the issues of this one. Either way, marking PR as stale.

**Pull request closed without merging**
