### PR TITLE
One last attempt at balancing tasers (and some adv egun stuff)

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Tasers changed to apply 20 stamina over its duration with an instant 10 stamina on hit
Tasers now only slow down by 1.5 instead of 8, and only if you are not already crawling.
Tasers do not knockdown or disarm.
Tasers do not increase clickdelay or disable combat mode.
Tase effect duration is 3 seconds.
tasers now have 12 range up from 7
taser stutter doubled
AI turrets keep the old powerful taser effect.
Hybrid tasers can fire 10 taser shots, drawing from the same energy pool (probably too much but we'll see.)

Taser cooldown is 1.5 seconds, bound to right click.

Advanced energy guns have LOST stun capability entirely. They were well overdue a nerf anyways (and whoever made them shit out 400 radiation, you are a very silly person).
Advanced energy guns now emit radiation pulses when overloading instead of checking if they're on a mob, but only pulses 50 on normal warmer ticks and 200 when overloading. Who the hell thought 400-800 was okay? Also it didn't even work before because it's not in mob contents if it's in your backpack, well now you're actually punished for carrying 16.

Head of security multiphase gets to knock down with 30 stamina damage with no cap in addition to normal taser effects for now, until that's proven as balanced (haha, yeah right), so bad it's changed as well, or someone gets me a better idea that isn't giving them a roundstart ion carbine (no).

## Why It's Good For The Game

Last effort at rebalancing tasers to be a niche-ish situational thing vs an one hit instant game over wonder in lieu of full removal.

## Changelog
:cl:
experimental: Tasers have been heavily reworked.
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
Combat mode is awkward as is, tasers seem to be bola guns now, and honestly until Combat works better in general I don't see the taser being something that should stay at all. It was built for stun combat which we don't have. It's not really a taser in this iteration. Meh.

**Comment by BlueWildrose** [comment]
This probably would need some adjustments to the AI's turrets, both in their upload and their core that'd just make them forget about tasers when in non-lethal mode. Anyone probably could easily break into the AI core with this change.

**Comment by Ghommie** [comment]
Merge conflicts.

**Comment by silicons** [comment]
duration buffed to 30
range buffed to 12

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
