### PR TITLE
gamer is now filtered for clowns

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game
funny

## Changelog
:cl:
tweak: added two words to clown filter
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
good pr

**Review by BlackMajor — APPROVED** [review]

**Review by deathride58 — DISMISSED** [review]
Numerous different repos have gotten nuked in the past for containing this word regardless of context. Remove it from this PR

**Comment by BlackMajor** [comment]
A repo would get nuked for censoring the n-word?

**Comment by Putnam3145** [comment]
for including it explicitly, yeah

**Review by nik707 — APPROVED** [review]

**Comment by Ghommie** [comment]
I really, really don't like the Smile genetics mutation. Whoever made them probably had no understanding of regular expressions at the time.
That said, It's good to go, though someone should apply some quality regexing on the thing.

**Pull request merged**
