### PR TITLE
Gamemode and gamemode vote obfuscation (Plus hub entry rework)

### PR DESCRIPTION
**Pull request by deathride58**
Quit self-antagging during extended just because "hurrr no antagggs!!!! i giv sec thing 2 doo!!!!!!!!". Nobody likes it, and I'm getting sick and tired of having to explain over and over that self-antagging is not acceptable, even during extended.

This PR obfuscates the gamemode and gamemode vote from players, but admins are given complete knowledge about the gamemode vote. This will help discourage people from using the gamemode as meta info for the sake of powergaming/as an excuse to self-antag.

This also reworks the hub entry! Here's a preview of the new hub entry
image

This also affects alert levels. When the alert level gets rolled, there's a small, yet notable chance that the game will change the alert level to the opposite alert level intended for the gamemode

:cl: deathride58
tweak: The gamemode and gamemode vote are now obfuscated from players. Admins will still be able to see all of the information regarding the current gamemode and the gamemode vote.
tweak: Gamemodes now have a small chance to use the opposite alert level intended for the gamemode.
tweak: The hub entry has been changed. It no longer displays the gamemode, and no longer displays the handful of pointless information present in all other SS13 server hub entries. Instead of displaying the gamemode, it will now display the ingame security level.
/:cl:

### CODE REVIEW

**Comment by Nightspark43** [comment]
I very heavily disagree with this change, me and a number of my friends actively avoid secret due to our own reasons, and all this is doing is making me, and maybe them not want to play at all.

And before anyone pops in with 'Just play the RP server,'  The RP server is almost literally dead, and I'd like to meet new people while also playing with established friends instead of ssitting around doing nothing for an hour hoping one other person arrives.

**Comment by ghost** [comment]
Then go go vore where it's always extended. Or just fine safe places to rp nerd, lavaland is the safest place with a capsule near the base

**Comment by ghost** [comment]
Also just vote extended, it won't change what the outcome of the gamemode is anyways with the voting changes. Also it's ss13, a game where paranoia is supposed to be mostly present

**Comment by deathride58** [comment]
@Nightspark43  You and your friends are a part of a small minority of the playerbase. As I've stated multiple times in ingame deadchat, if something as small as obscuring the gamemode is enough to get you to stop playing entirely, then tough luck.

The RP server was initially made as a safe haven for those that dislike secret, along with those that wanted a more RP-focused environment than the main server. However, instead of actually joining the RP server and populating it, the small minority that the RP server was made for chose to stick on the main server, making up all kinds of excuses to not join the RP server, and being disproportionately hostile about it when told to check out the RP server. The current excuse of "there's nobody playing on the RP server!" is primarily due to the endless feedback loop that was initially sparked from the target audience refusing to play on the RP server due to the now-removed whitelist. It'd be entirely plausible to break that endless feedback loop by having a group of friends consistently populate the RP serverr, but since nobody's stepping up to the plate to do so, the endless feedback loop of "There's nobody playing on the RP server!" remains.

**Comment by Nightspark43** [comment]
All repopulating the RP server is going to do is make another impenetrable clique culture start, most of the people I knew from the RP server stopped going there because no one new ever showed up, even after the whitelist was removed, so that's not going to fix anything.

And yes, I find no fun in about 75% of the current gamemodes due to inherent mechanics that cannot be changed without fundamentally altering how the gamemode is supposed to play, as such, I've stopped playing secret so as to not run into something I find so unfun that I'd rather just not play at all because of, I've burnt out completely several times due to that, at this point, my last bastion of defense against said unfun content is very likely going to be removed, what's the point in sticking around if all that'll happen is I get stuck with things I don't enjoy, namely clique culture and almost everything except for changeling and traitor modes.

I don't even want it to be exclusively extended, I'm fine with secret being played, people deserve a break from extended, just like how a long string of secret could use a bit of extended, all I want to be able to do is see the gamemode voted for so I know if it's worth joining or not, because most of the time, secret just isn't worth joining.

**Comment by ghost** [comment]
>he can't handle occasionally dying to an antag when secret is rolled like twice a day

just don't die bro

**Comment by CameronWoof** [comment]
Legitimately awful. The majority of the playerbase prefers Extended and a non-zero number of them don't play Secret. Do not merge, or at the very least, have an actual poll about it that's not based on github emojis.

**Comment by Poojawa** [comment]
> We don't want to go to the RP server, it's dead

If people populated the RP server, would it still be dead?

**Comment by SomanBat** [comment]
I approve of any step used to remove metainformation from the hands of players. Knowing the round type to be "safe" or not is a prime example of metainformation.

This is a fair compromise. If you see the station is blue/red, and you dislike those types of rounds, you can just not join up.

Round type really isn't something a player should know anywho. If you're altering your playstyle based on if it is or isn't secret, you're metagaming. This should slow that down.

**Comment by RogueSteampunker** [comment]
>Complains that people self-antag, buying into the idea they do it for the sake of sec, and not just for being idiots
>Removes any ability to know if it's extended or not, and will guarantee complaints from themself and others when more people join shortly after roundstart to try and avoid being a target
>ultimately trying to pull a Stoned, hoping that people will flock to the dead RP server, when Terry has shown us that trying to get people to go to servers that have little purpose for the majority of the playerbase doesn't work

Good job, you've fucked up again, this time thinking so low of the playerbase to make ANOTHER pr that's basically "Don't make admins ban people 2: electric boogaloo" while also thinking high enough of them to be able to maintain a side-server that you yourself couldn't get off its feet

Nice

**Comment by cebutris** [comment]
> The majority of the playerbase prefers Extended and a non-zero number of them don't play Secret.

Wow! If only there was a side server specifically catering to those types of people!

Seriously. No matter how much you complain, no matter how many excuses you make, the only response you'll get from us when you ask for more extended and less secret will be "play the RP server" because that's what it's meant for. That is _literally_ the entire point of the RP server. The excuse that's always made is that "nobody plays on the RP server!" but if what you say is true, if the majority of the playerbase truly does prefer Extended, and if a good amount of them legitimately do not play during secret, then the RP server should have enough population to be stable. The fact that it doesn't leads me to believe that what you're saying is wrong.

**Comment by RogueSteampunker** [comment]
@cebutris or, and hear me out on this one, the server is just so far gone, that no one wants to try and play on it? Cause y'know, a population of two at it's highest isn't really all that inviting for people to go join in on, no matter how much you or others try to say "it could be fixed if people just joined and played on it."

Jussssttttt sayin.

**Comment by cebutris** [comment]
The population would be fixed if more people played. If people want extended 24/7, they should play there. There's apparently a good chunk of people that want extended 24/7, and yet despite that, nobody plays there. That means that SOMETHING is wrong. I'm very much happy for any change that encourages those types of people to play on the server made for them

**Comment by Nightspark43** [comment]
Two things, one, nobody wants permanent extended, if we did, we would have tried to push for it or go to rp, what me and a number of the others who don't play secret want is to tell the modes apart, I don't want secret to go away I just don't want to take part in it myself, because I don't find it fun to play, but interesting to watch, usually.

Two, the main problems of the rp server are that apparently a config broke at some point and it didn't get fixed until recently, and my personal issue, which is the fact that the rp server eventually becom as it's own clique some people have problems getting into, and I personally don't want to go with the same seven people for three months before anyone else shows up like last time, that's only slightly above secret in my don't like it camp.

**Comment by CameronWoof** [comment]
So, people throw around the term "metagame" a lot and it doesn't apply here.

If my friends asked me to play a board game, my likely response would be "That depends on what game we're playing." If they then responded "It will be either LIFE or Monopoly, but knowing which one before you agree to play would be metagaming," I'd probably laugh at their funny joke and then ask, "No, really, what are we playing?"

Knowing what the gamemode is before signing up to play is completely reasonable. Implying otherwise is obtuse.

**Comment by Nightspark43** [comment]
Not to mention if you try to watch them over their shoulder you're not allowed to join afterwards, and all you have to go on is the box, but it's blank white with the name scribbled on, but it has a 20% chance to actually be the other game.

**Comment by SomanBat** [comment]
@Nightspark43 Nothing really stopping you from rallying others to the RP server.  Gather em up, go over, and play. 

You'll need people doing the "non-RP" jobs though, like engineering, chem, research, and the like.

That, I feel, is why the RP camp doesn't want to use the RP server. It's easy to sit in the bar and RP, when Other People are handling the gameplay aspects of keeping the round going.

**Review by silicons — APPROVED** [review]

**Pull request merged**
