### PR TITLE
borgis/scrubpups/medihounds aka standard/janitor/medical dogborgs now all have miniextinguishers

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by Cw3040** [comment]
yes
buff dogborgs further

**Comment by deathride58** [comment]
Why's this necessary? Their tongues already reduce firestacks

**Comment by Cw3040** [comment]
maneuverability in zero-g is the reason

**Comment by Cw3040** [comment]
read: giving dogborgs ion thrusters roundstart :^)

**Comment by silicons** [comment]
while dogbogs are powerful I don't think this is too much of a buff to them when comparing to normal borgs.

**Comment by Poojawa** [comment]
Ion thrusters would be good for z-g stuff, especially with how costly they are

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
