### PR TITLE
Lung pr + limb grower pr no one asked for.

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Adds 4 new lung types for breathing nitrogen, carbon dioxide, methane and methyl bromide. These use the slime lung sprite/*gas name* vacuole as names example: "Nitrogen Vacuole". Normal slime vacuole renamed to "Oxygen Vacuole"
Limb grower can print these new lungs along with now being able to print oxygen vacuoles, plasmaman lungs, ash walker lungs and lizard tails. Balance minded people please weigh in on ashwalker lungs/lizard tails.
Breathing nitrogen now outputs ammonia, thanks putnam.

## Why It's Good For The Game
Unused alerts should be able to be used. 
Ashwalker/lizard tail printing may be questionable due to their uses, someone more balance minded please weigh in on this, its not hard at all to switch those to emag only.

## Changelog
:cl:
add: New unique lungs are now available at the limb grower, located under the plasma man and other tabs.
add: Lizard goods including tail and ashwalker lungs are now available at the limb grower under the lizard tab. Access may be restricted.
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
What would the lizard tail be used for? As far as I know, it lets you craft a specific whip and it otherwise can be used in a specific booze, but what else?

**Comment by bunny232** [comment]
Bounty apparently? Miners could just grab a legion lizard corpse for that though so it just makes it faster to get that done
Edit: checked bounty code, 3000 for lizard tail, 4000 for tail whip. So not that much.

**Comment by DeltaFire15** [comment]
Pending further discussion due to balance implications & (I never thought I'd say this:) lung bloat.

**Comment by bunny232** [comment]
Could test merge it and see what happens since literally no one is giving feedback

**Pull request closed without merging**
