### PR TITLE
shamelessly nerfs purified claymore

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
it does fireaxe force in one hand and is theoretically mass produce-able ok don't sue me
this will only matter up until kevinz finishes his dark souls parry refactor anyways

also before you ask no i have not stabbed someone or been stabbed by someone with one of these block chance is just kinda poggy

## Why It's Good For The Game
yeah

## Changelog
:cl:
balance: removed the purified claymore's 50% block chance
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Maybe reduce the force? To like, 15? Or just remove the means to mass produce it?

**Comment by Arturlang** [comment]
Yes, make it chaplain converting only, at the LEAST

**Review by Ghommie — APPROVED** [review]

**Comment by necromanceranne** [comment]
My primary concern is less the block (it's still a concern) and more that it's still outdamaging a fireaxe in one hand.

Also holy fuck these things were so much stronger than eldritch longswords what the fuck @Hatterhat. It didn't click until just now how they went from a 30 force longsword without block to a 25 force longsword with as much block as a riot shield except it blocked all attacks, including lasers. That's unbelievably silly and even a cultist would want to make these into purified longswords over their own validswords just because statistically speaking they were superior in every way. I'll be completely honest, just remove this entirely it's just really not needed.

**Comment by silicons** [comment]
@necromanceranne remove it if you want

**Pull request merged**
