### PR TITLE
Removes Hive's Blessing and Xeno Queen Corpse from the Alien Ruin

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Tin.

## Why It's Good For The Game

It's been a long time coming, and it seems to do a lot more harm than good, from causing balance issues with the strong knockdowns, to people soft griefing with it. It also seems like people are obnoxious about it. A lot of people dislike it, and as the person that originally added the ruin and Hive's blessing, I think it's time they go.

## Changelog
:cl:
del: Hive's blessing and the xeno queen corpse have been removed from the lavaland alien ruin.
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
The corpse of the queen should really be left but it needs to have the eggsac removed from it.

**Comment by timothyteakettle** [comment]
keep the corpse, remove its egg sac, replace hive's blessing with some funny xeno-related item that isn't going to turn people into aliens

**Comment by keronshb** [comment]
By removing the corpse that's a hit to science/medical.  Even if it was RNG in the first place, experimental dissection of a queens corpse yields a decent amount of points.

**Comment by shellspeed1** [comment]
Possible alternative what if we replaced the queen with other xenomorph subtypes like the praetorian or sentinels?

**Comment by YakumoChen** [comment]
Reminder being a feature creator is not a valid reason for removal

**Comment by Tupinambis** [comment]
It would seem that the overall reception this PR has gotten implies the issue is not as significant as I initially had assumed. Will be closing it.

**Pull request closed without merging**
