### PR TITLE
LionBorgs

### PR DESCRIPTION
**Pull request by WanderingFox95**
## About The Pull Request
First of all, ignore all these commits. Wrangling GitHub to get my fork synced up to main, to undo modifications I did to another file earlier while trying something out and such kinda bloated up the log. Essentially only two files are changed. robot_modules.dm and widerobot.dmi, the others are just me cleaning up changes that didn't work. It's just all listed here. I mean, you can see which files are effectively modified and how.

## Why It's Good For The Game
Dogborgs are common - but what about catborgs? Exactly. And that's why I decided to add more variety.

## Changelog
:cl:
add: Added LionBorgs - Yes, a borg design looking like a lion.
imageadd: added sprites, obviously
code: changed some code to allow them to be selected
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
How about you put the goddamn pictures in your PR instead of making everyone have to download the fucking .dmi files

**Comment by Bapldap** [comment]
Better PR would be removing dogborgs (and not adding this), try that. Good luck!

**Comment by BlueWildrose** [comment]
> 
> 
> How about you put the goddamn pictures in your PR instead of making everyone have to download the fucking .dmi files

Go into the "Checks" tab on this PR and go to the IconDiff bot. Open the widerobot.dmi drop down and you can see the lions in action.

I must say, the walkcycle sprites are a bit weird looking.

**Comment by moltoretardo** [comment]
Drakeborg two, electric boogaloo. 

I am too lazy to rewrite why it's an awful idea. You can always refer to the week long drama storm that occurred not so long ago.
It's not fetish content though!

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> > How about you put the goddamn pictures in your PR instead of making everyone have to download the fucking .dmi files
> 
> Go into the "Checks" tab on this PR and go to the IconDiff bot. Open the widerobot.dmi drop down and you can see the lions in action.
> 
> I must say, the walkcycle sprites are a bit weird looking.

Thank you kind stranger

And yes the walk cycle looks weird, as if they're galloping like a horse.

**Comment by moltoretardo** [comment]
🎣

**Comment by silicons** [comment]
not a fan.

**Comment by moltoretardo** [comment]
I’ll give you props, I thought this awful idea was an april fools which would’ve been funny.

As I am quite lazy to rewrite the same arguments twice, please refer to the week long drama storm that happened not so long ago regarding drakeborgs.

Drakeborg two, electric boogaloo

**Comment by BlueWildrose** [comment]
> 
> 
> I’ll give you props, I thought this awful idea was an april fools which would’ve been funny.
> 
> As I am quite lazy to rewrite the same arguments twice, please refer to the week long drama storm that happened not so long ago regarding drakeborgs.
> 
> Drakeborg two, electric boogaloo

The reason why drakeborgs were removed was because of the requirement that you included credits for the sprite beside the DMI for it - something that was never required for Citadel's codebase up to this point.

The lionborgs don't require this on the other hand.

I will state that these sprites... are just really janky looking though.

**Comment by moltoretardo** [comment]
`The reason why drakeborgs were removed was because of the requirement that you included credits for the sprite beside the DMI for it - something that was never required for Citadel's codebase up to this point.`

That was only one of the reasons, if you followed the whole argumentation that happened back then, you can probably recall it going a bit deeper into the whatever hole.The whole idea of having another fetish beastiality borg disgust me and, as stated by an headmin, those aren’t just the cute roboderg you take for a walk, making them a cringe fetish addition. 

F565E388-6B75-41C3-8EDE-DBB43E64FFCB

**Comment by TripleShades** [comment]
janky and kinda cringe to add more feral-based borg forms, but also?
the service palette used makes it far too easy to mistake for medical. terrible. awful. please do not.

**Comment by WanderingFox95** [comment]
This was only a draft to begin with and to see some feedback. I'll work on improving the sprites and make them less janky. Using Dream Maker to do this was a pain, especially when I have much better options for spriting. Also, mind you - if I knew how to remove the vore stuff from that borg design I absolutely would. Except for licking, licking isn't vore, it's a harmless act of affection. I'll get to it when I get to it and close this _for now_.

**Pull request closed without merging**
