### PR TITLE
funny chair loses block chance and gains active block/parry

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
chairs lose block chance since we are swapping over to active blocks/parries for items, too much to paste in here so just check code for values

## Why It's Good For The Game
removing old systems

## Changelog
:cl:
balance: gave chairs active block/parry in exchange for removal of block_chance
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Why exactly is a random chair better at blocking than an actual weapon aka electrostaves?

**Comment by Sishen1542** [comment]
Chairs had a 50% block chance previously.
Also they have a 5% chance to break on attack/block

**Comment by Hatterhat** [comment]
buff it to 10 force because its inevitably going to break and because its a whole ass chair you are bashing someone to death with

**Comment by Sishen1542** [comment]
you can attack while blocking with chair, 10 force would make ripostes 25 unless I brought the multiplier down a bit.

**Comment by Sishen1542** [comment]
chairs require 2 hands to pick up now, gave a few value tweaks and introduced a damage cap (anything over 20 force will go through no problem, so riot shields are better at handling the big weapons)

**Pull request merged**
