### PR TITLE
plasmafist wizard plasmafist wizard

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
wizard can spend 3 points to buy plasmafist

it's the hippie thing (tm)

## Why It's Good For The Game
it probably isn't but wizard martial arts, more gimmicks, less fireball

also i don't feel like plasmafist is stronger than timestop, fireball, or ei nath, or any of them mixed together, seeing as how plasmafist is just ei nath with a chargeup

## Changelog
:cl:
add: plasmafist to wizard
/:cl:

### CODE REVIEW

**Comment by Linzolle** [comment]
NAMEKO PLASMA FIST HAS A COMBO THAT INSTANTLY GIBS

**Comment by ghost** [comment]
I KNOW CUCK

YOU KNOW WHAT ELSE WIZARD HAS THAT GIBS

**Comment by GrayRachnid** [comment]
> 
> 
> NAMEKO PLASMA FIST HAS A COMBO THAT INSTANTLY GIBS

Wizard has ei nath

??

**Comment by ghost** [comment]
also i like martial arts even if their code confuses me :)

**Comment by ghost** [comment]
feel free to give suggestions for pop limits and cost increases lmao but honestly wizard is already more busted op than plasmafist and i don't think i'm worrying too much about wizard having free aggrograb and nerfed/buffed ei nath compared to them having any of their other gamer gear honk

and yes i do know that just because something is op doesn't mean we should make it more op, but more variety = higher chance of fireball wizard not existing so fine in my book

**Comment by ghost** [comment]
also on an unrelated note i was looking at martial art scarp file and for some reason the chaplain's bo staff null rod is in it lmao

**Comment by Linzolle** [comment]
> 
> 
> also on an unrelated note i was looking at martial art scarp file and for some reason the chaplain's bo staff null rod is in it lmao

actually thats a compltely different bo staff than the one the null rod turns into, oddly enough.

**Review by Putnam3145 — APPROVED** [review]

**Comment by Putnam3145** [comment]
i take some responsibility for balance if this turns out to be OP

i know people will probably do this AND fireball but i can dream. i can dream

**Comment by ghost** [comment]
hey, nothing stopping people from doing fireball ei nath :)


at least it isn't wrestling ;^)

**Comment by Putnam3145** [comment]
i will take responsibility for all pain and misery this leads us to. yahoo

**Comment by ghost** [comment]
YO POG

**Pull request merged**
