### PR TITLE
heretics touchup

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

adds 7 new abilities to heretics. 1 passive for each path, 1 active spell for each path. 1 mute spell any path can take at any stage, just costs a point. fixes a bit of stuff and adds a way to remove circles as a non-heretic.

## Why It's Good For The Game

more stuff to sink points into before ascension is good. mute spell to help secure targets good. should make heretics better without buffing their ascensions too hard

## Changelog
:cl:
- runes can now be destroyed by non-heretics using a bible or a null rod
- mansus grasp now has a unique inhand.
- madness grasp now has a unique inhand.
- blood siphon is now redder.
- silence spell, lasts 20 seconds, gives an obvious message to the victim.
- fire immunity passive for ash
- guaranteed dislocation passive for flesh
- rust grasp passive for disgusted mood/causes victim to vomit.
- rust grasp cooldown reduced by 75% on structure/turf hit.
- living heart now checks z-level when telling you where someone is.
- grasp of decay: forced corrosion for 20 seconds, can make you vomit. probably shitcode.
- madness touch: give people trauma, braindamage and a terrible mood.
- nightwatcher's rite: fire shotgun that can do 75 damage on point blank
- flesh sickle buffed a bit. 5 -> 10 wound bonus, 15 -> 20 bare wounds bonus
- descriptions touched up a bit.
- fireball oath for ash ascension nerfed a bit. 70 second cooldown -> 120 second cooldown
- emp for rust hand removed
- rust can no longer stab themselves with their sickle to get the funny adrenal water fluid in their system
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
Finally, **THE** Z-level check

**Comment by kiwedespars** [comment]
you can locate people without it if you're a _good_ heretic, noob.

jokes aside though yeah it's finally here.

**Comment by Detective-Google** [comment]
epic fire immunity cant wait to plasma flood/flamethrower cheese as an ash pain

**Comment by Detective-Google** [comment]
Also vomiting is a 7 second hard stun

**Comment by Detective-Google** [comment]
I dont think i need to explain the issues with random traumas and shotgun spells

**Comment by Tupinambis** [comment]
traumas and vomit hands are absolutely horrible ideas. They can absolutely fuck someone over incredibly easy and make them incapable of fighting back. Keep in mind stuff like split personality exists too and that can REALLY cause problems. I am not a fan.

**Comment by kiwedespars** [comment]
trauma hand is just a phobia (or it should be) on a 3 minute cooldown
vomit hand is bad, but it's taking the place of the would-be winstate of ascension, and it's pretty delayed since it's just the status. could tone it down to a lower state of **absolute** disgust
5 streams of fire that do at an absolute pb, 80 damage aren't too bad i don't think, especially since, again they're taking the place of ascensions.
again fire immunity is taking the place of ascensions. shit they would've had at that point alongside **more** buffs.

this also makes them a bit stronger as unascended cultists, which are incredibly easy to stop compared to ascended cultists. i think it's neat, and i'd just say to see how it plays out and notice that you'd have probably armed up in advance because cultists who reach this point have sacrificed to get to it.

**Comment by The-Sun-In-Splendour** [comment]
Those abilities actually delay ascension, so I don't see how it is bad that they may have very strong abilities in the end game at the cost of delaying ascension which is just demi-god.

**Pull request merged**
