### PR TITLE
Fixes Radiation Closet Anti-Radiation Kit Icon (Thanks Flechercap.)

### PR DESCRIPTION
**Pull request by Ragolution**
Amends erroneous icon_states and adds functionality to medkits to pick one of the random striped/color patterns.

Hope it doesn't break anything.

### CODE REVIEW

**Comment by CameronWoof** [comment]
Most of this PR doesn't do anything. The paths you're changing are overwritten by #3800. You'll also want the radiation kit to point to [this dmi](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/modular_citadel/icons/firstaid.dmi) not the default storage one. It'll be out of place against the others.

**Comment by Ragolution** [comment]
OHhhh it's some modular shit

**Comment by Ragolution** [comment]
Turns out it was easier than I thought. 
:clap:

**Comment by CameronWoof** [comment]
This should work. If you wanted to add the multiple icon options, you can also add the following:

`/obj/item/storage/firstaid/radbgone/Initialize(mapload)
	. = ..()
	icon_state = pick("[initial(icon_state)]","[initial(icon_state)]2","[initial(icon_state)]3","[initial(icon_state)]4")`

**Comment by Ragolution** [comment]
Ready for review  and merge.

**Review by silicons — APPROVED** [review]

**Pull request merged**
