### PR TITLE
Removes Golem access to the station

### PR DESCRIPTION
**Pull request by Poojawa**
They're the new ashwalkers but with R&D toys and a license to grief due to 'lol w/e' as flavor text objectives.

No I'm not modularizing it. it's a quick fix.

### CODE REVIEW

**Comment by Poojawa** [comment]
Also I doubled checked and, no, this doesn't restrict them from their vendors. all it's good for is the ORM.

**Comment by silicons** [comment]
:rage:

**Comment by lightcat** [comment]
They're supposed to be neutral until provoked not just kill for no reason.

**Review by deathride58 — APPROVED** [review]

**Comment by Poojawa** [comment]
Well with the complete lack of feedback, I guess this is okay.

**Comment by lightcat** [comment]
Sure lets give it a go and see whats happens. They are not losing much anyways.

**Pull request merged**
