### PR TITLE
Makes all hypovials start full

### PR DESCRIPTION
**Pull request by improvedname**
Because the hypovials only being half filled triggered me.

## Changelog
:cl: Improvedname
tweak:Hypovials start full now
/:cl:

### CODE REVIEW

**Review by Ghommie — CHANGES_REQUESTED** [review]
I understand it's tedious to manually fill a hypovial with another at the start of every round, but you are doubling the overall availability of hypovial reagents without doing anything to counterbalance it, so it's not really a QoL change more than a powercreep.

**Comment by improvedname** [comment]
@Ghommie then why do they have double max volume??? it takes 3 seconds to make said chems its just super tedious to have a half filled hypospray

**Comment by improvedname** [comment]
The volume is max volume is 60/120
All beakers are filled to the brim
30 more bicaridine 60 more synthflesh will change nothing about balance you know it
You can get the preloaded medkits in medbay which means you can also steamroll all thrse chems out with macros with ease

If you gonna argue balance here the only arguement will be
Bicaridine vial.
Anti-toxin vial
Kelotane vial. All combined tricidorizine.

While the cmo gets charcoal for a reason?

**Comment by Poojawa** [comment]
All the hypovials were actually made full, but then Kev doubled their capacities without actually updating the rest of the code.

**Comment by Ghommie** [comment]
Just because it doesn't take much effort to make such reagents, it doesn't mean they should be even more effortlessly available at the very start of the round.
As an occasional chemist player, the existence of hypovials and the apotechary makes the job feel so damn irrelevant, almost vestigial to the point people hardly worry if I only make a couple useful reagents before calling it a day.

**Comment by necromanceranne** [comment]
Hyposprays being available to everyone was a fucking mistake.

**Comment by improvedname** [comment]
If this is really a big issue when doctors have direct access to chem dispensers and macros

**Comment by necromanceranne** [comment]
I'm more astonished they got powercreeped by their original tool, the 30 unit hypospray, and the vials can be printed for 60 unit beakers out of the chemmaster with the right chem quantities for specific macros. I just find it obscenely silly.

**Comment by improvedname** [comment]
blame kevinz 🤷

**Comment by silicons** [comment]
@Poojawa on purpose

@necromanceranne poojawa's fault not mine, i buffed it because 30 units was a goddamn joke with how crap they were (5 second delay why). now they're better although the whole emag instant eject is just shit balance to me
if you think it needs to be nerfed to 30 be my guest

@Ghommie i honestly wouldn't hurt a lot if hypos were seriously reworked

anyways yeah it's been 2 weeks i'm going to close this now

**Pull request closed without merging**
