### PR TITLE
Fixes racial blood colors.

### LINKED ISSUE #15051: Blood from specific human species (especially notably slimepeople) are discolored, except for footprints.
Generally non-human blood is colored a certain way. But, it isn't in this case.

I'm assuming this is because we're using a non-monochrome variant of blood as a sprite here.

## Reproduction:

Cut shit up.

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

Blood is always red due to a PR (that I don't know the name of, because I only know of it from reading a single commit) replacing the blood.dmi with the TG version. This removes that.

## Why It's Good For The Game

reverting an unintended change

fixes #15051 and #15003

## Changelog
:cl:
fix: The universe has realized that not every species uses hemoglobin again.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
mayhaps put the images for colorable blood in a separate dmi so it doesnt get overriten

**Comment by TheEaterOfBeans** [comment]
> mayhaps put the images for colorable blood in a separate dmi so it doesnt get overriten

that would require finding every reference to the blood sprites and changing it so it gets the sprites from whatever the separate DMI would be called

**Comment by Arturlang** [comment]
It is really easy to do this with VSCODE, just search icons/effects/blood.dmi, and tell it to replace with your variant

**Comment by TheEaterOfBeans** [comment]
> It is really easy to do this with VSCODE, just search icons/effects/blood.dmi, and tell it to replace with your variant

I have no idea what VSCODE is, so...

**Comment by Arturlang** [comment]
> > It is really easy to do this with VSCODE, just search icons/effects/blood.dmi, and tell it to replace with your variant
> 
> I have no idea what VSCODE is, so...

https://code.visualstudio.com/

**Comment by TheEaterOfBeans** [comment]
> > > It is really easy to do this with VSCODE, just search icons/effects/blood.dmi, and tell it to replace with your variant
> > 
> > 
> > I have no idea what VSCODE is, so...
> 
> https://code.visualstudio.com/

yeah uh
no idea how to use that
I literally just took the nanite vomit and added it to the previous version of the blood file, then replaced the current blood file with that.

**Comment by Arturlang** [comment]
You also deleted a bunch of probably needed images, such as xenogibs and so on, look at image diffs

**Comment by TheEaterOfBeans** [comment]
> You also deleted a bunch of probably needed images, such as xenogibs and so on, look at image diffs

They're still there, just called "xgib(insertpart)-OLD".

Also, again,
I literally just
added nanite vomit to the blood.dmi from before the PR that broke blood and then replaced the current DMI with that.

There is zero chance of this causing any new problems, it is a partial reversion of a single file.

**Comment by TheEaterOfBeans** [comment]
a

**Pull request merged**
