### PR TITLE
Ports cute birbs from RP

### PR DESCRIPTION
**Pull request by Xantholne**
Ports cute birbs from RP

Can be randomly bought from bird crate in cargo

the moluccan should've been more like the umbrella cockatoo though, but we can let it slide.

image

I'd credit whoever originally made them but honestly couldn't find through any search result
:cl:
add: New parrots from the RP server, can be found in Bird Crate in Cargo
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
How do we get access to them?

**Comment by Xantholne** [comment]
> How do we get access to them?

Changing up the bird crate currently to add them just need to figure out a method to choose randomly

**Comment by MrJWhit** [comment]
Awesome nice.

**Comment by LordSaladin** [comment]
birb crate

**Pull request merged**
