### PR TITLE
stops hijackers from being able to remotely blow up borgs (probably)

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

not sure if it actually works since I can't really locally test it

## Why It's Good For The Game

because blowing borgs from far away at any time is really shit.

## Changelog
:cl:
balance: stops hijackers from being able to remotely blow up borgs
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
please don't

**Review by silicons — CHANGES_REQUESTED** [review]
add range check to hijack implants while you're at it unless there's a good reason not to. something like 14 tiles for initial ranged hack, ongoing access can afford to be usable a bit further away if you want.

**Comment by Ludox235** [comment]
Mfw becoming an AI with the camera hijack is no longer possible if this pr is merged

**Review by silicons — APPROVED** [review]
whatever

**Pull request merged**
