### PR TITLE
Fuck it, Lambda Station, here we go!

### PR DESCRIPTION
**Pull request by dapnee**
## About The Pull Request
Welcome to Lambdastation! After almost two years in developement, the map is complete. Starting as a community project on Oracle station in which different players worked in game to create the map, headed by AndrewMontagne who created code to save the project as it was being worked on. After work on cargo, escape, medical, and parts of engineering, the project ended and I asked for the file.

I continued working on the file for a few months before jumping to a newer tg branch, in which I had to recreate the map from scratch. After another move to continue working the map on Citadel code, I have finally finished!

I'd like to thank Sishen for converting this to tgm formatting, and the original team of players that worked to shape the map.

## Why It's Good For The Game
New map, with a large maintenance system that allows additional rooms to be made, along with genpop! Good for mid to high population.

## Changelog
:cl:
add: Lambdastation and it's accompanying files
/:cl:

### CODE REVIEW

**Review by silicons — APPROVED** [review]
if this is an issue it can always be disabled let's go

**Comment by ghost** [comment]
there was just a round on this and have a number of thoughts, no doubt other players have more, but here's mine: 

- many, many doors do not have the proper access set, especially maint doors.
- map feels almost too large, probably better for high pop than medium pop. overall, rooms trend towards being too large and feel empty
- engineering has an awkward layout. also, it needs plasma/oxygen tanks. 
- whole thing needs more navigation signs. it's a huge map, give people some direction.
- round ended because of a tesloose. the engine was not sabotaged or set up improperly, rather, the emitters are not actually connected to the grid and failed after a generator was turned off
- pain in the ass to navigate the exterior for repairs
- nothing feels secure

as it is, it feels like an incomplete map

**Comment by dapnee** [comment]
- Doors are getting fixed.
- map is intended for a higher population, yes, complain to headmins for the config to have a minimum placed on it
- Engineering already has a tank dispenser, it's to the left of the engine, with the hardsuits. Though I am doing some changes to engineering.
- Adding even more signs would be redundant arrows that all point the same way until different hallways, but I will slap more stickers on the walls
- You'd be surprised at how not secure any map is if you feel that way about this one. I've been working on keeping the map from being too secure, where at one point, the armory in the middle of the brig and I was told that was too secure, 
- repairing rocks
  okay
The map was testmerged on low pop and every time it was in play I advertised it, but hey, why play low pop, haha.

**Comment by AffectedArc07** [comment]
Fuck I miss this map

**Pull request merged**
