### PR TITLE
SQL based character saving

### PR DESCRIPTION
**Pull request by Poojawa**
HEAVILY WIP, NOT TESTED YET

Ports and modifies Paradise's SQL saving system into Citadel, removing dependency on .sav files that are completely impossible to fix.

Vore preferences have been added to tables, as well as Cactus' arousal system framework. This should work as is now, but I haven't even test compiled locally, just getting this out there for the internets. fwee!

### CODE REVIEW

**Comment by Poojawa** [comment]
Yeah so, I can't get this shitty thing to accept ckeys no matter what I've tried. The only option left to me will have to be porting the majority of the UID I think.

**Comment by Poojawa** [comment]
¯\_(ツ)_/¯

Doesn't assign ckeys and just runtimes to shit. I dunno how to fix it.

**Comment by TalkingCactus** [comment]
is this dead

**Comment by LetterJay** [comment]
I'd prefer to keep this open assuming it's not gone for good.

**Comment by TalkingCactus** [comment]
closing until this is picked up again

**Pull request closed without merging**
