### PR TITLE
Glaceon+acorn hologram!

### PR DESCRIPTION
**Pull request by Squi-RL**
Imageadd: Glaceon bodymarkings in mam_body_markings.dmi
Imageadd: Glaceon ears and a tail in mam_bodyparts.dmi
Imageadd: An acorn hologram for AIs in AI.dmi
Edit: Added code to AI.dm to allow an AI to select the acorn hologram
Edit: Added code in sprite_accessories_citadel.dm to allow players to select glaceon markings,
ears, and tails.

[why]: To practice my spriting/coding, and because both myself and another have wanted sprites
like these to use

### CODE REVIEW

**Comment by LetterJay** [comment]
Gotta love them conflicts.

**Comment by Squi-RL** [comment]
not sure how it's conflicting, seemed fine when I ran it...

**Comment by Poojawa** [comment]
You didn't make a fresh branch, this contains #300 PR materials.

**Comment by Squi-RL** [comment]
yea... I'll close this out and redo it from the updated branch... at least I now know why the conflicts happened

**Pull request closed without merging**
