### PR TITLE
x-ray laser nerfs

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

nerfs x-ray laser irradiation from 300 to 
edit: 75
buffs x-ray laser damage to 20 from 15
nerfs shot capacity from 20 to 10

## Why It's Good For The Game

imagine getting shot 4 times and mutating getting hardstunned for 20 seconds on rng while simultaneously dying to tox

## Changelog
:cl:

balance: rebalanced x-ray lasers a lil.

/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Irriadiation is kind of the point though, it shoots xray lasers.

25 rads is Literally Nothing and you'll be good and dead long before you reach any meaningful amount of radiation.

**Comment by kiwedespars** [comment]
what about having a gun that shoots

- through walls
- applies a damage type that isn't easily fixed compared to literally the other 4 (radiation)
- can give you negative mutations and deal ramping tox-damage
- fits in bags
- has a 20 shot capacity

is balanced to you, but yeah i guess it's a bit weak now.

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Seems a bit overkill of a nerf, please don't completely nullify its special (hit) effects.
(25 rads = 20 hits till it's not completely safe, at which point you'll be long dead)

**Comment by DeltaFire15** [comment]
Replace it with a *light* nerf delaying it reaching the mutation threshhold by maybe 1-3 shots instead and this PR should be okay.

**Comment by kiwedespars** [comment]
6 shots until 500 rad,
10 shots total.
considering you can dual wield these and get 4 shots off for free on someone unaware **through walls** i'd consider this fair

especially when you again, consider these projectiles go through walls and give you a damage type that heals nowhere as close to the other 4 damage types

**Comment by YakumoChen** [comment]
you'll be *dead* by 6 shots total, it does 15 fucking burn

Nerf it to like 250 if you have to.

EDIT: oh he buffed the laser damage even, lmao

**Comment by lolman360** [comment]
have you considered nerfing shot count to 10 as well

**Comment by YakumoChen** [comment]
>buffed damage to 20
>it's the same as a regular laser gun now except through walls
>now a **straight upgrade** to the laser gun

I feel like you're entirely missing the fucking point now.

**Comment by kiwedespars** [comment]
10 shot capacity. i don't think it's a straight upgrade from regular laser guns, it's a tradeoff now.

**Comment by keronshb** [comment]
> 
> 
> 10 shot capacity. i don't think it's a straight upgrade from regular laser guns, it's a tradeoff now.

What about making it Bulky and/or needing to use two hands to use it?

**Comment by ghost** [comment]
My issue with both this PR and Yakumo's is that _neither_ tackle the issue of a gun with 0 counterplay having any reason to NOT use it. Changeling? Bloodsucker? Xenomorph? Abductor? Blob? Pirates and their ship? Any non-crew threat? Just stand behind a wall and laugh while they can't do anything to you except try to run which half the time won't work anyways if it's a long stretch that could even be 2-wide with walls. Normal lasers would be stopped by walls you can duck in and out, but x-ray?

If x-ray lasers _need_ to stay for some asinine reason then they need to have a reason to not be picked up unless you're absolutely sure you **_NEED_** them. Like irradiating the user heavily with each shot or steadily causing issues to the user while held.

**Comment by YakumoChen** [comment]
The tradeoff is the damage. It's not supposed to be high so you cant just dick someone over before they can react at all. Something OP is actively buffing despite complaining about this exact same problem. 
There's also a problem of collateral potential from missed shots and the fact that shooting behind walls is difficult without thermals. All of those antags you mentioned are likely to benefit more if they can snag those xray guns, blob benefits from less damage in general.
Making them strictly an upgrade to the laser gun is exactly what we dont allow in the code. (Shot capacity is not a major downside. 10 shots isn't even any lower than an energy gun)

OP also ignored the request of the maintainer so I cant see this gaining traction for a merge.

**Comment by ghost** [comment]
> 
> 
> The tradeoff is the damage. It's not supposed to be high so you cant just dick someone over before they can react at all. Something OP is actively buffing despite complaining about this exact same problem.
> There's also a problem of collateral potential from missed shots and the fact that shooting behind walls is difficult without thermals. All of those antags you mentioned are likely to benefit more if they can snag those xray guns, blob benefits from less damage in general.
> Making them strictly an upgrade to the laser gun is exactly what we dont allow in the code. (Shot capacity is not a major downside. 10 shots isn't even any lower than an energy gun)
> 
> OP also ignored the request of the maintainer so I cant see this gaining traction for a merge.

That's... not dissuasive at all, especially since a lot of antags take extra burn damage or have to spend more time healing it anyways. Most of which either lack rad healing or need to expend resources/valuable points to be able to deal with that one specific thing.

They shouldn't be something that anyone can pick up and use freely because lowered damage means nothing if you're not only getting to fire it from complete safety (behind 1+ walls that require time to remove) or you're doing chip damage on top of massive rad damage, potentially getting into the issue of mutating tourettes, yelling **_FUCK_** and then being a cakewalk due to a gun you cannot counter unless you yourself happen to have them in your bag.

Shotguns can be countered. Lasers can be countered. Swords can be countered; everything save for a penetrator round can be countered and, if you want to argue it, a perfectly cooked grenade. But what counterplay is there to x-ray lasers? You run but not all antags are able to actually run from projectiles that pierce the walls they try to duck between.

**Comment by YakumoChen** [comment]
>That's... not dissuasive at all, especially since a lot of antags take extra burn damage or have to spend more time healing it anyways. Most of which either lack rad healing or need to expend resources/valuable points to be able to deal with that one specific thing.

Citation needed? Vampires are arguably the only ones worse off and they have high armor anyhow and a lot of escape tools. Lings, xenos, blob, ayys have more trouble with up front damage than wall hacks and are not worse off (and none of those bar ayys are affected much by radiation)

>They shouldn't be something that anyone can pick up and use freely because lowered damage means nothing if you're not only getting to fire it from complete safety (behind 1+ walls that require time to remove) or you're doing chip damage on top of massive rad damage, potentially getting into the issue of mutating tourettes, yelling FUCK and then being a cakewalk due to a gun you cannot counter unless you yourself happen to have them in your bag.

The radiation should really be the bigger threat than the burn anyway to differentiate it from normal lasers and to make the wall hack not quite so awful. I dont see the problem. It's a late round weapon anyway and is almost never used due to being niche. There are plenty of counters such as just moving away, if you have a wall between them it's likely you have a good escape route. That's assuming they can even see you through the wall to know where to aim.

If sec is shooting at you with thermals with xray guns you have either fucked up badly as a regular antag (traitor) or you are an unga antag which late round balance is not a huge fucking deal for regardless due to being probably overpowered yourself (xenos, ninja, blob, lone op lol)

>Shotguns can be countered. Lasers can be countered. Swords can be countered; everything save for a penetrator round can be countered and, if you want to argue it, a perfectly cooked grenade. But what counterplay is there to x-ray lasers? You run but not all antags are able to actually run from projectiles that pierce the walls they try to duck between

If this gun is so vastly overpowered why has it never been an issue? You can block the projectile with any machine or door or just move away from the source. The damage is relatively low and doesn't stun so you're at an advantage if you fight back.

**Comment by YakumoChen** [comment]
To be clear the only antags I would recommend an xray laser for is Ninja or a roundstart antag that has scaled significantly and survived, like heretic or "hour prep time" traitor. Ninja in particular is a purposefully high powered late round antag who happens to have a big weakness to radiation (pretty much their only weakness), and the others will be on a level playing field anyway due to high scaling.

**Comment by kiwedespars** [comment]
>OP also ignored the request of the maintainer so I cant see this gaining traction for a merge.

I acknowledged the request, and I'm aware that 25 irradiation per shot is silly and overkill, that's why it's 75 now, so it's 6 shots for the tox-damage to start actually killing you. I don't sit well with a gun that deals a hard-to-heal damage type, being able to be mass printed where the fix for it is only readily available inside of sleepers.

>The radiation should really be the bigger threat than the burn anyway to differentiate it from normal lasers and to make the wall hack not quite so awful.

Radiation is still a threat, the issue you're taking with it is that it's no longer as **hyper-massive** of a threat where getting shot two-three times, while unaware, through a wall, by someone you can't even see, is going to give you mutations, a couple of which are likely just to hardstun you for long moments at a time.

> late round balance is not a huge fucking deal for regardless due to being probably overpowered yourself (xenos, ninja, blob, lone op lol)

xenos aren't affected by radiation
blob isn't affected by radiation NOR x-ray penetration
(might not be i forget)

two of the examples listed you're just using the x-ray gun because it goes through walls, not for the irradiation. loneop is unlikely that you'd use the x-ray laser against outside of if he's bunkering down in a blowing vault, and ninja has another reason you'd use the wallhack lasers on him.

>To be clear the only antags I would recommend an xray laser for is Ninja or a roundstart antag that has scaled significantly and survived, like heretic or "hour prep time" traitor. Ninja in particular is a purposefully high powered late round antag who happens to have a big weakness to radiation (pretty much their only weakness), and the others will be on a level playing field anyway due to high scaling.

Heretics scale, this is true, what isn't true is that it's putting them on a leveled playing field. Scaling doesn't make this 2-3 shot toxin-damage dealer go away. People use the x-ray laser on ninjas because it's the **one** thing that'll follow them jumping through walls.

>If this gun is so vastly overpowered why has it never been an issue? You can block the projectile with any machine or door or just move away from the source. The damage is relatively low and doesn't stun so you're at an advantage if you fight back.

because nobody else dives through the code and actually uses the gun because of the irradiation, they use it because it's damage that you can't **truly** fight back against through a wall. i just thought that the irradiation ability was dumb, especially when it's 3 shots to make someone bald and 2 shots **just** to start causing the tox damage.

**Comment by ghost** [comment]
> Citation needed? Vampires are arguably the only ones worse off and they have high armor anyhow and a lot of escape tools. Lings, xenos, blob, ayys have more trouble with up front damage than wall hacks and are not worse off (and none of those bar ayys are affected much by radiation)
>
Vampires have no defense against burn/rads nor do they naturally heal it. They need torpor to heal it, which not only makes them extremely vulnerable (sleep until healed) but it's also vastly slower to heal.

- Clings need to spend 2 points if they want to purge 500 rads per ability use, as well as burn being slower to heal with fleshmend compared to brute
- Ayys are organics. Radiation fucks them over like any other player and requires spending research points to be able to efficiently cleanse rads
- Blob is still able to be shot through multiple tiles. It doesn't matter if the damage is lower, you're able to damage more than 1 tile as opposed to lasering a single one
- Xenos take increased burn damage and at 15 burn, that's still 22.5 burn. A hunter and maybe a sentinel will be fine, but praetorians, queens and drones are all very slow


> The radiation should really be the bigger threat than the burn anyway to differentiate it from normal lasers and to make the wall hack not quite so awful. I dont see the problem. It's a late round weapon anyway and is almost never used due to being niche. There are plenty of counters such as just moving away, if you have a wall between them it's likely you have a good escape route. That's assuming they can even see you through the wall to know where to aim.
> 
You can easily unlock it by the 30 minute mark if toxins is done and you've still spent on a couple excess nodes prior. The issue is that fact that again, you can fire it from complete safety behind as many walls and rocks as you want. The target can't do a thing back to you unless they want to deal with absurd mutations and extra damage from radiation. Not to mention currently, if someone who knows how to do genetics is doing it, you're guaranteed to find thermals well before you unlock the lasers. Lastly, assuming you have a wall between you means you have an escape route is silly. There's plenty of winding maintenance tunnels that are still straight with tiny bends that amount to nothing, since an x-ray laser cuts through that bend and continues down your route


> If sec is shooting at you with thermals with xray guns you have either fucked up badly as a regular antag (traitor) or you are an unga antag which late round balance is not a huge fucking deal for regardless due to being probably overpowered yourself (xenos, ninja, blob, lone op lol)
> 
Tots rarely get the response. It usually comes from vamps/ayys/xenos/blobs and more rarely clings. Believe it or not though, late round balance is still important. Yes vampires can get powerful but 2 people can easily destroy one with scatterlaser or actively blocking while using a laser rifle. The fun comes from unlocking strong but **_fair_** weapons and equipment to deal with equally powerful threats. Equipment that has counterplay and requires LoS/proximity for it to work. Equipment that's both fun to use and fun to fight against.

X-ray lasers however, require nothing. Just fire it from the absolute safety of 5 walls and lmao you got yourself a walking Chernobyl who's probably mutated tourettes by now or, in the case of a xeno, probably has enough burn that if they managed to get away, require to sit on weeds for the next 10 minutes to heal back up. There's no fun from a gun that you can do fuckall against. It's **_ALMOST_** worse than cryosringe explosions and only just barely, At the very least syringe guns require you to be near the person with an unobstructed LoS.

> If this gun is so vastly overpowered why has it never been an issue? You can block the projectile with any machine or door or just move away from the source. The damage is relatively low and doesn't stun so you're at an advantage if you fight back.

If I knew I'd tell you, but I'd assume it's probably the same reason as why people haven't been doing the memestrat of 20 slug/scatterlaser speedloaders lately. Because it's not fun for either party to use unless you absolutely need to. The burn damage isn't that big of an issue for most cases, no, but it's still something to consider that it's only 5 less than a laser rifle and can still cause wounds, plus burn being slower to heal for the majority of antags is also another thing to consider or, in xeno's case, just straight up taking heavy damage because of the 50% burn vulnerability. 

The radiation though is absolutely repulsive. Have fun being quickly shot from behind a wall and then mutating and dying of tox before you realize what just happened

**Comment by YakumoChen** [comment]
>I acknowledged the request, and I'm aware that 25 irradiation per shot is silly and overkill, that's why it's 75 now, so it's 6 shots for the tox-damage to start actually killing you. I don't sit well with a gun that deals a hard-to-heal damage type, being able to be mass printed where the fix for it is only readily available inside of sleepers.

You didn't, the maintainer gave you a specific thing to go for and you completely ignored it, put in an arbitrary number, and changed the gun stats instead.

**Comment by YakumoChen** [comment]
Really not addressing the rest because almost all of it is hyperbole or completely infactual.

**Comment by YakumoChen** [comment]
@DeltaFire15 I looked up radiation code. OP is full of shit.

Let's look at the numbers:
Safe radiation: 500
Not a lot to start taking light toxin, but damage is based on radcount which means a couple shots can be shrugged off toxin wise 

Burn minimum: 1000
Four shots to start taking additional burn damage from radiation. A little worse when you have 60 maxBurn from the laser but still survivable. It's just damage so far.

Mutate minimum: 1250
It takes *5* shots to begin mutating. That's 75 maximum burn. By the time you can mutate tourette's or whatever you're really limping anyway. With a regular laser gun you'd be dead by this points or close.

Vomit / Stun min rads: 2000
This is *seven* shots. Last I did my math 7 shots puts you into critical, or very very close with some light armor on. If you are complaining about a vomit stun at this stage you are just as likely to die shortly from the radiation damage regardless and I really dont see a valid complaint about rad stuns unless you were sunbathing next to a super matter at the same time.

**Comment by kiwedespars** [comment]
forgetting the seriously difficult to heal radiation damage means that even if you escape, you still have 600 rads from just getting shot twice.

think about that for a second and then think about why that's a terrible thing to have on a 20 shot, printable weapon that shoots through walls, and can be dual wielded so you can guarantee 4 hits on someone whose unaware of you.

**Comment by YakumoChen** [comment]
600 rads is extremely miniscule toxin damage over a little bit of time before it goes back under the threshold. A single shot of vodka is enough to stave it without difficulty. I'd definitely be more concerned about the burn damage from the lasers themselves. The only serious effects start once you've taken 5 shots and by that point your health is down to a quarter - a much more serious issue than some creeping burn rad poison.

Or, of course, you'd just be crit if your """""nerf"""" goes though.

You also keep saying "guaranteed four hits" on someone but that assumes 
a) you can see them through the wall
b) you don't miss because of dual wielding accuracy
c) you actually fucking aimed right.

**Comment by ghost** [comment]
> 
> 
> Really not addressing the rest because almost all of it is hyperbole or completely infactual.

You wanted me to explain and then you dismiss everything as one or the either? Yeah, okay then.

**Comment by Poojawa** [comment]
Remember when X-ray was really just to counter blobs because see-through-wall equipment was really just a traitor or g-tech thing?

good times, good times.

**Review by silicons — DISMISSED** [review]
i'm not sure how this wasn't a problem sooner
300 irradiation under new radiation basically ensures you're dead in 5 shots unless you're a massive fuckoff powergamer with a bag of meds

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
With these changes, it still needs 7 shots (equal to 140 direct damage with the edited damage) to reach non-safe rad levels (on normal people, aka 500 rads), where you initially start to take any (pretty small amounts of) radiation damage from this, with the thresholds for special effects being much higher than this.
In my opinion, leave damage as is (so, the previous 15), and set the radiation amount applied to around 100 - 120 , which would be ~5 hits to reach unsafe levels, and a bit more than double of that to reach the mutation threshhold.
The energy cost change looks fine to me, those can shoot through walls afterall.

**Review by DeltaFire15 — APPROVED** [review]
Looking fine to me now.

**Pull request merged**
