### PR TITLE
CWC player requirement increase

### PR DESCRIPTION
**Pull request by ghost**
well basically most people dislike CWC in lowpop and it's generally unbalanced during lowpop so let's just not have it happen during lowpop. Easy fix!

:cl: 
~balance: CWC gamemode player requirement increase from 30 players to 45 players~
~balance: CWC gamemode player requirement increase from 30 players to 40 players~
balance: CWC gamemode player requirement increase from 30 players to 35 players
:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
\>45 people readying up roundstart
\>ever

**Comment by Fractious** [comment]
As mentionned by Useroth, the reason why the player cap is set at 30 is mostly due to players never readying up at round start. When we reach highpop (100+ players on Sunday) the max we'll get is 45-ish ready-up's and maybe 50. Doing this is basically the same as removing it off the rotation in all honesty.

**Comment by CozmoB** [comment]
I think its fine the way it is, i've seen lowpop wins and lowpop losses, I'd like to see some stats to make sure it is actually skewed one way or another.

**Comment by silicons** [comment]
not necessary at this time

**Comment by silicons** [comment]
actually hm

**Comment by silicons** [comment]
give me like, 2-3 days.

**Review by silicons — APPROVED** [review]

**Pull request merged**
