### PR TITLE
Improves Crew Monitoring Console Sorting

### PR DESCRIPTION
**Pull request by BurgerLUA**
[Changelogs]: 
tweak: Tweaked crew monitoring console sorting. The most damaged crewmembers are automatically bumped to the top, regardless of their rank and role.
/:cl:

[why]: Medical is extra shit when your manifest exceeds 2 pages of suit sensing monitoring. This quality of life addition should make it easier for doctors to find injured people.

### CODE REVIEW

**Comment by Poojawa** [comment]
Pics or fake.

**Comment by BurgerLUA** [comment]
> Pics or fake.

It's tested. I experimented with 3 fake humans. Spawning 3 of them and giving them jumpsuits was a bitch so I didn't do anything more than that.

If you can suggest an easy way to mass spawn 20 humans with random jobtypes and random suit sensors, I will provide pics.

**Comment by Poojawa** [comment]
> populate world

**Comment by BurgerLUA** [comment]
> > populate world

https://i.imgur.com/xnQ5bFQ.png

**Review by silicons — APPROVED** [review]

**Pull request merged**
