### PR TITLE
Make the radiation hardsuit a voidsuit instead

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
This change the radiation hardsuit that I added into a radiation voidsuit,
The main differences being the lack of helmet light (already done, so no changes there), the lack of a retractable helmet and the addition of the helmet in the Radiation Hardsuit crate, now renamed Radiation Voidsuit crate.

## Why It's Good For The Game
I was told it look more like a softsuit or a voidsuit than a hardsuit, and I agree with that, so it is now a voidsuit, like the NASA Voidsuit or the EVA Space Suit.

## Changelog
:cl:
change: Made the radiation hardsuit a voidsuit and added the helmet in the crate
/:cl:

### CODE REVIEW

**Comment by you-cant-stop-nico** [comment]
shoveldog

**Comment by you-cant-stop-nico** [comment]
shoveldog

**Comment by you-cant-stop-nico** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by you-cant-stop-nico** [comment]
shoveldog

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
