### PR TITLE
[READY] for Z debug. Industrial lift (not shuttle edition)

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
***Ports [TG#52397](https://github.com/tgstation/tgstation/pull/52397)***

[(spoiler) I try make something like this Hydraulic Industrial Lift](https://camo.githubusercontent.com/6baa298e032ae97ec8e5faf92be04e5c44950913fd58e3c11c47cc912a87d1e1/68747470733a2f2f352e696d696d672e636f6d2f64617461352f51482f544f2f4d592d322f3934352d353030783530302e6a7067)
[(spoiler) Or scissor lift](https://camo.githubusercontent.com/306c980d77e3cd7dce27faf02b1f13f026ad026a78cd3ce2884c64949887a9ed/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f362f36322f48656265627565686e655f53636973736f726c6966742e6a70672f33303570782d48656265627565686e655f53636973736f726c6966742e6a7067)
Catwalk + Ladder + rolling_table = lift

Seems like it work now.

Ideas are welcome.

TODO:
Make something like lift control panel, console, controller. Now it controlled from platform.

## Why It's Good For The Game
Lifts cool.

## Changelog
🆑
add: Lift platform that works like moving catwalk
add: Lift now on MultiZ debug station
tweak: Snaxi is now a single map file.
fix: Fixed a bad areastring path on an apc on snaxi.
fix: Fixed a runtime on tcg cards book.
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
One step closer to tram station :)

**Comment by TripleShades** [comment]
If I'm reading the cl correctly, does this imply multi-z maps will no longer be a pain to work on in the back? Or less of a pain/groundwork for better support?

**Comment by SandPoot** [comment]
This doesn't really touch z-levels, it adds a funny moving platform that on tg is now the base for the tram.

**Comment by deathride58** [comment]
Mirroring the screenshots from our PR to Sandpoot's PR: Here's what Snaxi's shaft miner office and outpost look like now!

image
image

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
