### PR TITLE
CAPTURE THE FLAG NOW HAS CLAYMORES 

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

title
also ctf people get high punch damage.

## Why It's Good For The Game

MELEE SQUAD

## Changelog
:cl:
add: CTF CLAYMORES
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
Speedmerge

**Comment by YakumoChen** [comment]
I thought the rifles already melee killed though?

**Comment by ghost** [comment]
25 PUNCH DAMAGE

**Comment by Ghommie** [comment]
The deagle already deals bout a whoppin 75 damage. These claymore don't have much of a purpose beside shielding. the other changes are fine though.

**Comment by silicons** [comment]
@Ghommie c'mon man what's more fun, pistol whipping someone or swording them :^)

**Comment by Ghommie** [comment]
A two-handed (duh) death sentence zweinhanders would be neat. I think I even saw the sprites on some HRP codebase such as Aurora time ago.

**Comment by Linzolle** [comment]
zweihander WOULD be sick as fuck...

**Review by Ghommie — APPROVED** [review]
Lazy.

**Pull request merged**
