### PR TITLE
Revert "Unironically adds elf ears"

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Reverts Citadel-Station-13/Citadel-Station-13#8276
[Why]
Fucken elf shit.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Bhijn must have pressed the wrong butten on the merg

**Comment by Poojawa** [comment]
but y tho.

**Comment by Useroth** [comment]
around elves watch yourselves

**Comment by deathride58** [comment]
Nah

**Pull request closed without merging**
