### PR TITLE
Ports/Adds new Berets for most heads and departments

### PR DESCRIPTION
**Pull request by Xantholne**
Ports some berets adds even more to most jobs

## About The Pull Request

Ports some berets from Paradise (I believe ported from elsewhere) as well as adding some new ones created by myself. New berets include
Cap, HOP, HOS, Warden,  CMO, Med, Chem, Viro, Robo, Sci, Atmo, Eng, Ce. 
Heads will find their new berets in their lockers, the rest will be found in those specific autodrobes for those jobs

## Why It's Good For The Game

This adds more player style choice for what exactly they wish to wear for outfits providing more variety since there does not seem to be a lot of head wear that is rather unique or something palyers would want to wear

## Changelog
:cl:
add: New Berets for most heads and departments available in their autodrobes or lockers
/:cl:

dreamseeker_tKyMo8IbRO

Top row left to right
HOS, Cap, HOP, Standard Purple, Standard Blue, Warden, CMO, Med, Chem, Viro, Sci, Robo
Second row
Atmos, Engi, Ce

No on mob picture since for some reason my uniforms are invisible and not really letting show how they match ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by Ghommie** [comment]
> No on mob picture since for some reason my uniforms are invisible and not really letting show how they match ¯\\_ (ツ) _/¯

Perhaps delete the .rsc file in your base repository and recompile. I had this sort of issue in the past when testing uniforms on a female character and doing that did the trick for me.

To explain, female onmob uniform icons are generated by blending the standard onmob uniform with another mask icon_state, effectively removing some pixels around the waist and torso.
Then in order to save CPU and memory, these new icons are copied in the rsc file and stored in global lists to be reused later.

Also merge conflicts.

**Comment by PersianXerxes** [comment]
I thought there was a mistake here and was gonna point out some of those jobs already have berets, thanks for including the picture to clear that up.

The white captain's beret is sexy, and with it the captain only needs a white cloak to match the parade tunic. :3

**Comment by Xantholne** [comment]
> > No on mob picture since for some reason my uniforms are invisible and not really letting show how they match ¯\_ (ツ) _/¯
> 
> Perhaps delete the .rsc file in your base repository and recompile. I had this sort of issue in the past when testing uniforms on a female character and doing that did the trick for me.
> 
> To explain, female onmob uniform icons are generated by blending the standard onmob uniform with another mask icon_state, effectively removing some pixels around the waist and torso.
> Then in order to save CPU and memory, these new icons are copied in the rsc file and stored in global lists to be reused later.
> 
> Also merge conflicts.

Will have to do later.
And yep, gotta fix that later. Haven't done merge conflicts in 2 years 3? idk maybe not even. Was going to have kevin help me sort that out real quick later.




> The white captain's beret is sexy, and with it the captain only needs a white cloak to match the parade tunic. :3

Might do, 100000% designed to work wit the white Star Trek TOS uniform and jacket in mind. That white is so attractive and the currents are so off-putting to me.

Need to update the CMO labcoat though since it uses an older model that is quite grimey and not as as matching to the beret as it was on another server I had originally made it for.

**Comment by Ghommie** [comment]
You need to pull from upstream/master in order to resolve the conflicts, not your remote origin / branch.

**Comment by Xantholne** [comment]
Reopening on another branch since I hecked this one somehow

**Pull request closed without merging**
