### PR TITLE
We hate powersinks

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

Ok jokes aside, this adds a loud beep to the powersink and increases the light it gives off a bit more.  In turn the power consumption was raised from 2mj to 2.5mj.

## Why It's Good For The Game

Not being able to find a power sink for most of the round is awful.  People get it for free as an objective.  And with a recent change it takes 33+ minutes to explode which is insane.

## Changelog
:cl:
add: Adds a constant beep to the power sink as long as its on
balance: increased the light from 5 to 8 for powersinks
balance: increased the power consumption from 2mj to 2.5mj to make up for the beep and extra light.
/:cl:

### CODE REVIEW

**Comment by Putnam3145** [comment]
could buff the power consumption even more than that tbh, or just as good, remove the dang objective

**Comment by YakumoChen** [comment]
33 minutes to detonate (at 1MJ/s) is fine considering before it was *3 hours*

You can see my reasoning for the time in my last PR, and the PR that forced me to make said PR. 
To be clear, the only reason it has an explode condition is so that engineering can't just wire to grid and forget about the sink. It is not supposed to be bought to act as a bomb, that is simply a condition of ignoring looking for it.

**Comment by YakumoChen** [comment]
Actually considering it was _you_ whose PR that was I made a counter to, and considering MY PR was merged over yours, I think you need to stop whining about the time it takes to explode it.

Coming from the coder that tried desperately to over-nerf it last time **I find this PR in pretty bad faith.** It's not that hard to find.

**Comment by keronshb** [comment]
> 
> 
> could buff the power consumption even more than that tbh, or just as good, remove the dang objective

So what about 3 or 3.5MJ?

I'm heavily considering removing the objective because haha free powersink, but I want to replace it with something because we're really starting to lose diversity in objs.

**Comment by dzahlus** [comment]
> could buff the power consumption even more than that tbh, or just as good, remove the dang objective

I'd agree but we have too little ANTAGONIZING objectives, honestly this one doesn't antagonize me either, I just feel trolled.

> 33 minutes to detonate (at 1MJ/s) is fine considering before it was _3 hours_
> 
> You can see my reasoning for the time in my last PR, and the PR that forced me to make said PR.
> To be clear, the only reason it has an explode condition is so that engineering can't just wire to grid and forget about the sink. It is not supposed to be bought to act as a bomb, that is simply a condition of ignoring looking for it.

Yes but making it actually explode in a reasonable time is good, because if you are unable to find it after 10 minutes it's just shuttle call "We can't find the sink I want to go home". This gives a punishment for not finding it, and hopefully reduces the cancerness of this objective in terms of "oh boy I already want to go home"

**Comment by DeltaFire15** [comment]
Personally I don't think this is really needed. Maybe sliightly increase possible power drain (which is a negative to the sink because it means it can go boom faster if the grid is being overcharged by engi), but doesn't really need a beeping aswell.

**Comment by keronshb** [comment]
> 
> 
> Personally I don't think this is really needed. Maybe sliightly increase possible power drain (which is a negative to the sink because it means it can go boom faster if the grid is being overcharged by engi), but doesn't really need a beeping aswell.

It needs the beeping sound or the objective needs to be removed because it's awful to deal with it.

**Comment by shellspeed1** [comment]
Sinks are fine. There are tools to help find them such as X-ray eyes. There are also solutions to the problem that no one considers such as isolating the power net to narrow down where it might be or swapping cells out on apcs for critical areas and cutting them from the grid in order to get power running. Even than  you could outpower the thing fairly easily if you know what you are doing by simply hooking in a few pacmen. I would argue the issue here is lack of coordination and teamwork to fix the problem as everyone just goes unga, find sink.

**Comment by keronshb** [comment]
This is my alternative #14204

**Comment by keronshb** [comment]
Other PR got merged, no need for this one.

**Pull request closed without merging**
