### PR TITLE
[Atomic] Cargo rework - Mat selling nerf, addtion of grater gear to sell MK I

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Nerfs all mat selling by 50% or more
Nerfs all bountys by a factor
Makes spare bountys give more
Adds all clothing to be sellable for small credits
Increases the price of almost every crate
Makes almost all weapons sell
Makes almost all gear sell
Makes most larger objects/stock parts sell
Makes almost all medical gear sell
Adds a tactical turtle neck and suppresser into the contraband pack
## Why It's Good For The Game

ATM cargo is rather relent on one thing, miners getting 400 plasma this is dumb.
By making mats sell for ***much*** less we make it so that them being made into cargo exports will be better then selling raw. Increasing the price of things makes cargo not as well snowball into having swat/spin disks and MASON rigs, but will still have to work for it.

# Any questions or such can be asked on Discord to @Trilby on development discussion main

## Changelog
:cl:
add: Almost all clothing and most weaponds can be sold for pocket change
tweak: Cargo costs of packets and selling 
balance: Lowered mat selling as well as most if not all bountys
code: Adds more files for easy finding/adding in packs
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
>reducing tesla bounty

ok

**Comment by Trilbyspaceclone** [comment]
This is ready for merge.

**Comment by davidchan13** [comment]
Is botany ever going to get to sell produce again?

**Comment by Trilbyspaceclone** [comment]
They already can

**Comment by davidchan13** [comment]
All produce has a price of 0 as of last time I played around with it, only bounties and materials like wood or metal rods can be sold for a profit.

**Review by silicons — DISMISSED** [review]

**Review by silicons — APPROVED** [review]

**Comment by Arturlang** [comment]
A lot of spelling errors, would be worth going through kelpers fixes

**Pull request merged**
