### PR TITLE
Digitigrade suits

### PR DESCRIPTION
**Pull request by Poojawa**
:cl: Poojawa
add: Added Digitigrade versions of everything appliciable in suit.dmi
imageadd: Snowflake Icons weren't modified, and were given NO_MUTANTRACE_VARIATION
/:cl:

### CODE REVIEW

**Comment by nik707** [comment]
finally the lizard-flakes can look proper

**Review by deathride58 — APPROVED** [review]
The hero we want but not the one we deserve

**Comment by Poojawa** [comment]
I probably missed a few west facing sprite edits, but with over 200 sprites changed and all of them by hand over several sessions, wew. Just report 'em as needed and I can fix. it's usually as easy as copying east, clicking over to west, paste, save. done.

**Comment by deathride58** [comment]
No major bugs reported during the testmerge. LGTM

**Pull request merged**
