### PR TITLE
Replaces plasma in execution syringes with amatoxin

### PR DESCRIPTION
**Pull request by Hatterhat**
holy shit what a meme

[Changelogs]:

:cl: Hatterhat
tweak: The plasma formerly present in some execution syringes was replaced with amatoxin.
/:cl:

[why]: #7128 is a fucking mistake.

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
Is this the part where we post the screenshots of you under it's effects?

**Comment by Hatterhat** [comment]
Not at all, no.

**Review by silicons — CHANGES_REQUESTED** [review]
Make a variant of plasma that isn't mutative.

**Comment by Hatterhat** [comment]
@kevinz000 i got lazy and swapped it out for something different

**Comment by Dankseed** [comment]
obvious salt pr, something something code around something admin level.


Always knew you were on Citadel for a reason. :^)

**Comment by Hatterhat** [comment]
@Dankseed delet this

**Review by Cw3040 — COMMENTED** [review]
s/intropidril/chloralhydrate please

**Comment by deathride58** [comment]
Ready for merge?

**Comment by Hatterhat** [comment]
fuck if i know lmao i forgot this thing existed

**Review by silicons — APPROVED** [review]

**Pull request merged**
