### PR TITLE
@kevinz000

### PR DESCRIPTION
**Pull request by Hatterhat**
this one's not gonna get merged chief you mark my mf words

### CODE REVIEW

**Comment by Putnam3145** [comment]
approved. accepted. can't argue with the facts

**Comment by Ghommie** [comment]
Truth.

**Comment by ghost** [comment]
merge pls

**Comment by YakumoChen** [comment]
Speedmerge

**Comment by Arturlang** [comment]
Kebinz on leave.... So itll never get merged

**Comment by Linzolle** [comment]
joke pr

**Pull request closed without merging**
