### PR TITLE
Lowers the slowdown on snow tiles

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

2 slowdown has been shifted to 1.5 making you only have to deal with a bit more then plasmamen slowdown

## Why It's Good For The Game
Makes mining and dealing with the snow tiles/mobs on tiles less of a hassle were you can perhaps maybe run away from things, or get some distance! 

## Changelog
:cl:
tweak: makes snow tiles no longer force you to go at slowdown 2, but slowdown 1.5 meaning your 50% faster then before on snow!
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
I know mobility plays a big factor in combat, but the slowdown is also what make snowy enviroments extra challenging. That said, I am mostly fine with the current situation, except shoveling snow tiles should clear most of their slowdown... but that's just one of many suggestions.

**Comment by Trilbyspaceclone** [comment]
doent shoveling already set it to 0 slowdown do to setting it to a different tile?

**Comment by Ghommie** [comment]
Umh, good to know.  A speed nerf to the fauna would be better solution.
By the way something tells me simple mobs don't give a heck about turf slowdowns due to how Goto() works, but I'll have to check.

**Comment by Trilbyspaceclone** [comment]
Mobs do not care about slowdown iirc and thats why the ice shard thingy and volfs/bears are so damn fast. Makes it almost impossable to really get away from them if you flat out run away and cant really get behind walls or such

**Comment by silicons** [comment]
it would be better to make mobs care about slowdowns than make the slowdowns less, tbh.

**Comment by silicons** [comment]
i don't particularly like the super high slowdown but if this is about mob combat i really do not like lessening it when we have a far better option

**Review by silicons — CHANGES_REQUESTED** [review]
... 
1.5 for now, instead of 1.3
we need to probably do something about mobs sometime(tm).

**Pull request merged**
