### PR TITLE
ORM Security.

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
Ore Redemption Machines have been moved to more publicly accessible areas on Box and Delta stations. All stations now have a Mineral Storage locked windoor in front of the ORM. Also moved the Cargo Protolathe into the mining dock on Box because Miners kept breaking into the cargo bay to grab shit on high pop rounds.

:cl: ORM Movement
tweak: Box Station ORM Moved to 2 tiles south of Cargo Office Door.
tweak: Delta Station ORM moved to the southernmost window of Cargo.
tweak: Box, Delta, Meta stations now have Windoors with Mineral Storage access blocking them. 
/:cl:

[why]: Because originally, people were moving the ORM to break into cargo. An earlier PR overcorrected and removed ORM access to anyone but cargo. Hopefully this works better as a middleground.

### CODE REVIEW

**Review by ZeroNetAlpha — COMMENTED** [review]
Wait why are there so many file changes... wtf?

**Comment by ZeroNetAlpha** [comment]
Well, I mean, it SEEMS to work on local testing. Nothing game breaking or anything missing. Still, that's new to me.

**Comment by Poojawa** [comment]
you didn't prepare your map before you started editing

Mapmerge in the tools folder, just read the readme.mds

**Comment by ZeroNetAlpha** [comment]
Will try this again properly.

**Pull request closed without merging**
