### PR TITLE
Removes blood drunk miner from the game

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

As title. Can still be spawned by admins, but please don't.

## Why It's Good For The Game

Whoever wrote the BDM code doesn't know how to code and whoever approved it doesn't know how to read code. The entire architecture of its AI is literally the worst possible. Nobody with any performance sense at all looked at this code before it was put into production on TG. I am extremely mad.

## Changelog
:cl:
del: blood drunk miner
/:cl:

### CODE REVIEW

**Comment by LetterN** [comment]
caused by this? 
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/90bdd55319b84d9877ceb709852dcb1639d2c64d/code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm#L170-L183

**Comment by Putnam3145** [comment]
yes

**Comment by Solaris-Shade** [comment]
Would it be better to comment out the blood drunk miner locations?
That way it is still in the code to be coded in a more sane way in the future and not hinder the server while it is in a shit code status.

**Comment by shellspeed1** [comment]
I highly recommend moving some of the loot from blood drunk mjner than. I previously moved the ka design disks from tendrils to blood drunk to give mining more progression. If we cannot kill blood drunk its impossible to get said disks. Of additional note, the trophy blood drunk is considered to be invaluable for crusher mining. One last thing, if blood drunk is a problem the ice miner might also need to be checked. If they aren't an issue could be possible to just swap them in and call it good.

**Comment by Putnam3145** [comment]
> 
> 
> Would it be better to comment out the blood drunk miner locations? That way it is still in the code to be coded in a more sane way in the future and not hinder the server while it is in a shit code status.

since we have version control (i.e. git) commenting out is pretty much pointless. this is literally what i have done in this PR anyway

**Pull request closed without merging**
