### PR TITLE
Ports #41638 and #43784, "Wizard Shapeshift now converts damage taken while transformed"

### PR DESCRIPTION
**Pull request by YakumoChen**
credit 4dplanner and MMiracles

## About The Pull Request

Wizard's transform spell no longer gives them full heals. Also ports some fixes to damage conversion to make it less shit.

## Why It's Good For The Game

ided
Wizard shouldn't get free heals with a spell that already gives them pretty good bonuses.

## Changelog
:cl: 4dplanner, MMiracles
tweak: Wizard shapeshift now converts damage taken while transformed
fix: transform spell transfers damage correctly instead of healing most of the time
fix: 0% simplemob health maps to 0 carbon health, 100% simplemob to 100% carbon
fix: transforming to a form with brute resistance no longer heals you
fix: transforming back to a species with brute resistance no longer heals you
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Well it doesnt compile. Lovely

**Comment by Putnam3145** [comment]
you replaced damage with damage_amount in the damage proc's body without changing it in the argument list

**Comment by BlackMajor** [comment]
If you can get this functional I'm down for it.

Make sure it works for ash drake transformation too.

**Comment by YakumoChen** [comment]
I have no idea what these codey explanations mean

**Review by silicons — APPROVED** [review]

**Review by silicons — APPROVED** [review]

**Pull request merged**
