### PR TITLE
Adds obscured slots and TRAIT_NODROP checks to the outline system

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title.

## Why It's Good For The Game
Oh right, we have those, it's good to let the player actually know.
XzQho4p4lh

## Changelog
:cl:
tweak: If your clothing is being blocked by something else (like a hardsuit) the outline will be thicker.
tweak: If you simply can't remove/drop the item too.
tweak: The outlines are thicker if you cannot interact with the item.
/:cl:

### CODE REVIEW

**Comment by keronshb** [comment]
I put my outlines to red by default so I'm not sure if this would help me

**Comment by SandPoot** [comment]
I mean, the default system already uses this for if the user is incapacitated

**Comment by Solaris-Shade** [comment]
Is there a way to have the highlights at different pixel thickness?
I ask because deuteranopia (red/green color blindness) makes telling the highlights apart difficult.

Overall I love this PR! UI upgrades are always welcome!

**Comment by SandPoot** [comment]
There actually is a way, but i can't do it right now, I'm not at my computer.

**Comment by SandPoot** [comment]
Working on it

**Comment by Solaris-Shade** [comment]
Visually distinct from one another without relining on any color input or prior player assumptions. Feels fantastic.

**Pull request merged**
