### PR TITLE
Gives corpses an important scientific use

### PR DESCRIPTION
**Pull request by silicons**
Miasma specific heat reduced to an absurdly low value
Miasma fusion power increased to an absurdly high value
Enjoy, science mains.

### CODE REVIEW

**Comment by Poojawa** [comment]
???? y tho

**Comment by lolman360** [comment]
Miasma was not intended to be useful. It was created as an incentive to bodybag/morgue corpses and clean up monkies from xenobio.

**Comment by lolman360** [comment]
>specific_heat = 0.00001

alright i'm pretty sure this PR is a joke

**Comment by Poojawa** [comment]
https://www.youtube.com/watch?v=MzKlmNLTkXM

**Review by deathride58 — APPROVED** [review]
[LAUGHING IN HYPERNUKES]

**Comment by lolman360** [comment]
i want to tc trade to remove the bomb cap for 1 bomb

**Comment by nik707** [comment]
I mean... Bhijn said yes :v)

**Pull request merged**
