### PR TITLE
Adds Pride Month as a holiday!

### PR DESCRIPTION
**Pull request by deathride58**
Title. Does exactly as it says on the tin! As an added bonus, assistants during pride month will spawn with rainbow jumpsuits/jumpskirts by default (though this does not take priority over loadouts or the grey jumpsuit config option)
Since I happen to be omnisexual, panromantic, bigender, and intersex (yeah, it's a lot of boxes ticked, I know!), I figured I'm probably someone that would be able to treat this holiday with the proper respect that it deserves. I was thinking of adding more LGBT-related holidays, such as Asexual Awareness Week, National Coming Out Day, Intersex Awareness Day, the Stonewall Riot Anniversary, Transgender Day of Remembrance, or Transgender Awareness week, but I figured it'd probably be best to stick with the most recognizable and most widely-celebrated holiday for the sake of portability (for codebases interested in porting), along with avoiding stirring the pot *too* much (There are a *lot* of channers and other assorted edgelords in the SS13 community, so I don't want to spark any massive riots, lol)

## Changelog
:cl: Bhijn
add: Pride month has been added as a holiday!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
@deathride58 make every vendor have a rainbow overlay now that we have vendor economy and have to spend 500$ for a single shirt

**Comment by KingTerrytheTerrible** [comment]
holy shit it's pride month not pride year

**Comment by Poojawa** [comment]
this is a lot better than the gender fluid idea. lol

**Comment by lolman360** [comment]
make them psychedelic jumpsuits not rainbow ones

**Comment by YakumoChen** [comment]
I don't really mind having more holidays but can you not just put it in the roundstart message like everything else?

 Forcing every assistant into ugly jumpsuits for an entire month is hugely pushing it, and Obligatory Everything Must Be Rainbow Month is already annoying as it is.

**Comment by Trilbyspaceclone** [comment]
How does the game handle overlapping holidays?
Will fathers day take over for the day on pride month or will the game use pride month over fathers day?
Do they act as both?

**Comment by YakumoChen** [comment]
If there's two holidays on a certain day it just displays both.

**Comment by Trilbyspaceclone** [comment]
Neat! Thats really good, was fearfull that other holidays would get shadowed

**Comment by KathrinBailey** [comment]
"Trans Rights" prefix would be pretty neat.
It'll disjoint the name but trans rights.

**Comment by BobJoga** [comment]
Finally, [BRAND] month

**Comment by ShadeAware** [comment]
Ah yes, here at [NANOTRASEN] we value the continued acceptance of our [EMPLOYEES] and their choice to be [SEXUALITY].

**Comment by ShadeAware** [comment]
Also forcing clothes on people for a holiday they probably aren't really identifying with is a pretty big 😬 , but the actual idea of having it is pretty nice.

**Comment by BobJoga** [comment]
This is a fine PR aside from the jumpsuit memery, despite my personal grievances about how pride month is just used as a marketing stunt.

**Comment by deathride58** [comment]
~~@YakumoChen~~
> ~~I don't really mind having more holidays but can you not just put it in the roundstart message like everything else?~~

~~I'm not reworking the way holidays get announced roundstart just to appease one single person, lol.~~ (EDIT: ah, i misread. disregard)

Also, for those legitimately pissy about rainbow jumpsuits, you can bypass that by just choosing a gray assistant jumpsuit (or any other uniform of your choice) in the loadout. I find it pretty hilarious that people are actually pissed about that despite the workaround being so easy

**Comment by ghost** [comment]
delete this

**Pull request merged**
