### PR TITLE
[Ready] Makes small chocolate have aphro in it

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Adds one u of aphro to small chocolate candy
[why]
~~Memes~~ Love is in those!

### CODE REVIEW

**Comment by Tupinambis** [comment]
Bad post OP

**Comment by Ragolution** [comment]
no please

**Comment by Trilbyspaceclone** [comment]
> no please

I thought you wanted this on discord...

**Comment by RogueSteampunker** [comment]
small chocolates, as in the ones in heart boxes? cause if I'm understanding that right, xenobio can and will be able to mass produce aphro.

take that as you will.

**Comment by Trilbyspaceclone** [comment]
> small chocolates, as in the ones in heart boxes? cause if I'm understanding that right, xenobio can and will be able to mass produce aphro.
> 
> take that as you will.

Is supper easy to make basic aphro, and only get 7u per box, your more likely to get cakes and metal cups like silver and gold...
And sci can make a chem dispenser and then make it faster and more of it almost at round start

**Comment by Ragolution** [comment]
CANDY HEARTS AREN'T THE SAME AS CHOCOLATE

**Comment by JogBoba** [comment]
I like this honestly, it feels like a good meme.

**Review by silicons — APPROVED** [review]

**Pull request merged**
