### PR TITLE
Blood Red Slimes + Crossbreeds

### PR DESCRIPTION
**Pull request by Seris02**
## _**This is probably not complete yet, feel free to give suggestions, codewise and featurewise.**_

Blood red slimes:

blood red extract:
- reacts with plasma: 1 in 140 chance of spawning 1-5 tc
- reacts with blood: spawns a blood red baby slime
- reacts with water: spawns an armor potion, which increases melee armor of a piece of clothing up to 50 melee

existing crossbreeds, blood reds:
- burning: creates an invisibility cloak that changes the users alpha value to (random 5-40) every 1-5 seconds
- charged: creates a slimy whetstone which can increase the damage of a weapon by 7 up to a max of 60 damage (one use, like normal whetstone) eg, it won't increase the damage of a weapon past 60
### THESE WHETSTONES ARE ONE PER ITEM
- chilled: makes the user *very close* to invisible for 10-15 seconds
- stabilized: makes the user take 50% less blood loss and stamina damage
- industrial: 1 in 150 chance of spawning a telecrystal for every 10 units plasma injected
- consuming: the cookies give you short adrenals

TREACHEROUS EXTRACTS (act like knives, basically, combat or deception based, each deal 5-7 brute per hit regardless of effect, has an 8% chance of stabbing you instead):
- grey: 2 uses, 30-40 clone damage on hit
- orange: 3 uses, sets target on fire and increases internal temp by 40 kelvin
- purple: 1 use, fully heals target then deals 50-60 toxin damage
- blue: 10 uses. slips people. yep.
- metal: 1 use, covers target in a ring of walls, 10% chance they're reinforced walls
- yellow: 2 uses, electrocutes target for 30-49 burn damage
- dark purple: 1 use, spawns 57 moles of plasma at 295 kelvin, then lights it on fire
- dark blue: 2 uses, freezes the target in a block of ice
- silver: 3 uses, adds 450 nutrition on hit
- bluespace: 1 use, picks an organ if the damage zone selected has organs, then checks if it is a vital organ. 
1. if it is, deal 50-60 organ damage to an organ there, then spawns a clone of that organ somewhere on station
2. if it isn't, fucking yeets the organ out of their body *no more eyes for you!!*
3. if there are no organs in the area selected, teleports their fucking bodypart away eg arm
- sepia: 3 uses, snapshots the target's direction and position and reverts them back there in six seconds
- cerulean: infinite uses, when you stab someone, they will be stabbed several more times at random intervals over the course of three minutes or so by invisible knives
- pyrite: 5 uses, gives the target blood cult eyes and a blood cult halo, *time to frame a blood cult yeet*, wears off after 100-150 seconds
- green: creates a pair of slimeboots on the target, 2x slower than magboots for 20 seconds
- red: infinite uses, like gloves of north star, but a knife
- pink: 3 uses, makes the target ***SUPER FUCKING DEPRESSED***
- gold: 3 uses, creates a copy of the target that chases after them and tries to kill them
- oil: 1 use, lathers over the target and explodes in 0/0/3 after 5-15 seconds
- black: infinite uses, deals 5-7 extra damage to target and heals the user by the same amount
- light pink: 4 uses, gives the target 10 pax
- adamantine: 2 uses, strips the target's suit, helmet and uniform of all armor
- rainbow: 3 types:

1. damage - 10 uses - deals random brute, burn, toxin, clone, brain or rad damage
2. mulligan - 1 use - mulligans the target
3. slime effect - 1 use - does a random treacherous extract's effect

An extract is role restricted to scientists in the uplink for 2 TC.

## Why It's Good For The Game

Because... slimes. Also, I think it would be fun for people and add quite a bit more to traitor xenobio than just trying to buff the shit out of yourself with stabilized extracts.

## Changelog
:cl:
add: Added blood red slimes + extracts + crossbreeds
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
I have to disagree with the repeatable whetstone, that's just a bit too good.

**Comment by lolman360** [comment]
>generates tc
>+armor for any clothing
>+7damage whetstone

these are just the most hilariously broken (op) effects, things like treacherous black/red are also pretty good

don't say it's balanced because it's a low chance tc are limited for a reason

considering all you need is 10 gray extracts, a monkey and a syringe to make a reprouctive br, then monkey cubes (which you can get from pub biogen or just grey slimes since you're a scientist) to make more, yes. It is piss easy to mass-produce these.

**Comment by Seris02** [comment]
This is why I said suggestions are fine. Please, if you're gonna shit on the PR, at least tell me how to improve it. Also, the slime whetstone isn't repeatable anymore.

**Comment by lolman360** [comment]
i'm listing what i find problematic.

anyways, 7 damage is more than the limited availability chef whetstones which add 5. imo it should be like 2-4, not more than 5

**Comment by MrJWhit** [comment]
It's repeatable because you can just make more of them, that's my problem. Once you get to the point in xenobio where you can make one yellow slime, you can make fifteen no problem and that's the problem. It's not the first whetstone, it's the tenth.

Maybe make it so that it has a teslum/teslacoil-esk effect when activated, shocking people around an X radius? With some stuns thrown in for good measure.

**Comment by Seris02** [comment]
No, you can't use whetstones more than once on anything, not even normal whetstones. Also, maybe. I might play around with the tesla effect.

**Comment by MrJWhit** [comment]
Ah, ok, time to _sharpen individual 10mm bullets_ then.

**Comment by lolman360** [comment]
or shurikens

**Comment by dapnee** [comment]
Raise the TC price, 13-15. You’re making an item that can become its own surplus crate, even if it “takes time”.

**Comment by MrJWhit** [comment]
I don't think it should go above the 10TC price, the major downside to reproducing it, is that if anyone sees it, they're going to be able instantly know what's going on.

**Comment by dapnee** [comment]
The blood reaction means reproducing this slime is ridiculously easy, and I doubt it can split into different colors. Extract numbers would exponentially increase as they are killed. And yeah, of course everyone would know what they’re doing if they saw it, but no one normally checks on xenobiologists, and a majority of the time, those players have made walled areas you’d need to view through cameras. Not to mention, they are only a shade darker than normal red slimes, some people are colorblind and even I have trouble denoting the difference between silvers and metals thanks to the lighting.

**Comment by xurxomario** [comment]
At least the TC gen works by chance and youd need a fair lot of plasma to generate what would be basically pocket change in tc, however some of the effects are just a tad much, namely the water reaction and the grey crossbreed, 30-40 clone damage is quite a lot. Also cerulean crossbreed sounds a tad too good as well.

Oh and also, a quick edit, recurring crossbreeds, sound hilariously broken if you can manage to get a few of em, that would generate TC a tad too reliably.

**Comment by Seris02** [comment]
thanks for the comments so far, Imma edit stuff so it's not so
powergame

**Comment by YakumoChen** [comment]
Looks about as overpowered as mass produced null crates. Disgustingly overpowered. This is for a job that usually has almost no oversight and is rare to see more than one person in the room at any given time.

Generates TC, can make any sharp weapon a 2 shot (this will also make delimbs hilariously easy), and can make weapons that are mostly 2-3 shot kills. Not to mention printable adrenals or flat invisibility.

**Comment by Seris02** [comment]
I'm just gonna fix this all and nerf it a bit after I do archivists

**Pull request closed without merging**
