### PR TITLE
Eldritch Affairs

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

20 TC items to make traitor chaplains into neutered versions of cults. 
They can not be deconverted via holy water.

Cult:
Can not use convert/sac rune
Can not use soulstones
Can not summon Nar'sie
Can not summon ghosts.
Can not twisted construction cyborgs, blood beam, or shuttle curse.

Clockcult:
Vitality matrices are neutered
Can not make conversion runes
Can not ascend to Reebe

## Why It's Good For The Game

Fun snowflakey traitor chaplain fun thing that I'm sure won't go wrong :)

## Changelog
:cl:
add: Traitor chaplains can now become neutered versions of cults.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Not curator as well?

**Comment by Detective-Google** [comment]
> Not curator as well?

ye

also chap has his grace can't be worse than le ebin murderbone weapon tbh except >>>>>>>>>>>>>>>>>>>>>>>>>>>>>chaplain with 4 stunhands 😂  🔫

**Comment by Arturlang** [comment]
Lets see how this one goes, though sad the ability of summoning ghosts was removed.

**Comment by KeRSedChaplain** [comment]
About the `...golden tendrils of light latching onto you.` part, I feel like this should say `A purple tendril of smoke crawls out from (the slab) and (something to do with interacting with your brain)!` or similar, since if we want to be """""lore""""" friendly with it Sevtug would be the one to do this kinda thing since his role as a general is dealing with minds and brain activity.

**Comment by Ghommie** [comment]
By the by, Can you make this feature work without handing out the clockwork/blood cultist antag role to the user? It's a tad annoying.

**Comment by silicons** [comment]
@Ghommie unfortunately not really because most of the abilities kiiinda are "hardcoded" to REQUIRE an antag datum =|

unless you mean something else? like not making a team?

**Comment by Ghommie** [comment]
Well then, I guess you should make the neutered antag datum not prompt the team objectives nor display them in the EOR report, as well as having a different antag hud icon so we understand they are actually a traitor.

**Comment by silicons** [comment]
aight bet

**Comment by Ghommie** [comment]
Knock knock?

**Comment by silicons** [comment]
done but probably needs a testmerge

**Comment by Featherfield** [comment]
Actually interesting chaplain traitor gimmick? count me in my dude pal guy.

**Comment by SomeguyManperson** [comment]
if you want to make sure neutered cults can't convert don't forget the mania motor's conversion effect

**Comment by Ludox235** [comment]
> 
> 
> if you want to make sure neutered cults can't convert don't forget the mania motor's conversion effect

Well, mania motor needs 2 invokers and clockwork marauders don't count as a cultist in the slab. So it's impossible to get a mania motor in the first place. (I tried it)

**Comment by Ghommie** [comment]
Conflicts, also there are three or four runtime errors with the neutered blood cult antag datum you may want to check (I did not screenshot nor read them carefully so I can't provide more infos, sorry)

**Comment by Ludox235** [comment]
Give the blood cult variant the ability to do the apocalypse rune but at a very big price aka like losing a shitton of blood or having everyone know where you're drawing it or smth

**Comment by silicons** [comment]
working on this in a bit

**Comment by silicons** [comment]
@Ghommie runtimes fixed

**Comment by Ludox235** [comment]
@Ghommie Hello??? please??? I need my eldritch affairs mr coder man :/

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
