### PR TITLE
Moves variable definitions to their object definition

### PR DESCRIPTION
**Pull request by Rohesie**
This is done upstream the same. Defining the vars elsewhere breaks the langserv's go to definition feature and promotes messy code.

### CODE REVIEW

**Comment by MrJWhit** [comment]
This feels incredibly dangerous, how robustly has this been tested on both citadel and /tg/'s codebase?

**Comment by Rohesie** [comment]
This is a very simple change. The variables are just moved on where they are defined, but remain otherwise unchanged. It wouldn't compile if there were issues.

Nothing is being removed or added, and this should produce no changes on the compiled code.

**Review by Ghommie — APPROVED** [review]

**Comment by Rohesie** [comment]
@Ghommie , for the love of things that are good and pure, clean the huge amount of unused branches in the repo.

**Comment by Ghommie** [comment]
I blame kevinz. But sure. EDIT: Aaaaand done.

**Comment by silicons** [comment]
@Rohesie <3

**Pull request merged**
