### PR TITLE
Removes makeshift switchblades

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request 
Title. Will close #11102. 

## Why It's Good For The Game
Mediocre concealable butcher knives with senseless recipe only merged because of a couple guys on the verge of throwing a fit, also Kevinz is about to nerf them into a stupid downgrade, so this is a mercy kill, leaving no trace of this nice but actually useless idea (minus commit history) to stop potential future contributors from reintroducing it.

## Changelog
:cl:
del: Removed makeshift switchblades.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Can you keep the wooden handle ones, we can use them as a skin for the normal switchblades like how you can change the skin on some guns.

**Comment by Ghommie** [comment]
That's not the scope of this PR sadly, I won't stop you from doing it yourself though.

**Comment by Trilbyspaceclone** [comment]
No no, as in not remove the wooden handle verson of the sprites.

**Comment by Ghommie** [comment]
> 
> 
> No no, as in not remove the wooden handle verson of the sprites.

You realize it's going to be an unused asset, right? You are free to bring it back later if needed.

**Comment by Trilbyspaceclone** [comment]
sure and fine

**Review by Linzolle — APPROVED** [review]

**Pull request merged**
