### PR TITLE
Gives Cargo Technicians the choice of longer trousers.

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

Following a "frostbite incident" at one of our colder research facilities, **Nanotrasen has authorized the production of a Cargo Technician uniform with longer pantlegs:**
ctf
cts
cti

**This is by no means a replacement of the current uniform** - they perform perfectly fine as-is in most scenarios. However, these new uniforms will be rolled out alongside the old in local CargoDrobe restocking units (as well as the loadout menu). As one of our financial analysts put it, "it's cheaper to produce fabrics than it is replacement limbs".

## Why It's Good For The Game

More choice is good, and it makes sense for maps like Snow Taxi.

## Changelog
:cl:
add: Cargo techs now have access to a "long pants" variant of their standard work uniform
add: Adds said uniform to CargoDrobes and the loadout menu
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
But I like shorts, they're comfy and easy to wear.

**Comment by EmeraldSundisk** [comment]
They aren't going anywhere! They're still the default outfit for the job. The long pants are simply an alternative. I wouldn't mind if someone resolved this conflict for me, though...

**Comment by deathride58** [comment]
ONLY COWARDS WEAR PANTS

**Comment by EmeraldSundisk** [comment]
...Fuck.

**Comment by EmeraldSundisk** [comment]
Should be good to go again.

**Pull request merged**
