### PR TITLE
Fixes missing decorative wing states

### PR DESCRIPTION
**Pull request by Poojawa**
Just a quick fix for the missing wingstates 

also line endings I guess?? fucking github

## Changelog
:cl: Poojawa
fix: fixed missing deco wing states
/:cl:

### CODE REVIEW

**Comment by r4d6** [comment]
Does the unsnowflake thing also applied for the other round start species like Slimepersons?

**Comment by Poojawa** [comment]
No it just allows people to select it

**Comment by r4d6** [comment]
By "allowing people to select it", do you mean adding them as an option for every round-start races?

**Comment by Poojawa** [comment]
...no? It just means it shows up

**Review by silicons — APPROVED** [review]

**Pull request merged**
