### PR TITLE
NT/Synda* no longer commits war crimes back on Earth 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

NT/Synda has rebranded back to the Blue/Black Cross on all items and borg units, rather then the Red Cross do to the red cross being a USA warcrime. 

The Syndicats also have done this to their gear as well, making black crosses on white backrounds

## Why It's Good For The Game
Makes all red crosses on things into a NT friendly blue cross, or a Synda black cross - Now only red when the blood of your enemy is spilled on it

## Changelog
:cl:
imageadd: Red to Blue/Black crosses as questioned by Bhijn
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Law in Question - 
https://www.icrc.org/en/doc/resources/documents/misc/57jm93.htm
Law in Question MK II-
https://ihl-databases.icrc.org/customary-ihl/eng/docs/v2_rul_rule59

**Comment by Linzolle** [comment]
this is already changed in https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9246

**Comment by Trilbyspaceclone** [comment]
That was after the fact I made this pr rawr

**Review by silicons — APPROVED** [review]

**Comment by Tupinambis** [comment]
This doesn't need to be a thing unless for whatever batshit reason Red Cross decides to contact the server. Which they won't. Plenty of high profile video games have done this and gotten away with it. Who cares.

**Comment by Trilbyspaceclone** [comment]
Bhijn does

**Comment by YakumoChen** [comment]
Most actual videogames that do this later patch it out. The Red Cross has gone to people before to tell them to quit.

Furthermore, it's an international symbol and you should maybe consider respecting its use instead of blowing it off, it makes you sound entitled when you pretend like people just can use it willy nilly.

**Pull request merged**
