### PR TITLE
Dotted socks

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

adds pink socks with white dots as four different versions.

## Why It's Good For The Game

More choices are always good!

## Changelog
:cl:
add: dotted socks!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
merge conflict? What?
Lemme check this.

edit: uh I have no clues why there's a merge conflict, it worked fine during tests. Could anyone else look over it and check?

**Comment by Thalpy** [comment]
Merge conflicts usually mean the master you wrote the code on is out of sync with the current master (master being citadel-station/master branch). What you need to do is update your branch from the master, then merge the two files in that both changes work. Since this is a DMI, you'll need to grab the new underwear.dmi, and add your sprites to that, then push that dmi to your merging branch.

**Comment by ghost** [comment]
nevermind Just close it. Probably not going to be used anyways since no one really uses the underwear and socks options :p

**Comment by Thalpy** [comment]
Whaa, if you put effort into it, you should finish it! Socks are nice! Send me your DMI and I'll try to help you.

**Comment by ghost** [comment]
when I updated the master I accidentally updated the branch too, so all that effort is gone.

**Comment by Thalpy** [comment]
You can revert your pushes if you end up doing something like this. I'll get the file to you, just a moment.

**Comment by ghost** [comment]
weh

**Comment by Thalpy** [comment]
Huh

**Comment by ghost** [comment]
merge conflicts

**Comment by Trilbyspaceclone** [comment]
#8603

**Pull request closed without merging**
