### PR TITLE
Oh that blob

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
[Changelogs]: Correct me if I'm wrong, but I haven't seen many blobs lately. Woops. Sorry bout that.

:cl: ZeroNetAlpha
tweak: Removed minimum player count for the blobs.
/:cl:

[why]: Our resident blo- Sharknet expressed displeasure about not being able to be a blob on lowpop. Feexed that. I kinda neutered blobs hard with #5771

### CODE REVIEW

**Review by deathride58 — APPROVED** [review]
What blob?

**Comment by CameronWoof** [comment]
What? No. Why? We literally just had this put in. Why are we removing it?

**Comment by ZeroNetAlpha** [comment]
You want the snarky response or the reasonable well thought out response?
Reasonable: Because getting 50 players to actually be in game, actually playing and not ghosting, is next to impossible.
Snarky: Because I made the original PR and I don't like how it turned out. Reeee.

**Comment by CameronWoof** [comment]
Then lower it to 40, or try a more measured response than 5 pop blob rounds.

**Comment by ZeroNetAlpha** [comment]
It's been a week with no blobs. They still have their 60 minute timer. It's not a complete revert.

**Comment by CameronWoof** [comment]
The timer is nice, but blob _needs_ a population limit, too. Lowpop blobs are a massacre. Bring it down to 40, or 30 at the absolute least, but don't remove it outright.

**Comment by ZeroNetAlpha** [comment]
I'm gonna be honest here. I don't want to. It's just laziness on my part. You're more than welcome to make the change yourself, even open up a competing PR.

**Comment by CameronWoof** [comment]
It's a one-line change? It's a one-character change from how it is now? Why open a PR at all if you don't want to put any effort into it?

**Comment by ZeroNetAlpha** [comment]
I put all the effort into it that I wanted to. If more people express displeasure at the reverting of that half of my original PR then I'll adjust it. Till then, do whatcha want cause a pirate is free.

**Comment by ZeroNetAlpha** [comment]
Didn't mean to close this.

**Comment by Knightfall5** [comment]
I like this change, I haven't seen any blobs in quite some time. If people don't want the station to get rolled, they should stop ERPing for 10 minutes and help kill it.

**Comment by king5327** [comment]
I disagree with the contents of this change. My recommendation is, lower the pop to 30, and make the blob announcement automatically set the individual dorm scrubbers to panic syphon (ignoring of course the dorm commonroom), with no option to fix.

Same thing with the maint bar and any other places people are likely to ERP in.

**Pull request merged**
