### PR TITLE
Stimpack transfer buff

### PR DESCRIPTION
**Pull request by Chiirno**
## About The Pull Request

Syndie stimpack has been buffed to allow different transfer amounts (5, 10, 25, or 50) through in-hand use or right-click context menu, instead of the usual 50u injection. The stimpack from the homerun syndie bundle has not been changed.

## Why It's Good For The Game

Lets syndicate agents use stimpacks without having to go on an aggressive rampage for 5 minutes straight.

## Changelog
:cl:
tweak: Syndie Stimpack now has possible transfer amounts
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
That imo makes it far too good for a 3 tc item. It did in fact get reduced from its original price to the current one when being able to do this got removed a whiile ago (#11867) (which also was a semi-revert of a buff PR for it that added that)

**Comment by Chiirno** [comment]
I'm not all that up-to-date on the history of stimpacks changes, but as far as I can see it currently costs 5tc.

**Comment by Chiirno** [comment]
It's already possible to remove the reagents out of the stimpack and turn it into pills/syringe/hypoinjections, so I view this more of a quality of life change.

**Comment by DeltaFire15** [comment]
You may be able to manually do funky stuff to extract it and split it apart, but it shouldn't be encouraged to do given its intended purpose of being a single-use dose of massive combat boost for a while. Closing this PR.

**Pull request closed without merging**
