### PR TITLE
[READY] some missing icons + sprite changes for taur suits

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Some icon fixes and changes for taurs. Changes red cross to blue cross on tauric suits.

## Why It's Good For The Game
fixes

## Changelog
:cl:
fix: blood on your body floating a bit to your right if you're a taur
fix: some suits having no icon on tauric characters
tweak: front facing CMO hardsuit icon for naga taurs
tweak: colour of medical cross on CMO hardsuit for taurs
fix: taur body and jumpsuit showing through mining suits
/:cl:

### CODE REVIEW

**Comment by Linzolle** [comment]
Gonna work with Forrest to sprite missing icons for tauric suits.

**Comment by Linzolle** [comment]
icon diff man bad
after
image
before
image

the after sprite is more in line with the rest of the directional icons of the suit

**Comment by Linzolle** [comment]
the fixes here should probably get merged soon, I'll see about adding more tauric sprites for more suits in the future.

**Comment by Poojawa** [comment]
the overlays are handled with the blood rework. the tauric suit fixes are all good though.

**Comment by Linzolle** [comment]
> 
> 
> the overlays are handled with the blood rework. the tauric suit fixes are all good though.

Should I revert that change then?

**Comment by Linzolle** [comment]
hold up a fucking second why did this make hardsuit-syndie black...

**Comment by Linzolle** [comment]
Hold off on merging this I'm looking at doing a few more fixes

**Comment by Linzolle** [comment]
ok thats what i wanted to get done.

**Comment by Poojawa** [comment]
lol. No worries. 

As for the overlay stuff, yours might end up superior to mine unless they're not grey scaled. which is what I'd done

**Comment by Linzolle** [comment]
I actually didn't change any icons related to the overlay,  it was fixed in code by changing the check to use the tauric blood overlays that were already present. I changed it from checking if the *mob* was tauric to if the *suit* was tauric.

**Comment by Poojawa** [comment]
ah hah. yeah. thats probably a superior way of fixing it then <3

**Comment by Linzolle** [comment]
oh wait. oh my god. my fix WOULDNT have conflicted with what you did, so I didn't need to revert it. time to... revert my revert lmao

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
