### PR TITLE
(is this really a good idea) hitscan emitters

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Emitters are now hitscan.
raises hitscan safety to 10x range, since there's already a safety mechanism for reflections.

## Why It's Good For The Game

Uh, could potentially be fun?? Emitters are stationary structures, they're very rarely used for defense and it's like >imagine not being able to dodge a stationary structure

DEFINITELY a testmerge first thing though, because I'm Sure This Will Probably Result In A Disaster When Someone Abuses It And Shows How Good It Can Be In Warops Or Something

## Changelog
:cl:
balance: emitters are now hitscan
/:cl:

and no i don't have time to consider porting vgemitters myself, as fun as those can be i guess.

### CODE REVIEW

**Comment by MrJWhit** [comment]
Uh, will this work with the engie traitor emitter gun?

**Comment by silicons** [comment]
no

**Comment by davidchan13** [comment]
LAZORS

11/10

**Comment by kevinz000** [comment]
while I like this this is not going to work until projectiles are refactored so.. hm.

**Comment by silicons** [comment]
above is fixed

**Review by Ghommie — APPROVED** [review]
"What could go wrong?"

**Pull request merged**
