### PR TITLE
Removed the racist ninja speech modification

### PR DESCRIPTION
**Pull request by SkullyRoberts**
Deleted the old PR and made a new one to clear out the spam.
This isn't the place to tell me what you think of race issues. Take it to the forums.

### CODE REVIEW

**Comment by CameronWoof** [comment]
https://cdn.discordapp.com/attachments/419883780275175426/590736402463981578/unknown.png
https://cdn.discordapp.com/attachments/419883780275175426/590736514271543306/unknown.png
https://cdn.discordapp.com/attachments/419883780275175426/590736587847892992/unknown.png
https://cdn.discordapp.com/attachments/419883780275175426/590736675655778316/unknown.png

Comments from the previous version of this PR. Please don't take it upon yourself to moderate the github by closing entire PRs to get out of a conversation.

**Comment by CameronWoof** [comment]
And, for the record, the github is for anyone who plays the game. You are not required to code to contribute to conversations about changes to the game we all play.

**Comment by RogueSteampunker** [comment]
>Deleted the old PR and made a new one to clear out the spam.
This isn't the place to tell me what you think of race issues. Take it to the forums.

Your entire PR is about your race and how that makes the feature racist to you. How can you even say this?

**Comment by Screemonster** [comment]
deleting and remaking a PR to try and sweep negative feedback under the rug is an absolute galaxy brain move lol

**Comment by deathride58** [comment]
Don't hit the door on the way out I guess

**Pull request closed without merging**
