### PR TITLE
new jungle gateway map

### PR DESCRIPTION
**Pull request by Llizny**
## About The Pull Request
Adds a new gateway to explore, loot, and whatever else people feel like doing. It was originally made mainly for a alternative to the beach, but after some suggestions I went ahead and added a out of the way mob to fight as well for anyone eager for action. Notable places include: the center lake and the surrounding buildings, which is a arrival storage, bar, manager office, several dorms, and a cafe/kitchen. Further west is power storage/comms, north from that is a abandoned cabin with donksoft toys. Other more 'hidden away' places are the toolbox chapel up north to the caves, sealed off by barricades and a cave-in, the river leading further into the mountain that's home to a leaper megafauna boss, and finally in the south mountains is a buried building with collectable hats and abandoned crates. Loot includes a reskinned chain of command whip along with a shotgun pump and axe for the leaper mob, while the only thing notable in the chapel would be the red and black toolbox with guerilla gloves and a fake golden toolbox for that greytider bling. Add map to config to enable it.

Full map view: https://imgur.com/a/ZT1u2Bz

## Why It's Good For The Game
More gateway variety and exploration as well as another place for horny people to have scenes in (hopefully) peace.

## Changelog
:cl:
add: new gateway mission
mapadd: jungleresort map
/:cl:

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Why does this move arachnid.dm below anthromorph.dm?

**Comment by Llizny** [comment]
Dunno, something the dme did on its own. Nothing bad about it, just got moved down a bit in alphabetical order.

**Comment by LetterN** [comment]
planet station 2

**Comment by KathrinBailey** [comment]
There's a way somewhere to define the Z level as fullbright without the need for lighting.
If you want the pool area to be lit up, var-edit some of the water turfs to have light_range and light_power instead of using machinery lights, since those have a random chance of breaking. If you have a lot of high range low intensity (15 range, 0.5 power) lights, you can have large areas dimly lit.

**Comment by Llizny** [comment]
Thanks for the tips but all the lighting on the map is intentional.

**Pull request merged**
