### PR TITLE
Removes stim packs from gangs

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
## About The Pull Request
As it says on the tin, removes stim packs from the gang tool menu.

Removes 
## Why It's Good For The Game
Gangs already get high grade gear they do not need to go mach 7 with it too

## Changelog
:cl:

del: Removes combat stimulants from the gang tool menu

/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
So much more in gangs needs to die than just stims. The game mode is obscene.

**Comment by KeRSedChaplain** [comment]
This is all I was asked to do and it was fast I'm not re balancing the whole mode.

**Comment by silicons** [comment]
Very good PR.

**Review by silicons — APPROVED** [review]

**Comment by Iamgoofball** [comment]
Antag freeze violation.

**Comment by Iamgoofball** [comment]
wait this isnt tg

**Comment by Iamgoofball** [comment]
When the tg antag freeze ends I'll get Families back up and running, it works way better in high to medium RP situations than normal Gang.

**Comment by necromanceranne** [comment]
@Iamgoofball tg doesn't even HAVE gangs to begin with, I'm near certain they killed that from the code outright. Also, how the hecc did you accidentally wind up here?

**Comment by Iamgoofball** [comment]
i have every repository on watch

**Pull request merged**
