### PR TITLE
Making metastation the meta.

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

I've essentially gone through and reworked some areas, taken some areas from other servers, and overall tried to take the best bits of every iteration of metastation, hopefully aiming to make Box station less-so the 'default'.

## Why It's Good For The Game

More valid map variety good.

## Changelog
:cl:
mapadd: Meta un-sucks now.
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
## **Stuff that needs addressing:**
image
I'm just glancing at mapdiffbot and someone should still download this and look it over in the editor but do you have mail sorting tubes for the following areas?
• Robotics (sortType 14)
• R&D (sortType 12)
• RD Office (sortType 13)
• Medical Office/Lathe Room/Storage (sortType 9)
• Genetics (sortType 23)
• Chemistry (sortType 11)
• CMO Office (sortType 10)
Was the removal of the preloaded organ smartfridge intentional or an accident? It's on Box/Meta/Delta/Pubby. If you don't want this to be there then just make a note so when a maintainer checks this they don't consider 
Same question again about the medical records laptop. I see you have the surplus limbs and synthflesh beaker in another room.
Remove the directional firelock windoors in the gas storage area. They crush you if you're in the same tile. Either test it and see if they still do that or remove them.
image
C'mon.
image
Check what tile this button is actually on. It's probably worth keeping the pixel_x to be a tad lower since every map has buttons like this ==> other side of wall  ||    wall♦|| tile button is on
You really need to sort this hallway out, it's horrific.
image
What on earth...
You've got the wrong decals all over.
image
image
image
I can understand this because you can't see it until mapdiffbot renders it.
image
image
image
image
This room has decals really weird. It looks like it's split into quarters. This becomes extremely glaring in the CMO office.
image
image
What is even going on with these decals? You have some decals to illustrate there's a door here, but some doors just don't have decals for that, top left you don't have any weird gaps to mark out there's a door but on the right side you do.
I'm glad that decals are actually being used but this just looks so incredibly jarring.
An infinitely better way of doing this would be to us those plasteel/white tile corner pieces at every door to play around with how the decal's alpha values interact with a darker colour, then just have a consistent border pattern.
image
The decals are all weird. It looks like the room is divided into quarters. It stuck out in seconds and I can't unsee how awkward it looks.
image
This will probably look much nicer as door wall door instead of door door wall like you did with the science entrance.
image
MULEBOTs are blocked roundstart. Pretty sure they're just going to get stuck there until medical screeches at Cargo, then some poor pissed off cargo tech goes to find the MULEBOT and finds out they're stuck on this water tank.
image

**Comment by Detective-Google** [comment]
god hates neutral corners and so do I the invisible bastards

**Comment by Valander** [comment]
I have vent-crawled for a while and found out that the air and scrubber networks are connected together right in front of the Brig's Medbay.

Colliding pipe networks

This is in fact also true for a connection in front of Robotics.

Another collision

Last edit: I have used the roundend to disassemble the erroneous pipes to ensure I don't encumber with crew duty as drone. I can confirm fixing those succesfully separates the air and scrubber networks.

**Comment by Detective-Google** [comment]
> I have vent-crawled for a while and found out that the air and scrubber networks are connected together right in front of the Brig's Medbay.
> [snip]
> This is in fact also true for a connection in front of Robotics.
> [snip]
> Last edit: I have used the roundend to disassemble the erroneous pipes to ensure I don't encumber with crew duty as drone. I can confirm fixing those succesfully separates the air and scrubber networks.

ty fixed now

**Comment by YakumoChen** [comment]
Honestly loathe the science and medbay. They take up entirely too much space. I don't like the morgue in maint for the same reasons I don't like it in your other PR. Sci and med are massive and box-shaped which is pretty aesthetically unpleasing. There's too many hallways. Medbay has too many extra frivolous rooms and several rooms in sci are just too open and large for their own good (robotics in particular from what I saw playing it)

There's a dozen other different complaints about why I hate it and I really don't agree with the design of this at all.

**Comment by YakumoChen** [comment]
I can make a list I guess, one post at a time

image

Windows into Brig EVA were removed, balance issue
8(!!!!!) prison lockers for the tiny-ass perma, removed ID card box and body bags, recharger (!), other fluff
I'm not really sure what you did with the maint there but it looks like you removed a bunch of goodies. It looks a bit too boxy in general and I don't like the shape
Brig EVA looks a bit too big
You removed the air can from maint 
and the wall radio from the prison main area
and the air alarm
and the fire alarm
and the air scrubber
and the fire extinguisher

**Comment by YakumoChen** [comment]
image


Hate secure brig

The first thing I noticed is that the whole brig is now one big path with lots of dead ends. Unless you start to break stuff, you're mostly only going one way through and in or out, which is extremely un-ideal compared to the original which had many pathways and loops.

The armoury feels absurdly unsecure. Like, appallingly unsecure. Four different rwindows into it, one single, measly airlock from the brig proper, and it's so centralized and oddly shaped. Breaking the windows for extra paths is nice and dynamic but it feels you sacrificed all the security of... security to do it. The armoury is supposed to be THE most fortified space in the station. It has all the guns.
I don't like the wall placement near space either as its confusing and makes it hard to figure out where to bomb. I don't know why there's a random bend in the wall. It should just be flat.

Half the armoury is next to windows to space. Because... why? Yes I never liked moving around the flashers either but you put like, the fucking firing pins right by space, all the implants, just... why?
I also noticed yet another rwindow removed, in perma, because balance.
It feels designed that you're never going to spot a break-in unless you're in the rooms that never get traffic anyway (how often do you actually grab an implant or a straight jacket?)

**Comment by YakumoChen** [comment]
comparing points of entry variety
image
image

**Comment by YakumoChen** [comment]
The shutter and door being far apart with paths separated (windows between for a shootout!) with guns in the middle was one of the strongest features of meta armoury and now you have both facing into an identical hallway, with a dead end if you want to get guns

**Comment by YakumoChen** [comment]
image
Cramped is a good way to describe the brig now.

The only thing I like is warden's placement, given the armoury. The outward facing office is a very nice touch since the checkpoint room is never used. 

That's where the good critique ends.

The cells are tiny and cramped. The windows are nice for the warden but not for the prisoners (who can try to break into other cells and probably shouldn't have LOS to each other. 
The warden can't even see cell 3 from his room, which I don't like, you could keep tab on all the cells before. (editor's note: I don't use widescreen)
The two entries into warden's office feel.... pointless? They're practically adjacent.
Despite the luxury of the warden's office now also serving as the brig checkpoint, you removed the door control buttons which sort of ruin the point (yes I know he has a remote, the point stands)
**rolly chairs downgraded (extreme frown)**
Why does the warden get the secway key now? Put it back.
The copier feels really badly placed from an otherwise interesting hallway
The recharger is outside the office now
All the fluff/paperwork items were removed, for no reason. The warden IS a paperwork role, you know.
Point of entry removed to make the weird court inbetween room, which... I don't see the point of that room to be honest. Why does it have a straight jacket and lockers?
I noticed you removed any point of entry from the hall that isn't through a brig cell or airlock. It almost feels too defensible.

**Comment by YakumoChen** [comment]
image

**Comment by YakumoChen** [comment]
image

**Comment by YakumoChen** [comment]
overlaid the entire engineering department (a department which is wide open for building) plus a large amount of space and maint over boxy medbay to demonstrate size
image

**Comment by YakumoChen** [comment]
where do I even start with medbay? How about with viro
Its tiny
there's only two monkies
it's incredibly insecure (there's a whole wall of regular walls on one side

cloning:
Very vulnerable from maint (this is good, I like this)
Too hard to break into from actual medbay (you removed all the fucking windows)
No patient lockers
No mirror
cloner is positioned badly
removed fluff items, body bags
no sink

genetics
removed all the fluff items
very small
no clothing vendor
no body bags
no sink

surgery
badly placed wall mounts, poorly utilized space
no theatre
no sight line into one of the rooms at all
no APC?

cyro
why is the machinery behind windoors?
how am i supposed to upgrade this
I can't sabotage it either

CMO office
It's a fort
it's too secure

chemistry
big
cramped workspace anyway
doesn't work near a window
why is there a hallway door if there's a lobby

secoff 
not actually inside medbay
why
mall cop more like hall cop

patient rooms
W H Y A R E T H E R E F O U R ? ? ? ? ? ? ?
holy shit

morgue
### STOP PUTTING THESE NEXT TO MAINT WE HAVE HALF A DOZEN JOBS THAT NEED ACCESS

medstorage
two
two
why

the rest
### HUGE
### HALLWAYS
### WHY ARE THERE SO MANY MEDVENDS
### HOLY SHIT LIKE 5 FUCKING MEDVENDS
### THATS NOT EVEN AN EXAGGERATION THERE'S LITERALLY FIVE

**Comment by YakumoChen** [comment]
im wore out from spending hours on why i hate this pr so I'm just going to let the picture of science say what I want

**Comment by YakumoChen** [comment]
holy fuck its a fucking manual valve straight into mother fucking distro from the turbine feed
image

**Comment by Detective-Google** [comment]
this pr has been open since MAY. smile.

**Comment by NalyKalZul** [comment]
If your going to fix all the nitpickings of the map, could you please add mini fans to the cargo shuttle doors, and mining shuttle dock eva?

**Pull request closed without merging**
