### PR TITLE
Ports Arachnids (Spider People) from WaspStation

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Adds spiderpeople to the game, they have their own unique little language, chitter adorably, have limited night vision, hate flashes, and can create webs at the cost of nutrients. They can create webs that have a low (20%) block chance when passed through and can create cocoons which can bind people but take 15 seconds to resist out of (less than wire cuffs). There is a 20 second delay to use webs again, though it may be increased if necessary. They are vulnerable to bugspray and bugswatters, and take ~10% more brute damage.

Ported from: https://github.com/WaspStation/WaspStation-1.0/pull/226

image

## Why It's Good For The Game

More species, character variety, and gameplay variation is good, and spiders cute.

## Changelog
:cl: Tupinambis
add: Arachnids (spider people) with limited night vision, flash vulnerability, and webbing.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
>its just a better moth

Don't we have a tauric body already? Dont know how I feel about moth but has free quirk and genetics power (the one that let's you leave movement blocking webs all over no less)

**Comment by YakumoChen** [comment]
Oh jesus the web trait let's you full up bucklecuff people
This is an ability they get free

**Comment by Tupinambis** [comment]
> Oh jesus the web trait let's you full up bucklecuff people
> This is an ability they get free

It's a draft calm the f down.

**Comment by MrJWhit** [comment]
Oh good jesus those are terrifying.
I love it.

**Comment by ghost** [comment]
Okay, but let insects use this sprite minus the legs on the back.

**Comment by Tupinambis** [comment]
> Okay, but let insects use this sprite minus the legs on the back.

I made it so all parts can be "none"

**Comment by ghost** [comment]
Is this supposed to not actually be available? I don't see it in the species list.

**Pull request merged**
