### PR TITLE
Revert "12/21 modernizations from TG live"

### PR DESCRIPTION
**Pull request by LetterJay**
Reverts Citadel-Station-13/Citadel-Station-13#103

### CODE REVIEW

**Comment by unusualcrow** [comment]
This isn't needed as long as lighting is reimplemented and any accidentally replaced content is put back.

**Comment by ghost** [comment]
Revert this and then do it correctly later after all current PRs are merged.

**Comment by ghost** [comment]
nevermind poojawa explained that he already solved conflicts instead of replacing everything so it should be fine

**Comment by TalkingCactus** [comment]
rip #64

**Comment by ghost** [comment]
oh right yeah we might wanna merge that first before this happens

**Comment by LetterJay** [comment]
So close this still?

**Comment by ghost** [comment]
revert it

**Pull request merged**
