### PR TITLE
Foam-Force Assault Machines.

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
[Changelogs]: # Adds two new guns, one donator only. The Foam Force AM4-B and AM4-C are two new guns for the greytide to play around with. No worries, eh?

:cl: Zna12
add: Added the AM4-B, Zero's personal version. 
add: Added the AM4-C, An autolathe craftable version. (Hidden behind the hacking like the others.) 
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
Sprites please!

**Comment by Zna12** [comment]
Sprites are in cit_guns.dmi

**Comment by ZeroNetAlpha** [comment]
SPRITES?! Okay. https://gyazo.com/7cac1a7524a8233d7b55a3e841696635

**Comment by Poojawa** [comment]
Just as a reminder, your name is the first line after the :cl: marker

**Comment by ZeroNetAlpha** [comment]
Whoops. Better now?

**Comment by Poojawa** [comment]
Yeeup. this good to merge?

**Comment by ZeroNetAlpha** [comment]
Yeabsolutely

**Pull request merged**
