### PR TITLE
Snow Snaxi update

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Three things being changed:
-Removing the air alarm in tcomms.
-Removing a trash bin in genetics and mining.
-Makes another cargolathe in the cargo area.

## Why It's Good For The Game

Air alarm removal- It goes off roundstart because it's too cold, there's nothing that can be done about it, and Boxstation and Deltastation (the only two maps I did a look in) don't have air alarms in the Tcom Stat area, so it feels fine.
Trash bin- Those were temporarily placed there while disposals was being introduced. These got skipped over, no biggie, but just popping them.
Cargolathe- There isn't a way for cargo techs to actually obtain mats without breaking into mining.

## Changelog
:cl:
del: Removed air alarm in Snow Snaxi in Tcomms Sat
del: Removed trash bins in genetics and mining
tweak: Gives cargo techs a cargolathe
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Yeah what was sent to me is fucked.

**Comment by MrJWhit** [comment]
Or something? I'm so confused what's going on with those line changes, when I did it myself it was fine.

**Comment by Detective-Google** [comment]
@MrJWhit line changes for map files tend to look super weird because of the mapmerger, ultimately mapdiffbot is the best determiner of what actually changed.

**Comment by MrJWhit** [comment]
Yeah, but when I tried to run it, it didn't run. It asked for python, but didn't tell me what version it was, and nobody told me what was going on, along with the fact that it somehow fucked up html\changelogs\.all_changelog.yml, just everything was going bad. It was easier to just force shit myself because I knew it worked.

**Pull request merged**
