### PR TITLE
Just another round-end sound.

### PR DESCRIPTION
**Pull request by Ragolution**
## About The Pull Request

Adds a new sound to round-ends. No frills. Duplicate of #11280 due to me trying to be a troglodyte and do this PR via web client.

Remember kids, only morons do Web Edits when trying to add audio files.

Preview: https://voca.ro/69CKa9ZbQE8

## Why It's Good For The Game

Has not every man, woman, whirry, platypus or otherkin heard that one repetitious round outro file and thought "Oh gee it's that one familiar but irksome sound again, isn't that quaint." But now, that mild ennui is partially alleviated with this brand new, organic free-range .ogg file! As its dulcet tones tickle my ears, soon shall it soothe yours as the station blossoms in the aftermath of explosions, catastrophic radition, bluespace lag sinkholes and violent bwoinking. So, as mother always said: variety is the spice of life. And if you hate spice, your opinion doesn't matter.

## Changelog
:cl:
Added new sound effect to the End-of-Round sfx list.
:cl:

### CODE REVIEW

**Comment by Linzolle** [comment]
why is it a video file if you open it

**Comment by Ragolution** [comment]
lol wtf it is

**Comment by Trilbyspaceclone** [comment]
Your back!

**Comment by Ghommie** [comment]
Most round end sounds are references, jokes or something between, sooo what's the meme here?

**Comment by Ragolution** [comment]
Explaining it ruins the magic, don't you think?

This one is definitely a reference, though. I'm sure at least a few people on the server will recognize DNSL.

**Comment by KathrinBailey** [comment]
This dilutes the chances of getting the literal ear-rape round end sounds so awesome.

**Comment by KeRSedChaplain** [comment]
stomach_loop.ogg as round end sound on god

**Review by Ghommie — APPROVED** [review]
w/e

**Pull request merged**
