### PR TITLE
Wataur Bottle

### PR DESCRIPTION
**Pull request by dapnee**
## About The Pull Request
It's a large water bottle, but bent. What's not to love? Currently in soda machines, hidden as contraband.

## Why It's Good For The Game
Haha, funny item.

## Changelog
:cl:
add: wataur bottle item
imageadd: wataur bottle and overlay
/:cl:

### CODE REVIEW

**Comment by dapnee** [comment]
who would of guessed updating my branch beforehand didn't actually update it, I'll fix it tomorrow

**Comment by KathrinBailey** [comment]
image

**Comment by Detective-Google** [comment]
afaik all you would have to do to make these available in drinks vendors is add this line to `code/modules/vending/cola.dm` 
image

**Comment by dapnee** [comment]
Think I'll add it to contraband considering it's the size of a large water bottle and those aren't in the machine.

**Comment by Detective-Google** [comment]
@dapnee you forgot to add a comma (,) after the shambler's line

**Pull request merged**
