### PR TITLE
Ports expensive swag outfit from TG

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Port of https://github.com/tgstation/tgstation/pull/56491. This is not a joke PR.

## Why It's Good For The Game

Well, it looks cool. Also, with new clothes you can show how rich(and stupid) your character is. 

## Changelog
:cl:
add: Added a new expensive swag outfit that can be bought in clothes mate.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Unfunny forced meme. Come up with something more original please (like those glowing gold clothes from gang)

Pretty sure theres already a few overpriced cargo crates with bling in them anyway (I specifically remember coding a couple of them, at that)

**Comment by SmArtKar** [comment]
> Unfunny forced meme. Come up with something more original please (like those glowing gold clothes from gang)
> 
> Pretty sure theres already a few overpriced cargo crates with bling in them anyway (I specifically remember coding a couple of them, at that)

Well, bling is just gang-style stuff.

**Review by silicons — CHANGES_REQUESTED** [review]
change it to something that isn't literally named swag, please. what yakumo said with "glowing x/y/z" would be nice.

**Comment by silicons** [comment]
reopen when this is fixed

**Pull request closed without merging**
