### PR TITLE
Underwear Additions, Chem Dispenser Addition

### PR DESCRIPTION
**Pull request by the-og-gear**
:cl: MASMC
add: Added new underwear and their pixmaps
add: Added sulpheric acid dispenser and it's icon
/:cl:

### CODE REVIEW

**Comment by TalkingCactus** [comment]
`SULFURIC`

**Comment by the-og-gear** [comment]
Reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeėeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by the-og-gear** [comment]
Can someone get the pic for me, from the icon file? Don't have access to my PC rn.

**Comment by Poojawa** [comment]
Somehow a huge tank of sulfuric acid seems... odd. Also, I'm not sure why science would need infinite resupply when chemmasters are really easy to construct, and The tier 3 parts for the circuit imprinter reduces the cost to 5u a board.

https://gyazo.com/edc0b17c22908e8202300dc68604a67d is the icon of the dispenser.

**Comment by TalkingCactus** [comment]
`S U L F U R I C`

**Comment by Poojawa** [comment]
Considering this stale/abandoned.

**Pull request closed without merging**
