### PR TITLE
Foxy away mission but its actually decent

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
New dangerous away mission edging on the sillier side.
Explore a fox filled derelict wooden mansion in a snowy mountain valley, some of the foxes are not as they seem.
Plenty of 20-40 damage 50 hp foxes. 4 more boss foxes that keep their range and cast magic missile/fireball with 4 more of the regular foxes as backup (each group is separate 1 boss fox 4 normal ones.)
A crashed syndi-clown co-op shuttle, careful guarded by a turret that will 2 shot to crit unarmored humans then finish them off with 2 more shots along with a explosive mine and punji sticks.
Punji traps scattered around, watch where you step!
loot:
dead cargo tech at the gateway entrance, might interest the greyshirts
west of the gateway: crashed syndi-clown shuttle, **deadly turret along with a actual explosive mine!** ,contains 5 duffel bags full of cream pies, dead syndi soldier gorilla gloves, swat helm, agent id are the things of interest on him.
east of the gateway: snowy forest with punji sticks, foxes and the bossfox ryoko and his bodyguard at the end guarding a aesculapius rod.
inside the mansion:
more man eating foxes! (who would of guessed)
punji sticks, scattered wood/metal/infinite no heat candles.
Tons of gibs!
South west corner: large library stuffed to the brim with wooden bookcases.
directly above ^: lounge room with a pair of binoculars
directly above ^: A giant working pool, biggest in the code rn afaik
South east corner: hidden occult library, contains the bossfox Ayumi and her bodyguard guarding a apocalypse rune, rainbow knife, book of babel, 4 human hearts, ***pride mirror*** (chasms you to deep space after use) and two healing fountains flanking it. Another secret entrance leading to the diamond mine, a smallish amount of diamond ore scattered about in the walls, contains 2 normal foxes and the tunnel to the shrine of salt a passage filled to the brim with punji sticks and bwoink mines _**have fun!**._
Shrine of salt/mansion center room in the center of the mansion circled by chasms that will round end you, blocked off by a layer of thin plasma glass windows. Ultra rare pete hat!!!! and a circled hand (gottem)
East side: large kitchen  7 lockers of 4 monkey meat each and 7 lockers of milk/eggs, 3 microwaves 2 all in one grinders and 2 food processers. 16 wildcard ingredient boxes and 2 butcher cleavers
Kitchen freezer( south of the kitchen): boss fox Takeshi and his bodyguard! 4 clown corpses 1 bee terrorist corpse (has insulated gloves) 2 assistant corpses infected with the spanish flu and beesease.
North east side, the guest lounge: pair of binoculars, 4 dorm rooms, 3 random bedsheets and a syndicate bedsheet, a breakable window that leads to a area containing a chlown (how horrifying chad clown also called "the entity") comes with a pair of circled hands (gottem good)
North center: the dining room,  boss fight! Kaede and his bodyguard, room contains various cooked meat products (careful these steaks are not your average cow)
master bedroom above the dining room: cookie synthesizer (self recharging device that holds 10 charges of cookie), yet another book of babel (some good night reading), 5000 credits and 2 cult bedsheets.

## Why It's Good For The Game
Combat focused away mission that can be turned into a large RP area with a fair amount of work. Contains plenty of medium difficulty mobs with a fair amount of humor thrown in.

## Changelog
:cl:
add: Theres a new away mission, watch out for the foxes!
config: ACHTUNG! new away mission available.
admin: ACHTUNG! new away mission available.
/:cl:

### CODE REVIEW

**Comment by bunny232** [comment]
Forgot to mention, boss foxes have 200 hp and are capable of casting magic missile/fireball

**Comment by bunny232** [comment]
forgot to mention that the fireballs only fire on straight lines

**Comment by bunny232** [comment]
Update:
Boss cast times increased, 10sec for magic missile 20 sec for fireball. Boss hp now varies: 200(dining room),150(cult area),100(forest),80(kitchen cold room)Map shrunk a tad. Tiny greenhouse infested by killer tomatos added to the south west, contains koibean seeds, killer tomato seeds, and corpse flower seeds. crashed shuttle moved to the north west. Replaced apoc rune with old hog nexus (does nothing its just fluff). Added a item fortification scroll to the loot contained within the cult area (next to the pride mirror). new 'oar' has been added to the salt mines along with a hand balloon in the locker. The entity (chlown) has been given a airhorn to play with. Item fortification scroll added in the forest loot area (east side of the map). A pair of wandering dark mages have been sighted in the south east. Main bedroom has a xenobio love potion hidden under the sheets (lewd). Candelabrum's integrity cut down to 50 from 300.  A normal glass spear has been added outside the spawn. Blood trail leading to the dining room. More hints have been added on how to access the cult area. Syndicate turret cut down from 160 hp to 100.

**Comment by silicons** [comment]
was regarded very badly in playtests
reopen the pr if you want to try this again, emphasis on the "don't do maps that have too much mob spam as its only defining piece".

**Pull request closed without merging**
