### PR TITLE
foot fetish content for kevin (ankle coverings)

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Kevin bugged me to port these from RP. I also tweaked the caltrops and footstep components to allow for shoes that don't cover your feet. These ankle coverings won't protect you from glass shards, sorry. You get to hear that "plap plap" sound effect though.

## Changelog
:cl:
add: Four colour variants of ankle coverings. Select them on the loadout screen.
imageadd: ankle coverings
tweak: allows for shoes that don't cover your feet to be taken into account for footstep sound effects and glass shards
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
So, uh, why?

**Comment by Linzolle** [comment]
> 
> 
> So, uh, why?

ask kevinz

**Comment by Poojawa** [comment]
why not. more variety is good

**Comment by Linzolle** [comment]
its literally only cosmetic so yeah, why not

**Review by silicons — APPROVED** [review]

**Pull request merged**
