### PR TITLE
Nerfs nanite armor

### PR DESCRIPTION
**Pull request by silicons**
its passive use isn't fast enough to justify 50% armor for melee/laser/35% bullet and i'm too lazy to overhaul nanites atm so

### CODE REVIEW

**Comment by ghost** [comment]
25 is a biiiiit of a yikes. just increase the draw rate 4head. Sure it's hidden armour but good luck fucking around long enough to get it set up on a main round. It wouldn't be worth it with this change.

**Comment by silicons** [comment]
@AnalWerewolf dude i get nanites up 12 minutes minimum if i don't do stock parts first lmao

**Comment by silicons** [comment]
buffed to 35 as i merged a nerf pr for pools.

**Comment by ghost** [comment]
Hah I knew you'd mention that /you/ can get them set up so quickly. Not everyone plays RD or scientist to powergame its features. Not everyone can make a maxcap within 10 minutes. You shouldn't balance things around a skewed perception of what is trivial and what isn't. That being said 35 is much better and I reckon that's a good place to keep the values, 25 is just a tad too low.

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
