### PR TITLE
Small pipes

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Pipes are small

## Why It's Good For The Game

Annoying to carry around, QoL

## Changelog
:cl:
balance: Pipes are small now
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
These are tile long pipes, it's a wonder they actually fit in storage already, and I don't see any good reason these should be made even smaller when closets/crates exist.

**Comment by Trilbyspaceclone** [comment]
@Ghommie A tile is a small item, 2 metal rods is a small item and those both are "bigger" game wise when on a tile.

**Comment by Ghommie** [comment]
While you are right that actual item sizes defy common sense at times, mentioning the issue complete with examples makes no good excuse to add further injury to said issue.

**Comment by BobJoga** [comment]
your pipe is small

**Comment by Trilbyspaceclone** [comment]
@Ghommie According to TG, each tile is around a foot long, Im p-sure a foot of pipe is simular if not the same as a pocket size crowbar.

**Review by silicons — APPROVED** [review]
ehh qol over realism, even if it's stupid that you can carry enough metal to build a room on you

**Pull request merged**
