### PR TITLE
VIBE CHECK

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Buffs nuclear fist cooldown 20 --> 10 seconds, and changes invocation

## Why It's Good For The Game

underpowered, tends to set the user on fire, almost unaimable without time stop, maybe i just need to git gud
also vibe check

## Changelog
:cl:
balance: nuclear fist buffed.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I feel like honestly, this is the kind of power you should be able to set your own invocation for, since it frankly has a good amount of meme material regardless of what you choose.

**Comment by silicons** [comment]
i'd do that if i had time to figure out how ;_;

**Comment by ghost** [comment]
ur just bad smh

**Comment by IronEleven** [comment]
I like "I CAST FIST" better.

**Review by Ghommie — APPROVED** [review]
Which "changed invocation"? I don't see any changed invocation.

**Pull request merged**
