### PR TITLE
Lowers Ephedrine and Morphine OD thresholds

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Lowers Ephedrine and morphine od's to be the same as their addiction, which is 30/25.

## Why It's Good For The Game
Lets.... not have smart darts be able to cause addictions alright?

## Changelog
:cl:
tweak: Ephedrine and morphine balance tweaks, Lowers od thresholds to 30/25 respectively
/:cl:

### CODE REVIEW

**Comment by bunny232** [comment]
I have to add on this is a cheap fix because I have no idea how to change smart darts to make them stop at the od or addiction threshold, whatever is lower.

**Comment by silicons** [comment]
@bunny232 what is the goal of this 
lowering od thresholds
or making smartdarts not work to addict people

if it's the latter the fix is making smartdarts check both thresholds and taking the smallest of each

**Comment by bunny232** [comment]
> @bunny232 what is the goal of this
> lowering od thresholds
> or making smartdarts not work to addict people
> 
> if it's the latter the fix is making smartdarts check both thresholds and taking the smallest of each

as i said in my comment, a cheap fix to make smart darts not addict

**Comment by silicons** [comment]
please fix smartdarts properly instead, ping me if you need guidance

**Pull request closed without merging**
