### PR TITLE
Removes mason rig crate

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Kev is a fucken lier. He said he would remove these and never did

## Why It's Good For The Game

Broken and unbalanced to the likings of the coder.
Useless for what It was intended for.
Was told that we would remove it by kev, he then never fucken did

## Changelog
:cl:
fix: MASON rig being in cargo
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
What's wrong with the MASON????

**Comment by YakumoChen** [comment]
How many times have you tried to remove this now?

**Comment by r4d6** [comment]
Gray, it is literally, objectively, the BEST hardsuit in the engineering departement.

**Comment by YakumoChen** [comment]
It also costs as much as a Raven Battlecruiser.

**Comment by r4d6** [comment]
Its only downside is its price, which isn't that much of a problem, and the slowdown. That's it

**Comment by YakumoChen** [comment]
How often is it actually bought?
The slowdown is rather inhibiting as well.

**Comment by r4d6** [comment]
Almost never, but it is just because no one ask for it.

**Comment by GrayRachnid** [comment]
I used to buy it everytime I did fusion, because then I can repay cargo.

**Comment by r4d6** [comment]
Why did you stop then?

**Comment by GrayRachnid** [comment]
I stopped doing fusion or messing with the SM. Started playing jobs other than engineering.

**Comment by silicons** [comment]
I forgot to do rebalances like making unmutable slow not a thing.
One sec.

**Comment by silicons** [comment]
Pending discussion on discord.

Bottom line is a no from me simply because none of the assets are **yours**. You should understand by now that code you PR are no longer sole yours and "the original coder not liking it" is not a reason at all for removal. It's pretty useful for me, enough for me to block this. I never said I'd remove them, I said I'd rebalance them unless I'm misremembering, because the last time I was damn well opposed to this.

**Comment by Trilbyspaceclone** [comment]
It should be removed @kevinz000

**Pull request closed without merging**
