### PR TITLE
Recolorable Guns and more ballistics for Security

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Added the Mk.37 pistol, comes in P variants for the Captain (recolorable), S variants for security (preset color scheme), and F variants for foam force memes (recolorable)
add: Added the Model D Energy Gun for the HoP and Captain (replaces the default egun)
imageadd: added all the sprites for the Mk.37 and Model D
/:cl:

The addition of recolorable guns will give players a slight amount of customization for somewhat mundane stuff, and more ballistics for security has been a long requested addition.

The armory has been made somewhat more cramped to accommodate the changes.
dreamseeker_2017-10-19_18-02-05

The Model D Energy Gun is functionally and statistically identical to the regular egun, safe for the addition of a stun mode that fires taser shots, of which it gets 5 of from a full charge. It replaces the egun that the HoP and Captain get normally. It's coloured a very dark grey by default. (refer to bottom row of image)
dreamseeker_2017-10-19_18-51-48

The Mk.37 pistol fires 9mm rounds out of its own magazines. It is incompatible with regular 9mm magazines. 2 ammo types spawn by default: Frangible, and Rubber. Frangible bullets have similiar stats to the detective's bullets, but lacks knockdown. Rubber bullets have knockdown, but lack the high damage and deals somewhat less stamina damage. These ammo types may require rebalancing. More ammo can be made in the autolathes, and lethal 9mm bullets can be placed into the magazines. Security gets 3 S variants in the armory, and the captain gets 1 P variant in his locker, in addition to the egun.

The F variant of the Mk.37 is simply a foam toy. It has all the recolourability as the P variant, and can be differentiated by the blue grip bit.
dreamseeker_2017-10-19_19-01-23

dreamseeker_2017-10-19_15-37-47

While the items have been tested to not runtime or cause any issues, they may very well have some balance issues. Such issues should be discovered fairly quickly as soon as the update is applied onto the live server, and hopefully be quickly patched out.

### CODE REVIEW

**Comment by cebutris** [comment]
I appreciate what you're doing here, and the sprites look nice, but at this point this feels like needless gunbloat

**Comment by Michiyamenotehifunana** [comment]
Absolutely valid point, and especially true for the Mk.37, but the Model D at least serves to emulate the Advanced Laser Pistol the Captain and LT used to get in 5th port, despite the eg- ah, goddamnit, you're right. Fuggit, I have absolutely no excuse for this aside from SNOWFLAKE GUNS FOR SNOWFLAKE PEOPLE.

**Comment by cebutris** [comment]
I mean, there already exists two guns that have all three main fire modes (disabler, taser, laser), the HoS's gun, and the tacticool energy gun that ERT Security members get. If you removed disable from the Model D and just made it a taser/laser, then it would be a more accurate version of the Advanced laser Pistol

**Comment by cebutris** [comment]
Also the idea of recoloring guns is 👍

**Comment by Michiyamenotehifunana** [comment]
Blammo, now the HoP and Captain gets an ALP analog.

**Comment by Michiyamenotehifunana** [comment]
...should I just give it the Tactical Egun's stun electrodes which consume half the power and let it shoot 10 shots instead of 5?

**Comment by Michiyamenotehifunana** [comment]
Now even the model D's inhands are recolorable! Oh, and the Model D actually has unique inhands now. Mk.37 probably won't get one because pistol inhands are literally 8 pixels.

dreamseeker_2017-10-20_22-31-11
dreamseeker_2017-10-20_23-05-21
dreamseeker_2017-10-20_23-06-34
dreamseeker_2017-10-20_23-08-04

**Comment by Poojawa** [comment]
The taser mode needs a revert, only disablers and lasers for the regular guns. Especially when you just need one it to suddenly lethal someone to death.

And honestly, there needs to be slightly higher contrast around the outlines for gun mode now that I'm lucid and actually looking at them more. Information is really, really important, you should be able to easily identify which intent the user's E-gun is on at a quick glance.

**Comment by Michiyamenotehifunana** [comment]
And now it's disabler/kill only and has inhand sprites DRASTICALLY more obvious than even the default egun's.

dreamseeker_2017-10-21_13-22-15
dreamseeker_2017-10-21_13-22-25
dreamseeker_2017-10-21_13-24-11
dreamseeker_2017-10-21_13-25-06

**Review by Poojawa — APPROVED** [review]

**Comment by silicons** [comment]
Ballistics are a huge nerf to security...

**Comment by Poojawa** [comment]
Not if they're loyalty pin'd. Honk.

**Comment by Michiyamenotehifunana** [comment]
And now sec's Mk.37s are loyalty pinned! The captain's Mk.37 also gets the Judge Dredd pin. Will probably be replaced with something sane if players abuse it.

The Mk.37P's recolor menu is now no longer spammy.
dreamseeker_2017-10-23_17-43-44

The Model D's sprite has some minor changes: The barrel is now outlined.
dreammaker_2017-10-23_18-08-23

Makes quite the difference in game:
dreamseeker_2017-10-23_18-04-02

**Comment by Michiyamenotehifunana** [comment]
Aaaah shit, did I fuck up the map even more with that?

**Comment by deathride58** [comment]
https://github.com/Michiyamenotehifunana/Citadel-Station-13/blob/df524ddaa6135d018161226466e09728ce4f5bfd/_maps/map_files/BoxStation/BoxStation.dmm Here's the version of Boxstation you'll want to replace the one in your branch with in order to (Hopefully) revert the map changes proper.

**Comment by Michiyamenotehifunana** [comment]
Holy shit it worked

**Pull request merged**
