### PR TITLE
adds a neutral quirk 'food critic' which lets you see food quality on examine

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
for anyone who isn't aware food has quality which scales off things like machine upgrades, family knife, cutting your meat in the kitchen (or using an upgraded gibber), high potency ingredients, etc

it's just some nice flavour stuff to be able to see the exact quality i guess.

(and yes, this is tested.)

## Changelog
:cl:
add: adds a neutral quirk 'food critic' which lets you see food quality on examine
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Should probably be a 1 point quirk considering it simply gives you an advantage and there is zero reason not to take the quirk, as opposed to all other 0 point quirks.

**Comment by timothyteakettle** [comment]
it's not really an advantage which is why i put it as 0 points, you can tell the quality of the food by just biting into something you wouldn't normally like, and if you like it, hey presto it's above 90

**Comment by Linzolle** [comment]
alternatively you could make this a trait that cooks start with perhaps

**Comment by timothyteakettle** [comment]
not a bad idea i think i'll do that

**Pull request closed without merging**
