### PR TITLE
Makes limb grower better

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title.

## Why It's Good For The Game
Makes limb grower not as useless like they usually are
Pictures ahead:
Menu:
image
Options:
image
Emagged:
image

## Changelog
:cl:
refactor: Changes the limb grower a lot.
fix: "Limb" costs on limbgrower are actually displayed like it was meant to all along.
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
u are really allowing dipshit MD/chemist to freely print out 500 dicks to throw at people

**Comment by LSommers** [comment]
> u are really allowing dipshit MD/chemist to freely print out 500 dicks to throw at people

To be fair, have you seen what assistants do with the horny vendor?

**Comment by MrJWhit** [comment]
If someone's going around chucking dicks and stuff from the horny vendor, you should tell someone.

**Comment by R3dtail** [comment]
Oh this is awesome, this makes it actually useful.

**Pull request merged**
