### PR TITLE
Old Yeller: Citadel Edition

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Old Yeller'd dog borgs.
/:cl:

let's go down the list here:

### loader borgs

these are just a reskinned engineering borg with a bar of soap, come on, their existence isn't justified in the slightest, just play engineering borg

### security dog borgs:

oh god this is bad
let's go down the module list:
1. dogborg cuffs, these duplicate existing cuff functionality for no reason while also not being up to date with the latest checks for it, these appear to be direct upgrades from the zipties that secborgs already get, they're gone now, oh and they're a 3 second cuff
2. big jaws: why does an ASIMOV security borg need to start with a 12 force IS_SHARP melee weapon
3. nose module: this is a complete copypaste of the default analyzer
4. tongue module: same as above but for soap, when you could of just replaced the strings with an assoc list or something
5. sechailer: yeah this is pretty standard no complaints here
6. delivery bags: what the hell, borgs did not need backpacks
7. disabler: also pretty standard
8. emag laser: same as above
9. POUNCE MODULE: who the fuck thought a ranged telescopic baton was a good idea lmao

### medical dog borgs
1. jaws, again, less damage and i dont recall if they're sharp but its an ASIMOV borg, come on
2. delivery bag, same issue
3. nose and tongue: same as before
4. health analyzer: at least this is standard equipment
5. sleeper: I checked the code for this and jesus christ this is awful it's a straight fucking copypaste of the sleeper code, oh my god, this needs to go
6. shockpaddles: oh yeah let's just give it a free defib why dont you
7. crew monitor: eh thats normal
emag: >>>POUNCE
"gee bill we got a medical cyborg, what should we give it on emag"
"let's just give it a free 4.5 second ranged stun to combine with the free brute damage module it has :D"

### borgi
hahahahahahahaha these are even more useless than service borgs, wow

# the verdict

dogborgs are gone for being OP copies of previous borg modules

the creator also:
1. apparently isnt even here anymore
2. left a bunch of passive aggressive comments in the code when asked to nerf stuff anymore
3. this is the laziest way to add a new type of borg or subclasses of existing modules ever

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
Goof, back at it again with those bait PRs

**Comment by Iamgoofball** [comment]
@deathride58 that's one extended kneejerk

@RogueSteampunker >bait

bait would be opening this with no description

**Comment by silicons** [comment]
Alright guys, I think we need to take Goof out back..

**Review by deathride58 — CHANGES_REQUESTED** [review]
This won't even fuckin compile goof

**Comment by Iamgoofball** [comment]
i'm working on it

**Comment by RogueSteampunker** [comment]
@Iamgoofball It's bait cause you aren't as hidden of a meme as you think you are, Goofy boi. Now, be a good boy and follow Kev to the shed, so we can take care of ya

**Comment by Iamgoofball** [comment]
i'm not afraid of angry furries trying to dox me

**Comment by silicons** [comment]
@Iamgoofball i'm one of the only people who do not like dogborgs and i will be frank with you and tell you that their biggest utilities is erp outside of the pounce piercing some forms of blocking ranged stuns have a nice day

**Comment by silicons** [comment]
also the jaws being used to break windwos is pretty hilarious imo

**Comment by Poojawa** [comment]
Nose module -> Fluff version because dogborg
fetch module -> only one item, could probably be given weight class limits
cuffing could use a duration increase. simple enough. 
Pounce is probably the only real point of contention, but with the rework they're more in line with what can be decently sensible 
 Plus a riot shield defeats the pounce, so.

**Comment by Iamgoofball** [comment]
>Fluff version because dogborg

Still copypaste, sorry my dude

>only one item, could probably be given weight class limits

the borg could also just right click the item and pull it, no need for the code here

>cuffing could use a duration increase. simple enough.

thats fair but why do that when you could just use normal secborg

>Plus a riot shield defeats the pounce, so.

this is why you use a stun baton

**Comment by Poojawa** [comment]
Oh, I wasn't aware the modules had to be direct copies  of currently existing borgs. 8^)

**Comment by Iamgoofball** [comment]
yes, the thing is that all your proposed nerfs just bring them straight back to being regular versions of the borgs, at which point **why keep it as a separate thing when you could just remove them or make them a reskin ala service borg**

**Comment by CameronWoof** [comment]
We don't even _have_ the fetch module, which is evidence enough that you're ill-informed about these borgs entirely.

Medihounds are designed for emergency medical attention; they're EMTs. They swap out the traditional borg's suite of surgery tools for their sleeper and a defib.

You're spot on about janidogs, though.

**Comment by deathride58** [comment]
If you've actually played on cit, you'd know they're pretty underpowered compared to the normal borgs, which are overpowered against anything that doesn't have a flash.

**Comment by Iamgoofball** [comment]
>We don't even have the fetch module, which is evidence enough that you're ill-informed about these borgs entirely.

then why is it defined in the module m8

**Comment by CameronWoof** [comment]
Why are you making meme PRs on a codebase you don't even play?

**Comment by Iamgoofball** [comment]
>he thinks this is a meme module

**Comment by cebutris** [comment]
On this episode of Coders Never Play....

**Comment by Iamgoofball** [comment]
>code/modules/mob/living/carbon/human/life.dm:121:error: /obj/item/device/dogborg/sleeper: undefined type path

>code/modules/mob/living/carbon/human/life.dm:121:error: 

>life.dm

# i want names

**Comment by Poojawa** [comment]
8^)

**Comment by Poojawa** [comment]
Vore code my dude.

**Comment by silicons** [comment]
< : ^ )

**Comment by deathride58** [comment]
🍿 😹

**Comment by Iamgoofball** [comment]
>vore code

**Comment by cebutris** [comment]
Bot hates memes

**Comment by Poojawa** [comment]
He didn't even test his changes

smh

**Comment by Iamgoofball** [comment]
>when you find dog borg code in 4 different places in life.dm

**Comment by Poojawa** [comment]
> needs a tgui recompile

**Comment by GhostEcho** [comment]
The reaction to this is hilariously expected, but a PR that is agreeable

**Comment by deathride58** [comment]
Ya this won't sit well with the community at all, it'd be a much better option to nerf dogborgs harder instead of removing something that's been part of Citadel's culture for years.

Taking this PR out back.

**Pull request closed without merging**
