### PR TITLE
why did i touch saycode - allows people to use asterisks, like god intended

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
removes the thing that uses asterisks for custom sayverbs
## Why It's Good For The Game
i hate hate hate not being able to use *
## Changelog
:cl:
tweak: Asterisk custom-say verbs are no more.
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
If the thing is that you want to use *s again, shouldn't we just assign this feature to a different symbol? Or is there more reasoning to this than that?

**Comment by DeltaFire15** [comment]
I dislike the removal of this, considering it's a pretty neat thing to have. What do you need asterisks for anyways?

**Comment by Hatterhat** [comment]
it gets in the way of shitposting in deadchat, how else am i supposed to call someone a g*mer

**Comment by Hatterhat** [comment]
putting it on another symbol would be an interesting idea i guess

**Comment by silicons** [comment]
unnecessary atm

**Pull request closed without merging**
