### PR TITLE
please stop using explosive holoparasites to make instant kill toolboxes

### PR DESCRIPTION
**Pull request by silicons**
stop

### CODE REVIEW

**Comment by necromanceranne** [comment]
How exactly are they picking up the object? TK?

**Comment by lolman360** [comment]
it doesn't detonate if the stand user touches it i thought

**Comment by necromanceranne** [comment]
They can't touch it at all. Or shouldn't, anyway.

**Comment by Wilchenx** [comment]
killer queen already touched the code

**Comment by silicons** [comment]
@necromanceranne good point

**Pull request merged**
