### PR TITLE
Minor captains closet cleanup.

### LINKED ISSUE #10286: captain's locker has too many shitty snowflake items
## Reproduction:
read above, captain locker has so many clothing items in it that some items spawn outside of the locker upon map load because it's over the locker's carrying capacity

recommendation: pull the clothes vendor thing but for captain, or make it so carapace and hat can be reskinned

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Removing one zipties from the captain locker. 
They should get a personal clothing vendor at some point, as well as get a pet for each station map (maybe a red panda and not the most boring Renault) and not only Delta/Meta, cause that pet collar and carrier in their closet is kinda useless too ngl.

## Why It's Good For The Game
This will close  #10286.

## Changelog
:cl:
del: Removed an old pair of zipties from the captain closet.
/:cl:

### CODE REVIEW

**Comment by Linzolle** [comment]
don't like the probability on the beret color to be honest

**Comment by Ghommie** [comment]
The closet is so bloated with wardrobe stuff that a captain personal autodrobe is a necessity. But I don't have time right now, it's late and christmas time.
Feel free to remove more useless crap if you wish. Later.

**Comment by davidchan13** [comment]
Proper vendor would be the ideal choice, though moving some of Captain's cosmetic gear to a second closet like the HoP has might also be an option without removing options from snowflakes, I mean Captains.

**Comment by Seris02** [comment]
I don't like the probability on the berets either, seems like a stupid idea, since both were added to be worn and people like wearing different ones.

**Comment by silicons** [comment]
@Ghommie yo gamer can you just make this a reskin thing or if your'e not doing a wardrobe

**Comment by Ghommie** [comment]
Yo, just removing zippies now, and I don't want to self-merge.

**Review by Linzolle — APPROVED** [review]

**Comment by Linzolle** [comment]
doesn't need zipties anyway if he just has sec access to get handcuffs

**Pull request merged**
