### PR TITLE
sorry gamers, no more self healing with a medbeam

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

someone said this would be an issue if i let people disarm-intent-shoot themselves

## Why It's Good For The Game

unintended behavior

## Changelog
:cl: silicons
del: no more self healing with medibeam guns
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
time to just buy medkit instead 4head

**Comment by lolman360** [comment]
cringe

**Comment by Ragolution** [comment]
The way I read it, this prevents you from healing yourself by sticking it in your mouth. If so, that seems kinda silly.

**Comment by ghost** [comment]
But this removes "Ha ha ha! Oktoberfest!".
:(

**Comment by Linzolle** [comment]
> 
> 
> The way I read it, this prevents you from healing yourself by sticking it in your mouth. If so, that seems kinda silly.

pretty sure that is also unintended

**Comment by Ragolution** [comment]
> > The way I read it, this prevents you from healing yourself by sticking it in your mouth. If so, that seems kinda silly.
> 
> pretty sure that is also unintended

I don't know that I agree.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
