### PR TITLE
tg port - Radioactive contamination now makes objects glow green. radiation glasses are slightly less useless. also, mobs are now vulnerable to contamination

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

rad glasses now show text more clearly

## Why It's Good For The Game

radiation is cancer and not being able to see it is cancer

## Changelog
:cl: silicons, tg port
add: radioactive contamination now makes objects glow. radiation glasses show information more clearly
balance: mobs are once again able to be contaminated by radiation
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
>rads make things glow

why they're rads they're not visible

not everything is coated in phosphors, kevin

**Comment by silicons** [comment]
@lolman360 because invisible radiation killing the round for the nth time is quite literally cancer

**Comment by rossark** [comment]
Atmosia moment... could make them visible only through rad glasses if it's too annoying? I haven't played engineering but rads aren't seen that often...usually...still, this PR is  the coolest.

**Comment by MrJWhit** [comment]
"mobs are once again able to be contaminated by radiation"
:)

**Comment by Ludox235** [comment]
*puts on engi mesons on rad mode
There, you can see the rads.

**Comment by Tupinambis** [comment]
> Radiation is cancer.

I mean you're not wrong...

**Comment by silicons** [comment]
@MrJWhit now they'll glow green so you know who to beat up

- quote from tg player

**Pull request closed without merging**
