### PR TITLE
Bring abductors up-to-date with /tg/.

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
More big updates related to them, oh boy. I don't think I've missed any of the latest updates to abductors but lemme know if I did.

## Why It's Good For The Game
Makes abductors even more interesting and fun to play with.

## Changelog
:cl:
add: Abductor chem dispenser, and added it to the abductor console.
add: "Superlingual matrix" to the abductor console. It's the abductor's tongue. Can be used to link it to your abductor communication channel and then implanted into a test subject.
add: Shrink ray and added it to the abductor console.
soundadd: Shrink ray sound effect (its the fucking mega man death sound)
add: special jumpsuit for abductors
imageadd: abductor jumpsuit, including digi version if a digitigrade person somehow manages to get their hands on it. sprites for the shrink ray and chem dispenser.
add: new glands to play with, including the all-access gland, the quantum gland, and the blood type randomiser.
code: split every gland into its own file instead of all being in one file
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
It doesn't compile because of a single brain trauma variable ol citadel still doesn't have. Nice.

**Comment by Linzolle** [comment]
> 
> 
> It doesn't compile because of a single brain trauma variable ol citadel still doesn't have. Nice.

Where is this issue? It compiles fine for me locally. edit nevermind found it

**Comment by Linzolle** [comment]
god damn it if I want tinfoil hats to work correctly I have to fuckin update the antimagic component which had a PR that ended up being closed...

**Comment by Linzolle** [comment]
oh boy that merge did some wacky stuff with the icons...

**Comment by ghost** [comment]
this could use a merge if it's ready @Putnam3145

**Comment by Linzolle** [comment]
> 
> 
> this could use a merge if it's ready @Putnam3145

its been ready for like a month lol i just resolve merge conflicts every time they come up

**Review by Putnam3145 — APPROVED** [review]
transformation might be a bit griefy but otherwise seems good

**Pull request merged**
