### PR TITLE
regarding malf ais, apcs, space, and engineering cyborg grippers

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

player made areas are no longer valid malf hack areas

## Why It's Good For The Game

image

## Changelog
:cl: silicons
balance: player made areas are no longer valid for malf hacking
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
emergent gameplay

**Comment by BlackMajor** [comment]
Personally I'd do something wild like making power gained based on area size so they're incentivized to hack the larger areas such as hallways etc.

But this is a good fix too.

**Review by BlackMajor — DISMISSED** [review]

**Comment by Ludox235** [comment]
This has been in for god knows how long and it's now you nerf it :joy:

**Comment by BlackMajor** [comment]
> This has been in for god knows how long and it's now you nerf it 😂

Most engiborg players didn't know they could mount APC's without the grippers.
Now that it's more intuitive, it's happening more often.

**Comment by Ludox235** [comment]
> 
> 
> > This has been in for god knows how long and it's now you nerf it 😂
> 
> Most engiborg players didn't know they could mount APC's without the grippers.
> Now that it's more intuitive, it's happening more often.

Sucks, I guess.

**Comment by YakumoChen** [comment]
Emergent gameplay don't remove

**Review by Ghommie — APPROVED** [review]
Lovely. Malf AIs still need a buff for their core toh.

**Comment by Ghommie** [comment]
Now I'm sad.

**Pull request merged**
