### PR TITLE
[potentially hugbox as shit] poplocks loneops to 15 players

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

Same reasoning as the hijack PR.
While I agree with the station getting punished for not securing the disk, there's nothing to gain by lowpop rounds getting nuked by this when there's barely even anyone around able to secure the disk.

## Changelog
:cl:
balance: loneops are now poplocked to 15.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Yeah I fully disagree on this one.

**Comment by keronshb** [comment]
The rounds are already getting increasingly boring as is, why lock something that ends them early?

**Comment by ghost** [comment]
> The rounds are already getting increasingly boring as is, why lock something that ends them early?

nuke ops are dumb

**Comment by shellspeed1** [comment]
Probably a good idea.

**Comment by silicons** [comment]
working on a more elegant solution to this at some point.

**Pull request closed without merging**
