### PR TITLE
Removes fireball from the game.

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Makes wizard no longer able to pick fireball.

## Why It's Good For The Game

Me big wizard highly creative shoot stun ball at enemy to make horizontal

## Changelog
:cl:
del: Removes fireball from wizard spells.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
The explosion knockout to knockdown tweak from tg should be ported instead.
Salt.

**Comment by RogueSteampunker** [comment]
Something something salt joke something.

In all seriousness, come on. If Ei Nath hasn't posed much an issue, why does the spell that more often than not just blows up in the wizard's face suddenly in need of removal?

**Comment by ShadeAware** [comment]
If there was a textbook example of a salt PR, this is it.

**Comment by Putnam3145** [comment]
what the fuck why is this still open

**Pull request closed without merging**
