### PR TITLE
Auto OOC

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Adds Auto-OOC:
Turns off OOC:
1. When you live again.
3. When the round starts.

Turns on OOC:
1. When the round ends.
2. When you die.

## Why It's Good For The Game

I got asked to make this, here it is, it's a thing for people who can't be bothered turning OOC on and off again.

## Changelog
:cl:
add: Auto ooc
admin: changed "assume direct control" from m.ckey = src.ckey to adminmob.transfer_ckey(M) so it works with auto ooc
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
I'm not smart enough to read this code, is this client-side or server side?

**Comment by ghost** [comment]
client

**Review by deathride58 — APPROVED** [review]
OOC is pretty cancerous sometimes and this is a good PR that lets people escape it without getting rid of it entirely.

**Comment by MrJWhit** [comment]
This being a personal choice, and being default off, I have no problem with. Sounds good to me.

**Comment by Ghommie** [comment]
Resolve conflicts and it can be merged

**Pull request merged**
