### PR TITLE
Degrading Riot Darts

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
[Changelogs]: Each time a riot dart is shot, it will do five less stamina damage with the next shot. This is meant as an alternative to #5939 #3568 

:cl: ZeroNetAlpha
balance: Foam Riot Darts will now loose 5 stamina damage every time they are re-used until they turn into a regular foam dart.
/:cl:

[why]: I don't want riot darts to be essentially removed completely from the game, so I propose an alternative. There'll be another PR coming soon that moves ammo to the sec protolathe.

### CODE REVIEW

**Comment by CameronWoof** [comment]
Does not solve the problem. They will just waste more station resources printing more grief darts.

**Comment by ZeroNetAlpha** [comment]
> There'll be another PR coming soon that moves ammo to the sec protolathe.

Like I said in the PR post. This is a two part special.

**Review by silicons — APPROVED** [review]
Very copy-paste and bad implementation but whatever.

**Comment by silicons** [comment]
Actually you know what I think this needs a rethink since the combat update.

**Pull request closed without merging**
