### PR TITLE
Research Directors are now empowered with the ability to supplex rods.

### PR DESCRIPTION
**Pull request by silicons**
This isn't a meme.

### CODE REVIEW

**Review by Trilbyspaceclone — COMMENTED** [review]
line 51	var/mob/living/wizard
 code/modules/spells/spell_types/rod_form.dm
Remove line 31	var/mob/living/wizard

ADD to lines 104 - code/game/objects/structures/flora.dm
/obj/structure/festivus/anchored
	name = "suplexed rod"
	desc = "A true feat of strength, almost as good as last year."
	icon_state = "anchored_rod"
	anchored = TRUE
https://github.com/tgstation/tgstation/pull/40774/files

**Comment by Coolgat3** [comment]
Can we have the supplexed rods turn into strip dance poles?

**Comment by Ragolution** [comment]
when are we getting this blatant nerf to wizards

**Comment by deathride58** [comment]
MAKE IT COMPILE

**Pull request closed without merging**
