### PR TITLE
[TESTMERGE FIRST] Disables halloween.

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Just stops loading the halloween files.

## Why It's Good For The Game

It's the middle of November, take down the damn decorations, the HOA's gonna start complaining.

## Changelog
:cl:
del: Halloween's over.
/:cl:

### CODE REVIEW

**Comment by Thalpy** [comment]
You don't need to remove Jacq and Barth, they don't activate unless it's halloween and have a special handler if they spawn outside of halloween.

**Comment by Thalpy** [comment]
Actually maybe I should check over that.

**Comment by ghost** [comment]
the jacq and barth stuff has not been spawning past their due dates in-game

**Comment by Thalpy** [comment]
Mmhmm! But you can get her from gold cores, but she just says hello if you do.

**Comment by Putnam3145** [comment]
already fixed by https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9807

**Pull request closed without merging**
