### PR TITLE
Engineering Suit storage Magboots.

### PR DESCRIPTION
**Pull request by ganglyalexander**
Not that great of a programmer when it comes to SS13, but here goes nothing....

 This file uploaded will fix the engineering Suit Storage, they will now come with engineering Magboots.

Small fix but I'm trying to get used to this github stuff.

Edit: The map edit was adding the button for secure storage that the engineers can reach. This was added into the pull request on accident, but the button is complete with access restrictions of an engineer

Small little gif I took real quick  :P

### CODE REVIEW

**Comment by unusualcrow** [comment]
that'll do pig, that'll do

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=rjQtzV9IZ0Q

**Comment by ganglyalexander** [comment]
ahhhhh. Sounded familiar but couldn't quite put my finger on it   XD

**Comment by TalkingCactus** [comment]
What was the map edit?

**Comment by ganglyalexander** [comment]
Didn't notice that the new upload affected pull request for magboots.

That map edit was adding the Engineering Secure storage button for the station engineers. The button is complete with access requirements of engineering and opening the blast doors.

I didn't mean for it to get added to the pull request, I was just using github as a method to backup any progress I made.

**Comment by ghost** [comment]
If you want to separate something from the branch your PR is on, make a different branch. PRs take every commit from their branch.
In fact, you should usually make a new branch for every PR you make and delete it when the PR is merged/closed.

**Pull request merged**
