### PR TITLE
The Holdout Update: How I learned to stop whining, and aim a pocket pistol.

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
 "Boss. Boss! We got a problem, boss!"
 "Frank, I swear to the Mother Mary herself, if this isn't urgent, I'll transfer you to the frontier myself. **Now**, what is it?"
 "Something went wrong with our supply order. Come, look at this shit!"
 
 A box, filled to the brim with boxes and boxes of guns, from .38 to .45-70, laid in the cargo bay. There's only one problem.. they are **not** the correct guns. No revolvers, just.. pocket pistols. 
 
 "So, just one crate? That's not so ba-"
 "I wish it were just _one crate_, but it seems somewhere down the line, someone changed the fuckin' orders to these.. things!"
 A sigh, and the sound of arthritic fingers popping as they curl around the handle of one of the guns.
 
 "Right. Then this is what we're gonna do. Get this shit unloaded, do not tell **anyone** about this, not yet anyway. I'll make some calls to our... subsidiaries, shall we say, and see if we can't turn this round. You will let me handle this, Frank. You couldn't sell eyesight to the blind."
 
 Shitty story aside, this PR ports and adds a few neat things to the game. 
 Derringers:
 Four guns, three calibers.
 The .38 derringer can be purchase from cargo, with the right circumstances, even being private purchasable, or purchased from the black market uplink for a significant upcharge, as well as the high odds of not actually getting it.
 
 The .357 derringer can be purchased from the uplink, which comes in a sleek cigarette pack! On top of this, there's a 1% chance, with every purchase of the package of cigarettes, you can get a **golden** derringer! It has a very distinct sound, though, and is extremely ostentatious, what with it being made of gold.
 
 The Gunslinger's Derringer cannot be directly purchased by normal traitors, and never obtained by the station in any normal way. It comes in a rather peculiar looking cigarette container, and uses an extremely premium ammo, known as .45-70 Govt. Which government? That remains to be seen, but it packs quite a punch, even to people with significant armor. Try not to waste it, Operative, as the Gorlex Marauders are not keen on issuing more of this ammo.

Each derringer purchased through Cargo, or a syndicate uplink, come in a cigarette pack, that can also hold spare ammo, and always comes with one free smoke. Feel free to enjoy the smoke, or just print more ammo, it's really up to you. You **might** find that you can stash these things in the darndest places, too! 

Cargo Crates:
The Holdout Crate - 2000 credits
This crate is the primary way you'd be able to supply people pocket pistols. Each crate comes with three cigarette packs, containing one .38 derringer, four bullets, and one cigarette. It also comes with a free wallet, for the cargoman on the go. This crate requires you to hack the cargo console with a multitool to reveal, and will be under the Armory Tab. Speaking of...

Esoteric Armory Shipment: - 10000 credits
Curiously, a gun collector, who is rather... sympathetic to the syndicate's cause, has agreed to use funds to procure some rather intriguing arms, ones that don't often see their way to the station. Due to the rarity of said weapons, it comes at a premium to anyone who'd deign to buy it, and you only get **one** gun per crate.

Current Possible Results:
Nagant Revolver
"Mare's Leg" Lever Action
Stechkin APS
"Robust Gold Cigarettes"
The Golden Revolver

Due to the difficulty of acquiring these arms, and lack of love for Nanotrasen, agents will need an E-mag to contact this collector, and plenty of cash up front to obtain one of these guns.

Credits for the port:
https://github.com/Whitesands13/Whitesands/pull/80 (AsciiSquid)
TripleZeta/TetraZeta for the updated sprites (and eventually, the Gunslinger's Derringer)

## Why It's Good For The Game
.38 ammo is so versatile, yet is only used by one (1) obtainable gun, and has two whole cargo orders that go oft unused. This adds an option for crew that isn't as good as the detective's revolver, but still is rather fun.

Cargo also has a distinct lack of interesting e-mag crates now-a-days, this adds one without it being hyper gaming loot like Null Crates +were+. The sheer cost to goods ratio would also be rather prohibitive for crew who got lucky and stole/acquired an emag, hopefully mitigating people spamming these crates to arm the station, over better value crates.

Prices can be adjusted over the course of a testmerge or two, should people either overpurchase or underpurchase things.

## Changelog
:cl: The0bserver, TripleZeta, and AsciiSquid
add: New, easily concealable weapons, chambered in .38, .357, and .45-70 Govt. Fun for the whole family!
add: Some smugglers seem to have acquired a high amount of .38 derringers, and are looking to offload them to those of gray morality, with no questions asked!
add: An enigmatic gun collector has seen fit to do special acquisition work for the Gorlex Marauders, selling the fruits of his labor for a premium price. If you have the right electomagnetic sequence, you might be able to contact him to acquire a piece of his armory.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
cool

**Comment by ghost** [comment]
Can't say I'm a fan of the crew being able to get more guns able to use .38 rounds. The detective's revolver is already extremely powerful, but if you can just buy it from a blackmarket uplink then that's even worse.

**Comment by TheObserver-sys** [comment]
The Derringer (the one from the black market uplink) does not come in a cigarette container with actual lethals, and only has two shots to its name. It comes loaded with a singular rubber bullet, of which you must manually reload, or obtain speed loaders from the seclathe. It is.. as it stands, nowhere near the lethality or strength of the actual detectives revolver, favoring concealability over effective killing speed. At best, you would need speed loaders to quick reload the gun, and access to lethals to make optimal use of it. There's also the fact that in the uplink, it's not even guaranteed that it: A. Appears, and B. You manage to get into the AI sat in time to grab the gun _as it is a valid location that items can be teleported to._

It should also be noted that I do *in fact* have plans to make them have a noticeable, but not absolutely dreadful fire delay, but that I'd like to see people use them first in a testmerge before I make such changes.

**Comment by ghost** [comment]
lmao i had a similar to that, not even that good, and it's lovely to see it in a way that is absolutely awesome
long live derringers!

**Comment by necromanceranne** [comment]
> Can't say I'm a fan of the crew being able to get more guns able to use .38 rounds. The detective's revolver is already extremely powerful, but if you can just buy it from a blackmarket uplink then that's even worse.

It's like 48 stamina for the rubber bullets. Not too outrageous compared to some weapons and bullets. And the lethal shot is 25, which is lower than a stechkin.

**Comment by ghost** [comment]
> 
> 
> > Can't say I'm a fan of the crew being able to get more guns able to use .38 rounds. The detective's revolver is already extremely powerful, but if you can just buy it from a blackmarket uplink then that's even worse.
> 
> It's like 48 stamina for the rubber bullets. Not too outrageous compared to some weapons and bullets. And the lethal shot is 25, which is lower than a stechkin.

You're forgetting there's also TRAC, hotshot and iceblox rounds in .38. This is on top of the fact that multiple people can now use .38 rounds on an easily concealable gun

**Comment by necromanceranne** [comment]
Those are security printed bullets that require tech. And also really don't do much good to anyone but security, especially TRAC. Moreso, if you're getting .38 derringers out of cargo, you can definitely get something scarier and bigger for less even if they're harder to hide. More importantly, more useful again the real threats you might come across, like someone with sec gear.

Someone with a gun is always going to have a distinct advantage. The issue with cargo guns is even getting one out of cargo without anyone noticing, and if you're getting one without anyone noticing, you can absolutely just get an autorifle and do more damage and nobody will know until you are already shooting. They fit into bags after all.

**Comment by TheObserver-sys** [comment]
I think the primary thing is, if you're in a situation where you need to be ready to kill people, are you going to spend time dealing with getting a funny concealable 2 shot pistol, or are you going to do the smart thing, and just hack the public autolathe for a receiver, and just make a maint shotty, which can use SLUGS to deal punishment? Sure, it's only one shot, but you can crank out a ton of 45 damage slugs and just kinda yeetmaster 5000 someone to death with them, or cripple limbs with them.

**Comment by TheObserver-sys** [comment]
This is, as far as I can see, ready for a testmerge, if maintainers want to throw it into that state, or just full merge it and have me balance them as the cards play out.

**Comment by R3dtail** [comment]
Crew shouldn't be able to just...easily get guns like this.  We already yell at people for buying guns unwarranted, and uh , we don't allow people to private order guns for a reason.

**Comment by TheObserver-sys** [comment]
Crew can already very easily get **better** guns than this, as with the agreed upon reversion of the awful makeshift shotgun nerf, which restored it to being some wood, a pipe, and some package wrapping. These are worse guns, but at a smaller formfactor. I can, if you want, remove the private buy on the derringer crate, but I am holding my ground on the emag crate, as 10K is a significant amount of capital, for a single, potentially good gun.

**Comment by Acer202** [comment]
These saved my character from sexual assault 10/10.

**Pull request merged**
