### PR TITLE
DNA-locked firing pins are now available under the Medical Weaponry node

### PR DESCRIPTION
**Pull request by jakeramsay007**
Available after already researching mindshield firing pins, adds some variety to pin usage for security weapons.

### CODE REVIEW

**Comment by YakumoChen** [comment]
Gun pins that require a specific implant to limit usage and allow for deep cover or flat out theft to use = good
Gun pins that make it impossible for anyone to steal your gun and use it = bad

**Comment by Poojawa** [comment]
imagine dna locking your department's mech.

**Comment by YakumoChen** [comment]
Mechs can be locked by ID access but it's a roundabout feature nobody ever remembers (and DNA lock should be removed)

But mechs tend to be KOS for anyone not authorized and are pretty big and obvious.

**Comment by nik707** [comment]
I kinda dislike DNA locking if I'm honest. @kevinz000 @deathride58 thoughts?

**Comment by silicons** [comment]
i dont like this

**Comment by silicons** [comment]
dna locking is lamer than mindshield pins being used so much sorry

**Pull request closed without merging**
