### PR TITLE
Krav maga leg sweep tweak.

### PR DESCRIPTION
**Pull request by Ghommie**
:cl:
balance: Buffed krav maga leg sweep stun and stamina damage. On the other hand, it's now unable to be used on already lying targets.
/:cl:

Another feature usefulness dunked by the stam rework, the krav maga leg sweep. Right now, it's hard to keep someone down with it (even with the related ui action button dragged near the center of the screen), whilst still being usable on lying mobs since it preceded the crawling feature (and the little tweaking of the pre-existin stun combat related features of the stam rework).

Values may need tweaking, but since it's not anymore spammable, and being the only stun method inherent this style, the 1 second hardstun sounds fair to me.

On a sidenote, I suppose sleeping carp needs some tweaking, since it doesn't hardstun anymore and is commonly bested by horizontal baton-wielding chumps et similar. But that may be done on another PR.

### CODE REVIEW

**Comment by Useroth** [comment]
`1 second hardstun`
Does it work like a real full-on stun or is it just 1 second guaranteed without standing up?

**Comment by Ghommie** [comment]
> 
> 
> `1 second hardstun`
> Does it work like a real full-on stun or is it just 1 second guaranteed without standing up?

full vanilla stun.

**Comment by Useroth** [comment]
That's a bit strong, for something you can't disarm someone out of, imo.
Also, on another note, is there any difference between the Knockdown and Stun procs, then?

**Comment by Ghommie** [comment]
> 
> 
> That's a bit strong, for something you can't disarm someone out of, imo.
> Also, on another note, is there any difference between the Knockdown and Stun procs, then?

Oh, guess there was some miscommunication then. Rather than "full vanilla stun", we should the basic sort of knockdown, the one preceding the stam system (and tgstation's mobility update done by kevinz with the proc name changed to Paralyze) where the affected is totally immobilized and flipped horizontal.
Stun(), rather, immobilizes the target but without flipping them horizontal (beepsky smash, high resistance headache symptom, CQC grab). Yea, this old naming pattern can confuse a bit, given its difference from the basic game terminology.

I guess I'll probably remove the hardstun if the user is crawling around, I agree it could obnoxiously null any upper hand, otherwise I'll buff the stam damage further more. But really we end up talking about a mere second.

**Comment by Useroth** [comment]
In my opinion, overall, the main purpose and niche for the gloves to fill is robusting unarmed prisoners while avoiding your taser/baton being disarmed off you if they get good RNG or manage to slip you. I think it would be better achieved with leaving the knockdown as it was, but adding a bit of straight stam damage to the mix, to make the person not able to stand up right away, but without the hardstun.

**Review by silicons — CHANGES_REQUESTED** [review]
disarm (0.01 second hardstun) + 20 more stam (not 45)

**Comment by Ghommie** [comment]
Going with 25 stam damage (plus the disarm) since it's not spammable on people already lying on the floor.
I hope you are ok with it.

**Review by silicons — APPROVED** [review]

**Pull request merged**
