### PR TITLE
Different combat mode message if user is on help intent.

### PR DESCRIPTION
**Pull request by Ghommie**
:cl:
tweak: A milder combat stance message will show up if the user switch combat mode on while on help intent.
/:cl:

Dedicated to the people switching combat mode on just to wave at other people or drumming the tables.
Sad.

### CODE REVIEW

**Comment by terranaut1** [comment]
What happens if you switch intent after toggling combat mode? Unless I'm stupid it looks like you can go into combat mode stealthily like this then which isn't good.

**Comment by Ghommie** [comment]
The combat 

> 
> 
> What happens if you switch intent after toggling combat mode? Unless I'm stupid it looks like you can go into combat mode stealthily like this then which isn't good.

Even so, stealthily dropping in combat mode is not even a real problem anyway, mobs moving sideways, backwaling etcetera is an already decent indicator regardless. The visible messages were humorically added months after it.

**Comment by deathride58** [comment]
A better way to handle this would likely be to make it so that being in help intent displays a "Urist McSpaceman looks alert!" message instead of a "drops into a combative stance!" message

**Review by deathride58 — DISMISSED** [review]

**Review by silicons — CHANGES_REQUESTED** [review]
please do what bhijn said because i feel like people will intent switch just to hide the fact they're entering combat mode which is what you usually do to melee someone effectively.

**Review by silicons — APPROVED** [review]

**Pull request merged**
