### PR TITLE
April sync

### PR DESCRIPTION
**Pull request by Poojawa**
fuck this one was annoying to grind through.

Recent as of 4/8 21:30 Texas time.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
texas time

**Comment by TalkingCactus** [comment]
Can you make one of these that merges from the bleeding edgy branch instead?

**Comment by Poojawa** [comment]
Probably. though this is also up so people know it is. :P 

And also to ensure travis compiles it without issues.

**Comment by Poojawa** [comment]
Icon preview is borked. refreshes upon saving, but it's 3 south facing icon 'pictures'. vanishes upon changing species/features. @TalkingCactus

**Pull request closed without merging**
