### PR TITLE
removes dildo

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
circuit assemblies

## Why It's Good For The Game
sex circuits are permabannable

## Changelog
:cl:
del: dildo circuit assemblies
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Yes.

**Comment by timothyteakettle** [comment]
remove the sprites

**Comment by ghost** [comment]
> remove the sprites

lazy webedit pr but i'm sure someone on skyratidel will have a use for it later

**Comment by timothyteakettle** [comment]
is there really a need for the mechanical dildo circuit sprite when we should remove circuits entirely anyway

**Comment by ghost** [comment]
> is there really a need for the mechanical dildo circuit sprite when we should remove circuits entirely anyway

true true true

**Comment by Ludox235** [comment]
image

**Pull request merged**
