### PR TITLE
raises miasma fusion power to 5,000,000 to compensate for the low specific heat

### PR DESCRIPTION
**Pull request by silicons**
I'm sure this won't go wrong.

And uhh if you're asking if this is a meme PR, it is but it's a more serious meme PR, I'll lower it/revert it if people suddenly murder every round with it.

### CODE REVIEW

**Comment by deathride58** [comment]
STRONGER HYPERNUKES??????????????????

**Review by deathride58 — APPROVED** [review]

**Comment by davidchan13** [comment]
So what's this meta gonna be, making 20+ unmonkies and killing them in a chamber set to siphon?

**Comment by Poojawa** [comment]
> So what's this meta gonna be, making 20+ unmonkies and killing them in a chamber set to siphon?

He just buffed miasma generation as well, so /shrug

**Comment by silicons** [comment]
porting tg fusion, let's do that first.

**Pull request closed without merging**
