### PR TITLE
Gives mineral storage access to those who need it

### PR DESCRIPTION
**Pull request by cebutris**
# DO NOT MERGE IF #5479 IS MERGED

:cl: Cebutris
add: Everyone who gets new mineral announcements should now have access to actually get those materials
/:cl:

[why]: Because why get announcements if you can't get them? I was originally gonna give virologists and chemists this as well but I learned they already have it **BUT ENGINEERS DON'T. WHAT IS THIS.**

Closes #5479

### CODE REVIEW

**Comment by cebutris** [comment]
Compiled but untested, as is tradition

**Comment by Poojawa** [comment]
Why do engineers have access to something the CHIEF Engineer is losing?

**Comment by cebutris** [comment]
If this PR goes through, the other one should be closed. They're alternatives to eachother, two different solutions to one problem

**Comment by deathride58** [comment]
@Poojawa Chief Engineer's access is untouched in this PR. This just adds mineral access for normal engineers, chief engineers keep their original access.

**Comment by Poojawa** [comment]
Well, barkeep doesn't really need it, but station engineers and atmosia techs could use it. so

**Comment by cebutris** [comment]
If the barkeep doesn't need it, why does he get mineral announcements?

**Comment by deathride58** [comment]
Bartender can use uranium to make nukacola, which is basically discount meth that lacks any lasting side effects.

**Comment by cebutris** [comment]
Not to mention all the other things they can do with uranium, plus some stuff with plasma and iron

**Comment by LetterJay** [comment]
Close one of these PRs. There's no reason to have two open like this.

**Review by deathride58 — CHANGES_REQUESTED** [review]
engineering.dm needs to be added to the .dme

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
