### PR TITLE
Reworked Bag of Holding Bombs

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Bag of Holding bombs were reworked into something less murderous. To put it short, the range was reduced, the singularity was removed, a new color scheme was added, and you are no longer killed when you use them; just injured.

Details:
BoH Bomb Range is now 4 instead of 6 (9x9 instead of 13x13).
You take 25 brute damage and 25 clone damage when you activate the BoH bomb, instead of just being gibbed.
Your all your limbs take 5 brute damage when you enter the portal (30 damage).
An extra random ladder to lavaland was added (4 ladders instead of 3)

## Why It's Good For The Game

Bag of Holding Bombs is 100% a grief feature. It is incredibly rare for any antagonist to use them for antagonist purposes. 90% of bag of holding bombs are used at the end on the shuttle, and the other 10% are used by people just griefing. This changes that so antags can now use them for antag purposes and makes them less of a dumb grief thing and more of an actual legitimate strat to use.

## Changelog
:cl: BurgerBB
balance: Reduced the range of Bag of Holding bombs, made them less lethal as well.
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
This PR makes tears ugly, and just makes BoH bombs lame. 
If you do want to change them, I recommend removing the instant 13x13 tear, and just replace it with the gibbing codebubble. Similarly to a singularity, it would travel randomly, but instead of eating the station, it could just leave a trail of tear turf in its wake. The codebubble itself could then, instead of gibbing, jettison all objects and mobs it touches away from itself at bluespace speeds (Very fucking fast). So fast in fact that getting hit by an object, or being thrown away from it, will do a fuck load of damage.

The tear itself could just randomly teleport you to literally any location that exists. Even z-1 if you want to get daring. (Imagine randomly teleporting into the nuke ops base).

I know I am basically ideamanning, but I think this would me a more creative and interesting approach, than what is essentially just a nerf to make boh bombing useless for anything BUT griefing.

**Comment by BurgerLUA** [comment]
If non-antags grief with it then they can be banned. The issue isn't that "people use it to grief", the issue is that "people solely use it to grief" because that is all it is good for.

**Comment by Sishen1542** [comment]
imagine making a salt pr to nerf something you died to in eorg

also the sprite is fucking ugly

**Comment by Ghommie** [comment]
The whole murdering nerf reasoning is comparable to "improving" the armory's usefulness by replacing its laser guns with laser tag versions.
Griefing doesn't equate to balance issues and falls under the rules jurisdition.
And the new blue is a punch to the sight.

The 4th latter is the only thing good here from what I see.

**Comment by BurgerLUA** [comment]
Two things I'm considering removing from this PR:

Reverting back to the old white chasm color and otherwise. I thought people would understand the references to nullspace/bluespace, but I was wrong.

Removing the clone damage. People don't think it would be viable as an antag tool since clone damage is difficult to repair. The reason why clone damage was considered is to prevent antags from constantly using it over and over again as clone damage is more difficult to fix than just a bunch of brute damage.

**Comment by Ghommie** [comment]
> I thought people would understand the references to nullspace/bluespace, but I was wrong.

I did understand the reference, but it still doesn't make up for its painful design. The byond the 4th wall reference was better though.

**Comment by BurgerLUA** [comment]
After a discussion, I will be removing the clone damage as well as the new sprites.

**Comment by R3dtail** [comment]
I'm not /much/ of a coder  but from an admin point of view we already heavily frown on folks BOHbombing, and excessive bombings in general.    This doesn't ...necessaril yseem like a great idea, especially with the fact that you're making it so that the person who does BOH bomb is more or less able to get away scotfree.  A little bit of damage, and being teleported into the rift in reality.  It doesn't sit well with me personally.  The extra ladder does seem pretty cool, both for adding another way for folks who fall into the BOH bomb to get out, and adding some "creative" options for navigation.  Everything else though doesn't seem like a great idea.

**Comment by BurgerLUA** [comment]
> I'm not /much/ of a coder but from an admin point of view we already heavily frown on folks BOHbombing, and excessive bombings in general. This doesn't ...necessaril yseem like a great idea, especially with the fact that you're making it so that the person who does BOH bomb is more or less able to get away scotfree. A little bit of damage, and being teleported into the rift in reality. It doesn't sit well with me personally. The extra ladder does seem pretty cool, both for adding another way for folks who fall into the BOH bomb to get out, and adding some "creative" options for navigation. Everything else though doesn't seem like a great idea.

From an OOC standpoint, Whether or not people get punished for Bag of Holding Bombs is largely irrelevant because this PR has nothing to do with the changing the frequency of people being punished  or reducing it. This PR is meant to make Bag of Holding Bombs more viable by antags who are looking to be more creative. Someone who randomly BoH bombs should be dealt with the same way as someone who maxcaps an area of the station and doesn't kill anyone while also randomly throwing bluespace crystals at people as a non-antag or objectives that don't make sense for them to do that.

From an IC standpoint, he person who did the bombing would receive a lot of damage. They'd get 55 brute damage while others would get 30 damage. That's a huge risk. That's like 2 e-sword hits right there. People argued that if you're not prepared either, someone could escape via a ladder if they're fast enough or just run around the exceptionally slow 55 damaged person trying to kill them.

What I expect to happen with this implemented is that people start to use it but stop because they're not robust enough to use it or they're really never in a position to use it. BoH bombs are a lot of risk with this new PR but give you quite a few unique advantages compared to other weapons.

**Comment by BurgerLUA** [comment]
Reverted the sprite changes and the damage as per's people request. Someone suggested that I rename the title because many people are reading the title and not the PR.

**Comment by Ludox235** [comment]
> This PR is meant to make Bag of Holding Bombs more viable by antags who are looking to be more creative.

The bag of holding bomb can already be used by antagonists who feel creative. There is something called Auto-cloners and xenobiology slimepersons. This PR just makes the bag of holding into something fucking useless.

**Comment by nik707** [comment]
@kevinz000 you're smarter with balance u look

**Comment by silicons** [comment]
ehh, actually an interesting nerf imo but honestly nah not needed atm sorry

**Pull request closed without merging**
