### PR TITLE
Update civilian.dm

### PR DESCRIPTION
**Pull request by B1gb3ast**
## About The Pull Request
Small QoL increase for shaft miners.

## Why It's Good For The Game
Now miners don't have to steal sec uniforms at roundstart anymore.
Unrobust bastards.

## Changelog
:cl:
tweak: added 5 melee and fire to explorer jumpsuits.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
This is straight up power creep for miners, even if it's small, it's still power creep.

**Comment by B1gb3ast** [comment]
> This is straight up power creep for miners, even if it's small, it's still power creep.

It's either this or nerfing security jumpsuit and buffing security armor.

**Comment by MrJWhit** [comment]
> > This is straight up power creep for miners, even if it's small, it's still power creep.
> 
> It's either this or nerfing security jumpsuit and buffing security armor.

But, why does mining _need_ to have security armor in the first place? They already have armor for the exosuit, or whatever suit they're using. This is just extra armor on top of it because... apparently everyone steals the sec jumpsuits? That's not great on the powergaming aspect, or good gameplay.

**Comment by r4d6** [comment]
When you are a miner, every bit of protection count, the sec suit has 10% reduction in melee damage received, while the miner suit has none, while the exosuit has 60 protection in melee, it stack, so no loses, and almost no one know that it even have bonuses. Even then, it get overlooked in favor of the SEVA which, while it jas like, 30% melee reduction, is ash-proof

**Comment by ZeroNetAlpha** [comment]
Every bit helps, sure, but why is _this_ the better way of going about it as opposed to... offering miners a jumpsuit upgrade they can buy for points instead of handing it to them on a platter?

**Comment by r4d6** [comment]
Simpler, easier and faster

**Comment by B1gb3ast** [comment]
> Simpler, easier and faster

Not just that, otherwise they can still just nab sec suits at round start. miners are powergamers and thats never gonna change.

**Comment by ZeroNetAlpha** [comment]
Simpler easier and faster, sure, but it also seems like laziness too. 

> Why work for something when I can just tweak something and give it to myself for free.

**Comment by B1gb3ast** [comment]
Okay I clearly didnt provide context.

At the moment miners just grab a security jumpsuit because it offers protection.

After this tweak, they would get a tiny amount of brute protection (still inferior to the security suit) and a tiny amount of fire protection. Fire is by far the worst protection, considering that lasers are laser damage and electricity is shock damage. It might aswell not even be there, but it may be just enough to safe their asses when they get pushed in lava or aggro the wrong ashdrake. 

I don’t even play miner. I just agree on the notion that its dumb that their suit, supposed to protect them, is identical to the normal mining jumpsuits except for the sprites when the flavortext says its made for protection from hazards. Now it actually protects from hazards.

Its a tiny amount, but a tiny amount should be enough to stop them from asking for jumpsuits from other departments.

**Comment by Trilbyspaceclone** [comment]
I dislike this power creep
At lest with sec jumps that takes RP/Stealing - as well as being powergaming
Cuz 60 + 5 + 15 = 80% 
And if they kill the drake its 70 + 20% or 90% now
Rather high levels for no reason. if anything we should be nerfing mining 
and now

**Comment by r4d6** [comment]
Almost no one know about the 60% protection o the exosuit, and no one use it anyway, because of 1. They do not know about the exosuit properties, 2. The SEVA suit's ash-proofness is too good to pass up, even if I think it has half the melee protection of the exosuit for double the ranged. 30 melee for 10 range for the SEVA, and 60 melee but 5 range for the exo. Also I think the normal explorer suit has 15%, which with the three goliath plates get that to 45% protection in melee.

**Comment by r4d6** [comment]
Also, where does that 15% come from?

**Comment by Trilbyspaceclone** [comment]
r4d6 bone tailsman, or skull crockpice

**Comment by Trilbyspaceclone** [comment]
Bone things	armor = list("melee" = 5, "bullet" = 5, "laser" = 5, "energy" = 5, "bomb" = 20, "bio" = 20, "rad" = 5, "fire" = 0, "acid" = 25)
So 5 + 10 = 15, or 5+5 = 10

**Comment by Poojawa** [comment]
power creep is power creep. 

and a big fat 👎

**Comment by cebutris** [comment]
If you're going to do a straight buff, be transparent about it. Descriptive PR titles are important.

And none of that "QoL" bullshit

**Comment by ktoma36** [comment]
I would suggest giving the suit a minor speed debuf as a tradeoff for the armor

**Comment by B1gb3ast** [comment]
>power creep.
>Miners grabbing security officer jumpsuits anyways
choose one

**Comment by lolman360** [comment]
just grab a sec jumpsuit if you want armor? i shouldn't be rewarded with extra armor as miner because i spawned in.

**Comment by r4d6** [comment]
You would not be rewarded with extra armor since you spawned as a miner. Sec would have _double_ that armor because they spawned as sec.

Also grabbing the sec jumpsuit because of the extra protection is a little bit of powergaming.

**Comment by B1gb3ast** [comment]
> You would not be rewarded with extra armor since you spawned as a miner. Sec would have double that armor because they spawned as sec.
> Also grabbing the sec jumpsuit because of the extra protection is a little bit of powergaming.

No-roleplay levels of powergaming at that, yes.

**Comment by lolman360** [comment]
>oh yes lavaland is very dangerous
>the most common way to get hurt is in melee
>i should wear this additional protection to be safe from a major source of injury

nrp?

it's not like
>oh yes I will take dragnet+shotgun+egun+aeg+magrifle as HoS because they all fit in my BoH

**Comment by silicons** [comment]
unnecessary, this isn't qol sorry ask security for a jumpsuit we don't need more of this for miners.

now if you want a kevlar item that does this for mining points, i'd be more open.

**Pull request closed without merging**
