### PR TITLE
adds the ability to pick body sprites (you can choose aquatic/avian sprites as anthromorphs!)

### LINKED ISSUE #13222: THE ABSOLUTE STATE OF MOTHS, or, how I learned to stop shitposting and finally make a formal complaint about the Poojmoth
**Formally, this is a feature request. However, it contains something of a bug report, in that some content complained about does not function as what I could fathom as in the intended manner. To the maintainers of this codebase, I dearly request that you consider this to be a _bug request_. I am requesting moths. Bring them back.**

# The Problem With Anthropomorphic Insect 
Simply put, moths on the Citadel codebase are in a disgusting state, left in it to rot after the otherwise much-needed species squash PR. The species squash PR existed in order to merge together the redundant Mammal clones together into Anthropomorph.  For whatever reason, this same PR decided to remove the Moth species and replace it with... Replace it with _a redundant clone of Mammal._ 

Here's what a Moth looked like before they were removed from Citadel, in a screenshot hastily taken from Beestation.
image

And now here's what the same Moth looks like, using the Insect species on Citadel.
image

The difference is striking, but one could simply say "deal with it", say they like the current head better, etc. That's fine, Citadel is all about options, right? Maybe a lot of people actually do like the alternate head better than the little plus eyes. Except... both before the change to insect, and now, Moths, Insects, and all the Mammal clones that were merged into Anthropomorph, have been able to select snout options, which includes the Bug snout. The Bug snout option is nearly identical to the head on the Insect species, except you can color the eyes using Tertiary color. Here's a Bug snout on aforeposted Example Moth Which Totally Isn't My Main Static, with eye color adjusted to be more noticeable.
image

So the snout is significantly better in most ways besides in that weird little black pixel that's in the corner. What is that, anyways? Oh, yeah, it's the eye pixel. You *can* adjust the eye color on an Insect without using the Bug snout that is otherwise identical to their head sprite, actually. I technically fibbed. Here's an Insect without a snout selected and red eyes.
image

What the fuck is that? What the fuck. ~~(Yeah, moths actually had this issue before the Insect change. You could change the eye color and it would just change a single pixel in the middle of the +-shaped eye. This is where the eye pixel is on single-pixel-eyed sorts. Anyways!)~~

There are a couple other issues with the Insect species and the Moth parts cannibalized in its name. Here's an Insect with blue fluff.
image
There are no antennae sprites for the back view. Also, the bug snout has antennae of its own that don't quite match up with the antennae attached to the fluff. Also, the missing back antenna isn't specific to the Insect and can be witnessed with any species, hell, even better, now that you can select it on species without antennae in their sprite. Here's an Anthropomorph with Reddish fluff, with the lack of antenna sprites on the back circled. 
image

Also, there seems to be a weird thing underneath the fluff that's inherent to the Insect sprite. To showcase, here's a screenshot of an Insect colored white, without fluff, snout, or antennae. 
image
I'm genuinely not sure what this is supposed to be. It looks weird as all fuck with the moth fluff over it and it looks weird as fuck without anything to cover it up. It's also colored brown which makes it look like shit if the moth is trying to be some other color as exampled here. 
image

Anyways, back to the chase- here's a moth character created using the Anthropomorph species.
image
You can get everything using Anthro's options- Anthro has sufficient support for creating an insectoid character, down to the wings, fluff, the meat, the voice, snout, markings, even bug 'tails' that you can't really see underneath the moth wings. In my opinion this genuinely looks marginally better than just using an Insect.

Things Anthro doesn't have that Insect does... The markings from the moths that don't precisely match up with the body shape of either, and a few gameplay differences that were previously unique to Moths (though a few gameplay features of Moths were removed during the Insectification, such as flashability).

Anyways, I'm losing the steam I had when I started this, so it's time to wrap it up.

# TL;DR
Moths were replaced with a worse clone of Mammal, Insect, in the same PR that existed to remove useless clones of Mammal. There is next to no reason to use the Insect species over the Anthro species, and with its existence removed the actually nice looking, gameplay unique Moth species. The Insect species is full of visual gore that I pray is unintentional, including the moth fluff sprites, which have no back antennae for some reason, even on other species. 

~~Come on, Skyrat even has both Moth and and Insect, for the insane bastards who would actually use the mess that is the Insect species. But I'm not going on fucking Skyrat.~~

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
**holy shit please only testmerge this first i don't want to break species**
also yes it's been tested

moth fluff now shows the antennae or whatever that is from behind as per request, and also so moths dont look stupid from behind who thought that was a good idea

hey the aquatic/avian/moth sprites are still in the code
you can now choose body sprite as a anthromorph and pick aquatic/avian to change to those old slightly different sprites

oh also as an insect you can now set your body sprite to apid, which is a bee, sprites ported from beestation, looks cool
(also OLD MOTH SPRITES ARE PICKABLE)

if you're going to make changes relating to this feature like adding more sprites to species to pick from, please tell me because adding them is an extremely delicate thing and will likely require further tinkering of how bodyparts are handled

closes #13222

## Why It's Good For The Game
better customization that isn't shitcode
i haven't actually seen any other server do this yet maybe because it's ridiculously snowflakey but it's fucking cool

## Changelog
:cl:
add: you can now choose a body sprite as an anthromorph or anthromorphic insect, and can choose from aquatic/avian and apid respectively (and obviously back to the defaults too)
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
this essentially completes poojs initial work on merging the species because you can get the sprites back now
the only one i haven't chased is moths because from what i can tell, anthromorphic insect is identical

**Comment by timothyteakettle** [comment]
oh fuck i forgot to make the option save give me a minute (also add moths)

**Comment by timothyteakettle** [comment]
ok its cool now

**Comment by tiramisuapimancer** [comment]
I really do hope this isn't much of a trouble, but, with regards to the moth sprites- would it be too much of a pain to have both the greyscale edition of the moth body sprites, plus the tan-colored ones? It's a HUGE pain to get a nice tan/cream looking moth using the greyscale ones since the way sprites are colored here doesn't account for how yellow is a bitch to shade and outline non-manually, but simply only having the yellow sprites would exclude anybody who would want a color that can't be gotten from slapping color multiplier on yellow. I don't know which sprite is the one that exists here, but I can guess it's likely the greyscale one?

**Comment by timothyteakettle** [comment]
i don't have the non greyscale sprites and yes, they're greyscale because you're supposed to be able to choose any colour

pretty sure kevin did some changes to the number of colours that can be selected also

**Comment by tiramisuapimancer** [comment]
It's not the number of colors possible as much as it is that tgcode has an absolutely ass method of recoloring greyscale sprites that happens to make yellows and browns look like complete shit. I'm in a round in a different server right now, but in a bit I can grab an attempt at making a Skyrat moth (which have greyscale sprites) into the original yellow color of moths once that round ends.

**Comment by tiramisuapimancer** [comment]
image
Here's the pic

**Comment by timothyteakettle** [comment]
if you're able to find the non greyscale sprites sure

**Comment by tiramisuapimancer** [comment]
https://github.com/tgstation/tgstation/blob/master/icons/mob/human_parts.dmi Does this work?

**Comment by timothyteakettle** [comment]
it does! i'll have a look at adding it now

**Comment by tiramisuapimancer** [comment]
BLESS YOU

**Comment by tiramisuapimancer** [comment]
Can ya stick "Closes #13222" into the main post here so it auto-closes the issue once this is fullmerged?

**Comment by TheSpaghetti** [comment]
### MERGE THIS

**Comment by ghost** [comment]
The insect tail doesn't connect with the moth sprite or the apid sprite, unfortunately. I just wanted my insect character to NOT have the dumb neck thing...

**Comment by timothyteakettle** [comment]
nothing i can do about existing accessories not fitting old sprites afraidly

**Pull request merged**
