### PR TITLE
Snapping half the modular_citadel folder into oblivion.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The modular_citadel has became more of a burden than a necessity and should be taken down due to the difficulties of maintaining a detached "modular" folder full of copy-pasta, duplicates, lack of standards and confusion.
Please don't struggle to think the folder is worth keeping, it'll pain me as it'll be one hell of a merge conflicts ride regardless.

## Why It's Good For The Game
Fun isn't something one considers when dealing with this stupid thing.

## Changelog
:cl:
code: Started "deconstructing" the mess that's the modular_citadel folder, moving its contents away to the respective outsider code, icons, sounds, modules, datums, game and whatsnot folders.
fix: Fixed many little issues such as duplicate icons/code, coding malpractice along the way.
del: commented/removed some unused/broken/duplicate contents.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
This needs very thorough review to ensure that everything removed from modular_citadel is properly demodularized.

**Comment by Ghommie** [comment]
Very.
When I made this thread I didn't care much about writing down several paragraphs on contents affected by this change as I was tired, so I'll do it here:

- I unchecked the compile box for all vg_clothery minus vg_uniforms as they were missing worn icons.
- a few donator's fluff items (the undertale collar, the boombox and izzy's ball and that's should be it) were moved elsewhere, not removed. But I'm pondering about the possibility of making a donator folder to contain these niches.
- Removed some damn duplicate code.
- Fixed some discrepancies or implemented features, such as birdpeople/ipc butchering not giving off
avian/ipc slabs of meat, the HoS skirt missing the alt worn icon, or the sec skirt not using the newer sprite (also made it possible to be worn casually).
- Reduced the clusterheck of Turtlenecks and Trek clothing a ton, and killed off the unused icon files.
- Demodularized all the sounds folder.
- Commented out a few useless or unused code while de-modularizing, such as the:

1. - Not-checked-for-compile plasma rifle cabinets (which shouldn't be using the gun/energy/plasma as guntype but its childs), 
2. - The nazi vendor refill (the vendor is commented out, and nazi stuff is a real legal taboo in many states)
3. - References to the aforementioned borked vg clothery in the soviet vendor.

- Utterly destroyed genemods.dm, an uncopiled file containing merely a couple dozens lines of a very incomplete feature no one is working on apparently.

Regardless, due to the sheer size of this PR (I am fed up with this drag of a modular folder), mistakes and possibly a couple missing icons are to be expected, and local tests will have to be run first.

**Comment by Poojawa** [comment]
the gun cabinets were a wip that I got distracted on from completing, was theorizing putting gun lockers in secured, but hackable armory racks that would unlock on red alert for big guns and blue alert for moderate lethals. Mainly for something that looked a hellva lot nicer than just ugly pixel edited gun layering thrown on metal racks.

the readme change isn't needed to be so passive aggressive, either just delete it fully or just leave it unchanged. 

I, for one, am glad to see the nazi/soviet shit gone. I didn't add them and I couldn't be arsed to keep it maintained but never really got around to purging it.

**Comment by Ghommie** [comment]
> 
> the readme change isn't needed to be so passive aggressive, either just delete it fully or just leave it unchanged.

Thanks for confirming my bias it could have sounded a bit too agressive.  I'll cut it down to the strict necessary, but it has to be known that the modular folder is no more mandatory.

**Comment by Ghommie** [comment]
This PR is fairly ready, I'd appreciate if it was given some higher priority (as in reviewing and maybe testmerging, not the label).

**Comment by nik707** [comment]
im scared

**Comment by Ghommie** [comment]
Yea, I haven't solved the ongoing conflicts in a while.

**Comment by Ghommie** [comment]
I'm better off doing this bit by bit, never take a step longer than your leg.

**Pull request closed without merging**
