### PR TITLE
removes a spammy and bad brain damage line about rp server 

### PR DESCRIPTION
**Pull request by silicons**
ugh

lrp as shit and was a mistake and i regret adding it

### CODE REVIEW

**Comment by MrJWhit** [comment]
But it's funny, and I still really enjoy it. We can dirty up the language a bit.

**Comment by ghost** [comment]
remove it but replace it with generic braindamage line about clown pie throw if we don't have one already just so people In The Know get the funny inside joke

**Comment by Ragolution** [comment]
i think it's fine

**Comment by silicons** [comment]
@kappa-sama open a pr that does that and says closes #13050 please thanks

**Comment by silicons** [comment]
same goes for you @MrJWhit 
@Ragolution what justin said would be good, i don't want to keep a line that's directly quoting something that can be searched up on discord to ridicule the person who said it

**Comment by silicons** [comment]
y'all have plenty of time anyways it's just a webedit :^)

**Comment by Detective-Google** [comment]
the issue imo is that this slaps a giant fucking wall onto the chat window and is completely OOC which is not epic

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
