### PR TITLE
Box Medbay Rework!

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request
the box medbay sucks currently, hopefully this is better!
boxmedbay
also fixes a bug where plasteel tiles showed up blindingly white in mapmaker due to a duplicate icon state.
## Why It's Good For The Game

I wanted the box medbay to be less CBT to play on
also bugs bad
## Changelog
:cl:
map: box medbay got a makeover
fix: white plasteel tiles now have the correct icon in the mapmaker
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
can you give them an EMT suit as well?
The storage is used to decontaimate people and the hardsuit is nice for dead in spacepeople

**Comment by YakumoChen** [comment]
I'd like a surgery theatre.

**Comment by YakumoChen** [comment]
I think surgery in general is kind of too big? So is genetics, just a ton of unused space.

**Comment by YakumoChen** [comment]
Also the morgue is really bad and denies every morgue-relevant, non-medical job (chaplain, robotics, chef) from getting access.

Discreet access, even. The morgue should preferably not have any windows so revenents and traitors can do bad things in there.

**Comment by YakumoChen** [comment]
I also intensely dislike the security office placement as its directly in front of the teleporter room, which is already hard enough to discreetly break into.

**Comment by YakumoChen** [comment]
I also feel that you made med storage too difficult to break into as there is no escape path or alternate route through it.

**Comment by YakumoChen** [comment]
The surgery room is also completely un-discreet so antags can't really operate in any capacity through surgery given you can stand anywhere in medbay and probably see into it

Honestly I want to find things I like about it. I like the doctor table! I like that cloning is a LOT more vulnerable!
But I think there's too much wasted space with all the hallways and I think cyro/sleeper area is far too cramped despite being the highest-traffic part of medbay.

**Comment by timothyteakettle** [comment]
you can't access the morgue as the cook with how it's been placed, and it dividing the morgue into two separate rooms is just weird

edit: also agreeing with the point on having windows to the surgery being a bad idea

it'd be nice if large mapping changes that get proposed like this were discussed more before just suddenly being thrown out as a pr when it seems to lack a tonne of needed things that the existing layout already has

**Comment by MrJWhit** [comment]
My two cents:
-You shouldn't have the oxygen can in the middle where it is, it's hard to wrench down with the cryo chambers being 2-tiles long, so it's impossible to click on, you need to alt-click. Just moving it to the top position works fine.
-The location of the Medbay Maint APC just sorta... feels weird. Same with the Sleeper Room APC, that feels too far away from the room it's named after.
-There's a random unconnected scrubber line here: Central Primary Hallway (130, 119, 2), central hallway on the left entrance to medbay, down and left one tile of the wall with light fixtures.
-I'm not a fan of adminbussing the NanoMed Plus machines 26 pixels up, them taking up a tile is fine.
-The location of the sleepers feels like they should be more prominent, because when you blast into medbay you normally run there first.
-The glass table-meetingroom table should really have some random items on it, so it doesn't feel like a big empty nothing.

**Comment by shellspeed1** [comment]
At the very least, give chemistry two chem heaters.

**Comment by YakumoChen** [comment]
The genetics APC and the air alarm need moved, the former preferably in maint to better suit the theme of the rest of the map. Given the current state you have to wade through the (access locked!!) monkey pen to access them. Same for the morgue.

The APC on the bottom right is mislabeled or something because I'm not actually sure what it is for.

I can't find the APC for the "Medbay Storage" but there's an APC for the "Sleeper Room" far away from the actual sleeper room.

I think the pipes need a lot of work because seeing pipes go through rwalls into departments and not near doors is kind of cringe.

There's a lot of dead ends in maint around medbay which just kind of show how hacky the map is placed.

**Comment by Detective-Google** [comment]
> The genetics APC and the air alarm need moved, the former preferably in maint to better suit the theme of the rest of the map. Given the current state you have to wade through the (access locked!!) monkey pen to access them. Same for the morgue.
> 
> The APC on the bottom right is mislabeled or something because I'm not actually sure what it is for.
> 
> I can't find the APC for the "Medbay Storage" but there's an APC for the "Sleeper Room" far away from the actual sleeper room.
> 
> I think the pipes need a lot of work because seeing pipes go through rwalls into departments and not near doors is kind of cringe.
> 
> There's a lot of dead ends in maint around medbay which just kind of show how hacky the map is placed.

don't you just love how box is built around pipes inside walls and everyone still pretends it's the best map ever with no flaws. 
in terms of APCs I actually cut the areas down (before medbay was just two giant super-areas with the APC hidden away in a place you couldn't replace it if it was broken, even as an engineer. This has been at least somewhat allieviated.)

and no APCs are not going in maint. you can pretend it's a map design choice all you want but most critical departments have their APCs in the actual room.
image
old box pipes for reference of how absolutely jank they are.

**Comment by Detective-Google** [comment]
> At the very least, give chemistry two chem heaters.

they have a second heater it's just not next to the chemistry setup (I could count on one hand the amount of times I need a heater during my average chemist round, the only time you really need one is fermichem, the rest of the time a welder or igniter is just faster.)
image

**Comment by ghost** [comment]
The Box medbay is fine.

**Comment by EmeraldSundisk** [comment]
I was initially going to say the lobby area could use some seating, maybe things changed around the entrance. But the chaplain (and cook I suppose) should have access to the morgue, and even if they have access the morgue's location doesn't exactly make it easy for them.

**Comment by MrJWhit** [comment]
-Security APC doesn't have wires
-There are no bodybags

**Comment by bunny232** [comment]
just surpised no one mentioned this, but the medical huds on the glass table are no actually med huds

**Comment by Detective-Google** [comment]
> just surpised no one mentioned this, but the medical huds on the glass table are no actually med huds

Duke brought it up to me and Ive fixed it, ty for mentioning though

**Comment by ShadeAware** [comment]
This really just seems to put aesthetic over functionality, which is the **last** thing the Medical Bay needs right now.

**Pull request closed without merging**
