### PR TITLE
parrying nerf/pugilism buff

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

gives old pugilist values back, making parrying significantly less clunky than before.
also makes it so you can't parry while resting, because that's kinda dumb.

## Why It's Good For The Game

removing the ability to parry while floored means that you can now not just go horizontal and still parry, there's now a downside to it, and also nerfing things to where they're worse than base unarmed is kinda bad for those items, might as well just remove them at that point. 

## Changelog
:cl:
balance: reverted the pr that absolutely gutted pugilism and made it worse than base unarmed, also gives it a second long stagger 
balance: removed the ability to parry while horizontal, because that's dumb and makes it easy to just time the parries right.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
>no cooldown pugilism parries

Could you not? Im pretty sure someone only just nerfed that, and it was cancer to deal with when people could just spam the fuck out of parry and be invincible.

Buff the traitor items, but stop making pugilism so overpowered.

**Comment by ghost** [comment]
parrying has a cost associated with it and as such you mechanically cannot spam parry against players because you will drain your resources and kill yourself

**Comment by Hatterhat** [comment]
> 
> 
> > no cooldown pugilism parries
> 
> Could you not? Im pretty sure someone only just nerfed that, and it was cancer to deal with when people could just spam the fuck out of parry and be invincible.
> 
> Buff the traitor items, but stop making pugilism so overpowered.

just shoot pugilists with your gun they only get damage mitigation

**Comment by kiwedespars** [comment]
>people could just spam the fuck out of parry and be invincible.

go ahead, spam parry and be invincible. i implore you to do it and open my eyes to this tactic of sheer invulnerability.

**Comment by necromanceranne** [comment]
community_image_1400690198

Posting this again.

Can I just say, as the person who added the pugilism trait and armwraps, I think it's had way too much stuff added to it over time, and it has long since moved away from being a baseline proficiency for unarmed fighting. It was primarily meant to give any martial arts a solid foundation, as well as enable people to fight somewhat more effectively while unarmed when you don't have a martial art.

At some point it's had a whole lot of different stuff added to it that actually probably should have been restricted to certain items (stuff like the cult armwraps is a good example, or the chaplain armwraps), and not added to the generic pugilism trait. I actually added the ability to change which traits the armwraps gave you for expressly this purpose. The lack of gun use wasn't a hard and fast rule, there wasn't really any reason to keep it universal, it was just flavourful. And, if you wanted it to be universal, that change isn't particularly difficult either without it being at the expense of the mechanical benefits.

Most anything with the pugilism parry stats would be better off without it. The ability to parry almost anything would be better for a martial art like Sleeping Carp, Krav Maga or Rising Bass, or armwraps attached to antagonists, and not some greyshirt posing as Jet Li. For pugilism, you should simply dominate in the area you are best suited for. Unarmed fighting. If that means this same greyshit is parrying a Scarp user, that's fine by me. That sounds awesome so long as the scarp user can do it in response.

**Comment by YakumoChen** [comment]
> 
> 
> parrying has a cost associated with it and as such you mechanically cannot spam parry against players because you will drain your resources and kill yourself



> 
> 
> > people could just spam the fuck out of parry and be invincible.
> 
> go ahead, spam parry and be invincible. i implore you to do it and open my eyes to this tactic of sheer invulnerability.

These are exactly the sorts of replies I can expect from people who have spent stupid amounts of time practicing with it; the people who benefit the most from this buff who can reliably time exactly when to parry so as to dominate combat with it, using the obnoxiously high skill ceiling to combat that parrying has introduced to the game. It was better when melee shit was just a click-fest because at least then the playing field was level for anyone who could click at the right time. The people who can flex on traitors using just armwraps they made at round start because the obnoxious extent parrying has been made freely available to any greyshit with wirecutters.

**Comment by moltoretardo** [comment]
Use the shotgun

**Comment by kiwedespars** [comment]
> These are exactly the sorts of replies I can expect from people who have spent stupid amounts of time practicing with it

the funniest thing is, the reason i'm asking you to show me is because no matter how much practice you have, you'll never be able to hit a security officer 20 times while also avoiding getting hit with a baton. i say this because even i, after fucking around with the system a good chunk and apparently being **super good** in your eyes can only count the amount of times on a finger i've actually parried a baton a more than once or twice.

the fact you're dismissing the system because you believe "i have to practice and pour 500 hours into learning the timing" really enforces an idea that you haven't tried to use the system or bothered with it. if you don't want to, that's fine, use an actual weapon, they're better most of the time and more consistent to use, after all.

the reason why people use armwraps is because it's a fun system to learn and it's a stylish way to take people down. if traitors are being beaten by some dudes using their bare hands, are these traitors actually using weapons, or are they the citadel "traitor" who takes twenty seconds to type  _"why"_ as they're getting punched

**Comment by dzahlus** [comment]
I'll reinforce the fact that while I did call for a parrywraps nerf the one we got is kinda funky, as he said the only reason parrying feels so hilariously overpowered is because you could do it while horizontal, this means you basically have a 100% guaranteed chance to be hit by your opponent which in turn means it's extremely easy to time every single parry. This is the only reason I personally ever got fucked by (unarmed)parries. So this seems good to me until the combat rework is out.

**Comment by ghost** [comment]
> These are exactly the sorts of replies I can expect from people who have spent stupid amounts of time practicing with it; the people who benefit the most from this buff who can reliably time exactly when to parry so as to dominate combat with it, using the obnoxiously high skill ceiling to combat that parrying has introduced to the game. It was better when melee shit was just a click-fest because at least then the playing field was level for anyone who could click at the right time. The people who can flex on traitors using just armwraps they made at round start because the obnoxious extent parrying has been made freely available to any greyshit with wirecutters.

for clarification i have never actually parried in any successful manner in my life outside of one time i did the bdm cheese just to see how it felt as well as twice using epitaph shortly before dying

**Pull request merged**
