### PR TITLE
Disco Inferno: She Blinded Me With Science Supplies edition.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Benevolent spiritual successor to #10740. Total price raised to 20k considering 3/4 of it is composed of science supplies of your choices. Support your local SCIENCE! to get it.

Includes a little extra code for possible future features based on cargo expenses.

## Why It's Good For The Game
Fits the lore of the shuttle. Stay cool, @chefferz.

## Changelog
:cl:
tweak: The Disco Inferno now requires you to support SCIENCE! to be unlocked (ergo buy 15k worths of science... or party supplies from cargo). The price of the shuttle itself has been lowered to 5k.
/:cl:

### CODE REVIEW

**Comment by BonniePandora** [comment]
Lovin' the Dolby reference, also looks pretty neat.

**Comment by chefferz** [comment]
Good balance. Thanks Ghommie.

**Comment by Tupinambis** [comment]
Ghommie this is the best idea that somehow nobody has thought of, INCENTIVES FOR INTERDEPARTMENTAL COOPERATION AND ACTUALLY DOING YOUR JOB! I want to see this for more shuttles.

**Comment by Ghommie** [comment]
Umh, actually, I'll probably scratch this Disco Inferno nerf, but will reimplement the cargo expenses tracking feature sometimes if I have time later. What a wasted funny title for a PR.

**Pull request closed without merging**
