### PR TITLE
Wizard objectives are shit and nobody follows them anyway.

### PR DESCRIPTION
**Pull request by BlackMajor**
Literally just changes the wizard gamemode objective to
"Cause as much creative mayhem as you can aboard the station! The more outlandish your methods of achieving this, the better! Make sure there's a decent amount of crew alive to tell of your tale."
and escape.

### CODE REVIEW

**Comment by nik707** [comment]
When faced with the issue of Wizards not following their objective and just murderboning, rather than enforcing them to you know, do them, we instead give them even more freedom to be completely fucking autistic and murderboney. Hot take, our players are not at all trustworthy enough to do anything with this objective that isn't autistic murderboning.

**Comment by nik707** [comment]
Furthermore, it's insanely subjective and literally no admin will ever enforce it or say what is and isn't "creative"

**Comment by BlackMajor** [comment]
Added a small catch at the end of the objective to catch Murderbonus the 5x fireball wizard.

**Review by deathride58 — APPROVED** [review]
Can be merged with approval from any other maintainer

**Pull request merged**
