### PR TITLE
removes flightsuits until pixel movement is out and i can redesign them

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by Cw3040** [comment]
😢

**Comment by Cw3040** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by Cw3040 — CHANGES_REQUESTED** [review]
Close this pls

**Review by deathride58 — APPROVED** [review]

**Comment by Cw3040** [comment]
reeeee

**Pull request merged**
