### PR TITLE
Ports fireman carrying from /tg/

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/44155

## Why It's Good For The Game
Just look at the original PR I'm too lazy to rewrite it

## Changelog
:cl:
add: can now carry people on your back by aggressive grabbing them while they are laying down and then dragging their sprite onto yours.
tweak: dragging people who are prone is now much slower, and carrying them will allow you to move faster at the cost of taking 5 seconds to lift them up onto your back.
tweak: pacifists can now aggressive grab (cannot table slam people though)
/:cl:

### CODE REVIEW

**Comment by IronEleven** [comment]
I really don't like the idea of slowed dragging for cultists trying to get converts.

**Comment by Tupinambis** [comment]
I don't like the idea of slowed dragging either. I can see this seriously fucking over antags. Time is of the essence with antagonists, and forcing them to wait 5 seconds not moving to pick their target up is a great opportunity for half the station to find and valid them.

**Comment by Arturlang** [comment]
To note also it makes it harder for sec into bring people to brig, which is very fast due to sprint, giving allies time to rescue them

**Comment by Tupinambis** [comment]
> To note also it makes it harder for sec into bring people to brig, which is very fast due to sprint, giving allies time to rescue them

Only applies to team antags though. Still fucks over traitors, lings, wizards and midrounds.

**Comment by Linzolle** [comment]
well the slowdown value can be tweaked, and also the slowdown doesn't apply if you shake someone to get them back on their feet.

**Comment by Trilbyspaceclone** [comment]
Shaking gives stam, so sec has to cuff them then shake, also messes with medical a bit and has bugs that are not fixed upstream...

**Comment by silicons** [comment]
i'm fenced leaning against this tbh.

**Comment by Owai-Seek** [comment]
I like the pickup from an RP standpoint and medical standpoint but dont think the slowdown sits well with anyone who plays antags or security.

**Comment by nero1024** [comment]
Realistically, you can't drag a lying person and still move at sprint speeds unless you happen to have superhuman strength or something like that. I like this change.

**Comment by cebutris** [comment]
I like this change, except maybe the time to pick up needs to be reduced. It reminds me of stealth games where you can either drag bodies clumsily into a nearby hiding place, or actually carry them longer distances at the expense of taking time to pick them up.

That said, there are a lot more use cases for dragging than just hiding corpses, so that shouldn't be the only thing factored. If this goes through, I can see people just grabbing lockers to drag people around in. 

Though dragging things at full sprint speed is kinda dumb.

**Comment by Linzolle** [comment]
values subject to change

**Review by silicons — APPROVED** [review]

**Pull request merged**
