### PR TITLE
Fixes *wag for mammals

### PR DESCRIPTION
**Pull request by Poojawa**
Someone forgot that we have snowflake bodyparts.

:cl: 
fix: fixed *wag for mammals
/:cl:

### CODE REVIEW

**Comment by Poojawa** [comment]
build_tools needs to be fixed for Travis.

**Review by deathride58 — APPROVED** [review]
You can probably move this to an override in modular_citadel to ensure this doesn't get overwritten by merge conflicts somewhere down the line

**Comment by Poojawa** [comment]
Probably. but my albet clumsy ways of trying to do that never worked for proc manipulations.

**Comment by deathride58** [comment]
Could probably try making this modular in the future, then

**Pull request merged**
