### PR TITLE
you can now beat eachother to death with a certain dildo.

### PR DESCRIPTION
**Pull request by kiwedespars**
## About The Pull Request

the literal horsecock dildo, the big one now does 10 brute. a valuable backup weapon for any would-be victim of death.

## Why It's Good For The Game

it's not.

## Changelog
:cl:
add: 10 force to a fucking rubber cock.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
yes

**Comment by moltoretardo** [comment]
Code adding, removing, or modifying the functionality of adult-oriented features (such as, but not limited to: vore, genitals, MKUltra, and more). This also includes pull requests attempting to add or remove these features outright. (Requires approval from at least half of the formal maintainer team)

 Sorry brogue but did you get the okay from your maintainer team

**Comment by rossark** [comment]
Desperate attempt to buff their meta weapon before Teak deletes them from existence.
What a shame this will be shutdown and never see the light of day.

**Comment by Ludox235** [comment]
image

**Comment by silicons** [comment]
@BlackMajor should we do this

**Comment by necromanceranne** [comment]
Give it parry data

**Pull request merged**
