### PR TITLE
Add 5th Port Sweaters to Loadouts

### PR DESCRIPTION
**Pull request by Ragolution**
We have literally had these sweaters in code since early February, and even longer before that.

**Changes:**
-  Adds bb_sweaters to the Loadout menu.

### CODE REVIEW

**Comment by deathride58** [comment]
Do the sprites for these even work anymore

**Comment by Ragolution** [comment]
Pretty sure they do, yeah. I used to regularly add them to my inventory using the game panel back in march.

**Comment by Poojawa** [comment]
weren't these in the citadel vending machine?

**Comment by Ragolution** [comment]
> weren't these in the citadel vending machine?

Yes. Right now they're unused. An earlier PR added them back to codebase (edit:) *last year:* https://github.com/Citadel-Station-13/Citadel-Station-13/pull/236 and haven't been implemented since.

Since we don't use that vending machine and there's no signs of it coming back any time soon, why not let people use the sweater? Again I'd just spawn these for myself when I needed them, when I was GameAdmin. Their sprites are functional and obviously, as uniforms, they don't provide any kind of balance element.

The one unique interaction they have with code is they don't hide dongs because of what the sprite is.

**Comment by Ragolution** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/236

**Comment by Poojawa** [comment]
it's literally a map the vender into the map sort of change my dude. but yeah

**Comment by Ragolution** [comment]
> it's literally a map the vender into the map sort of change my dude. but yeah

I don't know how to map, nor is anyone else willing to do it, apparently. I don't even know if the vending machine that spawned them works anymore or if they're registered to one.

**Comment by Poojawa** [comment]
main folder -> Tools -> mapmerge2 -> preparemaps.bat

open map. do edits. save

mapmerge.bat, 

PR. done.

**Comment by Ragolution** [comment]
Is that seriously your response to this? Rather than just add it to the loadout menu, you want me to go in and edit four maps to put vending machines that I don't know work on them?

**Review by silicons — APPROVED** [review]

**Comment by Poojawa** [comment]
You said you didn't know how to map, so I explained it.

good christ calm your tits my dude.

**Pull request merged**
