### PR TITLE
Lavaknights now get polychromatic ID badges [READY!]

### PR DESCRIPTION
**Pull request by cebutris**
:cl: Cebutris
rscadd: Knight badges, sprites courtesy of Toriate! They're functionally identical to IDs but look sexier and can be recolored!
rscadd: Lavaknights now spawn with Knight Badges!
/:cl:

[why]:  Because being "Unknown (as Namehere)" is not chivalrous at all, and lavaknights need more shiny colorful stuff. The badges don't start with any access

Image. Green bit is recolorable!
lavaknightbadge

image

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
Perhaps RGB holo IDs can work for the knights?

Code's good though, sprites can be focused on later

**Comment by cebutris** [comment]
Camille said he wanted knight badges for them. I can add them in this PR, if I had the sprites, or it can be in a separate one.

**Comment by cebutris** [comment]
Now with 100% more unique sprite (courtesy of Toriate). Next step: Making it polychromatic (oh god help me why am I doing this to myself) and making it say "Namehere's Knight Badge (Knight [Captain])" instead of "Namehere's ID card (Knight [Captain])"

**Comment by cebutris** [comment]
Thanks for catching that, Travis. NOW WITH ICONS FOR REAL.

**Comment by cebutris** [comment]
That's done. Now to make them polychromatic... 

Wish me luck for this is where I die

**Comment by cebutris** [comment]
This should be ready now!

**Comment by Poojawa** [comment]
WEEEEELL

I SUPPOOOOOSE.

**Review by deathride58 — APPROVED** [review]

**Comment by cebutris** [comment]
I PUT THE GIANT IMAGE IN ARE YOU HAPPY  NOW @Poojawa

**Pull request merged**
