### PR TITLE
Removes craftable shield impants

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Shield implants are now admin only

## Why It's Good For The Game
Such a misstake, should been admin only a long time ago
## Changelog
:cl
balance: RnD has lost the blueprints to the shield implant for arms, leaving the only remaining copys in CC for their use.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
that's not a good reason for removal
exactly why do you want it removed?

**Comment by Trilbyspaceclone** [comment]
They are bad for the game, they are not good. You were right, and they should have been removed

**Comment by silicons** [comment]
that's still not a reason saying something is bad doesn't make it bad

i was very wary of them but i still merged it

"they are bad" is not a reason.

**Comment by Trilbyspaceclone** [comment]
You were right to be wary of them, and they are nothing but power creep sec trash.
They were merged with 2 iirc other implants that frankly are also just bloat in the RnD system.
They have proven, to not be in the direction of combat or the game that we want.
They are lrp trash items that make hero protag cop with fancy gogo gadgets akin to a commic book then a high-scify setting with some magic thrown in.
They were a misstake just as much as the rest that was added and the M.A.S.O.N Rig

**Comment by silicons** [comment]
i'm sorry to do this but please reopen this if you still want to reopen it with some more specific reasoning pertinent to our server and gameplay other than you changing your mind and no longer liking them and some vague mentions of what direction of combat or game we want because yeah no that's overly vague..

**Pull request closed without merging**
