### PR TITLE
Make Box's Engine be randomised between SM, Tesla and Singulo [TEST-MERGE]

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request

This make the Engine in Engineering of Box not always the SM, also add a framework for more randomized area of the station.

I took most of the code from Yogstation

I ask for it to be test-merged just in case I fucked something up.

## Why It's Good For The Game

This make it so that it isn't always the SM the main engine and add the framework to be able to randomized different area of the station like Bar or Maintenance.

## Changelog
:cl:
add: Added submaps for the SM, Tesla and Singulo
add: Added a placeholder on Boxstation for the Engines
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
give me singuloth or give me death

**Comment by r4d6** [comment]
> give me singuloth or give me death

Thou shall not die today.

**Comment by Ghommie** [comment]
>+129,753 −125,360

Jfc, either you fucked up the line endings on boxstation .dmm, or did not mapmerge correctly.

EDIT: also remember to credit Yogstation for the code.

**Comment by r4d6** [comment]
No it was simply that I didn't knew how to overwrite files in the branch, turns out you simply upload the same file at the same place. and before that I deleted the file and uploaded it again.

**Review by nik707 — APPROVED** [review]
codewise it looks fine, but yeah tm

**Comment by r4d6** [comment]
Closing it because I made a cleaner one.

**Pull request closed without merging**
