### PR TITLE
[IDB IGNORE] [MDB IGNORE] [hilariously wip] atmospherics overhaul

### PR DESCRIPTION
**Pull request by silicons**
refactors:
- [x] proc stubs
- [x] standardized join/leave procs that movement/pipe layer sets hooks into
- [x] standardized pipeline expansion/pipe network builds
- [x] standardized connection/layer checks
- [ ] standardized icon update procs instead of this snowflake trash
- [x] make rebuilds near-instant
- [x] port layer adapters over (special code)
- [x] standardized/port atmos component code
- [x] standardized/port atmos pipe code
- [ ] do something reasonable with portable_atmospherics since it's snowflake

overhauls:
- [x] give all atmospherics machinery a max power rating
- [x] remove all pressure limits from vents/scrubbers/transfer devices
- [x] give transfer devices an adjustable power rating + max pressure
- [x] add procs to scrub/pump gas using power ratings
- [x] add molar mass + "specific entropy" calculations to gas mixtures for pump/scrub power calculations
- [x] make heaters/coolers consistent (5x thermodynamic cheat factor for heat/cool rate vs power in)
- [ ] buff thermal exchange pipes in planetary environments, reevaluate thermal exchange pipes regarding space/vacuum
- [ ] overhaul TEGs - doublesided/doesn't care about which input is which, can flow both ways. produce power with an efficiency depending on temperature difference + power directly based on thermal energy transferred between the two sides. add "turbine" power from TEGs - producing power via kinetic energy of gases passing through. if doublesided doesn't work due to gas expansion from the transfer causing a see-saw between the two sides, set to onesided + multitool to switch direction. TEGs should dynamically icon update to show which side is the cold/hot sides
- [ ] steal bay/eris sprites for TEGs/coolers/heaters
- [ ] allow all vents to be set to siphon mode

new components:
- [x] mains pipelines that connects but does not bridge all 5 pipe layers, including 3 and 4 way manifolds
- [ ] multiz up/down pipes if they don't exist yet
- [x] T section filters/mixers (output perpendicular from inputs)
- [ ] omni filters/mixers (1 input 1 output 2 filter sides for filter, 3 inputs 1 output for mixer)
- [ ] aux vent - scrubs into one layer, vents from another layer

icons needing converting to 5 layers:
- [ ] normal pipes (straight, bent, etc)
- [ ] filters
- [ ] mixers
- [ ] heat exchange pipes
- [ ] heat exchange junctions
- [ ] vents
- [ ] scrubbers
- [ ] freezers/heaters
- [ ] passive vents
- [ ] 2 sided relief valves

new icons needed to be made/ported:
- [ ] omni filters/mixers (from RP, requires layers)
- [ ] mains pipes (from bay/RP)
- [ ] multideck mains columns 
- [ ] aux vents (from RP maybe, requires layers as we don't want to hardcode)
- [ ] T section filters/mixers (from RP, requires layers)
- [ ] multiz single-layer pipes (from RP, can use pixelshifting probably, maybe use iconstates instead for performance)

### CODE REVIEW

**Comment by lolman360** [comment]
turbine overhaul planned too?

**Comment by silicons** [comment]
@lolman360 not atm as it isn't atmos machinery

**Comment by RummyRin** [comment]
> remove all pressure limits from vents/scrubbers/transfer devices
I mean that'd be really nice, but that's way bigger than you think.

**Comment by silicons** [comment]
dear god here we go

**Pull request closed without merging**
