### PR TITLE
Removes Sizeplay

### PR DESCRIPTION
**Pull request by Poojawa**
Removes sizeplay entirely.

### CODE REVIEW

**Comment by Cw3040** [comment]
Yes please.

**Comment by ktccd** [comment]
Does this mean no more huge/small people or size-ray guns?

**Comment by Poojawa** [comment]
That would be correct. You can blame Cactus for this removal.

**Comment by ktccd** [comment]
Whelp... IMO, I never liked those things. Being a different size was enough of a combat changer to be a super-power.

**Pull request merged**
