### PR TITLE
Makes rapiers and compression kits cost 12 not 8 and 5

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Kev I told you
turns out BS kit can make them into a pocket item : /

## Why It's Good For The Game

Its powerful as stated 

## Changelog
:cl:
balance: rapier costs and compression kits
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
make compression kit cost 9 not 12 so you can't do pocket rapier while also not doubling the price of an item that's overpowered for one strategy

**Comment by Trilbyspaceclone** [comment]
Its really powerfully for any depart tbh...

**Review by silicons — CHANGES_REQUESTED** [review]
@BlackMajor 

hmm maybe the rapier is the issue and not the compression kit 🤔

**Comment by Trilbyspaceclone** [comment]
its the kit 100%

**Comment by nik707** [comment]
@kevinz000 @BlackMajor

**Pull request closed without merging**
