### PR TITLE
new item test

### PR DESCRIPTION
**Pull request by Detective-Google**

### CODE REVIEW

**Comment by CameronWoof** [comment]
Security buff. I like it.

**Comment by dapnee** [comment]
xenobio can do this, but it needs crossbreeding. Dislike giving crew more ways of pacifying other players just cause, I don't see pacification surgery or the flower being used and adding this would make them invalid cause this is way easier.

**Comment by Owai-Seek** [comment]
I think it should probably require research to be created, and/or be locked to the security lathe so not everyone can get it. Either that, or require something only security would have in its crafting (IE: An actual full-blown taser)

If someone without a mindshield tries to remove it, maybe an alert is sent to security, or it zaps the person trying to touch it?

**Comment by necromanceranne** [comment]
Please don't tell me you're getting PR ideas from Girly Station, Google.

**Comment by silicons** [comment]
alright first of all why pacification isn't uh, supposed to be this easy to get

second

> If someone without a mindshield tries to remove it, maybe an alert is sent to security, or it zaps the person trying to touch it?

no.

**Comment by Detective-Google** [comment]
> Please don't tell me you're getting PR ideas from Girly Station, Google.

i had the idea and I felt like making it so it exists that's basically it.

**Comment by Detective-Google** [comment]
ehh overall I did this more as a fun project and threw it up on git since I figured people might be interested, they're not so I'm not gonna worry about it.

**Pull request closed without merging**
