### PR TITLE
Different icon for Bluespace jar

### PR DESCRIPTION
**Pull request by Ragolution**
## About The Pull Request

Adds a more differenter icon for the bluespace jar offered in #12648 

## Why It's Good For The Game

I think it looks pretty good and I don't know how to make a PR on someone else's Fork so I'm doing this instead B(

## Changelog
:cl:
add: Added more complex icon for Bluespace Jar
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
this icon is way better than the one i threw together

**Comment by Ragolution** [comment]
hmmm

**Comment by Ragolution** [comment]
howmst the fuck do it merge conflict @silicons 
it's 1 file and it's meant to overwrite that file

**Comment by Ragolution** [comment]
god i fucking HATE github

**Pull request closed without merging**
