### PR TITLE
Adds miners to each atmos tank - MKII

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Adds more gas miners to each chamber of atmos on each map
MK II

## Why It's Good For The Game

For better plasma floods and Kevs fussion memes - $$$ for cargo

## Changelog
:cl:
add: gas miners to each atmos tank
/:cl:

### CODE REVIEW

**Comment by Poojawa** [comment]
Yeah don't these horribly lag out servers?

**Comment by Trilbyspaceclone** [comment]
@Poojawa Kev wanted them and they spawn in 3 ruins in space already. From local tests they dont seem to steal tons of anything like some other things

**Comment by Tupinambis** [comment]
This would render ordering gas canisters completely useless, make sabotaging Atmos tanks impossible, and overall remove any sense of resource management. It also doesn't make sense from an IC perspective.

**Comment by BurgerLUA** [comment]
Honestly I think that a better idea is to put them on the lavaland base so if cargo wants anything they can get it from there. Miners don't make sense when they're in the middle of space.

**Comment by Trilbyspaceclone** [comment]
Buying gasses from cargo still is worth it for people without atmos access or means to get to it.
Other then that yell at kevs. He requested it as stated

**Comment by nik707** [comment]
@kevinz000

**Pull request closed without merging**
