### PR TITLE
Harvesting replica pods with your own blood allows you to become a podperson without relying on others.

### PR DESCRIPTION
**Pull request by Useroth**
The title pretty much explains it.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
That's pretty strong tbh but then again you can do this already with circuits so 🤷‍♂

**Comment by NalyKalZul** [comment]
BurgerLua the reason i asked for this pr fix is because the crew really are idiots sometimes.
i have 8 shift where the simple request to a listening crew member somehow failed. 2 of those where antag rounds.
Every time i explained them the 2 main steps, first confirm i am dead. Then harvest that pod, pointing at the tray until they responded.
My first attempt even was after i convinced a doctor, and through the doctors opinion the ai too.
i got cloned by sec with them slowballing the attempt to bring me back 20 minutes later. Both the the doctor and ai pubicly announced my desire.
And that was the most "sucsesfull" attempt in regards folks trying.

**Comment by deathride58** [comment]
This is just straight-up powercreep. If you want to become a podperson without the help of others, then learn circuitry.

**Comment by silicons** [comment]
eh nah

**Pull request closed without merging**
