### PR TITLE
adds a neutral trash eating quirk

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
only objects under the trash object type are considered 'trash'
the quirk is neutral as the items don't affect gameplay it's just a flavor thing

it ties into the vore system by changing the consume text if you have it enabled to your current preferred vore verb and belly name and putting the item into the belly, otherwise it qdel's the item and shows regular text

at some point ill make 'trash' be a object flag

oh also you can't forcefeed garbage to people unless they have a pref for it enabled (because it uses their selected vore verb and belly name if applicable and some people might not want to see that or have it be seen?)

also trash is now an element and cigbutts count as trash

and trash is in the maint pool at 15 weight

## Why It's Good For The Game
let the garbage gremlins exist

## Changelog
:cl:
add: new quirk that allows you to eat trash
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
https://www.youtube.com/watch?v=mMAbqjjgEec

In all seriousness, I dunno why that it would need a pref flag, trash eating isn't necessarily creepy in the same sense as some erotic things, and you can literally eat crayons already anyways. Let's not mention the people who go out of their way to eat dead mice lying around in maintenance.

**Comment by LordSaladin** [comment]
Trash sandwich

**Comment by timothyteakettle** [comment]
it has a pref because if the person has a vore belly selected it'll use the belly name and verb

**Comment by bunny232** [comment]
https://www.youtube.com/watch?v=wNTGYSG-SFk

**Pull request merged**
