### PR TITLE
Gives plasma genetic-modifying properties as outlined in the lore

### PR DESCRIPTION
**Pull request by deathride58**
https://citadel-station.net/lore/

This PR gives plasma one of the properties that was outlined in the lore. It's now capable of causing randomization of various different DNA features.

Here's an example of a generic human 30 seconds after consuming approximately 80 units of plasma!
image

:cl: deathride58
add: Plasma now has the genetics-modifying property that was outlined in the lore. While it's in your body, plasma will cause random changes in your character's appearance, which will change their colors, tails, ears, wings, markings, etc.
/:cl:

### CODE REVIEW

**Comment by pantherpusher** [comment]
Does this effect occur when you're breathing plasma?

**Comment by deathride58** [comment]
Yep. Breathing plasma injects you with the plasma reagent. There's no way to differentiate between liquid plasma and breathed plasma

**Comment by GuppyLaxx** [comment]
where's the part where it edits dicks

**Review by jakeramsay007 — APPROVED** [review]
Turned Harold into a furry; working as intended.
-IGN, 10/10

**Comment by Poojawa** [comment]
This would need to be updated to account for default features of various species.

**Comment by Iamgoofball** [comment]
you've turned the magic juice of SS13 into your transformation fetish juice

please, stop

**Comment by nik707** [comment]
I think 5 months is long enough to say stale

**Pull request closed without merging**
