### PR TITLE
revert tg tool sprites

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

i dont like them and the pr that created them had more negative feedback than positive

the new sprites are OBJECTIVELY worse as they're significantly busier, harder to distinguish (jaws of life especially so) some are pillowshaded

they're also SUBJECTIVELY worse because i dont like them

it does however keep the overlays for wirecutters on belt/inhand 
## Why It's Good For The Game

coherent sprites good

## Changelog
:cl:
imageadd: improved tool sprites
/:cl:

### CODE REVIEW

**Comment by HeroWithYay** [comment]
The multitool looked nice due to it being exactly the same but with better shading. Can we keep that one?

**Comment by zeroisthebiggay** [comment]
https://discord.com/channels/161574200581029888/534960816248848404/853792842703306753

>the pr that created them had more negative feedback than positive

nobody goes on github

**Comment by lolman360** [comment]
> 
> 
> https://discord.com/channels/161574200581029888/534960816248848404/853792842703306753
> 
> > the pr that created them had more negative feedback than positive
> 
> nobody goes on github

maybe they should

**Comment by necromanceranne** [comment]
Busier or are the old sprites not just flat

**Comment by maxymax13** [comment]
you merged a really shitty edited version of it and it *still* was too soulless for you :trollface:

**Pull request closed without merging**
