### PR TITLE
Increase age gap

### PR DESCRIPTION
**Pull request by Poojawa**
:cl: 
balance: Staff Heads have had timers greatly increased before being unlocked.
/:cl:

[why]: #  Maybe cut down on some of the really awful staff heads that crop up. Captain now also requires previous heads of staff experience before being able to take it on. I think

### CODE REVIEW

**Comment by MimicFaux** [comment]
f1 "y cant i be captain anymoer?"

**Review by deathride58 — CHANGES_REQUESTED** [review]
Modularize changes

**Comment by ghost** [comment]
>login for the first time
>logout
>wait two months
>login
>play captain

**Comment by Poojawa** [comment]
@Commandersand 
`exp_requirements = 180`
`exp_type = EXP_TYPE_COMMAND`

**Comment by yourdoom9898** [comment]
@Commandersand EXP is based on playtime, not time since first connection.

**Comment by Poojawa** [comment]
@deathride58 the "modularizing" is me commenting out stuff as is in the base file, so it's better to just comment instead. :v

**Comment by deathride58** [comment]
They're datums. You can modularize var changes to datums easily without touching core files at all.

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
