### PR TITLE
controversial shotgun buff (very scary)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
read code

## Why It's Good For The Game
shotguns are doodoo

## Changelog
:cl:
tweak: ishotgun crafting recipe no longer requires plasteel and is slightly more convenient
balance: ishotgun does 45 damage now instead of 40.5
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Not really a buff I see a need for. You can still load it with slugs or buckshot, I'm almost positive, or tech shells if you're adventerous. Plasteel is not terribly hard to get and the shotgun is one of the better weapons in the game, improv just so. "Shotguns are doodoo" is pretty disingenuous.

The damage buff seems unneeded and was implemented before for a pretty decent reason. 

Given I was the one that pushed for making improv weapons to be easier to craft again I would say that there's no need to make it easier than it is.

**Comment by shellspeed1** [comment]
Ya know, it's been a while since I've even tried to craft an improv shotgun, largely because I don't know how. Might be worth trying again to see how hard it is.

**Comment by ghost** [comment]
bro how can i not play anymore and still know more about the balance changes people make


shotguns don't do 60 damage anymore they do 45 😂 
they're absolute doodoo since you can do way more dps with lasers now

**Comment by YakumoChen** [comment]
Checked the code, slugs are still 60, where is your source?

**Comment by Hatterhat** [comment]
shotgun slugs do 50 and have 0 woundbonus

**Comment by YakumoChen** [comment]
That's still pretty high. That's 45 damage with improv. More than enough for damage slow, solid 3-shot even with armor. You can also just make the gimmick tech shells or other stuff to load, the laser shot is still pretty busted, so is dragonsbreath.

Getting plasteel is not terribly difficult (every lathe prints it, nobody in cargo/sci going to deny you a sheet if you ask) and a weapon as powerful as the shotgun in terms of versatility and raw burst damage doesn't need a buff.

**Pull request merged**
