### PR TITLE
adds swarming components to rats so they're a bit less cancer to visualize

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

seeing one rat when in reality it's 20 is not very funny alright

## Changelog
:cl: silicons
tweak: rats now swarm instead of stacking on one spot.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Salt pr

**Comment by silicons** [comment]
@Ludox235 you can still do that it wil ljust be visaulized so you don't have a surprise when one rat turns out to be 20 and now you're in critical

**Comment by timothyteakettle** [comment]
can you do this but with killer tomatoes too

**Comment by Ludox235** [comment]
Yeah do it with ikller tomatoes especially since dead tomatoes will cover up the living ones and basically sprite cuck you

**Review by Ghommie — APPROVED** [review]
cake and ice cream is on the way.

**Pull request merged**
