### PR TITLE
POCKET SAND

### PR DESCRIPTION
**Pull request by lolman360**
# [_POCKET SAAAND_](https://www.youtube.com/watch?v=PTAXUYLbFYk)

## Changelog
:cl:
add: POCKET SAAAAND
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
no compile no money kek

**Comment by lolman360** [comment]
webedit fix

**Comment by Linzolle** [comment]
seems a bit unnecessary if you can already throw it at people to do the blind...

**Comment by lolman360** [comment]
bounty pr

**Comment by silicons** [comment]
i do'nt know how to feel about basically adding a crappy improvised weapon but sure, we can always remove it if it gets abused too hard.

**Pull request merged**
