### PR TITLE
Give security krav maga implants

### PR DESCRIPTION
**Pull request by Roland410**
Give security krav maga implants, remove krav maga gloves from warden.

### CODE REVIEW

**Comment by billbillson** [comment]
will the warden get a implant as well or are they out of luck?

**Comment by Roland410** [comment]
He will, removed his gloves since he spawns with a black one anyways, no reason to have duplicates, and HoS, warden and sec officer closets have an implant.

**Review by ghost — APPROVED** [review]

**Comment by TalkingCactus** [comment]
why?

**Comment by Roland410** [comment]
Why not? But on a serious note, I feel like a lot of players don't play security because they suck at it, and this may give them an edge over their unrobustness. The warden having the only gloves which can give you krav maga was kinda awful too.
Edit: It's not like they become too overpowered with it anyways.

**Comment by TalkingCactus** [comment]
Seems unnecessarily powerful considering their kit already. Balancing it around the fact that some players are `unrobust` doesn't really defend this well.

**Comment by ghost** [comment]
It isn't really insanely op anyway. Makes a good backup for sec as well since they often get disarm spammed.











most sec players suck anyway lmao

**Comment by TalkingCactus** [comment]
Too large of a buff for seemingly no reason.

**Pull request closed without merging**
