### PR TITLE
emagged medibots now murder the everloving fuck out of slimepeople

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Emagged medibots now charcoal toxinlovers.

## Why It's Good For The Game

Hilarity factor and they shouldn't be immune

## Changelog
:cl:
balance: Emagged medibots now charcoal toxinlovers.
/:cl:

### CODE REVIEW

**Review by DeltaFire15 — COMMENTED** [review]
YES

**Comment by Weblure** [comment]
Do regular medibots still murder slimepeople instead of healing them, or has that been fixed?

**Comment by DeltaFire15** [comment]
Bots heal slimepeople since a while now, yep. Got changed in a different PR

**Comment by davidchan13** [comment]
Why not make it pent?

**Review by nik707 — APPROVED** [review]

**Pull request merged**
