### PR TITLE
Makes a new traitor Emitter gun for Engi memes

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Small hand cannon, has 4 shots. Deals emitter shoots aka 30 harm each.
Can be charged like normal, small item costs 5 tc

## Why It's Good For The Game

Engis have no real items to buy of their own. This is weak, cheap and easy to hide making it perfect for a small gun that can take down close range targets if all 4 hit.

## Changelog
:cl:
add: Emitter gun 
/:cl:

### CODE REVIEW

**Review by silicons — CHANGES_REQUESTED** [review]
unironically buff this to 40 damage or 10 shots or both tbh it's so bad

**Comment by Trilbyspaceclone** [comment]
@kevinz000 Done

**Comment by davidchan13** [comment]
This better share a sprite with an RCD or RPD.

**Comment by Trilbyspaceclone** [comment]
@davidchan13 Nope

**Review by silicons — APPROVED** [review]

**Pull request merged**
