### PR TITLE
Adds Arousal as a Damage Type

### PR DESCRIPTION
**Pull request by TalkingCactus**
Adds arousal as a damage type and system which will tie into future updates.

### CODE REVIEW

**Comment by Poojawa** [comment]
all them merge remote-tracking branches

**Comment by TalkingCactus** [comment]
github desktop in a nutshell

**Comment by Poojawa** [comment]
I've taken to just git shell -> git reset to clean up those lists now.

**Comment by TalkingCactus** [comment]
you monster

**Comment by TalkingCactus** [comment]
git reset inside the branch or my master fork?

**Comment by Poojawa** [comment]
it's too late for this branch, but reset your master before you branch, then work onnit. That's the secret to clean and tidy commit history.

**Comment by TalkingCactus** [comment]
👌

**Comment by TalkingCactus** [comment]
ready freddy

**Comment by dwright92** [comment]
NO

**Pull request merged**
