### PR TITLE
Removed the racist ninja speech modification

### PR DESCRIPTION
**Pull request by SkullyRoberts**
I am horrified that this is in the game in the first place, let alone a standard feature.

## Changelog
:cl:RobinFox
del: Ninja speech modification
/:cl:

### CODE REVIEW

**Comment by SkullyRoberts** [comment]
1) it is based off of a horrifically racist meme of Chinese people in the 19th century
2) It uses a racist meme of Chinese people to represent Japanese people.
3) It's not even an actual Chinese or Japanese accent.

**Comment by RogueSteampunker** [comment]
This is literally a non-issue. Nobody is suddenly clambering up and claiming it offends them, and it is unironically a joke for actual unnamed and unoriented group of space ninjas.

**Comment by SkullyRoberts** [comment]
I am. I am offended by it.
We've removed it before. I'm not sure why it was added back.

**Comment by SkullyRoberts** [comment]
A ninja is by definition, Japanese.

**Comment by CozmoB** [comment]
Just make it toggle-able. 

> 
> 
> A ninja is by definition, Japanese.

Kinda racist there to assume

**Comment by RogueSteampunker** [comment]
I mean, sorry to hear, but when you're literally claiming the obviously incorrect accent suddenly needs to get removed cause you and you alone are offended, that doesn't really seem all that right, no?

I mean, hell, it's INTENTIONALLY chinese for the sake of the joke. It isn't as if it's some knee-jerk attempt to be racist.

**Comment by SkullyRoberts** [comment]
What is it with white people getting offended when people don't like their jokes? We're allowed to stand up to you, you know. Seriously. It's like you can't understand that some people have different opinions than you.

**Comment by SkullyRoberts** [comment]
If you really think it's so funny, just type it out. No need to force it on people.

**Comment by CozmoB** [comment]
> 
> 
> What is it with white people getting offended when people don't like their jokes? We're allowed to stand up to you, you know. Seriously. It's like you can't understand that some people have different opinions than you.

The only one here upset over other peoples opinions is you. Like I said, can make it a toggle.

**Comment by SkullyRoberts** [comment]
As an actual Asian, don't I get a say in what is acceptable humor about Asians? Can't I play a videogame I have donated hundreds of hours working on without needing to have caricatures of my people shoved in my face?

**Comment by SkullyRoberts** [comment]
And yes, I know I am outnumbered about this. Cuz that's the definition of being a minority.

**Comment by CozmoB** [comment]
The largest ethnic group on the planet is Chinese Han but go off I guess. I'll leave it up to the higher ups to deal with. Guess Irish car bomb and the Italian mustache wasn't enough to set you off for some reason, guess some people only care about their own.

**Comment by SkullyRoberts** [comment]
Cosmo, please don't comment on PRs until you code literally anything for the server. It's just silly. This is for developers, not randos.

**Comment by SkullyRoberts** [comment]
Also, once again, Japanese, not Chinese. We are two separate races.

**Comment by RogueSteampunker** [comment]
>Cosmo, please don't comment on PRs until you code literally anything for the server. It's just silly. This is for developers, not randos.

Imagine arguing that your voice should matter enough to remove something, and then proceeding to tell someone they can't speak on it.

The platform is for anyone who plays or codes for the game to speak on it. You can't suddenly tell people they can't comment on your genuinely controversial PR just cause they're opposing you.

**Comment by Sishen1542** [comment]
> Cosmo, please don't comment on PRs until you code literally anything for the server. It's just silly. This is for developers, not randos.

**Comment by SkullyRoberts** [comment]
Oh my god. Take this to the forum. Stop spamming my PR

**Comment by CozmoB** [comment]
> 
> 
> > Cosmo, please don't comment on PRs until you code literally anything for the server. It's just silly. This is for developers, not randos.
>

Guess people who play on the server are just randos and non-coders get no say? And I literally said "I'll leave it up to the higher ups to deal with" but you had to pop in your two cents didn't you.

**Pull request closed without merging**
