### PR TITLE
Satchel of Holding!

### PR DESCRIPTION
**Pull request by Sishen1542**
-Adds a satchel of holding to bluespace pocket techweb, with keeping everything intact by having it only printable by the science fab. 
-Same stats as a bag of holding but without the ugly back sprite. 
-Allows BoH-bombing with both bags and satchels and also interferes with everything as a BoH does.
-In-hand sprite is same as BoH, kept in line with other satchels sharing hand sprites with the proper departmental backpacks. 
-Slight powercreep for angel toxin due to their ability to wear satchels.

### CODE REVIEW

**Comment by Sishen1542** [comment]
The cloak/vest commits are just because I'm dumb and forgot to branch prior to working. Force changed files so there'd be no frills to the satchel.

**Comment by Poojawa** [comment]
Really just looks like you took the animation and slapped it on the side of a regular grey satchel. Supposed to look tech-y

**Comment by Sishen1542** [comment]
I'll agree it looks butt, but I'm just an amateur. Definitely willing to have someone else sprite up a better version. It's functional as-is now though.

**Comment by davidchan13** [comment]
Why do I get the feeling this isn't properly flagged to trigger a 'special' event if its put inside of a BoH or vice versa.

**Comment by Sishen1542** [comment]
It is properly tested for BoHbombing in both satchels and bags, respectively.

**Review by silicons — APPROVED** [review]

**Pull request merged**
