### PR TITLE
Revert "Fancier throws, bullet casings, and more"

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Reverts Citadel-Station-13/Citadel-Station-13#7997
Why?
People don't like it. it looks horrible and isn't fun to deal with

### CODE REVIEW

**Comment by deathride58** [comment]
Yeah, that's really no reason for a full revert. If we reverted shit just because a vocal minority hated it, then we wouldn't have widescreen, we wouldn't have night shifts, we wouldn't have a night mode interface, and we wouldn't have anything unique to separate us from TG.
Closing at 24 hours unless another maintainer gives me damn good reason not to

**Comment by Trilbyspaceclone** [comment]
> Yeah, that's really no reason for a full revert. If we reverted shit just because a vocal minority hated it, then we wouldn't have widescreen, we wouldn't have night shifts, we wouldn't have a night mode interface, and we wouldn't have anything unique to separate us from TG.
> Closing at 24 hours unless another maintainer gives me damn good reason not to

A lot of people do not like it Bhijn and makes problems and looks horrible. Its not even a vocal minority, 
Also Its hard to fine people that didn't like night mode interfaces or widescreen, So yes those are vocal minority, BUT ask a lot of people and they tend to say "No I think it doesn't look grate" and that doesn't even account for the unfair way you can hide things or past items farther then you should.

Its not even a Kneejerk revert I waited 13 days and ask people about it.

**Comment by deathride58** [comment]
Name the actual problems it causes.

**Comment by Trilbyspaceclone** [comment]
@deathride58 
It looks bad, it adds Rng combat system with slip items, it stops people form seeing items like heads with right click, it prevents items form showing with right click, it has many problems.

**Comment by nik707** [comment]
Can you provide some proof of the bugs it causes? I haven't played with it but if you actually  can show me it causes issues I'd be for a revert until fixed solution, otherwise, I'd like to see a vote on player opinions.

**Comment by deathride58** [comment]
How the fuck does it add RNG with slip items and how does it stop items from showing in the context menu. I've tested the PR for quite a long time and I have yet to see a single instance where an item fails to show up in the context menu when you right click on the item itself or the tile itself.

**Pull request closed without merging**
