### PR TITLE
Possible runtime fix on Lighting list

### PR DESCRIPTION
**Pull request by Poojawa**
I haven't anywhere near the tools to test it solo, but basically  I copied what was done ages ago on TG by adding "" to the list() lines

might be a spectacular failure, but it's a quick fix idea

### CODE REVIEW

**Comment by Poojawa** [comment]
@PJB3005 If you could sanity check this, since you've been doing a lot of the heavy lifting. It's to fix #152

**Comment by PJB3005** [comment]
If this does anything it sounds like a genius way to break things at best.

That issue report is far from specific on what the issue is at all.

**Comment by Poojawa** [comment]
It didn't throw any errors at me, but like I said it wasn't really a good test environment since I've no idea what to spawn/do to use a ton of light sources

Just one of those, 'fuck it might just work' simple things. Damnifino.

**Comment by Poojawa** [comment]
Probably not the solution we're looking for.

**Pull request closed without merging**
