### PR TITLE
Reverts 10486 (Observe verb in the Ghost tab)

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Reverts #10486
Puts Observe back in OOC

## Why It's Good For The Game

Observe is directly paired with Cancel Camera View, a verb also in the OOC tab. Cancel Camera View has other uses outside of Observe so moving it to Ghost would break things.

Switching tabs to go in and out of Observe is annoying

## Changelog
:cl:
tweak: Observe is back in the OOC tab
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
fun fact, using observe a 2nd time stops observing before opening the menu, which you can close out of

this has no relation to this pr

**Comment by YakumoChen** [comment]
That's hacky and not immediately obvious.

**Comment by YakumoChen** [comment]
I couldn't tell you why travis is shitting the bed this time

**Comment by Arturlang** [comment]
Honestly, observe was too out of the way as it was, it ought to get its own hud button or have a pref to activate on orbiting someone

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
