### PR TITLE
Removes greentext

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Only lists antag objectives, not saying whether they succeeded or failed.

## Why It's Good For The Game

Greentext is pretty universally recognized to be unhealthy, so I've just gone and removed it here. Let's see if it improves anything or if we end up with more "ooc I GREENTEXTED Y'ALL"

## Changelog
:cl: Putnam
del: Greentext is gone
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
madlad

**Comment by ForrestWick** [comment]
Speaking as an antag main:

Speed merge please

**Comment by Arturlang** [comment]
B-B-but muh greentext

**Comment by Fractious** [comment]
Epic.

**Comment by EldritchSigma** [comment]
Yes. Oh my god yes.

Two things that will inevitably happen if this gets merged: 

People who permakill for "doing muh objective" will be considered massive assholes and there will be drama over this. This is bound to happen with this community. Besides those objectives are to put it into perspective like a crack in a glass with an oversaturated solution. It helps salt formation massively.

Permakilling for the sake of doing your objective as a fucking solo antag is no longer required since there is no incentive (greentext) to do so. Killing them once and leaving them to be found to "teach them a lesson" could be considered as enough by antags that do actually think about other peoples enjoyment (unlikely, but hey the world is full of different things).

--> People will still do that since people are people.
--> --> People will still go out of their way to "frag the antag" aslong that happens.
It could potentially result in people actually acting things out and not opting for most optimal path and you know cause slightly less salt under the line. People being salty is (thermodynamically) disfavored. People being slightly less salty is (thermodynamically) less disfavored. 

Love the idea, love that entire PR, would ERP. Finally someone with balls to propose that change. Though I doubt it gets the desired outcome in the desired order of magnitude.

**Comment by Ghommie** [comment]
:crab: And I thougth you were referring to the wizard event one but I was wrong. :crab:

**Comment by ghost** [comment]
i think it'll just have people do whatever they want, which can only be worse than the objectives because if it was less destructive they wouldn't do them anyways

**Comment by Putnam3145** [comment]
> 
> 
> 🦀 And I thougth you were referring to the wizard event one but I was wrong. 🦀

honestly might make an exception for that one tbh. just make it show a proper greentext at round end no matter what, with the "success" and "succeeded" and everything

**Comment by lolman360** [comment]
give it 4chan greentext format
>be me
>[role}
>need to succeed
>succeed

**Comment by Iroquois-Pliskin** [comment]
Greentext promotes shitty practices by both antags and crew. It was neat once, but when someone is so focused on winning that they just use the powergame meta every antag round, it gets boring fast.

Good PR

**Comment by ShadeAware** [comment]
Excellent PR. This opens the door for actual creative antag rounds instead of the meta to get the greentext every time.

**Comment by Tename** [comment]
you are all meming right

**Comment by Tename** [comment]
you are all meming right

**Comment by dzahlus** [comment]
can't wait to abuse this in ahelps after i hijack the shuttle for fun because no objectives 🤔

**Comment by Putnam3145** [comment]
> no objectives  

please, try to actually read the PR.

you don't even have to read the code, it should be pretty clear from reading here that it's just removing the bit that says "Success!" or "Failure!". The literal greentext bit.

**Comment by Tename** [comment]
please explain your reasoning to why showing of someone completed a certain objective or not is unhealthy

**Comment by xurxomario** [comment]
I dont know why, but i feel like this will backfire massively, i forsee this leading to more traitor griff than ever, tho cant be sure till its in action i guess so, i dont really dislike the change /that/ much i guess.

**Comment by GrayRachnid** [comment]
> 
> 
> please explain your reasoning to why showing if someone completed a certain objective or not is unhealthy

It reinforces the winning or losing mentality when SS13 is more about the Experience rather than the outcome.

**Comment by Tename** [comment]
> > please explain your reasoning to why showing if someone completed a certain objective or not is unhealthy
> 
> It reinforces the winning or losing mentality when SS13 is more about the Experience rather than the outcome.

it's also about doing your job, why should i not know if an antag did his job. this just encourages fucking off and doing whatever you want with tator gear.

**Comment by Putnam3145** [comment]
no other jobs in the game greentext, though?

**Comment by Tename** [comment]
> no other jobs in the game greentext, though?

because no other jobs involve having to specifically murder people

**Comment by necromanceranne** [comment]
Or steal shit. Knowing that your objectives being a success or not won't be telegraphed to you at round end is basically just making the entire point of the exercise...pointless. Sometimes you fail it in ways you don't anticipate. It happens.

TBH what does this incentivise other than strongly telling antags not to bother doing anything or a permit to do whatever they want as their objectives quite literally cannot be acknowledged as successful or not.

**Comment by Ghommie** [comment]
Discord's "Emojicracy" wants this closed. Giving you about one day to convince me this won't sit in PR limbo for eternity.

**Comment by deathride58** [comment]
There's significant value in this PR. Going purely off emojiocracy has a tendency to be pretty bad for the game's health.

**Comment by Tename** [comment]
Also let me add, no other job type you can't openly show people your work for recognition or tell them what you do or you will probably be taken out of the round. An engineer can show off his big dick energy design, science can show off his nest grenades, medical can show off the not dead people at their door, antags can't really show shit.

Why should I play an antag if the only people who see what I have done is a bunch of ghosts I will never interact with, a few people I murdered and will hopefully never interact with again that round, and security if I fuck up.

I find recognizion for my work a very satisfying part of the game and I see no reason being an antagonist if everything I do is pointless because it leads up to nothing.

**Comment by Tename** [comment]
My point is, just knowing that you yourself completed your objectives doesn't really sell it for everyone, some people are fine with just that, I'm not. You want to make it a fucking preference option, sure go ahead, I don't know why anyone would enable it though. Knowing if someone did their objectives or failed them usually sparks up a lot of cool conversations and story sharing for me both in game and out of game and it would be a disaster to see it removed for honestly a really poor reason.

**Comment by Weblure** [comment]
This PR is invalid straight off the bat. No worthwhile reason was given for how this would actually improve the game. You can't just give a weasel explanation of "X is pretty universally recognized to be unhealthy" and expect people to accept it, especially when the majority of voters and commenters strongly disagree. 

I see absolutely no reason for removing the primary motivation for antags to do their objectives. If nobody can see if you did your objective or not, why even bother doing them? This just encourages antags to do whatever the heck they want, since nobody can call them out for not completing their objectives anymore. 

I could go on and on, but most of everything has already be covered by other people here. In the end, it boils down to someone removing a core mechanic from the game for one incredibly weak, biased, and weasel-worded reason. This PR's author has also given 0 effort into elaborating on why this would be good for the game, nor have they offered any sort of counterarguments for the numerous comments explaining why this PR is bad.

I'm honestly appalled that some people, especially staff, are unironically considering this joke of a low-effort salt PR. This should've been closed by now for being invalid. Do the PR submission guidelines not even matter anymore?

**Comment by Putnam3145** [comment]
main reason i haven't been able to personally give a reply is because i'm basically a messenger here who is neutral on this stuff in general *except* that removing greentext makes it slightly easier for me to harder-to-track antag objectives

it's self-labeled "testmerge only" and "salt" for a *reason*, y'know

**Comment by necromanceranne** [comment]
Sorta like wizard objective being basically 'fuck shit up, fam'?

**Comment by Weblure** [comment]
> main reason i haven't been able to personally give a reply is because i'm basically a messenger here who is neutral on this stuff in general _except_ that removing greentext makes it slightly easier for me to harder-to-track antag objectives
> 
> it's self-labeled "testmerge only" and "salt" for a _reason_, y'know

In that case, it'd probably be better to open this as a draft for discussion, or have someone else upload it that fully supports it. As it stands, I see very little reasoning supplied for why this should be merged or how it'd improve the game in any way.

I suppose I should be asking @deathride58 for their input, since they're the one that reopened this?

**Comment by Putnam3145** [comment]
"Testmerge only" means it *shouldn't* be merged, so far as I can tell, and *is* a draft for discussion--or rather, testing.

**Comment by Weblure** [comment]
A testmerge affects gameplay just as much as a real merge, the only difference is that it's easier to remove. A draft would ideally be discussed before ever actually making it into the game, testmerge or not. This has been (test)merged for at least a few days straight, and I've honestly lost interest in playing antag roles because of it.

**Comment by chefferz** [comment]
I entirely disagree with this PR for the reasons below.

Yes, greentext makes crew and antags focus on those objectives, but ultimately that's what the antagonists are there for. This makes the game unfun for the antagonist because it doesn't give them the validation of having completed their objectives, nor lets them know if that person they murdered just happened to slip out of their grasp and get cloned, or that they accidentally downloaded 24 nodes of research than 25 and ultimately they failed.

Greentext is what allows antagonists who are newer the ability to craft themselves around the method of obtaining that validation. It punishes not tying up loose ends by showing you in big, bold, red that you did not succeed said objective.

You want to make antagonizing about the experience? Why not make objectives that you can pick from a pool as a traitor, so you can mold the story how you see fit as an antagonist? Even let traitors pick from the same pool so you'd have them fighting over stealing the nuke core or secret documents.

**Comment by Ghommie** [comment]
This PR hasn't been testmerged in days and the author moved on to make an improved version of this PR as well as several related overhauls.

**Pull request closed without merging**
