### PR TITLE
Game info verb for ghosts

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Ghosts can now hit a "game info" button that shows all the antagonists, what the current game mode is, and extra info on a mode-to-mode basis (e.g. dynamic will show storyteller, threat info)

## Why It's Good For The Game

Observer gang needs more good stuff

## Changelog
:cl:
add: Ghosts can see some extra info about the game
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
I am.. unsure if thats such a good idea, kinda opens up some very big metaknowledge paths, especially to people who die midround, ghost, click the verb, then get revived later.

**Comment by Putnam3145** [comment]
Ghosts like to yell about who the antags are to each other and such anyway?

**Comment by Detective-Google** [comment]
observer antag hud is here baybee

**Review by Ghommie — CHANGES_REQUESTED** [review]
This should only be usable by those people who have DNR or joined in as observer (Yea, I'm thinking of porting the PR that made antag moodlets invisible to observers later), the rest better gotta ask instead.

**Comment by Putnam3145** [comment]
Done.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
