### PR TITLE
[READY]Ports new brain traumas from /tg/, the creep side-antag, and the Desynchronizer. Also ports some new defines and traits.

### PR DESCRIPTION
**Pull request by GrayRachnid**
## About The Pull Request
This adds new brain traumas and re-codes how some of them work. All of this was ported from /tg/. No specific PR because I kind of cherry picked what to take. The magic traumas were not ported because that'll need me porting over the new wizard spells too. I'll be doing that later.

This also adds the destabilizer, a new toy for research. Blocked behind bluespace and syndicate tech.

## Why It's Good For The Game
Brain traumas are fun and it's about time we got some new ones.

## Changelog
:cl:
add: New antag, though a bit.... yikes
add: New traumas
add: Destabilizer
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
the desynchronizer is basically just an immortality talisman

**Comment by GrayRachnid** [comment]
derp i called it the wrong name

**Comment by GrayRachnid** [comment]
I don't know why travis broke.

**Comment by Thalpy** [comment]
Ah please don't remove friendlify, it's used with mku.

**Comment by GrayRachnid** [comment]
oh sorry, that was an accident. I'll re-add it.

**Review by Putnam3145 — APPROVED** [review]
Can't see any obvious issues with the code except some weird whitespace issues in all this. Feature-wise, obsessed is iffy, but whatever, that can be changed later with little trouble.

**Comment by GrayRachnid** [comment]
Okay, now I /actually/ add the creep side-antag.

**Comment by GrayRachnid** [comment]
Nevermind, i'm not adding the creep. Re-making this PR.

**Pull request closed without merging**
