### PR TITLE
Flightsuit Armor adjustments

### PR DESCRIPTION
**Pull request by Poojawa**
:cl: Poojawa
balance: returned Flightsuit armor to being less useful, also ensured they're not getting the best possible huds as well. Batteries to be done eventually.
/:cl:

These are minor, really. Once I figure out how to apply the ion thruster borg qualities to 'em, that'll bring 'em in line to how they really should be.

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
Modularize! Ree!

**Comment by Poojawa** [comment]
I don't trust it for this :v

**Comment by deathride58** [comment]
cmon, dork, simple value changes don't need to touch core files

**Review by ZeroNetAlpha — CHANGES_REQUESTED** [review]
Can you re-buff radiation protection? This is an engineering built suit after all.

**Comment by deathride58** [comment]
#5516 makes it much easier to modularize this

**Comment by Poojawa** [comment]
@Zna12 Why does this need rad protection Atmosia's armor has 0 rad protect as well.

There needs to be more drawbacks for the maneuverability and retarded all access it gets.

**Comment by ZeroNetAlpha** [comment]
@Poojawa it is also an endgame item that takes a ridiculous amount of waiting to get, waiting for mining to get their shit together, waiting for science to research, waiting for it to be built. Maybe perhaps nerf its door slipping abilities some?

**Comment by deathride58** [comment]
It isn't an endgame item at all, unless science decides to prioritize mining and sec gear over engineering gear.

Also, folks wearing radsuits are rarely, *rarely,* ***rarely*** ever going to be spending more than 5 seconds in irradiated areas, which makes a removal of their rad protection a non-issue.

**Comment by Poojawa** [comment]
so about 20m, tops.

And yes, planning on removing/disabling the 'slipping past' the airlock. adding a battery required, and such.

It's a mobility upgrade, it shouldn't be anything else.

**Comment by cebutris** [comment]
I don't think the armor values need to be substantially worse than the engineering hardsuit- This thing is a space suit, it should be able to withstand a couple of smacks. I'm not saying it should be BETTER, mind you, but this is a bit of an extreme nerf. I don't see how a how a literal space suit would be less protective than a sec jumpsuit.

**Comment by deathride58** [comment]
It ain't a space suit, it's a *flight* suit.

**Comment by Poojawa** [comment]
If you look at the armor values, it implies the thing is heavily reinforced, shielded, and also still light enough to _infinitely hover with 0 issues_

also reminder that the EVA suit, which is a space suit, has no armor

**Comment by cebutris** [comment]
Oh, in that case, this is fine 👍

**Review by deathride58 — DISMISSED** [review]

**Pull request merged**
