### PR TITLE
probably stops borgs from clicking fast enough to circumvent low health module failures

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

also this is a webedit so someone should look over this since I spent very little time on it

## Why It's Good For The Game

borgs being able to click fast and launch syndie grenades when they're damaged is bad

## Changelog
:cl:
fix: borgs being able to select and use a module when it's too damaged
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
i actually do not like this regardless of it being unintended as a side effect of how this is handled because i don't like borgs having basically a new "softcrit" where they can't do anything. 
also to me the image of a borg struggling to keep alive when it's nearly dead and barely able to function and still getting off hits is something that's good.

**Comment by Trilbyspaceclone** [comment]
Iirc kev you one time as a syndi borg with a gun killed someone well almost dead do to being able to pull out your saw and gun down the person attacking you, at critical health were a normal person would have been in hard crit. Let alone be able to try and run away or attack the person back...

What im getting at is that this bug has directly helped people sillicons alive and such and that they dont need more nerfs. This is a case were through skill and action a player was able to win based on not luck.*

**Comment by silicons** [comment]
silicons never had critical health as normal people experienced tbh, don't think they need it either, maybe weakening at super low health but nothing like the normal "softcrit/hardcrit" thing.

**Comment by necromanceranne** [comment]
God forbid a borg suffers from damage that would put a carbon well and truly close to death and is incapable of fighting back only up until the absolute brink of destruction. Meanwhile carbons keel over because they stubbed their fucking toe on an airlock. Don't mollycoddle borgs. They are statistically fucking obnoxiously overcompensated for as it is and don't need it and it isn't an excuse to retain broken buggy functionality.

**Comment by Ludox235** [comment]
> 
> 
> God forbid a borg suffers from damage that would put a carbon well and truly close to death and is incapable of fighting back only up until the absolute brink of destruction. Meanwhile carbons keel over because they stubbed their fucking toe on an airlock. Don't mollycoddle borgs. They are statistically fucking obnoxiously overcompensated for as it is and don't need it and it isn't an excuse to retain broken buggy functionality.

Silicons are supposed to be better than humans in most ways but have one or two super bad weakness. You can legit take out a syndiborg with a fucking flash

**Comment by silicons** [comment]
cyborgs have their own sets of strengths and weaknesses and to me not having the normal damage-weakness "scaling" is part of it

obviously a better way to handle this would be proper thresholds than keep in unintended things from a time when everything was life() processed than event driven but hm

**Comment by Ghommie** [comment]
screw it let's do it.

**Pull request merged**
