### PR TITLE
Makes a new COMBAT inducer! - Admin only

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
A brand new inducer made for COMBAT!!!
:cl: optional name here
add: Combat inducers for COMBAT!
/:cl:
[why]
More inducers are always fun and this one will allow for sec to do combat charging of their cell

### CODE REVIEW

**Comment by Poojawa** [comment]
Why tho

Why do powergamers need field rechargers.

**Comment by Trilbyspaceclone** [comment]
To deal with threats such as xenos

**Comment by deathride58** [comment]
Yeah, I am really not liking the balance implications that this PR has. Inducers had gun recharging removed for very good reason

**Review by silicons — APPROVED** [review]
this can stay admin only.

**Pull request merged**
