### PR TITLE
Nerfs the pandemics production.

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Doubles the pandemics cooldowns.

## Why It's Good For The Game
Should hopefully encourage doctors to not spam vaccine bottles and use it more efficently and smartly, plus makes it more difficult for bloodsuckers to sustain themselves oni it.

## Changelog
:cl:
balance: The pandemic can no longer make vaccines or synthblood as quickly.
/:cl:

### CODE REVIEW

**Review by Ghommie — APPROVED** [review]

**Comment by Putnam3145** [comment]
you forgot to mention that this is a massive nerf for virologists

**Comment by IronEleven** [comment]
Is the Chemmaster still unable to accept synthblood?  If so, this hurts viro bad.

**Review by silicons — DISMISSED** [review]
halve the blood made instead please, this will shaft viro hard.

**Comment by Arturlang** [comment]
Halved the blood made, and made it into synthblood, and undid the cooldown increase. Shouldnt be as bad for virologist, as they dont actually need that much for viruses.

**Pull request merged**
