### PR TITLE
stands now remove trait_nodeath from their user if given by memento mori 

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
what it says on the tin

## Why It's Good For The Game
stops memento mori memes

## Changelog
:cl:
balance: hugboxing mining loot
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/194e420a1c45d4742dfe89e1fc0e3cdec6400ec3/code/modules/antagonists/blob/blob/blobs/blob_mobs.dm#L222
Do this instead, it's a more consistent solution.

**Comment by silicons** [comment]
this nerfs traitor stands too, why is this necessary instead of just fixing memento mori + stand?

**Comment by Thalpy** [comment]
Maybe give a to_chat message to the grabber to say why, so they don't keep trying to grab and get confused, something like "They're too slippery to grab!" or something, or state the the memento mori is the reason why.

**Comment by Sishen1542** [comment]
i broke it doing blind work fuck, let me take a nap and ill fix/test shit when im up

**Comment by Sishen1542** [comment]
should work now

**Review by silicons — DISMISSED** [review]

**Comment by Sishen1542** [comment]
having a stand will now remove trait_nodeath from the user as long as the source is the mori necklace, you still keep pulling & you will keep the nohardcrit and nocritdamage traits

**Review by silicons — APPROVED** [review]

**Pull request merged**
