### PR TITLE
pAIs can no longer untie people's shoelaces

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

oversight

## Changelog
:cl: silicons
del: no more pais untying shoelaces
/:cl:

### CODE REVIEW

**Comment by Echopsychotic** [comment]
I had no idea shoelaces were a thing now

**Comment by lolman360** [comment]
good

**Comment by Tupinambis** [comment]
It's FUN!

**Comment by KeRSedChaplain** [comment]
my disappointment is immeasurable and my day is ruined :pensive:

**Pull request closed without merging**
