### PR TITLE
New stamp icons

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of:
https://github.com/yogstation13/Yogstation/pull/9588

## Why It's Good For The Game

A lot of these are minor adjustments giving a bit of color to the stamps.
I'm not 100% confident on the RD stamp, but, it was in the original PR, so I figured I'd bring it too. I'm fine with taking it out.

## Changelog
:cl:
tweak: New stamp pictures!
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Hm, honestly looking at the difference, I kinda prefer ours to the new ones, except for the captains and the CE's, the color bit is nice, and the CE's stamp is WAY too yellow for my liking.
I'm totally open to others opinions on this.

**Comment by LetterN** [comment]
they look much more blurred? And are these the old stamps?

| This PR| Current |
|--------|--------|
|||
|cenew|ceold|
|rdnew |rdold |
|rdnew |rdold |
|rdnew |rdold |
|rdnew |rdold |
|rdnew |rdold |
|rdnew |rdold |

**Comment by MrJWhit** [comment]
You can compare the images directly by going to Files changed, then hitting the Display the rich diff then you can just compare the two side by side.
But yeah, they look more scruffy when you stamp things, the ink isn't always completely accurate.

image

**Comment by CameronWoof** [comment]
The current stamps look much cleaner and just plain nicer to look at than the ones proposed here, to my eyes.

**Comment by keronshb** [comment]
The old ones look smoother, these kinda look blocky and off center.

**Comment by DeltaFire15** [comment]
I agree with the other comments here, these looks really blurry when compared with our current stamps. Preferring the ones we have.

**Comment by silicons** [comment]
we're in agreement then i guess

**Pull request closed without merging**
