### PR TITLE
Makes meteors require higher station population to roll more destructive waves.

### PR DESCRIPTION
**Pull request by chefferz**
Does as it says on the tin

Also shifts the weight up.
Also limits 1 of each meteor wave type.
Also pushes the time for them to start out a bit more so engineering actually has time to make shields.

### CODE REVIEW

**Comment by silicons** [comment]
A bump in numbers was needed but these are way too high and I don't see why you need 1 max occurence for the weaker waves.

**Comment by chefferz** [comment]
> 
> 
> A bump in numbers was needed but these are way too high and I don't see why you need 1 max occurence for the weaker waves.

What do you propose then.

**Comment by GrayRachnid** [comment]
😂

**Comment by Ghommie** [comment]
Kevinz is already handling meteor waves in a more acceptable way. Closing this without second thought.

**Pull request closed without merging**
