### PR TITLE
heterochromia: you can select individual eye colours

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
by default the toggle is off and your eyes remain the same colour
eye overlay is now two separate overlays
you can now select individual eye colours (and yes I spelt colour the american way for consistency throughout the code)

## Why It's Good For The Game
we're a snowflake server without this snowflake feature somehow
customization is good
[insert sans joke here]

## Changelog
:cl:
add: you can now have heterochromia and select individual eye colours
/:cl:

### CODE REVIEW

**Comment by jack-avery** [comment]
cant wait to see the overabundance of blue/pink or green/yellow eye combinations because 'character crazy mode'!!!!

**Comment by moltoretardo** [comment]
❄️ inbound

**Comment by The-Sun-In-Splendour** [comment]
Finally, now I can be the greatest ❄️ I've ever wanted to be.

**Comment by necromanceranne** [comment]
Setting your right eye to white justificaties the eyepatch now. You are visibly blind in that eye!

**Comment by kiwedespars** [comment]
image

**Comment by Putnam3145** [comment]
All this left_eye_color and right_eye_color stuff is mostly making me think that you should just have an "eye_colors" list, just in case we add a more-than-two-eye'd species, but I'm weird like that, so.

**Comment by timothyteakettle** [comment]
adding multi eyed species would require more support than just that, due to how it relates to dna blocks and the overlays being applied

**Pull request merged**
