### PR TITLE
LaTeX-in-paper

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Adds LaTeX formatting for paper, can be used when you put a latex equation in two $

## Why It's Good For The Game
Kevins asked me to do it, and by god, I fucking did it. 

## Changelog
:cl:
add: You can now put in LaTeX equations in TGUI paper if you insert them between two $ dollar signs
/:cl:

This took a lot of effort due to how tgui modules work, I went through about three different modules and fucking around with their dependencies was awfull but I managed to make it work with KaTeX
image

image

### CODE REVIEW

**Comment by Arturlang** [comment]
It will also render red if it has invalid formatting for latex

**Comment by Arturlang** [comment]
This does increase the size of tgui by 189 kb's, which is a lot, if you look at the big picture
image

**Comment by Arturlang** [comment]
-KaTeX is the module used to make this possible

**Comment by Arturlang** [comment]
image

**Comment by Arturlang** [comment]
vs current 
image

**Comment by Linzolle** [comment]
this is a bit cursed

**Comment by Arturlang** [comment]
@Linzolle Define "cursed"

**Comment by Linzolle** [comment]
> @Linzolle Define "cursed"

just the fact that you got LaTeX working in this is wack

**Comment by Arturlang** [comment]
@Linzolle That it is, but thankfully all it is is rendering HTML, and I did it after the sanitiziation, there might be problems due to sanitization removing needed stuff for some forms of latex, but I don't think it should be an issue

**Comment by silicons** [comment]
i love you so much artur

**Pull request merged**
