### PR TITLE
TALLY HO! (adds claymores to the uplink)

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Adds claymores for 8 TCs with a 25 player minimum poplock.

## Why It's Good For The Game

It's a less-concealable esword for being a pointless badass.

## Changelog
:cl:
add: The Syndicate started selling claymores to their agents.
/:cl:

### CODE REVIEW

**Comment by Drowzyleaf** [comment]
Now we just need a 40tc one with highlander mechanics

**Comment by Trilbyspaceclone** [comment]
Oh shit im so going to add in knight gear
and a buckler to that

**Comment by Trilbyspaceclone** [comment]
Also
"Esword" but a 2 hit weapon 
```/obj/item/claymore
	name = "claymore"
	desc = "What are you standing around staring at this for? Get to killing!"
	flags_1 = CONDUCT_1
	slot_flags = ITEM_SLOT_BELT | ITEM_SLOT_BACK
	force = 40
	throwforce = 10
	w_class = WEIGHT_CLASS_NORMAL
	block_chance = 50
	sharpness = IS_SHARP
	resistance_flags = FIRE_PROOF
        total_mass = TOTAL_MASS_MEDIEVAL_WEAPON```

**Comment by Arturlang** [comment]
Esword but you cant hide it, big difference.

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
