### PR TITLE
licking people washes pie off their face

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
i am not a fetish coder
i am not a fetish coder
i am not a fetish coder

## Why It's Good For The Game
licking is still a pref thing that can be disabled so this is probably fine

## Changelog
:cl:
add: licking people washes pie off their face
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
This sounds stupid but,
add nutrition,
flavor of the thing on their face.

**Comment by BlueWildrose** [comment]
You're a fetish coder Tim. Accept it.

**Comment by timothyteakettle** [comment]
nutrition no because it shouldn't have any real mechanical effect as it's an opt-in/out thing, taste isn't possible as it just adds a pie overlay and no extra info, and i don't want to add in-depth pie licking mechanics thank you

**Comment by MrJWhit** [comment]
Do you have a... reason for this?

**Comment by timothyteakettle** [comment]
i want to say 'none' but this pr was not made in bad faith, it's just a small funny thing i thought of while on the discord, i guess the reason is 'it funny' and licking is wholely pointless anyway as a mechanic so lets add some funny fluff to it

**Review by Linzolle — APPROVED** [review]
amazing

**Pull request merged**
