### PR TITLE
[HELP NEEDED]Who needs TGUI? The TGUI Next is the future.

### PR DESCRIPTION
**Pull request by Arturlang**
This PR ports TGUI next from TG, which were made with many many many PRs.
Mainly by https://github.com/actioninja and https://github.com/stylemistake
## Changelog
:cl:
add: Replaces a lot of ingame UIs with TGUI next
/:cl:
This doesnt actually remove TGUI or oracleui, however a lot of stuff got updated so it is HIGHLY likely that I broke something. Currently it works locally, but havent yet added the purity hud things yet.

### CODE REVIEW

**Comment by Arturlang** [comment]
Guh, will need to push an empty commit, travis died to failing to make secret sauce

**Comment by Ghommie** [comment]
Best of luck while I deal with other things, spaceman.

**Comment by Arturlang** [comment]
Lacking replacement guis for sleepers, heaters, chemmaster, and chem dispensers, and having trouble as to how to not have to use them due to wierd shit im unsure how to deal with.

**Comment by actioninja** [comment]
We're very close to fully removing old tgui on tg, I would recommend waiting until that happens before doing a port. Then you could nuke both oracle UI and old tgui in one go.

**Comment by Arturlang** [comment]
@actioninja Just currently having trouble with Uis we modified on our base, really.

**Comment by Arturlang** [comment]
Currently having some git problems due to line endings nad not getting clean commits for merge from upstream

**Comment by Ghommie** [comment]
Did you follow the instructions I provided on discord to renormalize the EoL changes?

**Pull request closed without merging**
