### PR TITLE
removes the 2 best weapons in the game from traitor uplink's 10tc surgery bag

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
title
no more 90 unit volume spen
no more 1shot hardstun defib belt

## Why It's Good For The Game
i haven't checked gitblame but i feel like trilby did this one

## Changelog
:cl:
balance: advanced surgery duffel bag no longer comes with a nukie medkit. it costs 4 less telecrystals to make up for this colossal nerf.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

go away noone uses you

**Comment by ghost** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7938

lol

**Comment by silicons** [comment]
this do be kinda quirky tho

**Comment by Trilbyspaceclone** [comment]
Ye I made that, kinda was hoping more people would buy it.
I dont think the kit should be flat out removed, maybe replaced with a medical basic kit and lower the price by 1?
idk

**Review by Ragolution — APPROVED** [review]

**Pull request merged**
