### PR TITLE
tweaks Tesla Point income

### PR DESCRIPTION
**Pull request by Poojawa**
40m into the round, R&D is finished and drowning in hundreds of thousands of points.

I did mention the original values were not even tested nor were they being anything other than blatantly generous. 

github did a dumb on the last one.

### CODE REVIEW

**Review by deathride58 — APPROVED** [review]
Be sure to send this upstream

**Comment by Poojawa** [comment]
already have.

**Comment by kiwilover8** [comment]
Provided it isn’t incredibly difficult to add additional generators to the Tesla array, I see no problem in bringing the point income down to a reasonable 720~ if the 4 generators to points still allows enough to power the station without additional added

**Comment by JogBoba** [comment]
That kiwilover8 comment was me, old account I forgot I had.

**Comment by Poojawa** [comment]
That's part of the intention is to make it so engineering needs to choose, power or research contribution. 

once I get an estimate on power income for analyzers alone, I'll end up tweaking their penalty moreso. the basic setup should be profitable but not anything to speak of. all of them to analyzing should be a pretty hefty deficit in power, it's only 1/20th, but might need to be 1/50th

**Comment by JogBoba** [comment]
My intention with that comment is that RnD should be able to be finished in a bit over 2 hours with just passive gain, and I feel the engine being able to power the station and provide that at the same time would be a better alternative than increasing the base server gain, which is why I asked if it could still power the station while producing the needed 700+.

**Comment by Poojawa** [comment]
oh no, self merge.

**Pull request merged**
