### PR TITLE
too many COOKS IN THE KITCEN WHY THE FUCK IS THERE MORE THAN 1 COOK SLOT

### PR DESCRIPTION
**Pull request by lolman360**
nerfs whetstone avilability

## Changelog
:cl:
tweak: chef slots 2 >> 1
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
no

**Comment by Ragolution** [comment]
because the cooks usually die

**Comment by lolman360** [comment]
@Ragolution hop can open more slots or promote people to chef if it's really needed

**Comment by Ludox235** [comment]
No.

**Comment by timothyteakettle** [comment]
no kitchen is built for having two cooks it's always horribly cramped and ends with one cook killing the other, just like how you can have three botanists, or imagine having a /second bartender/

**Comment by Ludox235** [comment]
> 
> 
> no kitchen is built for having two cooks it's always horribly cramped and ends with one cook killing the other

**cough cough** Teak and Hanako fucking fighting each other for a kitchen :^)

**Comment by Ragolution** [comment]
In a less memey response, having 2 cooks allows one to be an antag without it being more explicitly obvious. A chef out of the kitchen is suspicious, but no chef in the kitchen is either normal or a major red flag, depending on how population is during your playtime.

**Comment by timothyteakettle** [comment]
its normal to have no cooks regardless of the population, also literally nobody is going to go 'woah theres no cooks he must be an antag'

having two cooks is extremely rare and when it happens it sucks for both players involved
there's a reason there's only one cook roundstart, having a second just seems like a bad oversight in the code

**Comment by SirGurgle** [comment]
> having two cooks is extremely rare and when it happens it sucks for both players involved

recently had a round with two cooks present, we immediately made enough food for 5 stations combined and became the best of friends.

**Comment by lolman360** [comment]
edge case, most of the time cooks aren't going to try to coordinate and instead do their own thing and get in each other's way

**Comment by Ragolution** [comment]
> edge case, most of the time cooks aren't going to try to coordinate and instead do their own thing and get in each other's way

good

**Comment by Iamgoofball** [comment]
its so you can have 1 chef and 1 sous-chef

**Comment by silicons** [comment]
goofball is correct

**Pull request closed without merging**
