### PR TITLE
makes Pride Month not affect the station name

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

Title says it all.

## Why It's Good For The Game

I just
think "Genderfluid Course 93" and stuff like that sounds dumb.

That's it.

## Changelog
:cl:
del: Pride Month station names
/:cl:

### CODE REVIEW

**Comment by TheEaterOfBeans** [comment]
why?

**Comment by bunny232** [comment]
🦀 homophobia is gone 🦀

**Comment by TheEaterOfBeans** [comment]
> 🦀 homophobia is gone 🦀

literally not homophobic
Pride Month station names just
sound
really
stupid

**Comment by Keekenox** [comment]
gay

**Comment by nik707** [comment]
who cares what the station name is lmao.
people have tried to remove this in the past and it was also summarily closed. if the station name is really bothering you that much maybe try changing the words to make it sound less stupid.

**Comment by nik707** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12451

**Comment by TheEaterOfBeans** [comment]
> #12451

that removes Pride Month entirely
this just makes the station names normal during Pride Month

**Comment by TheEaterOfBeans** [comment]
> gay

ok

**Pull request closed without merging**
