### PR TITLE
Ports in emoji.dmi updates, plus flushed emoji.

### PR DESCRIPTION
**Pull request by Ghommie**
:cl: Ghommie (Original PR by JJRcop)
add: Ports in more emojis, including : flushed :
/:cl:

Endgame spoilers ahead: tgstation/tgstation#44043

Amongst other updates the one properly giving transparent bg to the thumbs up/down and joy emojis.

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
image
Bring these back 🔫

**Comment by Ghommie** [comment]
I quite forgot that there were some unique emojis here toh, thanks for spotting. 
Edit: it's just the thonk one that was missing, the Horray one was a duplicate.

**Review by silicons — CHANGES_REQUESTED** [review]
image
fix

**Comment by Ghommie** [comment]
As I said before, that icon_state is a damn duplicate, there are two of them. If you open up the .dmi on your local you'll see.

**Review by silicons — APPROVED** [review]

**Pull request merged**
