### PR TITLE
Gee Kevinz, why does YOUR research division let you have A HUNDRED AND SIXTY fetish gas points?

### PR DESCRIPTION
**Pull request by ghost**
wtf

## About The Pull Request
miasma research define is now 6 instead of 120

## Why It's Good For The Game
no more 3.05e^7 research points

## Changelog
:cl:
fix: kevinz forgot to nerf miasma research and cargo value after making it produce like 100x as much lmao
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
salt pr

**Comment by deathride58** [comment]
good first pr

**Comment by IronEleven** [comment]
A 95% nerf seems like overkill.  I'm not denying it's incredibly powerful right now but the proposed values seem like it will simply stop being worth the effort to set up at all.

**Comment by ghost** [comment]
this is reverting it to before miasma generation buff, which multiplied the amount of mols made by corpses by 5x but also lowered their effectiveness. also the original 160 value makes it the BEST method of getting research points PERIOD, and can be done in similar speed to a toxins bomb with no research cap. by comparison hypernoblium fusion is worth 1000 and requires 90 minutes of setup

**Comment by ShadeAware** [comment]
Will it at least still be a viable way to make points?

**Comment by ShadeAware** [comment]
Still, a _95% reduction_ is a bit overkill imho. Maybe, like, 50-65%?

**Comment by ghost** [comment]
50% is still 500k points in 15 minutes, aka a couple times more than you need to do every research

i dunno if anyone commenting about it has seen it in use besides the science mains that do it every round, but basically you do 15 minutes work in the roundstart map and take an rpd to it and get 1 million research points

**Review by silicons — APPROVED** [review]

**Pull request merged**
