### PR TITLE
Makes combat boots look T A C T I C O O L

### PR DESCRIPTION
**Pull request by Coolgat3**
## About The Pull Request

This PR just makes the combat boots have its own sprite instead of using the jackboots one. Yes, the sprite is a re-skin of workboots but I think it looks good enough to be considered combat.

This is the sprite https://i.imgur.com/ePMmzdB.png

## Why It's Good For The Game

It makes people able to differentiate the items right away instead of having to hover over them

## Changelog
:cl: Coolgat3
imageadd: added combat boots sprite
/:cl:

### CODE REVIEW

**Comment by Coolgat3** [comment]
Me dumb and forgot to add image for quick reference, added.

**Review by silicons — APPROVED** [review]

**Comment by Arturlang** [comment]
Did... you test it?

**Comment by Coolgat3** [comment]
Yes and it worked fine..?

**Comment by Linzolle** [comment]
The boots don't seem to have a sprite on your character when worn with digitigrade legs?

**Pull request merged**
