### PR TITLE
Screentips

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
This PR adds screentips and remove the "bottom of the screen" coming from tg with some changes to support the stuff we don't have.
image

## Why It's Good For The Game
It's questionable?

## Changelog
:cl:
add: Screentips.
del: Removed the bottom grey section of the screen.
/:cl:

### CODE REVIEW

**Comment by TripleShades** [comment]
Would it be possible to get a preview screenshot?

**Comment by SandPoot** [comment]
Aye

**Comment by TripleShades** [comment]
So it looks like this adds the tips at the top of the screen, but also keeps them on hover in the bottom left?
Sound good to me.
People might complain or want a toggle though.

**Comment by SandPoot** [comment]
Screentips (one at the top) are toggleable. Bottom ones, i don't even know why someone would want it toggleable.

**Comment by Linzolle** [comment]
> Screentips (one at the top) are toggleable. Bottom ones, i don't even know why someone would want it toggleable.

probably from years of muscle memory of looking at the bottom left corner

**Comment by SandPoot** [comment]
Yes, and that is what i sorta mean, why would they want to disable the specific one attached to their muscle memory.

**Pull request merged**
