### PR TITLE
Glorious /vg/ Lighting Port

### PR DESCRIPTION
**Pull request by ghost**
This completely replaces the old lighting system with /vg/'s lighting system, which is based on Goonstation lighting. It has been changed in many places to be compatible with /tg/ code. New features include:

- Fully dynamic lighting; no more blocky, choppy tile-based lighting
- Lighting uses objects rather than subareas
- Supports all RGB colors + mixing
- 3 different vars for lighting instead of one luminosity var: light_range, light_power, and light_color, these are applied with the set_light proc rather than SetLuminosity
- Objects within objects can have lights
- Starlight support
- A whole bunch of other code changes. Lighting_docs is also outdated to hell and back so don't look there.
PLEASE NOTE THAT THERE MAY BE BUGS/MISSING LIGHTS/MISSING COLORS
If you spot any lights that should be colored or somewhat significant objects that need a light, please tell me at #coderbus on the discord server.

If anyone ever needs to update this any time, be careful not to break anything that has been changed for compatibility. (Or just tell me to update it I guess.)

Thanks to /vg/station for having this in the first place and PJB3005 for helping me a ton with this; it probably wouldn't have been done without him.

Images:
image

image

image

image

image

image

image

### CODE REVIEW

**Comment by TalkingCactus** [comment]
Is there any way to make complete darkness a bit darker? That looks pretty easy to see into http://image.prntscr.com/image/c07f0c3c5a144df9a4c5e84991863a98.png
Check the inside of maint here after the light finishes smoothing. Seems brighter than the dark edge of the shading.

**Comment by ghost** [comment]
I can't really test it since I'm stupid and deleted my entire fork instead of a branch but I see what you mean.
If you merge it I can take a look and see if it happens again.

**Comment by TalkingCactus** [comment]
it's not a huge issue and it can probably be fixed pretty quickly anyway

**Comment by PJB3005** [comment]
The issue with complete darkness is that it's very badly dependent on monitor brightness. When I picked the number for the soft lighting cap I could barely see very bright colours if I really looked for them on the monitor I initially coded it on, then when I went on another computer I could very easily see.

**Pull request merged**
