### PR TITLE
Cw3040 is constantly making horrible, horrible mistakes (like adding ball gags, which is what this PR is)

### PR DESCRIPTION
**Pull request by Cw3040**
changelogs in the commits

### CODE REVIEW

**Comment by Cw3040** [comment]
hmmmm
to add the locking function (to make it function like a shock collar or electropack) or not to add the locking function

**Review by deathride58 — DISMISSED** [review]

**Comment by deathride58** [comment]
Conflicts

**Comment by LetterJay** [comment]
@Cw3040

**Comment by Cw3040** [comment]
i forgot about this

**Comment by Cw3040** [comment]
bhijn why the shit did you merge a goddamn 5 day old PR and not merge this beforehand, which is a month fucking old

**Comment by deathride58** [comment]
The PR that this PR conflicted with was the hard sync, which was much older than 5 days

**Pull request closed without merging**
