### PR TITLE
hardcaps stamina to 200 again

### PR DESCRIPTION
**Pull request by silicons**
kek

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
you can modify the proc in the base files directly instead of relying on modular_citadel

**Comment by Hatterhat** [comment]
feature

**Review by deathride58 — CHANGES_REQUESTED** [review]
Fix this PR you noob

**Comment by Hatterhat** [comment]
ITS BROKE

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
