### PR TITLE
readds the cryo and lewdstuff on the map

### PR DESCRIPTION
**Pull request by LetterN**

### CODE REVIEW

**Comment by Cw3040** [comment]
-rep, 100% gay

speedmerge pls

**Comment by deathride58** [comment]
Can you post screenshots of or give screenshots of what you changed? Mapdiffbot isn't working for some reason

EDIT: oh im a fucking idiot nevermind

**Review by deathride58 — APPROVED** [review]

**Comment by Poojawa** [comment]
These should probably be copied to the backups as well.

**Comment by deathride58** [comment]
We branched away from TG recently. We don't have to worry about modularization or map backups anymore

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
