### PR TITLE
A simple fix and a simple test.

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

The sign from #10342 and literally nothing else.

## Why It's Good For The Game

See #10342.

## Changelog
:cl:
add: Adds a sign outside MetaStation's custodial closet
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
nice commits

**Comment by EmeraldSundisk** [comment]
I'm trying my best...

**Comment by Detective-Google** [comment]
just joshing ya it doesn't actually matter if they're like that

**Review by Ghommie — APPROVED** [review]
Umhhhh, looks all right, I think.

**Pull request merged**
