### PR TITLE
Adds not-so-great TMP-era trek utility uniform, also fixes loadout restriction descs

### PR DESCRIPTION
**Pull request by NopemanMcHalt**
## About The Pull Request
This PR adds a little more trek into citadel, hopefully enough to not get bonked by someone. It also fixes wrong restriction text, as cargo *can* wear existing trek suits aside from fedcoat.

## Why It's Good For The Game
It's trek! Also, something more to wear for assistants, and also bonus service uniform for, obviously, service department!

## Changelog
:cl: Anonymous
add: Federation utility uniforms - Enlisted, Trainee (for assistants, cargo techs and janitors), and Service (for civilian and service roles, aside from entertainers and lawyers).
spellcheck: Fixes wrong restriction description of existing trek suits.
tweak: Some trek uniforms in-hand shall now show basic corresponding color.
/:cl:

south
west
north

### CODE REVIEW

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
The palette is a bit too vivid imo.

**Comment by NopemanMcHalt** [comment]
Not a great spriter, just wanted something trek-related for everyone, incl. most of service department.

**Comment by Ghommie** [comment]
merge conflicts.

**Comment by NopemanMcHalt** [comment]
@Ghommie Why you put cargo uniform icon so dang far from QM in icon file? He's like lost child now.

**Pull request merged**
