### PR TITLE
zero, , null, and empty text strings, all fulfill the ! operator.

### PR DESCRIPTION
**Pull request by Ghommie**
:cl:
fix: Reduces goonchat lag from being blasted by pellets and bullets repeatedly whilst wearing armor by properly removing the armor protection texts this times.
spellcheck: also reduced the size of armor protection messages in general. they clog up the chat box.
/:cl:

Goon chat has some grave performance issues that people are reluctant to fix anyhow, repeated message output freeze the heck out of clients.

I really would like to remove the armor feedback messages altogether as they are more harmful than beneficial by doubling the chat box clog-up done by the oversized userdanger span hit by text.
And really, people normally focus their eyes on the graphical half of the game when robusting.
But I would like to hear others' opinions before trying to PR such removal.

### CODE REVIEW

**Comment by Ghommie** [comment]
Actually, what I first supposed may have been a stupid attempt at silencing bullet act feedback could actually be the coder merely setting the proc's armor penetration var (the fifth one) without naming it.

But either ways I'm keeping this up, the armor message really does backfire in several situation it can become annoying beyond "i ded".

**Comment by deathride58** [comment]
This doesn't reduce goonchat lag at all. The lag with goonchat comes from the message receiving JS function itself, as internet explorer is shit at handling javascript. This PR makes no changes whatsoever that would affect goonchat performance in any way.
However, this is a definite code quality improvement.

**Comment by Ghommie** [comment]
> 
> 
> This doesn't reduce goonchat lag at all. The lag with goonchat comes from the message receiving JS function itself, as internet explorer is shit at handling javascript. This PR makes no changes whatsoever that would affect goonchat performance in any way.
> However, this is a definite code quality improvement.

Perhaps there may be some very asinine miscommunication going on here. You are right, strictly referring it as a goonchat performance improvement is erroneous, but what I really meant to say here is that currently the armor feedback messages add in even more client freeze to already noticeable when repeatedly struck by pellets/scatter/too many flying items/gloves of the north star etc. while wearing any sort of armor against those.
It's simply the hit by and armor messages being separate messages, not joined together. I know it's not the contents, size etc that cause lag, but the function.

Your comment makes me doubt what I say, like everything anyway.

**Comment by Useroth** [comment]
Maybe it's worth considering to actually drop goonchat and revert to something simpler.

**Comment by Ghommie** [comment]
Goonchat has several pros, not only cons. Dropping it altogether may have negative consequences.
Like Deathride said, It's also because of Byond relying on the old windows internet explorer.

**Review by Poojawa — APPROVED** [review]

**Comment by Poojawa** [comment]
Goonchat made the game playable for me again on my laptop. The old chat would cause client hang over and over randomly that was never able to be fixed. Like, full on freezes that required a client restart levels of shitty hang.

The only real solution to mitigating the chat lag is to batch action all the to_chats into one message and just send that one. Stuff like health scanners, self examine were horrible culprits of this spam too.

**Comment by Ghommie** [comment]
>
> The only real solution to mitigating the chat lag is to batch action all the to_chats into one message and just send that one. Stuff like health scanners, self examine were horrible culprits of this spam too.

There is a chat subsystem on another codebase that queues and joins chat messages, then outputs the payload the next decisecond. Dunno how effective it would be here though.

**Review by silicons — APPROVED** [review]

**Pull request merged**
