### PR TITLE
TRADE OFFER: YOU GIVE ME 30000 PLASMA. I GIVE YOU A SINGLE MAGAZINE OF 10MM INCINDIARY AMMO

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
These costs were fucking stupid. 30000 plasma (at T4) for a single magazine is earnest insanity.
Let's be a little more sensical with this. 

This also adds box recipes for the ammo, at a high, but reasonable price, and removes the nonsensical reagent requirements.

## Why It's Good For The Game
Nobody is going to use these blueprints if you make them cost so goddamn much, for so goddamn little. Maybe we should **change** that.

## Changelog
:cl:
balance: Illegal Tech Ammo actually is fucking reasonable, now.
balance: Expensive Illegal Tech Ammo Boxes are now constructible, with actually justifiable prices.
/:cl:

### CODE REVIEW

**Comment by HeroWithYay** [comment]
55000 iron

Enough to rebuild an entire room
OR
One pistol magazine

Lmoa who balanced this.

**Comment by shellspeed1** [comment]
Ya know, I feel like there was meant to be one less zero here.

**Comment by TheObserver-sys** [comment]
This is ready for a full merge. Boxes work, mags work.

**Comment by The-Sun-In-Splendour** [comment]
TRADE_OFFER

**Pull request merged**
