### PR TITLE
Lambda Mk.II

### PR DESCRIPTION
**Pull request by dapnee**
## About The Pull Request
Lambda now has a second level, the civilian level, home to service, dorms, an atrium, a small clinic, chapel, and the garden. The civilian level can be accessed next to tool storage, or right below security. If you'd like to comment on things you like/dislike, you'll need to leave a comment here.

Level 1
Level 2

## Why It's Good For The Game
Fixes some issues on lambda while also adding more things to do on the map.

## Changelog
:cl:
add: atrium, clinic, an extra office, a pseudo public mining area, two more deluxe dorms, micro beach, aux bathroom, two construction areas, mass driver, more intercoms
tweak: moved all of service, chapel, dorms, garden, holodeck to a different z-level, RnD is more open, maintenance is a bit more random, more firelocks, added more mine-able rock
fix: fixed the buttons in xenobio, gave shutters to cargo's storage area, fixed holodeck so it works now, fixed some techfabs being lathes, added sensors to atmos tanks, more decals, couple more signs, little floral areas and sitting areas added to break up hallway monotony, mech chargers are no longer missing their consoles, whiteship won't crash into arrivals anymore while the area it takes up is more telegraphed, APC placement on AI sat entrance, missing wire node for the outer portion of the AI sat, civilian level now has a telecom relay
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
Just from looking over it...

A: Please add some public airlocks to the hallways please god.

B: I like the direction and with how (much of a mess) lambda is, it's a good test bed for this sort of thing. I think the second floor looks very pretty and nice.

Overall Lambda is a funky beast and this is something that will just need to play out. Good PR.

**Comment by MrJWhit** [comment]
This should be testmerged, but, I think it's good. This is the first time we're dealing with a multi-z station map like this, and I'd like to make sure everything is working as intended.

**Comment by moltoretardo** [comment]
Porpl

**Comment by dapnee** [comment]
I see the maps been test merged for a while, have any issues occurred or is it the normal “not enough people on and the map wasn’t voted” issue? I’d be interested in adding rails lining the atrium, I think SR has a port of the updated version tg has. Other than that, I’m happy with this if no other issues have arisen.

**Comment by Sonic121x** [comment]
1:MiniSat Foyer APCAPC
2:The second floor is not covered in telecom,a telecommunication relay should fix this.
3:More intercom around the hallway and have least one in front of every department would be nice.

**Comment by dapnee** [comment]
Alright, I’ll get an update up later tonight when I have time, thank you.

**Pull request merged**
