### PR TITLE
changes the name of iron ore to metal ore

### PR DESCRIPTION
**Pull request by nik707**
[Changelogs]: iron ore is now called metal ore.

:cl: nicc
tweak: changed iron ore to metal ore
/:cl:

[why]: Because it makes slightly more sense than iron ore magically becoming other metals for things like wall plating. Now 'metal ore' is just a catch-all term for the various metals that would make sense for the metal sheet items various uses. IE, The walls of the station that may be steel/aluminum, metal circuitry that would more likely use copper, chairs which could be steel, aluminum, who knows, bullets which could be lead or steel or fuck even tungsten who knows man future.

### CODE REVIEW

**Comment by improvedname** [comment]
No

**Comment by nik707** [comment]
thats the first negative ive gotten on this change.

**Comment by silicons** [comment]
my vote is no

**Comment by Stalkeros2** [comment]
No, just no, my inner dwarf is angry

**Comment by ghost** [comment]
My vote is also no.

**Comment by silicons** [comment]
ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh I think I perfer iron more.

**Pull request closed without merging**
