### PR TITLE
Adds telescopic baseball bat

### PR DESCRIPTION
**Pull request by brokenOculus**
Adds Telescopic baseball bat and its telescopic functionalities.

## About The Pull Request

Adds a new item to the traitor uplink, a telescopic bat! It can contract down to fit in pockets or backpacks with ease, and pop out and bash people within a moment's notice! It deals slightly more damage than a normal baseball bat when extended (15 force, only 5 force when contracted) and costs 2 tc.

bats 1

## Why It's Good For The Game

I think a concealable baseball bat would be an excellent addition to a traitor's arsenal, and work as a functional side-grade to the e-dagger.

## Changelog
:cl:
add: Added Telescopic Baseball Bat
add: Added Telescopic Baseball Bat to Stealthy uplink items
add: Added sprites for Telescopic Baseball Bat
add: Added Telescopic Baseball Bat to Baseball kit under uplink bundles

/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
on one hand someone should really teach you git

on the other hand this is really fuckin funny let's Go

**Comment by moltoretardo** [comment]
Smack those kneecaps

**Comment by necromanceranne** [comment]
add this to the baseball kit

**Comment by brokenOculus** [comment]
> add this to the baseball kit

I could do that, if it's alright with the maintainers!

**Pull request merged**
