### PR TITLE
Hydroponic Changes - More types of weeds, more chems to use!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Iron now helps plants grow big and stronger meaning higher potency
Carbon helps kill bugs - Sorry moffs! - Make the plant nice and healthy as well as grow more
New types of Rng weeds are - Cotton (Fun fact this one is invasive irl) Grass (Show me were grass dosnt grow but were NETTLES DO?) Wheat/Oat and Poppys - Fun fact these are also aggressive and will take over whole fields

## Why It's Good For The Game

Hydro has had to deal with the same few rng weeds for to long, also helps getto hydro if they were to want to make wheat or other types of flowes. Chem wise just makes it a bit more consistant as ash is also used as well as sulfer so no reason to not add this

## Changelog
:cl:
add: Iron and Carbon have been found to help plants!
add: More invasive and agressive plants have been seen growing out of dirt piles and even hydro trays!
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
botany doesn't need chem dumping to be even easier, and weeds are generally something you do not wish to have in your garden, cotton/grass/wheat are not considered to be weeds, regardless of how invasive you believe them to be

**Comment by Trilbyspaceclone** [comment]
cotton is a weed tho,
And grass iirc is more agressive irl then kuz in game
The wheat and many grands are infact invasive and agressive to the out of killing off ground based plants
as for chems - Its still better to use tools, and mutagen. Ash is easyer to get then carbon as well

**Comment by timothyteakettle** [comment]
the fertilizers just outright aren't needed, and regardless of how 'aggressive' a plants growth is, **that does not make it a weed** , this is a bad change and makes botany weeds make less sense. (for reference, a weed is defined as an unwanted plant, and thus none of the things you have added are weeds)

**Comment by Trilbyspaceclone** [comment]
how are mushes weeds?
In fact most of the plants already in the list are just overly aggressive and invasive rather then classified as a weed.

**Comment by timothyteakettle** [comment]
mushrooms are not technically weeds due to being classed as a fungus, but they're still an unwanted piece of life in your garden, and so it's easier to classify them as such. wheat is not the same, and isn't applicable, nor are any of the other plants you have put in the weed section

**Comment by Trilbyspaceclone** [comment]
So we should remove everything form weeds as they all have wanted and uses.

**Comment by timothyteakettle** [comment]
I think you're heavily missing the point of what is and isn't a weed. It's a very variable definition, but it's best to take it from the standpoint of a regular botanist, who does not wish to make anything poisonous or lethal, and just wishes to make food for the cook. None of the things you listed count as weeds.

**Comment by Trilbyspaceclone** [comment]
im rather hard pressed to fine any botnist that would not want plumps/redcaps, resi, tower caps and starthisal even for cooks, as all those plants - and even nettle - have cooking

**Comment by timothyteakettle** [comment]
having cooking for something does not make it good nor wanted by a regular botanist, nettle soup will literally kill you, reishi has a ridiculous amount of morphine in, again, these things you propose to add are not weeds whatsoever and there's no point or need to any of these changes aside from making botany make less sense

**Comment by Trilbyspaceclone** [comment]
morphin isnt even a toxin, and nettle soup is healthy.
All the other things - other then herbells - are actively used in cakes pies soups and other dishes.
I dont know many gardeners that actively DONT want wood that actively WANT poppy. 
These are changes are logical as any other changes.

**Comment by timothyteakettle** [comment]
okay so more bad things about this, as I really dislike this PR:
1. carbon shouldn't be increasing weeds when it doesn't increase pests, see how sugar has the drawback of increasing pests because we don't want rushing kudzu to just become 'get carbon'
(this pr just makes rushing kudzu even easier, because you can now increase weeds with no drawback)

2. aside from rushing kudzu with carbon, iron/carbon are just going to become more useless fertilizers on the list of things nobody puts on their plants because they're not needed

3. if you want to buff ghetto botany, this is not the way to do it, want ashwalkers to have more plants? give them more seeds, want better ghetto botany on station? add a public seed vendor to the few remaining maps that still don't have one

**Comment by Trilbyspaceclone** [comment]
@timothyteakettle sugar - that thing thats found in legit soda dispenders you can get endlessly also increases weeds. Its called a drawback. Its their to make you need to not dump 50000u in to get more potency. Iron, grind metal and thats basically it, its not in any dispenser its not magically in any plant that I know of. Its limited on being an hassle to use.
Iron cant be used to rush kuz. And unless you have some mutation chems as well most roles can not really kuz rush from maints/lavaland or space.
If you dont like you dont like it. 
The pr itself regardless of preference is fine balance wise.

**Comment by timothyteakettle** [comment]
you clearly haven't read what I said

1. you said iron can't be used to rush kudzu, but I was talking about carbon being used
2. I literally mentioned how sugar has the drawback of increasing pests, because increasing weeds can be abused when there's nothing else detrimental with it (as in you can quickly boost your weed levels to then attempt to get kudzu)
3. these changes are generally bad and add nothing good to botany that is actually required in any way or form, if your wishes are to buff ghetto botany, this is not how you should be doing it

**Comment by Trilbyspaceclone** [comment]
@timothyteakettle I think they are good changes.
You think they are bad.
Were stating in loops at this point, if it gets merged -yay or boo- depending on who you view it.

**Comment by silicons** [comment]
"botany doesn't need chem dumping to be even easier" sorry trilby this about sums up my thoughts, consistency isn't as important as balance.

**Comment by Owai-Seek** [comment]
I feel like while this PR wasnt strictly necessary, there wasn't even a real consideration for balance.

Saltpetre: 0.5 potency. Available in BIOGENERATOR, and Chemistry.
Iron: 0.01 potency. Chem Dispenser.
Carbon: ADDS weeds, Adds Nutrients, Heals plant. Chem dispenser.
Ash: KILLS Weeds, Adds Nutrients, Heals plant. Light papers on fire.
Sugar: ADDS WEEDS, AND PESTS. Literally just hop the bar counter or use a chem dispenser.

Literally just, use weed or pest killer to control what you want, and dump sugar into a basin. How are Trills changes -any different- than what you can do now other than adding slightly more variety?

I know grass would be nice as a weed, not sure about the others. Wheat/Oats is meh, Poppies have bicardine, and cotton, I'm kinda meh on as well.

**Pull request closed without merging**
