### PR TITLE
Fermi chem creates a plushie

### PR DESCRIPTION
**Pull request by Thalpy**
A quick test of the chemistry system to create new reactions. Added FermisPlushie, which is created by reaction (I hope!)

A single FermisPlushie is created from 10 sugar + 10 blood + 10 stable plasma at 400K. It's capped so 2 shouldn't form. (i+=10)

Citadel-Station-13\code\modules\reagents\chemistry\recipes\others.dm add: Added reaction that creates a single FermisPlushie from 10 sugar + 10 blood + 10 stable plasma at 400K.
Citadel-Station-13\code\game\objects\items\plushies.dm add: Added FermisPlushie object and arguments
Citadel-Station-13\icons\obj\plushies.dmi add: Added FermisPlushie sprites
Citadel-Station-13\modular_citadel\sound\voicemerowr.ogg soundaddL: Added a new Merowr sound (at lowered volume so it's quiet)

🆑Fermi
add: Added Fermi plush! Made from Sugar, Spice, and everything nice!
soundadd: Fermi noises upon hugs.

why: To do a simple change, adding a FermisPlushie hooked to a chemistry reaction, to ensure understanding and competence of editing, workflow,uploading and gitting of the citadel station codebase. #FermiChemLives !

/🆑

### CODE REVIEW

**Comment by Poojawa** [comment]
Silly Fermi, this isn't how you do CLs

🆑 <name>
add: <stuff>
tweak: <stuff>
/🆑

**Comment by Thalpy** [comment]
Should I change the change log?

**Comment by Thalpy** [comment]
And if I do, should I make a change log for the changes to the change log?

(I'm joking but I don't mean it in a sassy way, everyone who is reading this is a wonderful person.)

**Comment by Poojawa** [comment]
YOu're sucha dork <3

but yeah, if you want it to be a change-log addition, the format I set will have the bot work correctly!

**Comment by Thalpy** [comment]
Add: FermiPlushie
Add: Meowrowr.ogg
Tweak: others.dm
Tweak: plushie.dm
Tweak: plushie.dmi

**Comment by Thalpy** [comment]
I might be too tired to do this right now

**Comment by Poojawa** [comment]
🆑 Fermi
add: Added Fermi plush! Made from Sugar, Spice, and everything nice!
soundadd: Fermi noises upon hugs.
/🆑

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
