### PR TITLE
funniest shit i've ever seen

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
changes wabbajack, adds smite and admin-spawn-only gun to pickle-ify people
smiting someone who is a pickle un-transforms them
dying as a pickle returns your corpse (unless wabbajacked, like all wabbajack mobs)
'attacking' anyone just tickles them and makes them laugh

image

## Why It's Good For The Game
image
image
image

## Changelog
:cl:
add: recent culinary and scientific advancements have brought forth new pickle related technologies
/:cl:

### CODE REVIEW

**Comment by MalricB** [comment]
speedmerge

**Comment by Ludox235** [comment]
speedmerge

**Comment by Hatterhat** [comment]
based

**Comment by moltoretardo** [comment]
Now put it in a jar

**Comment by ghost** [comment]
seek help

**Review by Ragolution — APPROVED** [review]
I SHIT YOU NOT

**Comment by nik707** [comment]
the FUNNIEST thing I have ever seen

**Review by nik707 — APPROVED** [review]
pickles

**Comment by DeusSepulchre** [comment]
You're a bad person.

**Comment by Hatterhat** [comment]
it's based dude the fuck do you mean

**Comment by Dahlular** [comment]
i think i'm gonna shit

**Pull request merged**
