### PR TITLE
Resprites all regular crates to 3/4ths ones

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
imageadd: All regular crates are now 3/4ths ToriCrates
iamgeadd: Unused plastic crate sprite added
add: Blood freezer crates now have unique sprites.
/:cl:

toricraterc3preview

This PR will replace all regular crates (i.e. not large, exotic, or otherwise uncommon) with sprites made by yours truly.

toricraterc4

They are in 3/4ths perspective and are of much higher quality than the existing ones.

The assets included in this PR are licensed under CC-BY-SA. If you would like to use them for other projects, please attribute to one of the following: Toriate, Tori, Michiyamenotehifunana.

### CODE REVIEW

**Review by deathride58 — APPROVED** [review]
Holy fuck you actually made a PR

**Comment by Poojawa** [comment]
O2 crate still has a crazy color shift

**Comment by Michiyamenotehifunana** [comment]
O2 crate has crazy shiny retro-reflective coating because it's an emergency thing.

**Comment by CameronWoof** [comment]
No, Pooj means that the O2 crate's color changes between the closed and open sprites

**Pull request merged**
