### PR TITLE
podpeople now have green blood

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Podpeople now have green blood.

## Why It's Good For The Game

More distinction between races.

## Changelog
:cl:
add: plant people bleed sap
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
i heavily suggest just editing their blood colour and not adding more stuff into the spaghetti code of blood subtypes (look at how slimes edit their blood colour, it's just a single line)

like i specifically detached blood subtypes from being hardcoded into being the only way to edit blood colour

anyone can have any blood colour by just changing one variable

**Comment by ghost** [comment]
> i heavily suggest just editing their blood colour and not adding more stuff into the spaghetti code of blood subtypes (look at how slimes edit their blood colour, it's just a single line)
> 
> like i specifically detached blood subtypes from being hardcoded into being the only way to edit blood colour
> 
> anyone can have any blood colour by just changing one variable

I guess I might do that if I can't get this to compile, but I don't want to have to make a new PR because I found out that there's a simpler way to give podpeople green blood.

**Comment by ghost** [comment]
Yet again, something really tiny was the whole reason why the code didn't work.

**Comment by timothyteakettle** [comment]
this PR will not colour blood green, i'm just going to open a PR and do it myself

**Comment by ghost** [comment]
ok fine

**Pull request closed without merging**
