### PR TITLE
Add passive vents

### PR DESCRIPTION
**Pull request by r4d6**
This port https://github.com/tgstation/tgstation/pull/46180 
Here is what the original code had to say about it :

## About The Pull Request
Adds a passive vent, think of it as an open pipe to the turf atmosphere.
The icon is just a vent pump/unary vent without the fan.

## Why It's Good For The Game
Right now there is no way to input or output gas to turf without use of power, so you can't for example make SM setups that require no to very little power.

## Changelog
:cl:
add: added passive vent to the arsenal of atmospheric devices.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
yes

**Comment by Putnam3145** [comment]
relief valves (#10501) set to 0 open 0 close essentially act as passive open-to-air vents that require no power

**Comment by r4d6** [comment]
This one is more permanent

**Comment by Arturlang** [comment]
Oh god lets hope tgui next doesnt need modifications for this, also dont forget about the pipe dispenser

**Comment by r4d6** [comment]
@Arturlang The only thing that concern TGUI in that PR is an addition to the list of devices.

**Comment by Arturlang** [comment]
Seems itll he fine for tgui next, though i was talking about the stationary pipe dispenser

**Comment by r4d6** [comment]
I don't know, probably will the same or something, or just not available

**Comment by Ghommie** [comment]
There are a few differences with passive vents and relief valves, no big problem.
Resolve conflicts and it's in.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
