### PR TITLE
[DNM]Properly Incorporates waddling into the clown shoes, clown car, and penguins.

### PR DESCRIPTION
**Pull request by GrayRachnid**
## About The Pull Request
WADDLE WADDLE

## Why It's Good For The Game
WADDLING

## Changelog
:cl:
add: WADDLE
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
waddling is a shit meme and while i hate buzzwords may i say lrp
@GrayRachnid regardless i'll merge it if it's not on clown shoes, because penguins are penguins and i'm not going to discriminate against them, and clown cars are an antag item, but i'm going to go literally insane if i see clowns waddling around while trolling security every round

**Comment by GrayRachnid** [comment]
Turns out this doesn't work anyways. Standby, i'll need to update the component.

**Comment by Ghommie** [comment]
Any trouble making sure the component works correctly?
Also come on, kev, don't be such a joykiller.

**Comment by Ghommie** [comment]
Rest in pieces, I'll make sure to properly incorporate waddling myself once day.

**Pull request closed without merging**
