### PR TITLE
ports plumbing

### PR DESCRIPTION
**Pull request by lolman360**
needs tgui4

https://github.com/tgstation/tgstation/pull/44833

also: automatic hydro trays. take like 20x more gaia to transcend, accept reagents via pipe, autoharvest

## Changelog
:cl: Time-Green (copypasta'd by lolman360)
add: plumbing
add: automatic hydro trays
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
lets fucking go

**Comment by Ludox235** [comment]
NOOOOOOooooo

**Comment by lolman360** [comment]
no plumbing area though fuck mapping

**Comment by lolman360** [comment]
im still mad nobody merged my perfectly fine and working pr that got multiple testmegres last time and now i have to redo everything because we use reagent datums now

**Comment by Hatterhat** [comment]
bruh @lolman360

**Comment by lolman360** [comment]
@Hatterhat waiting on tgui 4 dipshit

**Comment by lolman360** [comment]
tested on local, no major issues

**Pull request closed without merging**
