### PR TITLE
adds trolls as a roundstart race

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
- Adds the funny and epic h*mestuck trolls as a roundstart race.
- No gameplay advantages, only real snowflake bits are horns (we can branch this out to other races! woo) and colored blood.
- BUT!!! Colored blood cannot be finished until https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9047 is full merged and as such is just placeholders for now.
- Comes with an on_species_gain message to not speak in obnoxious quirks such as leetspeak or adding text emotes to the end of your say commands.
- I'm **_pretty sure_** I got kevs approval. :man_shrugging: 

HUGE THANKS TO @Thalpy AND @Putnam3145 FOR ASSISTING IN THIS.

## Why It's Good For The Game
Citadel is known for dumb snowflakey shit, why not add more fuel to the fire?

## Changelog
:cl: port by Sishen1542, original code & sprites by our friends over at 413: Dickle, Putnam, et al.
add: added trolls as a roundstart race
imageadd: added troll horns
config: added roundstart trolls as a roundstart race
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
no

**Comment by Putnam3145** [comment]
image

**Comment by nik707** [comment]
i'm still iffy on this and will leave it to @deathride58 and @kevinz000

**Comment by CozmoB** [comment]
If I talk with a quirk am I gonna get bwoinked

**Comment by MrJWhit** [comment]
> If I talk with a quirk am I gonna get bwoinked

Yes that's still against the server rules.

**Comment by Wilchenx** [comment]
vriskabot

**Comment by Weblure** [comment]
This is literally just a human with horns; why not just add horn options for all species? I see no reason for this to be its own species.

**Comment by Wilchenx** [comment]
nice necro

**Pull request closed without merging**
