### PR TITLE
on someone's request i am making meteors slice through station ruins like butter so they are no longer free meteor shields because i want to make meteor timer 10 minutes instead of 4

### PR DESCRIPTION
**Pull request by silicons**
opinions wanted

basically this means anything asteroid-y turf doesn't count as a hit

### CODE REVIEW

**Comment by lolman360** [comment]
on whose request, i need to know so i can send death threats over my spessman

**Comment by MrJWhit** [comment]
Sup.

**Comment by lolman360** [comment]
good suggestion

**Comment by CameronWoof** [comment]
A warning you can work with in exchange for needing to heed the warning. Could work well.

**Comment by timothyteakettle** [comment]
seems good

**Pull request merged**
