### PR TITLE
Refactors Martial Arts code, human_defense, and ports New Sleeping Carp

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

A lot of stuff in one PR. This ports many of the martial arts refactors over, and also ports my changes to sleeping carp on TG. I unfortunately had to kill Rising Bass' animation and I apologize to Seris, I didn't really want to futz about with trying to get the animation to work when I'm doing a lot of cleanup to get NuScarp in.

The relevant PRs for the new sleeping carp can be found here:
https://github.com/tgstation/tgstation/pull/49524
https://github.com/tgstation/tgstation/pull/49661

**This is the post nerf version. I'll reiterate the changes I made here via the magic of copypasta:**

**Conditionally Immune to Projectiles:** Since people were very keen for this to remain, I've added ranged immunity while you have Throw Mode up and only then. So you can't deflect ranged attacks and attack at the same time. More important for the approach.

**Now Heavily Resistant to Near All Damage and Disables:** Basically, the Sleeping Carp user is a tough fucking bastard of a martial artist. They have resistance to most every kind of damage except Oxygen, Clone and Fire/Heat. They are able to spacewalk temporarily as a result, given they take very little damage from pressure, cold and brute and burn. They're more akin to a carp than man. Or **anthromorphic humanoid** (It's cit).

**Higher Vulnerability to Things They Weren't Vulnerable too Before:** You can shoot them with guns and it will now work, **mostly**. Which means Joe Shmoe, Security Officer fresh off the boat, isn't reliant on specialized equipment to fight a sleeping carp user. He's probably still in deep shit if he's fighting them on his own, however. Temp Guns set to bake will work well here too because sleeping carp users are ultra vulnerable to heat. Someone setting them on fire or combusting next to them is going to be bad for their health.

**Immunity to Relevant Stuff, Stronger with Armor:** If your skin is as thick as scales, then things that could puncture that no longer work. They are immune to syringes, sutures, ninja stars, embedding spears. In addition, armor becomes way more important for Sleeping Carp users to encourage them to really focus in on the defense aspect of their martial art and tank damage.

**Carp Faction:** Carp petting.

**Only Three Moves:** All the moves are started with Harm intent and ended with one of the three other intents for whatever you aim to do. These are:
**Gnashing Teeth:** _One-Two punch with a potential for a critical hit. Basic damage move._
**Crashing Wave Kick:** _A kick that launches people off the screen. Good for keeping anyone off you and really fucking them up in space._
**Keelhaul:** _Dropkick that knocks down and disarms. While the person is on the floor, disarms and applies stamina damage. Pretty much your main opener._

**Increased Subtly:** The only way someone will know you have this is if they try and use anything that requires you not to be in a hardsuit. Sutures, syringes, etc. Otherwise the effects are immensely subtle until you start punching people.

**Thus ends the copy pasta**

The only thing I didn't port over was touching batons. See, I want to talk about making batons respect armor and stamina mods in a separate PR and I don't want to touch them at all until then. For now, new scarp might have issues against batons. But that's nothing new. They have a VERY powerful disarm and knockdown of their own that should very much overwhelm one punch with a stun baton with ease.

You might ask: wait hold up they can beat me in a 1v1 in melee? And the answer to that is: damn fucking straight, he paid 17TC for that shit.

## Why It's Good For The Game

Refactors good, old code bad, snowflake code bad

Some of the reasons for why I made the changes on tg are only partially true on Citadel. So Ill largely put it down to 'Holy shit Sleeping Carp was sorta crappy feast or famine bullshit'.

## Changelog
:cl:
add: Ports New Sleeping Carp
refactor: Ports the martial arts refactors, which includes things like moving martial into the martial subfolder and renaming it _martial, and cleans up human_defense rising bass/sleeping carp exclusive code.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can you bring this refactor over to /tg/station code so that I can add Monks again thanks

**Comment by necromanceranne** [comment]
Already on tg my dude, nemvar did most of this work.

**Comment by Iamgoofball** [comment]
oh lmao

**Review by silicons — APPROVED** [review]

**Comment by silicons** [comment]
i have my thoughts on this but this is better than the current stun combat memes

**Comment by necromanceranne** [comment]
@kevinz000 merged too soon kev but eeeeh it's fine

**Pull request merged**
