### PR TITLE
Lets slime damage structures

### PR DESCRIPTION
**Pull request by Arturlang**
Ports https://github.com/tgstation/tgstation/pull/46718, lets slimes damage structures, whether they be sentient or hungry.
:cl:
tweak: Slimes can now damage structures, don't leave them unfed!
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Made slimes unable to delam the engine, hopefully

**Comment by MrJWhit** [comment]
Oh I could delam the engine as a slime pretty easily with this.

**Comment by Arturlang** [comment]
@MrJWhit Do tell me how, all atmos machinery is blacklisted plus APCs, SMES and air alarms

**Comment by shellspeed1** [comment]
If they can damage walls, they can fuck the sm.

**Comment by Arturlang** [comment]
They cant. Too much armor. Meele cant damage walls anyways aside from special cases @shellspeed1

**Pull request merged**
