### PR TITLE
[Ready] Mirrors Clown Shield maybe fixing it

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Mirrors TG clown shield making it slip and then come back to persons.
[why]
It mite fix a bug and code improvements

### CODE REVIEW

**Comment by deathride58** [comment]
Relevant PR?

**Comment by Trilbyspaceclone** [comment]
@deathride58 Thats me just stealing clown shield code, to mirror it so we can have it work

**Review by deathride58 — CHANGES_REQUESTED** [review]
Needs link to the relevant PR that this PR is mirroring

**Comment by Trilbyspaceclone** [comment]
https://github.com/tgstation/tgstation/commit/1ebbab60ec4c7ddc064f08b81552be5d0e43e824
@deathride58 
This was the last PR that was done on TG with that file. Again im just mirroring the shield's code for a fix with slips/returning the shield

**Pull request closed without merging**
