### PR TITLE
ministation is back

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

Brings back ministation, the lowpop station from before Omega was even born.

## Why It's Good For The Game

designed for tinypop, cit currently tends to have a lot of tinypop, I felt like mapping.

## Changelog
:cl:
mapadd: ministation
/:cl:
Things I still need:

- [x] shuttle

- [ ] in game testing

- [x] files and shit

### CODE REVIEW

**Comment by lolman360** [comment]
isn't mini the wack 24x24 one

**Comment by Detective-Google** [comment]
> isn't mini the wack 24x24 one

no that's microscopic station

**Comment by Detective-Google** [comment]
every time I look at this pr I question why I made it

**Comment by Tupinambis** [comment]
Ministation is awesome and nobody will ever change my mind. It has such a classic and simple feel to it.

**Pull request closed without merging**
