### PR TITLE
Stops gear harness from getting deleted by 2 laser shots

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
Stops gear harness from getting deleted from 2 lasers because the clothing damage code is absolute shitcode and I don't even want to go into detail how bad it is and why adding leg and arm coverage works

## Why It's Good For The Game
Fixes clothing item and fix man good

## Changelog
:cl:
balance: stops gear harness from deleting by 2 laser shots
fix: fixes gear harness from deleting by getting sneezed on
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Please *do* go into detail on why adding arm / leg coverage resolves it.

**Comment by dzahlus** [comment]
> Please _do_ go into detail on why adding arm / leg coverage resolves it.

I checked bluebelles PR and decided hey why not add arm/leg coverage maybe it stops getting deleted. And it just works, I genuinely have no fucking idea why.

From local testing anything with arm/leg coverage refuses to go into the destroyed damage state. I have nooooooo idea why. IMO just remove clothing damage because it doesn't work.

**Comment by lolman360** [comment]
hot take: maybe fetish clothing should be inferior to regular jumpsuits

**Comment by dzahlus** [comment]
> hot take: maybe fetish clothing should be inferior to regular jumpsuits

bro this is a furry erp server hrnngh

here's my hottake, no clothing that is just a normal jumpsuit should be inferior to other normal jumpsuits because; this is a furry erp server and muh clothing variety

**Comment by DeltaFire15** [comment]
I'll probably be looking into what's causing the 'adding arms & legs fixes the issue' sometime, so just leaving this open for now.

**Comment by silicons** [comment]
i'm just waiting on @BlueWildrose's thing

**Comment by necromanceranne** [comment]
Fixing something by paving over it with broken functionality is by no means a good long term solution.

**Comment by DeltaFire15** [comment]
Closing this as #14480 does it in a better way.

**Pull request closed without merging**
