### PR TITLE
Did you know deltastation has syndicate cards? I didn't, and some fixes on boxstation

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Got some anti-powergay fixes on boxstation and deltastation

## Why It's Good For The Game

Apparently auto-spawn sunglasses are too good

## Changelog
:cl:
tweak: Reduced the amount of powerful items in boxstation
tweak: Removed one powerful item in deltastation
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
Rip cool playing cards 🙏

**Comment by necromanceranne** [comment]
'Powerful'

They're floor tiles my guy.

**Comment by MrJWhit** [comment]
They're also illegal tech available roundstart no questions asked.

**Comment by necromanceranne** [comment]
There was a few changes on tg to prevent getting illegal tech from these kinds of items. I'll find it for you if you want to prevent illegal tech being easily acquired, as I have even worse news. If cards are working, satchels probably are too and contraband crates can do it as well.

**Review by silicons — CHANGES_REQUESTED** [review]
make the syndicate cards not give illegal tech if you need to (via subtypes/retypes rather than the actual type of the traitor item, or giving it a new flag or whatever).

syndicate cards are otherwise harmless.

**Comment by MrJWhit** [comment]
I'm not going to lie, if you don't feel this is a big issue, and, this will let other people work on boxstation, I'm happy to just close it.

**Pull request closed without merging**
