### PR TITLE
[Ready] Janitor buff, they can now get a spray bottle of drying agent 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Makes and add a 100u bottle of drying agent 
Makes a new 3000 credit crate to be the home for the rare drying agent bottle

[why]
Qol and makes people more likely to use mop and bucket without being a slip hazed in main halls

### CODE REVIEW

**Comment by JogBoba** [comment]
As dumb as this sounds: it feels hugbox-y, you get wet floor signs for a reason and with the upcoming mop buff this just seems overkill.

**Comment by deathride58** [comment]
No. This is just blind powercreep, especially if combined with the upcoming mop buff. If you want to overcome one of the main downsides associated with mops, you should have to put in the effort of talking with chemistry first

**Comment by MimicFaux** [comment]
Nothing desalts me faster than following up a bad round with a dedicated janitor round. Dutifully keep the station clean, and pointing to the signs when people come ripping down the halls at full speed. That shit's zen. Unnecessary powercreep when it's so easy to just ask for some from chemistry and apply to your galoshes if you really want it. Also, water spills from a mop don't last long at all.

**Comment by nik707** [comment]
Seems like this isn't gonna happen. I'm against it and I don't even play main.

**Comment by Trilbyspaceclone** [comment]
Note: @deathride58 And @Trilbyspaceclone have desired to make it cargo crate, and worked out a middle ground as it is in at this time
@LeonDuvall @MimicFaux Have also said that cargo crate was a good idea so that Janitor can get it from cargo.

**Review by silicons — APPROVED** [review]

**Pull request merged**
