### PR TITLE
you can now shoot yourself with a gun by using disarm intent will this cause balance issues maybe do i care not really

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

why can you not shoot yourself with a gun what is the reason if it's medibeam well shoutout to whoever did that because syou already can by aiming at mouth.

## Changelog
:cl: silicons
add: you can now shoot yourself by disarm-intenting yourself with a gun.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Can't wait for nukies self healing instantly with their medi-beam.

**Comment by necromanceranne** [comment]
One hand medibeam, one hand eshield. Throw mode up with CQC.

Let's see those bastards stop me now.

**Comment by lolman360** [comment]
@necromanceranne team up with another nukie and you can cross streams if you do need to kill someone

**Comment by silicons** [comment]
@necromanceranne you can already do that by aiming to mouth i think

**Review by Linzolle — APPROVED** [review]

**Pull request merged**
