### PR TITLE
oh yeah woo yeah

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

**Adds the "Groovecruiser" emergency shuttle for purchase:**
GROOVETIMETONIGHT

It'll come up right below Disco Inferno, with a price tag of 7000 credits.

## Why It's Good For The Game

**Disco Inferno is a rather controversial shuttle**, and from what I've seen the chief issue its opponents have with it is the fact that its plasma floor tiles and statues can render the shuttle a flaming wreck in no time flat. Some take it upon themselves to remove these volatile features from Disco Inferno prior to departure, and argue they shouldn't be a part of the shuttle to begin with. However, proponents see this as cowardice and going against Disco Inferno's "spirit", for lack of a better term.

The Groovecruiser attempts to compromise between the two groups - first of all, by being a plasma-free **alternative** to Disco Inferno as opposed to an outright replacement. In exchange for the pimpin' plasma purple and literally being "on fire", the crew gets a larger dance floor, an easier time getting in, around, and out of the shuttle, more (although still probably not enough) seating, and all for a lower price tag.

UPDATE: Gives Disco Inferno some of the doors Groovecruiser added.

## Changelog
:cl:
add: Adds the "Groovecruiser" emergency shuttle.
add: Adds some doors to the standard Disco Inferno shuttle as well (not pictured).
code: Slides the Groovecruiser into code
/:cl:

### CODE REVIEW

**Review by nik707 — CHANGES_REQUESTED** [review]
Your lines are using what seems to be two spaces instead of tabs. Tabs are a standard thing and should be ubiquitous in all code. Aside from that, it seems just fine and honestly I'd replace disco with this outright. Disco inferno is just straight up grief bait

**Comment by EmeraldSundisk** [comment]
Not sure what the deal with that was but I believe I've fixed it!

**Review by nik707 — DISMISSED** [review]

**Comment by nik707** [comment]
can be merged at the 24h mark

**Comment by EmeraldSundisk** [comment]
https://www.youtube.com/watch?v=emP-7fLlDC4

**Comment by YakumoChen** [comment]
But that ruins the entire point of disco inferno? Nobody's going to buy the plasma shuttle now if there's an obviously safe alternative. 

Not that it matters right now since disco balls are broke.

also 
>chairs on a dance floor

**Comment by EmeraldSundisk** [comment]
Hey, they're on the outside of it rather than dead center in the middle. And we'll have to see what its introduction does - there was talk of making the original Disco Inferno emag-only.

**Comment by silicons** [comment]
I do not like this.

**Comment by EmeraldSundisk** [comment]
Would anyone complain if I added more doors to the original Disco Inferno?

**Comment by EmeraldSundisk** [comment]
Updated Disco Inferno to have two more doors (the one connecting the two main rooms inside the shuttle and the security entrance).

**Comment by silicons** [comment]
sorry i see this as ruining the spirit of disco inferno (and yes we will fix the jukebox at some point).

**Pull request closed without merging**
