### PR TITLE
[WIP/DRAFT] tg service hardsync 1/2: drinks

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
title
i'm making sure that anything citadel specific is kept such as cogchamp, racial drinks, buzz fuzz, the special teas, etc

part 2 is food and kitchen machinery
might split those into two more depending on the amount of work

## Why It's Good For The Game
boy we are years out of date

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
wip: still being worked on
experiment: experimental
tgs: has something to do with tgs
expansion: expands on something
qol: quality of life content
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Rip Bottler

**Comment by timothyteakettle** [comment]
yes it's july, yes it's still being worked on, please do not mark this as stale, i'm working through some issues with the right click stuff

**Comment by catrock31** [comment]
Please

**Comment by DeltaFire15** [comment]
Draft unchanged for over a year.

**Pull request closed without merging**
