### PR TITLE
Readds drones

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by Ragolution** [comment]
but is it balanced

**Comment by silicons** [comment]
@Ragolution they never go rogue outside of wizard/admins and we can easily deal with those who break laws or try to ruin things for others.

**Comment by Ragolution** [comment]
Cool. I missed drones.

**Comment by deathride58** [comment]
y tho

**Comment by silicons** [comment]
@deathride58 fun 🐱 
no really I don't think it's enough of an admin issue with bad players to warrent keeping it out considering it gave dead people a fun thing to do assuming they aren't shits wit hthe role.

**Comment by Trilbyspaceclone** [comment]
Add in emagable drones again

**Review by nik707 — APPROVED** [review]
approved but @deathride58 asked why and I want him to be the one to hit the button

**Review by deathride58 — APPROVED** [review]
EHHHHHHHHHHHHHHHHHH

**Pull request merged**
