### PR TITLE
Adds in Oxygen to grass

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]: # Adds in 0.03 Oxygen gene to grass!

[why]: # Mostly for Life-Bringers to be able to make there own Oxygen.

Side note: First time touching code if I did a bad make sure to yell at me for it with harsh words of disappointment!

### CODE REVIEW

**Comment by yourdoom9898** [comment]
~~This would allow botany to make ez saltpeter, so keep that in mind~~

EDIT: I am a idiot, ignore me

**Comment by Trilbyspaceclone** [comment]
How they still need N2 witch is only in gat fruit?

**Review by deathride58 — CHANGES_REQUESTED** [review]
Modularize or add a `//CITADEL CHANGE - adds 0.03 oxygen to grass`

**Comment by MimicFaux** [comment]
Oxygen for Lifebringers?
>Not just growing Space Tobacco for Salbutomol

**Review by deathride58 — APPROVED** [review]

**Pull request merged**
