### PR TITLE
nerf to biogenerator upgrades, removal of flour and glass bottles designs.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. Unupgraded biogenerators will still be as efficient as before, save for the reduced maximum storage.
Converted the old plant nutriments, planticide and pesticide bottles designs to dispense reagents instead. Removed the flour design.
Added a carton box design in place of the glass bottle's.

## Why It's Good For The Game
First, machines becoming outright 100% more efficient with each successive stock parts level goes well beyond the necessary to make their use less of a chore
Second, empty glass bottles designs are nonsensical in so many levels it's not worth arguing about.
Third, you can already get flour by farming wheat in the same dept., this is suplerfluous.

## Changelog
:cl:
del: Removed glass bottles from the biogenerator designs, nutriment and pesti/planti-cide designs were adapted to dispense reagents directly. Also removed the flour deisgn.
add: Added a carton box design instead.
balance: nerfed upgraded biogenerators efficiency/production, and maximum storage amount all around.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Why remove milk?

**Comment by Ghommie** [comment]
To clarify: Milk, pepper and cream already have reagent dispensing counterparts coded in with the same cost/results ratio, so I'm just removing these old ones.

**Comment by Owai-Seek** [comment]
Makes both botany and chef even more of a chore for no particular reason. I agree that the biogen and microwave getting just flat out better when upgrading was silly, but these other changes seriously hamper both departments and the public botany rooms.

There's basically zero effect on powergaming botanists because they're going to steal a chem dispenser and/or rush ambrosia immediately.

These changes only hamper players who are still learning the roles, or doing things as assistants.

**Comment by shellspeed1** [comment]
Could you add flour as a reagent to the biogen instead of outright removing it? Most recipes require it for the chef and it's somewhat nice to be able to get it from excess food even if it's without it's own container.

**Comment by timothyteakettle** [comment]
im against flour being available in the biogen because it just pushes to make getting stuff for the cook even faster and easier, you start with a tonne of flour, just grow wheat, it's not hard

**Comment by ItsTisme** [comment]
I don't see a legitimate reason to remove nutriments and such from the biogen, a good botanists will have gaia trays by then but a bad one might run out of nutriment/pesticide. This only hurts the learning botanist

**Comment by Ghommie** [comment]
The only removal here is flour and glass bottle, man. It doesn't hinder new players experience that much.

**Comment by timothyteakettle** [comment]
also getting flour is a joke seeming as some dinnerwares seem to contain it when hacked (like four bags), it's also quite difficult to run out of flour seeming as food lasts ages edit: this may no longer be the case as despite getting them before, I don't think you can get them now, instead you're able to get monkey cubes?

**Comment by CameronWoof** [comment]
Flour in the biogen was never _for_ the Botanists, it's for the chefs. It guarantees even the least cooperative dinks have no excuse not to at least get you flour.

**Comment by CameronWoof** [comment]
Flour in the biogen isn't _for_ the Botanists, it's for the chefs. It guarantees even the least cooperative dorks have no excuse not to at least get you flour.

**Pull request merged**
