### PR TITLE
ports colormates from rp/vorestation

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

gear painters
has a minimum lightness of 50
contains the ability to use matrix coloration mode. when in matrix coloration mode, there's a check to ensure 2 out of the 4 test colors have a minimum lightness of 75 to avoid matrices being used to bypass the color check.

## Why It's Good For The Game

better alternative to spraypaint

## Changelog
:cl:
add: colormates
/:cl:

### CODE REVIEW

**Comment by BlackMajor** [comment]
Pog

**Comment by SandPoot** [comment]
Pog indeed, is this coloring protected from washing?

**Comment by MrJWhit** [comment]
The mapping stuff is going to conflict with:
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13746
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13750

Wait until that's merged/whatever, and then I'll go through the maps and add in this as well:
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13747

That way things don't need to wait too long.

**Comment by silicons** [comment]
@SandPoot i believe so(?)

**Review by Linzolle — APPROVED** [review]

**Pull request merged**
