### PR TITLE
Bloodsucker the retweakening

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Everyone knows that bloodsuckers have been a bit overpowered lately, it's largely due to them just being able to hide and chum on monkeymen or blood bags for the whole round while in hiding, until they are high enough level to devastate all of security, this PR hopefully tries to resolve that, by making level 3 bloodsuckers unable to gain blood from bloodbags/monkeymen, hopefully forcing them to seek interaction with the crew, one way or another

## Why It's Good For The Game
To improve bloodsuckers as a antag, making them not use cheese tactics always, which is no fun for anyone.

## Changelog
:cl:
del: Bloodsuckers no longer passively regenerate stamina at bullshit speeds
add: Instead, now bloodsuckers can get more stamina damage before suffering their effects
add: Bloodsuckers now get a ability that at cost of burn damage, blood let's them resist knockdowns, stamcrit, but with a decent cooldown, it also let's them wake up from Torpor at a pretty big cost.
tweak: Bloodsuckers above level 3 now have to drink nonmonkey blood, as it won't sate them that much anymore, and certainly not enough to level up, nor will blood from blood bags work either.
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
You need to better explain what the actual intent of your changes are, this tells me nothing.

I get the monkey part, as bloodsuckers acting more as minor nuisances or friendtags is a legitimate issue, but was there an issue with stamina before? How do these changes change how you play it? What's the new ability for?

**Comment by Arturlang** [comment]
Gimme a sec, this is a draft still

**Comment by Arturlang** [comment]
Ugh, going to fix the changelog fuckery later

**Comment by moltoretardo** [comment]
Bloodsucker stays one of the worst fetish antag that ever happened on cit. I despise them more than ling and I think ling shouldn’t be an antag. The rack and the overpowered abilities the bloodsucker have makes it unfun for everyone (except for the one having the raging powerboner running around with the OC protagonist super powers) Be kind to cit and don’t bring that drama fest back

**Comment by moltoretardo** [comment]
Also running to get interaction with the crew is just a good way to say erp for blood. It’s bad.

**Comment by kiwedespars** [comment]
nerf immortal haste by removing the disarm, because having a knockdown disarm ability that also places you directly next to someone and can kick them away from their weapon makes fighting vampires the most unstoppable antag we have right now.

**Comment by Arturlang** [comment]
@kiwedespars Good feedback, thank you, will consider
@moltoretardo Please actually contribute actually usefull feedback instead of just saying it's bad, the point of this is to make bloodsuckers NOT overpowered, and I want to remove the torture rack myself as well

**Comment by moltoretardo** [comment]
@Arturlang You mentionned removing the rack like what, 6 months ago? It is honestly disappointing that it never was done. You're not even doing it during the ""rework"", if you can even call it that, so I honestly very doubt it at this point. 

As of why bloodsuckers suck:
-It is literally just buffed lings, there's no going non-lethal against them since they can always escape unless you sleep them forever.
-They get some nasty ass over powered abilities which you nerfed by making them use human blood for level 3+ while it obviously won't be a problem for the people that seek to get "captured" by bloodsuckers. Hell, you can literally call it roleplay and let yourself be enthralled by saying you were just diplomaticaly talking with the bloodsucker. The fact that they can silence and UwU pounce on you will surely make it very hard to harvest blood from people.
-They bring absolutely nothing fun to the round. As I said before, there'll be 1 person with the big giga powerboner going around busting asses while people tries to fight something that can stun,silence,teleport,obliterate you with bare fists and kill you by sucking you dry of blood. From a gameplay perspective it's bad. Abilities deserve a bigger nerf.
-From the non-gameplay perspective, bloodsuckers bring so much drama just from the indecision the admins have to call them valids or not.
-I get that you like vampire stuff and I don't mind that, but I'm adamant that the gamemode itself isn't making any round better. An antagonist that can convert people while having over the norms powers is just a washed down fetish bloodcult. I'd rather just have heretics.

A nice rework would've been changing the abilities not to be braindamage inducing, completely removing their ability to raise an army while already being a one man army themselves and giving them more counters. Having to smack something that can obliterate you with a glare using only a silver stick isn't what i'd call a fair fight. There's also the big laser shotgun but anyone that isn't an officer will have a hard time finding one. They have literally everything: mobility, strength and alot of substain. Your rework is only targetting a sliver of the problem and it honestly feels like it's just a lazy "get muh gamemode back" type of work.

**Comment by Arturlang** [comment]
And that is why this pr is a draft, so i can get feedback on what ive done so far, do realize that coding in new things takes effort, even tweaking things, if you dont want them to break immediately, i have planned on getting rid of it yes but if i dont want to just do something lazy ill have to put effort into it which takes time and dedication. If i just wanted bloodsuckers back for a short while, this wouldnt be a draft.
bloodsuckers already have some very solis counters that is not just le shotgun laser, and ive already put a limit on how maby they can thrall

**Comment by moltoretardo** [comment]
Having one bodyguard for an already too strong someone is too much. You're saying that it takes efforts and all but you could've just removed the rack while working on an alternative. Even a reskinned cult circle would be less cringy than that. As for the counters, what do we have here. Silver stick, wooden stick, lasers. It's pretty hard to nail lasers on someone that has a lot of mobility and once you're stunned you're just as good as dead. Honestly a gamemode that would bring diversity instead of that kind of _gameplay_ would be better. Lings and Heretics are just bloodsucker but better.

**Comment by Arturlang** [comment]
Garlic also exists, which hurts them badly and nulls their abilites, and the garlic necklace blocks bites long enough for you to call help,  and I dont like removing stuff unless it's really that bad

**Comment by moltoretardo** [comment]
Garlic requires you to grow them and can be sabotaged super easily. The garlic necklace blocks bites long enough for you to scream, it'd be a real shame if the bloodsucker could mute and stun you right haha, real shame.

>  I dont like removing stuff unless it's really that bad

You don't seem to like changing stuff that are extra bad either since it's not even mentionned in the draft that the rack is getting changed. I honestly don't think it's valuable to argue with you anymore and it's pretty obvious that you don't intent to do a real rework, only a silly little tweaking of some variables which doesn't solve the major part of why this round type is awful.

Thank you for atleast trying but I really hope deep down that this fetish antag remain disabled forever.

**Comment by YakumoChen** [comment]
I loathe the disruptive picture @moltoretardo paints of vampires (fuck off with the fetish antag shit, it's not relevant) but I'm not really warm on the idea of bloodsuckers returning.

Less so because they're unfun to fight and more because playing them feels unfun as a general premise. Upkeep mechanics in a roleplaying game in general aren't super fun to play with. Knowing I have a slowly ticking timer until I get The Shakes, blood in general being a pain in the ass th acquire without murderboning people or playing the Antag Personal Space Shuffle, having to drop everything I'm doing to take a nap every 20 minutes, the entire metagame with coffins being nauseating in general. It's not a fun antag to get into and it discourages roleplay at every step. The conversion is it's own set of pratfalls that I dont care to step into either, but given the general extreme distaste for their function and how we have to make so many rulings around it, I can't encourage its presence.

Bloodsuckers fundamentally limits what you can do as an antag. A stark contrast to other modes in which freedom of playstyle is encouraged through many choices.

**Comment by moltoretardo** [comment]
All of the points I brought are revelant enough. The “it’s bad for rp” argument is pretty risible though. The rp potential of antagonist is always locked to “if the players rp with it”. Some bloodsuckers would go on rampages while others would interact and try to maximise fun by not being unga power. Some traitors can do some funny gimmick involving other players with everyone getting a laugh and a share of rp while different traitors will just play antag miner with all the op gear they find or raid the armory and steal all the guns on low pop no sec round.

If there’s one thing I can’t trash bloodsuckers about it’s the rp potential. While for me it was the most disturbing and fetishy interactions, it was still “rp” as people would call it. Of course you can call me the R word for finding some torture rack and mutilations disturbing and fetishy but it’s almost the same thing as someone who would despise drugs and alcohol usage. It’s not for no reason people coded prefs in, hence why I think it’s a solid argument and not just a disruptive picture i’m painting. 

But yeah they do be real unfun to fight.

**Comment by Arturlang** [comment]
I'm gonna work on this more using the feedback ive gotten, It's really useful I only wish people werent so hostile giving it, thank you

**Pull request closed without merging**
