### PR TITLE
burn infection changes

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
limbs at total infection wont stop you from healing the infection now
if you have preservation chems or are cold (and not resistant to cold) your infections will also stop getting worse

## Why It's Good For The Game
less lethal, actually treatable, less reliance on cloning

## Changelog
:cl:
tweak: limbs at total infection wont stop you from healing the infection
tweak: if you have preservation chems or are cold (and not resistant to cold) your infections will also stop getting worse
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
gonna test this further because there's a case where it might not do what i expect

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Seems mostly good, though I'd suggest a early return before the switch handling infestation (l. 77) if the limb already is decayed, since it already gets constant tox damage caused at the very start of the proc, and some of the messages make no sense after the limb already hit full-on sepsis.

**Comment by shellspeed1** [comment]
I mean, when a limb is dead like that it's supposed to be replaced, either with a mechanical limb or a fleshy one. Might be worth adding a fleshy torso replacement instead.

**Comment by DeltaFire15** [comment]
@timothyteakettle bumping.

**Comment by DeltaFire15** [comment]
Marking this as stale due to requested changes having been present for a considerable period of time with no author response.

**Comment by DeltaFire15** [comment]
Closing this PR due to staleness. Feel free to reopen this once work on it is resumed.

**Pull request closed without merging**
