### PR TITLE
Porting Goofconomy & co.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Exactly what's said on the tin, still a WIP but the main bulk has been done, including direct cargo packs ordering, removal of non-cargo budget cards, custom vendors and CRAB17.

Also coded in some lazy z level stuff to make all id cards spawned in a vitual reality level unable to have a registered account, while still allowing vr characters to have preset, remote bank accounts they can't switch out of. Pretty sure not totally foolproof, so more tweaks to come for vr maybe.

There will be several balance issues, so expect public lathes and items availability tweaks in the future.

## Why It's Good For The Game
Adding economy to the game. I'm tired.

## Changelog
:cl: A very goof'd Contributor.
add: Ported Goofconomy. Credits to several contributors that shaped the feature over time on /tg/station.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
What needs to happen is that this is actually focused on departments instead of personal per-crew basis economy.

**Comment by silicons** [comment]
y'know what fuck it just whatever, let's just fucking roll with it, can always remove shit later.
please no vendorconomy though.

**Comment by Ghommie** [comment]
Time for live testing.

**Comment by silicons** [comment]
i guess we will collectively suffer

**Pull request merged**
