### PR TITLE
Total fire overhaul + new atmos stuff + uh oh stinky toxins nerf + sauna buff + ??

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Made plasma fires and trit fires part of generic fires, so that they can work with any new oxidizers added.

Generic fires now have the ability to release radiation with arbitrary reagents.

Generic fires have been reworked to use a more proper enthalpy bookkeeping system, i.e. how much they heat up or cool down is based on how much energy it takes their reagents to separate and combine.

Trit fires were nerfed heavily because now they operate on math that actually works. Plasma fires also act pretty differently.

Fusion has been nerfed (port of [https://github.com/BeeStation/BeeStation-Hornet/pull/2614](https://github.com/BeeStation/BeeStation-Hornet/pull/2614) by @jupyterkat)

Water vapor no longer deposits if the temperature in the room is above 40 celsius, for sauna purposes.

Methyl bromide now properly burns into carbon dioxide, water and bromine gas, at the right ratios.

Bromine gas was added as the first "chemical gas", an entire group of gases with similar behavior (TODO)

"Gas groups" were added: scrubbers and filters group some gases in buckets. Bromine is "Chemicals". Portable scrubbers get to keep all the gases.

Draught air alarm mode now only pressurizes up to 1.4x pressure instead of 2x--2x was too much, massive overpressure.

All of the alarm types interact with siphoning vents properly. Panic siphon maximizes siphoning vents, draught sets siphoning vents to lower levels etc.

## Why It's Good For The Game

Trit fires are stupid, mostly. Seriously, that's the main reason. Trit fires are broken and whoever wrote them can't do math. Our balance being built around maxcaps being literally trivial to make is baffling. Trit fires making the *baseline* bomb 10x as big as required to destroy an entire Z level is really, really dumb.

## Changelog
:cl:
add: Hydrogen gas (no way to get yet)
add: Gas groups, such as...
add: Chemical gases, starting with ethanol, bromine, diethylamine, ammonia, phlogiston
add: Bromine gas (can make it by tossing hot bromine on the ground OR by burning methyl bromide)
add: Ammonia gas (toss hot ammonia on the ground OR burn diethylamine)
del: Snowflake trit/plasma fires fires
tweak: Generic fires are now more accurate energy-wise
tweak: Water vapor condensation no longer happens below 40 C
tweak: Methyl bromide now burns properly
balance: Massive fusion nerf
balance: Due to the removal of snowflake trit fires, trit fires are much, much less hot
balance: Due to the previous, bombs are now easier to reach 50,000 points on (2 : 1 plasma : oxy at 160 kelvins cold side should be fine)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Trit fires being a white hot inferno is a bit iconic given how long it has been around, so preferably if something took its place that can be made relatively easily then that'd be nice

**Comment by Ghilker** [comment]
Dude just port the HFR already lol

**Comment by Putnam3145** [comment]
> 
> 
> Dude just port the HFR already lol

honestly at this point i want to keep open air fusion for the funny

**Comment by deathride58** [comment]
https://www.youtube.com/watch?v=hZb_6_WfquU

**Comment by jupyterkat** [comment]
how about both :flushed:

**Comment by silicons** [comment]
we love putnam

**Comment by Putnam3145** [comment]
the test is going to fail because it grabs auxmos for linux from a release but this isn't associated with one yet

**Comment by Poojawa** [comment]
reminder that plasma is gay hydrogen.

**Comment by bunny232** [comment]
Turning the operating mode away from filtering mode then back to filtering disables chemicals scrubbing. (line 538 in the air alarm file code/modules/atmospherics/machinery/airalarm.dm)
Draught vent pressure should be maybe be changed to one atmo*1.1ish to prevent over pressure alarms. (line 587 in the air alarm file)

**Comment by Arturlang** [comment]
Good PR, especially the port, but given how much the port changes that could have been atomized or atleast noted better.

**Comment by Linzolle** [comment]
this has been testmerged long enough

**Pull request merged**
