### PR TITLE
Adds new Fermichem-based chemicals!

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

Adds some really dangerous chemicals and their precursors to the game. The precursors aren't typically very strong, but the final reagent is. They use the Fermichem system, and so that code is also in this PR; Fermichem proper is only testmerged at the moment.

Current chems are:
-Methanol. Flammable, with a small explosion. Precursor for Methyl Iodide.
-Methyl Iodide. Highly toxic chemical, precursor for Dimethylmercury
-Dimethylmercury. Deathchem, extreme toxin damage and violent explosions even at 5 degrees C above room temp.
Planned:
-Uranium tetraflouride. Toxic, quite acidic chemical, gives off mild rads. Needs mining Uranium.
-Globulodine. Slowly turns the victim into a 50-hp fleshy monstrosity that can ventcrawl, but can't talk or understand Galactic Common, with high damage on hit. It's resistant against both lasers and physical brute, but weak against other incendiaries such as being on fire and incin/dragonbreath SG shells .Preventable with slime jelly, does NOT turn person into an antagonist like gluttony.
-Lithium Grease: When applied to shoes, causes the wearer to lubeslip after 25-100 tiles. Effect persists until clothing is removed.
-Tectrothium: Teaches the victim a spell that allows them to punch the ground, removing that floor tile (if it is covered) or dealing damage to it (if it is plating), while also sending out a shockwave. Spell is unlearnt when reagents are metabolized out.
-Aleothium: Makes the victim fly uncontrollably, allowing them to pass over hazards and tables but sometimes slamming them into the ground/ceiling. Control is dependent on purity of the chemical.
Alchemical Dust: Grants up to 20 seconds of immortality, then gibs the victim.  Needs a _lot_ of reagent to work - more than 90u (6 syringes)

## Why It's Good For The Game
New chems = cool. Eventually we will have a chem list to surpass even Goonstation.

## Changelog
:cl:
add: Added a lot of new chemicals. Have fun blowing up when making them.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
You know... it would have been just better if you PR'd it to the original author's branch at this point, but that'd bloat their PR furthermore.
This is one huge mess to dive through, and I can't even find any of the mentioned chemicals by using the search tab.
This is painful.

**Comment by silicons** [comment]
i'll be honest chief i'm not so hot on adding even more chemical warfare, even with fermichem.

**Comment by lolman360** [comment]
> 
> 
> You know... it would have been just better if you PR'd it to the original author's branch at this point, but that'd bloat their PR furthermore.
> This is one huge mess to dive through, and I can't even find any of the mentioned chemicals by using the search tab.
> This is painful.

I purposely did it this way to avoid fucking up Fermi's stuff as well as be able to test it on my end off my fork. The reason the chems aren't there is because the upload failed. Twice.

**Comment by Thalpy** [comment]
Heck, um. Maybe it's a good idea to keep this as a discussion, rather than a code review, since we're kind of stuck between two codebases.

**Comment by kiwedespars** [comment]
I like the chem ideas in general, but I feel like Dimethylmercury would just make chemical warfare a bit more of a pain. We already have enough chemicals made for killing people, in a numerous amount of ways. The rest are /amazing/ though.

**Comment by lolman360** [comment]
I'm fine with parting with it, as the reason I created it originally was to see if I could a) not royally screw up everything while messing with code and 2) use it as a test chemical to see if I can properly do Fermichem based reactions.

**Comment by silicons** [comment]
fermichem isn't even merged yet and this pr is stale anyways.

**Pull request closed without merging**
