### PR TITLE
High-Tier Map Memes

### PR DESCRIPTION
**Pull request by Cw3040**
Making the map not the same as /tg/'s while retaining functionality of /tg/'s shit like VR.

### CODE REVIEW

**Comment by Cw3040** [comment]
maintbar
F on the wall stands for "False"

**Review by deathride58 — CHANGES_REQUESTED** [review]
Remove the drone dispenser you added to meta. Drones are an absolute pain in the ass to deal with from an administrative standpoint 90% of the time; they're admin-spawn only now for good reason.

Also, try remaking your changes to Pubby. Travis is being weird about it, might be due to the finite symbol bug.

**Comment by Cw3040** [comment]
"Finite symbol bug" explain pls

**Comment by Cw3040** [comment]
I'm legit thinking that Travis just fails on the last commit of a series

**Comment by Cw3040** [comment]
Travis has failed only when BUILD_TESTING=true and it seemingly fails on a random map tile.

**Comment by Cw3040** [comment]
alright i guess it's just fucked now
time to un-fuck it

**Pull request closed without merging**
