### PR TITLE
adds tumor baguettes

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

Baguettes are bread too, therefore teleporting them causes them to turn into angry bread snakes.

## Why It's Good For The Game

it isn't

## Changelog
:cl:
add: baguettes are bread too, try teleporting one
/:cl:

### CODE REVIEW

**Comment by DrPainis** [comment]
wait fuck this should've been a draft, I didn't add all the files yet

**Comment by SmArtKar** [comment]
it doesnt even compile

**Comment by timothyteakettle** [comment]
use subtypes properly to stop having to copy/paste all the vars you wish to set

**Comment by TheEaterOfBeans** [comment]
uuuuhhhh hold on let me figure out how to add baguettes to the bread teleport proc

**Comment by TheEaterOfBeans** [comment]
aaaaAAAAAAAAAAAA HOW DO I ADD BAGUETTES TO THE BREAD TELEPORT PROC?

**Comment by Linzolle** [comment]
Have a look at code/datums/helper_datums/teleport.dm.

**Comment by TheEaterOfBeans** [comment]
> Have a look at code/datums/helper_datums/teleport.dm.

The problem is that there's only an "if" and an "else if" and if I try to copy the else if for baguettes, it doesn't compile.

**Comment by Linzolle** [comment]
> 
> 
> > Have a look at code/datums/helper_datums/teleport.dm.
> 
> The problem is that there's only an "if" and an "else if" and if I try to copy the else if for baguettes, it doesn't compile.

Just add baguettes to the bread_cache list. Don't need to overcomplicate it.

**Comment by TheEaterOfBeans** [comment]
OH GOD OH FUCK I FORGOT THIS PR EXISTED AAAAAAAAA

**Comment by TheEaterOfBeans** [comment]
> > > Have a look at code/datums/helper_datums/teleport.dm.
> > 
> > 
> > The problem is that there's only an "if" and an "else if" and if I try to copy the else if for baguettes, it doesn't compile.
> 
> Just add baguettes to the bread_cache list. Don't need to overcomplicate it.

...I was asking how to do that.

**Comment by Linzolle** [comment]
> 
> 
> > > > Have a look at code/datums/helper_datums/teleport.dm.
> > > 
> > > 
> > > The problem is that there's only an "if" and an "else if" and if I try to copy the else if for baguettes, it doesn't compile.
> > 
> > 
> > Just add baguettes to the bread_cache list. Don't need to overcomplicate it.
> 
> ...I was asking how to do that.

```
var/static/list/bread_cache = typecacheof(list(/obj/item/reagent_containers/food/snacks/store/bread, 
/obj/item/reagent_containers/food/snacks/baguette))
```

**Comment by Linzolle** [comment]
Actually, is there not any reason you could simply make baguettes a subtype of bread?
Not to mention the various other types of bread that are not bread subtypes. How necessary is this?

**Comment by TheEaterOfBeans** [comment]
> Actually, is there not any reason you could simply make baguettes a subtype of bread?
> Not to mention the various other types of bread that are not bread subtypes. How necessary is this?

eeeehhhh
not the point of this PR

**Comment by TheEaterOfBeans** [comment]
> > > > > Have a look at code/datums/helper_datums/teleport.dm.
> > > > 
> > > > 
> > > > The problem is that there's only an "if" and an "else if" and if I try to copy the else if for baguettes, it doesn't compile.
> > > 
> > > 
> > > Just add baguettes to the bread_cache list. Don't need to overcomplicate it.
> > 
> > 
> > ...I was asking how to do that.
> 
> ```
> var/static/list/bread_cache = typecacheof(list(/obj/item/reagent_containers/food/snacks/store/bread, 
> /obj/item/reagent_containers/food/snacks/baguette))
> ```

doing that makes it not compile anymore

**Comment by TheEaterOfBeans** [comment]
AAAAAAAAAAAAAA
someone HELP
I don't know how tO **ADD BAGUETTES TO THE FUCking** BREAD LIST

**Comment by TheEaterOfBeans** [comment]
**help**

**Comment by TheEaterOfBeans** [comment]
closing this because I couldn't figure out how to add baguettes to the bread list

**Pull request closed without merging**
