### PR TITLE
ports sec jumpsuits/skirts/gloves from hyperstation

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
title
only ports stuff listed in title, didn't add other items because I didn't think they were a good addition to citadel
it's all in the loadout

## Why It's Good For The Game
more clothing good

## Changelog
:cl:
add: ports some security loadout clothing from hyperstation
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
The skirts, gloves, and boots look good, but I don't like the pink variants. Pink just isn't a Security color.

**Comment by necromanceranne** [comment]
Oh no latex mallcops with guns in thigh high heel boots.

**Comment by MrJWhit** [comment]
I agree with the pink variants not looking great.

**Comment by timothyteakettle** [comment]
while i agree with that, i'm on the stance that some people might like them, which is why they're there as an option, my personal tastes in clothing are not going to influence me not porting certain clothing

**Pull request closed without merging**
