### PR TITLE
Adjusts Thermals in Genetics; Moves X-ray implant to illegal tech.

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

closes  #14415

Makes some minor nerfs to Thermal Vision from genetics
It is a recipe now. Recipe is Near-sighted + Stimmed. 
because it's a recipe you can no longer have it activated for free. Instability raised to 40.
Stimmed increased slightly in difficulty to match what Thermals was at.
X-ray vision mutation (not obtainable) had instability raised to 50, for parity.

Xray eyes is now illegal tech. No other changes.

## Why It's Good For The Game

#14415 has no idea what it's doing and just shotgunned a bunch of numbers to nuke vision techs because salt.

28 difficulty means *approximately 28 missing blocks* or *up to 14 missing pairs*. Obviously that makes Thermal vision more or less impossible to obtain from genetics. 71 instability is also not well considered and you can just bypass it by having Thermal rolled in your gene pool. Keron has me blocked so I can't exactly point this out.

This is a lot more sane and also means you can't cheese the instability of thermals by just rolling it in your natural genes. 

I could probably let the other PR just close because it's clearly untested code, but thermals is kinda gay so it could probably use a light nerf.

## Changelog
:cl:
balance: Genetics - Thermal vision is a recipe instead of a natural gene now. Nearsighted+Stimmed. Other minor nerfs, Thermal is 40 instability.
balance: Research - X-ray eyes are now an illegal tech.
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
the changes here seem fine but overall alternatives are being discussed which would mean a change like this would be better off being delayed until talks on them have finished

**Comment by timothyteakettle** [comment]
in response to the difficulty comment made in this PR, please see my comment about how difficulty functions in the other PR which you reference, it's a bit different to how it is expected to behave

**Comment by YakumoChen** [comment]
18 is the current default for Thermals. From playing genetics myself, it typically rolls between 3-5 missing pairs, with a couple other mutations sharing similar difficulty. 

3 pairs is about the maximum you can brute force, going through every combination until one works.

To get to three you either have to be lucky, use Jokers and hope you are researching the right gene, or manually log other combinations of the same gene and slap them together. All of these can be very time consuming, and only sometimes very fast if you get lucky.

I dont feel anything more than maybe 20 difficulty is reasonable for gameplay balance. TG has not changed the difficulty of any mutations to make them harder, making 18 the upper reasonable bound I would expect it to be generally considered "hard but not impossible"

**Comment by The-Sun-In-Splendour** [comment]
Delete genetics & X-ray

**Comment by timothyteakettle** [comment]
I was more just wanting to suggest that you change the description as it's misleading, difficulty 28 does not mean 28 missing pairs, it means 28 blocks are replaced to be missing, but because they can replace missing blocks, it's 'up to' 28, not always 28 (and for all 28 to be unique would be incredibly rare)

**Review by DeltaFire15 — APPROVED** [review]
After discussion, looks good and should make the mutation somewhat more difficult to acquire, especially considering it can no longer be a 'free' mutation.

Behind the xray change aswell since why'd you ever print thermal eyes if xray ones exist. The illegal node lock should make them more rare than before (given, it wasn't exactly that common before, but not rare either)

**Comment by DeltaFire15** [comment]
Merging this in favor of #14415

**Pull request merged**
