### PR TITLE
removes assistant

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

as title. removes assistant from the game

## Why It's Good For The Game

we have pop and 50% of players or more are still assistants all the time. i was recently on a round that was literally 90% assistant. people looked at the job listing, saw nobody was playing any roles, and unironically picked assistant. come on.

get a job hippies

## Changelog
:cl:
del: assistant
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
speed merge, it makes medical lore accurate.

**Comment by TheEaterOfBeans** [comment]
Putnam moment.

**Comment by Kraseo** [comment]
lol

**Comment by timothyteakettle** [comment]
if this is merged i'm just gonna go play somewhere with assistant

**Comment by keronshb** [comment]
Funny but not needed. 
>Get Pop Again
>Let's kill it

**Comment by Linzolle** [comment]
based

**Comment by KrabSpider** [comment]
I can't wait for jobs to get more content added to them!!!

**Comment by Solaris-Shade** [comment]
Amusing idea, make the assistant "job" pop locked.

**Comment by Linzolle** [comment]
why is this meme pr still open

**Comment by iliyaxox** [comment]
pls reconsider

**Pull request closed without merging**
