### PR TITLE
Various Mining borg changes. And some extras.

### PR DESCRIPTION
**Pull request by BlackMajor**
Mining borgs have been left outdated and unloved for a long time.
So, like all the other borg changes I've been doing lately, I'm giving them a run of updates.

This PR does the following.

- [x] Adds a dogborg variant to mining borgs. Wouldn't be cit without a dogborg for every module.
- [x] Mining Cyborg clamp. Functionally the same as the Ripley clamp. Can pick up an ore box for 3x3 pick up area. Cant pick up the nuke disk or any container with mobs inside.
- [x] Removes mining satchel of holding borg upgrade, considering the above.
- [x] Mining Cyborg basic plasma cutter. Worse than the protolathe one. Can upgrade to full at robotics. Recharges from the borg's power cell with its own 1250 power cell, shots cost 100 energy each, meaning the cyborg can fire 12 shots before needing the cutter to recharge. After testing, this seems fine.
- [x] All pickaxe subtypes given a 3 wide dig range. Except the cyborg diamond drill and sonic jackhammer, which were given a larger range. Perhaps too big.
- [x] All pickaxe subtypes now have an attack_self proc, allowing them to toggle between wide dig and singular dig at the cost of digspeed.
- [x] Shovel removed from mining borg since drill does its digging job, and the new borg tools can do its butcher job.
- [x] Mining Cyborg Kinetic crusher. Works identical to the regular crusher. Deals slightly more damage on the resonate and slightly less damage on the regular hit. Since letting an unemagged borg have a 20 brute weapon would be a bad idea.
- [x] Mining Cyborg Survival pod deployer. Can pick up and deploy survival pods.
- [x] Mining Cyborg mining point card for claiming and spending mining points. Future intent for this is so borgs can stash mining points in a point bank object I'll make later.
- [x] Let mining cyborgs upgrade their own KA/Crusher by clicking on respective upgrades with them. This is just QoL (and because inserting the upgrades into the borg directly doesn't work)
- [x] Add mining cyborg wrapping paper.
- [x] Add mining cyborg destination tagger.
- [x] Mining Cyborg Advanced Plasma Cutter robotics upgrade, still has the same power restrictions as the basic.
- [x] Mining Cyborg Premium Kinetic Accelerator robotics upgrade.
- [x] Basic pod now has borg charger
- [x] Luxury pod has upgraded borg charger
- [x] Bar pod has full upgraded borg charger
- [x] Change total roundstart borg slots from 1 -> 3. Argue this please, maintainers. Otherwise I'm doing it, since there's often like 3 assistants outside robotics shift start during highpop pulling their own brains out to get borged.

I'm finishing up this PR early so I can go work on other projects and get this merged.
But here's a list of the unfinished stuff I was going to do in this PR, that i'll save for another time.
-Rapid Rail Dispenser, RRD. Works like transit tubes but instead its rails and minecarts. Available in the mining vendor / mining cyborg.
-Mining Cyborg robotics upgrade: rechargeable fulton beacon, only recharges in borg chargers.
-Mining Cyborg robotics upgrade: rechargeable wormhole jaunter, only recharges in borg chargers.
-Remove stun arm from mining borg.
-Add emagged Cyborg Ore Cannon. Can load mats and fire them for various effects.
-Add emagged cyborg clamp. When emagged, can throw loaded crates at people for brief knockout damage. Can also use on mobs to pinch them, much like the peacekeeper emagged hug option.
-Point bank:
A static machine miners can store points in and transfer exact amounts. Starts in mining dock on the wall beside the vendor and the golem ship.

-Remote point bank:
Can be linked to a static point bank to do the same but remotely.
Can be built in a protolathe after researching mining tech.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Keep in mind, that borgo's can already upgrade their KA with the prolathen mods, if someone uses the mods on a open borg

**Comment by Soranayo** [comment]
As far as i know, shovel's only use apart from getting sand quickly was butchering mobs, but if you give them a plasma cutter that use is replaced, so shovel removal is a thing that could happen, if you buff the digging speed for drills.

**Comment by ghost** [comment]
don't change total borg slots, robotics exists for a reason 4head

edit: maybe make it 2 at highpop (like 60/70+ or something)

**Comment by BlackMajor** [comment]
> don't change total borg slots, robotics exists for a reason 4head
> 
> edit: maybe make it 2 at highpop (like 60/70+ or something)

I want you to go to the discord and type "Robotics Lab" in the search bar and look closely at what comes up.

The difference between 3 roundstart borg slots and 1 roundstart borg slot and someone who failed to get the roundstart borg slot is about 2 minutes of interaction at robotics as a latejoin assistant beelines robotics to say "Borg me please".

Imo this is just QoL stuff to skip that process.

**Comment by KathrinBailey** [comment]
> > don't change total borg slots, robotics exists for a reason 4head
> > edit: maybe make it 2 at highpop (like 60/70+ or something)
> 
> I want you to go to the discord and type "Robotics Lab" in the search bar and look closely at what comes up.
> 
> The difference between 3 roundstart borg slots and 1 roundstart borg slot and someone who failed to get the roundstart borg slot is about 2 minutes of interaction at robotics as a latejoin assistant beelines robotics to say "Borg me please".
> 
> Imo this is just QoL stuff to skip that process.

Couldn't agree more. Fuck having to play a different character, just to get your brain tugged out and put into a MMI. It's a waste of time for robotics and a waste of time for the players, it is also heavy NRP fuel. Everyone wants to be wide awake as the roboticist cuts their skull open (yikes) to save time. I somewhat changed that with my Box rework PR with adding anaesthetic on the operating table (hopefully someone took the hint?).

The only thing that needs to be discussed about roundstart borg slots being increased isn't if it should or shouldn't be, but if we're going to two slots or three slots. Imo 2 slots normally, 3 slots for 70+ players. Robotics still has to upgrade and reset borgs, they can still build mechs, they can make even more borgs, they still have stuff to do.

**Comment by ghost** [comment]
yeah fair enough


@BlackMajor remove crusher from borgs, hunter borgs killing miners is a sin
i've had borgs tell me they'd rather directly kill a miner by chasming them than let tendrils live 😂 

if you start drilling something in fast mode and swap to slow mode, it does the increased range of mining despite drilling at the faster speed.

you can drill multiple areas around you at once by drilling into a wall and looking in another direction.

drill only drains 1 charge (out of 10,000 from default battery), and drains it at start. should make it drain more(?) and at the end of the drilling process

large drill only drills 1 floor of sand

miner borgs unbalance the mining vendors, because you can spend 10 minutes drilling roundstart as a borg, go back with the other miners getting their first plasmacutters, and now there's miners running around with premium pka's and full healing and such because you got like 6-8k on your first trip

**Comment by Soranayo** [comment]
> @BlackMajor remove crusher from borgs, hunter borgs killing miners is a sin
> i've had borgs tell me they'd rather directly kill a miner by chasming them than let tendrils live 😂

I mean, PKA does the job much better, removal of the crusher is a big why for me, especially when, (I haven't tried, personally, so i base that on my normal crusher's knowledge, not the borg one.) you can't actually crusher blast tendrils.
You could also, you know... Just order them to not hunt tendrils, they still have to obey.

> 
> if you start drilling something in fast mode and swap to slow mode, it does the increased range of mining despite drilling at the faster speed.

I noticed that too, i can confirm it works with the diamond drill as well.

> 
> you can drill multiple areas around you at once by drilling into a wall and looking in another direction.

Yes, but it also only mine the large area in the direction you're looking at, aka if you start drilling north, and then south, north will only get one tile removed, and the other the normal 3.

> 
> drill only drains 1 charge (out of 10,000 from default battery), and drains it at start. should make it drain more(?) and at the end of the drilling process

As for the charge i'd say it's honestly pointless to change it, since it's not the main mining tool for borgs, at least from what i've experienced myself, the cutter, PKA and Crusher, and later the advanced cutter upgrade does the job much better, at least until the diamond drill is there, and when it is, chances are you already have a yellow core or a bluespace, making power more or less irrelevant.
> 
> large drill only drills 1 floor of sand

That also is annoying, but not for the same reasons as yours, i think it should at least speed up the sand gathering (Honestly, i haven't checked, i'm not sure it does or doesn't.)

> 
> miner borgs unbalance the mining vendors, because you can spend 10 minutes drilling roundstart as a borg, go back with the other miners getting their first plasmacutters, and now there's miners running around with premium pka's and full healing and such because you got like 6-8k on your first trip

Technically it's because they have less stuff to buy, and because there are more work force around lavaland, if miners were willing to share points, it'd end up doing the same thing to be honest.

One thing i'd like to have, but probably is unbalanced as hell is having the borg plasma cutter being a part of the advanced mining tech, and only that one. I know why it's not the case (Aka borgs are meant to be better than miners at roundstart and fall off since miners get their tech much faster/get gear.) but currently, you don't get 'em until everyone's donezo with lavaland.

**Comment by ghost** [comment]
yeah i was reporting bugs

also for crusher let miners hunt don't encourage shitter borg behavior crusher just encourages hunting (because it has no use as a mining tool)

borgs shouldn't be able to just hunt things without consequences (borgs can't die or lose gear so 😂)

**Comment by Soranayo** [comment]
> 
> 
> yeah i was reporting bugs
> 
> also for crusher let miners hunt don't encourage shitter borg behavior crusher just encourages hunting (because it has no use as a mining tool)
> 
> borgs shouldn't be able to just hunt things without consequences (borgs can't die or lose gear so 😂)

See, the thing is, i disagree, not only crushers do have a mining usage, especially early on, but also, PKA is vastly superior to crusher, for both carbons and -especially- for borgs since they can't upgrade their armor.

As for the usefulness in matter of mining, since PKA/crusher does not share cooldowns, you can shoot your PKA, then swap to crusher, shoot, swap, and so on, it's much faster than, you know, waiting for the cooldown, and slightly faster than a one-tile normal drill. Keep in mind, me as well as other miners have used that strategy as a carbon as well, silicons just make that much easier (Especially since picking up crushers nowadays only put them in a single hand, so you have to two hand it at every pickup.).

**Comment by YakumoChen** [comment]
The pick area mining is buggy if you're dragging a crate, it mines like adjacent to the crate instead of in front of you.

**Comment by BlackMajor** [comment]
> The pick area mining is buggy if you're dragging a crate, it mines like adjacent to the crate instead of in front of you.

Whoops. I know why too...

**Comment by BlackMajor** [comment]
Oh what the fuck

**Comment by BlackMajor** [comment]
Fixing icon conflicts should not be this hard.

**Comment by davethwave** [comment]
Can see most of this being ported to other servers. This is a big change.

**Comment by davidchan13** [comment]
I dislike the ore satchel upgrade going away.

But I do like more borg slots. We have a fair number of players who like to play silicon so this is good.

As an alternative though, perhaps making it so inactive posibrains can be placed into complete shells to add a borg slot to the late join menu so players can hop right into then from the lobby?

**Comment by davidchan13** [comment]
I dislike the ore satchel upgrade going away.

But I do like more borg slots. We have a fair number of players who like to play silicon so this is good.

As an alternative though, perhaps making it so inactive posibrains can be placed into complete shells to add a borg slot to the late join menu so players can hop right into then from the lobby?

**Comment by BlackMajor** [comment]
> I dislike the ore satchel upgrade going away.
> 
> But I do like more borg slots. We have a fair number of players who like to play silicon so this is good.
> 
> As an alternative though, perhaps making it so inactive posibrains can be placed into complete shells to add a borg slot to the late join menu so players can hop right into then from the lobby?

Ore satchel upgrade went away since it didn't make sense with borgs being able to carry ore-boxes in their internal cargo hold.
Neat idea on the posibrain change, but I'm not doing it in this PR.

**Comment by ShadeAware** [comment]
Building on that, being able to add some cyborg upgrades to a shell before it comes online would be a HUGE QoL when mass-producing cyborgs and you want them to come standard with upgrades.

**Comment by BlackMajor** [comment]
Removing WIP tag since this is technically in a good stage to merge now.

**Comment by BlackMajor** [comment]
Reeee conflict man bad

**Comment by BlackMajor** [comment]
Fug it, I'll fix the spawns in another PR. Fixing these conflicts will make me hate life.

**Review by Putnam3145 — APPROVED** [review]
didn't do my due diligence checking the files but it's been testmerged for a while and keeping this sort of thing testmerged is *painful* so

**Pull request merged**
