### PR TITLE
Makes tapered penises look more tapered

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

My god do I feel weird putting that as a pull request title, wew. WFWTP asked me to do this so here's what they now look like:
<details>
 <summary>image example spoiler</summary>

Annotation_2019-11-12_164102
</details>
Which is basically a single cock from the hemipenis sprite.

## Why It's Good For The Game

Because the current tapered penises look like - not tapered. This looks better in my opinion, and probably in a few others' as well.

## Changelog
:cl:
tweak: tweaked the way the tapered penis looks
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
Paxton told me of a dragging sprite so I may have to just go back and actually make that one, sadness

**Comment by AffectedArc07** [comment]
@KeplerStation-Bot NOMIRROR

**Comment by Owai-Seek** [comment]
I'd say make it a new type rather than outright replacing it, just in case people like the old one.

**Review by silicons — APPROVED** [review]

**Comment by Weblure** [comment]
Looks a bit too pointy and sharp imo

**Pull request merged**
