### PR TITLE
Adds 3 new Copyright compatible space-y music tracks to title

### PR DESCRIPTION
**Pull request by Thalpy**
## About The Pull Request

Adds 3 new tracks to play at title:

1. The End by Cerulean Crayons
https://carlthome.bandcamp.com/track/the-end
Licensed under Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)

2. Flying High by Lauren Bousfield
https://laurenbousfieldanyev3r.bandcamp.com/track/flying-high
Licensed under Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)

3.  霊桜 -Samsara- by maritumi from Haunted House by cYsmix
https://cysmix.bandcamp.com/track/samsara
Licensed under Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0)

## Why It's Good For The Game

Gives cit a bit of local flavour, and introduces more people to exciting new music!

## Changelog
:cl: Fermis
add: Adds 3 new music tracks.
/:cl:

### CODE REVIEW

**Comment by Zeldazackman** [comment]
>cYsmix

Always a good name to see pop up from time to time

**Comment by Thalpy** [comment]
As much as I wanted to add "The Space Shrine Maiden Appears" to this list I couldn't, turns out Touhou doesn't license out it's assets, except for characters, location, lore and screenshots. (Even if we'd probably get away with it.) I think the track I used instead is suitably spacey enough though. 

As a side note; if you can find out if O-Life.jp has a creative commons license, then you should tell me! They've done a really good remix of The Space Shrine Maiden Appears, but I can't figure out their license from their website.

**Comment by Zeldazackman** [comment]
Honestly the best way to contact MasamiT seems to be just to tweet at them these days as I've not gotten a response in the past few days from the email, perhaps due to the way that the japanese domains are set up?

**Comment by Thalpy** [comment]
I don't know Japanese well enough to tweet at them sadly.

**Review by nik707 — APPROVED** [review]

**Pull request merged**
