### PR TITLE
Who the fuck thought this was okay? (Removes monophobia)

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removes monophobia. Who thought a buggy trait that kills you if you don't stick around people was a good idea? Who thought forcing people to be grouped up, a thing that makes the life of antags harder, a good idea? Nothing about this trait is good, it's all bad, actually one of the worst additions I have ever seen in my fucking life.

## Why It's Good For The Game

Maybe let's not add a trait that forces people to group up constantly or else they just fucking die. Why the fuck.

## Changelog
:cl: Tupinambis
del: Monophobia trait
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
### 🧂I DETECT SALT🧂

**Comment by lolman360** [comment]
@TheSpaghetti https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13019

**Comment by ghost** [comment]
Oh, also, I use the monophobia trait and I've only died from it 3 times, one of which was while I was blind (brain trauma from defibrillation), and the other two were from taking too long to finish doing surgery. There are plenty of warnings before it kills you, though an easier way to tell how much stress you have would probably be a good idea.

**Comment by ghost** [comment]
> @TheSpaghetti #13019

ok whatever

**Comment by Tupinambis** [comment]
The issue is less the risk of dying from it, and more an issue of the fact it actively encourages people to stick in groups, which is incredibly powerful with how citcode plays. I don't want a trait that literally forces people to buddy system, most antags rely VERY HEAVILY on people being isolated.

**Comment by ghost** [comment]
> The issue is less the risk of dying from it, and more an issue of the fact it actively encourages people to stick in groups, which is incredibly powerful with how citcode plays. I don't want a trait that literally forces people to buddy system, most antags rely VERY HEAVILY on people being isolated.

Monophobia is one-sided. The mechanics encourage the person with it to be around others, but they don't significantly encourage anyone else to group up.

**Comment by Putnam3145** [comment]
I mean, one person being forced to group up means that two people are gonna be grouped up.

**Comment by ghost** [comment]
> I mean, one person being forced to group up means that two people are gonna be grouped up.

Monophobia only requires the monophobic person to avoid being alone, it doesn't make him/her have to specifically follow one person around. ANYONE, including antagonists, counts, and there's no real incentive for people to stay around the monophobic person. People who group with the monophobia trait are likely still going to group if the trait gets removed.

**Comment by silicons** [comment]
the [s] tag is for security issues

**Comment by ghost** [comment]
to be honest this pr would have been viable if instead of opening up with "it's hard for antags!!" you opened up with the fact it's another character quirk that just straight up kills you

**Comment by moltoretardo** [comment]
Going waaah I can’t ruin someones round because they’re grouped and not always alone in a “mrp” server shouldn’t be an argument. If someone always wants to be grouped he will still always be grouped. The argument should be that it’s a dumb quirk that kills or a dumb quirk that gives a free trait point for backrider players. “Making antag life harder” as if it wasn’t already easy enough with the pop nowaday is at best laughable.

**Comment by Tupinambis** [comment]
It is multiple issues simultaneously. It A: Just kills you, B: Is in fact free points for backriders, and C: is buggy, and D: isn't good for gameplay. If the claim is that people who use the trait are just going to stick around people either way, than yeah it's still bad because then it's free points. It's bad conceptually.

**Comment by silicons** [comment]
@TheSpaghetti Kindly stay out of PRs if you can't keep civil.

**Comment by silicons** [comment]
Overall I don't think monophobia is harmful enough to remove. A lot of things are just "free points" and if any positive quirk is too powerful nerf that instead.

**Comment by silicons** [comment]
Overall I don't think monophobia is harmful enough to remove. A lot of things are just "free points" and if any positive quirk is too powerful nerf that instead.

**Pull request closed without merging**
