### PR TITLE
Changes damage mods for lizardfolk

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Adjusts temp damage mods for lizards for the following:
+20% cold temp damage
-20% heat temp damage

## Why It's Good For The Game

The (relatively) new damage modifiers are not necessarily bad, but currently they are very unbalanced and large, the change should make lizard race more in line with humans and balanced

This is being made for Nayser#2314, any comments towards me, will be directed towards them instead. I'm just the middle man for this change, I have no skin in the game.

## Changelog
:cl:
tweak: Lizard temp damage mods adjusted to be an even 20% on either side
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
i'm fine with how they are currently personally, considering that cold damage you take is tiny anyway and other species like slimes take **triple cold damage and regular heat damage and start taking damage from cold air at regular temperatures (11.85C)**

**Comment by Sishen1542** [comment]
But why

**Comment by Putnam3145** [comment]
0.8 isn't -20%, it's -25%

**Comment by dapnee** [comment]
He can’t even math.

**Comment by MrJWhit** [comment]
Nah, that math is on me, this stuff is weird. I'm waiting for an updated value right now.

**Comment by MrJWhit** [comment]
Math has now been math'd to be 20% on both sides.

**Comment by Nayser8** [comment]
It's good because as of now, 50% more damage from cold is just ridiculous, if you want to compare it to slimes which are more vulnerable, they get some incredibly useful abilities to back it up. Lizards codewise are just hissy humans with tails with huge damage modifiers. I'm honestly fine with completely removing damage modifiers to completely make sure it's balanced. But a subtle damage modifiers are flavorful.

**Comment by moltoretardo** [comment]
We should remove their special language too since we want them more like humans. Maybe also remove their genetic flamethrower trait too since humans can’t have it. That’d make them balanced enough.

**Comment by timothyteakettle** [comment]
random unrelated fun fact: did you know lizards get a +1 defense buff to tackles while their tail is wagging
i want to add some flavour text for it because it's funny

**Comment by SandPoot** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10441 all over again.

**Comment by silicons** [comment]
wildly disliked and i agree with the people who already commented regarding this, sorry.

**Pull request closed without merging**
