### PR TITLE
Makes sure the server can never ever crash ever again

### PR DESCRIPTION
**Pull request by LetterJay**
:cl: Jay
tweak: Reduced autocall to two hours.
/:cl:

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
Speedmerge this,

**Review by deathride58 — APPROVED** [review]

**Comment by JogBoba** [comment]
Please just test merge this

**Comment by silicons** [comment]
techwebs is currently balanced for 3 hours.

**Comment by king5327** [comment]
I mean, it's not like the server sometimes OOMs 1h into a round after a full restart.

**Comment by MimicFaux** [comment]
This fixes the symptom, not the cause

**Comment by king5327** [comment]
I don't know anything about the server configuration, but my first instinct would be to increase swap space (since memory leaks can be swapped out and stay swapped out). If it persists then I'd resort to such drastic measures.

**Comment by ariever** [comment]
Even a fix that's supposed to make sure the server never breaks again is no match for **DELTA**.

**Pull request merged**
