### PR TITLE
Removes slowdown from clown shoes.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Clown shoes no longer slow you down.

## Why It's Good For The Game

Clowns will wear their shoes again. Pretty sure everyone hates seeing clowns with normal, non-clown shoes.

## Changelog
:cl:
tweak: Clown shoes no longer slow you down.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
No.

**Comment by ghost** [comment]
> No.

Why?

**Comment by moltoretardo** [comment]
No.

**Comment by ghost** [comment]
> No.

Again, why?

**Comment by ghost** [comment]
No.

**Comment by ghost** [comment]
Can people stop commenting "no" without actually explaining why they don't like this? I just want the powergamer clowns who don't wear their shoes because of the slowdown to STOP.

**Comment by Kraseo** [comment]
if you want them to wear the shoes make the moodlet debuff for not wearing them big enough that it slows them down from no sanity
otherwise this is just a dumb pr because clown shoes are meant to be goofy and annoying to wear

**Comment by ghost** [comment]
they're annoying to wear because yo go squeak honk on h honkm honk squeak

thank you for coming to my ted talk

**Comment by dapnee** [comment]
He shoes too big for his goddamn feet! Also, no.

**Comment by MrJWhit** [comment]
No.

**Comment by lolman360** [comment]
No.

**Comment by Ragolution** [comment]
Absolutely not. This is a major balance concern. Those shoes are what make the clown not a force of godlike antag (or Staff) obliteration. No, a thousand times no. Never. A shoeless clown is a tried-and-true sign of a POWERGAMER, and Staff looks for this, frequently.

This unironically needs the Balance tag.

**Comment by ghost** [comment]
> Absolutely not. This is a major balance concern. Those shoes are what make the clown not a force of godlike antag (or Staff) obliteration. No, a thousand times no. Never. A shoeless clown is a tried-and-true sign of a POWERGAMER, and Staff looks for this, frequently.
> 
> This unironically needs the Balance tag.

Clowns aren't any better than an assistant.

**Comment by lolman360** [comment]
pies are still really fucking robust with reagent transfer even though they lost their stun and slips are still a free knockdown

**Comment by ghost** [comment]
> pies are still really fucking robust with reagent transfer even though they lost their stun and slips are still a free knockdown

Everyone can use pies. And peels.

**Comment by silicons** [comment]
this will not be happening.

**Comment by MalricB** [comment]
no lol

**Comment by BlackMajor** [comment]
Closing this due to wide consensus from both staff and maintainers.

No.
The clown is historically a punishment role that is meant to be more of a pain to play, hence the clumsiness and clothing restrictions.
A clown who keeps his shoes on is a shining beacon of a good clown at a glance, one who is committed to the role.
A shoeless clown is a scourge, a red flag of darker times to come. These people need that clear cut, distinct difference from the good clowns so at but a mere glance, you can tell they're an unfunny clown.

By enabling the latter to go with shoes, you fall prey to mixing the two genus's of clown together. A horrible fate for all spacemen.

**Pull request closed without merging**
