### PR TITLE
Port of TG's "Auto Observe"

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/54031. It allows you to toggle an "Auto-Observe" mode that shows you the player's UI and inventory. Oh, and also it makes orbit menu update dynamically

## Why It's Good For The Game

Well, better orbit menu? And ghosts can do bag checks now!

## Changelog
:cl:
add: The orbit menu now has an Auto-Observe button! No more sifting through the lame observe menu to snoop in people's backpacks! Also, orbit menu now refreshes.
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
this does not work well here because we have respawns, and thus being able to look in bags as a ghost encourages meta-y behaviour

**Comment by SandPoot** [comment]
> this does not work well here because we have respawns, and thus being able to look in bags as a ghost encourages meta-y behaviour

You can normally check bags using the observe command, this just makes it more intuitive, *and some people don't even know about it*.

**Comment by timothyteakettle** [comment]
i was strangely not aware of this, so uh, while against the fact you can do it in the first place, yeah sure whatever im neutral on this

**Comment by Arturlang** [comment]
@timothyteakettle You can already check all antags using the game-info verb anyway

**Pull request merged**
