### PR TITLE
allows headsets to be bowmanized and adds a traitor item for that

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Dynamic bowmanizing headsets yay + a traitor item that also does that for 3 tc.

## Why It's Good For The Game

I dunno. Why not. Also, flashbang protection for traitors.

## Changelog
:cl:
add: traitor tool for bowmanizing headsets + bowmanizing headsets
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
you could change the bowman noise protection to a variable or something if you want to make it a little  bit cleaner (like the !ifbowman/syndicate/alien name check)

**Comment by Seris02** [comment]
>conflict within 4 hours

fucking goddamnit

**Comment by yourdoom9898** [comment]
Minor as hell nitpick, but isn't the bowman's description kind of misleading, since the bowmans defend against loud sounds, and flashbangs still flash?

**Comment by Seris02** [comment]
It's the same examine line for all the other bowman headsets

**Review by silicons — APPROVED** [review]

**Pull request merged**
