### PR TITLE
Adds newtonian physics to a specific action

### PR DESCRIPTION
**Pull request by BlueWildrose**
## About The Pull Request

This allows you to propel yourself using a specific action. Just view the code and you'll see what it is.

Edit: If you want to find out without going to look at the single one line of code added, then click "Spoilers" below.
<details>
  <summary>Spoilers</summary>
Newtonian movement is now applied when you climax.
</details>

## Why It's Good For The Game

Realism.

But really, this is just a shitpost PR and it probably isn't. If it does get added then I apologize if someone leaves a specific mess on the floor due to a no-grav area.

## Changelog
:cl:
tweak: Adds newtonian physics to a specific action. Hint: It has to do with erotic mechanics.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
this paves the way for vectored cumjet thrusters

**Comment by BlueWildrose** [comment]
after I made this PR I discovered this tweet, which actually exists.
Neil deGrasse Tyson saying that you will recoil if you ejaculate in space.
https://twitter.com/neiltyson/status/36776479320702976?lang=en

**Comment by tiramisuapimancer** [comment]
this is funny but it also means you have less reason to not put bits on your character just so that you have free infinite space movement (idk the cum cooldown so its not like u str8 up space walk but its still like. you got nothin on ya you just skeet one and your back on station u kno)

**Comment by Detective-Google** [comment]
Shitposts aside this means you cant do things like gbj lings without items on space tiles while prepping to deal with them because theyll just nut back to the station

**Comment by DeltaFire15** [comment]
No thanks.

**Comment by BlueWildrose** [comment]
I was also heavily considering applying the fire extinguisher logic to climaxing as well, as in if you use a fire extinguisher while sitting on an office chair you'll get propelled backwards a certain distance.

But obviously that would be too much effort for a shitpost.

**Pull request closed without merging**
