### PR TITLE
[WIP] Combat Modernisation Rework

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
No changes so far in this WIP PR, a number of players I spoke to asked for this however so I'm now asking for feedback from maintainers whether this would be accepted first as it has some pretty significant changes. 

Citadel made the switch from stun to stamina combat before /tg/ did which helped the combat meta substantially, however /tg/ learned from other servers' implementations and today the state of their stamina combat system is more fluid and fun than Citadel's. This PR aims to replace stamina combat with tg's version. 

**The changes would include:**
- Removal of combat mode (and debuffs removed so you'll always do and take normal damage, shoot accurately etc)
- Removal of sprint toggle
- Base run speed increased slightly (slower than current sprint)
- Attacking doesn't drain stamina
- Disarm intent click now a shove 
- Stamina regenerates to full instantly after about 8 seconds with no stamina damage
- Soft stamcrit removed, hard stamcrit immobilises you completely until you regenerate out of it

## Why It's Good For The Game
Combat more fluid and enjoyable. 

## Changelog
:cl:
del: Combat mode
add: More dynamic stamina combat
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
for what exact reason are you making a PR to remove citadel combat system without actually talking to maintainers first in our discord discussion channels
i know i've told people to discuss things on github but i'm finding it strange that i've never even heard about you until i saw this pr today
what say you?

**Comment by Detective-Google** [comment]
> remove combat mode

based

**Comment by deathride58** [comment]
This isn't a modernization. TG's combat is *nothing* like what we have. This PR goes directly against the server's intended direction by removing features such as sprint, stamina penalties for attacking, and proper stamina regeneration.

**Comment by MrJWhit** [comment]
To be clear, we don't have any stuns outside of xeno neurotoxin, by just removing stamina as a whole, there isn't any way to non-lethally detain someone.

**Comment by VictorVow** [comment]
@kevinz000 wasn't sure if the preference for discussion was GitHub or here, as for not hearing about me I've given some more info on Discord.

@deathride58 the foundation for these features is older than tg's stamina combat system, though there have obviously been newer changes to it. You can argue for "intended direction" with any feature so I don't agree with that argument. 

@MrJWhit stamina wouldn't be removed, tg has a functional stamina combat system for disabler/stunbatons/etc, just there would be less actions which use stamina (ie sprinting, attacking).

**Comment by necromanceranne** [comment]
I mean there is a way to meet in the middle but completely undercutting the development thus far seems extremely unnecessary. You would be better off finding and more heavily defining states in which players can or can't act and reinserting some of the stunned states taken out. Namely, make it possible again to subdue someone without gear being the sole reason you could. 

The core difference between /tg/ and citadel combat is actually gear reliance. /tg/ combat has a fairly robust assortment of methods for fighting without even needing what would traditionally be defined as a 'weapon'. Though very basic compared to baystation, it's unarmed stuff is adequate enough to subdue people. That's because you can't always use gear and gear can be taken from you.

On citadel, the only thing that matters is whether or not your weapon does damage fast enough to stop someone ever escaping. If it doesn't do an overwhelming amount of damage, it's usually too shit to force anyone to engage. Disarming reliably is also solely in the hands of stun batons and telebatons, so if you don't have those there is no point trying for it.

Readd some bite to the elements of combat that need it. Environmental disables (soap is still pretty strong but you can't do much off it, this is more for tabling, shoving and so on), and add defined states in which you lose hand use outside of stamina crit and snowflaked effects. There is no real way to stop someone using weapons until you literally have them in crit, so if their stick is bigger and could kill you faster (and is a ranged weapon), you can lose for even attempting to fight even if you knocked them prone or just got in a few shots.

**Comment by silicons** [comment]
in other news
- this pr is unnecessary and rash
- necro is right

**Pull request closed without merging**
