### PR TITLE
[MIRROR] Blobs can now sense loving cuddles!

### PR DESCRIPTION
**Pull request by CitadelStationBot**
Original PR: https://github.com/tgstation/tgstation/pull/29820
--------------------

:cl: More Robust Than You
add: Blobs can now sense when they're being cuddled!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
oh god will you guys code blob arousal meters

**Comment by LetterJay** [comment]
Hell no. At least I won't.

**Comment by ghost** [comment]
i'd join just to see people ERP with blobs but i'm afraid i wouldn't be able to unsee it

**Comment by ghost** [comment]
knew it

**Pull request merged**
