### PR TITLE
gives ling armblade 20 armor pen to make it more in line with eswords

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
armblade now has 40 armor pen, vs the eswords 35

stats per weapon
armblade 25 force, 7.5 stam per swing, 0 melee block, 40 armor pen
esword 30 force, 6 stam per swing, 50 melee block, 35 armor pen

armblade does have nodrop which is pretty darn good, which is why I decided against giving it any block

## Why It's Good For The Game
giving lings a reason to use armblade, as currently it takes a lot more hits to dunk an armored target with an armblade than an esword even though both are loud and obvious weapons

## Changelog
:cl:
balance: ling blade now has 40 armor pen
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
stealth antag shouldn't be getting given more powerful non-stealth powers

**Comment by Sishen1542** [comment]
> stealth antag shouldn't be getting given more powerful non-stealth powers

armblade isn't stealthy

_**loudness = 2**_

**Comment by YakumoChen** [comment]
Exactly

Ling was designed as the original "stealth antag" though, it just got given a bunch of combat buffs over time.

**Comment by Poojawa** [comment]
So Ling just ignores sec armor now, neat. Totally won't be overpowered or anything.

**Comment by EgoSumStultus** [comment]
In its current state, armblade is practically unusable as a weapon. It takes 20 chemicals to pull out, so unless you have it out already and have waited for your chems to recharge, your chemicals are tanked while in combat. Not to mention the fact that melee combat is completely countered by any modicum of projectile weaponry. 
Many people who are considered 'good players' agree with the statement of armblade not being viable for combat use for the reasons listed above -- and rarely, if ever, take the ability in question.

**Comment by Sishen1542** [comment]
> So Ling just ignores sec armor now, neat. Totally won't be overpowered or anything

compared to the 25 force 100 armor pen 50 block chance rapier and 30 force 35 armor pen and 50 block chance esword, this is modest compared to any options traitors get

**Comment by davidchan13** [comment]
Eswords can't pry open powered doors.

**Comment by BurgerLUA** [comment]
Not a good way to balance things. Increase the ling damage to 50 if you must, 40 armor penetration is just a fucking meme.

**Review by silicons — CHANGES_REQUESTED** [review]
20.

**Review by silicons — APPROVED** [review]

**Pull request merged**
