### PR TITLE
Ports tgui stripping (finally)

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Title.
image
*"long" style is a pref now :)*
This might contain tg garbage, warn me what needs out.

## Why It's Good For The Game
Yes.

## Changelog
:cl:
tweak: Stripping menu is now tgui.
fix: You also no longer get every animation sprite and direction sprite of items on the menus.
/:cl:

### CODE REVIEW

**Comment by TripleShades** [comment]
Please use this window layout instead, to match closer to our current size.
image

**Comment by TripleShades** [comment]
Just realized, does this allow for untying shoelaces still?

**Comment by SandPoot** [comment]
Totally does, just not through suit.

**Comment by DeltaFire15** [comment]
Seems fine on local and didn't notice any glaring code flaws, testmerging.

**Comment by DeltaFire15** [comment]
I haven't heard any issues reported since the last one and didn't encounter any myself, so time to merge this before something conflicts.

If I hear complaints later that people didn't say for some reason I'll be very disappointed.

**Pull request merged**
