### PR TITLE
removes AI upgrade from illegal tech

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

removes it from illegal tech

## Why It's Good For The Game

because this is just validhunt baiting. plus this is bad balance, wew.

## Changelog
:cl:
balance: illegal technology
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I fine the disk rather good, it gives traitors that need to steal the AI a way in.
Well also making the AI life harder. As if the AI were to hear you say "LAW 2 OPEN DOOR" without coms the AI is still forced to open the door and obey the crew if its laws are to do so.
All in all I see the disk as a AI nerff then a pwergamer buff do to those factors

**Comment by necromanceranne** [comment]
@Seris02 is this giving the AI x-ray as well as lip reading or is it just lip reading?

If it's the former, maybe remove the x-ray from this? Likely it's just giving the AI the malf power and not some subtype.

**Comment by DeltaFire15** [comment]
This literally only gives the AI the ability to lipread, which isn't really all that bad considering we have a full combat upgrade on lavaland.

**Comment by ghost** [comment]
looks like someone got caught by an AI using the upgrade

**Review by silicons — APPROVED** [review]

**Pull request closed without merging**
