### PR TITLE
Fixes genewebs being impossibly impassable

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request

This fixes the Genetic Spider Webs to use the 50% chance for mobs, rather than the current 100% no-pass rate. I can adjust this number if required.

## Why It's Good For The Game

Bug Fix

## Changelog
:cl: Funce
fix: Genetics spiderwebs are no longer impassable walls
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
this makes them always return true on `canpass` making them 0% chance to get stuck

**Comment by Funce** [comment]
It was returning NULL before hand. So it was like 50% FALSE, otherwise NULL. So 100% FALSE.
This changes that so the base-line is TRUE

**Comment by lolman360** [comment]
yes the baseline shouldn't be true that's not how canpass works if you want genetic spiderwebs to be not-snowflaked remove the `if(genetic)` check entirely

knowing that that check was placed there intentionally this is more a balance pr than a fix

**Comment by Funce** [comment]
Huh, okay. Let me check that out.

------


Oh heck you're right let me change this to the original way I was going to do this.

**Pull request merged**
