### PR TITLE
.38 lever-action rifles but not actually implemented

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
adds .38 lever-actions, which are - well i'm not sure if i want to put them in cargo or blackmarket, both seem like funny options
initial size bulky, weight heavy, 7+1 capacity
can be sawed for -1 capacity (6+1), normal size, normal weight (mare's leg woo yeah boogie)

icons stolen from citrp which stole them from polaris
## Why It's Good For The Game
.38 is criminally underutilized and putting it in the hands of the crew would be, dare i say, incredibly fucking funny
## Changelog
:cl:
add: Lever-action rifles, chambered in .38, are now sitting in the code. They might be buyable from Cargo or the Black Market soon. Watch this space.
add: Sawed-off shotguns now look like shotguns, but short, when inhand, instead of "generic gun".
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
> You currently have a negative Fix/Feature pull request delta of -113. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

bruh

**Comment by Hatterhat** [comment]
> 
> 
> > You currently have a negative Fix/Feature pull request delta of -113. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> bruh

yeah

**Comment by KrabSpider** [comment]
**Let's fucking gooooooo**

**Comment by DeltaFire15** [comment]
Hm I dunno do we really need more 'cargo buyable gun' bloat? This time with detective-revolver ammo.

**Comment by MacaroniCritter** [comment]
> Hm I dunno do we really need more 'cargo buyable gun' bloat? This time with detective-revolver ammo.

"bloat" there will never be enough room for guns to buy from cargo.

**Comment by Tupinambis** [comment]
Ehhhh I am fine with the idea of .38 rifles but I think sawing off should either be impossible or result in more significant drawbacks. I don't like the idea of people carrying such a potent stamina weapon in their pocket with no indication then they have it, especially when you could so easily turn around a melee fight with a sudden pb .38 shot.

**Comment by Hatterhat** [comment]
> Hm I dunno do we really need more 'cargo buyable gun' bloat? This time with detective-revolver ammo.

pr state as of now is "not normally accessible" and we can deliberate over it later

**Pull request merged**
