### PR TITLE
Bees

### PR DESCRIPTION
**Pull request by Xantholne**
## About The Pull Request

Botany bee pet
New bee model
## Why It's Good For The Game

Bees are adorable murderers

## Changelog
:cl:
add: Botany bee pet, Bumbles
add: New bee models that aren't 1 tile big of 0 opacity pixels
/:cl:

dreamseeker_HnpDyQknFO
MfjYk0ooDr
dreamseeker_gagl0wor0r
b7ZKxXwapt

### CODE REVIEW

**Comment by Xantholne** [comment]
They aren't mapped yet so not ready, until Kevin actually helps me fix that issue 😠

**Comment by Trilbyspaceclone** [comment]
Aw they dont do anything for hydro trays?

**Comment by Xantholne** [comment]
> Aw they dont do anything for hydro trays?

The red eyed ones function *exactly* like the normal bees but with a new model to stand out, the  white eyed one is Bumbles, the humble bumblebee who floats around and sleeps randomly taking the station over as station's cutest pet.

**Comment by deathride58** [comment]
Unbeelievable

**Review by silicons — APPROVED** [review]

**Pull request merged**
