### PR TITLE
Ports "Some stealth box changes #45332" Aka nerfing Stealth boxes

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

https://github.com/tgstation/tgstation/pull/45332

## Why It's Good For The Game

They are memely good do to speed/blocking and being 100% unseeable waiting for CQC.
This should make it not act like a bullet sponge for nukies/traitors that know to abuse this 

## Changelog
:cl:
ports a nerf
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
You could also try and figure out the diagonal movement bug in storage/cardboard_box because I wasn't able to when I pushed port of my own stealth box nerf.

**Comment by lolman360** [comment]
this will turn stealth box into old launchpad

**Comment by YakumoChen** [comment]
People who abuse blatantly overpowered items will always flood in to complain when an item is finally kicked down to where it rightfully should be.

**Comment by lolman360** [comment]
i never use stealth box?

**Review by silicons — APPROVED** [review]

**Pull request merged**
