### PR TITLE
I CAN'T FIND CERESTATION OR CIRCLESTATION SO WE GET KILOSTATION

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
## About The Pull Request
It adds in Kilostation from /TG/.

## Why It's Good For The Game
More maps are great so that we can stop playing box constantly.

## Changelog
:cl:
add: Adds Kilostation to the list of maps
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Wiring is all completely borked, because /tg/ has autowiring, it can't be a direct translation anymore.

**Comment by Trilbyspaceclone** [comment]
this looks nothing like box

**Comment by KeRSedChaplain** [comment]
wait are TG maps just a bunch of single tile wires instead of actually in a line

**Comment by ShadeAware** [comment]
> wait are TG maps just a bunch of single tile wires instead of actually in a line

They have simple wiring, so yes
Think Minecraft Redstone, stationwide.

**Comment by ghost** [comment]
what does it mean by single tile wiring? isn't ours like minecraft redstone??

**Comment by MrJWhit** [comment]
No, no you're thinking of /tg/, they added autowiring about half a year ago, and citadel hasn't ported that over (kevinz is still against it from what I remember).

**Comment by KeRSedChaplain** [comment]
should I close this then and wait for someone else to do it? My PC physically cannot handle the map loader so i can't make any edits myself.

**Comment by Arturlang** [comment]
@KeRSedChaplain I think kilo was pre-smart cable, so just look through github, anyways dont count on someone else doing it.

**Comment by MrJWhit** [comment]
You may be able to grab it from Shadowstation as well, I know they used Kilo.

**Comment by necromanceranne** [comment]
The current version of kilo used on tg is updated to use the new wires. There might exist a pr with the original map somewhere in the tgstation github.

HOWEVER, fair warning, both versions suffered from a yet unidentified crash which occurs somewhere within the hour and a half point that nobody can work out yet. It's likely that the map is being disabled on tg until the fix is located. Definitely not worth porting until the fix is identified, as the crash was shared across both version of the map.

**Comment by LetterN** [comment]
How about donutstation?

**Comment by LetterN** [comment]
Also you need to add the JSON so the maploader can read it

**Comment by KathrinBailey** [comment]
@KeRsedChaplain
Pretty sure I have a version of Kilo before smart cable. DM me on Discord or @ me in dev discussion.
Floof Ball#0798
Also you can't just straight-port an entire map, you're going to run into a ton of issues, I'm not sure how it even compiled. Here's a few issues you're going to have:
• Dorms are tiny, they are useless on TG but are more or less necessary on Citadel. There aren't enough rooms and the rooms aren't big enough.
• Security has far too many cells, they're going to go unused and are more or less an ironic security risk, easy way to breach in.
• Missing Citadel-specific features, such as new vendors.

**Pull request closed without merging**
