### PR TITLE
adds three t1 donator items

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
adds three more items to the loadout in the donator category accessible by anyone who has donated to the server (once added to the config to be recognised as such)

i have no clue if the config has been setup for tiers
me hopes it has been

the items are as follows:
chameleon bedsheet, self explanatory

carpet beacon, choice beacon that grants 50 carpet of a chosen type

pet beacon, choice beacon that grants a pet of a chosen type, it's set to tiny size so it can't knock people over if thrown, and its butcher contents is set to null, comes in a pet carrier that can't be turned into metal at a lathe, can't be drained by bloodsuckers, bullets go over it, people go over it, etc

they all cost 1 point

i have tried to make sure none of these items can be abused nor do they give a mechanical advantage, which is how loadout items should be, if there's any flaws in this, please say so

## Why It's Good For The Game
uhhh something something donator incentive

## Changelog
:cl:
add: three new items are in the loadout for all donators
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
okay so there's a good chance the configs for tiers haven't been setup uhhh

**Comment by moltoretardo** [comment]
Chameleon bedsheet pog

**Comment by timothyteakettle** [comment]
gonna make some changes as per feedback

**Comment by Tupinambis** [comment]
People shouldn't be spawning with carpet and pets because they paid money. Even if small, these are things USUALLY relegated to either being a certain role or getting it via cargo. Suddenly we have to distinguish between fake pets and real pets, and suddenly it's very easy to look at someone and go "wow they paid money to throw carpet in my department" and be taken out of the experience. With something like bedsheets or the other personal items in the game, at least it's subtle.

Nothing is subtle about carpeting my floor or having an animal running around that happens to not be an actual animal. It's distracting, it's annoying, and if we must have donator items, at least keep them simple, like with hats.

**Comment by timothyteakettle** [comment]
thanks for the feedback, the whole carpet issue doesn't make sense personally, people can already retile stuff, i can understand being annoyed at not knowing which is a 'real pet' however i don't see a circumstance where this actually matters unless you're the cook and want to butcher it for food

also it should be pretty easy to tell considering: they have no blood (for bloodsucker purposes), are walked over, bullets go past them, they have a unique description detailing who they belong to, etc making them entirely useless as anything other than a vanity pet

the pet thing is definitely the one i'm most iffy about but i can't see any way it can be abused and it's just an all-round nice thing

(if maintainers find any of the stuff an issue ill happily remove it as they're just ideas to put more cosmetic stuff on the loadout for donators)

**Comment by timothyteakettle** [comment]
closing this until the config is setup one day as right now it's not

**Comment by timothyteakettle** [comment]
config is presumably going to be setup soon? maybe?

**Pull request merged**
