### PR TITLE
Adds looc hotkey - on examination, just makes it better

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Makes an looc hotkey, L.
## Why It's Good For The Game

Because it's infuriating that we have ooc hotkey and not looc hotkey.
On further examination, we do, it's control + o, but it doesn't work without pressing a button first, and this is much easier.

## Changelog
:cl:
add: Added looc hotkey
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
`but it doesn't work, and this is much easier.`
Enable hotkeys in your game preferences, not just pressing tab

**Comment by lolman360** [comment]
>qol change
>doesn't make game easier as "qol"
>literally just a simpler hotkey for looc

good first pr

**Comment by deathride58** [comment]
Dont we already have an LOOC hotkey?

**Comment by Seris02** [comment]
we do have an looc hotkey already, but most people, including me apparently, seemed to not know how to enable it.
as in, only one person was actually able to do it when I told people about it in ooc, and they were the only one who actually knew about it.
also, lolman, not first pr, weh, third PR, first was bluespace bio bag, second was a spess ruin that is slightly too loot-y now that I look at it again.

**Review by nik707 — APPROVED** [review]
literally an extra hotkey why not this is nice

**Pull request merged**
