### PR TITLE
Adds gas miners to all maps.

### PR DESCRIPTION
**Pull request by GrayRachnid**
## About The Pull Request
They said I couldn't do it

## Why It's Good For The Game
Makes it consistent with box

## Changelog
:cl:
fix: fixes consistency
/:cl:

### CODE REVIEW

**Review by Putnam3145 — APPROVED** [review]

**Comment by Trilbyspaceclone** [comment]
Hey Ive seen this one before
#8960
#9111

**Review by Ghommie — DISMISSED** [review]
Like Burger said on previous attempts, it makes no sense for gas miners to be in the middle of space and should be found by the lavaland, it both makes more sense and gives atmosia and cargo techs a reason to go there beside not doing their jobs and/or replacing missing miners.
I'll fight everyone trying to defy me here with a toothpick.

**Comment by GrayRachnid** [comment]
> Like Burger said on previous attempts, it makes no sense for gas miners to be in the middle of space and should be found by the lavaland, it both makes more sense and gives atmosia and cargo techs a reason to go there beside not doing their jobs and/or replacing missing miners.
I'll fight everyone trying to defy me here with a toothpick.

Box has them, some people vote box just for the gas miners. This is about consistency.

**Comment by Ghommie** [comment]
:crab: Remove gas miners from box then? :crab:
Whatever, I'm out of this.

**Pull request merged**
