### PR TITLE
MASSIVE SALT NERF

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
Romerol is pop locked to 30 people

## Why It's Good For The Game
zombies in dead pop is MAXIMUM FUN.

## Changelog
:cl:
balance: There actually needs to be people for zombies to happen now.
/:cl:

### CODE REVIEW

**Comment by HeroWithYay** [comment]
30 is a bit high, I'd say 25

**Comment by keronshb** [comment]
Change it to 20/25, like how SCarp and Eldritch are.

**Comment by ghost** [comment]
30 makes sense with the belief that it's to ensure that there are enough people for an actual outbreak 

instead of the belief that it's just grr noone fight back unless many people >:((

**Review by silicons — CHANGES_REQUESTED** [review]
Lock to 20-25, please.

**Pull request merged**
