### PR TITLE
Gives pod lava land ruin a autolathen 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
replaces a sink with a autolathen
adds in blueprints to get more plant disks
:cl: optional name here
tweak: replaces a sink with a autolathen
/:cl:

[why]
So pod people can print more ammo, tools and other misc items they mite want. - Headsets are in those by the by

### CODE REVIEW

**Comment by Poojawa** [comment]
why tho.

They're literally just supposed to be botanists growing shit.

**Comment by Trilbyspaceclone** [comment]
To get more tools and buckets. As stated. They have to grow grass and steel caps just to use the autolathen

**Comment by davidchan13** [comment]
This would actually be kind of nice since the ruin is notorious for being looted by miners, I've hopped on it several times to find the rare seeds, toolbox, beakers and sometimes even the entire DNA machine missing.

**Comment by Poojawa** [comment]
If that's the case, then they'll just steal that too, but I guess

**Comment by Bran34** [comment]
Being able to build onto the structure more effectively with autolathe tools would be cool, imo.  Kind of goes with the whole "bring life to barren worlds" flavor text.

**Review by silicons — APPROVED** [review]

**Pull request merged**
