### PR TITLE
Alert Sounds 2.0

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
[Changelogs]: You know that sexy ai lady voice we had? The one that welcomed us to the station? Well I killed it. It's gone now. In turn, I made it so that people can actually add voice lines to the game again without 20 hours of experimenting. 
:cl: ZeroNetAlpha
tweak: Tweaked security level code to use new sounds. wew.
soundadd: Added a whole new list of Announcer voice sounds. Everything from code green to delta, meteors to blobs.
server: The old files are still available for the announcement voice under the AI-Old file. I can remove them if requested.
/:cl:
https://www.youtube.com/watch?v=z7j9xWmkoaU
[why]: Honestly, I wanted to add some voice lines for delta alerts originally, that turned into trying to get the voice to match the existing announcer. That was a pain in the ass. I quit trying that.

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]
Be sure to add a link to VG's SS13 VOX Toolkit in a README.md inside the vox folder.

**Review by deathride58 — APPROVED** [review]

**Comment by ZeroNetAlpha** [comment]
And here's a video of some of those voice lines in action
https://www.youtube.com/watch?v=z7j9xWmkoaU

**Comment by Poojawa** [comment]
having heard a lot of these. 

meeeeeh.

**Comment by ZeroNetAlpha** [comment]
Do not fully merge this until 72 hours after 00:00 CDT (GMT -5) 3/16/2018. (00:00 GMT -5 3/19/2018)
Awaiting further input for audio tweaks.

**Comment by Nightspark43** [comment]
Yeah, I'm not sure I'm much of a fan of the new voice, being able to add new lines easily is nice, but it's rough on the ears and hard to understand sometimes.

**Comment by ZeroNetAlpha** [comment]
Closing this until I can get the tweaks I want to done.

**Comment by Brimcon** [comment]
I believe /tg/ has merged new voice lines to the Vox so maybe going off that base may help.

**Comment by ZeroNetAlpha** [comment]
It's the same voice, just lower quality

**Comment by Brimcon** [comment]
Heads up, still testmerged. Not sure if that's intentional or not.

**Pull request closed without merging**
