### PR TITLE
Adds the Stabilized Tritium Switchblade for the Uplink

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Adds the new Stabilized Tritium Switchblade, fresh from the Syndicate's Research and Development team! This blade utilizes advanced miniaturized containment fields to sheathe a blade comprised of pure, superchilled Tritium. Blade deals direct poison damage and a little bit of burn; useful if you want a quick and relatively quiet takedown. Careful, its sound is somewhat distinct, and the containment is fragile! **Keep it away from EMPs!**

## Why It's Good For The Game
Adds more unique weaponry for the uplink of the energy variety! Makes you wonder less what the Syndicate is doing with all those tanks of Plasma gas. Also, allows silent poison takedowns. Strong weapon, so its price _should_ reflect that (but I am by no means attached to it).

## Changelog
:cl:
add: The Stabilized Tritium Switchblade, a new stealth weapon designed to do direct poison damage. Keep it away from EMPs if you value low cancer rates and not being dead.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Ignore the weird Github fuckery in that first commit, im not sure why its there but it shouldn't hurt anything.

**Comment by YakumoChen** [comment]
How many edaggers do we need in the uplink exactly?

**Comment by Linzolle** [comment]
its a neat idea but I'm not sure if we really need to add more melee weapons to the uplink

**Comment by Arturlang** [comment]
Seems a pretty neat thing, not many viable weapons that actually deal toxin damage.

**Comment by necromanceranne** [comment]
So if I emp it I have an embedding bomb.

**Comment by ShadeAware** [comment]
> 
> 
> So if I emp it I have an embedding bomb.

It doesn't embed, because how the _fuck_ is a blade made from a gas going to embed itself?

**Comment by Ghommie** [comment]
I'm really, really against adding more items to the traitor uplink unless they prove to be actually quite interesting, which is not the case for this one.

**Pull request closed without merging**
