### PR TITLE
BURGERSTATION 13: A NEW FUCKING HIGH-POP MAP NO ONE FUCKING ASKED FOR

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

A WIP draft of Burgerstation 13. Contains all update related progress to Burgerstation 13 as well as any and all discussion on it relegated to one convenient location.

## Why It's Good For The Game

New maps are nice.

https://cdn.discordapp.com/attachments/161574200581029888/615847319807590410/Burgerstation_Map.png

### Departments
- [x] Engineering (~100%)
- [ ] Atmospherics (~50%)
- [ ] Cargo (~50%)
- [ ] Mining (~50%)
- [x] Medical (~100%)
- [ ] Security (~25%)
- [x] Kitchen (~100%)
- [x] Bar (~100%)
- [x] Theatre (~100%)
- [x] Janitor's Office (~100%)
- [ ] Command (~25%)
- [x] Library (~100%)
- [x] Chapel (~100%)
- [ ] Botany (~75%)
- [x] Robotics (~100%)
- [ ] Science (~75%)

### Milestones
- [ ] Power
- [ ] Lights
- [ ] Distro/waste pipes
- [ ] Disposals
- [ ] Detail
- [ ] Bathrooms
- [ ] Recreation
- [ ] Directional Signs
- [ ] Map

## Changelog
:cl: BurgerBB
add: Added a new shitty map called Burgerstation.
/:cl:

### CODE REVIEW

**Comment by r4d6** [comment]
The only thing I would ask, please make a section so that engineering can so a Tesla/Singulo

**Comment by BurgerLUA** [comment]
> The only thing I would ask, please make a section so that engineering can so a Tesla/Singulo

image

Done.

**Comment by r4d6** [comment]
> > The only thing I would ask, please make a section so that engineering can so a Tesla/Singulo
> 
> image
> 
> Done.

Just thought of something, when the random event that cut power, it is not supposed to cut the power to "important" location I.E. AI sat & SM room, but on other maps, the SM still got its power cut, thus the filters and pumps stopped working, and the SM started delaming.

Maybe double check so that do not happen.

I will also try to be active in my suggestions, and helpful.

**Comment by BurgerLUA** [comment]
> > > The only thing I would ask, please make a section so that engineering can so a Tesla/Singulo
> > 
> > 
> > image
> > Done.
> 
> Just thought of something, when the random event that cut power, it is not supposed to cut the power to "important" location I.E. AI sat & SM room, but on other maps, the SM still got its power cut, thus the filters and pumps stopped working, and the SM started delaming.
> 
> Maybe double check so that do not happen.
> 
> I will also try to be active in my suggestions, and helpful.

The tesla doesn't use power from APCs, but from a direct wire connection so there is no need for this. Also the SM uses pumps that are marked "Critical" which means the filters won't shut off during a power issue.

**Comment by r4d6** [comment]
> The tesla doesn't use power from APCs, but from a direct wire connection so there is no need for this. Also the SM uses pumps that are marked "Critical" which means the filters won't shut off during a power issue.

Then it is a bug with the other maps.

**Comment by Linzolle** [comment]
> 
> 
> > The only thing I would ask, please make a section so that engineering can so a Tesla/Singulo
> 
> image
> 
> Done.

What about a place to put the PA? Perhaps to the left?

**Comment by BurgerLUA** [comment]
I just realised that a Tesla engine requires a particle generator so I made space for one.
image

**Comment by Thalpy** [comment]
A few of the coders and I are working on porting over standard chems to use fermichem mechanics, so if possible could you add a 2nd heater, or let me know how to do so when the time comes?
Also I'm excited! Thank you for making this!

**Comment by BurgerLUA** [comment]
> A few of the coders and I are working on porting over standard chems to use fermichem mechanics, so if possible could you add a 2nd heater, or let me know how to do so when the time comes?

Done 

image

**Comment by YakumoChen** [comment]
The biggest factor for map success is travel time. People HATE having to spend large amounts of time walking to get anywhere. It's probably the number one reason why the mainstay maps are designed as they are. How long does it take to get from security to science?

Keep in mind we already have a high-pop map in Delta that is fairly successful and adding more won't really add much.

Other major map critiques:
-Honestly a lot of spaces are just excessively huge, even for what you would expect to be highpop (80 players, usually). Especially places that are underused. Why does the library need 6 screens of space? Why is the chapel area taking a huge amount of Z level space? Why make the bar so huge? (it also has no tables) Why does every head room have a more secure, luxurious and large space than the actual captain? Do the hallways really need to be four wide? Do maints need to really be three wide? What's the deal with the giant empty space in front of the bridge? You really need to trim a lot of unused fat here. Why does the Toxins launch room need a long, pointless hallway with nothing in it? There is just a ton of map bloat here.
-Speaking of the bridge, it doesn't look secure even in the slightest. The bridge should be one of the most secure spots on the station, it's usually designed for heads to be able to make a hold out or last stand during a revolution and should be a good bunker during nuke ops. The bridge looks pitifully tiny and the adjacent invaluable rooms have no real protection. There's also no head meeting area.
-Don't give the CE an extra supermatter. Just don't.
-AI Upload should not be in the AI chamber. They require separate rooms to function in any sort of balanced environment. Even a legitimate connecting room would be preferable.
-The AI's SMES should be more secure and probably in the AI core chamber itself
-The AI core chamber is probably one of the worst designs I've ever seen. You can just tunnel into the AI from the back without having to face a single turret. Awful.
-AI teleporter room doesn't need to take that much space.
-Why is there an EVA suit on the AI sat?
-Do NOT make anything on station out of bananium. You can make mechs out of that.
-Do not make station floors or walls out of gold or silver, those should be suitably rare because science.
-The clown does not need his own EVA suit.
-You have made a highpop map with only three brig cells. Why?
-...Is that a fucking Greentext in an atmos wall cubby?
-The engine room is excessively designed, honestly.
-Most of maint seems kind of pointless as the tunnels don't really connect to anything. There's also random SMES units everywhere for no reason.

**Comment by BurgerLUA** [comment]
Wew there is a lot to pack in that post.

Most of what you said can be easily counted by saying that this is a WIP map. I mean I've tried my best to make it clear that everything is a work in progress and some things aren't even added yet.

Recreation areas are big for a reason. They're recreation areas and are meant to give people things to do on a larger scale. Engineers can build things if they want with the amount of space given, like the bar and holodeck area is perfect for a ragecage.

4 wide hallways is fine and will not be changed.

The bridge is fine and is about as secure as box.

The CE having an extra supermatter in his office is fine.

AI Upload being in the AI chamber is also fine. If it doesn't work out then it doesn't work out. Most things that occur to the AI usually requires the AI to be carded anyways.

The AI SMES is as secure as it needs to be. It's fine and doesn't need to be in the core.

Fuck your negativity tbh. Not going to address that.

EVA suit on the AI sat is just in case. It's the basic EVA suit and no one except the engineers can really only access it.

Those walls will be fake bananium later.

Gold and silver floors are fine for the QM.

The clown needs their own EVA suit. The clown is one of the most useful roles on the station.

3 brig cells is fine but I might upgrade to one solitary confinement cell if needed.

No. That is not a greentext.

Excessively designed isn't criticism it's just a buzzword.

The only part of maint which is excessive is xenobiology which will be reworked at a later time.

The "random" SMES units are substations. Each department gets their own SMES.

**Comment by Trilbyspaceclone** [comment]
@YakumoChen Toxins can do fussion in that hall, as well as adv bomb mixes
I like the larger toxin area

**Comment by YakumoChen** [comment]
>I will ignore all your criticism because it's negative

Fuck yourself.

-extra sm is not fuxking fine, there's  no coolant set up for it, and it's the kind you can take out and drag in the hallway (meaning fuck you if it's anchored, and fuck you double if it's not)

-Upload needs to be in a place where the AI can't literally hear you coming. Even delta had a way to get in upload plasuably without the AI being alerted.
-fuck off with your dismissive shit. the AI sat is literally designed to be the most secure room on the station. Don't make a bypass that doesn't put you near a single turret or even fucking worse, let's you EMP the thing from two tiles away.
-gold is limited to mining or the vault on every map, it's a big buff to research early they don't need.
-it's not, the design is very stifling to customization and has too many walls and doors.

**Comment by r4d6** [comment]
@YakumoChen 
He could probably replace the SM shard in the CE's office by a "fake" one (Like how he will make fake bananium walls)

I agree completely with the AI shit, just by looking at it, I can see that any monkey with an EVA suit (which he gave the clown one by the way) can just, remove/RCD three windows, and destroy  the AI's SMES,  Also, if he has a RCD, it can RCD the doors, deconstruct the computer, the wall behind it, and then attack the AI directly, all without facing a single turret.

That is a _**huge flaw**_ right there. Even if you can't RCD the high security doors, You can easely deconstruct the windows and the walls.

Another point of view on this ; _**The frickin' clown can destroy the AI almost roundstart**_

**Comment by YakumoChen** [comment]
There should not be spare EVA suits accessible to non-specialized jobs without a good reason. EVA capabilities are a surprisingly major balance concern given a lot of spaces are protected by vacuum, especially high security areas like Vault rooms. You yourself use it to protect head offices (except the captain, bafflingly). Service level jobs should not have free EVA gear. You shouldn't put excessive EVA gear in places like the AI sat (whose access is already limited purely to EVA capable jobs already).
There's an argument to be made there's already a lot of EVA creep and your map makes it doubly worse.

**Comment by BurgerLUA** [comment]
@YakumoChen I addressed all your criticism save for one which was aggressive. Most of what you posted are things I disagree with and I took the time out of my day to explain why I disagree with you.

**Comment by YakumoChen** [comment]
I am fairly certain most of my criticism is going to be the same reasoning against a map merge or general playerbase dislike, but I guess you can have opinions. I've played on TG and they've gone through half a dozen maps that players hated mostly boiling down to "it takes too long to get anywhere" or "it's badly designed" so take that how you will.

Having a bad AI sat will guarantee silicon players will loathe you and your map.

**Comment by BurgerLUA** [comment]
If people don't like a feature it will be changed.

**Comment by YakumoChen** [comment]
Maps are usually only maintained by their creator.

A hostile maintainer is probably going to have Goofvision (tm) and isn't likely to see "disliked features"

**Comment by BurgerLUA** [comment]
Who is being hostile here?

Like I just want to point out that you came in here, gave some criticism, some of it was hostile, some of it was stuff I couldn't really use.

I took the time out of my day to respond to every point you made, explaining myself as to why I disagree with you if that was the case. Some of what you said I agreed with and have made changes, but most of what you said I disagree with it.

You then throw a fit claiming that I'm ignoring all your criticism despite me literally addressing it and conceding on some of the points in the post above.

I then point this out, but you ignore that. I then tell you that I am willing to change features if they are unpopular but you say that's not good enough, call me hostile, then do a callout on goofball.

You are legitimately the most entitled and delusional player I've come across in my 2 years of developing for SS13. Maybe you don't understand this but just because I don't implement an idea you suggest, it doesn't mean I'm not listening to you or ignoring criticism.  Maybe you don't understand this but I'm not going to implement ideas that I don't have any faith in myself.

**Comment by lolman360** [comment]
imagine being hostile

**Comment by YakumoChen** [comment]
From my POV your response post looked more like you were just shooting down all my criticism with "it's fine" or "I don't care". Blowing off my criticism of your AI sat was what really got me mad because it's true, an AI sat that you can kill the AI in without needing to enter the core chamber is the worst possible design you can make. 

Most of your concessions are very minor, like the bananium and xenobio maint, while you blew off the most critical criticism without even bothering to consider balance. You also proceed to meme about the clown, showing further bad faith.

Obviously my response to that is going to be even worse? I'm not sure what you expected. If you are going to make bad maps then you shouldn't expect a healthy response from serious players. 

As I've said, I've seen a ton of bad maps in my time, they don't last. You haven't even addressed the most basic criticism like "how long does it take to get to places?" You don't explain substations or why they're important on your map (compared to every other map without them).  Your map is hard to even take seriously when you more or less put in the OP it's a shitty map nobody asked for. Maybe I shouldn't have bothered in the first place.

**Comment by BurgerLUA** [comment]
The problem here is that you're mistaking disagreement for "blowing off" and I think that's a problem, and an even bigger problem is that you're getting unreasonably upset that I disagreed with you on the AI thing.

I think the AI chamber is fine. It's okay to disagree with me. It's not okay to throw a fit over it.

Consider this: If I was blowing you off I'd just post "you're wrong", not explain myself, and ignore everything else you're saying and not bothering to talk to you past that, but here I am engaging with you, explaining myself to you and engaging you.

**Comment by r4d6** [comment]
I left a good explanation as to why the current AI sat in your map is very bad. As in ; _**The clown can deactivate the AI practically at roundstart**_ kind of bad. He would just need to find some tools, a welding mask, some O2 tanks (None of which are hard to get) and he can space himself, deconstruct a few walls and windows, then honk the AI into submission, or simply destroy it with his tools.
The only difference that would happen between the clown and an assistant, is that the assistant would need to greytide in the EVA Room before going unto the AI sat.

**Comment by BurgerLUA** [comment]
@r4d6 The design of the AI core will remain largely the same but the clown hardsuit will probably be removed.

**Comment by r4d6** [comment]
The problem isn't really that the clown has the hardsuit, it is that literally _anyone with a space suit, a screwdriver and a crowbar can kill the AI without any risk at all_ And the AI can't see them coming.
Deconstruct 3 windows, a SMES, and a single reinforced wall, and then you can smash the AI without facing a single turret.

I recommend removing the room entirely, and after that to lower the two bottom turrets by 1 tile to cover the hole, then you are golden about that part of the AI sat. You can always put the SMES where the console right behind the AI was. So it would be similar to the AI setup on other stations

**Comment by YakumoChen** [comment]
The whole room under the AI isn't needed. You already have FOUR borg chargers in the antechamber and the drone printer is useless since they don't start loaded with metal/glass and the machine is practically impossible for regular crew to get to without heavily triggering the AI.

You never explained the need for substations. It's a bad idea, it needlessly nerfs power sinks.

**Comment by BurgerLUA** [comment]
Again, the AI core is fine. However, the glass window at the back will be removed and a new system of waste will be designed.

**Comment by BurgerLUA** [comment]
@kevinz000 This was a draft PR

**Pull request closed without merging**
