### PR TITLE
cutlery deluxe decluttering

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title
(removes two knives, the four useless trash plates, two glasses, and one shot glass)
## Why It's Good For The Game
if you're buying this you know what you're really buying it for and you know that all this excess junk in it is just to annoy you
## Changelog
:cl:
balance: removed some of the excess stuff in the kitchen cutlery deluxe crate, including the trash plates
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
dont really see the need to remove them some people just want cool cutlery sets

**Comment by Hatterhat** [comment]
alright i could put the knives back in but it was more about "god, what the fuck are these four literal trash items doing in this cargo crate"

**Comment by Hatterhat** [comment]
there are now an equal amount of forks and knives for a complete cutlery set (inb4 no spoons)
still threw away the shitty plates and an excess drinking glass though

**Comment by lolman360** [comment]
`obj/item/sharpener`

who merged this

**Comment by silicons** [comment]
just because people order this for powergame doesn't mean we should encourage it

**Pull request closed without merging**
