### PR TITLE
Cerestation

### PR DESCRIPTION
**Pull request by frontline03**
## About The Pull Request
Adds cerestation to the active rotation.

## Why It's Good For The Game
It's a large map capable of holding a large amount of players on it. Doing events on it aswell is a good idea too.

## Changelog
:cl:
add: Cerestation
add: Cerestation cargo Shuttle
add: new area files
modify: areas.dmi
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Uh, why does this change chat.dm and chems.dm for a map PR? Also, you should probably change the name from Skyrat Cere Station to just CereStation.

**Comment by frontline03** [comment]
Sorry about that mate, The chatDM and Chems DM stuff showed up as a change in the desktop for some reason, didn't think much of it. I think I did change the name of the station to just Cerestation though.

**Comment by frontline03** [comment]
Fixed the json which hadn't been properly updated, sorry again mate.

**Comment by MrJWhit** [comment]
No worries, take your time with the PR. It's better to get things done nicely the first time than to freak out to get it done as soon as possible and make mistakes along the way.

**Comment by frontline03** [comment]
Should I remove the Chat and chem dm's then? In case they do something to the server.

**Comment by MrJWhit** [comment]
Yeah, anything not directly related to the map should get removed, so that would also include necropolis_chests.dm, AutoChangeLog-pr-12835.yml, and AutoChangeLog-pr-12847.yml.

**Comment by frontline03** [comment]
Well shit, travis didn't like me modifying the json.

**Comment by MrJWhit** [comment]
Travis wasn't awake the first time around. These things are weird and complicated.

**Comment by MrJWhit** [comment]
All right, to get a fresh copy of that code, go to here:
https://github.com/Citadel-Station-13/Citadel-Station-13/tree/master/code/controllers/subsystem
Right click chat.dm and then save as, and then throw that file where they were before. You just wiped your copy of the file itself, and by downloading a new copy from the citadel master code, you can make sure it's fully updated.

Do it for necropolis_chests.dm here:
https://github.com/Citadel-Station-13/Citadel-Station-13/tree/master/code/modules/mining/lavaland

And for chems.dm:
https://github.com/Citadel-Station-13/Citadel-Station-13/tree/master/modular_citadel/code/datums/status_effects

There's probably a better solution out there, but this is a hammering a screw in.

**Comment by frontline03** [comment]
That should be them now.

**Comment by frontline03** [comment]
Some stuff is fucking up but when I go to edit it, I see no issue. It's shit repeating itself.

**Comment by LetterN** [comment]
revert chat.dm changes, it looks like some generic github page

**Comment by frontline03** [comment]
I have no idea how to do that.

**Pull request closed without merging**
