### PR TITLE
monkeys now have one braincell more than the average player

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
this adds a new mechanic to monkeys:
they have a 'power level' which starts at 0 and caps at 100 which defines how good they are in terms of the probability they do stuff, and generally values the AI uses, with all their default values being at 0 power, this also defines how often they try to parry attacks (5 to 80% of the time) and how often the parries are perfect (50 to 80%)

their power level is capped at 33 until they drink monkey energy, which makes them aggressive, especially towards other monkeys, and unlocks their limit to 100, monkey energy also increases how fast they learn from a 1x multiplier to a 2.5x multiplier while it's in their system

the level increases by drinking monkey energy at an extremely slow rate, or by attacking things

a power level 100 monkey is still quite easy to put down despite the effort required for it to reach said level

also this primarily affects AI controlled monkeys, player controlled monkeys can't gain power and won't receive the majority of the benefits

also paper frames are way cheaper to craft now because they're awful but they look really nice for making dojos

## Why It's Good For The Game
welcome to monkey fight club this is your host punpun, a power level 84 monkey bokken user

## Changelog
:cl:
add: monkeys have now evolved and can parry attacks, and some have even been seemingly learning through repetitive combat, and medical doctors have evaluated that some of the monkeys have a higher IQ than many of the station's workers
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Can you make this also apply to gorillas for high tier memes

**Comment by timothyteakettle** [comment]
i want to make it apply to gorillas but the issue is that gorillas are already insanely strong and so having a gorilla parry someone would probably be going too far

**Comment by YakumoChen** [comment]
You say that like it's bad

**Comment by YakumoChen** [comment]
Gorillas are arguably underpowered for their TC cost / effort to make

**Comment by timothyteakettle** [comment]
i still really don't think it's a good idea to have a gorilla going around landing perfect parries 'n stuff

**Comment by Ludox235** [comment]
The dawn of the station of the apes.

**Comment by lolman360** [comment]
what is a man but a naked ape

**Comment by silicons** [comment]
travis

**Comment by timothyteakettle** [comment]
will do some fixes to this when i have time

**Comment by Ghommie** [comment]
Also stale.

**Pull request closed without merging**
