### PR TITLE
makes circuit theft admin only

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
circuit analyzers (lets you steal the copypaste code for a circuit) are now adminspawn only

## Why It's Good For The Game
the only thing that somewhat balances circuits is the suggestion that you need to be skilled to use them

## Changelog
:cl:
del: normies can no longer steal circuit codes
/:cl:

### CODE REVIEW

**Comment by Xantholne** [comment]
100% support removing of circuit theft. 

Learn how to make stuff

**Comment by ghost** [comment]
also note: this has no effects on basically anyone right now this just removes potential for use

**Comment by Ghommie** [comment]
Please make sure to not leave this item mapped in any .dmm file.

**Comment by ghost** [comment]
i don't think it's in any but i'll double check

**Comment by ghost** [comment]
post commentary: i was debating removing it from the game entirely, and i didn't get any compiling errors about the analyzer not existing on any map files (when i removed the actual object path) @Ghommie 

i'm assuming here the compiler is smart enough to tell me if there's missing item paths but...


edit: no it does not

**Review by Ghommie — APPROVED** [review]
Now it's ok.

**Comment by RatElemental** [comment]
I'm forced to wonder how anyone is supposed to get the codes for their own circuits now, but removing that seems like it's intentional anyway.

**Pull request merged**
