### PR TITLE
 the pr that removes the erp mechanics

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
but only dicks and breasts losing their mechanical downsides besides bigger sprites

## Why It's Good For The Game
please god 

## Changelog
:cl:
del: cock and breast torture is gone and will no longer make you attack slower and die of blood loss for eating that one sex pill you found in maintenance
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
compiles on local travis is actually broken

**Comment by Putnam3145** [comment]
mmmmeh. These are both totally opt-in right now. I'd prefer adding a "hyper" pref instead of just removing the thing entirely... maybe. I'll think it over and get some other opinions.

**Comment by ghost** [comment]
i don’t like having erp mechanics that have mechanical effects

**Comment by necromanceranne** [comment]
Make sure to check the chems as well. Those have damaging effects from reaching certain sizes.

**Comment by ghost** [comment]
i don't care enough to fix the merge conflicts on a pr that won't get merged

**Pull request closed without merging**
