### PR TITLE
chemical bear trap

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

Chemical bear trap. Does less damage than the regular bear trap but instantly injects 15u of chemicals if the target is injectable.

Piercing and bluespace ones exist, made from piercing and bluespace syringes.

## Why It's Good For The Game

ok honestly it might not be but beartraps are criminally underused

## Changelog
:cl:
add: Chemical beartrap, for when getting your leg caught wasn't already bad enough.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
That crafting requirement seems way too low, it doesn't even have a tool that's needed to make it.

**Comment by lolman360** [comment]
yes it's literally a syringe on a beartrap

also crafting menu bloat bad

**Comment by MrJWhit** [comment]
You're... adding to the crafting menu bloat.

**Comment by lolman360** [comment]
this doesn't use the crafting menu at all

**Comment by silicons** [comment]
memes aside i'm really not sure why we need chemical boobytraps

**Review by silicons — CHANGES_REQUESTED** [review]
admin only it.

**Comment by SmArtKar** [comment]
Too OP. Beartraps are like superior energy bolas and you're making them even deadlier.

**Comment by silicons** [comment]
reopen when fixed

**Pull request closed without merging**
