### PR TITLE
black crayons now have pwr game in them

### PR DESCRIPTION
**Pull request by silicons**
no don't actually merge this

### CODE REVIEW

**Comment by deathride58** [comment]
***OWO***

**Comment by Poojawa** [comment]
Kevinz is the new Goof

**Comment by MimicFaux** [comment]
Code checks out. Approved for merging.

**Review by nik707 — CHANGES_REQUESTED** [review]
not enough pwrgame

**Comment by nik707** [comment]
I'm here with a mop to clean up @kevinz000 's shit

**Pull request closed without merging**
