### PR TITLE
Boop sound effect removal

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Removes the BOOP whenever you boop someone on the nose

## Why It's Good For The Game
Loud noises that don't indicate any useful knowledge to the player

## Changelog
:cl:
del: The crew does not have bikehorn's implanted in their noses anymore.
/:cl:

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
😔

**Comment by bunny232** [comment]
Counter suggestion: make it check if the player is a clown, then it can play the funny noise

**Comment by Detective-Google** [comment]
good pr

**Comment by silicons** [comment]
not particularly a fan.

**Comment by Detective-Google** [comment]
> not particularly a fan.

Putting a bike horn in everyone's face devalues the clown, this shouldn't have been added in the first place.

**Comment by YakumoChen** [comment]
It's not even the same sound

**Comment by MrJWhit** [comment]
I'm not seeing any solid reason to remove it other than "I don't like it".

Which can be counted by "Well I like it".

**Comment by Detective-Google** [comment]
> I'm not seeing any solid reason to remove it other than "I don't like it".
> 
> Which can be counted by "Well I like it".

Democracy time

**Comment by deathride58** [comment]
3 thumbs ups to 8 thumbs downs. i think it's fair to say the community doesn't like this pr

**Comment by bunny232** [comment]
🤷

**Pull request closed without merging**
