### PR TITLE
removes brainwashing from uplinks

### PR DESCRIPTION
**Pull request by Sishen1542**
## About The Pull Request
comments out brainwashing disk from uplinks

## Why It's Good For The Game
quirky funny surgery that is too easily abused by just giving your metafriends the wacky antag status

### CODE REVIEW

**Comment by ghost** [comment]
kinda sucks but fair

**Comment by timothyteakettle** [comment]
brainwashing disk is fine considering only medbay antags have access to it shrug, if you really hate it, bump up the tc price

**Comment by moltoretardo** [comment]
Brainwashing is only used to get metabuddies funny free antag status with you or to erp with it. It’s a good riddance imo.

**Comment by ghost** [comment]
based

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
@TheSpaghetti 
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12973

**Comment by YakumoChen** [comment]
I don't think marginalizing an antag item with "haha funny surgery" is really valid and I dont see a problem with this item.

>but ERP

Is that really a problem?

**Comment by moltoretardo** [comment]
I mean, the problem was already described many time here. People uses the funny surgery to pull their metabuddies in their epic antag round.The only gimmick that comes from it is someone zpowdering and making an army of “you really love me” antags that defend the quirky master. Brainwashing is abusable and if your powerboner comes from getting brainwashed you can always rp it without having a broken feature in the bidiagaem.

**Comment by YakumoChen** [comment]
I imagine its a lot easier to convince your metabuddy to let you do surgery on them then some random guy, the same people are not really going to care if you're antag unless you're out to kill them. If people are doing the same thing to give their buddies antag every round, that's more a player issue that can be reported or tracked.
 Surgery isn't even easy to pull off anyway because citadel doesn't have a pain system or requirement to be asleep to do surgery, which isn't realistic and the victim can just watch what you're doing, making it very hard to unwillingly brainwash.

It seems like there's more systemic problems here that removing the "funny surgery" won't solve, simply band aid, removing a feature because the system is broken is bad faith.

**Comment by Sishen1542** [comment]
cit has a very bad history of handling "player issues"

**Comment by moltoretardo** [comment]
Brainwashing adds nothing of value to a round. Also yes there was some cases of people brainwashing their friends each round, making it so you can ban those people would make the surgery only a ban bait which has no purpose whatsoever. Surgery is also very easy to pull off, you just need one sleepypen with zpowder and mute toxin and a set of tools. Most of fermischem got removed for their fetish contents and weren’t allowed outside of “scening”. I don’t see how brainwashing is any different if not worse.

**Comment by YakumoChen** [comment]
Brainwashing adds plenty to a round, the same way thralling as a bloodsucker does, or the same way abductor objectives can add things. You dont always have to give a "follow everything I say" objective, you just arent being creative around it.

Sleepy pen is not easy to pull off as your target is likely to make a mad dash away as soon as they get pricked, spoiling the attempt. Its terribly messy anyway and they'll remember that far better than what surgery should be like with needing a knockout to do anything, which would make brainwashing much more "natural".

Fermichem largely isn't removed or the purely ERP ones are, brainwashing isn't completely limited to ERP and this is a pretty shitty argument.

**Comment by moltoretardo** [comment]
There was several discussions about removing abductor’s objectives since people hates them. Bloodsuckers also have the same problem as an antag which is to just convert the metabuddies to your cause and wait for power.The matter was already discussed and with tons of drama concerning them for the “am rp antag no attack me me just convert” I do not wish to engage any further on that matter since in my opinion bloodsuckers falls in the bad antag category (only my opinion,don’t bite). 

Now for the sleepy pen part I don’t really see what’s very hard about it. Just make your spicy mix that mute and sleep, guy will dash for what, 10-15 seconds if my memory is exact about zpowder and fall face first. Hooray for you you are a medical officer so just drag him off saying he got a disease or something. Due to me being not that fluent I don’t really understand the last part of that paragraph about natural brainwashing.  

I don’t get where you saw that brainwashing is completely limited to erp in whatever I said and it’s probably my faulty english at fault, but my point is that the mindcontrol chem was exactly the same thing as the brainwashing surgery with a bit more fetish things linked to it. What makes the chem better is that it’s reserved for scening which doesn’t create tons of “funny protect the cult leader with the disk” mini antags.

**Comment by YakumoChen** [comment]
If you are such a bore you cant handle playing up a new random objective to cause some chaos, why are you playing on main? The whole of most rounds is adapting to changing conditions. If you can't adapt to someone's gimmick you should be playing on a more stable roleplay platform.

With the sleepy pen, it forces you to find some way to migitage people remembering IC that you just kidnapped and brainwashed them. (Otherwise they would just scream kidnapping as soon as they woke up and you look suspicious as shit regardless)
 If you had been taking someone in for routine surgery they would more naturally wake up with the brainwashing and it would be bad form to go out you for doing it. 

Of course on cit, nice things like natural surgery and role-playing doesn't appeal to the TG reject powergaming crowd so we don't have it.

I dont see what your last point is. Nothing about the surgery directly leads to ERP unless that was the intention for both players from the onset, which doesn't really make a difference either way and isn't a real reason for removal.

**Comment by moltoretardo** [comment]
Some people hates abductors objectives, you can go tell them how much of a bore they are that isn’t really my problem nor the subject of this pr. Adapting to a changing situation sure can be funny.Having to deal with meteors and repairing the broken stuff, wrestling against threats that requires you to act as a team like when xenos appear sure is awesome. Now adapting to someone’s gimmick, which is in this case the most boring one after murderbone or ai subjugation, can be rather unpleasant for anyone involved except the someone in question. Most of the time, the brainwash will be used for the original “I am your master protect me and do my objectives for me k thx” which is very original and funny. The other time it will be used (i’m repeating myself) to get your funny metabuddies the antag status. There’s no gimmick. It’a just like the same people that rush AA when no sec are around and declare themselves captain syndicate. Oh boy oh boy do I like having to interract with that original gimmick.

Also again for the sleepypen, you can’t really be serious right? You just brainwashed them, you can literally force them to forget the brainwash surgery that just happened by telling them via it. I don’t see the point.

If you think that this community is filled with tg’s reject and that tg has better stuff I don’t see why you have a problem with citadel removing it.You can enjoy it on tg with the better people. Since we are a “TG reject powergaming crowd”, of course we’d like to remove the powergaming antag making disk, it makes sense.

The last point which was the fetish erp bit came from you in your first discussion about erp not being a problem with it. We lose nothing from removing the brainwash except the metabuddying free antag role giving. If people want to erp with brainwash they can do it via the chem. That’s it.

**Comment by YakumoChen** [comment]
Most of the time people will use it for the boring use, some of the time people will use it to help their metabuddies (something the admins should punish), some of the time people will be creative with it and come up with fresh content. Do we need to remove the brainwashing disk for the 90% who use it for a basic purpose? Maybe it's the 50th time you've been brainwashed that way, but maybe it's the first time for them and it's new and fresh. None of this really screams as a reason for removal. Do we remove ebow and esword for the Classic Combo because it's old and tired? No.

Sure you can brainwash them to forget they were kidnapped, but it still isn't natural and still doesn't fit in with how surgery should logically work (since nobody is willing to code forced maluses for conscious and pain-enabled surgery, or port it from skyrat). It'd be like having to finangle with AI laws, people will just look for a way to out you if you've gone out of your way to sleepypen and kidnap them to do your deed.

"It's powergaming" is not really justified or an actual reason to remove it, you're just using it in a buzzword-esque sort of way like how removing things you don't like is "hugbox" and I don't really buy it. Powergaming is a major issue on citadel and it's ironically worse than it was on TG (something kevin has said various times before). 

You lose a creative traitor item from removing the brainwashing disk and I have yet to see any valid reason for removal except "someone could abuse it" or "fuck ERPers"

**Comment by moltoretardo** [comment]
Ebow and esword keep being reworked and there's literally a rule about murderboning now. I haven't seen you mention any "fresh content" we can have from keeping it. Do we need to remove the brainwashing disk for the 90% of the time it is used by metabuddies to gain free traitor rounds which is by the way the main point of this, I'd say yes.

I don't know what's you attachement with the natural part of the surgery. Person A brainwash person B, Person A tells person B to forget everything about the brainwashing and to act like a shield or any other cringy command. Woowee person B is now a new antag that is obligated to help person A or get beaned. The concept of brainwashing is to implant ideas and commands to a person, the surgery can be whatever it is it doesn't matters at all the same problem will remain which is, I'm still repeating, that funny metabuddies will do the "harder" surgery while brainwashing. Even worse, with "realistical" surgery you'll just get sleep'd and brainwashed while trying to fix your bones with absolutely no counter play. Very quirky gameplay.

The powergaming part was just me laughing (quite immature from me but it's the shitposting reflexes I have, pardon me)  at your :
> Of course on cit, nice things like natural surgery and role-playing doesn't appeal to the TG reject powergaming crowd so we don't have it.

because I found it really silly that you'd mention cit being the googoo rejects from tg that powergames when removing that surgery would remove quite a chunk of powergaming. No more CMO with funny helping traitor objectives. Also you used that buzzword first so with the laws of the internet it gave me the right for one (1) free usage of the p-word.

Now to finish, the "creative" traitor item that was never used creatively kinda deserve it's removal. I don't understand how you don't see the real problem we had with the metabuddies brainwashing. It really did happens and it's by the rule so there's no punishing that gets applied. Also I never said "fuck Erpers", I infact can state that the removal won't affect them at all since we have the same thing as a chem that is only usable by them. Don't scramble my words.

So yeah, it's "People abuse it" and "Not good for the bidiagaem".

**Comment by ghost** [comment]
@TheSpaghetti 
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13019

**Comment by MalricB** [comment]
now this is actually based

**Comment by ghost** [comment]
> @TheSpaghetti
> #13019

**salt pr**

**Comment by Ghommie** [comment]
I can't care to read a meaningless wall text debate between two people over this non-issue.

**Pull request closed without merging**
