### PR TITLE
[READY]TGUI 3.0

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Ports basically all the TGUI Next UIs and kills old TGUI, plus the smart asset  cache, And a lot of stuff needed for everything

## Why It's Good For The Game
Old tgui bad, glory to TGUI

## Changelog
:cl:
add: TGUI 3.0 and enables all the UIs, plus the smart asset cache, and all the things required for them
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
:heart:

**Comment by Arturlang** [comment]
Still WIP, putting here so its easier for people to look at

**Comment by Arturlang** [comment]
Fuuucking conflicts

**Comment by Arturlang** [comment]
Travis is dead, compiles now

**Comment by Arturlang** [comment]
As expected, conflict galore...

**Comment by silicons** [comment]
<3

**Comment by LetterN** [comment]
i'l fix the sync issue and slab one

**Comment by Ghommie** [comment]
EoL linter issue on `dead/orbit.dm` (just run dos2unix on the bash CLI to fix), also there seems to be a rogue parenthesis on wildwest.dmm.

**Comment by Arturlang** [comment]
Thanks ghommie, wish i had known the bash CLI had dos2unix by default

**Comment by Arturlang** [comment]
mapdiffbot is dead, F

**Pull request merged**
