### PR TITLE
Nerfs spiders health/speed/damage but buffs spider nurses health by 20

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Makes spiders not better then legit morph/zombie npcs that are easy to spawn in

## Why It's Good For The Game

Makes the game a bit more fair and less steam rolley for spiders

## Changelog
:cl:
tweak: health/speed/damage
/:cl:

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
Spiders already get steamrolled with ease by a crew with more than two braincells. Why nerfing them even farther seems like a good idea is beyond me, especially when the round that triggered the "Spiders op plz nerf" scenario was a salt pr based on a round where the crew did absolutely nothing to stop the spiders, and let them snowball into critical mass.

Nerfing the egg spawns is a far more balanced idea, rather than nerfing all the spiders in full and giving the one type that shouldn't be fighting a buff that it won't need.

**Comment by Trilbyspaceclone** [comment]
@RogueSteampunker Not talking about pvp its for npc v npc.

**Comment by nik707** [comment]
approved the egg spawn PR for now, gonna put this on the backburner to see how it plays out

**Comment by Trilbyspaceclone** [comment]
Its less about the eggs, its what they do compared to other NPCs they are really strong for no reason and can/tend to take out any other NPC you can get out of the spawners. Hell ive seen them take down NPC nukies

**Comment by silicons** [comment]
lack of interest from other maintainers + i'm against this

**Pull request closed without merging**
