### PR TITLE
Syndicate Cruiser Event

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Adds a syndicate cruiser, and all the stuff that it needs.

## Why It's Good For The Game
Currently admin only, basically a nuke ops level threat, but they need to protect their own ship, instead of just going out to wreak havock onstation

## Changelog
:cl:
add: Syndicate cruiser event, admin only for now, ported from https://github.com/tgstation/tgstation/pull/50531
Original idea by WJohnston
/:cl:

Ported from https://github.com/tgstation/tgstation/pull/50531
Original idea by WJohnston

### CODE REVIEW

**Comment by Arturlang** [comment]
Almost done but could really use a review

**Comment by EgorDinamit** [comment]
You should credit WJohnston in both changelog and PR's body for the original design of Starfury and leave a link to PR that I originally made on Tegu Station, or outdated /tg/ version.

**Comment by Arturlang** [comment]
@EgorDinamit couldn't find a proper PR in tegustation but I will credit the TG pr and him

**Comment by Arturlang** [comment]
Wait, why wjohnston? Was he the one who originally made the code for this and you PRed it?

**Comment by Linzolle** [comment]
This seems like a lot of overhead for what's just supposed to be an event PR. (i.e. porting the entire transform component and balloon alerts, only to use them in one place)

**Comment by Arturlang** [comment]
That stuff.is already something we'd want to have anyways for porting stuff down the line @Linzolle

**Comment by Arturlang** [comment]
Though the balloon alerts are best used when you.have them in lots of places, maybe even give them configs to print to chat if the player wants to

**Pull request closed without merging**
