### PR TITLE
Adds lights to box station xenobio! 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Adds 2 lights to hop line so that you can see better around
Removes 1 light do to being close to hop lights
Adds more lights to box station xenobio

## Why It's Good For The Game

We cant see and its rather annoying! Issue ##8530

## Changelog
:cl:
tweak: light places
fix: darnkess
/:cl:

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
image
Why remove these corner decals?

**Comment by Trilbyspaceclone** [comment]
Oh... I dont know why...

**Comment by Trilbyspaceclone** [comment]
***Oh god what have I done?***

**Comment by IronEleven** [comment]
What's the status on this?

**Comment by nik707** [comment]
@deathride58

**Comment by Thalpy** [comment]
Heck I need light

**Pull request closed without merging**
