### PR TITLE
E-Switchblades

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Its basically a lesser esword that deals burns rather then brute
Brand new weapon, a small golden looking switchblade

## Why It's Good For The Game

More options, more fun looking toys and such
Also moved around tons of sprites in the folder so its not impossible to fine anything, shields with shields, ling slings with slings, ect ect

## Changelog
:cl:
add: Gold plated e-daggers have been made for 6tc
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
I don't even know if such a thing could even be considered a switchblade at this point, with the blade generated from the impossibilium that's hardlight and not actually stored in the handle...

Yet, I'm against adding this, pardon the word, crap to the uplink, we already got plenty, I hope you aknowledge.

**Comment by Trilbyspaceclone** [comment]
I would make the case of it being a cheaper esword that fits in boots well still being lethal. Unlike the pen dagger that cant really get any job done and looks rather sus from a meta point unless hidden in the pda/suit. But none the less I do think its worth adding thus not closing the PR yet.

**Comment by necromanceranne** [comment]
Edagger is literally already this. It's just worse because it lacks embedding which is the edagger's main strength. Being a high damage throwing weapon.

**Comment by Trilbyspaceclone** [comment]
Never seen the pen enbed. 
Edaggers are rather shit in melee
These are ment to be a lesser esword that deals burns

**Comment by necromanceranne** [comment]
Edaggers have 100% embed. If they're not embedding, they're bugged. Eswords are the same. A bug causes both to not embed sometimes.

Rather than a blade, why not them it as a concentrated gout of plasma. Sorta like a gas lighter. Either that or tie it into the NEB's since those are the alternative energy blades. How exactly hardlight blades get hot beats me but

**Comment by Trilbyspaceclone** [comment]
Edaggers have pen enbed so 0, 
second, its not a Edagger, its not steath, its not a hold out weapon
third the only plasma Synda has is stollen tanks from agents. 
Lastly light burns people and the NEBs are lava land gear, the one in the uplink is a toy thats been fitted with an energy blade around the plastic shell

**Comment by YakumoChen** [comment]
The pen has embed when the blade is extended.

**Comment by Trilbyspaceclone** [comment]
@YakumoChen 
I have legit NEVER gotten it to enbed,
not even on privet testing.

**Comment by Tupinambis** [comment]
Unnecessary uplink bloat that is basically just another edagger

**Comment by Ghommie** [comment]
What tupinambis said.

**Pull request closed without merging**
