### PR TITLE
Replaces kill once objectives with regular kill objectives wherever I could find them.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

eW huGbOX

## Why It's Good For The Game

We have respawn (In my opinion, we shouldn't, but that's not important right now.) and kill once objectives make no sense. If you have one, you can just ask your target to let you kill him/her once and get greentext. Having to stop your target from getting revived means antags have to actually do antag stuff.

## Changelog
:cl:
del: no more kill once objectives
/:cl:

### CODE REVIEW

**Comment by MacaroniCritter** [comment]
thank you the boringness of "can I kill you" "Ok as long as you revive me" was killing me inside.

**Comment by LordSaladin** [comment]
Honk

**Comment by silicons** [comment]
this won't happen unless we can figure out how we're going to have the medium between "sure you can kill me", and people rushing .357 --> cremator like we've constantly observed when this was a thing

**Comment by dzahlus** [comment]
awful

**Comment by MacaroniCritter** [comment]
> this won't happen unless we can figure out how we're going to have the medium between "sure you can kill me", and people rushing .357 --> cremator like we've constantly observed when this was a thing

admin example: "Hey I know this was your objective but we would really appreciate if you took the time next time to actually try to add something besides a generic mechanical kill."

more unnecessary code fixes for admin policy conflicts.

**Comment by silicons** [comment]
@

**Comment by silicons** [comment]
@Adelphon how do you expect that will happen with cloning being so easy? the easiest way IS going to be killing and spacing/otherwise fully destroying.

the same argument can be made for the current status quo: why are you just letting an antag kill you?

**Comment by silicons** [comment]
(this isn't really about cloning either at this point, given that as long as the brain exists it's able to be revived one way or another)

**Comment by ghost** [comment]
> awful

...why?

**Comment by MacaroniCritter** [comment]
@silicons It takes thirty minutes to respawn compared to twenty or less if you have the possibility of getting revived, also if you respawn as it currently stands you can't be a head or sec-officer( 😠 ). Also my argument is that its perfectly ok to deepspace or cremate someone as long as you didn't just immediately kill them without dialogue or previous interaction, better yet, wouldn't it be really cool if people were skilled enough to kill people without feeling the need to perma remove them and give people the chance of finding their body, like maybe a caveat to the kill objective that said "The body must be kept ungibbed for syndicate identification by the end of the shift."

**Comment by ghost** [comment]
> "The body must be kept ungibbed for syndicate identification by the end of the shift."

I can't code that but I'd be fine with that if someone else did.

**Comment by silicons** [comment]
making it required to keep the body ungibbed will just result in even more (admittedly hilarious) elaborate attempt to win at all costs by making it impossible to find someone's body 

policy is far better written around requiring people to care with killonce, as well as the upcoming policy that flat out forbids antags from one-and-doning objectives and spending the rest of the round erping **consistently** when they roll antag. the entire reason we removed this in the first place is because people rushed it too hard, the only ways i can see this going down if it's readded is either that happens or the antag repeatedly kills one person for the whole round as they are revived again and again until the revival fails. alternatively, antagonist waits until the end to kill them (fun fact we bwoink for that now, it is not permitted to roll antag without actually playing antag).

**Comment by silicons** [comment]
also yes, i put the respawn restriction back on for observers on request because it was quite iffy, to say the least. 
this is citadel some things just won't pan out. i am for the side that i see panning out better at the end of the day, as the harm from someone being boring and eating a bwoink sooner or later when they're observed to never do anything is far less than harm from the behaviors exhibited when objectives aren't killonce.

**Comment by ghost** [comment]
> making it required to keep the body ungibbed will just result in even more (admittedly hilarious) elaborate attempt to win at all costs by making it impossible to find someone's body

...how is that a bad thing?

**Comment by ghost** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13862
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13744
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12796
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12827
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12973
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12451

and finally, the truly classic PR.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13019

Now we can add https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14028 to the list.

**Comment by moltoretardo** [comment]
@Adelphon ` wouldn't it be really cool if people were skilled enough to kill people without feeling the need to perma remove them and give people the chance of finding their body, like maybe a caveat to the kill objective that said "The body must be kept ungibbed for syndicate identification by the end of the shift.`

You know deep down this utopia cannot exist bonko.

**Comment by DeltaFire15** [comment]
No thanks.

**Comment by ghost** [comment]
hurr durr round removal bad

**Pull request closed without merging**
