### PR TITLE
Revert "Little but possibly hella important fixes"""

### PR DESCRIPTION
**Pull request by LetterJay**
Reverts Citadel-Station-13/Citadel-Station-13#286

I need to pull this all off until it's working. Sorry again, Verk.

### CODE REVIEW

**Comment by Verkister** [comment]
put it back but before merging the newest fix.

**Comment by Verkister** [comment]
Actually idk if it's that important. The only unchanged file here is lizard front snout tweak now.

**Comment by LetterJay** [comment]
Does this need to be added back?

**Comment by Verkister** [comment]
well it's just like 8 pixels of change compared to the newer pr so no big deal

**Pull request merged**
