### PR TITLE
FLIGHTSUITS

### PR DESCRIPTION
**Pull request by kevinz-zero-three**
## About The Pull Request

Un-snowflakes ninja suits. Makes them a subtype of a powersuit, the generic powered suit which has a cell and abilities and such. Makes flightsuit a subtype of powersuit. Adds a non-spaceproof exoskeleton, which is also a powersuit.

## Why It's Good For The Game
New features = good. Cleaning up ninja code = good. Impersonating kevin = good. Joke PR = good. Chance of this PR being closed and opened as a serious one on my real profile = 1 (fuck true lolololol)

## Changelog
:cl:
add: Added FLIGHTSUITS
add: Added REAL EXOSKELETONS
del: REMOVES SNOWFLAKE NINJASUIT CODE
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
code: changed some code
refactor: refactored NINJERS
server server op should know i'm cool (mso already does, come on cit hosts)
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
🦍

**Comment by Fractious** [comment]
👀

**Comment by ghost** [comment]
flightsuits? disgusting behavior, kevinz zero three

**Comment by lolman360** [comment]
gee kevin, your mom lets you have TWO accounts?

**Comment by Thalpy** [comment]
What is going on here

**Comment by Arturlang** [comment]
Kevinzs getting memed, methinks

**Pull request closed without merging**
