### PR TITLE
[DO NOT MERGE] the CE hardsuit now prevents the equipped mob from getting dusted

### PR DESCRIPTION
**Pull request by Sishen1542**
what it says on the tin, requested by kev

CE's can now fiddle with the engine with one less thing to worry about

### CODE REVIEW

**Comment by YakumoChen** [comment]
awful idea

**Comment by Thalpy** [comment]
If it resonates with the supermatter crystal, does that mean the CE dusts on contact too?

**Comment by Poojawa** [comment]
This just means people are going to walk around with Supermatter crystals because now there's no potential drawbacks to it.

Don't take suggestions from Kevin. :V

**Comment by Trilbyspaceclone** [comment]
Please dont add it to MASON RIG

**Comment by yourdoom9898** [comment]
Any way to make it so a touch doesn't dust but prolonged contact (drags) do?

**Review by silicons — CHANGES_REQUESTED** [review]
i'd like it to use a mob sm immunity trait via datum trait system instead.
infact add one for dust immunity and one for full immunity, potentially have it do heavy burns if not fully immune.

**Comment by Sishen1542** [comment]
i thought about adding traits after i already slapped this together, yeah
ill see what i can do

**Comment by EgoSumStultus** [comment]
Just don't walk into the supermatter???

**Comment by dzahlus** [comment]
finally i can safely delam the sm for memes without getting dusted by a sudden grav anomaly giving me the good succ right into the crystal :^)

**Comment by Sishen1542** [comment]
okay this is fucked for now, gotta try some new shit

**Comment by silicons** [comment]
also just to let people know I've been considering doing MASONrig this too, but maybe weaker like heavy rad burns on contact or something, but the reason is to allow more close-contact engine fuckery without people being scared of the crystal. I know "just don't touch it 4head" is an argument but sometimes laggy shit happens and you just accidently touch it. If people start dragging crystlas through the halls as their antag gimmick we can revisit this, if the burn damage/etc isn't enough of a discouragement/counter.

**Comment by Trilbyspaceclone** [comment]
im really against the mason having it

**Comment by Tupinambis** [comment]
We already have rad man memes. Let's not take it farther even if it might be funny once or twice.

**Pull request closed without merging**
