### PR TITLE
Adds rooms to Meta, Box, and Delta for sci to play with fusion a but in

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Gives some blank rooms by toxins in each of the maps stated, mostly for them to test small scale cold fusion or other such things.

Each fusion lab has a little to no pipes, wiring or other things to get in the way. Other then at lest 1 scrubber in all and at lest 1 vent to get air close by or in the same room.
Note that delta dosnt have a vent into its room, thats do to the vent outside the room being able to do supple if needed 
Each fusion lab also has 2 scrubbers, and two pumps. Nothing more, nothing less

## Why It's Good For The Game

ATM toxins itself isn't modular at all, once 1 person fucks it its gone, really harder to fix and easy to cluck, but now we make are own custion cold and or hot fusion sets using the never used maints spaces. 

## Changelog
:cl:
add: Fusion labs
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
IDK how to add fusion labs into Puppy and omega, thats why they dont get any*

**Comment by YakumoChen** [comment]
Fusion is really a atmos department does, not science. All this really serves to do is remove the one real thing atmos has to play with and give it to the job that has plenty to do.

**Comment by YakumoChen** [comment]
I'm not sure science has enough actual gas for anything beyond basic fusion either. Atmos is the only department that has enough gas and pipes to do advanced fusion I think. You don't need much more than a burn room for most stuff toxins makes (like bombs, and nothing else)

**Comment by Sishen1542** [comment]
yeah sci does not have enough co2 and plasma to work with, not even counting what you'd need to burn to make trit in the first place

**Comment by Trilbyspaceclone** [comment]
thats why its small fussion, you can still make basics like Bz for xenobio and work down the Misma tree, ect ect. Just gives more room for bomb/fusion testing really.

**Comment by Linzolle** [comment]
Are you talking about _actual fusion_ as in 250 mols of trit with plasma and another gas, or mixing gasses to make other ones like making BZ? Fusion is **not** the same thing as other gas reactions. I feel like I've had this conversation with you before...

**Comment by YakumoChen** [comment]
Xeno should already have their own canister of BZ, assuming my PR to add it was cloned

**Comment by Sishen1542** [comment]
> Xeno should already have their own canister of BZ, assuming my PR to add it was cloned

it was

**Comment by Trilbyspaceclone** [comment]
Bz cold fusion, and you can do some some N02 fussion in sci, as well as plux.
Miasma fusion as well to get greater return rates, this also has room for new toxin sets ect ect

**Comment by YakumoChen** [comment]
Have you actually tested if toxins is capable of this with their default set of cannisters

**Comment by YakumoChen** [comment]
Are any of the gases you listed actually capable of being used for bombs?

Are you sure this isn't a thinly veiled attempt to invalidate Atmospheric Technicians?

**Comment by Trilbyspaceclone** [comment]
From my testing the best way to get miasma is via xenobio, and you get 4 o2 tanks, thus your able to get 22500k fussion temps for No2 with the addion of fussion power from the miasma that burns rather hot. I dont know what your talking about with atmos as they can mass make, well sci can just dabble in it. Learning vs mastering sorta deal

**Comment by YakumoChen** [comment]
If someone was intending to play with fusion why would they choose a job that has very limited gas and pipes over a job that has infinite gas and pipes, though?

Miasma collection is maybe a plus for science but science also doesn't have a monopoly on monkies or corpses and atmos has plenty of building materials and, again, pipes.

**Comment by Trilbyspaceclone** [comment]
People being fearful of fucking up the main pipes, for one.
People wanting to do small scale testes to get better knowings for two
Its sci and were ment to test things for three
And some people dont want to use all the limited o2 we have (As ive done that before)

**Comment by YakumoChen** [comment]
I don't see how that's an argument against atmos? Science has even more limited o2, atmos players who can figure out fusion have probably figured out the absolute basics of the pipe network already, and atmos already has several areas dedicated to or useful for testing fusion.

**Comment by Trilbyspaceclone** [comment]
Its not against atmos is why

**Comment by YakumoChen** [comment]
Consider you are trying to make it so two departments have to compete to do the same thing, instead of letting each one do seperate things

**Comment by Trilbyspaceclone** [comment]
If you want to debate this more please use discord.

**Pull request closed without merging**
