### PR TITLE
Update toylathe.dm

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
## About The Pull Request

Cleans up the autoylathe code, brings it back in line with the current autolathe. Also fixes an issue with the autoylathe not updating it's screen on click.

## Why It's Good For The Game

Bugs are bad for the game and this fixes a bug.

## Changelog
:cl:
tweak: Cleans up autoylathe code and brings it back in line with the regular autolathe.
fix: Fixes autoylathe interface not updating propperly.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
You somehow converted tabs to space, and thus cluttered your PR with unnecessary whitespace changes, so please undo them.

**Comment by ZeroNetAlpha** [comment]
That's an issue I'm having with Atom, in order to make it back to how it was, I'd have to use the built in byond editor or notepad unless I wanted to install something else on my limited storage space.

**Comment by silicons** [comment]
fix your spacing please

**Comment by ZeroNetAlpha** [comment]
That didn't work, hold on.

**Comment by ZeroNetAlpha** [comment]
Okay that did work.

**Comment by ZeroNetAlpha** [comment]
Spacing is fixed.

**Comment by lolman360** [comment]
@ZeroNetAlpha atom settings, autotab off, set tabs to hard only. it'll stop your ws issues. it's under the editor category.

**Comment by ZeroNetAlpha** [comment]
Oh shit, thanks man.

**Review by silicons — APPROVED** [review]

**Pull request merged**
