### PR TITLE
Updates Polychromic Clothing Code, adds new stuff in too

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Added Polychromic Athletic Shorts
imageadd: added greyscaled athletic shorts
tweak: optimized polycloth code, modularized it more
/:cl:

dreamseeker_2017-12-15_11-47-53

This PR optimizes polychromic clothing code and properly documents it to allow anyone to easily add their own RGB clothes. In addition, polychromic athletic shorts have been added.

### CODE REVIEW

**Review by deathride58 — DISMISSED** [review]

**Comment by Michiyamenotehifunana** [comment]
oh so the review becomes outdated because I fixed a typo in the comments for the code

**Comment by Michiyamenotehifunana** [comment]
Looks like I just fucked it up even more.

**Comment by Michiyamenotehifunana** [comment]
Aaaand looks like I fucked it all up even worse.

**Comment by Michiyamenotehifunana** [comment]
ugh, I have no fucking idea what to do now. hooray github for comitting 360 different files when I literally just reverted a specific SHA.

**Comment by deathride58** [comment]
Rebase your branch to fix the 360 extra files, and fix merge conflicts.

**Comment by Michiyamenotehifunana** [comment]
Closed pending unscrewing of _everything_.

**Pull request closed without merging**
