### PR TITLE
[READY] Adds durathread jumpskirts, rolled down jumpsuits and PROBABLY FIXES SPRITES

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

Requested by someone and I had 5 minutes, so. Allows rolling down durathread jumpsuits and construction of durathread jumpskirts.

## Why It's Good For The Game

New clothes = good?

## Changelog
:cl:
add: Added durathread jumpskirt
imageadd: Duraskirt sprites and rolled down jumpsuit sprites.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
i uh, managed to fuck up a 10 line 3 sprite PR.

**Comment by lolman360** [comment]
oh yeah this closes https://github.com/Citadel-Station-13/Citadel-Station-13/issues/9163

**Comment by nik707** [comment]
haha nice conflict

**Comment by lolman360** [comment]
pls no conflict mi amigo github

**Comment by lolman360** [comment]
fixes https://github.com/Citadel-Station-13/Citadel-Station-13/issues/9163

**Review by nik707 — DISMISSED** [review]

**Comment by nik707** [comment]
>686 lines
hello?

**Comment by lolman360** [comment]
@nik707 git thinks i'm making the sheet_types.dm file from scratch, for some reason

**Review by nik707 — APPROVED** [review]
yeah suck my fucking dick travis

**Pull request merged**
