### PR TITLE
makes jacq appear 2 days earlier (27th -> 25th)

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
title

## Why It's Good For The Game
people want it

## Changelog
:cl:
tweak: makes jacq appear 2 days earlier (27th -> 25th)
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
I'd rather not increase the span of this event due to what happened when this was done with another holiday with simillarely broken possibilities (Christmas), since Jac has access to a *lot* of stuff. Access to those kinda things should be only very limitied-time or it runs its course very fast.

**Comment by timothyteakettle** [comment]
huh yeah people just asked for it, no opinion on it personally

**Comment by DeltaFire15** [comment]
Closing this for next halloween since we already have enough Jacq-induced spice going on as is.

**Comment by timothyteakettle** [comment]
yeah that's completely understandable

**Pull request closed without merging**
