### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mufzaal**
Added Code of Conduct adapted from Contributor Covenant v2.0.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
wip: still being worked on
experiment: experimental
tgs: has something to do with tgs
expansion: expands on something
qol: quality of life content
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
This is most likely a bot spamming commits all over the place.

**Comment by SandPoot** [comment]
This **IS** a bot spamming commits all over the place.

**Comment by mufzaal** [comment]
This is not a bot spamming commits, i didn't find a code of conduct here, and so, thought it'd be valid to add one here, if you don't think this is to be here, please feel free to mark this as invalid. I'll look for some other ways I can contribute to this. Thank you.

**Comment by SandPoot** [comment]
Let's see, account created 2 days ago, several other prs (if not direct commits) with pretty much only this content, has not followed the PR placeholder, this repository has content unknown even to the user itself.

**Comment by deathride58** [comment]
Literally just hacktoberfest spam, lol

**Comment by deathride58** [comment]
As for specifics of why it's easy to tell that this is PR is hacktoberfest-related spam:

- This is an 18+ community. The generic copy-paste CoC having no modifications to account for the lewd nature of this community, and the prevalence of proud perverts like myself, exhibits a distinct lack of familiarity with it.
- The PR does not comply with the guidelines outlined in `CONTRIBUTING.md` at all.
- The copy-paste CoC fails to acknowledge the community's global rules, which do apply to the Github. It's also a *lot* softer and roundabout than how the global rules put it ("the following is unacceptable behavior" vs "don't be a dick")
- Upon asking around, there's nobody within the SS13 community who finds your username familiar. This indicates that you probably have no familiarity at all with SS13, and therefore are legitimately unaware of this repo's contents, or the community behind it.
- Your entire PR history is nothing but committing plaintext files; this exact PR has been committed to several different repos with the only thing in common being the hacktoberfest tag. This type of spam is extremely common when hacktoberfest comes around, as there's a lot of maintainers out there who simply don't know any better, and merge simple PRs without much thought. This can be genuinely harmful to FLOSS when those PRs are licensing-related.

If you're just in it for the free shirt, there's far better, and far more productive ways to go about it. Hacktoberfest is a pretty good opportunity to pick up a coding language; matter of fact, learning's the reason it exists in the first place! Most maintainers out there are fairly patient with new faces that exhibit good faith. There's not much harm in picking up Python and hacking away at projects that look neat; it's quite the opposite, in fact! But there is plenty of harm to be had in PRs like this that attempt to propose policies and licensing terms to repos who's maintainers genuinely don't know the implications of it.

**Pull request closed without merging**
