### PR TITLE
Makes damp rags no longer instantly apply chemicals

### PR DESCRIPTION
**Pull request by Kraseo**
## About The Pull Request

see title, rags now need you and your target to stand still before you apply things to them

## Why It's Good For The Game

chem warfare is shit, this coupled with zombie powder is a guaranteed win if you can get your click in and they haven't covered their mouth

## Changelog
:cl:Kraso
balance: Damp rags no longer instantly apply their chemicals onto someone.
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Just cover your mouth 4head
Literally put your internals mask on 5head

**Comment by Kraseo** [comment]
not everyone is going to have their face covered all round long in the off chance someone is going to hit them with the insta-stun chemical, this is a bad faith comment

**Comment by lolman360** [comment]
there are other easier ways to apply chems to people with mouth/head exposed (you can grab a pestsprayer from public garden, empty it out and it works exactly like a spraybottle), why nerf damp rags specifically

i agree with ludox's statement though yeah wear a gasmask or smth or pay the price

**Comment by Kraseo** [comment]
spray bottles and pepperspray apply their chemicals through vapor, not through ingest, meaning they're not literal instant i-win buttons, refer to point above as to why being forced to wear a mask (wow topical) just to avoid chem warfare being applied on you literally instantly is bad for the game

**Comment by rossark** [comment]
Simillar effect can be done with an eye dropper but I guess z powder is the issue here, so why not nerf the chemical instead or make the rags not to ingest(dont think it makes sense either, dont you breathe the stuff on the rag or do people eat it or smth i dunno ive never been abducted) instead of turning them almost unusuable for antagging?

**Comment by Kraseo** [comment]
having to wait 2 seconds is not unusable when grabbing/stunning exists (or your target is alttabbed)

**Pull request merged**
