### PR TITLE
While we're at it let's remove beepsky hating on furries too

### PR DESCRIPTION
**Pull request by silicons**
:clap:

### CODE REVIEW

**Comment by Ragolution** [comment]
sry i can;'t suport this PR really ruined the game for me

**Comment by Trilbyspaceclone** [comment]
:Hugbox: 
Cant say what I do hugbox'es anymore -_-

**Review by Ragolution — APPROVED** [review]

**Review by Ragolution — APPROVED** [review]
I wish my approval meant something. :100:

**Comment by lolman360** [comment]
hugboxed and based pr

**Review by nik707 — APPROVED** [review]

**Pull request merged**
