### PR TITLE
Gives all of kevins characters codersocks

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Don't worry, kevin will always have codersocks now.

## Why It's Good For The Game

Surely it must be hard for kevin to make a character and then give them codersocks. If only there were an easy solution to try and automate that process, and here I am, to help that process along. Don't worry kevin, you don't need to ask anyone else to do this, you can thank me later.

## Changelog
:cl:
tweak: Gives all of kevins characters codersocks
/:cl:

### CODE REVIEW

**Comment by jack-avery** [comment]
speedmerge

**Comment by Mazianni** [comment]
speedmerge

**Comment by YakumoChen** [comment]
Bad PR, does not generate a table underneath his characters on spawn.

**Comment by YakumoChen** [comment]
Optionally I will accept his characters always wear a nodrop, always active Reactive Table Armor

**Comment by MalricB** [comment]
merge asap please

**Comment by ArchieBeepBoop** [comment]
I'm commander archie and this is my favorite PR in citadel.

**Comment by BlueWildrose** [comment]
oh my goodness

**Comment by silicons** [comment]
image

**Pull request closed without merging**
