### PR TITLE
replaces walls with the superior and better version 

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request
old wall bad, new wall good
## Why It's Good For The Game
what if we didn't look like a shitty tg downstream 😳 

## Changelog
:cl:
add:new walls
/:cl:
ported from this pr https://github.com/SunsetStation/SunsetStation/pull/1215
image
image

### CODE REVIEW

**Comment by silicons** [comment]
this is treason

**Comment by Detective-Google** [comment]
> this is treason

your `soul`, hand it over

**Comment by moltoretardo** [comment]
Whats wrong with old walls 😢

**Comment by Tupinambis** [comment]
I'd have to see how they looked in game before I formed an opinion.

**Comment by Higgin** [comment]
old walls, while simple, look less crowded to me and should stick around

**Comment by EmeraldSundisk** [comment]
Can we see an example of how these walls look in action? As in several in a row connected, corners, etc.

**Comment by Detective-Google** [comment]
> Can we see an example of how these walls look in action? As in several in a row connected, corners, etc.

play the game it's been testmerged for days as you can see with the handy little thing that says 'testmerged'

**Comment by lolman360** [comment]
new walls are even more desolate and featureless somehow

**Comment by YakumoChen** [comment]
I liked old walls

**Comment by MrJWhit** [comment]
The rusted walls are the old sprites, I can't support this unless those are changed over, it's too awkward.

**Review by Ghommie — CHANGES_REQUESTED** [review]
You forgot to change the rusted walls too.

**Comment by Detective-Google** [comment]
closed since supposedly wjohn is doing wallsprites which would be way better than these

**Comment by lolman360** [comment]
:crab: UGLY WALL SPRITES PR IS CLOSED :crab:

**Pull request closed without merging**
