### PR TITLE
Adds Citadel Station to the game (finally).  <TEST VERSION>

### PR DESCRIPTION
**Pull request by Leon-Leonardo**
Version 0.9.0

citadel-v0_9

Version 0.9.1

citadel 0 9 1

### CODE REVIEW

**Comment by TalkingCactus** [comment]
Map file needs to be in tgm format using the dmm2tgm tool inside the /tools folder. I also need a high-resolution picture of the entire map either in chunks or by itself.

**Comment by Penguaro** [comment]
It's rather expansive and creative. It may be too spread out for a smaller number of players. And holy crap, the kingdom of engineering is far and wide! I do like the first thing all players see off the shuttle is the CE's glass encased office. Despite my thoughts on size, it's kinda neat for an RP perspective. The only change I would encourage is for the private cabins and that would be to add privacy shutters. Cool beans!

**Comment by TalkingCactus** [comment]
I plan to meticulously rip this map apart

**Comment by TalkingCactus** [comment]
I've done an initial pass on the map and labeled some problem areas.
edit: Github won't accept the link for a direct image, so here's the link itself
[direct link](https://cdn.discordapp.com/attachments/167060301013843968/290587058714705920/mapcriticism.png)

Missed a few things, but we can handle those in the next pass.

**Comment by Leon-Leonardo** [comment]
- Moved secure area closer to main station
- Reconfigured engineering and part of security
- Spaced out maintenance halls and added clutter
- Moved emergency shuttle and departure area about 3-4 tiles left
- Swapped EVA and the CE's office

[https://i.imgur.com/aGmm47J.jpg](url)

**Pull request merged**
