### PR TITLE
Even more engiborg power creep

### PR DESCRIPTION
**Pull request by BlackMajor**
Except not really.

This just changes the engiborg gripper to let it do more, y'know, engineering related things.
Rather unimpactful to rounds.
Thought it was a bit dumb my man engiborg's better at robusting than they are at actual meaningful construction.

-Tank dispenser given an attack_robot, so borgs can actually take tanks out of tank dispensers
-Engiborg holofan changed back to combifan (like it was to begin with before the holofans split)
-Engiborg gripper has an standard use now interacts with held item, dropping items has been moved to AltClick. This was necessary to get held item UI to work.
-Engiborg gripper grab list updated with the following:
All wall frames (newscaster, cameras, apcs, air alarms etc. Yes I'm aware engiborgs could already wall mount these with a screwdriver, but a gripper is so much more intuitive.)
Lights bulbs.
Vending machine restock units.
All /electronics subtypes (air alarm electronics, firelock electronics, etc. Again, yes I'm aware the engiborg has a pseudo circuit, but that doesn't cover all bases, and sometimes you just want to use a circuit that's on the ground, like the airlock electronics that fell out of an airlock that's already programmed)
Conveyer belts and conveyer switches. I'm a mad man I know.

And lastly, the following additions to the gripper are ones I'd like to be argued, since they're the most impactful.
Gas tanks. On the plus side, engiborg can actually put plasma tanks into radiation collectors, downside is bomb assembly (but they can't detonate them).
Material sheets and tiles, as well as use them in-hand. This means they can build walls and floors out of materials, as well as assemble associated material recipes.
Plasma and Plasteel are blacklisted however, unless emagged.
Stock parts. They can already pick them up with their RPED, but the fact they can pick up cells now means they can stick them in chargers first before making chemistry cry about the upgraded cells being empty. No, this does not mean you can take a cell out of your fellow borg.... you can stick one in though.

Let me know if there's any other engineering related items borgos should be allowed to pick up.

### CODE REVIEW

**Comment by Ludox235** [comment]
Speed merge. Now.

**Comment by yourdoom9898** [comment]
In the worst case scenario with the borgs being able to interact with toxins, you'd have a borg release a spicy burn mix can, but that's griefing and a large violation of asimov laws, so is it really a issue?

**Comment by BlackMajor** [comment]
> In the worst case scenario with the borgs being able to interact with toxins, you'd have a borg release a spicy burn mix can, but that's griefing and a large violation of asimov laws, so is it really a issue?

Engiborgs can already do this. They can already do every part of toxins except for putting gas in the handheld tanks.

**Comment by Tupinambis** [comment]
I'm alright with this, a borg should be able to setup the engine when no engineers are available. More toys is good for making a bland round fun.

One thing I'd also like to see is replacing the current engiborg tools with the combined equivalent. (Borg Hand Drill, Borg Jaws of Life.) The list of modules on engiborgs takes up half the damn screen so anything to ease the real estate would be nice.

**Comment by lolman360** [comment]
honestly a single tool module that you could just use ""inhand"" to switch tools (a la goon borgs) would probably be a lot more convinient because you could basically always keep it in borg hotbar with only sacrificing 1 slot instead of the 6 we have rn (screwdriver crowbar wirecutter wrench welder multitool)

**Comment by BlackMajor** [comment]
> honestly a single tool module that you could just use ""inhand"" to switch tools (a la goon borgs) would probably be a lot more convinient because you could basically always keep it in borg hotbar with only sacrificing 1 slot instead of the 6 we have rn (screwdriver crowbar wirecutter wrench welder multitool)

Yeah but hotswapping between hotbar tools ala number keys 1,2,3 is faster than pressing Z then mousing, selecting or cycling through tools to get the one you want.

Example. Screwdriver crowbaring a bunch of windows at once.

Probably not a bad idea to just make them 2 in one tools kinda like jaws of life and hand drills.

**Comment by ghost** [comment]
you already know how i feel about buffing a role so overpowered it has to have specific snowflake hardcounters to make them killable in the first place

**Comment by BlackMajor** [comment]
> you already know how i feel about buffing a role so overpowered it has to have specific snowflake hardcounters to make them killable in the first place

Yeah but none of these changes are combat relevant.

**Comment by Ludox235** [comment]
Blackmajor, you could maybe make them able to take batteries in their gripper to put them in a battery charger. Though you'll have to mess with it so engiborgs can't remove cells from other borgs and basically be better roboticist

**Comment by BlackMajor** [comment]
> Blackmajor, you could maybe make them able to take batteries in their gripper to put them in a battery charger. Though you'll have to mess with it so engiborgs can't remove cells from other borgs and basically be better roboticist

I've wanted to do something like this for a while so they can stick them in APC's/chargers but ah.
Danger zone y'know.
Might do it anyway if I can figure out a reasonable way to override not interacting with borgs.

**Comment by BlackMajor** [comment]
> Blackmajor, you could maybe make them able to take batteries in their gripper to put them in a battery charger. Though you'll have to mess with it so engiborgs can't remove cells from other borgs and basically be better roboticist

I did it.

**Comment by silicons** [comment]
BASED??? BASED????

**Pull request merged**
