### PR TITLE
This is the emergency broadcast system

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
changes malf ai nuke alert

## Why It's Good For The Game
what happened in 1999 please explain. Yeah thats what i thought, have a better sound instead.

## Changelog
:cl:
soundadd: new malf AI nuke alert
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
this is like
the second time someone has tried to replace the AI nuke with this exact sound

by you in fact

and @Ghommie told you no

**Comment by Trilbyspaceclone** [comment]
I thought the AI says 1998, second actives in office

**Comment by dzahlus** [comment]
> this is like
> the second time someone has tried to replace the AI nuke with this exact sound
> 
> by you in fact
> 
> and @Ghommie told you no

he didnt say no, he said he is for it just dont make it earrape. and its not the same sound at all...

**Comment by Ghommie** [comment]
Nice, but it doesn't belong to the AI nuke alert.
EDIT: Actually, the sound is just too long. I have kind of a grudge against long and tedious sound effects since the nuke sound was modified.

**Comment by dzahlus** [comment]
> Nice, but it doesn't belong to the AI nuke alert.
> EDIT: Actually, the sound is just too long. I have kind of a grudge against long and tedious sound effects since the nuke sound was modified.

Edited and made this 10 seconds instead of 32.
https://voca.ro/6C9gaglXJ9R for ease of viewing or well hearing.

**Comment by Ghommie** [comment]
After thinking for a long while, this sound works better for ambience if the volume was lower and an intro and outro fade were added.
But if you are insistent on it, make it exclusive to the medibot announcer version.

**Pull request closed without merging**
