### PR TITLE
removes shrink ray again because "wait, whose idea was to readd this?" (turns out it was shoehorned back in by lettern during the tgui port)

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title
## Why It's Good For The Game
"ah, i deeply enjoy getting all my equipment dropped in a single click," said probably no one ever

it was shoehorned back in with tgui thanks lettern
## Changelog
:cl:
del: Apparently, shrink rays were buyable again, despite a PR having been made a while ago specifically for removing shrink rays. They're gone again.
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
good.

It's not like an antag that's as obnoxious and unfun as old clock cult needs this kind of bullshit to begin with.

**Comment by keronshb** [comment]
Honestly they should be left in.

**Comment by Arturlang** [comment]
Abductors have long needed a ranged tool to deal with security ungas, and this allows them to bot have to kill them with their proper gun, just increase the cooldown and it should not be so bad

**Comment by MrJWhit** [comment]
It also wasn't a documented change.

**Review by DeltaFire15 — APPROVED** [review]
Readding was indeed a undocumented change with the shrinkray having been removed before. Merging this PR.

**Pull request merged**
