### PR TITLE
sensitive soles trait

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

sensitive soles trait
negative trait
you can no longer wear shoes
caltdrops and mousetraps do 1.25x the damage/knockdown unless you also have light step, in which case they do the normal amount

## Why It's Good For The Game

new traits yay!
+ fetish content for lizards (kidding (mostly))

## Changelog
:cl:
add: sensitive soles trait
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
why not just make light step and sensitive soles conflict with each other like the two mood ones?

**Comment by Ghommie** [comment]
This is just an excuse to give yourselves an extra quirk point while being snowlakes.

**Comment by Seris02** [comment]
WELL YOU REFUSED THE POSITIVE ONE DIDN'T YOU

**Comment by silicons** [comment]
y'all need to stop running feet memes into the ground.

**Pull request closed without merging**
