### PR TITLE
GotNS heal adjust - 7.5 per punch up from 3.5

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title.
## Why It's Good For The Game
gotns buff that allows you to outheal the stamina lost from punching people, so as to convey to the user, "yes, you are, in fact, supposed to punch the shit out of dudes very hard and very fast"
## Changelog
:cl:
balance: Gloves of the North Star now heal your stamina a lot better (~210% better) while punching the shit out of people.
/:cl:

### CODE REVIEW

**Review by silicons — CHANGES_REQUESTED** [review]
make it give TRAIT_NO_STAM_PUNCHES

adjust species code to make that a thing

i don't want to run into edge cases of local man found invulnerable to disablers while punching a corpse later

**Comment by kiwedespars** [comment]
-sweats-

**Comment by Ghommie** [comment]
What kevinz said.

**Comment by Hatterhat** [comment]
i forgot this was up but it wouldve been really funny to watch "scarper outheals disablers while punching man to death"

**Pull request closed without merging**
