### PR TITLE
Emergency fix for potential server crashing

### PR DESCRIPTION
**Pull request by silicons**
TG's already crashed multiple times to this.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
Waiting for https://github.com/tgstation/tgstation/pull/25509 to be merged.

**Comment by LetterJay** [comment]
```DM compiler version 510.1346

loading tgstation.mdme

code/modules/clothing/chameleon.dm:463:error: inconsistent indentation

tgstation.mdme.dmb - 1 error, 0 warnings (3/26/17 10:42 am)

mv: cannot stat `tgstation.mdme.dmb': No such file or directory

mv: cannot stat `tgstation.mdme.rsc': No such file or directory

The command "tools/travis/build_byond.sh" exited with 1.```

**Comment by TalkingCactus** [comment]
Compiler needs an update, it seems. Also, is a .mdme normal?

**Comment by LetterJay** [comment]
Me or Travis? I've been compiling on 511 and everything compiles in Travis.

**Comment by TalkingCactus** [comment]
Well, you edited the post so it's no longer there. But, wherever that output was from was outdated.

**Comment by LetterJay** [comment]
No I mean, his last commit failed due to inconsistent indentation

and the .mdme only seems to do so in Travis, so I'd assume it's normal.

**Comment by silicons** [comment]
Fixing this soon

**Pull request merged**
