### PR TITLE
Makes Medsprays align with patches

### PR DESCRIPTION
**Pull request by Poojawa**
Also ensures you can't spray it on ghosts, ai eyes, etc.

## About The Pull Request

Makes med sprays, which were more or less patch code when they were added, perform the same as patches do now. Yes, I double checked to make sure I was using Ghommie's fix too.

## Why It's Good For The Game

It doesn't make sense for a sealed space suit to receive medical attention when syringes, patches, cryo, and most other healing doesn't either. 

## Changelog
:cl:
balance: Med Sprays are now more aligned with patch mechanics
/:cl:

### CODE REVIEW

**Comment by Weblure** [comment]
I'd like to see syringes given the ability to inject through suits as a trade-off for this nerf. That'd give medics a reason to actually ever use syringes for something other than the hecking syringe gun. Hardsuits should still have soft areas around the joints where a needle would penetrate if inserted directly and deliberately, and thus it wouldn't be reality-breaking.

**Comment by Poojawa** [comment]
> I'd like to see syringes given the ability to inject through suits as a trade-off for this nerf. That'd give medics a reason actually ever use syringes for something other than the hecking syringe gun. Hardsuits should still have soft areas around the joints where a needle would penetrate if inserted directly and deliberately, and thus it wouldn't be reality-breaking.

They already do if you print the armor pierce ones

**Comment by Weblure** [comment]
> > I'd like to see syringes given the ability to inject through suits as a trade-off for this nerf. That'd give medics a reason actually ever use syringes for something other than the hecking syringe gun. Hardsuits should still have soft areas around the joints where a needle would penetrate if inserted directly and deliberately, and thus it wouldn't be reality-breaking.
> 
> They already do if you print the armor pierce ones

Oh yeah, I forgot those exist. This looks like a good PR, overall.

**Comment by Poojawa** [comment]
its easy to forget when "better" stuff exists. :P 

As misunderstood as my balance ideas can be, with this fix I've literally brought AP syringes back into a reason for existing other than chem warfare.

**Review by silicons — APPROVED** [review]

**Pull request merged**
