### PR TITLE
Makes the gorilla shuttle emag only

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

why wasn't this done yet

## Why It's Good For The Game

this is not a safe shuttle, why would nt let you buy this? seriously. and every single time, it's ordered by a shitter captain/shitter and ends up killing everyone.

## Changelog
:cl:
tweak: makes gorilla shuttle emag only
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
i thought they replaced the glass with plasma glass so they never break out anyways?

**Comment by silicons** [comment]
ANTI FUN ANTI FUN

**Comment by Seris02** [comment]
they always break out anyway

**Comment by chefferz** [comment]
You can RCD the glass to let them loose. It was intended to be put into emag only, I dont know why it hasn't yet.

**Review by Ghommie — APPROVED** [review]
This is so sad, but it does make sense, yet it's still... sad. CitadelBot, play despacito.

**Pull request merged**
