### PR TITLE
Makes *spin spin the client direction too

### PR DESCRIPTION
**Pull request by Poojawa**
## About The Pull Request

Enhances spin by making it spin client direction as well

## Why It's Good For The Game

5115877a6ca850ffe4fe644a31dffffa

## Changelog
:cl: Poojawa
imageadd: More spin, More fun
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
This will legitimately ruin anyone who has any sort of motion sickness.

**Comment by Weblure** [comment]
image

**Comment by Linzolle** [comment]
I know this is a meme PR but oh my god that would give me a headache

**Comment by silicons** [comment]
sorry my eyes hurt just from looking at that 

would be nice for april fool's tho

**Pull request closed without merging**
