### PR TITLE
Miner loot table shuffle

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Likely will never get merged cuz I made a mining pr about nerfs!
Moves god's eyes to fallen angel loot table thus killing the angel might be more worth wile to do...
Removes spell blade and fire wand from drake/bubble gum table
Replaces fire wand with meat hook
Replaces spell blade with holoparasight
Moves the holoparasight, meat hook and eye of god from spike loot table.

## Why It's Good For The Game

Makes fighting lava land megafuna more worth wile and less of a `Well if get lucky with spikes I can just never deal with that` and more stable rounds without the issue of 4 holo parasights or other things of that sort just via spike drops that are kinda easy to cheese and such.
This also takes out the frankly overly good fire wand aka 1 hit killer
and the also grate spell blade that nuggets people has 50% block iirc and is amazing.

## Changelog
:cl:
del: Removed spell blade, and fire wand from lava land loot tables
balance: Moved god eye from spike loot table to hard spawn collosses fight
balance: Moved holoparasight from spike loot table to bubble gum
balance: Moved magic meat hook from spike loot table to drake
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Kind of disagree with this. First off you're removing a lot of options from the drop tables, thus making it a lot more predictable. 

Second of all, these are basically all the best items in the tendril pool (aside from the cubes, personally), you are really straining a lot of value to deal with the tendrils in the first place. 

Third of all, Colossus already hard spawns with the voice of god AND the anomalous crystal, you are putting a very absurd amount of power on whoever kills the damn thing. The vocal chords are an extremely powerful item and the crystal can have some very good or bad effects depending on what it rolls. A near-guaranteed (in multiples even!) spawn of an item that gives you X-ray Night Vision? are you fucking insane?

This also applies to putting the best tendril drops on megafauna to begin with. You act like you're doing us all a favor but now I just have to kill megafauna for the best tendril loot instead of hoping one RNGs from a chest. What's that? I can get a self-charging taser instead of a limited use fireball wand? Alright, sure.

Fifth of all multiple stands aren't an issue. It's random, requires a (competent) ghost, and multiple people having stands is a joke in itself anyway.

Sixth of all round stability is a bad thing and getting a bunch of varied power is not a real problem. If anything you're making it worse. You have been trying over and over and over again to kick mining in the teeth and it's getting aggravating with each PR.

**Comment by Trilbyspaceclone** [comment]
@YakumoChen Both the holosight deck and meat hook is on RNG 1/3rd picks.


As for the eye of god. It fits with the whole fallen angel wayyyy more then some Rng loot drop
As for "these are the best loot drops" - Colossus is rarely killed, and cords need someone to help instal, the shard you get is RNG and could be amazing or a griffen tool that kills the station, its loot IS the hard spawn cords more so then "Hey maybe this rock will recharge wands?", All and all it does need a loot buff and eye of god is thematic.
`			W.desc = "A pair of strange eyes, said to have been torn from an omniscient creature that used to roam the wastes. There's no real reason to have two, but that isn't stopping you."
`
Yes, replacing the best wizard gear you can get with wizard gear for megafuna is in the goal of the pr.

IMO the stands stacking "joke" is not a funny one, but thats just me.

Glad you like the wand change, the idea behind it is that you pull people to yourself and well on fire to set them ablaze! I thought this is a nice combo thats less One shot dead. 


Ye the loot table is out of 25 now, from 28 down 3 items meaning all other picks are up a bit. Sorry about that, maybe someone can add more loot to it, like maybe bows and arrows that have fancy affects or a fire lash, something more theme-like and fun to use. Also that cult armor is a big yikes but outside the scope imo to change as this is a table shuffle and not a rebalance of the system picks. - Tho I should at some point make the table be a little less rng by allowing you to pull from tables based on what you kill. Maybe killing watcher spikes give you more of the magic stuff well leagon is more of the fun gimmics, golith can be the good armors/weapon mods ect ect

**Comment by YakumoChen** [comment]
What you are doing is basically making the best tendril loot more available, which is somehow actually _worse_ then your intention.

I dont care if its thematic, the voice of God gives you _hard stuns_ and you do not need free guaranteed nightvision xray on top

The colossus is easy to pull and cheese if you are careful, you are just giving a huge amount of power to only the best miners.

**Comment by Trilbyspaceclone** [comment]
>Admits to abusing a AI bug to cheese kill a mega funa and calls it intented
>Legit argument is that you cant kill mega funa easy, thus only rewards the best of the best
>The whole point of the pr is to make it more rewording but not bullshit wiz stuff
image


I think you really need to rethink what your typing/thinking good changes are other then
`This is shit, cuz bugs, and skilled players are a thing`

**Comment by YakumoChen** [comment]
no I'm pretty sure you're literally just restating my point against why this is ever a good idea.

Using cover against the colossus is not a bug. Using cover against any mob AI with only projectile attacks is not a bug, really. Mob AI just isn't super sophisticated. Good players think smart and rewarding them with Xray Nightvision when they're already rewarded with a griff crystal and an at-will AoE hardstun is not the way to go with """""balancing""""" lavaland loot. 

This isn't even taking into consideration using the fucking overpowered crusher which slaughters all the megafauna anyway, your quoted context is really stupid.

The same goes with the rest of the changes and as I said you are making the best lavaland loot even more available, regardless of how rewarding it is. The megafauna already have very rewarding loot as it is (all of them have guaranteed drops of high-powered items on top of whatever is in their chest if they have one) and this only serves to remove it from the RNG pool for frankly vexatious reasons.

**Comment by Trilbyspaceclone** [comment]
How do you be so conflicting on every statement you type back to back to back without noticing it over and over? I wish I could be like you in that, were I dont care about being consistent.

**Comment by YakumoChen** [comment]
I'm pretty consistent in saying this is a terrible idea actually

**Comment by Ghommie** [comment]
I'm not in the mood to consider shuffling paths around an acceptable substitute of actual development.

**Pull request closed without merging**
