### PR TITLE
Updates Science Uniform and Accessories

### PR DESCRIPTION
**Pull request by dapnee**
## About The Pull Request

Updates scientist uniform, lab coat, and shoes. Sprites by Enu, Demonic Mistress#9383

## Why It's Good For The Game

They look sleeker. 

## Changelog
:cl:
imageadd: new toxin's uniform and accessories
imagedel: old toxin's uniform and accessories
/:cl:

### CODE REVIEW

**Comment by dapnee** [comment]
oh boy

**Comment by Linzolle** [comment]
don't forget digitigrade icons.

**Comment by Tupinambis** [comment]
I wish people would put images of sprite changes in PRs

**Comment by Poojawa** [comment]
> I wish people would put images of sprite changes in PRs

click 'checks' then click the sprites

**Comment by dapnee** [comment]
Right, there's digitrade taken care of.

**Comment by Ghommie** [comment]
More conflicts, I'm sorry for ya.

**Comment by dapnee** [comment]
I swear ghommie.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
