### PR TITLE
Removed (an)aphrodisiacs.

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

Removed crocin, hexacrocin, camphor and hexacamphor from the game, editing things that required them to require something else.

## Why It's Good For The Game

I get the impetus to have mechanics relating to ERP in a roleplaying framework, I really do, and I know intimately what these mechanics are for, how they're used, and why people enjoy them. I joined this server partially because I wanted to see exactly how people utilize the ERP mechanics therein--it was a new concept to me--and I found that the answer is... not good. 

Essentially, the mechanics were too "automatic". It was too easy to _unintentionally_ wander about, at full mast, pointing at people with your member, or whatever. And I _did_ fix this, by making that sort of thing _strictly_ manual... with one exception.

And that exception is the worst exception of them all, because unlike the rest, it's something that can happen by accident, with no consent. **Chemicals are simply incompatible with proper consent rules.** The way chemicals are, in Space Station 13, is explicitly designed in its entirety to be something you can administer surreptitiously, to slip into food or drinks or put into smoke machines or force feed people or syringe gun into them. They are, in other words, primarily a combat mechanic. It doesn't help that until recently the flavor text of crocin _implied you ought to spike peoples' drinks with it_ ("tastes like strawberry roofies"). This _was_ fixed, but isn't exactly a good sign.

Crocin's presence in community workings is, from what I've seen, almost entirely in muddying the waters on whether or not someone's behavior is _clearly_ unacceptable. Walking around naked? Could be a variety of reasons for that, maybe they just got cloned and had to flee, and so on. Walking around naked... and aroused? Should be an auto-punish, but you get the occasional "oh, I wanted to see what hexacrocin does", which I usually take on good faith... and just makes me question what place hexacrocin has.

Again, I understand what it's for. I have _used_ it for its intended purpose. But I look at all those times, and I all I can think is that I could've just typed it out, and that so much trouble could be avoided by just... not giving people this easy way to accidentally break the rules.

## Changelog
:cl:
del: (Hexa)crocin
del: (Hexa)camphor
/:cl:

### CODE REVIEW

**Comment by bunny232** [comment]
yes mechanical erp be gone

**Comment by ghost** [comment]
based

**Comment by lolman360** [comment]
putnam doing god's work

**Comment by KeRSedChaplain** [comment]
o7

**Comment by moltoretardo** [comment]
Speedmerge

**Pull request merged**
