### PR TITLE
head of staff (including QM/excluding captain) lockers now have a single coin

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game
it's pretty hard to get coins if you don't have maint access or the assistants speedrun them before you
now the heads can give their favorite employee a coin for the department vendors

## Changelog
:cl:
add: heads lockers have a coin now
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
not something i'll lose sleep over but i don't like this

**Comment by Trilbyspaceclone** [comment]
```
A coin to ya Commander

**Comment by Tupinambis** [comment]
We don't need heads of staff rushing insuls every round. A hard no from me.

**Comment by ghost** [comment]
idk they'd need to beat the other heads and assistants to get the gloves

**Comment by davidchan13** [comment]
Y tho

**Comment by Ghommie** [comment]
Sadly this only enhances potential issues with head of staff lockers being filled to the brim and beyond, and that's already a thing for the captain's, mind you.

**Pull request closed without merging**
