### PR TITLE
Increasing passive point generation to 1900 due to the increase of tech costs

### PR DESCRIPTION
**Pull request by jakeramsay007**
:cl: RealDonaldTrump
tweak: Tweaked passive point regen up to 1900 due to increasing tech costs.
/:cl:

### CODE REVIEW

**Review by deathride58 — APPROVED** [review]

**Comment by Poojawa** [comment]
Won't be needed with #5787

**Comment by yourdoom9898** [comment]
Will still be needed after #5787 to make techwebs bearable and able to be completed without praying to a higher power that you have a competent engineer to make it so you can do the basic function of your job

**Comment by Poojawa** [comment]
Sounds like a player issue, not gameplay.

**Comment by Knightfall5** [comment]
Sounds like a developer ignoring the players issue.

**Comment by JogBoba** [comment]
It’s still needed due to the increased point cost of the nodes, especially the huge upfront cost increase.

**Comment by Iamgoofball** [comment]
>increase tech costs to delay people purchasing everything
>immediately bump up the free point gen to counter this

tenor

**Comment by jakeramsay007** [comment]
@Iamgoofball The point generation here was lowered to 1200, which is over twice the time required for research on /tg/

**Comment by Knightfall5** [comment]
Basically that. It was lowered to 1200 before the increased costs upstream, so we were double nerfed and it's too much.

**Comment by silicons** [comment]
@Iamgoofball tg has it set to 36somethingsomething on accoutn of not enough ways to generate points.

**Comment by Poojawa** [comment]
So uh, point generation hasn't been an issue from what I've seen in terms of the Tesla Engine's reworks. I'mma call this unneeded.

**Pull request closed without merging**
