### PR TITLE
Added a config to disallow unreadied players from voting on modes

### PR DESCRIPTION
**Pull request by Putnam3145**
…rytellers

## About The Pull Request

See title. It's getting ridiculous.

## Why It's Good For The Game

Modes work based on readied up players. Therefore, players who are not readied up might not reasonably have a say in the mode. Simple as.

## Changelog
:cl:
add: Config to keep unreadied players from mode voting
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
I knew this day would come eventually. What a shame.

**Comment by moltoretardo** [comment]
Does it count observers?

**Comment by MrJWhit** [comment]
An observer is not a readied player, so, no.

**Comment by dzahlus** [comment]
I'm against this but to be real honest here, It is needed with the citadel playerbase

**Pull request merged**
