### PR TITLE
Really fancy resprites

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

This PR resprites some stuff. Credits to Aurora Station, Bay Station and TG Station for the sprites

The following stuff was resprited:
Syringes, Wallets, Lockboxes, Leather Satchels, Secure, medical and common Briefcases
Cleanbots, Floorbots, Waterbots, Honkbots
Claymores, DNA injectors, Implanters(and implant cases) and Pride Hammer

## Why It's Good For The Game

New sprites are good

## Changelog
:cl:
imageadd: Resprited some stuff
/:cl:

### CODE REVIEW

**Comment by LetterN** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14275/checks?check_run_id=1941036013

**Comment by timothyteakettle** [comment]
can you list what sprites you changed please

**Comment by SmArtKar** [comment]
> can you list what sprites you changed please

Done

**Comment by MrJWhit** [comment]
I'm not a fan of the syringes and the cleanbot, they don't fit the overall aesthetic of our artstyle. The cleanbot perspective is way too high in comparison to everything else, and the syringe... maybe they look better in-game, but, they seem too fancy of syringes for what we use in ss13.

Also, it looks like the wallet lost some sprites, is that intentional?

**Comment by timothyteakettle** [comment]
not a fan of new bot sprites

**Comment by keronshb** [comment]
I'm not a fan of any of these really.

The storage stuff (briefcases, etc) look worse and more plain, wallet too.  They also lose a lot of dimension.

**Comment by Tupinambis** [comment]
Do not like the syringes or containers at all.

Cleanbot isn't good either, and most of the other bots are kinda like, yeah they are consistent with newer sprites but eh the old ones have charm.

New implant stuff looks sick though.

**Comment by necromanceranne** [comment]
You're porting over the claymore and hammer icon sprites but not even bothering with their inhands or slot sprites?

**Pull request closed without merging**
