### PR TITLE
Updates inventory plates

### PR DESCRIPTION
**Pull request by CameronWoof**
## About The Pull Request

Updates inventory plates to conform better with the midnight UI. Will probably make other UI schemes look better, too, even if it doesn't match exactly. 

https://cdn.discordapp.com/attachments/336748540690825216/604243710447976448/unknown.png

## Why It's Good For The Game

They look pretty and more pretty more better. May not be to everyone's taste, so yell really loud if it's not.

## Changelog
:cl:
tweak: Altered the icons for inventory backplates. Sleek! Stylish! New!
/:cl:

### CODE REVIEW

**Comment by IronEleven** [comment]
I don't like the idea of losing the transparency of the inventory plates, especially if you have two rows of items.

**Comment by CameronWoof** [comment]
Transparency's easy to fix if that's the prevailing opinion.

**Comment by CameronWoof** [comment]
Increased transparency for gameplay purposes. https://cdn.discordapp.com/attachments/336748540690825216/604243710447976448/unknown.png

**Review by silicons — CHANGES_REQUESTED** [review]
bit more transparency please, I second Kamikaze that it's quite painful to play without it.

**Review by silicons — APPROVED** [review]

**Pull request merged**
