### PR TITLE
Ports traitor codeword highlighting

### PR DESCRIPTION
**Pull request by Arturlang**
Traitor codewords are highlighted, blue for phrases, red for responses.
:cl:
add: Traitor codewords are now highlighted for traitors.
/:cl:
Fixed version. Ported from TG

### CODE REVIEW

**Comment by Arturlang** [comment]
Re-opening and closing since it seemed like travis died. Which sadly did not work.

**Review by deathride58 — APPROVED** [review]
@kevinz000 please give this a look-over

**Comment by silicons** [comment]
@Arturlang is this a port from tgcode because this pr worries me a bit codewise.

**Comment by Arturlang** [comment]
It is a port from TGcode. Should I uh, change stuff if its not good? Forgot to say it was a port, fixed it in the pull description. Though yes it is worrying to me too due to what ive had to change.

**Comment by Arturlang** [comment]
A testmerge may be wise to see if there are bugs

**Pull request merged**
