### PR TITLE
Adds Knot Modules for most Dogborgs

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Gives knot modules to dogborgs. Knot modules are enabled for all dog-frame options, except for the borgi which gets it when emagged. The sprites are my own.

## Why It's Good For The Game

Knot modules are the #1 requested feature for Citadel Station. I think this PR would seriously benefit from dogborg players as it gives them something to do on code green.

image

## Changelog
:cl: BurgerBB
add: Adds knot modules.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Absolute madness. Speedmerge. :joy:

**Comment by Linzolle** [comment]
I kind of expected them to be able to be used as really shitty handcuffs but guess not

**Comment by deathride58** [comment]
How do I ban someone from github itself

**Comment by silicons** [comment]
no thank you

**Pull request closed without merging**
