### PR TITLE
Add dwarves as a round-start race

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
This update the config in the repo and inform everyone if a headmin decide to add dwarves as a roundstart race

## Why It's Good For The Game
1. Dorf
2. Wouldn't it suck if we bugged a headmin to add them in, but everyone who made a fork or copied the repo need to change the config themselves?

This does not affect the game at all since the actual config that matter are only accessible/modifiable by headmins, so technically you could bug the headmins to change the config to add them in, but then you wouldn't get any trace that they are now available as a roundstart race.

## Changelog
:cl:
config: Made dwarves into a roundstart races
/:cl:

### CODE REVIEW

**Comment by bunny232** [comment]
would need some sort of debuff to counteract the small size

**Comment by r4d6** [comment]
They already die if the area around them is too filthy and they need to drink to stay alive

**Comment by ghost** [comment]
what do dwarves do?

**Comment by r4d6** [comment]
Get drunk, puke because there is too much filth, are smol, always have a beard, even the girls, need to be drunk or they die.

**Review by silicons — APPROVED** [review]

**Pull request merged**
