### PR TITLE
Adds previously un-added polychromic clothes to loadout

### PR DESCRIPTION
**Pull request by izzyinbox**
:cl: izzyinbox
add: Added more polychromic uniforms to the loadout
/:cl:

This adds in a couple of polychromic uniforms that are available in game but aren't part of the loadout (skirt, button-up, and jumpsuit) ~~as well as adds a few uniforms that aren't available yet (pleated skirt, tank top, panties)~~, all at the standard cost for the previously existing polychromic loadout items. ~~Also adds the polychromic cloak for an expensive 5 loadout points!~~

### CODE REVIEW

**Comment by LetterJay** [comment]
These are more than likely going to be added to the donator tier list

**Comment by izzyinbox** [comment]
The skirt, button-up shirt, and jumpsuit are already available in most maps in lockers, so shall I reduce it to just those items?

**Comment by izzyinbox** [comment]
@LetterJay I've reduced the added loadout options to only the polychromic clothes that are available on the maps.

**Review by deathride58 — APPROVED** [review]
Can be merged with Jay's approval

**Comment by nik707** [comment]
@LetterJay If you don't approve these changes by EOD today I'm gonna close this for the time being.

**Pull request closed without merging**
