### PR TITLE
Drone Satellites! Automatic Drone Factories for Ghosts!

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Adds a drone satellite to all 4 stations that are currently in rotation. They feature an automatic drone maker, materials, and a spring loaded launcher to launch drones to the station. Each station has a slightly different configuration (sadly had issues getting screencaps)

Box: North of security, a larger satellite with a monitoring room and separate solars.
Meta/Pubby: East side of station, smallest configuration that contains the essentials.
Delta: West of engineering, a large and cozy ship for drones and humanoids alike. Doesn't move, but it looks cool.

## Why It's Good For The Game

Ghosts have no 100% consistent role to pick from, and drones are one solution to the problem, especially for players that just want to do engineering/janitorial stuff. In essence, this gives the default round start options of either the RP heavy pAI or the mechanic focused drone, both of which have minimal effect on the round but can still be fun to play.

The drone satellite should be cozy and a good "social hub" to encourage drones to interact with each other and hopefully discourage them from interacting with living affairs. It is also just a good place to spruce up or expand.

## Changelog
:cl: Tupinambis
add: Automatic drone manufacturing satellites to every station.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Does it have a ghost catcher?

**Comment by Tupinambis** [comment]
> Does it have a ghost catcher?

I am not even sure that is a feature on this codebase. Drones ping players about their creation and you can click on them at any time to become one though, so that shouldn't matter. The conveyor belts are mostly just there for flavor.

**Comment by KathrinBailey** [comment]
I'm not really on board with the idea of trying to keep drones in their own satellite, I like the idea, buuuut:
• The satellites are massive, they're much larger than necessary.
• Roundstart drones aren't really necessary, it would be much better to have something like Ashwalkers or Charlie Station to be 100% chance.
• By utilising R4D6's random engine stuff, you can make the drone bases different.
• Having this as a space ruin so the drones are capable of making it to the station would serve the purpose of not messing with the station more.
• Makes robotics even more useless, they now don't even have to do anything, drones will probably get annoyed be the lack of posibrains and print some themselves.

**Comment by MrJWhit** [comment]
I'm for this change. 
1. I think the satellite size is fine, it's slightly big, but it's also off in the corner where nobody can see it.
2. I'm also pro ashwalkers or charlie station being a 100% chance, we can chew gum and walk at the same time. There are quite a few rounds where the spawner menu just shows nothing at all.
3. Random bases are good, but not really the point of this PR.
4. There already is a "drone repair station" ghost role, that's the soviet station.
5. Drones should absolutely /not/ be printing posibrains in the first place. Technically they can print them, but touching one and dragging it over to a borg body is hard against their rules.

My biggest worry is that their sat could be looted for materials, but it's a pretty limited amount so it shouldn't be a problem. Also, I saw that cheeky fix on Box, nice.

**Comment by Tupinambis** [comment]
Drones are supposed to assist on the facility in which they were created. I also like the idea of having a bit more stuff in SPACE around the SPACE STATION that isn't off the z-level. Obviously there is a risk of overdoing it but I don't think the syndie shuttle should be more limited from these additions.

As well, a roboticists clicking a drone button isn't really content.

Maintainer man, please let me know if this is going to be approved so I may resolve conflicts as needed.

**Comment by silicons** [comment]
There's a reason we don't have roundstart drones in most cases.
They should be something science has to make. They have enough of an impact that I don't frankly care that people aren't having "consistent ghost roles". The game is centered on actually playing the main game, not on ghost roles and people observing for them, especially when it comes to this.
Against this.

**Comment by davidchan13** [comment]
Just make a drone shell crate cargo can order I'd they don't have faith in engineering?

**Comment by Putnam3145** [comment]
ghost dojo is a "consistent ghost role" and it's basically impotent for a *good reason* actually

**Comment by Tupinambis** [comment]
My issue is honestly that of there not being really any GAMEPLAY options for ghosts. Ghost bar/dojo is nice for talking with other people and for dicking around a bit, but if you actually want to do ss13 stuff you are kinda out of luck. Are there any other alternatives that I could consider to make instead for ghost roles?

**Comment by Ghommie** [comment]
Uh, pretty cool for drones to have their own ground, but this isn't fairly configurable and really not that much automatic. I would help you with a remake if I have time later.

**Pull request closed without merging**
