### PR TITLE
Paramed office on box + Surgery remodel

### PR DESCRIPTION
**Pull request by Chiirno**
## About The Pull Request
 
This pull request remodels Box Stations surgery room, adds a surgical storage room, and shrinks Starboard Emergency Storage and Morgue with a Paramedic's office.

Before:
image
 

After:
image

 
Operating Room has effectively turned into two operating theaters with a waiting lobby below it, containing three beds with IVs.
To the right two wheelchairs were added, the station has no replacements for paraplegics.
To the left some of maintenance was turned into a surgery storage room, where the blood crate, prosthetic crate, and blood bank were moved. Moreover a limb generator was added.
 

Before:
image
 

After:
image

 
 

 
## Why It's Good For The Game

To begin, the original layout for surgery had medical staff re-organizing and rebuilding it at the start of nearly every round.
It was a mess to deal with and got severely clogged up when a surgeon had more than themselves and the patient in the room.
For similar reasons a lot of the clutter that was previous in the operating room has been moved to the storage. No longer will the fridge be blocked by two crates.
The paramedics office was added to give them a home base, near the main hallways as well as close to maintenance. With the hope that they'll take a more proactive position in medical while not contributing much traffic in medbay itself. The closet is standard medical access but contains a paramedic jumpsuit, skirt, vest, pinpointer and crew monitor, as well as a defib, gloves, and medical headset.
The paramedic EVA suit would allow the paramedic to fetch people in space or decompressed areas, rather than having engineers play medical or begging the CMO to play paramedic or to hand over their hardsuit.
 

 
## Changelog
:cl:
add: Paramedics office and Surgery Storage Room
tweak: Remodeled the surgery room, as well as shrunk Morgue and Starboard Emergency Storage.
Fiddled with some areas for better map edit clarity and fixed one runtime in Vacant Office A.
imageadd: Added the paramedic closet sprite, a paramedic colored medical3 closet.
code: Added a paramedic closet, which is the standard medical3 closet with their suit, a pinpointer, and a crew monitor added.
/:cl:

Big thanks to @TripleShades who remodeled the surgery room, shrunk the morgue, and managed a lot of the maintenance paraphernalia (The big chunk of the PR, really) as well as @MrJWhit who helped us with the pipe and cable layout.

### CODE REVIEW

**Comment by lolman360** [comment]
in the storage the air can is blocked by the heater/tank

**Comment by Chiirno** [comment]
Yes I realize this.

**Comment by MrJWhit** [comment]
> in the storage the air can is blocked by the heater/tank

get gud

**Comment by lolman360** [comment]
the office can be 3x3 do they REALLY need 2 tables
emergency storage > paramedics

**Comment by MrJWhit** [comment]
Pure boxes for rooms are bad, rectangles are better. Not ideal, but, better. A 3x3 is a lot worse than a 4x3

**Comment by TripleShades** [comment]
> the office can be 3x3 do they REALLY need 2 tables
> emergency storage > paramedics

Here's one of the variants we tried before moving ahead, if that helps any. [Image](https://cdn.discordapp.com/attachments/336748540690825216/790818205148250112/unknown.png)

**Comment by lolman360** [comment]
i dont see any problem with it

**Comment by keronshb** [comment]
Is that a health monitoring console?  I don't think we should have another one so readily accessible on station.

**Comment by Chiirno** [comment]
It's a crew monitoring console yea. I don't think it's that exclusive a piece of machinery, anyone who wants one can rather easily print one or hop over the table in medbay. 
This one at the very least is locked behind a reinforced window.
I also don't consider getting a snapshot of where people might be if they maxed out their sensors to be that strong either, as antags have a lot more options than breaking into a decently well-trafficked part of the station.

**Pull request merged**
