### PR TITLE
Adds a new traitor item, Motivation (Part 1)

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

This adds the katana called **Motivation** to the game.  It has ranged projectiles called Judgement Cuts.

Due to how advantageous this is, it's 20tc with no discount.

Part 1 because I plan on adding one for wizards and special wizard spells at a later date.

Special thanks to Dzahlus who provided the firing and hit sounds for it.  Please go to him for all of your sound needs!

## Why It's Good For The Game

More references are interesting and having more variety for traitors is nice.

## Changelog
:cl:
add: Adds motivation and adds it to the uplink
add: Adds Judgement Cut projectiles
add: Adds Judgement Cut hit effects and firing effects.
soundadd: added sounds for the firing and hit sounds of Judgement Cuts, created by @dzahlus
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
Pull my merge trigger

**Comment by Tupinambis** [comment]
Seems a tad too memey for a traitor, and we've had a lot of memey additions as is. It'd fit much better as a wizard exclusive item.

It doesn't really make sense for traitors to basically have magic weapons, because a katana that shoots "judgement cuts" is incredibly fantastical.

**Comment by keronshb** [comment]
> 
> 
> Seems a tad too memey for a traitor, and we've had a lot of memey additions as is. It'd fit much better as a wizard exclusive item.
> 
> It doesn't really make sense for traitors to basically have magic weapons, because a katana that shoots "judgement cuts" is incredibly fantastical.

Eldritch Affairs, His Grace, a giant comical nutcracker, holoparas, and epitaph aren't incredibly fantastical?

**Comment by YakumoChen** [comment]
Cult and Grace are thematic items for the chaplain, and make a fine amount of sense for them. 
The nutcracker is Citadel exclusive and is not really seen much, no comment.
Holoparasites have actual basis in the item (they're nano machines or something)
Epitaph is a really shitty meme that shouldnt have been merged, probably.

**Comment by YakumoChen** [comment]
We already _have_ a sword that shoots beams in the game as a wizard item, and traitors have a multitude of swords in the uplink already, I dont see a niche for this that isnt filled.

**Comment by dzahlus** [comment]
> Seems a tad too memey for a traitor, and we've had a lot of memey additions as is. It'd fit much better as a wizard exclusive item.
> 
> It doesn't really make sense for traitors to basically have magic weapons, because a katana that shoots "judgement cuts" is incredibly fantastical.



> Cult and Grace are thematic items for the chaplain, and make a fine amount of sense for them.
> The nutcracker is Citadel exclusive and is not really seen much, no comment.
> Holoparasites have actual basis in the item (they're nano machines or something)
> Epitaph is a really shitty meme that shouldnt have been merged, probably.

We have 18 different sounds for pred_digest, lavaland loot that is literal magic, and a bunch more of strange shit, I'm not sure how any of these make any sense, so yeah why not this.

There literally nothing wrong with meme items, antags are boring 90% of the time.

**Comment by moltoretardo** [comment]
There’s literally tons of memey references. The sneak implant is literally a MGS box that turns you invisible and trying to remember the basic of cqc is also one. The Ripley is a reference to the alien movie, miner dogborg is a reference to metal gear rising, stunbatons from half-life, hulk from...hulk. The whole game is filled with funnies and I don’t think a sword referencing funny pizza guys will doom it all. The only problem that can arise would be someone murderboning with it to sate his primal needs but that is also possible by just buying a pistol and going to town on low pop aka a community problem.

**Comment by ghost** [comment]
would be cool if this was a role restricted item that wasn't for the chaplain so some other roles can have some unique fun

shaft miners because of flavortext, assistants (if you know you know), chef?? (big knife), just throwing some ideas out

**Comment by keronshb** [comment]
> 
> 
> would be cool if this was a role restricted item that wasn't for the chaplain so some other roles can have some unique fun
> 
> shaft miners because of flavortext, assistants (if you know you know), chef?? (big knife), just throwing some ideas out

I was thinking of locking it to the Curator.

**Comment by Detective-Google** [comment]
powerful weapons need to have unique inhand sprites to make them more identifiable, but regardless of that chen sums it up pretty well

**Comment by kiwedespars** [comment]
when

**Comment by DeltaFire15** [comment]
Merge conflicting
~~also someone should review this sometime, scream~~

**Pull request merged**
