### PR TITLE
Heavy nerfs to plasma cutters

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Plasma cutters have less flat disarm 
Plasma cutter more balanced as a welder tool
:cl: optional name here
balance: Made nerfs to cutters
/:cl:

[why]
Rather op and a meta meme

### CODE REVIEW

**Comment by RogueSteampunker** [comment]
I can kinda see where you might go with the sharp bit, even though if you're in an envviornment where those cutters are actually gonna be effective damage dealers, you're in the wrong place. But why suddenly making them useless to weld anything?

**Comment by Trilbyspaceclone** [comment]
@RogueSteampunker Their not really meant to be a better welder. They also dont take any charge when welding.

**Review by silicons — CHANGES_REQUESTED** [review]
at most:
make welding take chrage
reduce max charge
reduce the amount plasma ore/bars charge

but otherwise this is fine as of right now and nerfing stuff over stuff over a year ago when it isn't an actual issue isn't advantageous. this isn't broken overpowered. it's staying as is other than the above as of current until there's an actual issue.

**Comment by Useroth** [comment]
Plascutter dismemeberment has to stay, imo. It's a hard reference to where the ss13 plascutters even came from originally.

**Comment by silicons** [comment]
unnecessary change to something that isn't broken and still nerfing projectile damage for no reason.

**Pull request closed without merging**
