### PR TITLE
adds tax fraud to the pride station names because fuck you

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

joke PR

## Why It's Good For The Game

Funny™

## Changelog
:cl:
add: tax fraud pride
/:cl:

### CODE REVIEW

**Comment by TheEaterOfBeans** [comment]
wait I should probably add context

**Comment by kiwedespars** [comment]
i love it

**Comment by TheEaterOfBeans** [comment]
h36kripi06721

**Comment by bunny232** [comment]
gitban any%

**Comment by TheEaterOfBeans** [comment]
this is a joke PR and if it gets merged I will
uh
okay I won't actually do anything

**Pull request closed without merging**
