### PR TITLE
graffiti artist midround antag

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
it fails linters because of some dumb tgui thing

the antagonist name: graffiti artist

the antagonist's equipment:
burgundy suit
weak wheely heelies (move delay is 1.4 instead of 0)
offbrand tackler gloves
polychromic canvas cloak
regular red beret

they have a conjure spell that allows them to summon and unsummon their primary tool, the spraycan of life which allows them to spraypaint various objects

this has some limitations:
objects require paint to be created with varying costs
the artist only has 100 maximum paint
paint regenerates 3 per tick (about 2 seconds)
you cannot spray more than one trap per tile to avoid stacking
you cannot create things if structures are in the way (i.e. tables/walls/etc), you need a surface/turf to actually spray on

the things you can spray are divided into: traps, mobs, structures, equipment

the traps are the following:
arrow: throws whoever steps on it one tile in the arrow's direction, costs 5 paint
splatter: slips whoever steps on it, costs 10 paint
firedanger: sets whoever steps on it on fire, costs 30 paint
bigheart: heals the artist 0.2 brute/burn/tox every 0.2 seconds, if someone else stands on it, it does 0.2 brute per 0.2 seconds, costs 100 paint

the mobs are the following:
stickman: close to the regular stickmen you find in the paper ruin, costs 20 paint
carp: close to the regular carp you find in space, costs 35 paint
slime: similar to slimes you find in science, costs 35 paint
monster: a edited version of the blank body mob

structures:
table: self explanatory, it's a table, costs 20 paint
barricade: again, self explanatory, like the wooden barricade, costs 25 paint

equipment:
20 force claymore that can't block and has 50 AP: 100 paint
12 force throwing star that doesn't embed, just paints what it hits: 25 paint
regular toolbox: 25 paint

in upfront combat they're not strong (you have to use the UI to switch between paint types), but with enough preparation, they should be fairly difficult to fight

while the things they spraypaint such as mobs and structures are 'hollow' they're actually filled with alpha 1 pixels so they can be clicked

the antagonist's three objectives:
1. "Vandalize the station with your art."
2. "Leave some crew alive to appreciate your art so that the Wizard Federation's art department can return to its former glory."
3. standard escape alive objective

## Why It's Good For The Game
a fun, slightly chaotic, midround

## Changelog
:cl:
add: new graffiti artist midround antagonist, the things they spray from their spraycan act like real objects
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
Sounds funny and original

**Comment by YakumoChen** [comment]
can mops and such clean them up or are they not treated as grafitti

**Comment by ghost** [comment]
janitor saves the day from the dastardly antag

**Comment by YakumoChen** [comment]
would be kind of dumb if a janiborg could completely shut down the antag though just by rolling over mobs

**Comment by timothyteakettle** [comment]
scrap what i said before, it seems fairly weak so ill just let janitors clean the traps up that they graffiti

**Comment by YakumoChen** [comment]
Are you going to provide a list of things it can do?

**Comment by timothyteakettle** [comment]
i'm going to fill the description out fully to explain everything it can do, its objectives, and its limitations

**Comment by YakumoChen** [comment]
Give them the tagger trait for flavor

**Comment by YakumoChen** [comment]
And maybe crayon runes that work like cult teleport runes?

**Comment by timothyteakettle** [comment]
crayon runes that work like cult ones would be neat yeah

**Comment by timothyteakettle** [comment]
alright i'll reopen this once i have mops doing more damage, and water/space-cleaner spraying on the mobs hurting them

**Comment by timothyteakettle** [comment]
reopening this because i have more time to sort it out now, want a review, and not too sure on the direction i wish to take it

**Comment by timothyteakettle** [comment]
given up on waiting for maintainers to look at this

**Pull request closed without merging**
