### PR TITLE
Code stuffs + more framework for cargo rework cuz atomic prs are good

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Magic vender is now MAGIC PROOF as well as more MRP friendly slogans
***Made all of the crafting into different files for easyer viewing and placement of more*** Kinda like cooking and such
Moves banners into main crafting folders.
## Why It's Good For The Game

its a pain to look through and add to the repices file as its gotten really unorganized so the mini files are to help with that. 

Magic armor on the vender is a joke but the removal of LRP slogans are not

## Changelog
:cl:
add: New book - Unused
code: organized files
/:cl:

### CODE REVIEW

**Comment by nik707** [comment]
what all does this rely on

**Comment by KrabSpider** [comment]
@nik707 Only a coin/dollar, inserted into your department Nutrimax. 

@trilbyspaceclone However, why not just flat out reduce the actual inventory space of durathread items and instead make the production armaments only available through Credible Threads? I'm not even trying to confront you, I'm just curious.

**Comment by Trilbyspaceclone** [comment]
Its do to the coming rework of cargo, dura gear will be worth a lot.

**Comment by silicons** [comment]
i don't see why this needs to be restricted

**Comment by silicons** [comment]
also i do not like passing prs just because "it will be integrated in the future" unless there's a very clear design document that's been approved. you can change it later if it's for cargo rework along with why and what part.

**Comment by Trilbyspaceclone** [comment]
This is waiting on the mini-gun PR

**Review by silicons — APPROVED** [review]

**Pull request merged**
