### PR TITLE
adds cat meteors

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
## About The Pull Request

People shorten "catastrophic meteors" to "cat meteors", so I
kind of had to do this.

Oh, also, the cat meteor event has the same announcement as carp, because fuck you.

## Why It's Good For The Game

it isn't
this is a joke PR
what do you want me to say?

## Changelog
:cl:
add: cat meteors
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
alright that's pretty funny

**Comment by TheEaterOfBeans** [comment]
testing this in localhost tomorrow, it's 1 am here so I can't test it now
edit: it is now almost 3 am, please kill me

**Comment by keronshb** [comment]
We need more wacky SS13 humor on Cit and this is it.

**Comment by TheEaterOfBeans** [comment]
uuuuuuuuuuuhhhh well the meteors themselves work now but the event doesn't do anything

**Comment by TheEaterOfBeans** [comment]
ok, after some testing, I have figured out that
either this breaks _all_ meteors or meteors just
don't work in localhost

**Comment by TheEaterOfBeans** [comment]
...why did you merge this? It doesn't work.

**Pull request merged**
