### PR TITLE
porting "Split Travis shell scripts by job" and "Remove unneeded import from travis python script" with the power of patches. Also DreamChecker.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
tgstation PR #44594, #44845 and #44966, this time using some amateur git patching magic instead of copy paste. I'm curious to see if travis will react the same this time and commit sudoku.

## Why It's Good For The Game
Nobody will ever bother to update travis otherwise.

## Changelog
Nope.

### CODE REVIEW

**Comment by Ghommie** [comment]
Good news: The thing works.
Bad news: Holy cows, The repository is far from being dreamchecker compatible thanks to bad quality control. I'll have to make a PR to fix all those shitcode issues.

**Comment by AffectedArc07** [comment]
@Ghommie we did this downstream in a semi compatible manner, see the following PRs.

These ones made dreamchecker not shit itself
https://github.com/KeplerStation/KeplerStation/pull/336
https://github.com/KeplerStation/KeplerStation/pull/421
https://github.com/KeplerStation/KeplerStation/pull/423
https://github.com/KeplerStation/KeplerStation/pull/567

This one tweaked our travis run, adding dreamchecker and a few other optimisations
https://github.com/KeplerStation/KeplerStation/pull/377

**Comment by Ghommie** [comment]
Yep, I have looked at those PRs already and I'll proceed to port them (Minus 377, which is more or less what I have done so far) later, thanks.

**Review by Putnam3145 — APPROVED** [review]

**Comment by Putnam3145** [comment]
let's tear off this bandage

**Pull request merged**
