### PR TITLE
Makes brass tools look better*

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

    Old   ------------------------------------------------  New
image

Legit just resprites brass tools keeping bronze the same
## Why It's Good For The Game

Looks nicer

## Changelog
:cl:
imageadd: redid brass tools to look better*
/:cl:

### CODE REVIEW

**Comment by cebutris** [comment]
I like the premise of this PR to make the brass tools visually unique, but as it stands, most of them are just slight differences for the sake of being different.

**Comment by nik707** [comment]
Toss up a vote sometime, cus sprite changes get people bitching

**Comment by Trilbyspaceclone** [comment]
Diff bots broken, sprites work fine

**Comment by Trilbyspaceclone** [comment]
image
The people have spoken

**Review by nik707 — APPROVED** [review]

**Comment by Trilbyspaceclone** [comment]
God damn it bot

**Review by silicons — APPROVED** [review]

**Pull request merged**
