### PR TITLE
citrp security cameras

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

image

## Why It's Good For The Game

soul bad

## Changelog
:cl:
add: new camera sprites
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
The EMP'd effect seems a lot harder to notice with the newer cameras.

**Comment by lolman360** [comment]
soulless. no.

**Comment by Tupinambis** [comment]
I straight up just dislike the sprite soul aside. The current camera sprite was based on the system shock cameras. (The entirety of AI was inspired by system shock really) and have an instantly recognizable and easy to read appearance.

This just looks like one of those cameras you'd find on the ceiling at a target and it's bland.

**Comment by keronshb** [comment]
No thanks, please leave the exadv cameras.

**Comment by YakumoChen** [comment]
Awful, somehow even harder to look for than regular cameras. System shock reference good.

**Comment by silicons** [comment]
too negatively received and we aren't exactly using vorestation's art style

**Pull request closed without merging**
