### PR TITLE
Ports Oracle UI framework, and updates UI for paper and disposal bins.

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Ports https://github.com/KeplerStation/KeplerStation/pull/514 with some additional fixes.

## Why It's Good For The Game
tgui man bad

## Changelog
:cl: Alonefromhell
add: Ported Oracle UI, a framework for self-updating and neat UI's
refactor: Paper now uses OUI
refactor: Bins now use OUI
/:cl:

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
There's no need to put it in modular_citadel, since modularity is no longer necessary here, and something as major as a UI system is something that should be as close as possible to the core files as possible to ensure it doesnt override things it isnt supposed to

**Comment by Linzolle** [comment]
aight I'll try to move it then

**Comment by Linzolle** [comment]
oh no what did I even DO

**Review by deathride58 — APPROVED** [review]
Remind me later and I'll work some magic to replace more TGUI interfaces with OUI interfaces

**Comment by lolman360** [comment]
tgui > oui

**Comment by silicons** [comment]
OUI > TGUI

**Comment by AffectedArc07** [comment]
Having all the TGUI --> OUI changes being sent downstream is gonna be beautiful

**Pull request merged**
