### PR TITLE
drake armor goliath resistance

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title
## Why It's Good For The Game
making the ash drake armor more of an upgrade compared to the starter suits
## Changelog
:cl:
tweak: Ash Drake armor now has goliath resistance, same as the Exo-suit.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
powercreep. Drake armor is already incredibly good, it doesnt need to be even better.

**Comment by Linzolle** [comment]
is this a salt pr

**Comment by Hatterhat** [comment]
idea thought up on a whim:
"what if the drake armor was still literally better than any of the roundstart suits"

**Comment by Poojawa** [comment]
good change. always kinda silly that you roundstart had superior gear compared to something that takes effort to get.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
