### PR TITLE
Makes the Space Hotel Booze Mate, not need access to use

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Rarely used, and rather annoying to have to hack, even as a hotel person.
:cl: optional name here
fix: No longer will hotel person have to hack their own vender
/:cl:

[why]
No one can use it at the hotel without hacking or if they somehow get a bar access ID

### CODE REVIEW

**Comment by Poojawa** [comment]
change the access to hotel access ???

**Comment by Trilbyspaceclone** [comment]
@Poojawa Hotel access isnt a thing

**Comment by Poojawa** [comment]
Yes it is, it's called 200. 

Give them ID cards with access 200 and 201 (maint) on them, and it's fixed.

https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/code/game/objects/structures/ghost_role_spawners.dm#L306

**Review by deathride58 — CHANGES_REQUESTED** [review]
What pooj said. If hotel people lack hotel access, then that's a problem with the ghost role, not with the machines inside the ruin.

**Pull request closed without merging**
