### PR TITLE
Ports a significant amount of the tg cybernetic organ code + more

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Ports the vast majority of the current cybernetic organ code from /tg/station, which includes changes that were first outlined and trends set in this pr https://github.com/tgstation/tgstation/pull/48714 but also all followup from that PR onwards. There were a lot of prs.

Includes some additional adjustments to cyber organs. These aren't ports.

Cyberhearts Tier 3 injects you with 5 units of atropine instead of just epinephrine. While a damn good heal, atropine isn't _quite_ good enough on its own to survive through repeat attacks/environmental damage. It will definitely save you in some instances, and absolutely save you if you happened to have multiple organ failures due to an emp, if only keeping you above crit.

Cyberlungs Tier 3 makes it immensely difficult to affect you with most basic toxic gases, while also allowing you to breath minimal amounts of oxygen in order to survive. Next best thing to having internals!

Cyberlivers at a basic level are a lot worse than tg's, but scale upwards to being on par with current with upgraded.

## Why It's Good For The Game

If you're getting your organs replaced, a single emp probably shouldn't instantly kill you. With this, it requires checking for severity and adjusting the effects of the organ failure based on that severity. Some of these effects are still very, very severe, like the 10 second cardiac arrest of a severely emp'd heart, but you may survive all the same.

The downsides of the cyberorgans continue to exist in that you're one emp away from having a very bad time and will need to get your organs swapped out, but their benefits will hopefully outweigh those downsides.

## Changelog
:cl:
add: Basic cybernetic organs: they're worse than organic! Basic stomachs, hearts, lungs and livers! For when you hate someone enough to not bother harvesting organs from a monkeyhuman!
add: Cybernetic organs have been adjusted into three tiers: 1 (basic), 2 (standard, better than organic) and 3 (absolutely better than organic but expensive to print)
add: Cybernetic organs that are emp'd instead suffer different effects based on the severity of the emp. The bigger the emp, the worse the effect is.
add: Rather than outright bricking, severely emp'd cyberorgans degrade over time very quickly, requiring replacement in the near future.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
catgirls truly do carry main dev

**Comment by DeltaFire15** [comment]
Be aware our EMPcode is currently adjusted to work on a scale from 0 (nothing) to 100 (very strong) instead of explicitly 1 (strong) and 2 (weak)

**Comment by necromanceranne** [comment]
> Be aware our EMPcode is currently adjusted to work on a scale from 0 (nothing) to 100 (very strong) instead of explicitly 1 (strong) and 2 (weak)

Ah bugger, I'll have to redo it then. Thanks for the heads up.

**Comment by necromanceranne** [comment]
fixed for now

**Comment by TheEaterOfBeans** [comment]
I'm just happy that this finally adds **cybernetic stomachs**.

**Pull request merged**
