### PR TITLE
Makes Traitor AIs have 'kill once' objectives instead of 'assassinate'

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
Title. Changes their assassinate objectives for kill once ones.

## Why It's Good For The Game
Seems good for AIs to also not have to roundremove folk.

## Changelog
:cl:
tweak: AIs now only have to kill people once instead of permanently.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Changeloooooooog.

**Comment by Linzolle** [comment]
pls fix line endings (thats prob what that is)

**Comment by DeltaFire15** [comment]
> pls fix line endings (thats prob what that is)

Yeah I'll look into it soonish, should be fine to keep testmerged till then.

**Comment by DeltaFire15** [comment]
This works, no more changed other file.

**Pull request merged**
