### PR TITLE
Locks most lavaland crafting to ashwalker only

### PR DESCRIPTION
**Pull request by chefferz**
Locks most bone items/talismans to where only ashwalkers can craft this.
Tested and working (on local server)

Allows someone to still craft the following items:

Skull Codpiece
Skull Helmet
Goliath Cloak
Ash Drake Armor
Bonfire
Mushroom Bowl
Goliath Bone Oar
Goliath Hide Boat
Spike Head

Restricts the following items:

Bone Armor
Bone Talisman
Bone Bracers
Bone Satchel
Bone Dagger
Bone Spear
Bone Axe

Actually makes it to where negotiating with ashwalkers might be beneficial!

Below shows the example. On the left is what everyone can craft, on the right is what an ashwalker can craft.

### CODE REVIEW

**Comment by ghost** [comment]
i said make an ahelp not make a pr 4hed 😂 

also yeah definitely a salt pr and not even implemented into something fun like a recipe book or a ruin or similar
and also kinda hacky and should preferably only use one learn proc and group them all under a variable or something similar

**Comment by Hatterhat** [comment]
salt pr

**Comment by Detective-Google** [comment]
salt pr

**Comment by ShadeAware** [comment]
Salt PR

**Comment by Kraseo** [comment]
salt pr

**Comment by BonniePandora** [comment]
>Didn't update the bounties to remove the restricted items from the usual roll
Aight then
Also
Salt PR

**Comment by chefferz** [comment]
> 
> 
> > Didn't update the bounties to remove the restricted items from the usual roll
> > Aight then
> > Also
> > Salt PR

You mean having to trade ashwalkers for potential bounties?

**Comment by ghost** [comment]
ok let me reiterate how badly this is implemented
1) does everything in ugly individual procs (probably more fault of actual procs)
2) doesn't have a method of removing it if they stop being an ashwalker (minor issue but still relevant if it's supposed to be limited to them like all other race-locked abilities outside of vampire bat form which is a bug)
3) rng-reliant and no way to get it (ie a recipe book) and also relies on ghosts wanting to play ashwalker and also relies on said ghosts wanting to help miners while playing the antag designed to kill a bunch of miners
4) fixed
5) is also a salt pr
6) is inconsistent in the fact it removes some parts of gear sets and not other parts from the same set of gear
7) doesn't buff the gear to make it actually viable to be limited to only lavaland

**Comment by BonniePandora** [comment]
> 
> You mean having to trade ashwalkers for potential bounties?

What, the salt PR remark? Nah, that was aimed more to the fact you never dropped the armour yeh silly goose

Also, trading? With primitives? Whilst part of a megacorp? As if, just cull them all and harvest their bones! /s-but-also-not-/s
For real though, ashies don't spawn too oftem compared to how regularly the bone axe/daggers bounty shows up
So you're effectively denying cargo at least one bounty every 3 shifts out of 5, if my arbitrary maths rounded up right.

**Comment by chefferz** [comment]
> 
> 
> > You mean having to trade ashwalkers for potential bounties?
> 
> What, the salt PR remark? Nah, that was aimed more to the fact you never dropped the armour yeh silly goose
> 
> Also, trading? With primitives? Whilst part of a megacorp? As if, just cull them all and harvest their bones! /s-but-also-not-/s
> For real though, ashies don't spawn too oftem compared to how regularly the bone axe/daggers bounty shows up
> So you're effectively denying cargo at least one bounty every 3 shifts out of 5, if my arbitrary maths rounded up right.

Updated bounties for removal.

**Comment by chefferz** [comment]
> 
> 
> ok let me reiterate how badly this is implemented
> 
>     1. does everything individual procs
> 
>     2. doesn't have a method of removing it if they stop being an ashwalker
> 
>     3. rng-reliant and no way to get it (ie a recipe book) and also relies on ghosts wanting to play ashwalker and also relies on ghosts wanting to help miners while playing the ghost antag
> 
>     4. can cuck cargo bounties
> 
>     5. is also a salt pr
> 
>     6. is inconsistent in the fact it removes some parts of gear sets and not other parts from the same set of gear
> 
>     7. doesn't buff the gear to make it actually viable to be limited

Why on earth would this need a buff?

The bone axe does 23 force.
An actual fire axe, _of which there are only two in every station_, do 24 force.

**Comment by Putnam3145** [comment]
> does everything individual procs

unironically i was the one who suggested this. how do you propose doing it?

> doesn't have a method of removing it if they stop being an ashwalker

minds are generated per-mob? i don't see how they could stop being an ashwalker.

> doesn't buff the gear to make it actually viable to be limited

>literal fire axes-1

>limited to two

>this one is limited and thus needs buffed

??

**Comment by deathride58** [comment]
>limiting HEAD PIKES of all things

literally why

**Comment by Trilbyspaceclone** [comment]
Lava land vet and golems are kinda screwd over by this. As well as beach bumbs/hermis downstream

**Comment by chefferz** [comment]
> 
> 
> > limiting HEAD PIKES of all things
> 
> literally why

Because of their primitive nature falling under the scope of tribal, and just a general discussion with numerous people what would constitute as "ashwalker".. 

Never really have seen head pikes ever on station, as well. No problem removing it from the pool if it's that big of an issue.

**Comment by SectoidDan** [comment]
Let crew make head spikes, sticking nuke op heads on spears on the bridge is kino.
Bone knives are actually pretty neat to have if you're a miner or something but the point about trading is well taken. In conjunction with making the ashwalker camp a static spawn this is actually not bad.
Adding a way for other people to learn how to make these things would be nice.

**Comment by deathride58** [comment]
@chefferz Then that confirms my suspicion that this PR was made in bad faith. Heads on spikes are something that's been very prevalent in world history, and the symbol very frequently appears in works of fiction to signify the de-civilization of an otherwise civilized society (ever read lord of the flies?). Removing a very basic symbol solely because "it seems like ashwalker aesthetic" shows a very distinct lack of actual thought put into the PR.

Since you provided no explanation or justification at all to any of the other changes in this PR, I have no choice but to assume that the same exact reason you gave for restricting head pikes applies to all of the crafting recipes you're restricting in this PR. I cannot think of a good reason to restrict these recipes to ashwalkers since they require access to lavaland (read: only lavaland ghost roles, gulag'd prisoners, and miners can reliably access them), and are outclassed by everything aboard the station anyhow (only exception being the bone spear).

**Comment by chefferz** [comment]
> 
> 
> @chefferz Then that confirms my suspicion that this PR was made in bad faith. Heads on spikes are something that's been very prevalent in world history, and the symbol very frequently appears in works of fiction to signify the de-civilization of an otherwise civilized society (ever read lord of the flies?). Removing a very basic symbol solely because "it seems like ashwalker aesthetic" shows a very distinct lack of actual thought put into the PR.
> 
> Since you provided no explanation or justification at all to any of the other changes in this PR, I have no choice but to assume that the same exact reason you gave for restricting head pikes applies to all of the crafting recipes you're restricting in this PR. I cannot think of a good reason to restrict these recipes to ashwalkers since they require access to lavaland (read: only lavaland ghost roles, gulag'd prisoners, and miners can reliably access them), and are outclassed by everything aboard the station anyhow (only exception being the bone spear).

I was openly discussing this in voice chat with a large number of people and gauged opinions. The whole reason to this is ultimately that lavaland itself already has a huge assortment of weapons and whatnot available and the bone axe and bone spear is something that should really be used with ashwalkers. 

The heads on a stick were deemed primitive, in a sense that I've also personally only seen those in ashwalker bases. 

Updated so head spikes aren't restricted.

**Comment by ghost** [comment]
@Putnam3145 bone axe is useless on lavaland and you know this and honestly doesn't even deserve to exist
what is 23 damage worth if you need to do 19 hits to kill one basic monster? perhaps bone axe should have some sort of bleed effect on lavaland monsters (much weaker than cleaver of course) or something to make it at least a sidegrade to almost any other option instead of a downgrade, not to mention how much stamina it uses to swing an axe vs any of the other weapons ashwalkers have access to.
if the locked items are intended to be for ashwalker solo use they should be at least somewhat viable to use on lavaland, especially if crusher is the "unviable option" for miners to use (and still does 70-100 damage sans upgrades)
bone spear on the other hand is useful on lavaland and only because it has 2 tile range and not at all because of its damage

also start ashwalker become non-ashwalker, people can no longer tell you're an ashwalker and you have none of the downsides

and it's really ugly having it all as one giant list of individual learning procs just sitting there in the middle of the race code although that's probably just the fault of the actual proc itself

**Comment by silicons** [comment]
alright firstly i'm going to go and hide the obviously spam comments

> voice chat

your first mistake is pulling up a thing with no logging at all and no way for me to go find some conversation from wherever-it-was so if those people care so much they better come make some comments because otherwise i'm going to completely disregard it

second, i do not see a "where is this good for the game", a working changelog, this is a webedit pr made after a staff forum complaint about these items like really?

all in all i'm in agreement that this is not a necessary change to the game, there's plenty of lavaland things if someone abuses this stuff to an egregious degree (and i don't mean just because you think it's not okay, even if certain cases are getting annoying to deal with) the admins should be dealing with it. as much as i speak out against miner powergame this stuff isn't too bad, as of right now i don't see a severe balance concern that would necessitate removal of these items from being available to be crafted from the station.

i will be closing this PR at the 24 hour mark unless another maintainer disagrees. 
also, please stop making prs for your overreactions. the codebase is not a place for you to attempt to weaponize in your quarrels with others players and i'm frankly not going to tolerate this.

**Pull request closed without merging**
