### PR TITLE
/tg/ ""hardsync"" part one of many*

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
Ports a fuckton of shit from /tg/, notably sounds, animation "gliding", and subsystem updates

## Why It's Good For The Game
speed good, immursion good

## Changelog
:cl:
add: Coin & Holochip support for slot machine
admin: Stickybans are now saved in the DB too
soundadd: Immersive &trade; audio reverbs. (also adds multiz audio)
code: Semi-hardsync from TG
code: Updates rust-g
code: Uses git CI instead of travis/appveyor now
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Added merge conflict label due to merge conflicts being present.

Also wow thats alot of linter errors.

**Comment by LetterN** [comment]
rustg faling :joy:

**Comment by DeltaFire15** [comment]
Do not merge. Severe issues ~~including some atoms not initializing~~.
Edit: The atoms not initializing part was caused by a different PR.

**Comment by LetterN** [comment]
```
file ./code/datums/elements/bed_tucking.dm is missing a trailing newline
file ./code/modules/research/designs/machine_desings/machine_designs_engi.dm is missing a trailing newline
file ./code/modules/shuttle/spaceship_navigation_beacon.dm is missing a trailing newline
file ./code/modules/mob/living/simple_animal/parrot.dm is missing a trailing newline
file ./modular_citadel/code/modules/client/loadout/unlockable.dm is missing a trailing newline
```

linter problems, code is fine though

**Comment by Putnam3145** [comment]
kind of maybe the worst possible time for this

**Pull request merged**
