### PR TITLE
Ports a bunch of wings from cit RP and fulpstation [Ready]

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
This PR ports a bunch of wings from both cit RP and Fulp station. From Fulp station we are getting four new moth wings made by Papaporo Paprito. The original PR for these wings can be found here https://github.com/TheSwain/Fulpstation/pull/415. Additionally some of the wings which had extra pixels have been cleaned up.

## Why It's Good For The Game
Offers more character customization for characters including some wings which people have been wanting on the main server and some new wings for moths.

## Changelog
:cl:
add: Wings from Cit RP have been ported over
add: Moth wings from cit have been ported over
fix: Cleaned up some pixels on existing moth wings.
tweak: Organized the lists for wings by if they are for moths or not and than by alphabetical.
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
As a side note, in the process of making this PR I figured out that on main the ckey locking for donator item for character customization does not work properly. I'm honestly exhausted and don't have the energy to make a full on issue for this.

**Comment by timothyteakettle** [comment]
don't rename sprite accessories, they're sadly saved by name if i recall correctly, and thus this can and will cause data loss (unless you wish to do a migration for it)

**Comment by shellspeed1** [comment]
I think I got them all renamed back to what they were but I would like it if someone could double check please.

**Comment by shellspeed1** [comment]
Alright should be good now.

**Comment by BlueWildrose** [comment]
I noticed that the succubus wings has a spaded tail on the same sprite - this isn't intentional is it?

Shouldn't that tail be its own completely separate sprite perhaps?

**Comment by shellspeed1** [comment]
I mean for the most part I just pulled sprites directly from RP. I guess I could separate it out into a tail.

**Comment by shellspeed1** [comment]
Ya know what lets leave it for now. When I get around to porting tails assuming that there are tails to be ported I'll separate succubus wings and tails than.

**Pull request merged**
