### PR TITLE
Committing the conflicting file

### PR DESCRIPTION
**Pull request by ktccd**
:cl: ktccd
tweak: Renamed breasts to use size numbers instead of cupsizes
/:cl:

[why]: # 
This is the file that caused a binary file conflict in my virology PR.
Since github hates binary conflicts, I'm attaching it as a new PR.
NEITHER PR WILL WORK WITHOUT THE OTHER!! God I wish there was a better way to handle binary file conflicts...
Related PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/353/

### CODE REVIEW

**Comment by silicons** [comment]
you mean dmi conflicts? they're fixable without opening a new PR..

**Comment by ktccd** [comment]
I know they are, but it has to be done by whomever merges it, not me. You can specify which file to use when merging such conflict. But I think this was the simplest way to do it for whoever handles merges?

**Comment by TalkingCactus** [comment]
This file reverts the changes made in #397

**Review by TalkingCactus — CHANGES_REQUESTED** [review]
Needs to include changes made in #397

**Comment by TalkingCactus** [comment]
What you have:
image
What you need:
image

**Comment by ktccd** [comment]
And I was so certain it worked... I downloaded the icon from master so it would have whatever pixel change it should've had and just renamed them to fit the new stuff...

**Comment by ktccd** [comment]
Gonna be honest, I should probably close this PR anyway, since the virology PR it's supposed to go with is fucked. Thanks for pointing out the file error though.

**Pull request closed without merging**
