### PR TITLE
[DNM] Latejoin Gamemode Scaling

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Latejoins are not going away no matter what because it's a fundamental part of the game.
Instead of doing some nuclear option stuff like some people proposed like disallowing latejoins which would bar like a third of the server from participating and punish people who are just trying to play the game I'm instead going to solve the problem as best as I can mathematically

## Why It's Good For The Game

Entire gamemodes getting shafted by this is upsetting and exhausting and people literally encouraging others to do this maliciously is shitty I'm done so I'm going to play the math game and make it so latejoining doesn't hit gamemodes as hard.

## Changelog
:cl:
add: gamemodes now automatically scale to latejoins
/:cl:

General:
Adding config entries for scaling coefficients for every gamemode not just traitors and stuff and making it a keyed list, this includes stuff like nukeops telecrystals, this is something long overdue
For stuff like clockcult/nukeops/offstation antags latejoins can be directly grabbed to the antag base and equipped if they have the antag option enabled to meet the intended scaling

Plans by gamemode:
Cults, clockcults, traitor, changelings, bloodsuckers: with enough latejoins it just antags people until it meets its proper scaling
Nukeops: latejoins that create an imbalance results in people with the preferences on being moved to be nukeops via teleport to shuttle instead of crew, and raw telecrystals being beamed in based on intended scaling
Revs: not necessary, it's automatic and scaled to heads anyways
Dynamic: putnams thing I'm not touching it but if they don't bother with this maybe threat level increases 
Gang  I need to double check but it's probably not worth trying to auto scale a gamemode that's already going to result in 80% of the server being converted so it's a whatever
Wizard: this gamemode doesn't scale at all and having it on lowpop was stupid anyways who cares

### CODE REVIEW

**Comment by CameronWoof** [comment]
Good PR.

**Comment by MrJWhit** [comment]
Uh, unless I'm mistaken, revs does _not_ scale with latejoins, there are no revheads added when a head joins.

**Comment by GrayRachnid** [comment]
> 
> 
> Uh, unless I'm mistaken, revs does _not_ scale with latejoins, there are no revheads added when a head joins.

Revs scales with the number of heads.

The more Heads of Staff there are, the more Revs get automagically converted to revheads.

**Comment by MrJWhit** [comment]
From what I can tell, they aren't "automatically" converted, that's from admin intervention. At least, that's what I do, and what I see BlackMajor do.

**Comment by GrayRachnid** [comment]
I've been turned into a revhead the second I was flashed before 🤔

**Comment by Ghommie** [comment]
Are you still working on this?

**Comment by Ghommie** [comment]
Stale.

**Pull request closed without merging**
