### PR TITLE
removes an item

### PR DESCRIPTION
**Pull request by Detective-Google**

### CODE REVIEW

**Comment by moltoretardo** [comment]
Speedmerge

**Comment by timothyteakettle** [comment]
counter argument:
unknown
edit: also someone could rename anything to 'dildo' and embed it in you using tape

while i'm not against this i'm also not for it because there's literally no reason to either remove it or keep it
edit2: just remembered we nuked the dildo circuit model so yeah nuke these too

**Comment by ghost** [comment]
changed my mind this is neither based nor unbased

**Comment by Tumesuo** [comment]
no

**Comment by Putnam3145** [comment]
this i agree with though

**Comment by silicons** [comment]
not harmful enough for full removal at the moment.

**Pull request closed without merging**
