### PR TITLE
door charges no longer unconscious() you

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
- it doesn't knock dudes out
## Why It's Good For The Game
bruh
## Changelog
:cl:
balance: Door charges no longer knock people out.
/:cl:

### CODE REVIEW

**Review by silicons — CHANGES_REQUESTED** [review]
just remove the unconscious so they have a good chance of survival, apply damage nerf is unnecessary

**Comment by lolman360** [comment]
isn't that the entire point of doorcharges though

🧂

**Comment by ghost** [comment]
🧂

**Comment by lolman360** [comment]
@TheSpaghetti 
#13019

**Comment by necromanceranne** [comment]
Did someone add airlock charges to the uplink again? Or is this the kit?

**Comment by Tupinambis** [comment]
Airlock charges are kit exclusive. They are so rare that nerfing them makes zero sense. You get two of them total from the kit if you even manage to role it with RNG.

**Comment by ghost** [comment]
> @TheSpaghetti
> #13019

**salt pr**

**Pull request merged**
