### PR TITLE
Revert "Adds realism to pleasure" - "Kev people are two hitting each other with sex circuits"

### PR DESCRIPTION
**Pull request by silicons**
Bad ideas.

### CODE REVIEW

**Comment by Poojawa** [comment]
More like shitty circuits

**Comment by RogueSteampunker** [comment]
just to remind everyone, adding a genuine ingame effect to an opt-in feature who's main effect is making cum swastikas on the bridge was never a good idea to begin with. Blaming a meme circuit for the fact that you thought 40 stamina loss was a good idea is like trying to blame metastation for your first iteration of character creation overhaul literally eating all the server's resources (^:

**Comment by Poojawa** [comment]
and this person wants to be a player rep :^)

**Comment by granodd** [comment]
@RogueSteampunker isn't wrong.

**Comment by Keekenox** [comment]
I don't see an issue with anything Steampunker said.

**Review by deathride58 — APPROVED** [review]
Merging since both other maintainers are against my alternative PR

**Pull request merged**
