### PR TITLE
Combat v7 - Sprint removal, automatic block/parry, turns combat mode into a pure UI/interaction toggle with no side effects, and a truckload of other stuff.

### PR DESCRIPTION
**Pull request by silicons**
https://hackmd.io/@CitadelStation13/HJWbIYJWO

on testmerge:

- tweak config movespeed + disable sprint in config

done: 

- implement autoparry mouse hooks
- implement autoparry simulation overrides for both kinds of autoparries

- id components work again, **and are applied to radioactive microlasers**
- blocking offsets look less ridiculous
- batons now apply_damage instead of adjuststaminaloss. physiology armor will now work on them.
- laser miniguns are less awful
- experimental changes to sound that make 3d apparent range and falloff much higher, plus a higher falloff exponent
- wound bloodloss values nerfed
- wounds will be a bit more common now
- limb damage cap raised to 150 from 75
- limb damage multiplier lowered to 0.25 from 0.75
- limb disable threshold still at 75
- batons and telebatons now get blocked at around 50% mitigation
- stunprods buffed to 35 stamina damage from 25
- blocking pixel offsets look less ridiculous
- all combat mode mechanical effects have been removed. it is now just a ui toggle.
- legcuff removal is no longer stopped by movement, but will be slowed down 2x by its
- xenos take 1.75x burn damage up from 1.2
- vtec -=s 0.5 speed instead of 1, might be op but w/es
- shoving people who are on the ground now does stamina (5 to 10)
- tasers have been slightly buffed
- yelling has been reworked because as it was in the past it completely ruined the concept of stealth
- chempuffs/sprays have been refactored. anyone walking inside will be hit rather than needing to land on someone on specific
- damage slowdown calculation redone

### CODE REVIEW

**Comment by moltoretardo** [comment]
Combat rework 😳

**Comment by ghost** [comment]
hell yeah it's here

**Comment by MacaroniCritter** [comment]
sprint removal 😭

**Comment by TheEaterOfBeans** [comment]
PLEASE make it so megafauna (or at least BDM specifically) let you sprint when they're attacking you or something aaAAAA**AAAAA**

**Comment by TheEaterOfBeans** [comment]
aaaAAAA I NEED TO BE ABLE TO DE-AGGRO BDM SO I CAN DO MY DUMB HIT AND RUN STRATEGY AND GET THE FUNNY SAW

**Comment by DeltaFire15** [comment]
Merge conflicting.

**Comment by DeltaFire15** [comment]
Marking PR as stale due to unaddressed merge conflicts with a long period without commits.

**Comment by ghost** [comment]
every time i see this PR i get sad because it's lower and lower on the list, while also being the change im most hyped about

**Comment by kiwilover8** [comment]
with sprint removed, I feel like a large number of non-humanoid antagonists who do not utilize sprint currently will need some degree of movement speed penalty/nerf, xenos are one of the big ones that come to mind, possibly blobbernauts and simplemobs such as the cat surgeon/giant spiders and other space ruin monsters.

**Comment by silicons** [comment]
yeah this only took me 3 months.

**Comment by CameronWoof** [comment]
Okay but just remember this was my idea.

**Comment by TheObserver-sys** [comment]
> Okay but just remember this was my idea.

https://www.youtube.com/watch?v=P-B3OLLUoN4

**Comment by kiwilover8** [comment]
if the purpose of autoparry is to minimize ping-reliance in combat, then tying it to your mouse hovering over someone would still cause issues in that regard, no? Because it has to recognize you're hovering them.

**Comment by kiwilover8** [comment]
the sheer amount of movespeed that the ninja shoes give seems like it might need to be reigned in under this, as it goes at speeds comparable to the removed sprint

**Comment by TheEaterOfBeans** [comment]
What are the config options for disabling sprint and increasing movespeed?

**Review by Linzolle — APPROVED** [review]

**Comment by TheEaterOfBeans** [comment]
aaaAAAAAAAAAAA
HOW DO I CHANGE
MOVESPEED
TO 6.66
IN LOCALHOST?

**Pull request merged**
