### PR TITLE
Removes my Lavaland Xeno Ruin. Reverts (#7455)

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removes the Alien/Xenomorph Lavaland ruin from the code. As the creator of this map, I no longer wish for it to be featured on this codebase. 

## Changelog
:cl:
del: Lavaland alien/xeno ruin
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Isn't the ruin just a rework of the original xeno ruin from a gateway mission?

"It's my code" isn't actually a valid reason to remove anything excepting code you need to actively maintain (like station maps)

**Comment by Linzolle** [comment]
is this because people kept turning themselves into xenos

**Comment by YakumoChen** [comment]
no, he's just ragequitting the codebase

he should probably figure out that once code is merged, it's no longer technically "his".

**Comment by deathride58** [comment]
Looks like someone didn't read the license file

**Pull request closed without merging**
