### PR TITLE
Makes the spoopy event last for four more days

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Gives people a chance to be more spoopy, also seems to be widely requested.

## Why It's Good For The Game

Because the people want it. And because it's four more days of spoopy skeletons.

## Changelog
:cl:
tweak: democracy spoop - four more days
/:cl:

### CODE REVIEW

**Comment by Thalpy** [comment]
And 4 more days of Jacq!

**Comment by IgiariValkyr** [comment]
I made one for it to last the whole month. Go away :u

**Comment by Seris02** [comment]
> I made one for it to last the whole month. Go away :u

I tried this and kevz said no

**Comment by silicons** [comment]
ehh next halloween maybe.

**Comment by kevinz000** [comment]
actually fuck it

**Pull request closed without merging**
