### PR TITLE
poisoned knife for tators

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

like a sleepy pen but a knife and doesn't inject all of it's reagents, only a random pick of 4,5,7 or 10 reagents at a time.

## Why It's Good For The Game

more traitor items

## Changelog
:cl:
add: Added new things
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Ah yes, the phlog/sacid/facid knife.

**Comment by silicons** [comment]
ah yes, a multi use sleepy pen because the regular one wasn't broken enough.

**Comment by necromanceranne** [comment]
Also this isn't blocked by thickmaterial so if there is any immediate change you need to make, it's that one.

**Comment by Seris02** [comment]
fuck true yeah

**Comment by silicons** [comment]
sorry calling it here, reagent warfare is bad enough with people killmixing via sleepypens/whatever, we really do not need a multi hit one. if you really want this maybe make it have like 10 or so units and inject all on hit and make the pr again. also, make it respect thickmaterial.

**Pull request closed without merging**
