### PR TITLE
Nanomed plus changes + lasers are cauteries now

### PR DESCRIPTION
**Pull request by katnep**
Added some stuff the the nano vend
3 epinephrine medipens
1 box of hugs
3 medical belts
1 medical wrench

Lasers can be used as a cautery
also closed my other PR becuase the changes somehow merged into this branch as well

### CODE REVIEW

**Comment by ghost** [comment]
All PRs need a description detailing what has been added, removed, changed, etc.

**Comment by katnep** [comment]
how nice of my PR to not include what i wrote down

**Comment by ghost** [comment]
👍

**Comment by TalkingCactus** [comment]
I don't really think the medivend needs the belts, wrench, or box of hugs since it vends drugs not clothing/tools. Maybe shove the box of hugs into contraband or something.

**Comment by katnep** [comment]
my argument for the belts and wrench is it also vends a crew locator so it adds like useful hardware that's not gonna get put in someones back pack and forgotten about especially that medical wrench

**Comment by TalkingCactus** [comment]
Yeah, but there's already a wrench in cryo, belts in the storage room, and box of hugs are a meme item found in maint.

**Comment by katnep** [comment]
i actually have no idea what's in a box of hugs tbh, i only find the empty ones but this one is full

**Comment by TalkingCactus** [comment]
It's an epi-pen, gauze, and ointment.

**Comment by TalkingCactus** [comment]
**POWERCREEP**

**Comment by katnep** [comment]
ah, well yeah that's in this one, i'll bump that into contraband and delete the rest

**Comment by TalkingCactus** [comment]
Can you also change the title so it's not shit and do that every time you make a PR. The title of it can be useful when searching for a certain PR at a later date for a rollback or searching for the cause to an issue.

**Comment by katnep** [comment]
did that

**Comment by TalkingCactus** [comment]
thanks

**Pull request merged**
