### PR TITLE
LOUDER DELAMS

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This is more something I had a problem with, but when thinking about it, it made sense to bring it up in a PR. The SM messages broadcasted over common are no different from a cyborg or any other machine stating something. While that could be fine when going on the engineering channels, a common broadcast alerting to something dangerous like that, SPECIALLY the countdown, should be "louder" and therefore easier to notice. I ain't dyslexic or anything but even I had a hard time seeing shit was going down in my peripheral vision.
Tldr.: Integrity % broadcast will show in bold, but still same font size; Countdown will be just like Command Headsets on the LOUD setting (might be a little too much). REMINDER THAT ONLY APPLIES TO COMMON BROADCAST. The engineering alerts will remain the same.

## Why It's Good For The Game

Makes it easier to see when crystal integrity/delam countdown in case you are distracted by anything else, or have difficulty reading the chat.

## Changelog
:cl:
tweak: Super Matter Crystal integrity messages over common now will be bold.
tweak: Super Matter Crystal Countdown messages over common will now be larger and bold.
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
Nah bro just give it the narsie font trust me on this one

**Comment by shellspeed1** [comment]
Why use Narsie when you can use Ratvar

**Comment by ghost** [comment]
alright how about a 1/255 chance that it will be one of the cult fonts/blob

**Comment by DeltaFire15** [comment]
People missing the 
30..
20..
10..
5.4.3.2.1.
 countdown is obviously just a feature

Anyway, joke aside, not exactly opposed to this but not inclined either, so, leaving this to the other maintainers to decide.

**Pull request merged**
