### PR TITLE
Coggers.

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

**This pull request is effectively a second attempt at #11415** - in other words, a remake of Goonstation's Cogmap1 for TGcode servers. Originally started by someone who wants to remain anonymous for all I know, I've gone ahead and seen to it their work was finished. It still has some kinks to work out, but should be suitable for testing at least.

freesample

It isn't a perfect 1-to-1 remake, partially due to differences in server code in addition to feedback from the Citadel community. However, CogStation seeks to capture the spirit of the original while featuring its own unique charm. **Most of its defining features have been preserved, including:**

- **Integrated Artificial Intelligence:** Unlike most maps that relegate it off to a satellite, CogStation's AI is more or less the heart of the station.
- **Thermo-Electric Generator:** For many engineers, the TEG is usually a side project that comes after the supermatter engine is fired up, but on CogStation it's your primary power source.
- **Advanced Disposal Systems:** CogStation features independent disposal pipe systems for trash, mail, even corpses!
- **Routing System:** A unique method of cargo delivery that lets you launch goods through space. (It isn't fully functional yet, unfortunately.)

**It's also undergone some modifications in order to better suit TGcode, such as:**

- Pod bays have been replaced with conventional shuttle docks, making the map Lavaland-ready.
- The Research Sector features a newly-added Xenobiology Lab and Toxins test range.
- A "Discount Transfer Centre" has been set up next to Security, if perma isn't enough.
- You'll find a complete telecomms satellite outside the bridge, as opposed to merely a receiver.

Unlike the original pull request, the shuttles have been added independently via #11511.
**Be aware you may need them for this station to work properly.**

## Why It's Good For The Game

In addition to being a new choice in map, CogStation seeks to provide a unique experience. Much of modern Space Station 13 can trace itself back to Goon, and this remake is intended as a homage.

## Changelog
:cl:
add: Adds CogStation to the map rotation.
tweak: Adds several new area designations to accommodate CogStation.
/:cl:

### CODE REVIEW

**Comment by EmeraldSundisk** [comment]
Closing while I make some discussed additions.

**Comment by EmeraldSundisk** [comment]
I might reopen this once it's ready again, but any pushes I'm making shouldn't be testmerged at the moment. It's more "saving my work".

**Comment by EmeraldSundisk** [comment]
Reopened so it can be incorporated into the code at least.

**Comment by EmeraldSundisk** [comment]
Shitcode solution sadly did not work.

**Comment by EmeraldSundisk** [comment]
...What.

**Comment by EmeraldSundisk** [comment]
Adds the atmos system, some fixes to science, and a bit of decor. Thanks for the help!

**Review by nik707 — APPROVED** [review]

**Pull request merged**
