### PR TITLE
a PR about empty hypospray kits, vial printing, along with a thing about quantum electromag

### PR DESCRIPTION
**Pull request by Hatterhat**
uh oh! it's another stupid fucking hatter pr!
update: removed bluespace hypovial designs from applied bluespace, so they can't be unlocked
## About The Pull Request
adds hypovials to basic tech so they're roundstart printable from med fab
adds designs for bluespace hypovials. not implemented
adds empty hypospray kits as printable items i.e. printable empty medkits
PROBABLY SHOULD BE ATOMIZED: nudges quantum electromag behind adv bluespace like the rest of t4

## Why It's Good For The Game
uh get back to me on that one i pr'd this while between rounds
## Changelog
:cl:
add: Hypospray vials are now printable from the medical techshift start.
add: Empty hypospray kits are now printable behind biological technology.
tweak: Quantum electromag (T4 lasers) are now behind Advanced Bluespace like the rest of T4.
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Personally don't think there needs to be a printable 240u hypo vial.

**Comment by Hatterhat** [comment]
@DeltaFire15 how about now

**Comment by DeltaFire15** [comment]
Remove the bs vial designs you were adding too since there's no need to have them sit dead in the code and it should be good to merge.

**Comment by R3dtail** [comment]
Give me printable large hypovials from the medifab so I never have to leave medical ever again thank you

**Comment by Hatterhat** [comment]
@DeltaFire15 ok

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
