### PR TITLE
holodeck WRESTLING

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
adds a new holodeck map which has special wrestling belts which only work on other people wearing them, map also has some masks and gloves

image

## Why It's Good For The Game
wrestling memes are good, and in this format it's also hard to abuse because of the requirement of the opponent also wearing one of the belts

## Changelog
:cl:
add: add new holodeck wrestling belt which lets you use moves only on those also wearing it
add: add new holodeck map featuring the holodeck wrestling belt
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
the wrestling code leaves a bad taste in my mouth

**Comment by timothyteakettle** [comment]
I am still fairly new to this language, but any knowledge on how I should refactor it to be less bad would be super appreciated edit: I think I know what I did wrong.

**Comment by timothyteakettle** [comment]
I looked over it and I think I fixed what was wrong with the code. I should have probably reviewed it before going 'it works, time to make a pr.'

**Review by silicons — APPROVED** [review]
this is silly as shit (also use FALSE/TRUE in the future please for booleans!) but ..
ehh it's 
not hurting anyone so
why the fuck not.

**Pull request merged**
