### PR TITLE
Removes bloodsuckers until I rework it

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Removes bloodsucker code cleanly out of the code, need to make it more respectable before I re-add it, it's unused anyways.
Leaves in TRAIT_NOMARROW because vampires the race use it, tempting to rename it something better named like TRAIT_NOBLOODREGEN, but that's pretty long

## Why It's Good For The Game
Unused code is pointless to leave in the codebase

## Changelog
:cl:
del: Removed bloodsuckers and most related code
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
so true bestie

**Comment by SgtHunk** [comment]
🤨

**Comment by DeltaFire15** [comment]
How likely is it for you any such rework is going to happen anytime soon, as it has been mostly unchanged for two years?
If you intent on doing that sometime soonish, sure, otherwise I'd prefer keeping it in the code for special use or downstreams.

**Comment by Arturlang** [comment]
The code will be around even if it is removed from the main branch due to how git works. @DeltaFire15

**Comment by Arturlang** [comment]
However, what it would require is someone reverting this PR if they wanted to start fixing it, but so far, nobody has really made any feature changes to bloodsuckers besides me. I'll do so myself once I get enough good changes together.
I haven't had a lot of time to work on coding ss13 lately due to learning web-development

**Comment by Arturlang** [comment]
been open for almost a month  I guess it'll just stay in now

**Pull request closed without merging**
