### PR TITLE
Content update & tweaks [TESTED & READY FOR REVIEW/MERGE]

### PR DESCRIPTION
**Pull request by ghost**
New stuff, balance changes, tweaks
- Protokinetic Crusher
  Images:
  dreamseeker_2016-09-03_14-05-15
  dreamseeker_2016-09-03_14-05-26
  dreamseeker_2016-09-03_14-05-57
  dreamseeker_2016-09-03_14-06-00
- Military belt cost bumped down to 1 [gives you away, basically fanny pack but with more slots]
- TK fixed to be less stupidly awful op
- DNA scanner rejuvenators changed to potassium iodide
- Plasma is slightly radioactive upon consumption
- Necropolis chests no longer burn in lava
- Urinals can now hide items and include a cake of soap stuff
- Trick self destruct firing pin added to syndicate uplink
- Breath masks guaranteed to be in oxygen lockers
- Triple esword added (combine esword with double esword, even more powerful, see code for details)
- New booby trap device, bought from uplink. Rigged closets and boxes can be defused with wirecutters.
- Added Tiger I WW2 tank as a "mech", currently adminbus spawn only. (requested by TK)
  eyj1cmwioijodhrwczovl2ltywdlcy1lehqtmi5kaxnjb3jkyxbwlm5ldc9leuoxy213au9psm9ksfj3t2k4dmftnxbiv2qxy2k1amiymhztr3hzwlzkae1dnxdibwnpzleur05zbgdmegmzcfvjlu9xaf9stkzasvhpcmdnlnbuzyj9 piw1qm_64ehyeswpqtqlrxak2p0
- Captain's space suit is now a hardsuit, featuring a functional light like all the other hardsuits.
- New 50u thermite spray bottle that can spray walls, comes in a kit with a zippo
- Ghosts may now examine silicons to read their laws
- Weather events made into their own subsystem
- Radiation storms now make all unprotected areas glow with radiation (because that's totally how radiation works) and provide a better forewarning and damage balance.
- Space description text.
- A total of nine randomly selected title screens. (thanks funkynuggets)
  fullscreen
- 2 new large graffiti
  dreamseeker_2016-09-11_12-59-52
- Craftable headlamps

DISCLAIMER: Some of this is shamelessly ripped from tgstation pull requests.

### CODE REVIEW

**Comment by ghost** [comment]
pics added

**Comment by ghost** [comment]
this is now an actual content update, will continue to add more

**Comment by ghost** [comment]
eyj1cmwioijodhrwoi8vaw0uzxpnawyuy29tl3rtcc9lemdpzi0yndq4nzexni5nawyifq oo8hranleb41spfw2q1o-xbf1fg

**Comment by unusualcrow** [comment]
Booby traps.

**Comment by ghost** [comment]
Everything now appears to work fine. Feel free to review the changes and merge whenever.

**Comment by TalkingCactus** [comment]
Some of this is great, A+ work. Other parts are completely unrelated and I personally don't think we need. Split this into multiple PRs of related content so they can be reviewed separately.

**Comment by ghost** [comment]
Alright, going to split this into multiple PRs and branches.

**Pull request closed without merging**
