### PR TITLE
Fixes bugs in BoxStation; turns on docking beacons on Box; fixes roundstart atmos differences.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Fixes mapping errors. Like two are my own and some others have existed for a long time. Minor fixes, but this also fixes a maint room that starts out with a hole to space.

## Why It's Good For The Game
Fixes bugs that have existed since ~~the dawn of time~~ the big Box Rework PR.
Fixes bugs that have existed since the Romans invented computers that can face in more than one direction.

## Changelog
:cl:
fix: Missing turf_decals in Cargo Office.
fix: Turns on the docking beacons on Box.
fix: Fixes Starboard Quarter maint room being spaced. It was never intended to be like how it was.
fix: The aforementioned maint room not having stuff in it.
fix: varedited photocopier sometimes not opening any UI.
fix: Atmos differences in Starboard Quarter maint.
fix: Atmos differences in destroyed shuttle/EVA bridge. Plating replaced with airless plating.
fix: Rotates AI satellite computers. These have probably been like this since computers had the old sprites and no directional ones. You shouldn't sit at a chair to operate a sideways computer.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Aelita's changes doing the same thing with the spawns has been merged just after I made this.
Do not merge until updated to not just overwrite those changes.

**Comment by Ghommie** [comment]
Conflicts.

**Review by Ghommie — CHANGES_REQUESTED** [review]
You deleted boxstation.dmm, bravo.

**Comment by KathrinBailey** [comment]
> You deleted boxstation.dmm, bravo.

I'm fully aware. I just merged my master with upstream master and copied Box over to avoid any problems as I had conflicts, and my Box was conflicting with a Box that got merged into upstream hours after I made the PR. I have copied the changes over, and for now I am ditching Metastation changes in favour of doing a larger rework, similar to that of Box's one, in the future. For now, I'm just working on Box. After playing different roles I'm also doing some QoL fixes and other bug fixes, such as:
• Fixed probable accidental deletion of turf_decals in cargo.
• Gave the HoP a denied/accepted stamp for their own paperwork.
• Condensed items on the table at the Cargo Office desk, using the space for a filing cabinet.
• Added maint loot spawners into the warehouse crates, for consistency with other maps that also do this.
• Moved stuff in HoP office, added swapped the PDA painter's position with a table that has a folder and stamps. HoPs can make a form, go up to the meeting area, print copies and put them in their folder, then hand them out and file them once completed. Paperwork HoPs can now do their thing roundstart.
• Urhh I gotta go to work so travis probably shoes changes.

Anyway I need to redo the meta part but I gtg to work now.

**Review by Ghommie — CHANGES_REQUESTED** [review]
This PR is an unatomized mess now. This was supposed to be a fix but ended up with many unwarranted changes.
Revert the changes done to the public garden, cargo, HoP office / heads meeting room and library.

**Comment by KathrinBailey** [comment]
> This PR is an unatomized mess now. This was supposed to be a fix but ended up with many unwarranted changes.
> Revert the changes done to the public garden, cargo, HoP office / heads meeting room and library.

-edit:

Kev told me what you meant,

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
