### PR TITLE
Removal of MKUltra

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title.

## Why It's Good For The Game
Since its addition, there have been issues about MKUltra on several fronts ranging from the high risk and efforts to make it to the consent taboos and rules, from its low practicability to the unpolished code and huge copypasta that's the velvet chords vocal organ.
I appreciate the efforts Fermis put into it. But alas, it's been a spine in the back, so goodbye master-pet hypno feature. :crab:

## Changelog
:cl:
del: Removed MKUltra.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
It was fun well it lasted, guess hypo fetishes relie on alien tech once more.

**Comment by MrJWhit** [comment]
MKUltra was designed as the End All Be All of chemicals, requiring a lot of trial and error, math, and so on. Just straight removing it without another chemical feels weird.

It's still worth it to remove it to save headaches, but just strict removal makes everything feel underwhelming.

**Comment by Ghommie** [comment]
That's why it's unpractical, there is little time to play with it when the round is coming end.

**Comment by Trilbyspaceclone** [comment]
Well get a 3-4 hour round and its not that bad, a good chemi makes it around 40~ mins if miners get bs shards and sci dosnt use them all on parts - Tho ye I still think game/admin wise the chem isnt not ready for the player base

**Comment by IronEleven** [comment]
F

**Comment by NoctuaAngelis** [comment]
l o l

**Comment by Vizoplez** [comment]
> That's why it's unpractical, there is little time to play with it when the round is coming end.


This is literally false, I can make ~60u of mkultra in less than 30 minutes using a drip-feed method, the only issue is that it requires constant babying to make sure it doesnt gib everyone inside of chemistry.

**Comment by Vizoplez** [comment]
Also, MKultra is now entirely RP within regards to the rules, so theres no point balancing it, nor commenting on its "practicality" (cough, penis enlargement), the "Poor code" honestly isnt worth commenting over, looking at vorecode, this is a cakewalk, the only main gripes I have with MKUltra is a few bugs that can be fixed with a single return.

**Comment by SmArtKar** [comment]
Just the fuck why. It is a feature, and nobody except you has troubles with it. Citadel doesnt need other Orange :)

**Comment by ShadeAware** [comment]
The Tyranny of the Fruit begins.

**Comment by Ghommie** [comment]
Stale.

**Pull request closed without merging**
