### PR TITLE
Revert Drakeborgs

### PR DESCRIPTION
**Pull request by CameronWoof**
Reverts Citadel-Station-13/Citadel-Station-13#12739

This was a cute idea but if the artist is going to be inflexible about their copyright and demand that we tag up a community-driven project with hundreds of contributors, none of whom have demanded their name be anywhere in the code, I think we're better off without them.

If we leave these things in we're officially stating in front of God and everyone that horny sprites are worth sacrificing our integrity for.

### CODE REVIEW

**Comment by timothyteakettle** [comment]
the sprites do not fit well for citadel and holy shit we don't have to put up with some random artists demands, remove them already

**Comment by MrJWhit** [comment]
The walk cycle doesn't even fit with the movement of the borg, a lot of the idle animation is way too aggressive.

That, and the fact that these have been a constant pain in the ass for a bucket of reasons out-of-game, and the fact that nobody uses them (probably from the movement reasons) means we should just remove it.

**Comment by moltoretardo** [comment]
Nobody wanted them but it still got added because ???

But we're lucky: since most of the ~~hypoc~~ people that wanted them declared them as non-fetish content we should be okay even without 5 maintainers voting yes.

**Comment by Tupinambis** [comment]
> If we leave these things in we're officially stating in front of God and everyone that horny sprites are worth sacrificing our integrity for.

Sigh. Big fucking sigh.

I want drakeborgs removed, but uh, yeah. The main issues I have are that the sprite is massive, doesn't really fit with the artstyle, and it's overall form is not super condusive to gameplay. I'd consider even the old verkele borgs to be pushing it (Even if I really like them) so drakeborgs are kinda that step too far.

**Comment by silicons** [comment]
we're finalizing our decision on this tomorrow

**Comment by silicons** [comment]
whether it'll be to keep them, remove them, or hold a vote to decide.

**Comment by Kraseo** [comment]
imagen
imagen

drakeborgs aren't fetish content and you heard it from The Man himself so there should be no need to hold a vote on it considering the licencing is a complete headache

**Comment by The-Sun-In-Splendour** [comment]
Maintainers wanted the sprites that give credits gone, yet The Man Himself™ merged despite the author of the PR going "no"
The fucking artist won't fucking let us remove the fucking 2.5KB(!!) sprite that is literally unused, just to tag even harder his imprint onto the fucking codebase. Because text credit isn't enough.
I am urging whoever can to merge this PR asap because holy fucking shit, I may have liked the drakeborgs but the more I look at them the more they unsettle me in how they, for some reason, move while idle, their walk cycle is just... idk... And the fact that they do not fit the rest of the sprites at all

**Comment by Putnam3145** [comment]
> Maintainers wanted the sprites that give credits gone, yet The Man Himself™ merged despite the author of the PR going "no"

What

> The fucking artist won't fucking let us remove the fucking 2.5KB(!!) sprite that is literally unused, just to tag even harder his imprint onto the fucking codebase. Because text credit isn't enough.

you put !! after 2.5KB like it's big when most of the _text files_ in the code base are bigger than that. besides that, yes, this isn't a horrifically unreasonable request when the license is mismatched; Goon has an entire top-level folder dedicated to their stuff for the literal exact same reason.

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> > Maintainers wanted the sprites that give credits gone, yet The Man Himself™ merged despite the author of the PR going "no"
> 
> What
> 
> > The fucking artist won't fucking let us remove the fucking 2.5KB(!!) sprite that is literally unused, just to tag even harder his imprint onto the fucking codebase. Because text credit isn't enough.
> 
> you put !! after 2.5KB like it's big when most of the _text files_ in the code base are bigger than that. besides that, yes, this isn't a horrifically unreasonable request when the license is mismatched; Goon has an entire top-level folder dedicated to their stuff for the literal exact same reason.

I don't care most people don't like drakeborgs so I don't see why we should keep them :')

**Comment by MrJWhit** [comment]
The walk cycle is weird because there are 4 different speeds a borg can move, sprinting and walking with vtech installed or not, none of which work with how they move in the animation.
Dogborgs are fine with their jump-walk, because it's not a full on walk, it's a weird troting-thing.

Plus, yeah, idle animation is weird.

**Comment by BlackMajor** [comment]
I'm in favour of this.

**Comment by silicons** [comment]
For the record, I'll say that my personal plan was to merge it on a very close split vote, and close it if keep had a majority. The reasoning is between a permanent solution that people will be upset with, and a temporary solution that shuffles it out until any issues that people here will be upset with are solved, I think the lesser evil is removing them.
For technical clarification, this doesn't mean the module concept is banned from the codebase, but do not expect them back in their current forms for the near term future, or with these sprites.

**Pull request merged**
