### PR TITLE
Allows pod people to be made using other fluids

### PR DESCRIPTION
**Pull request by Putnam3145**
## About The Pull Request

As title. Allows pod people to be made using liquid gibs, blood substitutes/subtypes and, of course, genital fluids (sorry!)

**I honestly don't know how to do this stuff so I didn't test lol**

## Why It's Good For The Game

Pod people are underused and it's nice to have more ways to revive peeps anyway.

## Changelog
:cl:
balance: A lot more fluids can be used for replica pods
/:cl:

### CODE REVIEW

**Comment by BlueWildrose** [comment]
Time to just leave a beaker of cum in xenobio so someone can pick it up later when I inevitably get gibbed or dusted by someone.

**Comment by DeltaFire15** [comment]
> and, of course, genital fluids (sorry!)

No on that part. Impact of erp-related mechanics on gameplay should be kept low as to avoid incidents and issues stemming from them.

**Comment by MalricB** [comment]
my word has no value here but i agree with deltafire

**Comment by Poojawa** [comment]
Clown based cum pranks are a classic. Big approval.

**Comment by LeadOnTaste** [comment]
@Putnam3145 can we remove female ejaculate from the list of those liquids? I mean, technically it isn't cum like cum, so it would be more realistic...

**Pull request merged**
