### PR TITLE
[Testmerge] Porting oracle's icon smoothing for plating

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of:
https://github.com/OracleStation/OracleStation/pull/1116

THERE IS AN ISSUE WITH MAPPED IN BROKEN PLATING THAT I DON'T KNOW HOW TO FIX, PLEASE HELP ME.

## Why It's Good For The Game

God damn this is pretty.
image
It's really pretty.
image

## Changelog
:cl:
add: Ports smooth plating from oracle
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
also, soulless

**Comment by MrJWhit** [comment]
You gotta be more specific than that.

**Comment by LetterN** [comment]
@silicons expensive?

**Comment by YakumoChen** [comment]
clashes insanely badly with our current floor tile sprites, the matte black color doesn't scream 'bare plating' at all.

**Comment by keronshb** [comment]
This is bad.  It seems like a feature added to a collection of SNES games to make the sprites look "HD" but instead look like a blurry and blotchy mess.

**Comment by DeltaFire15** [comment]
Yeeah this plating blends in too much with our floor tiles and looks really monotone in general. I dislike it.

**Comment by MrJWhit** [comment]
It also gives some amount of visual layering from the plating to the floor so it's not some sort of weird paint on top of it, there's an elevation and divot to it, there's actually direction on the z-direction. 
There's some same-y look but have you actually looked what it is now? It's also quite same-y. I think this is worth the time investment. It's **darker**, sure, but that's not objectively good or bad.
image

**Comment by YakumoChen** [comment]
"Plating is just dark tiles" sure but the lighter outline with the dark inside makes it -feel- bare and empty. Matte black plating just looks like a weird floor tile. The art style doesn't match either.

**Comment by DeltaFire15** [comment]
We'll be keeping our current plating style for now.

**Pull request closed without merging**
