### PR TITLE
two toggled self-buffing spells that have no relation to any anime or video game in particular

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
adds the Inner Mantra spell for wizards and the possibility for the Asura's Wrath spell for miners.

Inner Mantra: wizard/martial apprentice locked spell, toggleable every 10 seconds and adds/removes a status effect to the caster that grants them 10 punch damage, 5 wound punch bonus, stun/shove immunity, a slight burn/brute armor and mild healing, very good stamina armor, and the ability to fight into softcrit at the cost of a constant stamina drain while active and the inability to use guns. It also deactivates automatically if the user enters hard stamcrit or hard health critical.

Asura's Wrath: a new drop from bubblegum that replaces the super shotgun, a one-use spellbook with a very **Hot** cover art. The spell acts similarly to Inner Mantra, but its only buffs are a slight stamina regen every second and the punch damage/wound punch bonus/pugilism at the cost of a constant 1hp/second health drain. Asura's Wrath also has far less style points.

if anyone wants to make animated flare-up auras when combat mode activates a reality, feel free to drop some hints for a poor beggar

## Why It's Good For The Game
it's probably not

## Changelog
:cl:
add: A new spell for the wizard and his martial apprentices, the Inner Mantra technique. It makes you punch people really good and makes you durable, but drains your energy while it's active.
add: A self-buffing spell for valiant bubblegum slayers that is ultimately useless on lavaland and probably overpowered for miner antagonists. Go figure. At least all it does is let you punch hard while draining your health every second.
balance: bubblegum now drops a book that makes you into an abusive father instead of a shotgun that plays like pre-nerf shotguns
soundadd: a powerup and powerdown sound effect
imageadd: two icons for two buff spells
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
the official sequel to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13977 does not live up to the hype. 6/10.

**Comment by kappa-sama** [comment]
fixing travis

**Comment by YakumoChen** [comment]
Ehh. We already have like, two meme wizard martial arts now?

**Comment by ghost** [comment]
i fell asleep but i'm fixing travis again now
i missed a parenthesis

**Comment by MalricB** [comment]
did I just get roasted and toasted

**Pull request merged**
