### PR TITLE
what if launchpad remote illegal tech :flushed:

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
adds a bluespace launchpad remote to unregulated bluespace tech. it looks like the science door remote.

## Why It's Good For The Game
launchpads are cool and giving them a remote locked behind the annoying to obtain illegal tech is kinda epic

## Changelog
:cl:
add: Unregulated Bluespace Technology now has a design for a launchpad remote.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
what if we didn't

**Comment by Hatterhat** [comment]
that's a fair point

**Comment by Hatterhat** [comment]
before we close this though aint it kinda fucked up how the flushed i put in the commit message as a joke did, in fact, render out as :flushed:

**Comment by DeltaFire15** [comment]
Yeeah what if we didn't, considering having a printable traitor launchpad except with 50 tiles x & y range is a *bit* wack. Least currently, you need someone else to recall you if you want to launch yourself.

**Pull request closed without merging**
