### PR TITLE
Gives space queen's men void jet packs + tweeks

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
[Changelogs]
Makes nukie jet packs have 50v
Makes void harnesses have 60v
Gives space Queen's men some basic void packs
Makes Void jet pack slower

:cl: optional name here
add: Added a few jet packs to the space queens men
tweak: volume of jet packs
/:cl:

[why]
Void packs are ment to be old and used. Why they are smaller yet get the same air is byond me
Nukies like to zoom around space, lets let them do it a bit more. After all its a hard life as a red suit.
Space Queen's men are basicly fucked over if they ever get into a space battle and not have a jet pack. So they HAVE to steal some or make their own. Really shitty thing to do if they want to green text.

### CODE REVIEW

**Comment by silicons** [comment]
no jetpacks

**Comment by silicons** [comment]
no normal jetpacks*

**Comment by Trilbyspaceclone** [comment]
@kevinz000 for who?

**Comment by MimicFaux** [comment]
Mobility to a mid/late-round side antag that thrives on hit-and-run tactics when the station is mobilizing with beam cannons and jetpacks of their own. This is good.

**Review by silicons — APPROVED** [review]

**Pull request merged**
