### PR TITLE
removes malf disk from tendril loot

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
 🤡 

## Why It's Good For The Game
malf ai and illegal tech are both items that are worthless on lavaland and overpowered on station. 
however malf ai is way more shitty overpowered literal antag ability gear and illegal tech is kinda aight i guess since snaxi has abductor tech

FUCK those types of items my dude. it's like how we have the anti-magic items that are worthless on lavaland but absolutely CUCK the shit out of cult and wizard rounds if they're unlucky enough that a miner gets the funny anti-magic.

## Changelog
:cl:
balance: miners can no longer acquire funny antag item
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
>hostile mobs in tendril chests
>>megafauna in tendril chest

>>>>people safely taking megafauna to station using a tendril chest

**Comment by ghost** [comment]
> > hostile mobs in tendril chests
> > > megafauna in tendril chest
> 
> > > > > people safely taking megafauna to station using a tendril chest

emergent gameplay tbh if a man's willing to run all the way back to station before opening their chest they deserve the funny antag lavaland megafauna on station 
bdm is a pussy anyways

**Comment by lolman360** [comment]
nowhere did i imply this is a bad thing

**Comment by YakumoChen** [comment]
Hard no from me. If you're gonna remove the malf disk, move it somewhere else it can be feasibly acquired.

Malf disk is a metabreak item for AI and having it exist is important for the health of traitor AIs

**Comment by Ludox235** [comment]
Why yes let's just add shit that fucks over the miner for trying to get loot. Instead of you know, replacing the problematic items.
No from me.

**Comment by necromanceranne** [comment]
Actively punishing people for tendril killing code wise is fucking ridiculous and actively malicious. This is practically active sabotage. Do something more direct to solve the problem or don't bother. And even if that is axing tendrils entirely, at least you're not being shit about it.

**Comment by YakumoChen** [comment]
That isn't even the only item that's useless to miners. Youd have to remove the snek rod too since that's completely useless for mining.

What's that? The hookshot isnt good on the mine and only useful for traitors? Better axe that too.

**Comment by ghost** [comment]
> That isn't even the only item that's useless to miners. Youd have to remove the snek rod too since that's completely useless for mining.
> 
> What's that? The hookshot isnt good on the mine and only useful for traitors? Better axe that too.

stop pissing yourself but also bet



> Actively punishing people for tendril killing code wise is fucking ridiculous and actively malicious. This is practically active sabotage. Do something more direct to solve the problem or don't bother. And even if that is axing tendrils entirely, at least you're not being shit about it.

fine i'll remove clown hulk i only copied that one too because it was funny 😔

**Comment by ghost** [comment]
> Why yes let's just add shit that fucks over the miner for trying to get loot. Instead of you know, replacing the problematic items.
> No from me.

/obj/effect/sliding_puzzle/lavaland/dispense_reward()
	if(prob(25))
		//If it's not roaming somewhere else already.
		var/mob/living/simple_animal/hostile/megafauna/bubblegum/B = locate() in GLOB.mob_list
		if(!B)
			reward_type = /mob/living/simple_animal/hostile/megafauna/bubblegum
	return ..()

**Comment by ghost** [comment]
> Hard no from me. If you're gonna remove the malf disk, move it somewhere else it can be feasibly acquired.
> 
> Malf disk is a metabreak item for AI and having it exist is important for the health of traitor AIs

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8606

**Comment by silicons** [comment]
i don't like malf disks because the issue with malf ai stealth isn't malf disks metabreaking it it's the antag just being a hard tell + super powerful/can go rampaging at any time.

regardless no do not make a loot drop drop a megafauna on someone that is shitty c'mon now

**Comment by ghost** [comment]
> i don't like malf disks because the issue with malf ai stealth isn't malf disks metabreaking it it's the antag just being a hard tell + super powerful/can go rampaging at any time.
> 
> regardless no do not make a loot drop drop a megafauna on someone that is shitty c'mon now

this is why snaxi is the superior map :pensive:

**Pull request merged**
