### PR TITLE
Makes portal guns spawn without firing pins

### PR DESCRIPTION
**Pull request by deathride58**
Go prod sec or cargo if you want your mass-produced 0-effort all access.

:cl: deathride58
balance: Portal guns now spawn without firing pins.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Or learn circuits and print at round start all access with 0-effort what so ever!

**Comment by silicons** [comment]
:-1: alternative nerfs are better :rage:

**Comment by deathride58** [comment]
Short of removal of portal guns, what alternatives are there?

**Comment by LetterJay** [comment]
TRAVIS FAILING

**Comment by deathride58** [comment]
Master branch was failing when this PR was made, the PR was able to be testmerged successfully a while back without compiling errors

**Review by silicons — APPROVED** [review]

**Comment by silicons** [comment]
ri pscience

**Pull request merged**
