### PR TITLE
adds polychromic clown outfit and mask

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
title
available in the loadout to clowns

## Why It's Good For The Game
customization is cool

## Changelog
:cl:
add: polychromic clown outfit and mask
/:cl:

### CODE REVIEW

**Comment by TripleShades** [comment]
image
Pink???

**Comment by timothyteakettle** [comment]
fuck

**Comment by DJKouta** [comment]
I like this idea and have no biases at all I swear.
Honk.

**Comment by TheEaterOfBeans** [comment]
> I like this idea and have no biases at all I swear. Honk.

ok cluwne

**Comment by Putnam3145** [comment]
i expect genuinely horrible things

**Pull request merged**
