### PR TITLE
Ports TG newfood

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Foundational work for porting TG cooking.
Citcode is so behind I tried to port griddles, but...

https://github.com/tgstation/tgstation/pull/41517
https://github.com/tgstation/tgstation/pull/51925
https://github.com/tgstation/tgstation/pull/53047
https://github.com/tgstation/tgstation/pull/53116
https://github.com/tgstation/tgstation/pull/53224
https://github.com/tgstation/tgstation/pull/53574
https://github.com/tgstation/tgstation/pull/53641
https://github.com/tgstation/tgstation/pull/53837

## Why It's Good For The Game
Allows the eventual porting of griddles and ovens from TG.
This doesn't mean we have to copy everything TG has done to the kitchen either.

## Changelog
:cl:
expansion: Initial port of TG newfood
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
> Citcode is so behind I tried to port griddles, but ...

techdebt's a bitch (i know how that feels)

gl tho

**Comment by DeltaFire15** [comment]
Draft unchanged for about a year.

**Comment by KathrinBailey** [comment]
Yeah sorry this honestly killed me so hard I legit lost any desire to code for SS13 for over a month, it was such a giant task.

**Comment by DeltaFire15** [comment]
No worries, only PR cleanup.

**Pull request closed without merging**
