### PR TITLE
Overhauls and 2/28 sync

### PR DESCRIPTION
**Pull request by Poojawa**
Wew lad, lots of work on this

updates to 2/28 TG, 
Added HIppie station's altered Vending machines

new turret sprites, a lot of overhead should be gone on the server as well.

### CODE REVIEW

**Comment by Poojawa** [comment]
Merge #241 before this so I can implement it, if that PR's done.

**Comment by TalkingCactus** [comment]
Yeah it's just about finished, should be done in the next 12 hrs or so.

**Comment by TalkingCactus** [comment]
Why aren't you just using TRUE/FALSE?

**Comment by Poojawa** [comment]
Because it shows 'replied ' as 0 and clicking "log" lags everything, then just repeats the ahelpahelp list.

**Comment by LetterJay** [comment]
aside from the minor tweaks above, what's holding this?

**Comment by Poojawa** [comment]
Fuck you travis it compiles fine.

**Pull request merged**
