### PR TITLE
Revert "Makes HE pipes realistically radiate away heat"

### PR DESCRIPTION
**Pull request by Ghommie**
Reverts Citadel-Station-13/Citadel-Station-13#10126

Holy shit batman! The space is on fire! This is why we shouldn't trust blindly simple atmos changes.

### CODE REVIEW

**Comment by Poojawa** [comment]
This seems like it could have benefited from a test merge for a while before being merged.

**Comment by Putnam3145** [comment]
i didn't even know this was merged, what the fuck

**Comment by ghost** [comment]
FUCK

**Comment by ghost** [comment]
this doesn't change the sprites right?
i really liked how it would glow as it gets hotter

**Comment by Detective-Google** [comment]
> this doesn't change the sprites right?
> i really liked how it would glow as it gets hotter

the heat glow has been around long before the pr this seeks to revert

**Review by Putnam3145 — APPROVED** [review]
just fullmerge it tbh i'll figure it out

**Pull request merged**
