### PR TITLE
Maint-Bar Fixes

### PR DESCRIPTION
**Pull request by Cw3040**
Changes:
-Maint-Bar area (area/maintenance/bar) re-added, space area removed
-Minor area fixes
-Old Maint-Bar changed to storage room

### CODE REVIEW

**Comment by Cw3040** [comment]
Fixes #365

**Comment by TalkingCactus** [comment]
What are the `Minor area fixes`?

**Comment by Cw3040** [comment]
The map had three specific tiles where the area was incorrect (Eng. Maint was labeled F/S Maint). This has been rectified.

**Comment by TalkingCactus** [comment]
Need screenshots of the changes as well

**Comment by Cw3040** [comment]
gotcha

**Comment by Cw3040** [comment]
http://i.imgur.com/uanboDb.png

Done

**Pull request merged**
