### PR TITLE
Gripper brained. The medborg can do chemistry now, oh no.

### PR DESCRIPTION
**Pull request by BlackMajor**
Y'know.
Borgs on this codebase have been unchanged for a long time.
Time to bring up some major balance concerns.

Following the merge of https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12780 where I recoded how grippers work, it's now really easy to make new grippers.

So now the medborg gets one, for medical things.

-Borgs can interact with IV drips now
-Removed medborg beaker, replaced with medborg gripper
Medborg gripper can interact with the following:
-Glass reagent containers (beakers), meaning they can put them into chem dispensers to do chemistry. Note, yes, harm splashing with a beaker works.
-Pills and their subtypes, meaning they can pick up pills and patches, as well as apply them.
-Pill bottles
-Bio bags. Yes, I'm aware that helps them do xenobiology. They were already able to do xenobiology by themselves.
-Chem bags. Just for convinience of moving chems to the chem fridge, assuming you're a good borg.
-Blood bags.

Major point of concern.
Chemistry, with enough work, is immensely powerful, and by doing this I've put that power in the hands of medical cyborgs. It's a little harder for them to actually do the chemical management that a human can, and I'd salute a mediborg who goes to the work of making me wildly regret letting them pick up beakers.
Read: Literally any medborg who makes chem bombs during malf. At least you can't throw them right?

Hopefully I can address most of my balance concerns after finishing off all the grippers and move onto adjusting how cyborg combat works...

### CODE REVIEW

**Comment by Ludox235** [comment]
Next: Service cyborgs being able to pick up dildos with grippers.

**Comment by BlackMajor** [comment]
> Next: Service cyborgs being able to pick up dildos with grippers.

Service borgs are next actually.
I'm making them able to do botany.

**Comment by lolman360** [comment]
> service borgtany 

YES

**Comment by ghost** [comment]
we're about to enter skyrat territory boys, sit down and buckle in your seatbelt and make sure to keep your arms and legs inside the vehicle at all times

**Comment by BlackMajor** [comment]
> we're about to enter skyrat territory boys, sit down and buckle in your seatbelt and make sure to keep your arms and legs inside the vehicle at all times

I'm a maniac, I know.
(Hopefully it balances out to be ok gameplay when I get round to changing how borg combat works entirely)

**Pull request merged**
