### PR TITLE
Fix for stuff that needs specific light levels

### PR DESCRIPTION
**Pull request by ghost**
Hopefully fixes any issues with how get_lumcount is now used.
This should fix any issues with podmen dying quickly and plants being unhealthy for no reason.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
_There's nothing here!_

**Comment by LetterJay** [comment]
Lol.... I just noticed that.

**Comment by ghost** [comment]
what the fuck

**Comment by ghost** [comment]
what has happened

**Comment by LetterJay** [comment]
You didn't check any of the files when you made the commit, lol.

**Comment by ghost** [comment]
no i definitely did, git is being fucky right now and i can't even make another PR

**Pull request closed without merging**
