### PR TITLE
Turns hive blessing into a traitor item and reworks it to turn people into a xenomorph larvae.

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
First things first, this should not be merged without https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14075 or https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14083. The reason for this is hive's blessing needs to be removed from the lavaland ruin first. Otherwise this PR does exactly what is says on the tin, it adds the Hive blessing syringe as a 24 tc role and pop locked traitor item. The TC value isn't set in stone although it will not be under 20. 

## Why It's Good For The Game
Instead of removing what is a fun item, why don't we turn it into a traitor item for people to use.

## Changelog
:cl:
add: The Hive blessing has been added as a 24 tc item for members of the science department. It requires 30 players minimum to use.
balance: Xenomorph transformation disease no longer turns people into a hunter and now turns them into a larvae so they can evolve into the other xenomorph species.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Yeah I disagree on adding this for a roundstart traitor scientist, considering they can get 12 monkies roundstart, and plenty more if someone spends a little bit of time doing xenobio.

**Comment by MacaroniCritter** [comment]
I agree with this because I really like getting my shit kicked in by simple mobs.

**Comment by shellspeed1** [comment]
I mean xenos aren't simple mobs. They are actually counted as complex ones since you can do surgery and all that on them.

**Comment by DeltaFire15** [comment]
Gonna say no to this in its current state.
Considering you can just stock up on monkeys before injecting yourself and immediately roundend the station afterwards, this seems far too strong to be a traitor item, even if it were at romerol price.
If you have any ideas to resolve that problem, be my guest. DNM till then.

**Comment by Tupinambis** [comment]
> Gonna say no to this in its current state.
> Considering you can just stock up on monkeys before injecting yourself and immediately roundend the station afterwards, this seems far too strong to be a traitor item, even if it were at romerol price.
> If you have any ideas to resolve that problem, be my guest. DNM till then.

Delta, Hive's' blessing only turns you into a sentinel or runner. You literally cannot become a queen with it. I'd argue 24 is way too high, this is closer to the gorilla mutation in terms of power.

EDIT: Turns out this PR changes that, so yeah don't let people become larva that's a terrible idea.

**Comment by shellspeed1** [comment]
I can fix the monkey problem but it would mean a significant nerf to xenomorphs. So A.

**Pull request closed without merging**
