### PR TITLE
Adds space blast doors to meta xenobio

### PR DESCRIPTION
**Pull request by bunny232**
## About The Pull Request
Adds heavy shutters to the spaceside windows around meta xenobiology.

## Why It's Good For The Game
Keeps things out... and worse things in.

## Changelog
:cl:
add: Meta Xenobiology is now equipped with shutters on the space windows.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I can't say I'm a fan of this since it makes xenobio extremely defensible beyond the specific area meant for containment. Perhaps if they were downgraded to destructible ones then that'd be fine, but otherwise this would make things a bit too well defended

**Comment by MrJWhit** [comment]
Not a fan, those things are indestructible. The less we use straight up indestructible things the better.

**Comment by keronshb** [comment]
Hugbox

**Comment by ghost** [comment]
> 
> 
> Not a fan, those things are indestructible. The less we use straight up indestructible things the better.

They're destructible. I've been able to melt them as a xeno queen, but it takes absolute ages and multiple applications to actually do it

**Comment by shellspeed1** [comment]
weirdddddddddd question, aren't the blast doors pryable which xenos can do when they lack power?

**Comment by zeroisthebiggay** [comment]
hugbox

**Comment by ghost** [comment]
> 
> 
> weirdddddddddd question, aren't the blast doors pryable which xenos can do when they lack power?

They can be pried without power, but good luck getting inside to depower it

**Comment by bunny232** [comment]
btw blame blubelle for asking for me to add these.

**Pull request closed without merging**
