### PR TITLE
Random Chimp Event (midround monkey antag)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Help is appreciated! TESTMERGES WILL BE NECESSARY! (will talk to maintainers later, when I am sure it's ready)

The idea is to relaunch Monkey antag as an midround antagonist that is fun and not completely awful.

What NEEDS to be done:
- Test and balance it after if needed.

What IS done:
- Midround Event named Random Chimp Event works and will pool for a ghost to take control of a monkey;
- Spawns a monkey inside a Pump Vent on the station z-level.
- Fixed round end summary;
- Cure is instant on reagent delivery and reverts Infected to their shape;
- Infects Synthetics as well, includes even Pod People (don't look at me, xenos do the same thing); 
- Synthetic species that are turned into a monkey (by admin, the disease, or any other monkeyize() call) will now have a robotic monkey sprite (they used to turn invisible);
- Monkey Leader passes on the regular Jungle Fever to other monkeys, a strain that CAN be cured with Holy Water + Banana Juice;
- Monkey Leader itself can not be cured of Jungle Fever;

Optionals/Things to add later, as a separate PR after plenty of feedback:
- Make the cure for Jungle Fever be the Monkey Leader's blood;
- Instead of pooling for a single ghost, pool for 1-3, or more. Or better yet, pick LIVING crewmembers to be infected as well;
- Fix humanize() so it restores all original player character characteristics (right now it fails to restore hair color, underwear options, maybe genitals as well) (similar to a problem with cloning)

## Why It's Good For The Game

More events are more fun. Also resurrects an antag that was pretty unique and stuck in limbo forever, hopefully in a sane way.
All hail monkee.

## Changelog
:cl:
add: Added Midround Event named Random Chimp Event
tweak: Jungle Fever is now curable with Banana Juice + Holy Water
tweak: Jungle Fever acts faster on the infected
tweak: Monkey Leader can not be cured and must be killed to stop him
tweak: Jungle Fever Cure is instantaneous
fix: Round Summary correctly displays results for Monkey antags
refactor: Jungle Fever and Monkey antag datum are refactored. This changes behavior of both substantially, and old Monkey Gamemode will not work for now
imageadd: Some grayish sprites for a Synth Monkey
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
https://www.youtube.com/watch?v=ur-ggo4Aek8

**Comment by ghost** [comment]
> https://www.youtube.com/watch?v=ur-ggo4Aek8

unironically i was thinking about putting that as an alert after a while

**Comment by The-Sun-In-Splendour** [comment]
Idk how to feel about a midround conversion antagonist but I'm willing to check it out if it ever gets testmerged

**Comment by ghost** [comment]
inativity/nobody was interested

**Pull request closed without merging**
