### PR TITLE
Adds new space ruin! - Armored Raid

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

A new space ruin that has a lot of loot for people that are willing to safe crack. As well as some basic loot like a power drill and some venders.

## Why It's Good For The Game

Space ruins are fun and will more map space this should be a nice one to fight!
Has mobs that are stronger then most, so its not free loot! 

## Changelog
:cl:
add: spess ruins
/:cl:
Loot of worth - 
Mats, diamond, bananaium, plasteel ect
AI upgrade disk
Upgraded welding goggles
Power drill / Experimental welder
SPEAR GUN
Any color paint
A katana
Synda smokes
Toys
cold igniter
A clown implant and bluespace honker!

### CODE REVIEW

**Comment by Ghommie** [comment]
There are more than just a few issues with this ruin:

- The nanotrasen security officers and the space pirates simple mobs have different factions and this will wastefully start fighting each other and die as soon as their "AI" is booted up.

- There are 6 of those sneaky ai law uploaders disguised as toy AIs in one safe. One is enough if not already too much considering what it does.

- A champion wrestling belt in another safe. I'd rather not see wrassling nerfed because of this meme. I might suggest making a new champion belt subtype that gives psychotic brawling, but I have some doubt martial arts code can really handle multiple sources of a style at once.

- The speargun in the floor safe comes with no spare ammo.

- The most of the remaining safe is pretty much junk.

- The ruin is a bit too narrow, small.

- The energy shielding is layered below the fluff broken tiling.

- The fire alarms are useless, and the firelocks by the cockpit are merely frames. Replace the latter with proper shutters and the former with shutter buttons.

- There will be no need for indestructible window grilles if you follow the above suggestion.

- every but one of the wall mounted machineries are actually located inside the wall, rather than just visually. Replace them off the wall and then var edit their pixel_y and/or pixel_x to make the objects visually located on the wall, lest you want them to be usable from every side of the wall.

- The cockpit window isn't made of plastitanium glass, nor of reinforced glass, quite odd for a shuttle.

- Useless empty display cases and blackbox deco in the middle of this tiny ruin.

- One of the space pirate is stuck between a wall, a safe and two security barriers.

**Comment by Trilbyspaceclone** [comment]
@Ghommie Woops those AI mods were ment to be be toys not even uploads x_x
The display cases are not empty, they have items in them.
The stuck space pirate is in cover and will shoot outside
The NPCs are ment to fight a little to make bullet cases and move around the Space Queen Men
Energy shield layering is a big "I dont know"
The windows are low-end do to being heavy fire doors.
Spear gun spawns with ammo in it - You get one shot that can be reloaded over and over, if you lose the spear the gun is useless

**Comment by Ghommie** [comment]
> 
> The NPCs are ment to fight a little to make bullet cases and move around the Space Queen Men

Just spawn in a couple nt secoff or pirates' corpses, a handful of empty bullet casings instead. It's more reliable.

>
> Energy shield layering is a big "I dont know"

Edit either the broken tiling or the energy shielding' layer then.

> The windows are low-end do to being heavy fire doors.

Still the heavy fire doors are just frames, not even complete ones, and shutters are still more appropriate.

> Spear gun spawns with ammo in it - You get one shot that can be reloaded over and over, if you lose the spear the gun is useless

Regardless of the reusability of their projectiles, the speargun is still a mere three 30-dmg rounds gun, uncapable of critting the average healthy spaceman in one mag dump, whose munitions. unachievable in-game minus by admin intervent or wizard's spawn guns. So don't worry adding in some spare bolts, really.

**Review by silicons — DISMISSED** [review]

**Comment by Tupinambis** [comment]
Space is already a huge balance conundrum, this would just make it worse. The spear gun, katana, and as much as it pains me, the AI upgrade disk as well, should not be in the space ruin. Just relegate it to utility and "fun" items instead. As someone who has taken out antags with space weaponry I shouldn't have access to, it's just frustrating to deal with.

**Comment by silicons** [comment]
space ruin power is already an issue let's not make it worse feel free to reopen a nerfed version.

**Pull request closed without merging**
