### PR TITLE
Removes the queen, and increases xeno variety in lavaland xenomorph ruin.

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
~~This PR is an alternative to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14075. It works to fix some of the worst features of the lavaland xenomorph hive while still making it interesting.~~ This PR aims to remove the eggsac from the lavaland queen primarily by removing the queen and replacing it with a mix of other xenomorph subtypes. The hive blessing has been readded as it has been deemed to be fine for now.

## Why It's Good For The Game
~~This PR works to maintain the integrity of the lavaland xenomorph hive while also removing both the eggsac and hives blessing from the ruin. These two items in particular are rather problematic based on what people have talked about.~~ The hive blessing syringe has been argued over again and has been deemed fine for now and has been added back.. The queen is however still potentially a problem with the eggsac.

## Changelog
:cl:
add: All xenomorph types have been added as corpses for mapping purposes
balance: The dead xenomorphs in the lavaland xenomorph hive now have more variety.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
deja vu

**Comment by shellspeed1** [comment]
And I fucked up the mapping I think. Time to go figure out how to do it right.

**Comment by Tupinambis** [comment]
> And I fucked up the mapping I think. Time to go figure out how to do it right.

Use mapmerge2. It's in the tools folder somewhere. At least I assume that's your issue.

**Comment by shellspeed1** [comment]
Okay think I did this right, someone check me though please.

**Pull request merged**
