### PR TITLE
Post This Ratvar, OR how I regained my contributor role in one simple step, OR how I buffed clock cult unknowingly.

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
## About The Pull Request
Adds a new advanced clockwork cult poster.

## Why It's Good For The Game
New posters are fun and good.

## Changelog
:cl:
add: Added Ratvar poster object
imageadd: added Ratvar poster icon
:cl:

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
I should probably show how the poster shows up in game huh

**Comment by MrJWhit** [comment]
Uh, not going to lie, this looks bad, it moves too fast, SS13 doesn't really have a lot of actively moving sprites, the text is too small, and text is also surprisingly pretty rare. 
EDIT: Also the description isn't particularly funny, but that can be fixed.

I'm just going to vote no here.

**Comment by lolman360** [comment]
justin its funny
funny = good

**Comment by KeRSedChaplain** [comment]
Post_RatVar
Here's the new poster by the way

amazing how I forgot this PR even existed the day after I made that last commit haha

**Pull request merged**
