### PR TITLE
[MIRROR] Switches database connector over to mariadb

### PR DESCRIPTION
**Pull request by CitadelStationBot**
Original PR: https://github.com/tgstation/tgstation/pull/34708
--------------------
byond supports this.

@ optimumtact

### CODE REVIEW

**Comment by MrsTonedOne** [comment]
tgs3 compatible upgrade process:

1. copy mariadb.dll to static folder
2. update server
3. update json (repo tab)
4. recompile server
5. graceful restart.

**Comment by Poojawa** [comment]
@LetterJay Has this been completed yet?

**Comment by MrsTonedOne** [comment]
I should specify that those steps have to happen after this is merged but before the server is updated.

**Comment by Poojawa** [comment]
Oh, well, I'll let him merge and update then. fwee.

**Pull request merged**
