### PR TITLE
Ports "Adds toggleable light and blinking charging light to crusher" and "Lets the kinetic crusher be one-hand carried"

### PR DESCRIPTION
**Pull request by Linzolle**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/45110/ and https://github.com/tgstation/tgstation/pull/42520 from tgstation.

## Why It's Good For The Game
Miner QoL. It's not fucking powercreep, don't say it is.

## Changelog
:cl: TerraGS / Skoglol
add: Adds toggleable light and blinking charge indicator to kinetic crusher
add: Kinetic crusher can now be one-hand carried. You'll still need two hand to use it.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
>Removing a major downside of the crusher
>Miner QoL. It's not fucking powercreep, don't say it is.

ok

**Comment by ghost** [comment]
can you split this port between one-hand and toggle lighting as 2 separate pr's if possible? The lighting will definitely be merged unless something about the code is gamebreaking or similar, but i could see people arguing against the one-hand carry

and the light toggle would be nice :)

**Comment by davidchan13** [comment]
TBH as long as crusher unwielded can't mine or be used as an effective weapon the change is fine. Thematically crusher is fine but mechanically it's worse than KA and Plasma cutter in every way and is only superior to the resonator, aka that mining nobody wants to use cause it's slower than a pick.

**Comment by Linzolle** [comment]
while one-handing the crusher, it can't be used for anything. It can't mine and has 0 force. This basically just allows you to pick something up without dropping the crusher on the ground

**Review by silicons — APPROVED** [review]

**Pull request merged**
