### PR TITLE
Totally professional fix to one word. (Nar'Sie fix)

### PR DESCRIPTION
**Pull request by Roland410**
Let's just pretend I didn't forget changing that, thaaaanks.

### CODE REVIEW

**Comment by ghost** [comment]
one invokers.

**Comment by ghost** [comment]
s.

**Comment by Roland410** [comment]
This is what I get when I decide to change something right after I sleep 12 hours. Fixed.

**Comment by ghost** [comment]
congratulations

**Review by ghost — APPROVED** [review]

**Pull request merged**
