### PR TITLE
Explosions now throw mobs around like ragdolls.

### PR DESCRIPTION
**Pull request by Useroth**
## About The Pull Request

Accidentially came up with this idea and thought it's funny enough to implement.

## Changelog
:cl:
tweak: explosions now throw mobs around
/:cl:

### CODE REVIEW

**Comment by Putnam3145** [comment]
Actually, devastation-level explosions already throw people around in /mob/living/carbon/human/ex_act, and I think if you wanna implement this you're gonna wanna do it in ex_act to begin with?

**Comment by Useroth** [comment]
I re-used the item throwing code tbh.

**Comment by Putnam3145** [comment]
Yeah, same code as the already existing code that throws mobs around when they're exploded.

If the item throwing code's in the explosion proc rather than ex_act, then yeah, it should probably go there, otherwise probably in ex_act?

**Comment by MrJWhit** [comment]
Any chance you could make a gif of it in action, so I can watch things get flung around by autistic monkies?

**Review by silicons — CHANGES_REQUESTED** [review]
do a static typecache, explosion performance is really important

**Review by Ghommie — APPROVED** [review]
Ok. Even though I don't like the extra loop.. You should do what Kev said.

**Comment by Ghommie** [comment]
Staled.

**Pull request closed without merging**
