### PR TITLE
[SPEEDMERGE NOW I THINK] Delta Chapel Driver fixes

### PR DESCRIPTION
**Pull request by EmeraldSundisk**
## About The Pull Request

Replaces the chapel morgue with coffins, reducing the number of available morgues to 2. Also corrects some area designations outside the driver.
SlightAdjustment

## Why It's Good For The Game

Fixes some things I missed by mistake. Makes coffins available from the get-go as opposed to needing to leave the chapel to get the needed supplies.

## Changelog
:cl:
tweak: CentCom has noticed the lack of coffins in Delta Station's chapel and provided some, but in exchange for reducing the chapel morgue's capacity.
tweak: Fixed a maintenance door the chaplain should have been able to open.
fix: Fixes space areas outside the driver
removal: CentCom Defense Analysts have ordered the maintenance hatch to the Mass Driver room be removed citing "security concerns".
/:cl:

### CODE REVIEW

**Comment by EmeraldSundisk** [comment]
It's come to my attention the door opens and closes but the mass driver can't be controlled via that PDA. Need to get to the bottom of that.

**Comment by chefferz** [comment]
Please remove the additional maint door beside the mass driver and replace it with a reinforced wall. Not fond of the idea of having two maint doors for lings/cultists that already speedrush the chapel during rounds, to have even more entries into what's suppose to be a secure area.

Also, since you're working on that area, could you please fix the maint door in chapel (the one in the public chapel area, on the north side) to actually be usable by the chaplain? Currently it's not ID coded and unable to be opened by chaplain, even though it's in the chapel.

**Comment by EmeraldSundisk** [comment]
I can get rid of the mass driver maintenance door, sure, but I'm not sure what'd be affecting the door north of the church "pews" (that's what you're talking about, right?) considering I didn't touch those. Maybe because it's a standard "Maintenance Hatch" as opposed to "Chapel Maintenance"? I can try that.

**Comment by chefferz** [comment]
Yeah you're not the cause of that issue, just... Since you're working on
that general area it could be a quick fix.. And good. Thanks!

**Comment by EmeraldSundisk** [comment]
HIT IT!

**Review by nik707 — APPROVED** [review]

**Pull request merged**
