### PR TITLE
(Ports /tg/station#50290) I kill bag of holding spam maybe

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Read the discussion here https://github.com/tgstation/tgstation/pull/50290

Nothing is different here to there. My arguments are pretty much the same, as the issue is the same. But even more in it's favour, we have anomaly production here before I made this change, unlike on /tg/ where that feature was still in the works. So the loss of the bag spam is slightly less harsh compared to when I initially pushed this change.

## Why It's Good For The Game

today I'll fill the halls with bombs

Someone in the bar talked about how they couldn't do this on yog because dumb dumbs would put the bags into each other. We have people will severe cum in ear syndrome, so is this any better?

## Changelog
:cl:
balance: Bags/Satchels/Duffelbags of Holding need to be crafted with bluespace anomaly cores.
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
IMO they should take any anomaly core at all. Bluespace ones are rare as shit

**Comment by lolman360** [comment]
finally

good job anne

**Comment by SmArtKar** [comment]
Probably you should make BS anomalies much less rare

**Comment by YakumoChen** [comment]
finally, I can assault the station with singularities and no longer fear the threat of bluespace bags

**Comment by necromanceranne** [comment]
You can make bluespace anomalies with toxins.

**Comment by keronshb** [comment]
Please no.

This also makes the ninja objective hard as shit.

We've already hugboxed the bags enough here too.

**Comment by ghost** [comment]
we can replace the boh objective

**Comment by necromanceranne** [comment]
Wait there is an objective? I didn't know that. I'll replace it in the pr.

**Comment by Tupinambis** [comment]
As much as I dislike techweb shit and scaling power, bags of holding are not even remotely the problem. BoHs already have downsides and are seldom ever going to decide the outcome of a fight.

People are just going to use alternative methods to bypass this nerf anyway (bluespace body bags and such), and this honestly just screws over engineers and miners who benefit a lot from having bags of holding. 

And with the bag of holdings being super rare, I almost guarantee science will just hoard them and people will inevitably fight over them. I see little benefit from this PR.

**Comment by necromanceranne** [comment]
Whoops wrong button.

**Comment by necromanceranne** [comment]
Anyway, this isn't matters of individual fights, but larger scale perspectives on problem solving. BoH makes it do that deciding exactly what gear to take is irrelevant. You can access everything you need fairly readily, including items normally only storable on your back at the exclusion of a bag. It's a heavy weakness of many items the BoH resolves.

This isn't a problem. This is the fun bit of the item. The problem is in it being mass producable and inconsequential in acquiring one.

Also I genuinely don't really think miners ever needed them? They are so utterly luxury that I feel msot miners screaming to have one most rounds just desperately wanted to acquire as much power as humanly possible. Same with nightvision. I've never seen it as a mandatory pickup for them. Meanwhile, what does an engineer lose exactly they have the luxury of hauling duffels in-hand if they need to transport materials somewhere since, unlike miners, they aren't fighting on the move or performing reflex heavy tasks that require handuse. I've never needed a BoH as an engineer don't be silly.

Also I thought Bluespace Bodybags were unable to be crumpled while they have items. I'll just nip that in the bud as well while I'm here if not.

**Comment by keronshb** [comment]
> 
> 
> Anyway, this isn't matters of individual fights, but larger scale perspectives on problem solving. BoH makes it do that deciding exactly what gear to take is irrelevant. You can access everything you need fairly readily, including items normally only storable on your back at the exclusion of a bag. It's a heavy weakness of many items the BoH resolves.
> 
> This isn't a problem. This is the fun bit of the item. The problem is in it being mass producable and inconsequential in acquiring one.
> 
> Also I genuinely don't really think miners ever needed them? They are so utterly luxury that I feel msot miners screaming to have one most rounds just desperately wanted to acquire as much power as humanly possible. Same with nightvision. I've never seen it as a mandatory pickup for them. Meanwhile, what does an engineer lose exactly they have the luxury of hauling duffels in-hand if they need to transport materials somewhere since, unlike miners, they aren't fighting on the move or performing reflex heavy tasks that require handuse. I've never needed a BoH as an engineer don't be silly.
> 
> Also I thought Bluespace Bodybags were unable to be crumpled while they have items. I'll just nip that in the bud as well while I'm here if not.

Isn't the difference between here and TG is that we actually do have items that take up more space in our BOH?  Correct me if I'm wrong but we don't even allow backpacks inside of BOH anymore, as well as more than like a couple of guns since they become too bulky.

**Comment by UselessTheremin** [comment]
An anomaly core is waaaaay to steep. I would just say to double the price, because working hard to get one feels better than getting one through RNG. The main people receiving this nerf are miners who really deserve the extra space as almost all megafauna drops are bulky items.

**Comment by NalyKalZul** [comment]
> An anomaly core is waaaaay to steep. I would just say to double the price, because working hard to get one feels better than getting one through RNG. The main people receiving this nerf are miners who really deserve the extra space as almost all megafauna drops are bulky items.

we also now have durathread bags, what if boh's requires one of them to craft them.
so you basically take a durathread bag, and apply a bluespace harness to it with some basic tool steps.

so you can't just spam print them, you have to craft every single one of them, with durathread crafting prior to it.

**Comment by Tupinambis** [comment]
I like Nalykal's idea. It encourages interdepartmental cooperation and gives the bag a bit more of a dynamic than "press button to print"

**Comment by necromanceranne** [comment]
I'd rather honestly keep the production of the bags in a single department doing their departmental duties, like toxins, than shoehorning in the completely false notion of 'interdepartmental co-operation' like that has any functional impact in the game. If you can make one bomb, you can make 8 bombs and make 8 bluespace cores.

Either bags disappear due to forcing another department to graciously waste their resources for your sake, which happens quite infrequently without a lot of hassle that some people genuinely can't be arsed to do. Or, and largely as a result of the previous feelings about having to go through a third person, they just produce an infinite quantity because that person unrelated to the department took all the necessary equipment and made the durathread themselves, which is the more likely scenario.

>Isn't the difference between here and TG is that we actually do have items that take up more space in our BOH? Correct me if I'm wrong but we don't even allow backpacks inside of BOH anymore, as well as more than like a couple of guns since they| become too bulky.

You can fill your bag with an obscene amount of guns. It's honestly only other bags that can't fit. You can fit a lot of bulky guns in them just fine.

> An anomaly core is waaaaay to steep. I would just say to double the price, because working hard to get one feels better than getting one through RNG. The main people receiving this nerf are miners who really deserve the extra space as almost all megafauna drops are bulky items.

I would ask you to look at the picture again. I want you to know that bluespace bags are expensive as fuck, taking quite a lot of resources per bag to produce. The price is nothing. Material limitations are not limitations at all, because you'll always have more than a lot of excess materials due to parts grant massive multipliers in ore value.

**Comment by The-Sun-In-Splendour** [comment]
You do know bluespace anomalies are one of the rarest anomalies if not the rarest, right?
BoHs are already good enough (ever since you cannot cary more than bulky in them)
:\

**Comment by lolman360** [comment]
you can literally make bluespace anomalies via implosion compressor/cargo now


also:
>almost all megafauna drops are bulky items

hm i wonder if there was a way to balance powerful items by restricting their ergonomics, forcing them to be placed in a slot with tradeoffs or where they are extremely visible

**Comment by necromanceranne** [comment]
Lol it's failing on something I didn't do nice what the fuck actually though?

**Comment by necromanceranne** [comment]
What the actual FUCK is going on.

**Comment by Hatterhat** [comment]
make bohcrafting a radial no balls

**Comment by necromanceranne** [comment]
Aaaaaaaah what is with this fucking mythril coin what the fuck

**Comment by lolman360** [comment]
@necromanceranne it's segfaulting during travis try an empty commit

**Comment by necromanceranne** [comment]
Well this is truly out of my league.

**Comment by silicons** [comment]
uhhhhhhhhhhhhhh

**Comment by lightcat** [comment]
There is no reason for this nerf. We don't have this problem on citadel.

**Comment by DeltaFire15** [comment]
This does not seem to be needed, considering we have nerfed BoHs (no more bags in BoHs), aswell as have somewhat adjusted material balance to make them not *as* mass printable.

**Pull request closed without merging**
