### PR TITLE
drastically lowers the damage-related benefits of combat mode

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
combat mode has been an issue for a long time because one person will cockblock anyone trying to make it not ridiculous in terms of its benefits

do i expect bhijin to cockblock this pr (also this isn't meant to be insulting, love you really bhijin)
yes but it's worth trying because it should seriously make combat more fun, especially with wounds

for the exact changes:
1.5x damage buff when attacking someone not in combat mode when you are is 1.2x
0.5x damage debuff when attacking someone in combat mode when you are not is 0.8x
0.5x damage debuff for laying down is now 0.7x

martial art damage roll that utilizes your punch damage is changed so attacking someone not in combat mode does 1.2x, from 1.5x, attacking while not in combat mode does 0.8x instead of 0.25x (yes, really.), and attacking while laying down does 0.7x instead of 0.5x

## Why It's Good For The Game
other then being absolutely awful, its awfulness has been highlighted by wounds which proc far too often due to combat mode drastically increasing damage

## Changelog
:cl:
tweak: combat mode now has weaker buffs in terms of damage dealt and took for being or not being in the mode
tweak: damage debuff for laying down has been decreased from 0.5x to 0.7x
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
Or just remove combat mode because it literally is just CLICK THIS BUTTON TO DO INCREASED DAMAGE.
Add in interaction mode that gives all the special interactions combat mode give and call it a day. (without the increased damage lol!)

In case you don't know I absolutely despise the idea of combat mode.

**Comment by CameronWoof** [comment]
The person above me is exceedingly intelligent and has a completely fantastic idea. I have never in my life felt such intense joy and gratitude as I did when reading their comment, and its introduction would be wildly beneficial in every way. The only thing missing is that it should perhaps not halt stamina regeneration or affect aim accuracy.

Fantastic idea, though.

This PR is nice too.

**Comment by necromanceranne** [comment]
Combat mode as a way to add additional depth to action is why you should keep it, rather than a binary state of whether you are or are not shit at combat in this present moment. Removing combat mode entirely is reductive, and you have no idea how much better things are made by it's presence. It just needs a little work to be set right. 

Anyway, I thought most of these effects were already removed by ghommie.

Actually why not just remove them entirely? The numbers here are so tiny as to render it entirely inconsequential so why have it in the first place.

**Comment by timothyteakettle** [comment]
I am not against combat modes existence and I can't remove it without a 100% chance of bhijin cockblocking the pr anyway, wounds doesn't work with damage with damage bonuses like this and I really don't want to work further on wounds when it's impossible to balance damage-threshold-wise because damage changes so much with combat mode

by reducing its effects im trying to reach an agreeable midpoint so I can continue balancing wounds

**Comment by CameronWoof** [comment]
It's the special control scheme and interactions that make combat mode _cool_. All of the braindead statistical benefits just serve to make it _mandatory_. Ergo garbage.

Rather than a cool system that adds complexity to the top end of combat, it's a mandatory system that adds extra work to learning how to fight at even the most basic level.

Elitist, punitive design. Whether that was the intent or not.

**Comment by Trilbyspaceclone** [comment]
Every time I see combat mode I think "Why isnt their a peacefull mode?" to toggle with it...
It would be nice to have a way to sorta pick and chose what your mode is rather then "Higher damage and defense!" to "More stam regen but lower damage and lower defense"
Were being in full flight mode and full fight mode. Personally I like taking the peacefull quirk more just so I stop hitting myself and misstakenly hitting others when, could be a thought for a different rework tho.

Anywho I like these changes <3

**Comment by ghost** [comment]
tbh remove all the damage modifiers and if bhijn tries to close it call him a cockweed and call literally the entire maintainer team to counteract his headmin status

admins literally almost got jumped by dudes that write lore or something how strong can one headmin be

**Pull request merged**
