### PR TITLE
Lighting fix

### PR DESCRIPTION
**Pull request by ghost**
This should fix lighting anomalies with unlit areas.
Thanks, PJB, for being the only one who understands this system.
Also removes dynamic lighting from shuttles, for now.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
u da man pjb

**Comment by PJB3005** [comment]
You should still make shuttles ignore turf level variables for lighting because there's still gonna be anomalies otherwise.

**Comment by ghost** [comment]
How? Dynamic lighting is disabled there now so it shouldn't do anything on shuttles.

**Comment by ghost** [comment]
Nevermind, I see it now.

**Pull request merged**
