### PR TITLE
[READY]Removes tasers from security officers, cargo, the armory, advanced energy guns, the warden blaster and otherwise any ingame way to get tasers outside of Admin or Magic. Only the HoS gets a weaker version.

### PR DESCRIPTION
**Pull request by GrayRachnid**
## About The Pull Request
Title says it all basically. Tasers are removed outside of Magic or Admin intervention. I was asked to make this PR after having played around with the taser re-work for the past month. The taser re-work was initially seen as a good change from the 3-tap taser before it. However, this turned out to be a more infuriating change than a good one. Anyone on the receiving end of a taser is more frustrated than enjoying the game. At least with the old tasers you had a chance to escape if security was sloppy. This changed 3-tap taser to 1-tap taser that fucks you over for a good 15 seconds. 

Knowing that, i've reverted my stance on tasers to what I thought of them before the changes and I believe others would agree with this. Tasers in their current iteration are too frustrating to play against.

Recent kevinz buffs to disablers already makes them good so i'm not changing anything about them despite removing tasers 👍 

Edit: Warden shotgun replaced with the blaster version. It has two settings: Scattered disablers and focused disabler. The focused disabler deals around 75 stamina damage per shot and can instantly disable a limb.

## Why It's Good For The Game
This removes removes a frustrating weapon from security or anyone's hands and makes ranged combat a bit more than a single taser hit. Officers still have their stun batons but that involves risking themselves.

## Changelog
:cl:
add: Added new disabler sprites from teegee
del: Removed tasers from sec officers, hos laser, advanced energy gun, cargo and armory
tweak: tweaked turrets and borgs to only have disablers
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
I'd personally give the hos gun a weaker disarming taser without the new effects, or a really really short (1 second or something) of the new ones, but I'm not going to hurt too much either way. Just a suggestion for making HoS gun special.

**Comment by ghost** [comment]
what if it was changed to be a realistic taser?
1 use that needs reloading after every use, can't penetrate armor and has a chance to fail even on clothed people

**Comment by GrayRachnid** [comment]
Edited title and OP to include further changes.

**Comment by GrayRachnid** [comment]
@kevinz000 might want to tag it again.

**Comment by kiwedespars** [comment]
good change.

to say why: they went from a near almost instant win weapon to something where it gimps every chance you have at actually fighting back. your accuracy with guns is decreased, your damage with melee is 75% less and it's also slower. your stamina is drained to a point, and it went from that near almost instant win weapon to an instant win weapon.

**Comment by ghost** [comment]
ok

**Comment by Fractious** [comment]
To be honest, unless someone manages to save tasers somehow in a way that doesn't make them overpowered I think tasers needs to go. Not being able to turn on combat mode for 5 seconds is just unhealthy to play against, and you can't even force yourself up to run away which gives a free follow-up for stunbatons. They've been a 1 hit insta-win weapon for too long, and the meta needs to shift imo.

**Comment by ForrestWick** [comment]
Tasers were a major issue because they were just an "I win" button that sec got roundstart and antags would rush like mad because of the stun meta for combat. The fact that they now will keep you from shaking yourself up to boot makes them even WORSE than they were originally, especially with people starting to learn disablers are busted as shit. This removal only means sec players have to temporarily adjust to the things TG has been on for ages anyway, and for good reason. There's no solving this issue, and nobody has the time or patience to even attempt balance.

+1 from a regular antag and sec/command player

**Comment by Ghommie** [comment]
Remade in #10710.

**Pull request closed without merging**
