### PR TITLE
Removes prevent from leaving alive, maroon objective

### PR DESCRIPTION
**Pull request by dzahlus**
## About The Pull Request
What it says on the tin

## Why It's Good For The Game
I literally only see either permakill/lockerstuffing or round end shuttle aggrograb yeet or objective begging "oh please don't go on the shuttle". Terrible, awful objective that only promotes lame and toxic gameplay and goes against our whole do not game end do not objective rush policy.

## Changelog
:cl:
del: Removed maroon objective due to toxic gameplay behaviour
/:cl:

### CODE REVIEW

**Comment by dzahlus** [comment]
oh god this is like old ass code and this is gonna take forever to do properly im gonna cry

**Comment by ghost** [comment]
"hurr durr round removal bad"
we literally have respawn (we shouldn't, in my opinion, but that's not the point)
might as well remove objectives completely at this point

**Comment by KrabSpider** [comment]
> "hurr durr round removal bad"
> we literally have respawn (we shouldn't, in my opinion, but that's not the point)
> might as well remove objectives completely at this point

When was the last time you rolled antag again?

**Comment by keronshb** [comment]
> 
> 
> "hurr durr round removal bad"
> we literally have respawn (we shouldn't, in my opinion, but that's not the point)
> might as well remove objectives completely at this point

Objectives are in the talks anyway.

Respawn is absolutely fine.  Do you want midrounds and ghost roles removed too?

Round removal IS bad, including on some antags like lings and suckers.  Because it completely halts the flow of a round.

**Comment by dzahlus** [comment]
> "hurr durr round removal bad"
> we literally have respawn (we shouldn't, in my opinion, but that's not the point)
> might as well remove objectives completely at this point

ah yes the based man spaghetti himself bringing outstanding arguments to this PR like these gems
#12451
#13019
#14028

**Comment by ghost** [comment]
> > "hurr durr round removal bad"
> > we literally have respawn (we shouldn't, in my opinion, but that's not the point)
> > might as well remove objectives completely at this point
> 
> ah yes the based man spaghetti himself bringing outstanding arguments to this PR like these gems
> #12451
> #13019
> #14028

i'm so glad this tradition hasn't died out yet

**Comment by ghost** [comment]
> Respawn is absolutely fine. Do you want midrounds and ghost roles removed too?

I don't want midrounds and ghost roles removed, I want them to be the ONLY way to rejoin the round if you don't get revived.

>Round removal IS bad, including on some antags like lings and suckers. Because it completely halts the flow of a round.

...what does that even mean?

**Pull request merged**
