### PR TITLE
Cyborg UI Beautification and Improvements

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request 

I've cleaned up some some of the cyborg module sprites, modernized some of the action/notification sprites (namely APC hacking and Doomsday), improved coloration and make the HUD overall more stylized, and moved the language selection so it is floating in a less awkward place.

Example: https://imgur.com/a/bYwmw6u

## Why It's Good For The Game

Some of the cyborg hud elements are well over two years old, and it lacks a visually distinct appearance. Some of the sprites also just looked bad. This hopefully addresses those issues and makes the HUD look prettier

## Changelog
:cl:
imageadd: Beautified and stylized the cyborg HUD sprites, animated and cleaned up some of the old, modernized APC hacking and Doomsday sprites, 
tweak: moved cyborg language select above the radio icon, instead of above the picture icon.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
As I said on the discord, I don't think the Borg HUD is an improvement. At most its a recolor that takes away the very minor UI hints the module slots show currently, and changes the light icon to a flash icon, something that will confuse new players and doesnt add anything substantial to the design. 
The only addition i can actually see is a change to the language icon.

Two years is not a substantially long time for the age of a UI when several sprites are still present from the original game.

**Comment by davidchan13** [comment]
Agree with Yakumo, the flash light change is just bad and the flashlight is a much better indicator of the buttons function.

**Comment by Tupinambis** [comment]
Updated with recommended Sprite changes

**Comment by Tupinambis** [comment]
Updated Sprites on Request https://imgur.com/a/4sgFM6e

**Comment by YakumoChen** [comment]
A lot nicer

**Review by silicons — APPROVED** [review]

**Pull request merged**
