### PR TITLE
Stops the preloaded lethals shotgun meme, take time to load yourself with the shotgun beanbags/buckshots/slugs you get supplied with

### PR DESCRIPTION
**Pull request by improvedname**
:cl: Improvedgay
balance: Balances magically loaded guns that arent used, and shouldnt be loaded at that point
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Why though

**Comment by improvedname** [comment]
Because some wardens tend grab a gun, pump, shoot. WHOOPSIE POOPSIE ITS WAS BUCKSHOT I DIDNT KNOW this way any shotgun contents are non lethal the least, if you want lethal guns you swtich the ammonution

**Comment by deathride58** [comment]
So this is a salt PR?

**Comment by improvedname** [comment]
Not my salt atleast 🤷‍♂️

**Comment by deathride58** [comment]
Closing since this is primarily a blind salt change without much justification beyond that

**Pull request closed without merging**
