### PR TITLE
allows players in deadchat to see explosions

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

explosions and EMP pulses now send a deadchat message saying where it happened, the size, and a button to jump to the epicenter.

## Why It's Good For The Game

it's good to be able to jump to see the cool kabooms

## Changelog
:cl:
add: explosions now get broadcasted to deadchat.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Could you remove the adminmessage then? It should still be logged and everything, but I'd rather not have the same message twice while I'm adminning.

**Comment by Putnam3145** [comment]
These need the deadchat spans, confused the shit out of me when I tried testmerging, thought it might've displayed to everyone.

**Comment by silicons** [comment]
@Detective-Google

**Comment by Detective-Google** [comment]
> These need the deadchat spans, confused the shit out of me when I tried testmerging, thought it might've displayed to everyone.


Was using the emergency shuttle call etc messages as a guideline which doesnt use it, bleh.

**Pull request merged**
