### PR TITLE
Better CE tools and advanced tool sprites

### PR DESCRIPTION
**Pull request by MrJWhit**
## About The Pull Request

Port of sprites courtesy of yogstation:
https://github.com/yogstation13/Yogstation/pull/9205

This doesn't port tricorder sprites, because, well, we don't have that.

## Why It's Good For The Game

I think they look nice

## Changelog
:cl:
tweak: Ports sprites from yogstation for CE and advanced tools
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
the hand drill is alright but the jaws are absolutely soulless

**Comment by MrJWhit** [comment]
The current jaws also doesn't make any sort of sense at all. Plus, have you **seen** those in-hand sprites? They're awful.

**Comment by YakumoChen** [comment]
The sprites are so small, you can't actually tell what the function is on them visually anymore, at a glance.

**Comment by keronshb** [comment]
I don't really like these.  I can't even tell what the jaws are anymore.

**Comment by DeltaFire15** [comment]
Hand drill: Eh looks pretty much the same.
Jaws: Yeeah no that just looks bad, like a amalgamation of RCD and something unidentifiable.

**Comment by silicons** [comment]
not video gamey enough

**Pull request closed without merging**
