### PR TITLE
what if i just gave the x01 an rmb taser while also giving it, like, way more disablers

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
see title
+ x01 gets sec-taser tier electrode on combat mode rmb
+ x01 now fires hos disablers, which use 25 energy instead of a regular disabler's 40
(the above has the effect of granting the hos gun **40!!** max disablers, if you don't use literally any other firemode)
## Why It's Good For The Game
dzahl is a hack
## Changelog
:cl:
balance: The X-01 now has incredibly scuffed power efficiency for spitting disablers down a hallway while also getting an auxiliary taser.
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
Delete the particle defender

**Comment by LordSaladin** [comment]
disabler goes brrr

**Comment by DeltaFire15** [comment]
Not really on board with the timeline of
HoS revolver gets added
Revolver gets buffed because it was seen as too weak
Now the X01 is getting buffed because the Revolver is 'better'

Especially considering as opposed to the Revolver, the Multiphase gun can use all its charge on one single ammo type aswell as it being able to switch between them very easily, making it more flexible than the Revolver.

Leaving this to the other maintainers though.

**Comment by DeltaFire15** [comment]
Since apparently noone else feels like looking at it, guess I'll go ahead with my judgement and close it.

**Pull request closed without merging**
