### PR TITLE
[REVIEW PLEASE] Minimum Megas/Tendrils For Lavaland But Cleaner I Swear

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
implements an incredibly scuffed subsystem for minimum spawns

ng yrnfg vg'f abg gnpxvat guvatf bagb gur vavg fhoflfgrz naq hfvat gjb ybat tybony yvfgf bs ghesf

issues at the moment:
nnnone? it should be fine from here
## Why It's Good For The Game
"god, i sure love having literally two tendrils and only one colossus", said literally no one, ever
## Changelog
:cl:
add: The wastes of Lavaland and the icy caverns of Snow Taxi rumble in unison.
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
tell me when this is tested because this seems like some wackass code

**Comment by Hatterhat** [comment]
rest assured it is entirely dogshit code and i'm going to keep poking at it with a stick until it's decidedly less wackass

**Comment by Hatterhat** [comment]
good news: new fire-once subsystem that might be cleaner
bad news:
`[00:04:14] Runtime in minimum_spawns.dm,78: type mismatch: the lava (1,1,5) (/turf/open/lava/smooth/lava_land_surface) + 1
  proc name: Initialize (/datum/controller/subsystem/min_spawns/Initialize)
  src: Minimum Spawns (/datum/controller/subsystem/min_spawns)
  call stack:
  Minimum Spawns (/datum/controller/subsystem/min_spawns): Initialize(182542)
  Master (/datum/controller/master): Initialize(10, 0, 1)`
i'll poke at it again eventually

**Comment by Hatterhat** [comment]
it works

**Comment by Hatterhat** [comment]
@silicons god damn it what the FUCK is with travis segfaulting all the goddamn time anyway jesus christ

**Pull request merged**
