### PR TITLE
Adds a new melee weapon for Security.

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

Adds a new weapon choice for Security, the Riot Suppression Electrostaff. It's a huge (no bohs) quarterstaff that needs two hands to hold or use, can be held on back or suit slot of certain armors, and has two modes. It also has 30 melee block (10 ranged.)

Lethal mode does 20 burn.

Stun mode does 45 stam,1 hardstun and 2 softstun using the knockdown proc (i don't understand bhijin please help) but drains a lot of stam on use.

## Why It's Good For The Game

A new weapon/utility for Sec that's not a straight upgrade (see: AEG, teleshield), but instead an alternative to the stunbaton. As it can take down threats pretty quick it's not a bad choice for things like cult/revs/newcops/gang, but its bulk makes it a logistical challenge normally.

Melee block stops it from getting dominated in CQC by sharpened cult swords or eswords, the small range block offers minor protection against things like op guns/ stolen guns in rev/ gang weapons
Icondiff broke. [Here.](https://user-images.githubusercontent.com/22850904/65421769-e951b080-de47-11e9-812d-80a891c24189.gif)

## Changelog
:cl: lolman360, Toriate, Cross
add: NT has approved its prototype Riot Suppression Electrostaff for research and development at your station. 
soundadd: Sounds for the staff.
imageadd: Sprites for the staff, handcrafted by Toriate.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
where the fuck is the DM file

**Comment by B1gb3ast** [comment]
Opinion: At the moment this thing is just a bigger damage stun baton. It looks cool, but it doesnt really scream riot supression; it just screams “FUCK YOU TRAITORS I HAVE A DESWORD TOO NOW”

If you were to lower the damage slightly and give it a CM xdnomorph style sweep attack, it would actually be such a fucking cool weapon to use. Imagine that feeling when you rush into a crowd of revs and electrocute three of them in one fell swoop.

**Comment by lolman360** [comment]
@deathride58

**Comment by CdrCross** [comment]
@B1gb3ast Counterpoint being it also kinda prevents you from using any other weapons. It's forced 2 hander which can't fit in backpacks, so you're dedicating yourself to being a melee specialist.

**Comment by YakumoChen** [comment]
AEG isn't a straight upgrade, especially since I'm about to give it back the intended downside of using one

**Comment by lolman360** [comment]
when the PR was created it is, so /shrug
bulky AEG when

**Pull request closed without merging**
