### PR TITLE
Disks are now smaller

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

2 --> 1

## Why It's Good For The Game

Kinda silly you can't even fit 20 disks in a bag post-volumetric nerf.

## Changelog
:cl:
balance: Disks are now smaller.
/:cl:

### CODE REVIEW

**Comment by WhiteHusky** [comment]
Might be wise to use a constant.

**Comment by silicons** [comment]
@WhiteHusky i put all volume defines in that one specific file, it'll be extremely easy to see/modify later

**Comment by ghost** [comment]
I keep reading the title as "Dicks are now smaller".

**Review by Linzolle — APPROVED** [review]
sure

**Pull request merged**
