### PR TITLE
Revert "removes two unused sprites"

### PR DESCRIPTION
**Pull request by silicons**
Reverts Citadel-Station-13/Citadel-Station-13#13184

According to @deathride58 the images are required in addition to the .txt for the license, rather than only the latter.

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
Oh man I sure do love a 2.5kb sprite that says "HEY LICSNED BY ME LOL" because .txt files aren't fucking enough 😖

**Comment by moltoretardo** [comment]
Can we also revert the whole thing? Drakeborgs are one of the worst fetish content that got merged because of the headmin’s “taste”. Nobody likes them and they’re just another waste of space that brings 2.5kb of uselessness.

**Comment by MrJWhit** [comment]
Just revert the whole thing. This is adding a second license, nobody plays them, it doesn't fit the aesthetics, it's just causing issues from day 1. We can just move on.

**Comment by jack-avery** [comment]
why

**Comment by Putnam3145** [comment]
we can remove them later if we merge this and merging this now is required so I'm doing it

**Pull request merged**
