### PR TITLE
Hyperblade restored to uplink

### PR DESCRIPTION
**Pull request by keronshb**
## About The Pull Request

Re adding the Hyperblade to the uplink.  Hyperblade is also poplocked like dsword. It has a fundamentally different playstyle compared to the dsword, so it doesn't need a choice beacon.

## Why It's Good For The Game

Hyperblade is a nice extra addition to change up staleness.

Also a literal Dee moment.

## Changelog
:cl:
add: Hyperblade to uplink with poplock
balance: Removes combination of two Dragon Tooth Swords while keeping it for regular eutactics.
/:cl:

### CODE REVIEW

**Comment by dzahlus** [comment]
speedmerge hrnnngh

**Comment by necromanceranne** [comment]
You should add a beacon to summon your sword of choice. And by summon, I mean discreetly place into your hand.

You should also axe the mindbogglingly weird statistical discrepancies between these items.

I am also fairly sure this wasn't undocumented. It was almost definitely deliberate on the part of Ghommie to remove item bloat from the uplink. These are still item bloat as far as I'm concerned.

**Comment by keronshb** [comment]
> 
> 
> You should add a beacon to summon your sword of choice. And by summon, I mean discreetly place into your hand.
> 
> You should also axe the mindbogglingly weird statistical discrepancies between these items.
> 
> I am also fairly sure this wasn't undocumented. It was almost definitely deliberate on the part of Ghommie to remove item bloat from the uplink. These are still item bloat as far as I'm concerned.

Honestly the removal of "bloat" just made things more stale.

**Comment by Hatterhat** [comment]
> You should add a beacon to summon your sword of choice. And by summon, I mean discreetly place into your hand.

yeah but make it so there's an alt function to the beacon that puts it in my hand loud and obviously it'd be epic

**Comment by dzahlus** [comment]
i agree that the non eutactic blade, while being a deus ex reference, is literally copy pasted esword. THE HYPERLBADE HOWEVER IS THE MOST BASED MELEE WEAPON IN THE GAME. It is actually very unique in playstyle compared to the desword.

**Comment by necromanceranne** [comment]
> Honestly the removal of "bloat" just made things more stale.

There is already two esword equivalent weapons in the uplink, but they both serve different purposes. Having an item that does literally the same thing as another item but only having a vaguely different inhand sprite is the definition of bloat. You should pick one or the other, not just readd a sprite change and fill up the already fairly cluttered uplink.

**Comment by silicons** [comment]
make it a choice beacon

**Comment by keronshb** [comment]
> 
> 
> make it a choice beacon

How?

I tried and summons a pod and an empty box.

**Comment by keronshb** [comment]
> 
> 
> make it a choice beacon

I removed Dragon Tooth and just left the hyperblade in.

It doesn't need a choice beacon since it plays fundamentally different compared to the dsword.

**Pull request merged**
