### PR TITLE
[JUST NEEDS MORE SPRITES] Adds taur variants for worn item sprites

### PR DESCRIPTION
**Pull request by deathride58**
See title. This PR adds taur variants of wearable item sprites. Featuring sprites from Vivi on Discord! (I've no idea if you're on github, man)

:cl: deathride58
add: Hardsuits now have different variants for nagas, and hardsuit helmets now have different variants for those with snouts! Sprites by Vivi on Discord. NOTE: since the taur sprite layer is now above the suit layer, this may result in visible oddities with wearables that lack taur sprites. This will be resolved as more taur sprites are added.
add: This also paves the way for future taur-specific sprites.
/:cl:

## TODO:

- [x] TESTING. TESTING. TESTING. TESTING
- [x] actually put the sprites in
- [x] add support for different helmet/mask sprites when a snout is present
- [x] Teeeeeesting
- [ ] Beg Vivi for more sprites
- [x] TESTING.

### CODE REVIEW

**Comment by deathride58** [comment]
This basically just needs more sprites, and it's done.

**Comment by Poojawa** [comment]
What sprites are missing from this?

**Comment by deathride58** [comment]
Right now, this PR only has naga sprites for the base engineering hardsuit and the chief engineer's hardsuit, along with snout variants for those two suits' helmets.

The engineering hardsuits lack variants for other taurtypes, and every single other hardsuit lacks variants for taurs.

**Comment by Poojawa** [comment]
p.sure the additions I gave you are good. the basic inhands sprites are fine as well.

**Comment by Poojawa** [comment]
S T A L E

**Comment by deathride58** [comment]
ZZZZZzzzzzzzzz.....

**Comment by Poojawa** [comment]
reeeee. probably need to rebase. since that merge is d u m b due to github

**Comment by deathride58** [comment]
rrrrrrrrrrrrrrreeeeeeee

**Comment by Poojawa** [comment]
I added 'wolf' 'horse' and the few missing naga suits, and edited them so they weren't a 1:1 copy.

**Comment by deathride58** [comment]
Closing since this is stale as fuck and probably doesn't even compile anymore

**Pull request closed without merging**
