### PR TITLE
Port - Lets you tape knives to cleanbots. You know, if you really want to. #47590/tgstation/Ryll-Ryll 

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

You can now tape knives to cleanbot.
Cleanbots with knives will stab anyone crossing over them. 

https://github.com/tgstation/tgstation/pull/47590

image

## Why It's Good For The Game

Robots with knives are funny.

## Changelog
:cl:
add: You can now tape knives to cleanbots
/:cl:

### CODE REVIEW

**Comment by Echopsychotic** [comment]
Why the need for a knife bot?

**Comment by Trilbyspaceclone** [comment]
The cleanbot has past the pomerium!

**Comment by Ryll-Ryll** [comment]
This'n too https://github.com/tgstation/tgstation/pull/47816

**Comment by shellspeed1** [comment]
The ultimate weapon of mass destruction.

**Review by Linzolle — CHANGES_REQUESTED** [review]
add the followup PR by ryll-ryll as well

**Review by Linzolle — APPROVED** [review]

**Pull request merged**
