### PR TITLE
Malf Overridden APCs are EMP Proofed

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

When an Antag AI hacks an APC, it becomes immune to EMPs.
Machines in the same room as the APC are still affected.

## Why It's Good For The Game

Getting killed as a malf AI because some funny man floated outside your core and threw a single grenade is honestly the dumbest thing to experience. EMP'd APCs are disabled for a ridiculously long time and it often only takes one or two to kill you, without even needing to ever go inside the satellite. You're made a sitting duck for several minutes and it's not a fun way to die.

With this change, an overridden APC is no longer affected by an EMP. While this doesn't stop all your turrets, borgs, and Pingsky from being disabled for half a minute, it at least ensures whoever is trying to wipe your code has to actually look you in the face to do it, and gives you a fighting chance.

## Changelog
:cl: YakumoChen
balance: APCs hacked by an antag AI are EMP-Proof
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
What's the solution that isn't "maxcap it" then?

**Comment by YakumoChen** [comment]
Nothing, but at least the AI can detonate toxins first.

**Comment by YakumoChen** [comment]
Have you tried fighting the core defenses?

**Comment by timothyteakettle** [comment]
removing the way to counter AIs entirely is not the way forward and this just seems like a knee jerk salt pr

**Comment by MrJWhit** [comment]
Ah yes, fun and interesting gameplay.
image

**Comment by moltoretardo** [comment]
🧂

**Comment by YakumoChen** [comment]
It's not even a full counter, it just stops you from making the AI a complete sitting duck for the rest of its short lifespan. Reconnecting to the APC when you're depowered sucks and doesn't actually do anything because there's a massively long timer before anything reboots. Winning without ever entering the AI sat (or bombing it) is absurdly dumb.

This also doesn't stop you from draining the SMES with repeated EMPs, which eventually kills the AI as well.

**Comment by YakumoChen** [comment]
There's also plenty of other ways to just cheese it, including (and most easily) just making an unlinked cyborg

**Comment by ForrestWick** [comment]
Why not make this a 20 point malf power?

**Comment by moltoretardo** [comment]
Are we talking about the antag that can blow up electronics, plasma flood, stay stealthy for as long as they need it, convert, remote self-destruct borgs like walking bombs, can hide in the station using a borg, can raise electronics to fight, blow up pipes and gets free controles over everything on the station. Making an unlinked cyborg is easy when everything is burning.

**Comment by YakumoChen** [comment]
it would require more code than I am capable of @ForrestWick

**Comment by ForrestWick** [comment]
Fair enough but it shouldn't be too hard to look at how the other powers are coded and work from there. I'm sure some of the more experienced devs would help out considering malf could use some attention anyway.

I will say this tho, malf ai being a glass cannon definitely works better as a game mode than one traitor among others. I think I'd rather see a sacrifice of a malf AIs gamer powers in exchange for something a little more balanced. If I had time and energy, I might try my hand at such a project, but sadly my hands are kinda tied. Either way, I'd say your best bet would be to look into making this an ability that can be bought instead of a free buff, even if you aren't code savvy

**Comment by YakumoChen** [comment]
20 malf points, as well, I would consider pretty minor. That's only 2 APCs and the only APC you really are going to want the power for is the one near your AI core regardless. I think it's kind of negligible and the PR seems fine as-is. A power like that won't stop someone from EMPing your defensive turrets in other rooms or EMPing your borgs.

**Comment by ForrestWick** [comment]
Oh no, I meant 20 points for emp proof APCs period

**Comment by YakumoChen** [comment]
Drop in the bucket as far as resources go (and a noob trap for anyone who doesn't take it immediately) and doesn't feel worth the time to code a whole proc and power for something that's pretty essential.

**Comment by YakumoChen** [comment]
> 
> 
> Are we talking about the antag that can blow up electronics, plasma flood, stay stealthy for as long as they need it, convert, remote self-destruct borgs like walking bombs, can hide in the station using a borg, can raise electronics to fight, blow up pipes and gets free controles over everything on the station. Making an unlinked cyborg is easy when everything is burning.

if the AI has well and truly "won" already than who are you to complain because you can't death spiral the thing from 2 screens away using only two beakers and some ore?

**Comment by moltoretardo** [comment]
Honestly I don't think there's any chances this will get merged. Even Skyrat seems to disapprove it since it's blatant powercreep towards one of the already strongest antag.

**Comment by Poojawa** [comment]
tag: i ded

**Comment by YakumoChen** [comment]
I'll wait for a maintainer to say that before I come to that conclusion.

**Comment by Tupinambis** [comment]
I like the idea of EMP proof APCs, but it should really only apply to a select few APCs for the cost of points. That way it's a strength but one you have to sacrifice a different power for.

**Comment by MrJWhit** [comment]
Honestly this is a symptom of two problems:
1. EMPs are too easily obtainable by people who know things. It's just two materials that are grinded up, it's not something special.
2. EMPs are too binary of a result of, "fuck everything up" vs "not touched" on a raw linear scale.

I don't think this is a good bandaid either, but, that's me.

**Comment by ForrestWick** [comment]
I do agree EMPs are way too easy to get and way too black and white tbh

**Comment by timothyteakettle** [comment]
working on a pr currently to change emp severity to go from a binary 1/2 to 1-100 severity and it weakens with distance

**Comment by YakumoChen** [comment]
`// damage and destruction acts
/obj/machinery/power/apc/emp_act(severity)
    . = ..()
    if (!(. & EMP_PROTECT_CONTENTS))
        if(cell)
            cell.emp_act(severity)
        if(occupier)
            occupier.emp_act(severity)
    if(. & EMP_PROTECT_SELF)
        return
    lighting = 0
    equipment = 0
    environ = 0
    update_icon()
    update()
    addtimer(CALLBACK(src, .proc/reset, APC_RESET_EMP), 600)`

EMP severity doesn't matter with APCs. It's a flat power kill with a long reset timer.

**Comment by timothyteakettle** [comment]
it reduces power based off severity
also i am changing the timer to be based off severity in the new system

**Comment by YakumoChen** [comment]
It still feels like a largely shitty and un-combatable death to be EMP'd outside the AI sat, and I would assume a large EMP mix or an EMP grenade is going to have a large severity.

**Comment by timothyteakettle** [comment]
a large emp will have less effect than it used to, though yes, this won't entirely solve the (personally non-existent) issue of emps being too strong at killing AIs, but it'll make it harder

i'm tempted to look at rewriting the recipe to require slightly more effort than running to any departments lathe and printing uranium sheets out but i am scared it'd affect balance too much

**Comment by The-Sun-In-Splendour** [comment]
Almost as if EMPs are literally meant to be the thing used to murder AIs and borgs.
I ded pr, please close.

**Comment by Detective-Google** [comment]
the ion rifle no longer works on malf ais either 

congrats on removing the silicon hard counter from silicons 🥴

**Comment by YakumoChen** [comment]
If you're in range to ion it you're in range to laser the core, ions  still do direct damage to the AI core and disable turrets. I dont see your argument.

If you want to make ion bolts be somehow snowflake compared to EMP be my guest.

**Comment by silicons** [comment]
sorry but please find a more nuanced solution than just tossing emp ignore onto the apc.

**Pull request closed without merging**
