### PR TITLE
Unfucks the monophobia traits (Aswell as traits in general) with this one simple trick

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
One tab too much made the monophobia trait not work aswell as fucking traits in general, including but not limited to adding some very wonky stuff.
It unfucking these things has been tested locally, though I did not test on if the monophobia quirk works completely as intended now as this is out of scope for this PR.

## Why It's Good For The Game
Fix man good

## Changelog
:cl:
fix: Traits are no longer fucked
/:cl:

### CODE REVIEW

**Comment by TheSpaghetti** [comment]
Speedmerge.

**Review by ghost — APPROVED** [review]
**SPEEDMERGE PLEASE**

**Comment by TheSpaghetti** [comment]
Monophobia still doesn't actually give you the trauma for some reason.

**Comment by DeltaFire15** [comment]
Appears to be working on local, so I dunno what your issue is here.

**Pull request merged**
