### PR TITLE
Completely removes ERP 

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
All mechanical ERP has been completely removed, extending to arousal, genitals, vore, fetish items like fuzzy handcuffs, and dogborg sleepers (even their non-voracious variants). Lewd chemicals have been replaced with cement. KinkMate vendors have been replaced with bottled water vendors, because water is good for you.

## Why It's Good For The Game
ERP has long been a contented subject in the community, mechanical ERP even more so, because for as much as it theoretically enables, there's much it limits, too. ERP being allowed on a server tends to detract from non-erotic roleplay- people will often be unable to say much about their character beyond how said character serves their own fetishes, which isn't at all conductive to either gameplay or RP on Citadel as an MRP server. Even with that said, it's still fully possible to ERP without the burden of mechanical ERP on a codebase, which, even as there are infinite ways to disable being able to be mechanically ERPed in a way you don't want to be, still ends up causing more issues for consent and the realism of an excessive saturation of sexual themes in a workplace where it's explicitly illegal to have sex. Servers can and do have ERP exist without the mechanics supporting it, and people can typically vouch for this being the superior approach- see Sojourn. 

## Changelog
:cl:
del: ERP and vore mechanics
del: Medihound sleepers
tweak: Lewd chemicals have been replaced with cement
tweak: KinkMate vendors have been replaced with bottled water dispensers
admin: players who do not pass the age check are forced to eat cement when they were six
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
we kepler now

**Comment by The-Sun-In-Splendour** [comment]
I tought this was a aprils fools PR but I unironically agree

**Comment by ghost** [comment]
i mean i wouldn't miss any of it personally, first time i joined the server i thought the erp was reserved for the RP server  and not allowed in main
i don't care about it existing or not

**Review by DeltaFire15 — APPROVED** [review]
It passes CI so surely it'll be fine

**Comment by zeroisthebiggay** [comment]
>midnight passes
>april fools is now officially over
>pr is being maintained
>fc6

**Comment by HeroWithYay** [comment]
You forgot to remove dogborgs.

**Comment by ghost** [comment]
> You forgot to remove dogborgs.

but the dogborgs are cute and not necessarily horny

**Comment by moltoretardo** [comment]
It’s no longer april fools so I can unironically thumbs up this PR

**Comment by zeskorion** [comment]
Good job tira. You've solved ss13.

**Comment by PowerfulBacon** [comment]
You cant just delete the entire codebase like that

**Comment by kiwedespars** [comment]
based

**Comment by TheNeoGamer42** [comment]
the good ss13 ending

**Comment by The-Sun-In-Splendour** [comment]
THE BAD ENDING

**Comment by TheNeoGamer42** [comment]
this is so sad

**Comment by moltoretardo** [comment]
Never forget what the people truly wanted

**Pull request closed without merging**
