### PR TITLE
More lenient soft stamina combat, decentralized gun inaccuracy from combat mode.

### LINKED ISSUE #12245: Lighteater Doing Little Damage to Objects
## Round ID:
ID 22907

## Testmerges:
#12075: 'Field of Vision component.' by Ghommie at commit 226d0f111f
#12175: 'Adds a New map, Snow Taxi (A vgstation13 map port)' by Detective-Google at commit 4378a34ea7
#12217: 'The real fastmos: C++ monstermos port' by Putnam3145 at commit 86afd889f1

## Reproduction:
Become a nightmare and try hitting lights/APCs with lighteater.

- Lights take 1 - 3 hits to break
- APCs take 2 soft stamcrits (from solely swinging lighteater) and a couple more hits to break

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Replacing most "you are too tired to attack" stamina combat crap with attack damage/accuracy penalties and higher click delays.
Changed the way gun inaccuracy is calculated to penalize hastily fired shots versus sole enforcement of combat mode. This may undergo some tweaking as development goes on, but I believe it's not as crude as the former method.

Some actions such as baton stuns will remain unperformable while in stam crit to avoid turning the tide so easily. Capped the stam loss from weapon attacks to not push the user themself into total stamina crit (May allow it as development goes on).

Final changes, fairly minor ones, are the target and user combat mode checks not stacking together and leading to a 0.75x multiplier if both are out of combat mode, and the removal of the 0.5x modifier if attacking an object outside of combat mode, which is quite unnecessary on second thought.

## Why It's Good For The Game
I have never been a fan of the current 'soft stamina crit' design translating into hapless sitting ducks, it leaves other players with no counterplay to pull off aside adrenals, magic and other edge cases, rather then crippling them into slightly troublesome pushovers, which is what I'm trying to accomplish here. This will close #12245.

## Changelog
:cl:
balance: Made stamina combat a bit more lenient, you should now be able to use weapons/guns while soft critted, while incurring into damage penalties, inaccuracy and longer attack delays.
balance: Modified the way gun inaccuracy is calculated to take in consideration the time passed since your last click (a few other actions can cause delays, but most of them are clicks), take a second or two to aim your shots if you want no spread, Combat mode helps, but not as much.
balance: The item attack combat mode checks for user and target do not stack anymore and lead to a 0.75x modifier when both parties are not in combat mode.
balance: Removed the combat mode check for object damage from items.
/:cl:

WIP, gotta test it.

### CODE REVIEW

**Comment by silicons** [comment]
based ghom out here saving citadel combat

**Comment by necromanceranne** [comment]
Don't forget the unarmed attack multipliers in species and martial arts.

**Comment by Linzolle** [comment]
very in favour of this

**Comment by deathride58** [comment]
These are pretty good changes in general, though I'm *extremely* iffy on keeping soft stamcrit entirely threshold-based, as having hardset thresholds makes balance fairly wonky since there's a hardset line where crossing it by a single decimal will result in you suffering the full brunt of the penalties. As of right now, I believe that the majority of the issues with the combat rework stem from combat being centered primarily around static thresholds.

**Comment by Ghommie** [comment]
@necromanceranne I'll get to fisticuffs later, Thanks for tellings. This is ready by the by

**Review by silicons — APPROVED** [review]

**Comment by silicons** [comment]
iffy on gun aiming but this is being held up too long

**Pull request merged**
