### PR TITLE
Remove Events that Strait up Kill You For Having Bad RNG

### PR DESCRIPTION
**Pull request by ktoma36**
## About The Pull Request

As the title says this removes the three following events. Appendictis, Heart Attack, Brain Trauma

## Why It's Good For The Game

These events are not fun or interesting for anyone involved, kills antags (there is nothing in place stopping these from effecting antags), have no way to be countered, will just kill you if you're unable to get to medical (Good luck mining when you suddenly are hard stunned by puking while fighting a goliath or collapse from a heart attack), and just overall poorly designed events. 

I do not see the argument of 'these give medical something to do' as valid at all since these events come at the express expense of someone else's round. An engineer is trying to do a massive full round project setting up some madman machine? Whoops sorry you got brain trauma and will be spending 20-30 minutes in medical as you go unlucky and rolled 'special' on the brain trauma scale. Out exploring deep space and fighting alien creatures? Oh sorry you got appendictis, got puke stunned, and have been mauled to death by mobs because of a 'fun' RNG event. You roll traitor for the first time in a month with hijack? Oh man bummer you had a heart attack and the doctor's looked through your backpack while they were resuscitating you. Now you're in perma (or you know cremated after killing a bunch of people).

## Changelog
:cl:
del: Removes Events that just kill you
/:cl:

### CODE REVIEW

**Comment by Putnam3145** [comment]
special surgeries are actually good for you though??

**Comment by ktoma36** [comment]
What do you mean by special surgeries? This only removes the random events that just forces people to have these conditions not the conditions themselves

**Comment by timothyteakettle** [comment]
can we stop the trend of making PRs that just disable events because you don't like them
this just increases the chances of other events happening dramatically and gives medical even less to do
this is hugbox to the extreme

**Comment by timothyteakettle** [comment]
following up on this, if you want to make an actually useful change, copy how the brain trauma event blacklists anyone but those on the station z level getting hit by it, onto the other two events, and add an antag datum check to all 3 if you're really that paranoid over antags getting hit by them

**Comment by UncleBourbon** [comment]
https://user-images.githubusercontent.com/27906735/154848488-1318d956-8ffe-47ef-9279-8b78e351198e.mp4

**Comment by CoreFlare** [comment]
adding onto this, this also doesn't do anything about other """round destroying""" events like rad storm. this isn't made to alter gameplay, this is just made because you don't like these random events. as teak said there are better ways to do this.

**Comment by DJKouta** [comment]
I can understand Heart Attack, but it's pop-locked
Sure if you're on lavaland and you get mauled, it sucks, but with that pop people normally check on miners. Most people that explore space get a clone scan. 

The other two, man.
If you're dying to Appendicitis, there are much bigger problems at play here.

**Comment by ktoma36** [comment]
> I can understand Heart Attack, but it's pop-locked
> 
> Sure if you're on lavaland and you get mauled, it sucks, but with that pop people normally check on miners. Most people that explore space get a clone scan. 
> 
> 
> 
> The other two, man.
> 
> If you're dying to Appendicitis, there are much bigger problems at play here. 

Appendicitis hits you with stuns when you puke, brain damage actively makes you hurt yourself to the point you need a helmet to not slam your head into airlocks. There is no skill involved with getting hit with an rng event

> following up on this, if you want to make an actually useful change, copy how the brain trauma event blacklists anyone but those on the station z level getting hit by it, onto the other two events, and add an antag datum check to all 3 if you're really that paranoid over antags getting hit by them

This would be only a bandaid fix that wouldn't even fix the issue. The issue with these events is that they *are not fun to deal with by anyone* nor can they be prevented by player action. Crying hugbox won't change that issue, if you want I can add in some more events that drop mobs on station to balance the hugbox quota.

> adding onto this, this also doesn't do anything about other """round destroying""" events like rad storm. this isn't made to alter gameplay, this is just made because you don't like these random events. as teak said there are better ways to do this.

You're right, I don't like these events. I much prefer rad storms, meteor showers, space vines, literally anything that is actually fun to interact with. The station falling apart around you is dynamic and interesting. Getting random brain damage or appendicitis is just a 20-30 minute time sink depending on if there's a medical doctor on shift that isn't dead/erping/dealing with something else. 

For those suggesting I just Frankenstein a bunch of z level checks and antag checks to stop people from getting hit with this stuff off station/antags not getting hit are missing the point. Those whom argue this will make other events happen more frequently **good**, any other event is more fun to deal with by everyone involve _including broken lights in my opinion_

**Pull request closed without merging**
