### PR TITLE
sweaters for taur fags

### PR DESCRIPTION
**Pull request by katnep**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

:cl: sweaters for the sweater fags
add: Added sweaters for the taur fags so they can have a jumpsuit and not look "wrong"
/:cl:

[why]: # because someone was whining about it in suggestions and so i can still claim im a coder

### CODE REVIEW

**Comment by TalkingCactus** [comment]
That's a lot of changes for 1 line of actual difference.

You forgot the refills, too.

**Comment by katnep** [comment]
what do you mean by "i forgot refills", im kinda not clear on how it works

**Comment by TalkingCactus** [comment]
See comments [here](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/code/game/objects/items/weapons/vending_items.dm).

**Comment by katnep** [comment]
do i just boost the amount of charges it supplies or something

**Comment by TalkingCactus** [comment]
Yes, by roughly 1/3 of what you added rounded up. You'll also want to do this on a fresh branch created from the Citadel-Station-13 Master branch. Stats for this branch say: `This branch is 2 commits ahead, 1051 commits behind Citadel-Station-13:master.` which explains why you have conflicts and a strange difference.

**Pull request closed without merging**
