### PR TITLE
autolathe .357 speedloaders->bullets, surplus rifle bullets in hacked lathe

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
replaces .357 speedloaders in autolathes with individual .357 bullets (costs less total metal per speedloader's worth of bullets) and adds individual surplus rifle bullets when lathe is hacked (same ammo used by surplus, mosin, and improvised rifle, costs more total than clips from seclathe and individual loading). Also readds speedloader to illegal tech since they're no longer in lathe.

## Why It's Good For The Game
you now have a reason to buy .357 speedloaders from the uplink if you're using the revolver, but is not necessary. improvised rifles are now feasible to use, similarly to improvised shotguns. makes seclathe better than autolathe for printing some ammo.

## Changelog
:cl:
balance: .357 speedloaders in autolathes are now individual bullets instead, speedloaders are now illegal tech, costs less total metal to make 7 bullets than a previous speedloader. 7.62mm bullets in autolathe when hacked and costs more metal to make 5 7.62mm bullets than getting a clip from the seclathe.
tweak: mentions that you can refill speedloaders on .357 uplink description
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
More or less what tgstation did too, good.

**Review by Putnam3145 — APPROVED** [review]

**Comment by ShadeAware** [comment]
_improvised rifles are now feasible to use_

👀

**Comment by ghost** [comment]
really gonna approve and not merge, huh Put Nam? huh? huh Put Nam?

honk

**Comment by ghost** [comment]
also forgot to mention hard nerfs detective .357 as a side effect hjonk

**Pull request merged**
