### PR TITLE
Twitch Plays: Clown Car

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Adminbus only, not obtainable otherwise.

Adds a component for polling ghost movement. When a ghost orbits something with it, it captures the ghost's movement if the ghost isn't trying to jump away, and adds it to a vote.

Adds a clown car that polls this 5 times a second to move.

## Why It's Good For The Game

It probably isn't.

## Changelog
:cl:
add: Twitch Plays: Clown Car
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
based

**Comment by TheObserver-sys** [comment]
Now this is podracing!

**Comment by BlackMajor** [comment]
Why would you do this.

**Comment by BlueWildrose** [comment]
Ghost-controlled clown cars sadly can't open airlocks.

That should change. While we're at it, somehow add a means for manually loading people staying still maybe.

**Review by DeltaFire15 — APPROVED** [review]

**Pull request merged**
