### PR TITLE
vehicle rider headshots

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
vehicles (secways, ATVs, etc) now default to dinking occupant(s) in the face with bullets if you're aiming for head/chest
## Why It's Good For The Game
nice bullet deflect idiot
## Changelog
:cl:
balance: Vehicle riders can now, by default, get shot in the face and/or chest.
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
Bye bye cringue vehicule meta

**Comment by rossark** [comment]
Ok, but what if I DONT have a head?

**Comment by Tupinambis** [comment]
Good. Vehicle abuse is fucking annoying.

**Comment by Ludox235** [comment]
Man I love when my mall cop secway protects me from a fucking machine gun

**Comment by lolman360** [comment]
give `/obj/vehicle/sealed` `enclosed = TRUE` btw

**Pull request merged**
