### PR TITLE
TGUI Next vendors plus spritesheet port from TG

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Makes vendors prettier by making their interface TGUI Next, plus makes icons actually work without needing a shitty hack.

## Why It's Good For The Game
Bad hack bad, pretty UI good

## Changelog
:cl:
add: TGUI nextifies vendor UIs
tweak: Vendor item icons now use a spritesheet
del: Nanotrasen has removed the ability to put bills in vendors.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Works, but theres something TGUI related i need to fix first

**Comment by Arturlang** [comment]
Actually, gonna leave the spritesheet stuff for https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11122/

**Comment by Linzolle** [comment]
I wonder if the tgui next stuff would fix some of the issues with spritesheets I'm having..?

**Comment by Arturlang** [comment]
Works perfectly fine locally, whats the issue?

**Comment by Linzolle** [comment]
honestly I think you're just going to want to put the changes to cigs_lighters.dm and misc_special.dm from #11122 into this, then 11122 can just be closed and everything will be in this one PR.

**Comment by Arturlang** [comment]
Got it, will do

**Comment by Arturlang** [comment]
Travis linter died, not my fault

**Comment by Linzolle** [comment]
don't forget to remove the if (!icon_state) in the vape's Initialize, or else it will always be black.

**Review by silicons — APPROVED** [review]

**Review by Linzolle — APPROVED** [review]

**Comment by Arturlang** [comment]
I need to properly add a way to remove and add coins and bills for the vendor UI, since TG doesnt have that

**Comment by Arturlang** [comment]
Is dish_quants and its related things something we want to keep around? TG doesnt have it and it seems to have been added in a mirror PR, curiously enough

**Comment by Arturlang** [comment]
Had to remove the ability to put in bills due to a bug i couldnt for the life of me figure out, anyways it works, is ready

**Review by silicons — APPROVED** [review]

**Pull request merged**
