### PR TITLE
Zoombas

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Ports Zoomba cyborg skins from VOREStation

## Why It's Good For The Game

customization, zoombas are nice.
if anyone wants to argue about hitboxes we can probably figure something out but I think it's fine for now(tm)

## Changelog
:cl: kevinz000 (port from VOREStation)
imageadd: Ported zoomba skins for cyborgs.
/:cl:

### CODE REVIEW

**Comment by MrJWhit** [comment]
Isn't Roomba a copyrighted term?

**Comment by silicons** [comment]
@MrJWhit oh, it's renamed in the actual files

**Comment by silicons** [comment]
good reminder

**Comment by silicons** [comment]
ended cl/body too

**Review by Linzolle — APPROVED** [review]

**Pull request merged**
